### ISSUE TITLE
Question: Vertical sidebar and 3 breakpoint states

### ISSUE THREAD

**Issue by njannink** [Megabit/Blazorise#1036]
Hi I'm using the new vertical sidebar, but we need to display it in 3 different states based on the breakpoint:

1. Collapsed on mobile
2. Small on tablet
3. Wide on desktop

I have been trying a bit with the different options in the demo project, but I cant get this to work. Any ideas?

**Comment by njannink** [comment]
We would like it to work it the same as for example the sidebar in VSTS online
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3843546/85925429-0b0c1800-b85e-11ea-8293-cc9c3b1e2ab2.gif)

**Comment by MitchellNZ** [comment]
Currently there is no way to do this with out of the box config.
I also think this would be quite a good feature, and I will add it to the list of other outstanding vertical bar features.

As a workaround, it shouldn't be too difficult to add some custom CSS to achieve this.
I would recommend using `BarMode.VerticalInline` + `BarCollapseMode.Small` + `Breakpoint.Tablet` and then handling mobile with a `@media` query to set the bar (e.g. `.b-bar-vertical-inline`) to either `display: none;` or  `min-width: 0; width: 0;`

Hope this helps in the meantime!

**Comment by njannink** [comment]
Yes I was already investigating in this direction. Need to figure out how to get the horizontal navbar above the vertical sidebar

**Comment by MitchellNZ** [comment]
@stsrki was mentioning in issue https://github.com/stsrki/Blazorise/issues/1038 about this.

However I was just trying to test this myself and think there might be a couple of bugs with it..
I will comment on the linked issue with my findings.

**Comment by stsrki** [comment]
Closing as we don't have plans for this feature.
