### ISSUE TITLE
Bar Dark/Light Theme

### ISSUE THREAD

**Issue by imtrobin** [Megabit/Blazorise#1050]
Hi, I have a few questions about Bar Dark/Light theme.

1. Are we supposed to switch between them ourselves? I notice other themes use the lumanice value to switch.

2. In sample, I remove the Background for Bar header, it seems not be affected by LightTheme

`<Bar Style="height: 64px;" Breakpoint="Breakpoint.Desktop" ThemeContrast="ThemeContrast.Light">`

![image](https://user-images.githubusercontent.com/531606/86094494-2f2c5b00-bae3-11ea-8117-3a83f8fd705f.png)

![image](https://user-images.githubusercontent.com/531606/86094546-40756780-bae3-11ea-9c6a-1ea6461caec5.png)

3. When I select brown, it seems it does not switch (with background set to primary)

![image](https://user-images.githubusercontent.com/531606/86094883-b11c8400-bae3-11ea-8f1d-46440e83bc64.png)

**Comment by stsrki** [comment]
1. For now you need to switch them by yourself.
2. When you remove background it will use default style that comes with bootstrap css
3. I still need to calculate BarItem text colors based on the background. The same as for button and other component.

**Comment by imtrobin** [comment]
3. Rather than calculating, I prefer if there is a way for me to set the color directly.

I tried TextColorOption, ColorOption, it doesn't set the text color in buttons/text.

I don't find the dark/light theme useful at blazor level. Because in my app, I also have other third party libraries to theme so I can't rely on just Blazorise theme.

**Comment by stsrki** [comment]
`TextColorOptions` is used only for textual component, like `Paragraph`, `Text`, etc.

Maybe `LuminanceThreshold` will help you to control the calculated contrast of the text on `Button` element?

**Comment by imtrobin** [comment]
Hmm, I do not understand the magic formula used here in calculating luminance

```
//Counting the perceptive luminance - human eye favors green color... 
luminance = ( 299 * color.R + 587 * color.G + 114 * color.B ) / 1000d;
```

As you can see, it's not quite right in above when it is brown. That said, I would still prefer a way that I can set the color directly instead of above magic formula

**Comment by stsrki** [comment]
The thing with calculating text color based on background color is to give the best possible reading contrast. Not every color is best suited for reading. The function above is basically used to figure out whether light or dark color need to be applied to the text, based on the background. And will `LuminanceThreshold` you can have some control over it.

**Comment by imtrobin** [comment]
![image](https://user-images.githubusercontent.com/531606/86296618-d1eff100-bc2b-11ea-8a28-0c3cdba81bf6.png)

I'm referring to this text, how to set this color. It doesn't change. I actually use a image background so I want to set the text color directly. It seems to be using text-dark in scss. It would be great if I can set it directly like how ThemeBarOptions

**Comment by stsrki** [comment]
That one still cannot be changed through theme. You will need to use CSS.

**Comment by imtrobin** [comment]
Ok, I changed css .bar but it's not ideal as I use buttons in some places as icons and I want to choose different color. Something like TextColor would be good.

<Button  Color="Color.Primary" TextColor="Color.Whiite" >
