### ISSUE TITLE
Enhancement: Extra dropdown directions or don't draw dropdown outside visible area

### ISSUE THREAD

**Issue by njannink** [Megabit/Blazorise#1054]
I think the following directions should be added to the dropdown or we must make sure that the dropdown isn't drawn outside the visible area of the screen

- Direction.TopRight
- Direction.TopLeft
- Direction.BottomRight
- Direction.BottomLeft

**Comment by David-Moreira** [comment]
I believe this is an old issue. we already have directions and use popper behind the scenes to relocate the dropdown to proper visible areas. Currently migrating to floating ui #4887.

Closing issue.
