### ISSUE TITLE
InputMask Component

### ISSUE THREAD

**Issue by ricardoromaobr** [Megabit/Blazorise#1066]
Blazorise is great there is alot of input components 
Date, Numeric and Text, but Mask at the moment is not good for real business format.

A think that is time to  a better solutions to input with the mask feature.

**Comment by ricardoromaobr** [comment]
How it would be start, who would be base  class for that component?
Would be the TextEdit?
Because it need coming with validations like the others input component. 
I start to look in the input component and  I see that are so many inherits level at the input components
Where would be good point of the start to do it?

**Comment by stsrki** [comment]
I would say it depends. But to make it more general maybe the best is to place it into TextEdit as that is most suitable for mask feature.

**Comment by ricardoromaobr** [comment]
I start an implementation of the MaskEdit component that inherits from TextEdit. 
And I use the EditMask that is inherits from the TextEdit. 
I'm thinking to create a property IsCurrency, if true only number 
will be accept. Somes examples:
```html
     <MaskEdit @ref="@phoneNumber" EditMask="XX+ (XX) XXXXX-XXX" />
```
When using X any caracter will be accept in place of X caracter mask. 

it is already working.

I'm thinking to add to EditMask a caracter 9, that only number digit would take place. 

```html
     <MaskEdit @ref="@zipcode" EditMask="99999-999" />
```
and maybe for currency
```html
     <MaskEdit @ref="@itemPrice"  IsCurrency="true" />
```
In this case the MaskEdit will be aligned on right and  make currency mask. Maybe 
is not necessary a mask the property EditMask is ignored.

I thinking to start as simple as possible and new versions do more stuffs 

Please some suggestion?

**Comment by stsrki** [comment]
@ricardoromaobr I googled a little and I found this https://formidableforms.com/knowledgebase/format/. I think it would make things better than just having **9** or **X**.

Also similar https://coreui.io/docs/2.1/components/masked-input/

**Comment by stsrki** [comment]
- https://github.com/nosir/cleave.js
- https://github.com/RobinHerbots/Inputmask
- https://github.com/text-mask/text-mask

**Comment by stsrki** [comment]
@ricardoromaobr The InputMask component will be available in 0,9,5 :)

**Comment by begandroide** [comment]
Hi! @stsrki I'm using `0.9.5-preview2.1` and ColorPicker and InputMask are not recongnized by the framework and is not rendered in UI. I'm missing something?

![image](https://user-images.githubusercontent.com/22018004/142211957-7fa743ef-9119-4eba-8f5b-449e6512b599.png)

![image](https://user-images.githubusercontent.com/22018004/142211920-2230f7b5-e449-489a-bba2-0349478d5312.png)

**Comment by begandroide** [comment]
My apologizes, i had previous version in nuget packages. I upgraded to `0.9.5` and install dependencies for net core 6 but console shows this errors: Maybe abp 5.0.rc is not compatible with this version?

![image](https://user-images.githubusercontent.com/22018004/142217121-4f6df216-dd83-40a3-b895-5ed59324d1c5.png)

**Comment by stsrki** [comment]
Yes, probably they need to upgrade their projects to the latest version. The 0.9.5 only got out two days ago.

**Comment by begandroide** [comment]
thanks you @stsrki!
