### ISSUE TITLE
Question How to change chart axis color

### ISSUE THREAD

**Issue by imtrobin** [Megabit/Blazorise#1067]
Hi, I'm trying to change the chart axis color, I do this, it is null object reference.

```
        async Task                                                          HandleRedraw ()
        {
            await lineChart.Clear()
                                    .ConfigureAwait (false);
            await lineChart.AddLabelsDatasetsAndUpdate (Labels, GetLineChartDataset())
                                                                                    .ConfigureAwait (false);
            lineChart.Options.Scales.YAxes.ForEach (x => x.ScaleLabel.FontColor = "#ff0000"); // Null object error
      }
```

I put on OnAfterRenderAsync, it also null object error.

I'm thinking of using the Labels/Dataset, but they are protected, not public

```
linechart.Labels   .. // protected, not public
linechart.Datasets   .. // protected, not public
```

**Comment by stsrki** [comment]
Based on this answer https://stackoverflow.com/questions/41958548/chartjs-change-axis-line-color it should be something like this:

```cshtml
<LineChart @ref="lineChart" TItem="double" Options="@options" />

@code{
    ChartOptions options = new LineChartOptions
    {
        Scales = new Scales {
            XAxes = new List<Axis> {
                new Axis {
                    GridLines = new AxeGridLines {
                        Color = "#131c2b"
                    }
                }
            },
            YAxes = new List<Axis> {
                new Axis {
                    GridLines = new AxeGridLines {
                        Color = "#131c2b"
                    }
                }
            }
        }
    };
}
```

**Comment by imtrobin** [comment]
Thanks but it didn't work

```
<LineChart @ref="lineChart" TItem="double" Options="@options"/>

LineChartOptions options = new LineChartOptions
        {
            Scales = new Scales {
                XAxes = new List<Axis> {
                    new Axis {
                        GridLines = new AxeGridLines {
                            Color = "#ff0000"
                        }
                    }
                },
                YAxes = new List<Axis> {
                    new Axis {
                        GridLines = new AxeGridLines {
                            Color = "#00ff00"
                        }
                    }
                }
            }
        };
```


![image](https://user-images.githubusercontent.com/531606/86425956-13aa9580-bd19-11ea-97d9-68616cfed61f.png)

**Comment by imtrobin** [comment]
I looked at blazorise.chart.js, the options object seems to be passed as list, but the link you gave me is an array

![image](https://user-images.githubusercontent.com/531606/86437152-78281d80-bd36-11ea-872d-219ad58d9090.png)

![image](https://user-images.githubusercontent.com/531606/86437231-a0b01780-bd36-11ea-9af9-8f5422f79e9a.png)

**Comment by stsrki** [comment]
This works

```cshtml
<LineChart @ref="lineChart" TItem="double" Options="@options" />

@code{
    LineChartOptions options = new LineChartOptions
    {
        Scales = new Scales
        {
            XAxes = new List<Axis> {
                new Axis {
                    GridLines = new AxeGridLines {
                        Color = "#ff0000"
                    }
                }
            },
            YAxes = new List<Axis> {
                new Axis {
                    GridLines = new AxeGridLines {
                        Color = "#00ff00"
                    }
                }
            }
        }
    };
}
```

![image](https://user-images.githubusercontent.com/900302/86440916-9debfd00-bd0b-11ea-9bd9-0db986af963c.png)

**Comment by imtrobin** [comment]
That's really weird, I'm using demo bootstrap RC, didn't work in Opera and Edge.

**Comment by stsrki** [comment]
Tried RC demo in Edge and it also works

![image](https://user-images.githubusercontent.com/900302/86449118-fa551980-bd17-11ea-84ba-eb2b13576a66.png)

**Comment by imtrobin** [comment]
Hmm, I updated to latest source, git check modification shows only these two changes, erased cache, delete bin/obj folder, full rebuild, but still not working. 

![image](https://user-images.githubusercontent.com/531606/86459397-4c6a5f00-bd59-11ea-87bc-889b645b1150.png)

What did you do differently?

**Comment by stsrki** [comment]
Nothing actually. Those are the only changes I have done in the demo app.

**Comment by imtrobin** [comment]
I tried debug/release, material, all no change. No errors in console output either.

![image](https://user-images.githubusercontent.com/531606/86467981-09b08300-bd69-11ea-9a70-3464fe3e8ac6.png)

**Comment by imtrobin** [comment]
In another test project, I'm using another ChartJS library, and I could customize font colors fine so its not my system.

https://github.com/mariusmuntean/ChartJs.Blazor

I also noticed you are not using latest version of chartjs, it looks like 2.9.3 now

**Comment by stsrki** [comment]
So, I included latest version of chartjs `<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>`, and it works. I really have no idea why it should not work on your system.

**Comment by imtrobin** [comment]
No idea, can you please send me a release bin and I try to run on my side?

**Comment by stsrki** [comment]
[Debug.zip](https://github.com/stsrki/Blazorise/files/4873632/Debug.zip)

It should be on visible on `http://localhost:8211/`

**Comment by imtrobin** [comment]
Thanks, I noticed something weird from your Debug.zip

1. you are running Blazorise.Demo.Bootstrap from what I see in the launchsettings.json , it is webassembly, but the build is .netcoreapp3.  Webassembly should be .netstandard2.1

![image](https://user-images.githubusercontent.com/531606/86523557-d8d36980-bea0-11ea-9f41-b8b39384a8fb.png)

Since the beginning, I couldn't get Blazorise.Demo.Bootstrap to run, It will give me this

![image](https://user-images.githubusercontent.com/531606/86523523-64002f80-bea0-11ea-8f71-b463984063a4.png)

So I'm using the server hosted Blazorise.Demo.Bootstrap.RC instead. My own project where I setup webassembly with blazorise, it works fine.

2. Your say it's port 8211, the launchsettings.json is saying 7678/7679. The 8211 port is in launchsettings on Blazorise.Demo.Bootstrap.Server

![image](https://user-images.githubusercontent.com/531606/86523653-dde4e880-bea1-11ea-985a-d89d80cc7a5e.png)

It seems you are not running from master branch, I'm running directly from master branch,

**Comment by stsrki** [comment]
- Blazorise.Demo.Bootstrap is just WebAssemly project, and it is set for `netstandard2.1`. It cannot be run directly.
- Blazorise.Demo.Bootstrap.Server is the host application for WebAssembly that runs on IIS and it is using Blazorise.Demo.Bootstrap as a client app. That one is set for `netcoreapp3.1`. 
- Blazorise.Demo.Bootstrap.RC is the server-side Blazor app that runs fully on `.netcoreapp3.1`

**Comment by imtrobin** [comment]
I don't understand, why can't we run webassembly directly? In my own project which is netstandard2.1, I can run fine and Publish to a folder and deploy.

**Comment by stsrki** [comment]
You have probably selected WebAssembly project without net core part when you have first created your project. Blazor comes with three project templates. WebAssembly, WebAssembly + NetCore host, and Blazor Server.

**Comment by imtrobin** [comment]
Yes, I did that in that project. I want webassembly client only. I created new .net core host project, as you can see, the client is using netstandard2.1.

![image](https://user-images.githubusercontent.com/531606/86534419-ea515b80-bf0a-11ea-96ef-8ffd26ed2cef.png)

How did you get client app as netcoreapp3.1

**Comment by stsrki** [comment]
Check your `BlazorApp3.Server`. It should say `netcoreapp3.1`

**Comment by imtrobin** [comment]
Yes, the server is netcoreapp3.1. So what did you pass me in Debug.zip? It looks like a server and client. How  do you run it? I run the exe and the localhost is not valid

![image](https://user-images.githubusercontent.com/531606/86546843-464acd00-bf69-11ea-9650-f407aca30f0e.png)

**Comment by stsrki** [comment]
I already mention it, you should run it on `http://localhost:8211/`

**Comment by imtrobin** [comment]
![image](https://user-images.githubusercontent.com/531606/86593559-0d8e1080-bfc8-11ea-8077-52d338c89670.png)

**Comment by stsrki** [comment]
It seems `http://localhost:8211/` worked for me last time because I had Blazorise solution already opened. Can you run `Blazorise.Demo.Bootstrap.Server` from VisualStudio if you already didn't?

But anyways I think we stranded far from original problem.

**Comment by imtrobin** [comment]
I agree. I'm not sure what the Debug.zip you pass me will do. If I run Blazorise.Demo.Bootstrap.Server from Visual studio, the IIS Express is tied to that. I replace the bin folder and no difference.

What I really wanted was a Published webassembly build from you, so I can run it on a local webserver to check.

**Comment by imtrobin** [comment]
So I try the PieChart, and it seem that the Options are not completely mapped? Eg.

![image](https://user-images.githubusercontent.com/531606/87063406-e7bf7080-c240-11ea-98b7-85c24685d2dd.png)

E.g Legend has Labels object that can customize color but I don't see it in

![image](https://user-images.githubusercontent.com/531606/87063617-2fde9300-c241-11ea-9e39-6d1ead530ee9.png)

![image](https://user-images.githubusercontent.com/531606/87063775-5dc3d780-c241-11ea-8b25-e49c0438501a.png)


https://www.chartjs.org/docs/latest/configuration/legend.html#legend-label-configuration

**Comment by stsrki** [comment]
Could be they added more options for `Legend` in the latest versions of chartjs. It's fairly easy to add new fields.

Btw, do you still have original problem with axis color?

**Comment by imtrobin** [comment]
Yes, not resolved. I'm trying other parts of chartjs to learn about it.
