### ISSUE TITLE
Charts.Streaming refresh event problem with multiple datasets in single chart

### ISSUE THREAD

**Issue by intiharj** [Megabit/Blazorise#1088]
When adding a second dataset to a streaming chart, the framework seems to call the refresh event handler for the second dataset only for both datasets.

**To Reproduce**
Attached project which takes the example in the docs and adds a second dataset.  NB that OnHorizontalLineRefreshed_2 is called for both dataset refreshes, and OnHorizontalLineRefreshed is never called.  I couldn't locate the problem, but perhaps it has something to do with calling IndexOf inside the foreach in ChartStreaming<TItem>.Refresh()?  Not sure if IList<T> order is guaranteed.

**Expected behavior**
The Refreshed event callback should call the correct handler specified in the ChartStreaming component instance.
[LiveChartTest.zip](https://github.com/stsrki/Blazorise/files/4876564/LiveChartTest.zip)

**Comment by stsrki** [comment]
Should be fixed in the latest version.
