### ISSUE TITLE
Bootstrap 5 Provider

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#1103]
This will be tracking ticket for planning of migration to Bootstrap 5. 

### Links:

- https://v5.getbootstrap.com/docs/5.0/migration/
- https://blog.getbootstrap.com/2020/06/16/bootstrap-5-alpha/
- https://hackernoon.com/bootstrap-5-basics-85113ujs?source=rss

### Updates

- https://blog.getbootstrap.com/2021/08/04/bootstrap-5-1-0/

### Extras

- https://www.sitepoint.com/bootstrap-5-new-features-examples/

**Comment by ParadiseFallen** [comment]
waiting for it with love

**Comment by swaipa** [comment]
Hi Blazorise team

Is this in a current road map?

Will it be in a near future?

**Comment by stsrki** [comment]
It will probably be in 0.9.5, which should be the final release before v1.0. At least that is the plan.

**Comment by michaelongithub** [comment]
Would this also mean for your icon extension to move to the bootstraps own (rel) new icons collection   (away from font awesome) ?

**Comment by stsrki** [comment]
@michaelongithub Yes, it was the idea also. I was waiting for icons to grow in numbers, but seeing it now I think they're ready :) https://icons.getbootstrap.com/

**Comment by stsrki** [comment]
Seems to me the time to start with migration is here :) 

https://blog.getbootstrap.com/2021/05/05/bootstrap-5/

**Comment by WillianGruber** [comment]
V5.1 will add a skeleton component. Maybe update to it so we can have standard skeleton? Maybe easier implementation than the other ticket

**Comment by stsrki** [comment]
I still need to support all the providers. And bootstrap4 is still going to be supported as it is still the most used framework.

**Comment by hikalkan** [comment]
@stsrki what about the status of this issue? We've completed the bootstrap 5.0 migration for the ABP Framework and waiting for the Blazorise :)

**Comment by stsrki** [comment]
Hi @hikalkan, already done in ABP? :)

Bootstrap 5 is next on the list. We're probably going to start working on it next week.

**Comment by hikalkan** [comment]
@stsrki it is basically done: https://github.com/abpframework/abp/pull/9877 :)

Thank you for the update.

**Comment by stsrki** [comment]
@hikalkan Cool. So is BS5 #2928. We're just finishing final optimizations and then we will release a preview on the MyGet feed.

**Comment by stsrki** [comment]
Blazorise 0.9.5 preview is published. Migration guide can be seen at:

https://preview.blazorise.com/news/release-notes/095
https://preview.blazorise.com/docs/usage/bootstrap5

Please note that there are some breaking changes regarding the async methods.

**Comment by hikalkan** [comment]
You're great @stsrki :) We will check these.

**Comment by maliming** [comment]
> There doesn't appear to be a listing for the Blazorise.Bootstrap5 provider package on the MyGet feed.

Same for me.

**Comment by stsrki** [comment]
Sorry guys. In a hurry, I forgot to update NuGet build script. It is fixed now and `Blazorise.Bootstrap5` is up on MyGet.
