### ISSUE TITLE
Data grid initial sort direction is not working

### ISSUE THREAD

**Issue by SvenNav** [Megabit/Blazorise#1104]
This is a duplicate of issue #807. In #807 there's stated that the issue is fixed but for me, the initial sort direction is still not working. The sorting arrow is showing the right direction but the data itself is not sorted. I'm using Blazorise and Blazorise datagrid v0.9.1.1

![image](https://user-images.githubusercontent.com/4492615/86783717-f8b18b80-c060-11ea-91fe-996a66aad881.png)

**Comment by jffaust** [comment]
I have the same exact problem. Arrow shows the right initial direction but the data is not sorted.
I'm using version `0.9.1.2`
![image](https://user-images.githubusercontent.com/4367222/95004941-19d23b80-05c0-11eb-9321-0a4b444a1c98.png)
