### ISSUE TITLE
Add option to disable text-transform: uppercase in material tabs

### ISSUE THREAD

**Issue by WillianGruber** [Megabit/Blazorise#1107]
Hi,

Comparing the Tabs page for all providers, I noticed the tab headers are always uppercase (```text-transform: uppercase```) in material.
Could ```text-transform: none;``` be included in blazorise.css?

**Comment by stsrki** [comment]
This is the default Material behavior so it makes sense not to touch it. If needed, it can be overridden by out text utilities on each component.
