### ISSUE TITLE
Use FAST framework

### ISSUE THREAD

**Issue by codeclash** [Megabit/Blazorise#1116]
I just stumbled over Microsoft's new [FAST Design](https://www.fast.design/) and it seems this could actually be the underlying glue for the different designs you provide (bootstrap, material, bulma, etc.) via design providers. 

Intro Video [on FAST Framework via .Net Community Standup ](https://www.youtube.com/watch?v=sYTH_xYH3iA&list=PL1rZQsJPBU2St9-Mz1Kaa7rofciyrwWVx&index=0) - Start at 13:48

Just want to raise awereness, no expectations :-)

**Comment by stsrki** [comment]
Might be worth looking into it at some point. Thanks

**Comment by damianog** [comment]
Hi, it seems Microsoft started to write a simple wrapper of FAST controls https://github.com/microsoft/fast-blazor

**Comment by stsrki** [comment]
After further investigation, we figured that FAST lacks many features and components that are possible in other frameworks but not in FAST. As a result, it would be almost impossible to properly integrate with Blazorise. We would have to implement most of the stuff on our own. So, closing this now.
