### ISSUE TITLE
New item's context.CellValue value is not the Select/SelectList's first option's value.

### ISSUE THREAD

**Issue by bestpika** [Megabit/Blazorise#1119]
**Describe the bug**

When using `context.CellValue` in EditTemplate's Select/SelectList, if new an item then doesn't change the selected index and save,
I can't get the right value (first option's value) in the callback item.

**To Reproduce**

1. New item.
1. Save.

**Expected behavior**

```C#
public class Data {
    public int id { get; set; }
    public string name { get; set; }
}
```

```C#
<EditTemplate>
    @{
        <SelectList Data="@data"
                    ValueField="@(x => x.id)"
                    TextField="@(x => x.name)"
                    SelectedValue="@context.CellValue"
                    SelectedValueChanged="@(v => context.CellValue = Convert.ToInt32(v))">
        </SelectList>
    }
</EditTemplate>
```

The select list:

value: 1, text: "a"
value: 2, text: "b"
value: 3, text: "c"
...

The context.CellValue will be 0.

**Additional context**

When my selected value type is int, then I **don't change the selected index and save**,
I will get 0 rather than 1 (first option's value) in callback item (if my value is null-able, I will get null).

**Comment by koryphaee** [comment]
I have the same issue. When using a Select inside the EditTemplate the SelectedValueChanged EventCallback is never called.

**Comment by stsrki** [comment]
Unable to reproduce with the latest version.
