### ISSUE TITLE
Feature: Media queries / resize events

### ISSUE THREAD

**Issue by njannink** [Megabit/Blazorise#1140]
I need to make some custom UI. That when I pass a certain width (breakpoint) that that part is automatically hidden. Most of the things you can do by using the css breakpoints, but not all.

I found a library that has this functionality, but I would like to limit the number of external libs. How whould you guys think about incorporating this behavior in Blazorise?

https://github.com/EdCharbeneau/BlazorSize

**Comment by stsrki** [comment]
@MitchellNZ I think you implemented similar functionality on Bar component. It might be good idea to move it to the Layout or just copy the same functionality on Layout. Either way there could be as `BreakpointChanged` event after each change.

Or maybe have `BreakpointService` that could be injected into every component that needs it.

**Comment by MitchellNZ** [comment]
This sounds like a good idea! 

I will take a look into this when I get a chance.

**Comment by stsrki** [comment]
@MitchellNZ do you think this would be a good feature for 0.9.4?

**Comment by MitchellNZ** [comment]
@stsrki Yup - that sounds good.

**Comment by stsrki** [comment]
Closing in favor of #3607
