### ISSUE TITLE
Confirm before deleting

### ISSUE THREAD

**Issue by bestpika** [Megabit/Blazorise#1166]
Can you add a function to the datagrid to confirm before deletion?

**Comment by stsrki** [comment]
Seems like a good idea. It shouldn't be a problem. In the meantime you can try do it by using custom button template

```cshtml
<DeleteCommandTemplate>
    <Button Color="Color.Danger" Clicked="@(()=>OnDeleteClicked(context))">Delete</Button>
</DeleteCommandTemplate>
```

```cs
Task OnDeleteClicked( CommandContext context )
{
    // do something here
    if ( deleteWanted )
        return context.Clicked.InvokeAsync( null );

    return Task.CompletedTask;
}
```

**Comment by bestpika** [comment]
@stsrki Thank you.

**Comment by stsrki** [comment]
Should be possible after #1634

**Comment by stsrki** [comment]
@ArneCools look at https://blazorise.com/docs/services/message

**Comment by David-Moreira** [comment]
Just to throw out another idea, you can actually let the delete event bubble up to Datagrid, and bind to the Datagrids OnDelete event, where you can actually manage if it proceeds or not with the deletion with the cancel argument.

I do think we already give enough tools to build this scenario very easily, like shown in the example above.

**Comment by stsrki** [comment]
Like this

```cs
if ( await MessageService.Confirm( "Are you sure you want to confirm?", "Confirmation", options =>
{
    options.CancelButtonIcon = IconName.Book;
    options.CancelButtonText = "cancel me";
} ) )
{
    Console.WriteLine( "OK Clicked" );
}
else
{
    Console.WriteLine( "Cancel Clicked" );
}
```

**Comment by rgomezia** [comment]
@stsrki ty a lot !!! , but i can resize de icon or change the color , you know some way ?

**Comment by stsrki** [comment]
To change the color you can use `MessageIconColor`. But for size, you would probably need to use CSS.

**Comment by rkrause22** [comment]
Similar to other pages of the Blazorise documentation, https://blazorise.com/docs/services/message fails to mention how to add <MessageProvider /> to the page.  Without it, the message does not seem to render.

Does anyone know what version is required?  What package(s) are required? What is the @using statement?  Thanks!

**Comment by rkrause22** [comment]
Thanks for getting back to me so quickly.

I have added @using Blazorise to the component directly, and to the _Imports.razor file.  In both cases when I add < MessageProvider /> to the page, VS reports the following warning:

Warning (active)	RZ10012	Found markup element with unexpected name 'MessageProvider'. If this is intended to be a component, add a @using directive for its namespace.		C:\repos\full-stack\interfaces\medchart\src\SettleSmart.MedchartService.Blazor\Components\ParticipantsGrid.razor	115	

When I invoke MessageService.Info(), nothing is displayed (no error).

In terms of what would be helpful in the documentation, please include a hyperlink to anything references on the page that exists in your documentation.  On the document pages, include the version required to use the feature, the required @using statements and packages required.

Thanks again.

**Comment by David-Moreira** [comment]
Ahhh I just remembered. The problem is not the `using` at all, like I told you, pretty much all components are under `using Blazorise;` and if they are not we usually have snippets with the `using` that should be added.

So, On our latest v1.1 we renamed to `MessageProvider` and are making `MessageAlert` obsolete. You should use `MessageAlert` on that version. Sorry for the incovenience. :)
https://blazorise.com/news/release-notes/110
![image](https://user-images.githubusercontent.com/22283161/198153685-fcb00290-1386-4037-9600-6232abbbf56c.png)


Thank you for your feedback for improvements.

**Comment by rkrause22** [comment]
That worked!  

Leaving the information regarding the change in a note on the pages concerning the MessageService (like https://blazorise.com/docs/services/message) would be helpful.  I would only be inclined to look at the release notes when upgrading.  Hyperlinking to the old example pages would also be helpful (at least for a version or so).

Thank-you very much for your help.

**Comment by David-Moreira** [comment]
Right, ideally you'd just be visiting the docs for your version. 
I have already talked with @stsrki about doing just that.

Glad you got it to work.

**Comment by yarutyunov** [comment]
> Like this
> 
> ```cs
> if ( await MessageService.Confirm( "Are you sure you want to confirm?", "Confirmation", options =>
> {
>     options.CancelButtonIcon = IconName.Book;
>     options.CancelButtonText = "cancel me";
> } ) )
> {
>     Console.WriteLine( "OK Clicked" );
> }
> else
> {
>     Console.WriteLine( "Cancel Clicked" );
> }
> ```

This stopped working for me after .net7 -> .net8 update

**Comment by stsrki** [comment]
Do you have `@rendermode="InteractiveServer"` enabled?

**Comment by yarutyunov** [comment]
im running webassembly

**Comment by yarutyunov** [comment]
https://github.com/Megabit/Blazorise/issues/5521
