### ISSUE TITLE
Categorize ClassNames

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#1169]
Currently when we generate component class-names we do it using the same `ClassBuilder`. This can be problematic in cases where underline html element is not always the only thing that is rendered on DOM. For example Check or Switch components are using div wrappers around `<input>` and `label`, so when we wan't to apply Margin or Padding to the wrapper it cannot be done because internally they're actually applied to the `<input>`

The solution I propose it to have several layers or groups of `ClassBuilder`.

- `ClassBuilder` - This is the default builder that will have only the basic underline element class-names
- `UtilityBuilder` - contains the class-names for utilities like margin, padding, sizing, etc.
- `WrapperBuilder` - in case we need to have a special container inside the component

Finally, after everything is built we can either combine everything to the same `ClassNames` or apply it it to the each separate element `class` attribute. Depending on the situation.

@MitchellNZ any thoughts?

**Comment by MitchellNZ** [comment]
This sounds like a good plan to me! 

Lately, I have needed to create a few custom `WrapperBuilders` in components. 
So this change would definitely make that easier!

Will there be much extra overhead by having these on all classes, since most probably wont be using a `WrapperBuilder`?

**Comment by stsrki** [comment]
I don't think there will be much overhead. The only thing here that is not going to be used always is the `WrapperBuilder `but even that is not going to be noticeable on performance.

The next thing I plan to do is to organize class hierarchy better, but that is going to be part of another ticket.

**Comment by MitchellNZ** [comment]
Great, that sounds good then!

> The next thing I plan to do is to organize class hierarchy better, but that is going to be part of another ticket.

This also sounds like another good idea! 
Would be a great way to organize/manage parameters, etc.
