### ISSUE TITLE
FileEdit Progressed event does not update UI

### ISSUE THREAD

**Issue by makhin** [Megabit/Blazorise#1184]
`<FileEdit Multiple="false" Changed="@OnChanged" Progressed="@OnProgressed"></FileEdit>`

`<ProgressBar Value="@PercentageLoad">@PercentageLoad%</ProgressBar>`

```
        public void OnProgressed(FileProgressedEventArgs e)
        {
            Debug.WriteLine($"File: {e.File.Name} Progress: {e.Percentage}");
            PercentageLoad = (int)e.Percentage;
            this.StateHasChanged();
        }

```

Progress bar does not refreshing

**Comment by makhin** [comment]
sorry wrong code

**Comment by giovannigambino1980** [comment]
Hi Alexandr, maybe I'm having the same problem. How did you solve?

> `<FileEdit Multiple="false" Changed="@OnChanged" Progressed="@OnProgressed"></FileEdit>`
> 
> `<ProgressBar Value="@PercentageLoad">@PercentageLoad%</ProgressBar>`
> 
> ```
>         public void OnProgressed(FileProgressedEventArgs e)
>         {
>             Debug.WriteLine($"File: {e.File.Name} Progress: {e.Percentage}");
>             PercentageLoad = (int)e.Percentage;
>             this.StateHasChanged();
>         }
> ```
> 
> Progress bar does not refreshing

Hi Alexandr, maybe I'm having the same problem with the same code. How did you solve?

**Comment by makhin** [comment]
My code which is working now

```
                <FileEdit Multiple="false" Filter=".zip" Changed="@OnChanged" Progressed="@OnProgressed">
                </FileEdit>

            <Progress Margin="Margin.Is3.FromTop" Size="Size.Large">
                <ProgressBar Value="@PercentageLoad">@PercentageLoad%</ProgressBar>
            </Progress>
```

```
        public int PercentageLoad { get; set; }


        public void OnProgressed(FileProgressedEventArgs e)
        {
            PercentageLoad = (int)e.Percentage;
            this.StateHasChanged();
        }

```

**Comment by giovannigambino1980** [comment]
It's very strange.... I'm using **the same** code but nothing happens. 
If I write 
`Console.WriteLine($"File: {e.File.Name} Progress: {e.Percentage}");`
before 
`this.StateHasChanged();`
I see data in debug console scrolling, but ProgressBar position is frozen.

mmm, 
thank you anyway

**Comment by makhin** [comment]
here is project where I used it 
https://github.com/makhin/BorderCrossing/tree/master/BorderCrossing/Pages
UploadFile and UploadFileBase

**Comment by stsrki** [comment]
@giovannigambino1980 Are you sure you're using the same code as @makhin ?

In your first example, you only have partial code for ProgressBar, while the full example uses Progress and ProgressBar sub-component.

```cshtml
<Progress Margin="Margin.Is3.FromTop" Size="Size.Large">
  <ProgressBar Value="@PercentageLoad">@PercentageLoad%</ProgressBar>
</Progress>
```

**Comment by giovannigambino1980** [comment]
Hi, 
that's my code:

```
<FileEdit Filter=".pdf, .doc, .docx" Multiple = "false" Changed="@OnDocSelected" Progressed="@OnProgressed" />

<Progress Margin="Margin.Is3.FromBottom" Size="Size.Medium" >
    <ProgressBar Value="@this.ProgressValue"> @this.ProgressValue %</ProgressBar>
</Progress>

```

```
  private void OnProgressed(FileProgressedEventArgs e)
        {
            Console.WriteLine($"File: {e.File.Name} Progress: {e.Percentage}");
            this.ProgressValue = (int)e.Percentage;
            this.StateHasChanged();
        }
```

When running I see Browser's console writing all percetages, but progress bar doesn't work.
I don't know if can be useful, the progress bar is inside a 
```
<Modal @ref="modalRef">
....
</Modal>
```

tnx so much

**Comment by stsrki** [comment]
@giovannigambino1980 I tried your example in both **modal** and in a **page**. And for me, it works just fine.

Here is my copy-paste code based on yours:

```cshtml
<FileEdit Filter=".pdf, .doc, .docx" Multiple="false" Changed="@OnDocSelected" Progressed="@OnProgressed" />

<Progress Margin="Margin.Is3.FromBottom" Size="Size.Medium">
    <ProgressBar Value="@this.ProgressValue"> @this.ProgressValue %</ProgressBar>
</Progress>

@code{
    int ProgressValue;

    async Task OnDocSelected( FileChangedEventArgs e )
    {
        try
        {
            foreach ( var file in e.Files )
            {
                // A stream is going to be the destination stream we're writing to.
                using ( var stream = new System.IO.MemoryStream() )
                {
                    // Here we're telling the FileEdit where to write the upload result
                    await file.WriteToStreamAsync( stream );

                    // Once we reach this line it means the file is fully uploaded.
                    // In this case we're going to offset to the beginning of file
                    // so we can read it.
                    stream.Seek( 0, System.IO.SeekOrigin.Begin );

                    // Use the stream reader to read the content of uploaded file,
                    // in this case we can assume it is a textual file.
                    using ( var reader = new System.IO.StreamReader( stream ) )
                    {
                        var fileContent = await reader.ReadToEndAsync();
                    }
                }
            }
        }
        catch ( Exception exc )
        {
            Console.WriteLine( exc.Message );
        }
        finally
        {
            this.StateHasChanged();
        }
    }

    private void OnProgressed( FileProgressedEventArgs e )
    {
        Console.WriteLine( $"File: {e.File.Name} Progress: {e.Percentage}" );
        this.ProgressValue = (int)e.Percentage;
        this.StateHasChanged();
    }
}
```

**Comment by giovannigambino1980** [comment]
Unbelievable... I created a brand new page and pasted your code and it still doesn't work.
So I think the problem is to search somewhere else.
Maybe I'm missing some using?
If I set "ProgressValue" manually I see progressbar working.
Any idea?

**Comment by giovannigambino1980** [comment]
I tried to create a new wasm project, setting up blazorise and pasting your code.
[TestProgressWASM.zip](https://github.com/stsrki/Blazorise/files/5783701/TestProgressWASM.zip)

Can you help me to understand what's wrong?
Tnx so much, 
Giovanni

**Comment by makhin** [comment]
I will check tomorrow

**Comment by makhin** [comment]
> I tried to create a new wasm project, setting up blazorise and pasting your code.
> [TestProgressWASM.zip](https://github.com/stsrki/Blazorise/files/5783701/TestProgressWASM.zip)
> 
> Can you help me to understand what's wrong?
> Tnx so much,
> Giovanni

I checked everything code looks good and should work, but there is one difference between your and mine projects. 
Your is WASM but mine is Server.  
So I can only agree with you Blasorise for WASM has problem with Progressed event

@stsrki can you also check this sample, mb I miss somthing?

**Comment by stsrki** [comment]
I have just tried it in WASM and it works. A little slower, but still works.

**Comment by makhin** [comment]
Can you check this sample or share your?
Thanks

**Comment by makhin** [comment]
![TestProgressWASM - Microsoft Visual Studio 11 01 2021 17_29_48](https://user-images.githubusercontent.com/1430717/104210240-ee6ab280-5432-11eb-9ff7-ea889e003a23.png)

https://user-images.githubusercontent.com/1430717/104210314-02161900-5433-11eb-82f0-c4ac1df1cef6.mp4

Does not work for me.

**Comment by giovannigambino1980** [comment]
The same behavior for me. No updates during upload, but just a burst at the end.
I tried with all browsers, nothing :(

**Comment by sgesweinFusion** [comment]
I'm also running into this same behavior on WASM/0.9.2/dotnet core 3.1 with similar code (calling StateHasChanged after changing the Progressbar value, etc.)

While Console.WriteLine shows console output on Chrome at regular intervals, there are no visual updates on the page between 0 and 100.

**Comment by stsrki** [comment]
Yep, the same thing is happening to me also. Sorry guys, I tested with smaller files and it appeared to work just fine.

**Comment by sgesweinFusion** [comment]
My workaround of the day for this is to rewriting OnProgressed as async and having it explicitly yield to other Blazor work (like updating the UI) after calling StateHasChanged:
```
    async Task OnProgressed(FileProgressedEventArgs e)
    {
        Console.WriteLine($"File: {e.File.Name} Progress: {e.Percentage}");
        _progressedPercent = Convert.ToInt32(e.Percentage);
        StateHasChanged();
        await Task.Yield();
    }
```
That `await Task.Yield()` to let Blazor do whatever it wants for a while with the UI thread feels somewhat risky, though, and is probably a bad idea outside of Blazor WASM and maybe in other ways. I'd rather see it baked into file.WriteToStreamAsync() at appropriate points if that seems a prudent course, and let Blazorise worry about it!

**Comment by pangjianxin** [comment]
seems that the problem still there, @sgesweinFusion 's solution is the best for me

**Comment by David-Moreira** [comment]
Quite a strange behaviour, Have you guys tried InvokeAsync(StateHasChanged)?

**Comment by pangjianxin** [comment]
> Quite a strange behaviour, Have you guys tried `await InvokeAsync(StateHasChanged)`?

sure,i tried this but nothing.it worked for you?

**Comment by David-Moreira** [comment]
So I was doing some testing, when uploading a larger file, the UI does freeze. 
It's like Windows Forms all over again haha. Let's not forget Blazor WASM is single threaded, but my guess is that we can hope for multi thread in the future.

The proposed solution of `Task.Yield` does work. But the UI does act a bit slugish.

I also found out that using 
```
InvokeAsync(StateHasChanged);
Task.Delay(1);
```
does work also giving time to the UI thread to catch up and update. The more you increase the delay time the less slugish the UI looks at the cost of upload time.


We'll see if we can do something about it.
Have you guys tried using the `OpenReadStream` API also?

**Comment by pangjianxin** [comment]
OpenReadStream api seems can not emit a progress event at all???

**Comment by pangjianxin** [comment]
OpenReadStream api seems can not emit a progress event at all???

**Comment by David-Moreira** [comment]
These should hopefully be fixed/better in the next version with #3475 
While working on the new `FilePicker` component, we've made some improvements to the `FileEdit` which should address these issues.

**Comment by stsrki** [comment]
@David-Moreira I think you accidentally referenced the wrong issue :)

**Comment by David-Moreira** [comment]
haha right! Similar numbers, thanks.
