### ISSUE TITLE
DropdownOptions in Theme are wrongly mapped

### ISSUE THREAD

**Issue by WillianGruber** [Megabit/Blazorise#1190]
Hi,

DropdownOptions in Theme are not working (border radius and gradient).
In fact, the Dropdown border and gradient are controlled by ButtonOptions's border and gradient.

You can check with https://github.com/stsrki/Blazorise/pull/1146/commits/aeb7584b3c1d290b780193d5071a5b4bc346aacf

**Comment by stsrki** [comment]
Dropdown is using button as toggle element so I guess it's perfectly fine to have it be styled by ButtonOptions.

**Comment by WillianGruber** [comment]
Sure, but shouldn't then the DropdownOptions be removed?

**Comment by stsrki** [comment]
It can still be expanded with options for dropdown menu and dropdown items.

**Comment by WillianGruber** [comment]
Sure, I expressed myself badly. I mean remove border radius and gradient

**Comment by stsrki** [comment]
Tested and working as expected.
