### ISSUE TITLE
Feature: Icon buttons

### ISSUE THREAD

**Issue by njannink** [Megabit/Blazorise#1220]
Bootstrap and material both have the concept of `btn-icon` for icon buttons. Now I apply that using setting the class of a button, but maybe we should just add it to blazorise?

What would be your preference? An additional flag to the `Button` component or a completely new `IconButton` component?

**Comment by stsrki** [comment]
Do you have an example of `btn-icon`? I cannot find it.

**Comment by njannink** [comment]
https://djibe.github.io/material/docs/4.5/material/buttons/#icon-buttons
https://mdbootstrap.com/plugins/jquery/button-icon/

**Comment by stsrki** [comment]
It's just an icon placed inside of an button. This is how you should do it:

```cshtml
<Button Color="Color.Primary">
    <Icon Name="IconName.Add" />
    New item
</Button>
```

I don't see a reason for new component.

**Comment by njannink** [comment]
But for the material design you will need to add the additional `btn-icon` class otherwise the button won't size correctly. As you could see in the RichTextEdit

**Comment by stsrki** [comment]
The examples you provided are only for djibe material provider. There is not concept of icon button in regular bootstrap. https://getbootstrap.com/docs/4.5/components/buttons/

**Comment by njannink** [comment]
I have been looking at our other providers: 
- ant-design has the concept of icon buttons `ant-btn-icon-only` 
- Bulma also only adds the icon inside the button like bootstrap

So it's like 50/50 based on the provider if we need somehow icon related behavior to a button.

In my own project I added the concept of an `IconButton` 

```           
<IconButton Clicked="@context.Clicked" Size="Size.Small" IconName="IconNames.Edit" />
<IconButton Clicked="@context.Clicked" Size="Size.Small" IconName="IconNames.Save" />
<IconButton Clicked="@context.Clicked" Size="Size.Small" IconName="IconNames.Delete" />
```

**Comment by njannink** [comment]
```
@inherits BaseComponent

<Button Class="@ClassNames"
        Style="@StyleNames"
        Outline="@Outline"
        Clicked="@Clicked"
        Command="@Command"
        CommandParameter="@CommandParameter"
        Disabled="@Disabled"
        @attributes="@Attributes">
    <Icon Name="@IconName" IconStyle="@IconStyle" Class="@GetIconSize()" />
    @ChildContent
</Button>

@code {
    ...

        protected override void BuildClasses(ClassBuilder builder)
        {
            builder.Append(@"btn-icon");      
            base.BuildClasses(builder);
        }

}
```

**Comment by stsrki** [comment]
You're right it seems. OK I will add it on backlog.

**Comment by njannink** [comment]
I don't know what would be the best approach. Create a complement new component or extend the existing Button component?

**Comment by stsrki** [comment]
I think it's best to create new component. It doesn't need all the functionality from regular button.

**Comment by pascx64** [comment]
@stsrki  Why would it not need all the functionality of a regular button ? It seems like it is a regular button, with an icon. It should behave like all other buttons, with the only difference that there is an icon along side the text.

**Comment by stsrki** [comment]
Because regular buttons can be used inside of Addon, Dropdown, and other components and its styles are natives supported for that kind of scenarios. The icon button from what I can see looks different and has a different structure in some cases. Which would make it hard to adjust for different use case scenarios. Thats why it's best to create the separate components. Just like there is CloseButton already.

**Comment by njannink** [comment]
And from a SOLID point of view I wouldn't want to make on big bloated button either

**Comment by stsrki** [comment]
Closing since we don't have plans for such a component at the moment.
