### ISSUE TITLE
FilterRowStyling in Datagrid doesn't appear to work

### ISSUE THREAD

**Issue by mdwyercalamos** [Megabit/Blazorise#1221]
In the datagrid definition, I have:  FilterRowStyling="@filterrow"

I have the variable defined as:   DataGridRowStyling filterrow = new DataGridRowStyling();

And as part of onitializedasync I set the style:
filterrow.Style = "position:sticky; top: 110px; line-height:1em;padding:1;";

I have tried to changing background colors and other changes however they do not appear to work.  This was one of the breaking changes of the new release, this style used to work when FilterRowStyle was available.  

I can not find any documention on the new FilterRowStyling so not sure what I am doing wrong.  Any ideas?

**Comment by stsrki** [comment]
Settings the filter style work on my side

eg. `FilterRowStyling="@(new DataGridRowStyling { Style = "background-color: red;" })"`

![image](https://user-images.githubusercontent.com/900302/122920055-3df9c680-d361-11eb-8e7a-22b81a5d2d39.png)

Regarding you problem with sticky settings: `position:sticky; top: 110px; line-height:1em;padding:1;`. If I understand correctly you want to have header fixed while table body is scrollable?

That will be possible with v0,9,4 version. (Table sticky header #2293)
