### ISSUE TITLE
Access to datagrid columns

### ISSUE THREAD

**Issue by NicolasFVS** [Megabit/Blazorise#1225]
Hi

**Is your feature request related to a problem? Please describe.**
I want to access to the list of datagridcolumns in my datagrid but all methods are protected because I want to clear all filter on external action

**Describe the solution you'd like**
Can you change the definition and expose those methods

### Additional context
![image](https://user-images.githubusercontent.com/69345012/89629497-37c04000-d89e-11ea-99aa-be4fd94a9ed1.png)

**Comment by stsrki** [comment]
#2503 will handle this scenario. You will just call `.ClearFilter()` on the DataGrid instance.
