### ISSUE TITLE
DropdownList - no scroll when data list is long

### ISSUE THREAD

**Issue by dobermanch** [Megabit/Blazorise#1229]
I'm trying to use DropdownList. When I bind log data list the dropdown menu does not have any scrollbar. The documentation does not have any information about it.
Is there any way to make it scrollable?

**To Reproduce**
Behavior reproduces on [Demo Site](https://bootstrapdemo.blazorise.com/tests/components)
![image](https://user-images.githubusercontent.com/7737773/89724098-ae029680-d9b3-11ea-89d3-5105c0251543.png)

**Expected behavior**
I guess it should looks something like this
![image](https://user-images.githubusercontent.com/7737773/89724131-1fdae000-d9b4-11ea-8106-e16f2109e9d8.png)

**Comment by stsrki** [comment]
You could just use custom css https://stackoverflow.com/questions/47645634/bootstrap-4-making-dropdown-scrollable/47646286 to make it scrollable. But I'm not sure it's the right thing from UX perspective. Dropdown(s) are supposed to be used just as a quick menu. And with long list you kinda overuse it. It's better to switch to SelectList in your case.

**Comment by doberman-ch** [comment]
Thank you for so quick response.
Not sure if SelectList suites for my control (not sure what is correct name for it):
![image](https://user-images.githubusercontent.com/7737773/89740259-01b8c280-da3c-11ea-98fe-b38adc0b47ad.png)
when item is selected in dropdown it disappears from the list and appears next to the dropdown and when remove button is clicked it returns back to the list.

Regarding to Dropdown even on the demo page that list is huge, and it breaks UX on 3440x1440 monitor resolution. 
I guess it would be useful to have scroll option available, maybe as a separate switch.

Thank you for the link, that was my first idea, but decided to ask here before using workarounds.

Thanks.

**Comment by David-Moreira** [comment]
This has been implemented on the latest blazorise versions. Closing issue. :)
