### ISSUE TITLE
Validation in DataGrid

### ISSUE THREAD

**Issue by NicolasFVS** [Megabit/Blazorise#1237]
**Describe the bug**
Hi. Validation in Datagrid not working like we want. It seems not possible to use ValidateAll() because it return always true

**To Reproduce**
When we edit row and after we click save button. 

**Expected behavior**
ValidateAll should return false

Also please provide a sample code or point us to a minimalistic GitHub repo

**Screenshots**
![image](https://user-images.githubusercontent.com/69345012/89908795-9fec8a00-dbee-11ea-88c8-f0b81f76281b.png)

On inserting 
![image](https://user-images.githubusercontent.com/69345012/89908864-babefe80-dbee-11ea-93aa-99b7aa6db303.png)

Thank-you for your answer

**Additional context**

**Comment by stsrki** [comment]
Validation is handled by the DataGrid internally. You should only need to remove the `Validations` tag from EditTemplate.

We're currently DataGrid validations and if any problem still occurs after we release v0.9.4 please reopen.
