### ISSUE TITLE
Fields with the data type of time do not generate input boxes automatically in edit mode

### ISSUE THREAD

**Issue by bestpika** [Megabit/Blazorise#1253]
**Describe the bug**

There is no time element in the DataGrid so I use the date element and it doesn't generate the input box automatically when in edit mode.

**Screenshots**

![image](https://user-images.githubusercontent.com/5698157/90218379-3b237080-de36-11ea-8ae3-20da289dc019.png)
![image](https://user-images.githubusercontent.com/5698157/90218519-96edf980-de36-11ea-8f28-5ae11456e8a7.png)

**Additional context**

```c#
<DataGridDateColumn TItem="Cio" Field="@nameof(Cio.Begintime)" Caption="報到" Editable="true"></DataGridDateColumn>
```

I think there should be a `<DataGridTimeColumn />` to support this function.

**Comment by SunnyOswal** [comment]
I use below:

<DataGridDateColumn TItem="XXX" Field="@nameof( XXX.OfficeCloseTime )" DisplayFormat="{0:hh:mm:ss tt}" Caption="Close Time" Editable="true" Filterable="false">
            <EditTemplate>
                <TimeEdit TValue="TimeSpan?" Time="@selectedCloseTime" TimeChanged="@((v)=> { selectedCloseTime = v; } )" />
            </EditTemplate>
        </DataGridDateColumn>

**Comment by stsrki** [comment]
Thanks for reporting this. You're right there should be a time component also. I will add it.

**Comment by bestpika** [comment]
@SunnyOswal I know it works this way, but wouldn't it be easier to just let it auto-generate if it's a common and internally supported component?

@stsrki Hey, don't forget to include the step variable, or you won't be able to get the user to enter the seconds. ;-)

**Comment by SunnyOswal** [comment]
@bestpika yes if we have blazorise support it that will be super easy as it was not supported, i did a workaround for my use.
