### ISSUE TITLE
TimeEdit component lose the Step variable

### ISSUE THREAD

**Issue by bestpika** [Megabit/Blazorise#1255]
The TimeEdit component should have a step variable, but an additional step variable will cause the first read to be 00 seconds.

![image](https://user-images.githubusercontent.com/5698157/90235998-bdbb2880-de54-11ea-9d6a-70ec61d1e44d.png)

Click Edit:

![image](https://user-images.githubusercontent.com/5698157/90236041-cb70ae00-de54-11ea-941d-66d8fd20a9d0.png)

My code:

```c#
<TimeEdit TValue="TimeSpan?" step="1"
          Time="@(context.CellValue as TimeSpan?)"
          TimeChanged="@(v => context.CellValue = v)"></TimeEdit>
```

Should be:

```c#
<TimeEdit TValue="TimeSpan?" Step="1"
          Time="@(context.CellValue as TimeSpan?)"
          TimeChanged="@(v => context.CellValue = v)"></TimeEdit>
```

**Comment by stsrki** [comment]
It's not very clear what is the problem. Step is used to control the seconds part of the time, according to this https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

I can easily add a Step parameter if that is the right approach.

**Comment by bestpika** [comment]
Normally when I use `<input type="time" step="1">`, there would be a field for seconds when the control is generated.

Like this.
![image](https://user-images.githubusercontent.com/5698157/100842165-613b5200-34b3-11eb-84f6-f72e34641de4.png)

However, when I use Blazorise's Time control, even if I add `step="1"` at the beginning, the second's field does not appear when the control is generated.

So when I have seconds in my data, filling in Time will look like `:00` instead of what I expected.

**Comment by stsrki** [comment]
Not sure why it won't work for you. I've tried it and seems fine for me:

**Razor**

```cshtml
<TimeEdit TValue="TimeSpan?" step="1" />
```

**Result**

![image](https://user-images.githubusercontent.com/900302/100851857-0808f980-3486-11eb-9e68-e55269542a40.png)

**and**

![image](https://user-images.githubusercontent.com/900302/100851952-25d65e80-3486-11eb-8e47-8836ca70fd8a.png)

As you can see, it's showing the seconds part and it is not zero.

**Comment by bestpika** [comment]
Do you use my code in DataGrid?

```C#
<TimeEdit TValue="TimeSpan?" step="1"
          Time="@(context.CellValue as TimeSpan?)"
          TimeChanged="@(v => context.CellValue = v)"></TimeEdit>
```

**Comment by stsrki** [comment]
Not in a DataGrid, just placed it in the page.

**Comment by bestpika** [comment]
When used in a DataGrid component, if the default data filled in contains seconds, the component does not display the seconds properly, but appears as `:00`.
Just like the picture I posted earlier.

**Comment by stsrki** [comment]
I tried to place it in DataGrid and alone on the page. The result is always the same. Zero is lost as soon as I apply the `step` attribute. Internally there are no problems. Blazorise parses the time including the seconds. My guess is that something is wrong with the browser and how the `step` works.
