### ISSUE TITLE
Load huge data in TreeView

### ISSUE THREAD

**Issue by tarafdarmansour** [Megabit/Blazorise#1276]
Hi
Recently you added TreeView as a extension to Blazorise project.
Suppose I have a huge amount of data in tree structure, I should load all data to TreeView in one data seek, furthermore if I edit my data, I should load all again and again ...
Is there any way to load data in TreeView partially for a node or subtree ?

**Comment by dockinkong** [comment]
Hello,
I'm facing an performance issue when loading big amount of items in treeview... is treeview virtualized DOM speaking or is there a way to virtualize it?
Being a newbee maybe this problem is not a real problem :)
Thanks for any answer...

**Comment by stsrki** [comment]
This feature will be available in the comming 1.2 release. Closing now.
