### ISSUE TITLE
Bad nuget author name

### ISSUE THREAD

**Issue by Luk164** [Megabit/Blazorise#1280]
**Describe the bug**
Just noticed there is a problem in Blazorise.TreeView NuGet package author name.

![image](https://user-images.githubusercontent.com/30559213/91304653-21751800-e7aa-11ea-9de6-f6ad96600b59.png)

**Comment by stsrki** [comment]
Thanks for letting us now. This should be fixed!

**Comment by Luk164** [comment]
Forgot to close, issue resolved.
