### ISSUE TITLE
Autocomplete - The dropdown 'dropdown-menu' item is having the wrong mouse pointer style

### ISSUE THREAD

**Issue by kthe** [Megabit/Blazorise#1295]
When using the autocomplete, and hovering over the dropdown menuitem texts, the mouse pointer is for input not selection. 

This can be seen in the samples https://rcbootstrapdemo.blazorise.com/tests/components

The mouse cursor should be of pointer style.

**Comment by David-Moreira** [comment]
Autocomplete selection mouse cursor should be of pointer style in the latest versions of Blazorise. 
Closing issue.
