### ISSUE TITLE
Chart Streaming Extension Fails To Respect Changes To Options

### ISSUE THREAD

**Issue by constrictor14** [Megabit/Blazorise#1334]
**Describe the bug**
Using the OptionsJsonString, I am setting the duration and pause components of my chart like so:
 "{\"animation\": 0, \"scales\": {\"xAxes\": [{ \"type\": 'realtime', \"realtime\": { \"duration\":" + **duration** + ", \"pause\"" + **pause** + "}}]}}";

Duration:
Afterwards no changes are made to the chart duration even if I were to call Update(), Refresh(), or tell Blazor that the StateHasChanged().  I can set the duration once at the beginning like so, but never modify it after creation:

```
        <LineChart @ref="horizontalLineChart" TItem="LiveDataPoint" OptionsObject="@horizontalLineChartOptions">
            <ChartStreaming @ref="chartStreaming" TItem="LiveDataPoint"
                            Options="new ChartStreamingOptions { Delay = 2000, Duration = DurationValue, Refresh = 3000, FrameRate = 5 }"
                            Refreshed="@OnHorizontalLineRefreshed" />
        </LineChart>
```

Pause:
Setting this causes pause the data to stop propagating, but the chart continues to move and the chart loses interactivity when the correct behavior should be like it works here where the chart stops moving: https://nagix.github.io/chartjs-plugin-streaming/samples/interactions.html  In fact, the behavior of the streaming plugin should work like that link in all respects in terms of behavior.

**Expected behavior**
When modifying the x-axis duration, the chart should change the actual x-axis to match the new period.
When modifying the x-axis pause, the entire chart should stop moving, but remain interactive.

**Comment by stsrki** [comment]
Hi, can you create a small project to reproduce the problem?
