### ISSUE TITLE
Accessibility and BarDropdownToggle

### ISSUE THREAD

**Issue by stevenlupo** [Megabit/Blazorise#1340]
Not sure if this is a bug or a feature request, but this can be illustrated in the [Blazorise Demo](https://bootstrapdemo.blazorise.com/).

When you tab through the page, all components will show an outline when they have focus. Specifically, the elements across the top and the sidebar will show this outline when they have focus -- _except_ if it's a `BarDropdownToggle`. So, for example, _Home_, _Documentation_ and _GitHub_ get an outline, but _More_ and _Theme_ do not because they are `BarDropdownToggle`. Same thing happens in the Sidebar.

This came to my attention because of accessibility testing.

**_Update_**: Hold on, those elements are not even getting focus when you tab. There's no way to navigate to them using tab, so this is definitely a problem. Hopefully, when we can tab to them, they'll show an outline. Is this a `tabindex` problem?

**Comment by stsrki** [comment]
Should be fixed as part of #3454
