### ISSUE TITLE
HTML 5 datalist or equivalent

### ISSUE THREAD

**Issue by Jinjinov** [Megabit/Blazorise#1358]
**Is your feature request related to a problem? Please describe.**

HTML 5 datalist
 - [X] dropdown opens on mouse click
 - [X] dropdown has a scrollbar
 - [X] has a text edit to filter the options with Contains("")
 - [X] has a text edit to filter the options with StartsWith("")

Autocomplete
 - [x] dropdown opens on mouse click
 - [x] dropdown has a scrollbar
 - [x] has a text edit to filter the options with Contains("")
 - [X] has a text edit to filter the options with StartsWith("")

DropdownList
 - [X] dropdown opens on mouse click
 - [ ] dropdown has a scrollbar
 - [ ] has a text edit to filter the options with Contains("")
 - [ ] has a text edit to filter the options with StartsWith("")

SelectList
 - [X] dropdown opens on mouse click
 - [X] dropdown has a scrollbar
 - [ ] has a text edit to filter the options with Contains("")
 - [ ] has a text edit to filter the options with StartsWith("")

**Describe the solution you'd like**

- a.) Add missing features to Autocomplete or SelectList

or

- b.) Wrap the HTML 5 datalist in C#

### Additional context

https://www.w3schools.com/tags/tag_datalist.asp

**Comment by stsrki** [comment]
@David-Moreira I think we already support these features. Can you confirm?

**Comment by David-Moreira** [comment]
Hello,
Ticked some more.

`DropdownList` does not have scrollbar, do we want to add it?

Also filters don't make sense in `Dropdownlist` and `SelectList` do they?

**Comment by stsrki** [comment]
We can add a scrollbar to `DropdownList`. It is practically the same thing as `Autocomplete` in terms of structure so it makes sense ta have it.

And filters on `DropdownList` and `SelectList` don't make sense, I agree.

**Comment by Jinjinov** [comment]
The `Autocomplete` on https://bootstrapdemo.blazorise.com/tests/components does not open its dropdown list when you click on it.

**Comment by stsrki** [comment]
Autocomplete is set to only show dropdown after a certain number of characters is entered. To show it in click just set MinLength to zero.
