### ISSUE TITLE
[Question]About the Inline attribute of Radio component in Documentation

### ISSUE THREAD

**Issue by tzengshinfu** [Megabit/Blazorise#1363]
**Describe the bug**
Maybe the Inline is the attribute of RadioGroup, not Radio?
![Image 001](https://user-images.githubusercontent.com/2170033/95166699-ee7a6700-07e0-11eb-8b57-2a175483e947.png)

**To Reproduce**
Please go to [Radio component - Blazorise](https://blazorise.com/docs/components/radio/)

**Comment by stsrki** [comment]
Hi @tzengshinfu, not sure what the problem is here. Can you please edit your message?
