### ISSUE TITLE
Exception occurs when clicking on refresh on a page that has a Modal component

### ISSUE THREAD

**Issue by thuhaile** [Megabit/Blazorise#1383]
When click Refresh button on a page that has a Modal component, an exception error occur

Circuit has been shutdown due to error

blazor.server.js(19)

**To Reproduce**
1. Any server side page that has a Modal component
2. Click on Refresh after the page is loaded
3. Exception briefly shown at the bottom of the page then disappear

![Screen Shot 2020-10-14 at 10 18 34 AM](https://user-images.githubusercontent.com/34693207/96023126-cacda700-0e06-11eb-91e7-410c202f6d7e.png)

**Comment by stsrki** [comment]
It's hard to say what's wrong without any code sample.

- Maybe you're using validation on modal?
- If, so do you use data-annotation for validation?
- And, do you reset Model by doing `myModel = new MyModel();` ?
- Do you have any `EventCallback` that might fail somewhere?

**Comment by thuhaile** [comment]
No error when it's first loaded. Exception appears when hitting Refresh button.

```
<Modal @ref="warningDialog">
    <ModalBackdrop />
    <ModalContent Centered="true">
        <ModalHeader>
            <ModalTitle>Warning</ModalTitle>
        </ModalHeader>
        <ModalBody>

            <Field>
                <FieldLabel>Appointment Date is more than 3 months in the future!</FieldLabel>
            </Field>
        </ModalBody>
        <ModalFooter>
        </ModalFooter>
    </ModalContent>
</Modal>


@code {
    private Modal warningDialog;
}
```

**Comment by stsrki** [comment]
I don't see anything wrong with the supplied code. Has the same problem happened before `0.9.2 preview 9`? Can you try revert to preview 8?

**Comment by thuhaile** [comment]
Thanks, for your quick response. Yes, it also happened on preview 8. I upgraded to preview 9 hoping it would fix the problem :)

**Comment by thuhaile** [comment]
It also happens on 0.9.1.2 if it helps

**Comment by stsrki** [comment]
Any chance you might create a small project where we can reproduce this?

**Comment by thuhaile** [comment]
Sure. I used a default template Blazor Server project from VS2019. Please refresh the Counter page to reproduce this issue.

https://github.com/thuhaile/TestBlazorise/blob/main/BlazorApp1.zip

**Comment by stsrki** [comment]
I'm hitting refresh but nothing happens for me

![image](https://user-images.githubusercontent.com/900302/96049514-69deb700-0e78-11eb-91cc-07a0aebea449.png)

**Comment by thuhaile** [comment]
If you put a break point anywhere in the Counter page, you'll see it

**Comment by thuhaile** [comment]
![Uploading Screen Shot 2020-10-14 at 3.05.47 PM.png…]()

**Comment by thuhaile** [comment]
<img width="1881" alt="Screen Shot 2020-10-14 at 3 05 47 PM" src="https://user-images.githubusercontent.com/34693207/96050805-20b64500-0e2f-11eb-89ed-8495e133756a.png">

**Comment by stsrki** [comment]
I was able to reproduce it. Going on the backlog and we'll see when to work on it.

**Comment by thuhaile** [comment]
Thank you! Unfortunately, I've just noticed that this issue also happens on other Blazorise components such as Button, TextEdit, etc.

**Comment by stsrki** [comment]
We did a lot of improvements in the last version to properly dispose of components so this should be already fixed. If the problem persists after the 0.9.5 release, please reopen.
