### ISSUE TITLE
Blazorise MetroUI

### ISSUE THREAD

**Issue by fMichaleczek** [Megabit/Blazorise#1394]
I like MetroUI because it has an original layout.
https://metroui.org.ua/

The javascript dependency is also well documented 
https://metroui.org.ua/m4q-about.html

I found this framework could be interesting to Blazorize. 

Thank you for you amazing work 👍

**Comment by stsrki** [comment]
I like it. I seem like a good candidate for the next Blazorise provider, Components are nice and clean, and from what I can see it supports most of the things required for easy implementation, like colors, utilities, etc. Nice find!

**Comment by fMichaleczek** [comment]
Well, the author change the licensing there is 2 weeks, from MIT to GPLv3.
The latest public MIT is 4.3.10 : https://github.com/olton/Metro-UI-CSS/tree/4.3.10
I understand the author because he was never paid for all his 5 years of hard work.
But GPLv3 is for GPLv3 open source project and If I paid 50€ and give you the MIT License, after I don't understand why people still would want to pay him ... 🤷‍♀️

/cc @olton

**Comment by stsrki** [comment]
That's too bad :(

**Comment by olton** [comment]
> Well, the author change the licensing there is 2 weeks, from MIT to GPLv3.
> The latest public MIT is 4.3.10 : https://github.com/olton/Metro-UI-CSS/tree/4.3.10
> I understand the author because he was never paid for all his 5 years of hard work.
> But GPLv3 is for GPLv3 open source project and If I paid 50€ and give you the MIT License, after I don't understand why people still would want to pay him ... 🤷‍♀️
> 
> /cc @olton

Probably because the author is constantly developing the library, but you will only give away a certain version, which will fall within the paid annual period.

**Comment by stsrki** [comment]
I'm not an expert on this but If I try to use a project that has a GPL license, withing a project that has MIT, it means I need to apply with the GPL license? And that is not something I would wish for.

**Comment by fMichaleczek** [comment]
@stsrki we are allow to create another repo (better) with only Blazorise.MetroUI with MIT license for MetroUI MIT and GLv3 user. (MIT <4.4, GPLv3 >=4.4 and MIT >=4.4). The license is a right for the enduser. I already begin to integrate Metro, so I don't have the choice to fork and keep a 4.3 layer compatibility. It's a lesson about free software today 😉

@olton First, I love your work. You're a very great frontend developer. I know MetroUI from the beginning, I am more an system admin who like to create beautiful reports. Nothing to sell to people, only fancy documents. I work as a Microsoft IT, so you know, it's nice. Now, we are involving to Blazor and I want my lib. Dev People are paying for 995 € for Blazor Component https://www.syncfusion.com/sales/products/blazor. Yes, people who paid are not JS or PHP dev, there are building office developper. So 50€ is not enough for the real business world and the GPLv3 is a blocking license for others open source projects. You should make a benchmark on the Blazor community as people have more money at works than the average frontend dev. If you had a MIT license which cover normal people and a paid version for office dev people with support, I will be more happy at day with devs and at home, for open source project.  I made a fork of the latest MIT and I will wait for you to resolving this gray zone. Nothing against you, more the opposite ! I think you take the wrong direction, because you add restriction (you remove me a right) and I think MetroUI is a so much amazing that you must help people to realize that is the best CSS UX (I think it is). Previous frontend developpers was more Google fanboy (Material etc..), and it's why Microsoft design didn't interested people. Now MS is more cool, you should be more near this community and try to find a business model. At least, I think it's more possible to find 1000 C# devs who paid you 250$.

And sorry @stsrki to hijack your thread, I was so happy you are interested to integrate it.

PS : I don't speak too much on GitHub, please be kind and respectious. I am not a english native and I only want to give feedback.

**Comment by stsrki** [comment]
@fMichaleczek As you said already, the price is not a problem, at least it shouldn't be for any company. A couple of hundred dollars is appropriate for high-quality software. And from what I can see MetroUI is really good. But having GLP over MIT is really limited and whenever I see it run from it.

Personally, I know how hard it can be to work on an open-source project. A understand that. I always wanted for Blazorise to be free no matter what. That's why I'm currently working on a business model that will lean onto Blazorise being open-source and extend upon it. There are always ways to make it work, I hope :) For me, MIT is the least obtrusive license and it also gives community space to grow.

I hope something will change with the MetroUI license. 

@olton Just wanted to say I understand you, and I'm always open to collaboration :) cheers

**Comment by olton** [comment]
@fMichaleczek thank you for your feedback. Unfortunately, I am also not a special expert on the topic of licensing. The current version was suggested by the xs: code manager. But your words got me thinking. All my work is aimed at giving the end-user a convenient and simple tool. All these years (since 2012) I have been giving away my Metro UI for free and without restrictions under the MIT license. Unfortunately, these are difficult times for me and I would like to receive at least some profit from my work on the Metro UI project, so I took this step. And yet, I am always open to cooperation for integrating Metro UI into other products :)

**Comment by olton** [comment]
@fMichaleczek. @stsrki Your words made me think, and I made a decision: With version 4.4.1, I decided to revert to the MIT unified licensing model. Priority dedicated email support will be paid. Thanks.

**Comment by stsrki** [comment]
@olton That was fast I must admit :)

**Comment by olton** [comment]
Welcome to Metro 4 with an MIT license! 4.4.1 now released.

**Comment by fMichaleczek** [comment]
@olton It's the shorlist where Blazor people find good libraries : https://github.com/AdrienTorris/awesome-blazor
There is only 3 professionals (and more expensinves) components for Blazor : 
- https://www.radzen.com/pricing/
- https://www.telerik.com/purchase/blazor-ui
- https://www.devexpress.com/blazor/ (i dont find the price)

Your amazing work is very professinoal, I think you should have a free basic components and specific enterprise component like "crazy grid" for heavy data (things I don't need). If me or @stsrki implement a basic Blazorise.MetroUI the work will be MIT and, so we will give back the code, so you can have a look of the Blazor ecosystem. And I will take a license for 2021, you deserve it.

Thanks you a lot.

**Comment by olton** [comment]
@fMichaleczek thank you, but You no longer need to buy a license! Only additional priority support is now paid!

**Comment by olton** [comment]
Metro 4 is now licensed by MIT and will remain so, well, unless of course, someone offers me a million dollars :) I want people to have free access to the tools and thank the author for their work voluntarily if the author's work deserves it. Thanks.

**Comment by fMichaleczek** [comment]
All framework integrated into Blazorise are owned by big corporate company who made them with an army of developers and there is no Microsoft framework inside Blazorise ... because Microsoft fluent design is unfinished. Your is far better.
I will hope to find 2 millions of dollars, and give you back one :)

**Comment by olton** [comment]
> I have to ask. Do you know if Metro UI is still maintained? The last version was released almost a year ago.

I am currently working on the Metro 5, you can find the repo in my account. Metro 4 will be supported very slowly.
