### ISSUE TITLE
Individually clearable textboxes in the DataGrid filter to allow use when Editable is false. 

### ISSUE THREAD

**Issue by Welchen** [Megabit/Blazorise#1403]
Feature request is the ability to display a clear X on a DataGrid checkbox to allow the user to clear only one filter textbox instead of all. This also allows for a grid to be set to Editable = False and be able to easily clear filter fields. 

Issue I am having is that I have a DataGrid where I show logs and don't want to allow any CUD operations but want to just let them read. I also want to let them filter the results in the DataGrid. If you set Editable to false, then you no longer get the "Clear Filter" button and if you turn Editable to true you get the Clear button but it takes up a full row in the grid. Being able to just click a clear button on the text field would be helpful.

**Comment by stsrki** [comment]
You can already do this I believe.

Can you try `FilterTemplate` like this?

```cshtml
<DataGridColumn TItem="Employee" Field="@nameof( Employee.FirstName )" Caption="First Name" Validator="@CheckFirstName" Editable="true">
    <FilterTemplate>
        <TextEdit Placeholder="Search name" TextChanged="@(v=>context.TriggerFilterChange(v))" />
        <Button Clicked="@(v=>context.TriggerFilterChange(""))">
            <Icon Name="IconName.Clear" />
        </Button>
    </FilterTemplate>
</DataGridColumn>
```

Also, you can hide a clear button by just adding an empty `ClearFilterCommandTemplate`

```cshtml
<ClearFilterCommandTemplate>
</ClearFilterCommandTemplate>
```

**Comment by Welchen** [comment]
This kind of works.  The TextEdit text doesn't clear when the button is clicked but the column does stop filtering. Also the clear button ends up being on a separate line from the TextEdit, that might just need to be fixed with ColumnWidth though.

**Comment by stsrki** [comment]
For that try to set Text parameter `Text="@context.SearchValue"`

**Comment by Welchen** [comment]
Setting that does not get it to clear.  During the Clicked event I can also set context.SearchValue = "" but that only works after the first clear and the value doesn't reset if you try to search again.

**Comment by MGabala** [comment]
Same problem here. Cannot make it clear.

**Comment by stsrki** [comment]
This ticket got stuck in limbo, and I think it could be a good feature to have.

@David-Moreira, What do you think we add an argument to the existing `ClearFilter()` method?

**Current**:

`public Task ClearFilter()`

**Proposed**:

`public Task ClearFilter(params string[] fieldNames)`

**Comment by David-Moreira** [comment]
Don't see why not. More flexibility.
