### ISSUE TITLE
DataGrid after delete a row bind-SelectedRow is firing

### ISSUE THREAD

**Issue by Riedi2070** [Megabit/Blazorise#1419]
**Describe the bug**
I've an editable, selectable data grid with delete button. After I push the delete button, I get an exception cause after the row is deleted the `@bind-SelectedRow` is calling. In the setter I get the object which was deleted, but this object no longer exists, cause its deleted. Why is the `@bind-SelectedRow` called? When using the edit button next the delete button and save  `@bind-SelectedRow` isn't called.

**To Reproduce**
1. Create editable, selectable data grid
2. Define `RowUpdated`, `RowRemoved`, `@bind-SelectedRow`
3. Fill with data
4. Push row delete button
5. Error occurs

**Expected behavior**
I expected when deleting a row, the function @bind-SelectedRow is not calling.

My datagrid:
```
<DataGrid TItem="Dto"
          Data="@Dtos"
          Editable="true"
          EditMode="DataGridEditMode.Inline"
          RowUpdated="@OnRowUpdatedAsync"
          RowRemoved="@OnRowRemovedAsync"
          @bind-SelectedRow="@SelectedDto"
          RowSelectable=@((item)=>item?.Name != "")>

        <DataGridCommandColumn TItem="Dto">
            <EditCommandTemplate>
                <Button Clicked="@context.Clicked"></Button>
            </EditCommandTemplate>
            <DeleteCommandTemplate>
                <Button Clicked="@context.Clicked"></Button>
            </DeleteCommandTemplate>
            <SaveCommandTemplate>
                <Button Clicked="@context.Clicked"></Button>
            </SaveCommandTemplate>
            <CancelCommandTemplate>
                <Button Clicked="@context.Clicked"></Button>
            </CancelCommandTemplate>
        </DataGridCommandColumn>

        <DataGridColumn TItem="Dto" Field="@nameof(Dto.Id)" Caption="Id" />
        <DataGridColumn TItem="Dto" Field="@nameof(Dto.Name)" Caption="Name" Editable="true" />
</DataGrid>

@code {

    protected IList<Dto> Dtos { get; set; }

    protected Dto SelectedDto { get => new Dto();
        set {
                NavManager.NavigateTo($"dto/{value.Id}/edit");
            }
    }

    protected async Task OnRowUpdatedAsync(SavedRowItem<Dto, Dictionary<string, object>> e)
    { ... }

    protected async Task OnRowRemovedAsync(Dto dto)
    { ... }
}
```

**Comment by Riedi2070** [comment]
Not solves the problem, but its a workaround:

```
...
protected Dto SelectedDto { get => new Dto();
        set {
                if (Dtos.Contains(value))
                     NavManager.NavigateTo($"dto/{value.Id}/edit");
            }
    }
...
```

**Comment by stsrki** [comment]
Can you try `RowSelectable=@((item)=>item?.Name != null)`?

**Comment by Riedi2070** [comment]
> Can you try `RowSelectable=@((item)=>item?.Name != null)`?

Sry same result, @SelectedDto is still called

**Comment by David-Moreira** [comment]
We've added the following on the latest release:

https://blazorise.com/news/release-notes/100
![image](https://user-images.githubusercontent.com/22283161/157775129-f98b4640-add1-4461-9205-300426bed67b.png)

This should help solve these type of issues, where we want to avoid the button clicks to trigger the row clicks... which can cause the row to be incorrectly selected.

Closing issue, just let us know if you have any other issue with this.

**Comment by am185760** [comment]
![image](https://user-images.githubusercontent.com/122779717/217534212-c6767db8-d981-42b4-a850-5c8832b11a22.png)

@stsrki  how to remove delete btn for Admin ?

**Comment by David-Moreira** [comment]
@am185760 I believe you have contextual Item access in the **DeleteCommandTemplate**. So you can just go ahead and do something along the lines of `@if (!context.Item.GroupName == "Administration")` and controlthe markup you render however you want.

**Comment by David-Moreira** [comment]
@am185760 Also please just open a new discussion or issue whenever you have questions, otherwise it can easily get lost and unresponded. :)
