### ISSUE TITLE
Autocomplete Component - Cursor keeps on jumping when we type on the search box

### ISSUE THREAD

**Issue by ashishKumarAgarwal** [Megabit/Blazorise#1429]
**Describe the bug**
When we type quickly on the Textbox in Autocomplete, the cursor keeps on jumping (looks laggy)

**To Reproduce**
1. Start typing some text in autocomplete 
2.  You would see the lag

**Expected behavior**
No lag should be there when we search any text

Also please provide a sample code or point us to a minimalistic GitHub repo

**Screenshots**

**Additional context**

**Comment by stsrki** [comment]
Hi, look at this ticket https://github.com/stsrki/Blazorise/issues/1397

**Comment by ashishKumarAgarwal** [comment]
Thanks for the swift reply. Will have a look at this.

**Comment by ashishKumarAgarwal** [comment]
Have tried adding DelayTextOnKeyPress="true"
              DelayTextOnKeyPressInterval="300" to AutoComplete.
This works in my local environment but again fails in the dev server. Any idea on this?
Below is my code setup.
<Autocomplete @ref="@Autocomplete"
              Style=""
              Data="@Endpoints"
              TextField="@(endpoint => endpoint)"
              ValueField="@(endpoint => endpoint)"
              SelectedValue="@EndpointName"
              SelectedValueChanged="@OnEndpointSelected"
              ChangeTextOnKeyPress="true"
              Filter="AutocompleteFilter.Contains"
              DelayTextOnKeyPress="true"
              DelayTextOnKeyPressInterval="300"/>

**Comment by stsrki** [comment]
Blazor server-side uses SignalR to communicate between the client and a server and every UI interaction needs to be run by the server. So if you have a slower connection or your server is too far it can take some time, especially when you type too fast. You have two options

- use `ChangeTextOnKeyPress="true"` to submit input changes when it lost focus
- increase `DelayTextOnKeyPressInterval`

It depends on your scenario so you need to choose, wisely :)

**Comment by ashishKumarAgarwal** [comment]
Not really know what to do!
I am using bellow config now:
changeTextOnKeyPress="true"
DelayTextOnKeyPress="true"
DelayTextOnKeyPressInterval="1000"/>

Still it does not work. Not sure if more than 1sec delay should be applied.

**Comment by stsrki** [comment]
Sorry I was fast to copy-paste. I updated the previous example. Try with `ChangeTextOnKeyPress="false"`, that one should not have any side-effect.

**Comment by David-Moreira** [comment]
This seems to repeatedly be raising issues. I am also using Blazor Server and even locally it's easily reproducible just by typing fast.
I ended up just using ChangeTextOnKeyPress="false" as it's more safe. 
But maybe it should not be as easily susceptible to this occurring by default?
I know it's a good feature for Blazor WASM, but people will always be puzzled when using Blazor Server.

**Comment by ashishKumarAgarwal** [comment]
The issue still persists ,I am using blazor server side with autocomplete config like below:
ChangeTextOnKeyPress="false"
DelayTextOnKeyPress="true"
DelayTextOnKeyPressInterval="1000"

**Actual component**
<Autocomplete @ref="@Autocomplete"
              Style=""
              Data="@Endpoints"
              TextField="@(endpoint => endpoint)"
              ValueField="@(endpoint => endpoint)"
              SelectedValue="@EndpointName"
              SelectedValueChanged="@OnEndpointSelected"
              ChangeTextOnKeyPress="false"
              Filter="AutocompleteFilter.Contains"
              DelayTextOnKeyPress="true"
              DelayTextOnKeyPressInterval="1000"
              />
