### ISSUE TITLE
How to use multiselect in Autocomplete and SelectList 

### ISSUE THREAD

**Issue by mortezabarzkar** [Megabit/Blazorise#1436]
can you change the autocomplete and SelectList for  multipliable selection  ?

**Comment by stsrki** [comment]
SelectList shouldn't be a problem to have multiple selections. But for Autocomplete since it's using a Dropdown internally it is a lot heavy, so I should need to investigate if it makes sense to do it.

**Comment by hvnon** [comment]
Yah, up vote. That will be awesome if SelectList supports multiple selections like select2 do.

**Comment by mortezabarzkar** [comment]
@stsrki at first Thanks for this useful component.
when you can release selectlist ?

**Comment by stsrki** [comment]
It's still on the backlog. Meaning I will need to finish other things before I can pick it up.

**Comment by lrequena** [comment]
https://github.com/stsrki/Blazorise/issues/1436#issuecomment-722821015
> Yah, up vote. That will be awesome if SelectList supports multiple selections like select2 do.

+1 for that!

**Comment by stsrki** [comment]
Done in 0.9.5
