### ISSUE TITLE
Make bar extendable

### ISSUE THREAD

**Issue by MathieuDR** [Megabit/Blazorise#1444]
**Is your feature request related to a problem? Please describe.**
I'm trying to add some functionality and override some functionality of the navbar. But I want some different behaviour that I do not have access to.

* Not auto visible when breakpoint is hit
* Not auto visible when breakpoint is hit, on first render
* Some CSS when some cases are met, that I want to confine in the component

But because some classes are internal or virtual (`OnBreakpoint` & `Toggle`) you cannot fully extend/change the behaviour.

**Describe the solution you'd like**
Change toggle to protected virtual, OnBreakpoint should also be virtual and call `OnBreakpoint` on the `OnFirstAfterRenderAsync` to handle the visibility changes.

### Additional context
This would make things like the BarToggler also work with new extended classes.

**Comment by MitchellNZ** [comment]
The `Breakpoint` attribute is designed to toggle the visibilty of the Bar when hit.
Could you please explain a bit more about what you are trying to achieve by overriding it?

In regards to the `BarToggler` - release 0.9.2 adds a bunch for functionality this (especially when using `Vertical` modes - [see update docs](https://blazorise.com/docs/components/bar/#vertical-bar-toggler)).

Additionally, `IComponentActivator` changes (coming 0.9.3+) can help make the Bar more extendable.. at this stage, it is quite difficult to extend without breaking core functionality.

**Comment by stsrki** [comment]
IComponentActivator is implemented with the latest preview so it's now possible to customize any component.
