### ISSUE TITLE
Link Target property shouldn't be an enum but a String

### ISSUE THREAD

**Issue by MithrilMan** [Megabit/Blazorise#1448]
Link components Target property shouldn't be an enum because it can be used to specify a custom frame name by specification

https://www.w3.org/TR/html401/present/frames.html#target-info

**Comment by stsrki** [comment]
I would like to leave Target as it is and introduce additional parameters just for frames. Maybe name it `FrameTarget`?

**Comment by stsrki** [comment]
Going to be worked as part of larger project regarding the support for custom enumeration object #3073
