### ISSUE TITLE
Snackbar extension of the Location property for top of the screen.

### ISSUE THREAD

**Issue by Welchen** [Megabit/Blazorise#1451]
Wanted the ability to pick other locations where the snackbar could be.  Ultimately would like to put it in the top right corner. 

To not be a breaking change, a second property could be added to pick between Top and Bottom and default to Bottom.

**Comment by stsrki** [comment]
It's a nice feature to have. I can put it on the list for the next milestone as it shouldn't be too difficult.

**Comment by Sparkmb21** [comment]
Is it added ?

**Comment by stsrki** [comment]
@Sparkmb21 no, it is not yet added.

**Comment by adamreed90** [comment]
You can just override the `.snackbar-stack` css class and put it where you like :D

**Comment by kyletraynor-neo** [comment]
+1, this would be great to have
