### ISSUE TITLE
Cannot reference non-static field in RowRemoving on Datagrid

### ISSUE THREAD

**Issue by LouiseAJensen** [Megabit/Blazorise#1556]
I'm experiencing the exact same issue as is described here:
https://github.com/stsrki/Blazorise/issues/570

I'm getting this error:
`
A field initializer cannot reference the non-static field, method, or property 'DepartmentOverviewPage_.DeleteCase(string)'
`

I have:
```
private Action<CancellableRowChange<model.Department>> OnRowRemoving = o =>
{
    o.Cancel = DeleteCase(o.Item.DepartmentID); // can't call non-static method
};

private bool DeleteCase(string id)  // If this is static, then I can't use JsRuntime
{
    bool confirmed = JSRuntime.InvokeAsync<bool>("confirm", "Are you sure?").Result;
    if (confirmed)
    {
        return true;
        // Delete!
     }
     return false;
}
```

My version is
![image](https://user-images.githubusercontent.com/55488191/100774596-8754e980-3402-11eb-8a55-ba0664efb6c1.png)

**Comment by stsrki** [comment]
You have this `Action<CancellableRowChange<model.Department>>`. What is the `model.Department`? Is it a data-type or is it a object field or member?

**Comment by LouiseAJensen** [comment]
It is the data-type that I'm using as a TItem in my Datagrid

**Comment by stsrki** [comment]
I will need to see your models and a sample of DataGrid usage. If possible full reproducible sample would be great.

**Comment by rgomezia** [comment]
Hi , I have the same problem ¿ how can i solved this or view some example ? 
On my Grid i use RowRemoving="@OnRowRemoving" and use code , but not working i use version 9.5.3
