### ISSUE TITLE
Nested Dropdowns malfunctioning

### ISSUE THREAD

**Issue by danielheddelin** [Megabit/Blazorise#1559]
**Describe the bug**
I am trying to nest BarDropdown according to the example at [https://blazorise.com/docs/components/bar/#nested-dropdowns](https://blazorise.com/docs/components/bar/#nested-dropdowns)
When clicking "Nested toggler" the entire dropdown collapses.

**To Reproduce**
1. Add the code from the example
2. Click on the nested menu item "Nested toggler"
3. The entire dropdown disappears and no sub-items are displayed.

**Expected behavior**
The expected behavior is for the nested submenuitem "Nested item" to be displayed.

**Comment by stsrki** [comment]
It seems this is a bug.

@MitchellNZ Can you please check into this?

**Comment by MitchellNZ** [comment]
@stsrki sure!

@danielheddelin could you please provide a little bit more information
- Which Bar mode are you using? (Horizontal or Vertical)
- Which Blazorise version are you on? 
- Which provider are you using? (Bootstrap, Material, etc)

**Comment by danielheddelin** [comment]
@MitchellNZ absolutely!

- I am using the bar defined here: [https://blazorise.com/docs/components/bar/](https://blazorise.com/docs/components/bar/) which is a Horizontal bar.

- The version used is 0.9.2.2

- The provider is Material

The tree is:
```
<Bar Breakpoint="Breakpoint.Desktop"
     Background="Background.Light"
     ThemeContrast="ThemeContrast.Light">
    <BarMenu>
        <BarEnd>
            <AuthorizeView>
                <Authorized Context="Auth">
                    <BarItem>
                        <BarDropdown>
                            <BarDropdownToggle>Title</BarDropdownToggle>
                            <BarDropdownMenu>
                                <BarDropdown>
                                    <BarDropdownToggle>NestedTitle</BarDropdownToggle>
                                    <BarDropdownItem..../>
                                    <BarDropdownItem..../>
                                    <BarDropdownItem..../>
```

**Comment by MitchellNZ** [comment]
@danielheddelin thanks for reporting. 
I will get this fixed for 0.9.3 (possibly a 0.9.2.x patch if the changes aren't too large). 

It looks like I have overlooked nested Dropdowns for Horizontal bar! 😅 Sorry about that.

**Comment by danielheddelin** [comment]
Fantastic. Thank you!

**Comment by Smurf-IV** [comment]
Just as a note on my attempts to workaround this. The following also _does the same_ as the OP
```
                <BarItem>
                    <BarDropdown>
                        <BarDropdownToggle>
                            Top-level toggler
                        </BarDropdownToggle>
                        <BarDropdownMenu>
                            <BarDropdownItem>
                                Top-level item
                            </BarDropdownItem>
                            <BarDropdownItem>
                                <Field Horizontal="true" Class="no-padding">
                                    <FieldLabel Padding="Padding.Is1.FromRight">Plot</FieldLabel>
                                    <FieldBody>
                                        <select id="plot" >
                                            <option >None</option>
                                            <option >Stress (N/mm²)</option>
                                            <option >Thickness (mm)</option>
                                        </select>
                                    </FieldBody>
                                </Field>                            
                                </BarDropdownItem>
                        </BarDropdownMenu>
                    </BarDropdown>
                </BarItem>
```

**Comment by Smurf-IV** [comment]
Also, as an aside, the following also does not allow the visibility or selection of the sub menu
```
    <Dropdown>
        <DropdownToggle>Down</DropdownToggle>
        <DropdownMenu>
            <DropdownItem>Item 1</DropdownItem>
            <DropdownItem>
                <Dropdown Direction="Direction.Right">
                    <DropdownToggle>Right</DropdownToggle>
                    <DropdownMenu>
                        <DropdownItem>Item 1</DropdownItem>
                        <DropdownItem>Item 2</DropdownItem>
                    </DropdownMenu>
                </Dropdown>
            </DropdownItem>
        </DropdownMenu>
    </Dropdown>
```

**Comment by WayneHiller** [comment]
Any news on this issue being fixed?

**Comment by T3charmy** [comment]
Also running into this issue with bootstrap and 0.9.3 patch 7. Trying to have a Nested drop down in the NavBar. Any idea when this will be fixed?

**Comment by stsrki** [comment]
I can schedule it for v0.9.5. The current milestone is already packed.
