### ISSUE TITLE
Datagrid LoadingTemplate

### ISSUE THREAD

**Issue by mortezabarzkar** [Megabit/Blazorise#1620]
How can i invoke loading template to show ?

i need button to reload datagid , but when it invoked loading template dose not shown .

**Comment by mortezabarzkar** [comment]
@stsrki

**Comment by stsrki** [comment]
It's handled automatically by the DataGrid. And it shows only in `ReadData` mode.

You can't invoke it manually from outside.

**Comment by mortezabarzkar** [comment]
ok i know it
but is it better to have reload button template ?

**Comment by stsrki** [comment]
hmm it's not a bad idea. But it's better to have an API to force DataGrid to reload.

**Comment by stsrki** [comment]
Forgot to close this. It is already possible with `.Reload()` API.

eg.

`dataGridRef.Reload()`
