### ISSUE TITLE
Question : Does RadioGroup also support 'complex' classes ?

### ISSUE THREAD

**Issue by StefH** [Megabit/Blazorise#1635]
In my case I had a 'complex' class `X`.

``` c#
class X
{
  // properties
}
```

``` c#
public X X1 { get; set; } = new X();
public X X2 { get; set; } = new X();
```

``` xml
<RadioGroup TValue="X" Name="colors" CheckedValue="@checkedValue" CheckedValueChanged="@OnCheckedValueChanged">
    <Radio TValue="X" Value="@X1">Red</Radio>
    <Radio TValue="X" Value="@X2">Green</Radio>
</RadioGroup>
```

And setting the value did work, however the OnCheckedValueChanged was never fired.

Is this a known issue, or is something else wrong?

**Comment by stsrki** [comment]
I would guess it's the same problem like on other components. Every **value** must be represented as a **string** when presented to the DOM element. 

So I would try to `override ToString()` on `X` and make it a combination of different properties, enough to be unique. See if that works.

**Comment by StefH** [comment]
My current workaround is to use `GetHashCode()` (which is an integer).

``` html
<RadioGroup TValue="int" Name="AudioOnlyStreamInfos" @bind-CheckedValue="@CheckedAudioOnlyStreamInfoHashCode">
    @foreach (var info in AudioOnlyStreamInfos)
    {
        <Radio TValue="int" Value="@info.GetHashCode()">@info.GetTitle()</Radio>
    }
</RadioGroup>
```
