### ISSUE TITLE
Setting CellClass in DataGrid

### ISSUE THREAD

**Issue by marcusjm** [Megabit/Blazorise#1641]
Seems there is no way to set the Classes for Columns in the DataGrid. Any reason why there isn't a CellCssClass like for Header?

**Comment by stsrki** [comment]
There is. It's called `CellClass` and it can be applied to `DataGridColumn`. 

**Example**

```cs
CellClass="@((item)=>"some-class-name")"
```

It's a function to allow more control over conditional class-names, based on the current row item.

**Comment by marcusjm** [comment]
Oh, yeah that would be even better. Is it "heavy" to use?
