### ISSUE TITLE
Carousel with more than one visible slide

### ISSUE THREAD

**Issue by CobraCalle** [Megabit/Blazorise#1667]
Some times you would like to have a carousel showing more than one item at the same time. Would be a nice addition just defining the count of visible slides...

Like here:
https://mdbootstrap.com/snippets/jquery/ascensus/135508
https://www.codeply.com/go/s3I9ivCBYH/bootstrap-4-responsive-carousel-one-at-a-time

### Additional context
![image](https://user-images.githubusercontent.com/6218368/103671627-73f5ea80-4f7b-11eb-802b-a2f65a84de6e.png)

**Comment by stsrki** [comment]
Basic Blazorise components are just an abstraction over bootstrap(and other CSS providers) components. So they also take the cover of their default features and behavior. With this feature, we would go too far from that, and I'm not sure if it's even worth it. 

For now, it's low on the priority list, but I will leave it on the backlog. In case more people request it I will consider it again.

**Comment by CobraCalle** [comment]
👍
