### ISSUE TITLE
DataGrid switching between Inline Edit and Display loses applied Style's in Edit template

### ISSUE THREAD

**Issue by SimonAndrews** [Megabit/Blazorise#1682]
**Describe the bug**
When using a DataGrid and applying additional Styles to the DataGridCommandColumn using the CellStyle Property / Func, when you click on the Edit button to edit a row the html created loses the styles applied in Display mode.

**To Reproduce**
1. Setup a DataGrid
2. Add a method to add a style to the DataGridCommandColumn.CellStyle such as changing the background color
![image](https://user-images.githubusercontent.com/6128975/104040370-79e40980-51cf-11eb-8512-4c84798cd77b.png)
![image](https://user-images.githubusercontent.com/6128975/104040419-87998f00-51cf-11eb-973d-1f113a689fff.png)

3. Run site to see that the Styles have been applied while in display mode (can see that the td has the expected styles applied)
![image](https://user-images.githubusercontent.com/6128975/104040509-a26c0380-51cf-11eb-885b-240275eae241.png)
![image](https://user-images.githubusercontent.com/6128975/104040787-00005000-51d0-11eb-9ee3-5761108a8ef3.png)

4. Click the Edit button and you can see that the styles have been removed now in edit mode. (can see that the td has lost all styles)
![image](https://user-images.githubusercontent.com/6128975/104040584-bc0d4b00-51cf-11eb-986f-514477cc20a7.png)
![image](https://user-images.githubusercontent.com/6128975/104040637-cdeeee00-51cf-11eb-8532-a65fcb299d00.png)

5. Click Cancel or Save to go back to Display mode and you can see the style returns

**Expected behavior**
Styles should persist into the Edit Template.

Hope this makes sense 😃

**Comment by stsrki** [comment]
I don't think Display mode and Edit mode should share the same style. Rather they would have to have different styles.

Maybe I can add parameters to control styles in Edit mode...

**Comment by SimonAndrews** [comment]
Yep that would work and would provide full flexibility 😃

**Comment by stsrki** [comment]
Already fixed!
