### ISSUE TITLE
Datagrid - Unselect child data grid

### ISSUE THREAD

**Issue by devinbandara** [Megabit/Blazorise#1705]
Currently when you select a datagrid row that has a child grid, the child grid expands when you click on the parent row but if you click on the parent row again, you can not deselect the row and collapse all the child grid rows. The only way to collapse the child grid row is to click on another row.

Can you add a feature that collapses the Child Grid within a selected parent row when you click on the parent row?

**Comment by stsrki** [comment]
Just hold the CTRL key while clicking on a row. It's a standard way of unselecting the row and it is supported by DataGrid.

**Comment by paulosdfigueiredo** [comment]
If you really want unselect on click you can just use a SelectedEntity like this in your component.

```
protected TItem SelectedEntity
{
	get => this.selectedEntity;

	// unselect if it's an entity already selected
	set => this.selectedEntity = (this.selectedEntity != null && this.selectedEntity == value) ? null : value;
}        
```

**Comment by devinbandara** [comment]
> Just hold the CTRL key while clicking on a row. It's a standard way of unselecting the row and it is supported by DataGrid.

This action unselects the parent grid but does not collapse the child grid. Child grid stays expanded

**Comment by stsrki** [comment]
Child grid is controlled by `DetailRowTrigger` handler

**Example**

`DetailRowTrigger="@((item)=>item.Salaries?.Count > 0 && item.Id == selectedEmployee?.Id)"`

**Comment by StephenOTT** [comment]
> Just hold the CTRL key while clicking on a row. It's a standard way of unselecting the row and it is supported by DataGrid.

@stsrki does this still work?  I am unable to reproduce in the demo.

**Comment by stsrki** [comment]
@StephenOTT It works, I have just tried the demo in Chrome and Firefox. What browser do you have?

**Comment by StephenOTT** [comment]
I am on mac and tried with https://bootstrapdemo.blazorise.com/tests/datagrid

Using CTRL plus click on a row (all options turned off on the grid) just produces the browsers context menu.

Tried with latest FF, Chrome, and Safari using OSX latest

**Comment by stsrki** [comment]
I have no idea how to reproduce it without mac...

**Comment by StephenOTT** [comment]
To confirm the functionality:
 
<img width="1423" alt="Screen Shot 2021-06-21 at 5 13 55 PM" src="https://user-images.githubusercontent.com/1994838/122828746-113ba580-d2b4-11eb-82aa-ffba9bdf45e7.png">

If i were to CTRL+mouse left click `Caro` in row one, the Detail Row should collapse?

**Comment by stsrki** [comment]
Yes, it should collapse if it is opened. Or open if it is already collapsed. Basically toggle open states.

**Comment by StephenOTT** [comment]
Okay yup.. does not seem to work...

**Comment by stsrki** [comment]
I can only asume on Mac ctrl key is not detected properly. Is it named diferently?

**Comment by stsrki** [comment]
@StephenOTT Any chance you could clone Blazorise and debug it on Mac? In file `Blazorise.DataGrid._BaseDataGridRow` there is a `HandleSingleSelectClick` method. `eventArgs.CtrlKey` should be `true` if everything is good.

**Comment by StephenOTT** [comment]
Similar scenarios: https://stackoverflow.com/questions/45438932/ho-do-i-capture-ctrl-click-on-macos-with-d3js

Using the "Command" button: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey

**Comment by stsrki** [comment]
How it is usually done on Mac? The select and deselect of items..

**Comment by StephenOTT** [comment]
I have seen a mix of usage.  But If you follow close to how windows works: example: CTRL+W is close tab in a browser.  The Mac equiv is Command+W (MetaKey+W)

**Comment by GilShalit** [comment]
I can confirm this is working fine on Windows

**Comment by David-Moreira** [comment]
@StephenOTT I honestly don't know MAC very well.. But do you not have this corresponding key? 
Not the Command, but the Control.
![image](https://user-images.githubusercontent.com/22283161/123343970-c091aa00-d54a-11eb-8b7e-4fdf14cf9e79.png)

**Comment by JanVargovsky** [comment]
We have custom logic for (multi)selecting rows in DataGrid and the `args.MouseEventArgs.CtrlKey` doesn't work, meaning it's `false` when control is pressed on MAC.

**Comment by David-Moreira** [comment]
We need to do some digging...any developer around who knows how this is usually handled with a MAC?

Even with js you'd have the same problem right?

**Comment by David-Moreira** [comment]
Hello guys,
We are still working on getting the tools to troubleshoot this Issue.
In the meantime it would be great if you could help us. If you own a MAC, could you please visit our demo at :
https://megabit.github.io/DemoMetaKey/

Press the Mac's Ctrl Key while clicking the button and send us the log? 
Thanks!
