### ISSUE TITLE
Creation of BarDropdownDivider

### ISSUE THREAD

**Issue by joseazevedo** [Megabit/Blazorise#1706]
Creation of a BarDropdownDivider

**Comment by stsrki** [comment]
A little background here. @joseazevedo and I talked over Gitter and we realized there is no `BarDropdownDivider` component. There is only `DropdownDivider`. But we need the one that is just for the Bar component.

**Comment by stsrki** [comment]
@MitchellNZ I will assign this to you and you decide in which milestone to do it.

**Comment by stsrki** [comment]
Already created it.
