### ISSUE TITLE
BarToggler misaligned when horizontal scrolling

### ISSUE THREAD

**Issue by intiharj** [Megabit/Blazorise#1728]
Easy to see this problem by looking at attached image.

Using:   _<Bar Mode="BarMode.VerticalInline" CollapseMode="BarCollapseMode.Hide"_, and _<BarToggler Mode="BarTogglerMode.Popout">_

First, make the browser narrow so that the browser's horizontal scrollbar appears.  Then scroll to the right while watching the popout toggler.  When I do this, the small, curved toggler button does not move left with the rest of the Bar.
![bar](https://user-images.githubusercontent.com/6271320/105054687-48c1cf80-5a40-11eb-9ae0-8a9fb3ac5c59.jpg)

**Comment by stsrki** [comment]
Unable to reproduce it in the latest version.
