### ISSUE TITLE
Carousel component - slide animation not working

### ISSUE THREAD

**Issue by dumaisf** [Megabit/Blazorise#1745]
I use the carousel component in my blazor app. All work fine, including **controls** and **indicators**, except there is **no slide** animation. As if the _transition delay_ is zero.
On the same page, I create the **same carousel** (_same photos_) **without** the _carousel component_, using html **markup** from carousel bootstrap v4.6 documentation. Everything works fine including the slide animation.
There is something in your component that seem to suppress the slide animation.
```
    <Carousel @bind-SelectedSlide="@selectedSlide" Autoplay="false" Class="mb-5">
        @foreach (var photo in Photos)
        {
            <CarouselSlide Name="@photo.Rang.ToString()">
                <Image Source="@photo.Link" Text="" Display="Display.Block" Style="width: 100%;" />
            </CarouselSlide>
        }
    </Carousel>
```
Here is my index page:
```
<head>
    ...
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="_content/Blazorise/blazorise.css" rel="stylesheet" /> 
    <link href="_content/Blazorise.Bootstrap/blazorise.bootstrap.css" rel="stylesheet" />
    ...
</head>

<body>
    ...
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="_content/Blazorise/blazorise.js"></script>
    <script src="_content/Blazorise.Bootstrap/blazorise.bootstrap.js"></script>
    ...
</body>
```
I have tested with **dynamic** and **static** photos and I have the same problem with both.

**Comment by stsrki** [comment]
The reason why Bootstrap animation is working is that native elements are controlled with javascript and jquery.

Blazorise component on the other hand only switches CSS class names and because if that no animation can be seen. The only way to make it work is to call Bootstrap javascript methods but I'm still not sure if I'm OK with that.

**Comment by dumaisf** [comment]
Since all bootstrap javascript is already included in my page, why not let bootstrap do all the work with javascript? What is the benefit of your solution?

**Comment by stsrki** [comment]
The benefit is to do everything in C#, without the need to import `bootstrap.js` or `jquery.js` files. I know many Blazorise users, and also worked on some projects that do not want to depend on those files and want to do everything with C# code only.

Now, this is some idea that I'm been thinking about lately. Could be possible to detect if any `bootstrap.js` or `jquery.js` is available, and then use them instead of C#. But it will take some time until I try to implement it, considering all the work already scheduled.

**Comment by dumaisf** [comment]
Blazorise installation source require bootstrap.js and popper.js. So then why do I have to include bootstrap javascript for blazorise to work? I added bootstrap javascript after installing blazorise package. That's the only reason. I don't get it.

**Comment by stsrki** [comment]
They're left in the installation guide as an example. But they are not required for Blazorise to work. It all depends on your own project requirements.

**Comment by dumaisf** [comment]
Blazorise doesn't use bootstrap javascript, that's fine, it should be documented. Carousel component doesn't support slide animation, I understand everything is not perfect, but this should also be documented. Thanks.

**Comment by stsrki** [comment]
You're right, it should be documented, or mentioned somewhere. If everything was perfect I would have 10 people working on Blazorise, and these things would be left to a minimum. But, I'm not. I'm mostly working alone and in my free time. So, there no way I can think of, or do everything. I hope you understand that...

Also, if you feel something is missing or can be improved feel free to contribute and create a PR. Any help is appreciated.
