### ISSUE TITLE
DataGrid ItemsPerPageTemple, TotalItemsShortTemplate, TotalItemsTemplate not configurable

### ISSUE THREAD

**Issue by oaldrian** [Megabit/Blazorise#1816]
**Describe the bug**
When using a DataGrid some RenderFragments can be given to the DataGrid (FirstPageButtonTemplate, LastPageButtonTemplate, ...). This can be used to localize the pagination.
In the _DataGridPagination.razor there are already ItemsPerPageTemple, TotalItemsShortTemplate, TotalItemsTemplate used, but they are not accessible from outside. 

**To Reproduce**
1. Insert `<DataGrid ...></DataGrid>` into razorpage
2. Add `<DataGrid ...><FirstPageButtonTemplate>My own FirstPageButtonTemplate</FirstPageButtonTemplate></DataGrid>` --> Works
3. Try to add `<DataGrid ...><ItemsPerPageTemple>My own ItemsPerPageTemplate</ItemsPerPageTemple></DataGrid>` --> Does not work
4. Error message in Visual Studio: Unrecognized child content inside  component 'DataGrid'. The component 'DataGrid' accepts child content through  the following top-level items: 'PopupTitleTemplate', 'EmptyTemplate',  'LoadingTemplate', 'FirstPageButtonTemplate', 'LastPageButtonTemplate', 'PreviousPageButtonTemplate',  'NextPageButtonTemplate', 'PageButtonTemplate', 'DetailRowTemplate',  'DataGridColumns', 'DataGridAggregates', 'ChildContent'.

**Expected behavior**
ItemsPerPageTemple, TotalItemsShortTemplate, TotalItemsTemplate are configurable.

**Additional context**
As the RenderFragments already exist, and it is done for some of them already this should not be a big task.

**Comment by dkonstantinov193** [comment]
I believe this feature is just not completed yet, you can use the following workaround to apply custom stuff:

`<DataGrid Localizers="_dataGridLocalizers">
 </DataGrid>
@code
{
  private DataGridLocalizers _dataGridLocalizers;

  protected async override Task OnInitializedAsync()
    {
        _dataGridLocalizers = new DataGridLocalizers
        {
            ItemsPerPageLocalizer = new Blazorise.Localization.TextLocalizerHandler(ItemsPerPageLocalization)
        };

        await base.OnInitializedAsync();
    }

    public static string ItemsPerPageLocalization(string name, params object[] arguments)
    {
        return "записей на страницу";
    }
}'

**Comment by stsrki** [comment]
This issue is already fixed with some changes in v0.9.4. Closing now.
