### ISSUE TITLE
DataGrid Custom Button/Action Column

### ISSUE THREAD

**Issue by Jirubizu** [Megabit/Blazorise#1827]
**Is your feature request related to a problem? Please describe.**
I am trying to create a new column that holds custom action buttons. For example, I want a column called Actions that has a button in which will show a popup model once pressed. However, I have been unable to find anything through the documentation that would allow me to achieve this. 

**Describe the solution you'd like**
A new DataGrid column that accepts custom buttons and does not require a field parameter.

If there are existing methods of achieving this please let me know as I am lost at the moment.

**Comment by stsrki** [comment]
You can just use any existing field on your item model and add DataGridColumn. Then use DisplayTemplate to add any button inside of it.

Or you can inherit from DataGridColumn and try implementing what you need: look this https://github.com/abpframework/abp/blob/2c36a37933c7824974c966d696048a6930047ddb/framework/src/Volo.Abp.BlazoriseUI/Components/DataGridEntityActionsColumn.cs

**Comment by stsrki** [comment]
Custom actions will be possible with changes introduced in #2503
