### ISSUE TITLE
Add Selectable parameter to ListGroup

### ISSUE THREAD

**Issue by Jimmys20** [Megabit/Blazorise#1840]
Hello, I think it would be nice if ListGroupItem could also generate an `<a>` or `<button>` element with the list-group-item-action  class. What I want to achieve is this kind of html https://getbootstrap.com/docs/4.6/components/list-group/#links-and-buttons. The main reason I would like this functionality is because list-group-item-action has special highlight styling when it's hovered or focused, a plain `<li class="list-group-item">` does not have any hover/focus feedback.

Maybe something like this:
`<ListGroupItem Type="ListGroupItemType.ListItem">item 1</ListGroupItem>`
would generate
`<li class="list-group-item">item 1</li>`
ListGroupItemType.ListItem is the default Type

`<ListGroupItem Type="ListGroupItemType.Button">item 1</ListGroupItem>`
would generate
`<button type="button" class="list-group-item list-group-item-action">item 1</button>`

`<ListGroupItem Type="ListGroupItemType.Link" To="https://blazorise.com/">item 1</ListGroupItem>`
would generate
`<a href="https://blazorise.com/" class="list-group-item list-group-item-action">item 1</a>`

Or maybe use the Mode property of ListGroup component like this:
```
<ListGroup Mode="ListGroupMode.Static">
    <ListGroupItem>item 1</ListGroupItem>
</ListGroup>
```
would generate
```
<ul class="list-group">
    <li class="list-group-item">item 1</li>
</ul>
```
--------------------------------------------
```
<ListGroup Mode="ListGroupMode.Selectable">
    <ListGroupItem>item 1</ListGroupItem>
</ListGroup>
```
would generate
```
<div class="list-group">
    <button type="button" class="list-group-item list-group-item-action">item 1</button>
</div>
```

and finally

```
<ListGroup Mode="ListGroupMode.Selectable">
    <ListGroupItem To="https://blazorise.com/">item 1</ListGroupItem>
</ListGroup>
```
would generate
```
<div class="list-group">
    <a href="https://blazorise.com/" class="list-group-item list-group-item-action">item 1</a>
</div>
```

I believe it makes more sense for a Selectable ListGroup to generate button instead of li elements. This would make a ListGroup with Mode="ListGroupMode.Selectable" actually look 'selectable' because now it looks like a static list without any hover/focus highlight.

I don't know if this can be applied to the other css frameworks that Blazorise supports.

**Comment by stsrki** [comment]
All valid ideas. Although I like more the second example (`ListGroup Mode`).

I can consider adding it for one of the next versions. For now, it's not a priority since you can already use existing items, and using the `Clicked` event you will be able to fire any link or action.

**Comment by Jimmys20** [comment]
I agree, it's more of a nice-to-have feature, not something desperately needed. Thanks for including it in the plans for next versions.

**Comment by stsrki** [comment]
Maybe naming it `Hoverable` instead of `Selectable`. For example, Table component has a similar effect and it is named `Hoverable`

**Comment by Jimmys20** [comment]
In my opinion `ListGroupMode.Selectable` is fine, no need to rename. Bootstrap uses the word _actionable_ in their documentation

**Comment by stsrki** [comment]
Going to be Selectable!

**Comment by Jimmys20** [comment]
I think this issue can be closed now

**Comment by stsrki** [comment]
Yes, I emerged from my phone yesterday and forgot to close it. tnx
