### ISSUE TITLE
Suggestion: Select2 like component.

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#1890]
**Is your feature request related to a problem? Please describe.**
I currently took in a dependency to a select2.js in a project of mine with a component wrapping the interop, but would like to remove it, if there's already something similar in a blazor component.

**Describe the solution you'd like**
I was taking a look at AutoComplete extension and it already does part of it. Just that it could be augmented to have more features. Basically a merge between Select and AutoComplete.

**Examples:**
![image](https://user-images.githubusercontent.com/22283161/108622481-0de0fc00-7431-11eb-9019-9a1e96cb2a21.png)

![image](https://user-images.githubusercontent.com/22283161/108622600-cb6bef00-7431-11eb-8f85-b37b17255ed1.png)

![image](https://user-images.githubusercontent.com/22283161/108622604-d6268400-7431-11eb-89d8-2adda21a46c7.png)

**Comment by stsrki** [comment]
What is it missing? Multiple selection mode?

**Comment by David-Moreira** [comment]
There's a few things in my opinion that still makes me want to use select2 over autocomplete for now.

I know that you can have a placeholder saying "Search", but it's different, if you have that imediate feel of a dropdown with options. You'll know that you'll have to select something out of a pool of options. Also sometimes users, just want to click that arrow / field and look at the options, before starting to type and filtering out.
- So missing dropdown out of the gate + autocomplete 
![image](https://user-images.githubusercontent.com/22283161/108782925-65cc4f80-7564-11eb-94bb-e3ba10d9b8f9.png)

- Multiselect would actually be a neat one also

I really think the field where you select the data should be the same size as the Autocomplete by default. I know you can customize it yourself, but in my opinion makes for better UX?

Also I tried adding alot of values to the autocomplete data. I would expect it to have an item limit of like 5 or 10 and just have a scrollbar.
![image](https://user-images.githubusercontent.com/22283161/108782455-834ce980-7563-11eb-8bc2-cfa6de15b955.png)

There's also some cool things like grouping data, rendering html...(able to render images with the options) but well that's just extras...:P
Hope you don't mind me posting the library link here, so you can see some examples:
https://select2.org/getting-started/basic-usage

**Comment by paulosdfigueiredo** [comment]
I agree that AutoComplete should have some/all of this features.

When i use AutoComplete i feel that it should behave more like a searchable dropdown. just as @David-Moreira described.

**Comment by stsrki** [comment]
It seems Bootstrap now has better support for `datalist`, which can be used for better Autocomplete. https://getbootstrap.com/docs/5.0/forms/form-control/#datalists. I need to check all other providers too.

But in either case, we need to first update Bootstrap and that can take time considering some breaking change between v4 and v5. And I still need to decide do I support v4 in Blazorise.

**Comment by David-Moreira** [comment]
That does not seem an easy decision. But I would think bootstrap 4 is too popular to drop support right off the bat. In my opinion there may be too many large projects depending on bootstrap 4 where developers just don't have the possibility / resources to invest on upgrading to bootstrap 5 with ease. 

Which would also mean that they wouldn't be able to keep using the latest blazorise. You could loose a sizable demographic here.

I'm targetting bootstrap 4 myself and I'm not sure how soon will I be able to start migrating to bootstrap 5.

Keeping support on v4 shouldn't be exactly hard either. Has the provider should remain mostly stale with what's already been developed?

**Comment by stsrki** [comment]
Yeah, my thinking also. But on the other hand, the migration shouldn't be hard if people were working with Blazorise components and not modifying CSS too much. But even in case they did, I think the v5 and v4 are not that much different, for the most part. But that all depends on how people are using it.

What I was thinking was to create `Blazorise.Bootstrap` and `Blazorise.Bootstrap4` projects. All existing code would go into Bootstrap4 and all new stuff into the Bootstrap project. Or vice versa. It's all still just an idea.

**Comment by David-Moreira** [comment]
Well I can't speak to how hard it is or not. I haven't taken a good look at bs5 yet. But I'm guessing people could be using a mix of blazorise with something else. Or just grabbing a few blazorise extensions that are interesting to their use cases.

Yea exactly my thoughts for the provider support. 
If like you said bs5 isn't that much different you could potentially inherit bootstrap provider 5 components from blazorise.boostrap4 and just override the breaking changes. But that can potentially turn out to be harder to maintain... Or even easier, I don't know, you should know that better yourself. 😅

**Comment by angelru** [comment]
I was wondering if autocomplete accept images next to text?

**Comment by stsrki** [comment]
It can with the use of `ItemContent`.

Look at the example **Extending with custom item content** on https://blazorise.com/docs/extensions/autocomplete
