### ISSUE TITLE
Clearing filters with a separate button (outside the DataGrid)

### ISSUE THREAD

**Issue by kswoll** [Megabit/Blazorise#1915]
**Is your feature request related to a problem? Please describe.**
I want to be able to clear the filters of the `DataGrid` component.  This could be straightforward, but because the `DisplayableColumns` property is protected instead of public, you must subclass `DataGrid` in order to do this.  Please see [this StackOverflow question](https://stackoverflow.com/a/66357930/189950) and answer for a realworld scenario with a concrete workaround that solves the issue.

**Describe the solution you'd like**
I suggest that the `DisplayableColumns` property be made public for user scenarios such as these.

I can make a PR for this if we agree on a solution.

**Comment by kswoll** [comment]
Alternatively, since changing `protected` to public is, I believe, a breaking change, we could expose a new property that simply maps to `DisplayableColumns`.

**Comment by David-Moreira** [comment]
Hello, I might be missing something here, but why is `protected `to `public `a breaking change?

We've been talking about this today. The real solution is exposing some kind of API with the internals to use the Datagrid commands, we need to find a sound solution. I have a few, but I need to investigate further first. If you have any good ideas... :D

So for the ClearFilter question, you can also just use the ClearFilter command... which generally makes more sense to call in the actual provided commands, or you might be missing on usefull internal logic by manually doing it yourself.

And actually you can check yet another temporary workaround I just tested today here: #1914

**Comment by kswoll** [comment]
So I looked at the `ClearFilter` command and it appears to me that it is only for a specific column?  Please correct me if I'm wrong, as I was only introduced to this libarary while trying to help the OP on the SO question.  But the original use case was to be able to clear _all_ the filters of _all_ the columns.  This (I believe) would require iterating over all the columns individually.  That said, I agree with you that utilizing that would be preferable to setting the property to null explicitly.  I'll have to mull that over a bit to see if that means I should change my answer.

As to why it would be a breaking change, I was erroneously considering the case of _overriding_ a `protected` member.  In this case, since the method is not `virtual`, that is actually not a problem, so merely changing the access to `public` would be non-breaking.

**Comment by David-Moreira** [comment]
It's the equivalent to the clear filter command on this demo page that clears every column filter:
https://bootstrapdemo.blazorise.com/tests/datagrid

(Basically does the same iteration that you did, and I think a bit more)
PS: The FirstName and City aren't being cleared because they have a bug on that demo version

**Comment by stsrki** [comment]
The `ClearFilter` command clears all the filters. There is no API to clear each column individually.

The example in the demo is wrong because it's an older version that had a bug that was fixed in the meantime. We will release a new demo app soon.
