### ISSUE TITLE
EditTemplate with select returning null in detailrow

### ISSUE THREAD

**Issue by davazlan** [Megabit/Blazorise#1940]
I have the following code:

```<DataGridColumn TItem="UPVShared.Models.Project" Field="@nameof(UPVShared.Models.Project.Name)" Caption="Project Name" Editable="true" Filterable="true" PopupFieldColumnSize="ColumnSize.Is12">
<EditTemplate>
                                    <Select TValue="UPVShared.Models.Project" SelectedValue="@((UPVShared.Models.Project)(context.CellValue))" SelectedValueChanged="@((v)=>context.CellValue=v)">
                                        @if (@SpidProjects != null && @SpidProjects.Any())
                                        {
                                            <SelectItem TValue="UPVShared.Models.Project" Value="null" Disabled="true">- Select a Project -</SelectItem>
                                            // there are projects, show them
                                            foreach (var proj in SpidProjects)
                                            {
                                                <SelectItem TValue="UPVShared.Models.Project" Value="@proj">@proj.Name</SelectItem>
                                            }
                                        }
                                        else
                                        {
                                            <SelectItem TValue="UPVShared.Models.Project" Value="null" Disabled="true">... no SPID projects found</SelectItem>
                                        }
                                    </Select>
                                </EditTemplate>...
```

All you neet to know is that "Project" is a class and it has an attribute "Name" which is a string and a "ProjectId", which is a GUID.

Whenever I select an Item in the edit form, I get "null" on my "rowcreated" method:

```
void OnProjectCreated(SavedRowItem<UPVShared.Models.Project, Dictionary<string, object>> e)
    {
        if (!string.IsNullOrEmpty(e.Item.Name) && selectedModel.Projects.Exists(p => p.Name.ToUpper().Equals(e.Item.Name.ToUpper())))
        {
            // TODO: alert, don't add the project if it already exists
            return;
        }
        selectedModel.Projects.Add(e.Item);
        tasksService.UpsertModel(selectedModel);
    }
```

But, with the following code, I get the string I expect (but it's not elegant at all):

```<DataGridSelectColumn TItem="UPVShared.Models.Project" Field="@nameof(UPVShared.Models.Project.Name)" Caption="Project Name" Editable="true" Filterable="true" PopupFieldColumnSize="ColumnSize.Is12">
                                <!-- TODO: Use a select list for Editing -->
                                <EditTemplate>
                                    <Select TValue="string" SelectedValue="@((string)(context.CellValue))" SelectedValueChanged="@((v)=>context.CellValue=v)">
                                        @if (@SpidProjects != null && @SpidProjects.Any())
                                        {
                                            <SelectItem TValue="UPVShared.Models.Project" Value="null" Disabled="true">- Select a Project -</SelectItem>
                                            // there are projects, show them
                                            foreach (var proj in SpidProjects)
                                            {
                                                var v = $"{proj.IndustrialComplexNo};;{proj.Name};;{proj.SpidSiteIni}";
                                                <SelectItem TValue="string" Value="@v">@proj.Name</SelectItem>
                                            }
                                        }
                                        else
                                        {
                                            <SelectItem TValue="string" Value="null" Disabled="true">... no SPID projects found</SelectItem>
                                        }
                                    </Select>
                                </EditTemplate>
                            </DataGridSelectColumn>
```

Am I doing something wrong? Could the fact that the "Project" class has a GUID attribute be a problem?

**Comment by stsrki** [comment]
Are you talking about the temporary variable? `var v = $"{proj.IndustrialComplexNo};;{proj.Name};;{proj.SpidSiteIni}";` ?

If yes, then it's needed. That is how Blazor works. You can find many examples and why it behaves like that if you google. 

https://github.com/dotnet/aspnetcore/issues/22302

**Comment by davazlan** [comment]
Hi, no, that’s the dirty trick I did to solve the problem, which is that I can’t access the base class (Project) from the select. So instead of accessing the parent object, I create that ugly string to read it as the “Name” of the object, then split it, then look for the object in my observable collection of <Project>. It’s really dirty, but I don’t know how else to do it.


David Vazquez Landa
CAE DevOps @ Digitalization & IT

Mobile: +49 173 307-4665, Email: david.vazquez-landa@basf.com
Postal Address: BASF SE , GE/DI - Q920, Carl-Bosch-Strasse 38, 67056 Ludwigshafen am Rhein, Germany
[cid:image003.png@01D70EB2.B4848430]
BASF SE, Registered Office: 67056 Ludwigshafen, Germany
Registration Court: Amtsgericht Ludwigshafen, Registration No.: HRB 6000
Chairman of the Supervisory Board: Kurt Bock
Board of Executive Directors:
Martin Brudermueller, Chairman; Hans-Ulrich Engel, Vice Chairman;
Saori Dubourg, Michael Heinz, Markus Kamieth, Wayne T. Smith

Information on data protection can be found here: https://www.basf.com/global/en/legal/data-protection-at-basf.html

**Comment by David-Moreira** [comment]
@stsrki does Select work with complex types as @davazlan was trying on the first example?
Othwerise, I don't think I get it. 
Why not just use the ProjectId itself as the unique value, even if having to call ToString()? 
Or just have a "computed property" on your model that compiles the unique value itself?
Or hashing the model object?

**Comment by stsrki** [comment]
@David-Moreira No, complex types are not supported. If it would be just for Blazor it wouldn't be a problem. But considering we must work with DOM, everything will/must be converted into a `string`. And complex types will not work unless there is some kind of conversion involved. Just as you mentioned.

@davazlan The best option is to use some kind of unique ID and assign it to a select item. Or as David mentioned, have a converted from a complex type into a string value.

**Comment by davazlan** [comment]
I tried with the ProjectId. The problem I had there is that the property is a Guid and I couldn’t get rid of an exception trying to cast string to Guid.


David Vazquez Landa
CAE DevOps @ Digitalization & IT

Mobile: +49 173 307-4665, Email: david.vazquez-landa@basf.com
Postal Address: BASF SE , GE/DI - Q920, Carl-Bosch-Strasse 38, 67056 Ludwigshafen am Rhein, Germany
[cid:image003.png@01D7100E.610B3530]
BASF SE, Registered Office: 67056 Ludwigshafen, Germany
Registration Court: Amtsgericht Ludwigshafen, Registration No.: HRB 6000
Chairman of the Supervisory Board: Kurt Bock
Board of Executive Directors:
Martin Brudermueller, Chairman; Hans-Ulrich Engel, Vice Chairman;
Saori Dubourg, Michael Heinz, Markus Kamieth, Wayne T. Smith

Information on data protection can be found here: https://www.basf.com/global/en/legal/data-protection-at-basf.html

**Comment by davazlan** [comment]
Thanks guys, that explains a lot actually.

David Vazquez Landa
CAE DevOps @ Digitalization & IT

Mobile: +49 173 307-4665, Email: david.vazquez-landa@basf.com
Postal Address: BASF SE , GE/DI - Q920, Carl-Bosch-Strasse 38, 67056 Ludwigshafen am Rhein, Germany
[cid:image003.png@01D7100E.78401090]
BASF SE, Registered Office: 67056 Ludwigshafen, Germany
Registration Court: Amtsgericht Ludwigshafen, Registration No.: HRB 6000
Chairman of the Supervisory Board: Kurt Bock
Board of Executive Directors:
Martin Brudermueller, Chairman; Hans-Ulrich Engel, Vice Chairman;
Saori Dubourg, Michael Heinz, Markus Kamieth, Wayne T. Smith

Information on data protection can be found here: https://www.basf.com/global/en/legal/data-protection-at-basf.html

**Comment by stsrki** [comment]
You must define TValue as Guid and not `TValue="UPVShared.Models.Project"`. Considering you need nullable value it should be `TValue="Guid?"`.
