### ISSUE TITLE
Bootstrap > Modal Dialog > Support modal-dialog-scrollable

### ISSUE THREAD

**Issue by Jman012** [Megabit/Blazorise#1946]
**Is your feature request related to a problem? Please describe.**
I am attempting to use the modal-dialog-scrollable feature described here: https://getbootstrap.com/docs/4.6/components/modal/#scrolling-long-content. Unfortunately, the `Class="modal-dialog-scrollable"` on the `<Modal />` component and on the `<ModalContent />` component fail to add the class on the `div.modal-dialog` properly.

**Describe the solution you'd like**
Either an explicit property on the `Modal` component or a `DialogClass` property on the `ModalContent` component to be able to set this class on the Bootstrap modal.

**Comment by stsrki** [comment]
I never noticed `"modal-dialog-scrollable"` before. Otherwise, I would have added it already. Thank you for reporting it.

A new release is planned for today and I will try to see if it makes little trouble to add this feature. Won't make promises :)

**Comment by stsrki** [comment]
Moving for 0.9.4 milestone. While Bootstrap and Bulma are fairly easy to do, AntDesign requires more work.

**Comment by EnsignPayton** [comment]
I second the `DialogClass` idea. I'm currently using a custom implementation of exactly that to add classes to the `modal-dialog` div.

I'm using a custom implementation of `ModalContent`, mostly copy-pasted from the Bootstrap implementation, with the following modifications:

```cs
[Parameter]
public string DialogClass
{
    get => this.dialogClass;
    set
    {
        this.dialogClass = value;
        this.DirtyClasses();
    }
}

...

// in BuildDialogClasses:
builder.Append( this.DialogClass );
```

Would be nice to have this available on the base `ModalContent` out of the box

**Comment by djlaney3** [comment]
When will we see this feature?

**Comment by stsrki** [comment]
It's scheduled for 0.9.4, so soon, in one of the next previews.
