### ISSUE TITLE
FileEdit ioexception file is used by another process

### ISSUE THREAD

**Issue by mliguori** [Megabit/Blazorise#1948]
In a blazor server project, trying to use the file after the upload, I get the said exception.

this is the tag syntax

`<FileEdit Multiple="false" Filter=".xls, .xlsx, .xlsm" Changed="@OnFileChanged" />`

this is the code fragment I use:

   ```cs
 async Task OnFileChanged(FileChangedEventArgs e)
    {
        if (e.Files.Length>0)
        {
            var SaveName = e.Files.First().Name;
            var SavePath = Path.Combine(env.ContentRootPath, "upload");
            if (!Directory.Exists(SavePath))
                Directory.CreateDirectory(SavePath);
            SavePath = Path.Combine(SavePath, SaveName);
            using (var stream = new FileStream(SavePath, FileMode.Create))
            {
                await e.Files.First().WriteToStreamAsync(stream);
                await stream.DisposeAsync(); // I have added this to ensure disposal of stream even if the using should be already ok
            }
            await processFile(SavePath); <-- the exception happens inside this method
        }
    }
```
The file is correctly saved and I can process it using a button that invoke processFile, but after and outside the upload process.

I am currently using another file upload control and the behavior is correct without exeptions. Only the control is changed, the rest of code is the same.

Thank you.

**Comment by stsrki** [comment]
It's probably something with thread blocking. Can you try with `await InvokeAsync( async ()=> await processFile(SavePath);)`

**Comment by David-Moreira** [comment]
@stsrki I was taking a quick look at FileEdit code. I don't think I see the internal stream being closed and releasing the file. maybe I'm just missing smthg?
