### ISSUE TITLE
Support for multiple DataGridCommandColumn's

### ISSUE THREAD

**Issue by angelru** [Megabit/Blazorise#1987]
It is not possible to do something like that, right? I'd like the edit buttons on the right and the add button on the left.
 
```
<DataGridColumns>
        <DataGridCommandColumn TItem="Item" EditCommandAllowed="false" />
        <DataGridColumn TItem="Item"  Editable="true" />
        <DataGridColumn TItem="Item" Editable="true" />
        <DataGridCommandColumn TItem="Item" NewCommandAllowed="false" EditCommandAllowed="true">
            <EditCommandTemplate>
                <Button Color="Color.Primary" Clicked="@context.Clicked">Edit</Button>
            </EditCommandTemplate>
        </DataGridCommandColumn>
    </DataGridColumns>
```

**Comment by stsrki** [comment]
It is not working because internally we keep a reference to only one command column. So when you add another column it will get the options from the first.

Yuu can just create a regular `DataGridColumn` and then use `DisplayTemplate` to add the buttons.

**Comment by angelru** [comment]
but then, if I want the button to show a modal, I have to do it manually and I can't take advantage of TItem, right?

**Comment by stsrki** [comment]
Yes, that will only be possible once we implement the new API. I will put it on the list for next milestone.

**Comment by angelru** [comment]
thanks!!! great job

**Comment by angelru** [comment]
Thank you very much, but I don't want it to appear in all rows. I can also hope that this issue https://github.com/stsrki/Blazorise/issues/1986# can be set independently and thus leave only the new button and use `DataGridCommandColumn `on the left

**Comment by David-Moreira** [comment]
Yes, it does work. You can have the New Button placed on the ButtonRow, which is placed on the Pager and not the table itself.
You have examples in the demo and in the docs: https://blazorise.com/docs/extensions/datagrid/#datagrid-button-row
Just let us know if you have any doubts.

**Comment by angelru** [comment]
Yes, I thought of ButtonRow, but it is that the pager above is also shown as I comment in the issue, I need it to be independently (these requirements are from the client, not mine)

**Comment by David-Moreira** [comment]
There are some more hacks you can do... Like applying css to the pager setting display:none to the stuff that you would like to not be showing. Just so you can satisfy your client requirements.
But of course, those are temporary hacks, hopefully we can have the suggestion of #1986 about decoupling pager and ButtonRow soon, giving some more flexibility.

**Comment by angelru** [comment]
The display: none trick is fine, but what if I want to display the page at the bottom? wouldn't it apply too?

Great job!

**Comment by David-Moreira** [comment]
Haha that seems harder. Not sure if you can have css specificity for that one.
Maybe if you play with :nth child selector you can get there...

**Comment by David-Moreira** [comment]
Again this is just a dumb solution / hack. But sometimes we just have to find other ways to get stuff working.

I got it working with these, assuming you have a data-grid class wrapping the Datagrid:
```
.data-grid .row.justify-content-between:nth-child(3) .col-auto.d-flex:first-child {
    display: none !important;
}
.data-grid .row.justify-content-between:first-child .col-auto.d-flex:nth-child(2) {
    display: none !important;
}
.data-grid .row.justify-content-between:first-child .col-auto.d-flex:nth-child(3) {
    display: none !important;
}
```


![image](https://user-images.githubusercontent.com/22283161/110853859-07b1a300-82ac-11eb-952f-fa7ebd87326b.png)

**Comment by angelru** [comment]
hahahaha, it's been a long time since I play css very thoroughly, I didn't remember child! Thanks a lot

**Comment by stsrki** [comment]
@David-Moreira That is actually a good solution.

**Comment by stsrki** [comment]
With the new set of public APIs in #2503, this feature is not needed. YOu will be able to create your command column or place command buttons wherever you want.

Closing it now.

**Comment by angelru** [comment]
an example of how to add that button wherever you want?

**Comment by stsrki** [comment]
```cshtml
<Button Color="Color.Primary" Clicked="@(()=>dataGrid.New())">New Command Example</Button>
<Button Color="Color.Secondary" Clicked="@(()=>dataGrid.Edit(dataModels[2]))">Edit Command Example</Button>

<DataGrid @ref="dataGrid"
            TItem="Employee"
            Data="@dataModels">
    ...
</DataGrid>
```
