### ISSUE TITLE
Fixes 0.9.3

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#1991]
## 0.9.3.10

- #2480 Pagination Items not aligned straight in DataGrid
- #2531 DataGrid.RowSelectable not firing when clicking the DataGridMultiSelectColumn checkbox directly
- #2539 Settings ProgressBar Max doesn't do anything
- #2413 DataGrid inline edit mode forgets text alignment settings
- #2533 DataGridMultiSelectColumn & Filtering Misbehavior
- #2549 DataGrid Selection Behavior on Switching Single / Multiple

## 0.9.3.9

- #2462 Time picker TimeChanged stopped firing
- #2474 Modal fails intermittently with InvalidOperationException: Sequence contains no elements error (#2475 by @GordonRudman)
- #2393 DataGrid Button row disappears on small screens

## 0.9.3.8

- #2437 Time Picker malfunction in 0.9.3.7
- #2435 Date component Max attribute not working as expected with InputMode.DateTime

## 0.9.3.7

- #2268 SetDeltaAsync API in Rich Text control does not work (#2286 by @njannink)
- #2324 Multi-select SelectedValues returns distinct values
- #2321 PR: set dotNetObjectRef to null on dispose
- #2280 Datagrid PageSize bugs
- #2351 24 time format of TimePicker
- #2413 DataGrid inline edit mode forgets text alignment settings
- #2374 EditText/Tab Underline - Theme
- #2395 Line charts throw error if dateset contains NaN data value

## 0.9.3.6

- #2262 Show zeros when DataGrid have no items
- #2253 Link-Type Button cannot be Disabled
- #2240 FileEdit filename text overflows the component
- #2252 FileEdit Validation

## 0.9.3.5

- #2182 Update fr.json
- #1083 Switch ReadOnly, Disabled unexpected behavior
- #1823 TextEdit FocusAsync "Event is already tracked" exception
- #2215 Modal is not centered when it is set to center
- #2211 ReadOnly NumericEdit still editable using arrow keys

## 0.9.3.4

- #2139 Vertical button group is not working
- #2146 DataGrid accents
- #2134 Material Modal behind Layoutheader
- #2122 Unable to select items using Autocomplete extension
- #2165 Memory-leak on Server-side Blazor
- #2155 Typography components should not default to the text-align left

## 0.9.3.3

- #2082 DataGrid editing nested fields
- #2044 JSException when viewed on Edge mobile app
- #1959 Hamburger Menu Drop Down Not Correct when Browser is Refreshed
- #2085 TextEdit input events refactoring
- #1134 Slider refresh value

## 0.9.3.2

- #2059 MultiSelect dos not closed oblur
- #2066 SideBarNavigation doesn't display drop down arrow with upgrade of Blazorise.Bootstrap and Blazorise.Icons.FontAwesome.
- #2065 Class setting on DataGridRow Command
- #2054 Debug symbols for Blazorise
- #2078 Validation threading issue

## 0.9.3.1

- #1983 What is the correct way to use Validation with the SelectList in version 0.9.3
- #1979 Error on working project After upgrade to 0.9.3
- #1989 Step is missing theme CSS for primary color
- #2014 Italian translating errors
- #2008 Datagrid: Resize feature: js should always check if exists even if halfway through work
- #2029 Slider error when changed
- Add null checks for bar states
- #2030 DataGrid's Modal/Popup behavior
- #2011 MemoEdit - Size doesn't work
- #2010 ThemeStepsOptions doesn't work (Material)
- #2016 AntDesign Select does not work
- #2036 Modal scrolling issue
- #2051 [RadioGroup] Manual validation
- #1887 introduce difference for disabled radio button

**Comment by Rubenisme** [comment]
When are you releasing 0.9.3.7 on nuget.org? ;)
