### ISSUE TITLE
DataGrid API

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#1994]
This will be the main ticket for the planning and work process of DataGrid API which would allow us to make changes programmatically.

## Suggestions

- [x] Add method to reset EditMode, eg `.ResetEditMode()`, `.ClearEditMode()` or `.SetEditMode(EditMode.None)`

**Comment by sks-ttaylor** [comment]
I would like to see an insertable FooterTemplate:  Allowing TableFooterRow and TableFooterRowCell

**Comment by tesar-tech** [comment]
- I am currently missing the option to open edit mode by clicking on the (and selecting) specific row. 
- Also, for more complicated scenarios would be helpful to have multiple detail/edit views. For example for editing Salaries in Demo table... Clicking specific button in a row would open specific detail, etc...

**Comment by fori920** [comment]
I'd be helpful to trigger grid refreshes programmatically as well.

**Comment by stsrki** [comment]
We've dome almost all except for

> Also, for more complicated scenarios would be helpful to have multiple detail/edit views. For example for editing Salaries in Demo table... Clicking specific button in a row would open specific detail, etc...

considering we're limited with time we will move to the next milestone.
