### ISSUE TITLE
Backgroud colum on Barchart not show color

### ISSUE THREAD

**Issue by tupx333** [Megabit/Blazorise#2013]
**Describe the bug**
The first column does not show color if have 2 data

**To Reproduce**
1.Click on firt colum barchart
2 .See error . it don't have color backgroud 
3. IF I click redraw the color is back

**Here my code**
https://github.com/tupx333/sss/blob/main/Untitled-1.razor

**Screenshots**
![Unti3tled](https://user-images.githubusercontent.com/80302740/110763747-cb1e8100-8284-11eb-82af-143498ae59d9.png)

**Comment by stsrki** [comment]
Should be possible in the new v1,x, with v3 chart support.
