### ISSUE TITLE
Add async/await support for event handlers

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#2052]
Most of the internal events are regular `event EventHandler` and they don't work well for async-await scenarios. 

eg. `public event EventHandler<ValidationStatusChangedEventArgs> ValidationStatusChanged;`

Investigate if they can be converted to real Task-able events. Preferably to also be subscribed with `+=`.

**Sources**

https://stackoverflow.com/questions/12451609/how-to-await-raising-an-eventhandler-event

**Comment by David-Moreira** [comment]
I don't really think events mesh well with async altought I've seen some async implementations of it.

What about just propagating with EventCallbacks?

**Comment by stsrki** [comment]
The problem with EventCallbacks is that they can also trigger re-rendering of a component and I don't want that to happen all the time as it can degrade performance.

**Comment by David-Moreira** [comment]
Ah I see. There's a good pattern by Steven sanderson to do precisely that with async support if I'm not mistaken. I'll search for it.

**Comment by David-Moreira** [comment]
@stsrki See if this helps:
https://gist.github.com/SteveSandersonMS/8a19d8e992f127bb2d2a315ec6c5a373

**Comment by stsrki** [comment]
I know about Steves pattern. You can see it in my Async Validation PR https://github.com/stsrki/Blazorise/pull/1958/files :)

Maybe it could help with this, but I want to have a way of subscribing to multiple event handlers for one event(`+=`), and I don't think EventCallback supports that.

**Comment by David-Moreira** [comment]
I see, seems interesting, great! I haven't taken a look at your PR yet. This month is kinda tight... 😑

As for the multiple, maybe you can just adapt it?

**Comment by stsrki** [comment]
Yeah, I will investigate once I go back to this. Here I just create a ticket so I don't forget about it.

**Comment by angelru** [comment]
a doubt, to an event you can put async and you can execute asynchronous functions, or is it that they want the event itself to be Task?

**Comment by stsrki** [comment]
You can put `async void` but there are problems when you try to await multiple events.
