### ISSUE TITLE
Accordion with one Item

### ISSUE THREAD

**Issue by itsLollo1000** [Megabit/Blazorise#2102]
Creating an Accordion and filling it with only one item results into unexpedted design

I am unable to reproduce it on your demo page but I have tried various things and didnt found a thing.
Even tried a new Layout with only:

```
@inherits LayoutComponentBase
@Body
```

Normal cards beahve as expected.

![image](https://user-images.githubusercontent.com/10349466/112457882-7981f600-8d5c-11eb-8dcc-f2f250e4dc6f.png)
![image](https://user-images.githubusercontent.com/10349466/112458003-99b1b500-8d5c-11eb-9fc2-690cb408a381.png)

**Comment by stsrki** [comment]
Can you post a code-sample so I can reproduce it?

**Comment by itsLollo1000** [comment]
> Can you post a code-sample so I can reproduce it?

Just create an accordion and fill it with just one item. I created a new empty project and the same happened.

Ill shortly create another project via git so you can have a look at it.

**Comment by itsLollo1000** [comment]
https://github.com/itsLollo1000/Accordion

**Comment by stsrki** [comment]
I tried your example and I don't see any problem. What exactly I need to look for?

**Comment by itsLollo1000** [comment]
As in the pictures look at the bottom of the card it is not renedered 100% correclty. It is cut of a little bit.
This only happens when the accordion is filled with one card

![image](https://user-images.githubusercontent.com/10349466/116665492-240fb900-a99a-11eb-97ee-41b21bdbb923.png)

**Comment by stsrki** [comment]
The problem was in duplicate bootstrap files.

Remove this line from `_Host.cshtml`: 

`<link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />`

**Comment by itsLollo1000** [comment]
> The problem was in duplicate bootstrap files.
> 
> Remove this line from `_Host.cshtml`:
> 
> `<link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />`

Yes I can approve that 🤦
