### ISSUE TITLE
LiveChart stops streaming

### ISSUE THREAD

**Issue by bestpika** [Megabit/Blazorise#2125]
**Describe the bug**

<https://bootstrapdemo.blazorise.com/tests/livecharts>
In your demo, LiveChart often stops streaming.
Then whenever it stop streaming I see the following error in the console.

**To Reproduce**

1. Go to the web page.
1. Move your mouse over the point and pass over a few more points.
1. Move the mouse out of the chart.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/5698157/112971333-b0ec0a80-9181-11eb-8f0b-9a33d4c21abe.png)

**Additional context**

**Comment by bestpika** [comment]
This bug seems to be still present in v0.95.
<https://blazorise.com/docs/extensions/chart-live>
![image](https://user-images.githubusercontent.com/5698157/142605272-3257e20d-9124-4f08-bf10-aee8ee413a53.png)

**Comment by stsrki** [comment]
I think the bug is somewhere in the actual chart streaming plugin. You can only try using a different version.

Currently, I'm upgrading to the ChartJS v3 for the next Blazorise release, along with the newest streaming plugin.

**Comment by stsrki** [comment]
#2229

**Comment by stsrki** [comment]
This is fixed with the new v3 support.
