### ISSUE TITLE
Escape key in Autocomplete component closes Modal

### ISSUE THREAD

**Issue by Jman012** [Megabit/Blazorise#2138]
**Describe the bug**
While typing in the Autocomplete text box that is present in an open Modal, the escape key propagates up to the Modal. The result is that the Autocomplete clears its value, but the Modal also closes.

**To Reproduce**
1. Embed an Autocomplete with some options in a Modal 
2. Open the Modal
3. Start typing in the Autocomplete and have some autocomplete options appear
4. Press the Escape key on your keyboard

**Expected behavior**
I expect that the Autocomplete will clear its value, and that the Modal will stay open. The Autocomplete does clear its value, but the event propagates to the Modal and the Modal closes.

**Comment by stsrki** [comment]
Unfortunately, I would not be able to fix it for 0.9.3 without introducing some breaking. So I'm moving it to the next milestone.

**Comment by stsrki** [comment]
To fix this, we would have to create a completely new way of tracking closable components in the order of the opening, and according to their scope(one closable inside of another closable, etc.)

Considering we're almost at the end of the 0.9.4 milestone we will probably move it to the next milestone until we figure the best way to progress.

@David-Moreira Maybe we can talk about this for future planning?
