### ISSUE TITLE
Switch within an addon

### ISSUE THREAD

**Issue by drma-dev** [Megabit/Blazorise#2150]
![image](https://user-images.githubusercontent.com/12803050/113424340-61d2ef00-93a6-11eb-9686-be11166ffba5.png)

When I change the size of the switch, it will still work if it has text, otherwise it will break. I tried to adjust via CSS but without success.

```
<Addons>
    <Addon AddonType="AddonType.Body">
        <InputSelect TValue="TValue" Value="@SelectedValue" ValueChanged="@SetValue" ValueExpression="@For" @attributes="@GetAttributes(For, disabled: Disabled)">
            <option></option>                    
        </InputSelect>
    </Addon>
    <Addon AddonType="AddonType.End">
        <AddonLabel>
            <Switch TValue="bool" Size="Size.Medium"></Switch>
        </AddonLabel>
    </Addon>
    <Addon AddonType="AddonType.End">
        <AddonLabel>
            <Switch TValue="bool" Size="Size.Medium">A</Switch>
        </AddonLabel>
    </Addon>
</Addons>
```

**Comment by stsrki** [comment]
I think this is more the Boostrap issue with addons. Even if I adjust CSS I still think it is not a common scenario to have "empty" switch. When you look at it without text, from a UX perspective you have no idea what it does. SO adding text should be the best option.
