### ISSUE TITLE
Image cropper

### ISSUE THREAD

**Issue by njannink** [Megabit/Blazorise#2178]
I'm busy creating an image cropper control based on [CropperJS](https://fengyuanchen.github.io/cropperjs/). If you see this as a valuable addition I could add it later to Blazorise aswell.

**Comment by stsrki** [comment]
It might be a valuable asset for Blazorise. Looking good :)

**Comment by mortezabarzkar** [comment]
you can get help from this


https://github.com/FirstcodGit/FC.BlazorCropImage

**Comment by stsrki** [comment]
@njannink, how far did you go with CropperJS? I might try it soon on my side.

**Comment by njannink** [comment]
I got it to work in our own project. I will have a look if I can extract our own integration. Probably that can form a good base for you to continue on @stsrki
