### ISSUE TITLE
RichTextEdit how to adjust picture size

### ISSUE THREAD

**Issue by LouieGuo** [Megabit/Blazorise#2204]
RichTextEdit how to adjust picture size

**Comment by stsrki** [comment]
@njannink Can you answer this?

**Comment by njannink** [comment]
I'm quite busy at the moment so I have no time to dive into this. But my first guess would be css styles something like

```
.ql-editor img {
   max-width: 200px;
   height: 100%
}
```

And if you want to support img resize inside the editor by the user then you will have to add an additional module like:

https://github.com/kensnyder/quill-image-resize-module

**Comment by stsrki** [comment]
Thank you @njannink 

I hope CSS would be good enough for now as the new module would have to wait for a little.

PS. hope to see you back soon!

**Comment by Smurf-IV** [comment]
Ive found  that the image can be resized by Dragging the corners, It's just that the mouse cursor does not change properly, and it's a bit hit'n'miss

**Comment by njannink** [comment]
Improved resize logic you will get from any of the linked modules above. You will have to load these additional modules during initialization. 

Me myself I have tried to include the emoji module. It worked but the included emoji selection control is horrible so I never put that into production.

**Comment by Devteamsolutions** [comment]
I've managed to get the image resize working if anyone needs help.

**Comment by njannink** [comment]
if you can post the sample code then I will add it to the demo pages

**Comment by Devteamsolutions** [comment]
So I had to just add this to your example:-
 var resize = Quill.register("modules/imageResize",ImageResize.default);
        var resizeImport = Quill.import("modules/imageResize");

        options.modules.imageResize = {
                modules: ['Resize', 'DisplaySize', 'Toolbar']
        }

I also had to add a reference to the plugin js file, but because that needed quil to be loaded, I had to reference the js file for quil too. So Iadded this to my _hosts.cshtml

    <script type="text/javascript" src="https://cdn.quilljs.com/1.3.7/quill.js"></script>
    <script src="https://cdn.rawgit.com/kensnyder/quill-image-resize-module/3411c9a7/image-resize.min.js"></script>

Only problem I have is I can't get the HTML from the editor if I use an image picker toolbox item.  No exception is thrown in c#, no errors on the browser console, it just pauses and does nothing.  The c# code just stops running on the line.  Bit odd that no exception is thrown, wrapped it with a try catch and nothing.  Any ideas why the image picker works but doesn't allow capture of the html.  Maybe some blazor size limit/setting?

await richTextEditRef.GetHtmlAsync();

**Comment by Devteamsolutions** [comment]
ah ok, so I can get it to work.  
Had to add this to start up:-

services.AddSignalR(e => {
e.MaximumReceiveMessageSize = 102400000;
});

**Comment by ArneCools** [comment]
> So I had to just add this to your example:-
> 
> ```
> var resize = Quill.register("modules/imageResize",ImageResize.default);
>        var resizeImport = Quill.import("modules/imageResize");
> 
>        options.modules.imageResize = {
>                modules: ['Resize', 'DisplaySize', 'Toolbar']
>        }
> ```
> 
> I also had to add a reference to the plugin js file, but because that needed quil to be loaded, I had to reference the js file for quil too. So Iadded this to my _hosts.cshtml
> 
> ```
>   <script type="text/javascript" src="https://cdn.quilljs.com/1.3.7/quill.js"></script>
>    <script src="https://cdn.rawgit.com/kensnyder/quill-image-resize-module/3411c9a7/image-resize.min.js"></script>
> ```
> 
> Only problem I have is I can't get the HTML from the editor if I use an image picker toolbox item. No exception is thrown in c#, no errors on the browser console, it just pauses and does nothing. The c# code just stops running on the line. Bit odd that no exception is thrown, wrapped it with a try catch and nothing. Any ideas why the image picker works but doesn't allow capture of the html. Maybe some blazor size limit/setting?
> 
> await richTextEditRef.GetHtmlAsync();

Where do you add this code? In the constructor, OnInitializedAsync?

**Comment by LouieGuo** [comment]
已经收到您的来信，我会尽快回复。

**Comment by ArneCools** [comment]
What I tried:

<script type="text/javascript" src="https://cdn.quilljs.com/1.3.7/quill.js"></script>
<script src="https://cdn.rawgit.com/kensnyder/quill-image-resize-module/3411c9a7/image-resize.min.js"></script>
<script src="js/CustomQuillJS.js"></script>

In Razor file:
ConfigureQuillJsMethod="myComponent.configureQuillJs"

CustomQuillJS.js:
```
window.myComponent = {
    configureQuillJs: () => {
        var resize = Quill.register("modules/imageResize",ImageResize.default);
        var resizeImport = Quill.import("modules/imageResize");

        options.modules.imageResize = {
            modules: ['Resize', 'DisplaySize', 'Toolbar']
        } 
    }
}
```
Where do I get "options"?

After doing this Quill breaks for me:
![image](https://user-images.githubusercontent.com/1440244/188609934-fa8d6421-5bae-4f20-b2ea-7fb9822566dd.png)



Can anyone helpe me out?

**Comment by njannink** [comment]
do you have an example project that I can debug

**Comment by Devteamsolutions** [comment]
replace  
`configureQuillJs: () => {`

with 
`configureQuillJs: (options) => {`

**Comment by ArneCools** [comment]
Thanks!

I also fixed the css problem by importing the css again, _Hosts.cshtml looks like this now:
```
<script type="text/javascript" src="https://cdn.quilljs.com/1.3.7/quill.js"></script>
<script src="https://cdn.rawgit.com/kensnyder/quill-image-resize-module/3411c9a7/image-resize.min.js"></script>
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
<script src="js/CustomQuillJS.js"></script>
```

**Comment by LouieGuo** [comment]
已经收到您的来信，我会尽快回复。
