### ISSUE TITLE
Update Chart.JS to v3

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#2229]
https://www.chartjs.org/docs/latest/getting-started/v3-migration.html

**Comment by eluchsinger** [comment]
@stsrki thanks for the library!
Do you have any progress here? I am looking into charts for Blazor and this would be perfect.

**Comment by stsrki** [comment]
No, not yet. We're already full with the features for this milestone so it will probably be done in the next milestone. Just in case I will add it to the Last Minute in case we got enough time left.
