### ISSUE TITLE
Copy to clipboard attribute

### ISSUE THREAD

**Issue by StephenOTT** [Megabit/Blazorise#2283]
**Is your feature request related to a problem? Please describe.**
Ability to add a config on `<Text>` (or wherever would be most appropriate) so on hover of the text the user is offered the ability to copy the text.

Common use case is when dealing with IDs.

Thanks

**Comment by stsrki** [comment]
It sounds to me like it would be a better choice for a separate component that would wrap the text and then have the copy ability on hover. That way it could copy almost any content.

eg.

```cshtml
<CopyClipboard>
  <Text>abc123</Text>
</CopyClipboard>
```

**Comment by StephenOTT** [comment]
+1

**Comment by Stirda** [comment]
Any plan to implement this?

**Comment by stsrki** [comment]
We can try to make it part of v1.0.
