### ISSUE TITLE
Lazy load of tab content

### ISSUE THREAD

**Issue by StephenOTT** [Megabit/Blazorise#2284]
**Describe the solution you'd like**
When loading tabs, would be great to have a lazy load option so tab content is not always executed if the tab is not active.  Common use case is when queries/HTTP/DB queries are executed within a tab.

similar arguments to #1110

**Comment by stsrki** [comment]
So simple if statement should be enough?

**Comment by StephenOTT** [comment]
I was just experimenting with this: The scenario i am experiencing seems to need some sort of firstLoad detection:

Where there is a difference between reload the tab's content on each new tab view, and the second scenario of: only load the tabs content on first view of the tab.

**Comment by StephenOTT** [comment]
Example use case:

3 Tabs with data grids in each tab. data grids use the ReadData Attribute

Scenario 1: On each tab load the data grid is refreshed for the specific tab

Scenario 2: The data grid for each specific tab is only loaded once, on the first load of the specific tab.

**Comment by stsrki** [comment]
The first example is problematic because you don't have any component reference until the underline element is added to the DOM. This is how Blazor works in general.

**Comment by StephenOTT** [comment]
For scenario 1 I meant more about the data load aspect of the grid: where the data read is triggered each time the tab is selected/made visible.

**Comment by stsrki** [comment]
As long as people dont access not-yet-loaded tabs, I think everything should be fine.

**Comment by David-Moreira** [comment]
I'm not sure I follow 100% but this just has to do with rendering the tabs or not hidden in the html.

**Scenario 1 :** You can have all 3 tabs with 3 datagrids load the data at same time. Meaning as soon as the page loads.
Even if only the first one is active. This is done by just rendering the tabs hidden in the html.

**Scenario 2 :** You can render each tab a time, meaning that only when you set each tab to active, it will render it's own Datagrid and load data only when it's set to active. The tab that was previously active.. any components inside it, will be disposed.

Pretty sure we're on scenario 2, are we not @stsrki ? Is Stephen suggesting an option to have Scenario 1? Is that it?

**Comment by stsrki** [comment]
@David-Moreira Yes I think that is the case here. 

Scenario 1 is how it is done now. Everything is rendered immediately as page is opened since tabs are only hidden. But they are still in the HTML(DOM).

Scenario 2 should be the new feature where only after a tab is activated the content should be loaded and rendered.

**Comment by David-Moreira** [comment]
If that's it, I guess it could be a good feature, ah?

I see it being useful for uses cases with multiple tabs and like a ton of information / components under each tab. It will save on information / ton of html being sent forth and back between client / server(Blazor.Server) and processing unneeded components. Or just to make it easier to have a 'clean slate' when switching tabs.
Seems viable in my opinion... :P

**Comment by StephenOTT** [comment]
So to recap on current ideas: Would be a config that would only load the tab's content when the tab is active/content is visible, and the tab would/may be disposed when not active/not visible?

**Comment by stsrki** [comment]
I think it should be possible to both lazy load and dispose of.

**Comment by David-Moreira** [comment]
Yep. I personally have something similar done here. Simple if statement. 
Either load the components into the HTML hidden or just don't render tab body, until tab is actually set to active.

https://github.com/David-Moreira/BlazorXTabs/blob/master/src/XTabs/XTabs.razor

**Comment by stsrki** [comment]
That was my way of thinking also. Have a simple **if** statement to control the load.

**Comment by CupcakeThief** [comment]
Yep I've gone that way myself, was just thinking "it would be handy if this was an option on the blazorise tab control" :) Would have saved me a bit of finger leather!
