### ISSUE TITLE
missing dataset labels on PieChart

### ISSUE THREAD

**Issue by naefp** [Megabit/Blazorise#2287]
When using a pie chart with multiple datasets, there can be set a label for each dataset which never will be displayed. Since this seems to be default behavior in Chart.Js it is not a bug in Blazorise!

But definitely it would make sense to add an option for displaying the dataset labels additionally in the tooltips. A possible solution which would perfectly fit in my use case, is to update the tooltip label callback: `return data.datasets[item.datasetIndex].label+ ": "+ data.labels[item.index]+ ": "+ data.datasets[item.datasetIndex].data[item.index];` (got this from here: https://stackoverflow.com/a/45184272)

Discussion on Chart.js: https://github.com/chartjs/Chart.js/issues/1417

**Comment by CPlusPlus17** [comment]
*bump*

**Comment by stsrki** [comment]
Sorry guys, lately I've been very busy with some other business-related work to make it done all as soon as possible so I tend to overlook some issues.

---

The fix seems doesn't seem that complicated. Can't promise when it will be done. I will schedule it for 0.9.4, and if anyone in the meantime could create a PR it would be released soon as part of the next preview.

**Comment by stsrki** [comment]
Working on this now. Should I make modifications only for Pie chart?

**Comment by naefp** [comment]
Not sure, I did not use every chart type yet. So far, I only missed the dataset label on pie chart...

**Comment by stsrki** [comment]
Not sure if I'm missing something? But for me, the labels are working just fine for Pie chart

![image](https://user-images.githubusercontent.com/900302/123932980-3efaab80-d992-11eb-8bd5-133b1995ccf3.png)

**Comment by naefp** [comment]
@stsrki that's correct, the labels of each entry are displayed correctly, but not the label of the dataset.

Each circle in the pie chart represents a dataset and the tooltip should be able to show the dataset label as well. Example here: https://stackoverflow.com/a/45184272

To be able to do that we need to change the tooltip callback for the label, and right now this is not possible with the Blazorise implementation. I can set the Label property in PieChartDataset, but this is never displayed and so you are not able to understand what each circle of the pie chart represents.

In my opinion the tooltip could always show that like: `<dataset.label>: <entry.label>: value`
But there may be use cases where the dataset label is not expected to be shown, I don't know. Maybe you could enable/disable that with a simple bool or you could provide a way to customize the tooltip callback directly? (which may be possible already, but I just didn't find it :D )

**Comment by stsrki** [comment]
I was able to do it the same as for all other charts

![image](https://user-images.githubusercontent.com/900302/124286455-431ff800-db4f-11eb-9a29-fbe02ab92137.png)

```js
if (type === "pie") {
    options = {
        ...options,
        ...{
            tooltips: {
                callbacks: {
                    title: function (item, data) {
                        const label = data.labels[item[0].index];
                        return label;
                    },
                    label: function (item, data) {
                        const dataLabel = data.datasets[item.datasetIndex].label;
                        const dataValue = data.datasets[item.datasetIndex].data[item.index];
                        return dataLabel + ': ' + dataValue;
                    }
                }
            }
        }
    }
}
```

Is this OK?

**Comment by naefp** [comment]
This is much better already. But in my opinion the title and label should be switched...
```
if (type === "pie") {
    options = {
        ...options,
        ...{
            tooltips: {
                callbacks: {
                    title: function (item, data) {
                        const label = data.datasets[item.datasetIndex].label;
                        return label;
                    },
                    label: function (item, data) {
                        const dataLabel = data.labels[item[0].index];
                        const dataValue = data.datasets[item.datasetIndex].data[item.index];
                        return dataLabel + ': ' + dataValue;
                    }
                }
            }
        }
    }
}
```

As I can see, i.e. in the barchart it is done this way.

**Comment by stsrki** [comment]
Unfortunately, it doesn't work in that case. With my changes, as far as I can see it looks and behave the same as all other charts.

**Pie**

![image](https://user-images.githubusercontent.com/900302/124353877-7921b280-dc09-11eb-973d-60ae21301ebb.png)

**Line**

![image](https://user-images.githubusercontent.com/900302/124353922-acfcd800-dc09-11eb-9625-c2c10fdb64a6.png)

**Bar**

![image](https://user-images.githubusercontent.com/900302/124353884-7f179380-dc09-11eb-962f-20394ccdaadf.png)

**Comment by naefp** [comment]
Should be fine. Anyway, I will be happy to have the dataset label available! Thank you for implementing that! :sunglasses:

**Comment by naefp** [comment]
Hi @stsrki 

In my opinion there is something wrong in the current version (0.9.4-preview6).

In the example of a BarChart you can see that each dataset is a date and contains some data using the colored labels. In the tooltip the title is used to show the dataset label, not the data label. I think this make sense and is correct.
![image](https://user-images.githubusercontent.com/42241289/126057347-b186f883-fea4-4a91-aa69-b3303aa173d6.png)

In this new example of a PieChart, we have the newly added dateset labels as well - thank you for that! But here it is the other way around: while a dataset here is a month, the data label is displayed in the tooltip title instead of the dataset label.
![image](https://user-images.githubusercontent.com/42241289/126057369-25caffef-9837-4009-a615-78f9d33fd0fe.png)

Can you check that again?

**Comment by stsrki** [comment]
But I don't see a dataset label on Pie chart. Can you try and submit a new PR with the fix? I'm in the middle of finishing Blazorise for the final release and there is little time for me. If you manage to fix I will make it part of the release. Thanks.

**Comment by naefp** [comment]
I have tested the changes from the PR  locally in our project
