### ISSUE TITLE
<Text> in @if statement doesn´t work except when wrapped in (at least) a <Field>

### ISSUE THREAD

**Issue by sturlath** [Megabit/Blazorise#2295]
Hi, this might be fixed already but I'm still on my old 0.9.3-preview6 version (I´ll hopefully be updating later this week).

I hope the image tells the whole story. I got it working by adding a `<Field>` around the `<Text>` but I haven't tried anything else.
![image](https://user-images.githubusercontent.com/2386572/117044320-d37fbf00-acfd-11eb-8699-230362e8e323.png)

**Comment by stsrki** [comment]
Seems like an error in VS IntelliSense. It might help to close VS and reopening it. If that doesn't help try defining the Blazorise namespace. eg,

```cshtml
<Blazorise.Text>
  Some text
</Blazorise.Text>
```

**Comment by StephenOTT** [comment]
Ya VS (including mac) has issues with <text> vs <Text> (Blazorise)

**Comment by David-Moreira** [comment]
Yea that text shouldn't actually be from html, it is a reserved razor keyword, for when you want to input html inside code, so something like this should work : 
```
@if (true)
{
    <text>
        <Text Color="TextColor.Primary">Should work just fine</Text>
    </text>
}
```
I did not test it. But pretty sure it does. Eitherway, does not seem that bothering... :)

**Comment by stsrki** [comment]
I have reported it to .Net Core team, but it seams they will not bother fixing it 😠

**Comment by stsrki** [comment]
Closing since this is a razor and VS problem.
