### ISSUE TITLE
Lost connection after choose not small picture in RichTextEdit

### ISSUE THREAD

**Issue by DDDenisSobek** [Megabit/Blazorise#2297]
**Describe the bug**
After selection of picture bigger than 1 MB connection crashed on server side projects.

**To Reproduce**
1. Clone repo https://github.com/DDDenisSobek/BlazoriseTestProject
2. Start Project
3. Go to RichTextEditTest Page
4. Click on image button
5. Select picture >1MB

**Expected behavior**
I can select picture until 3 MB without crash with projects like this https://github.com/DDDenisSobek/BlazoriseTestProject .

**Screenshots**
After select ~2,2MB:
![grafik](https://user-images.githubusercontent.com/65016836/117147152-4304b580-adb5-11eb-823c-3279635cfad4.png)
Result after reconnect:
![grafik](https://user-images.githubusercontent.com/65016836/117147211-5283fe80-adb5-11eb-8235-cb9d791b55d0.png)

**Comment by stsrki** [comment]
I have copied your example into Blazorise and trying it with an image ~10MB and it works for me without any error.

**Comment by DDDenisSobek** [comment]
Ok, interesting. I try it with an other pc, maybe is my hardware too bad.

**Comment by DDDenisSobek** [comment]
@stsrki Can you clone the repo and try with it? Because in Blazorise it works, but in my example project does not work. But it is a standard start server side Blazor project.

**Comment by DDDenisSobek** [comment]
@stsrki I found the problem. The connection problems have to do with SingleR connection. By default maximum message size is 32 KB. Connection is refused, because the string is bigger than 32KB with image, that JavaScript returns.
Actual my workaround is setting [MaximumReceiveMessageSize](https://docs.microsoft.com/de-de/dotnet/api/microsoft.aspnetcore.signalr.huboptions.maximumreceivemessagesize?view=aspnetcore-5.0) up.
The reason why it works on the demo project on Blazorise Git is: The project is a client side project, that does not need SingleR connection for execute code.
A solution by Blazorise would be, that GetHtmlAsync read the html string in pieces smaller than or equals 32KB by JS and returning hole string in C#.

**Comment by stsrki** [comment]
Aaahh makes sense. And we already have it increased in the demo server app so that's why it was working.

```cs
services.AddServerSideBlazor().AddHubOptions( ( o ) =>
{
    o.MaximumReceiveMessageSize = 1024 * 1024 * 100;
} );
```

**Comment by DDDenisSobek** [comment]
@stsrki Changing the behavior (like described) or extending documentation of RichTextEdit would be nice or?

**Comment by stsrki** [comment]
I would just extend documentation with the note about MaximumReceiveMessageSize for server-side projects.

**Comment by stsrki** [comment]
Note added to the docs
