### ISSUE TITLE
Code component

### ISSUE THREAD

**Issue by StephenOTT** [Megabit/Blazorise#2298]
Can/should `Text` support `code`?  Or is there a better way?

**Comment by stsrki** [comment]
Do you mean this?

![image](https://user-images.githubusercontent.com/900302/117155020-b65df580-adbc-11eb-8e6d-f92fb3c2dd72.png)

**Result**

![image](https://user-images.githubusercontent.com/900302/117155055-be1d9a00-adbc-11eb-94a4-dd79ddfde037.png)

![image](https://user-images.githubusercontent.com/900302/117155088-c4ac1180-adbc-11eb-92a7-2fbe11d2da73.png)

Seems to be working just fine to me.

**Comment by StephenOTT** [comment]
ya `<code` works: was asking specifically about the https://blazorise.com/docs/components/typography/#text `<Text>` tag where it supports the `italic` attribute (rather than using `<i>`).  Is there some history on why italic is an attribute?

**Comment by stsrki** [comment]
Just the wish to use everything Blazorise instead of native HTML tags. That way I have full control over how different CSS frameworks might apply the styles. For example, Bulma has `.is-italic` class name.

And I plan to bring more of these _native_ Blazorise components in Blazorise 0.9.4.

**Comment by StephenOTT** [comment]
Okay so in the future would there essentially be a `<Code>` blazorise tag?

**Comment by stsrki** [comment]
Yeah, it could be. In fact, I might add it just now :)

**Comment by stsrki** [comment]
The plan is to also have some advanced `CodeSnippet` components. But that will probably be a separate extension for Blazorise.

**Comment by StephenOTT** [comment]
good carry over for: #2283
