### ISSUE TITLE
FileEdit MaxMessageSize error handling

### ISSUE THREAD

**Issue by StephenOTT** [Megabit/Blazorise#2310]
When uploading there does not appear to be a handler for max message size? (as in no way to catch the error and route it to somewhere else (such as toast/snackbar)

**Comment by stsrki** [comment]
I'm not sure what you mean handler for max message size and catching the error. Can you please explain?

**Comment by stsrki** [comment]
Ahh, I understand. It might be good to have something like `OnErrors` event callback that might give you all the information.

**Comment by stsrki** [comment]
But it will need to be implemented internally. Since it is introducing a new API I will implement it for v0.9.4

**Comment by David-Moreira** [comment]
Hello,
I am not sure we should do anything here?

When using the `WriteToStreamAsync`, if some error happens, we already invoke `UpdateFileEndedAsync` with `success=false`, and let the exception flow, I don't think Blazorise should be handling exceptions internally, unless it's something on the Blazorise Domain.
Also `MaxMessageSize` is configurable and can be easily validated?
![image](https://user-images.githubusercontent.com/22283161/142733704-563c4692-ea95-436f-81c9-3acbac4dded6.png)

As for the `OpenReadStream` we do throw an `IOException` ourselves if the maxSize argument is exceed, however, it's clearly configurable, and again you can validate on your side before invoking the API.
![image](https://user-images.githubusercontent.com/22283161/142734084-b7e1c10a-58f3-4851-b5b1-25c4d839bf7b.png)


I'd argue that what we could do is have a validation step that checks whether the file being uploaded is valid or not.
And there would be a `FileEntry.IsValid` bool / `FileEntry.InvalidReason` enum, according to configurations, as to avoid the use of exceptions, for something Blazorise already knows before hand it's not gonna go well (Currently, Blazorise only knows the MaxSize can go wrong?)... also it's just a shortcut so the user does not have to do the validation himself, just check the `File.IsValid` // `FileEntry.InvalidReason` and act accordingly?

**Comment by David-Moreira** [comment]
@stsrki 
*bump* :D

**Comment by stsrki** [comment]
I think the best option would be to expand `Ended` eventArgs. We can add either `InvalidReason` enum, or an `ErrorMessages` as an array. I tend to go more forward to the `InvalidReason` enum because then we don't need to bother with localizing the messages.

**Comment by David-Moreira** [comment]
These are technical messages, users shouldn't expect them to be localized. :D
I like the enum also.
