### ISSUE TITLE
Create column resize on Table

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#2313]
> I was thinking... tables don't have the resize feature like in datagrid, and in retrospective since datagrid uses table behind the scenes, maybe the feature could have been implemented in the table and be available in both, eitherway I was thinking if this is gonna mesh well with it or not, in theory it should still work exactly the same.

I just now understood this message 🤦‍♂️. It might just be a great idea to have it directly on the Table. I don't think it would be hard to move it. Good catch!

_Originally posted by @stsrki in https://github.com/stsrki/Blazorise/issues/2293#issuecomment-834517658_

**Comment by a-postx** [comment]
It would be good for developer to have a way to also save the table columns positioning for the user. We can save it (e.g. on local storage) and load once the user get back to specific page.

**Comment by stsrki** [comment]
Sounds like a good feature.

**Comment by stsrki** [comment]
@David-Moreira We should do this as soon as possible. I think with this feature there will be no reason to have `blazorise.datagrid.js` or `blazorise.datagrid.css` files.

**Comment by David-Moreira** [comment]
Ya. Although Js will be needed for virtualize at the moment. But virtualize still needs work so for the time being we can move the feature to the table and remove the files, yes.

**Comment by David-Moreira** [comment]
@stsrki can we create a new feature issue to handle this "nice to have" in the future:
>It would be good for developer to have a way to also save the table columns positioning for the user. We can save it (e.g. on local storage) and load once the user get back to specific page.

And could you leave it allocated to me, for a future milestone.
Also, do we have any internal apis for handling local storage?

**Comment by stsrki** [comment]
@David-Moreira Assigned to you in the new ticket.

---

Regarding the local storage API. I didn't think of it before. So far I always used _Blazored/LocalStorage_ from Chris Sainty. But if it makes sense we can try to create our own if it's worth it. If you think, I can open a new ticket.

**Comment by David-Moreira** [comment]
@stsrki yea I have also used his. However, if we are going to be needing to access localStorage and create internal APIs for that, might as well make a Blazorise LocalStorage Component for that. Which can also be a new feature issue, which the new ticket you've just assigned to me will depend upon.
