### ISSUE TITLE
Unable to use complex object with Chart

### ISSUE THREAD

**Issue by Luk164** [Megabit/Blazorise#2317]
**Describe the bug**
I am trying to use a complex object with the Chart component, but I just cant get it to work, no matter what I try. The label is displayed and array is 100% not empty, I even debugged the JS and all seems fine (screenshots attached).

**To Reproduce**
1. This is my "complex" class

```
public class WatcherEvent
    {
        public string Sector { get; set; }

        public int Count { get; set; }

        public DateTime Date { get; } = DateTime.Now;
    }
```

2. I created a LineChart component, passed a list of these to it and set WatcherEvent as a type.
3. I set OptionsJsonString based on this guide https://www.chartjs.org/docs/master/general/data-structures.html

`private readonly string _settingsForChart = "{\"parsing\":{\"xAxisKey\":\"count\",\"yAxisKey\":\"sector\"}}";`

4. Nothing shows

**Expected behavior**
I expect the values to start showing up.

**Screenshots**
![image](https://user-images.githubusercontent.com/30559213/117519585-748fa380-afa4-11eb-9a70-1769abd2e141.png)
![image](https://user-images.githubusercontent.com/30559213/117519758-38107780-afa5-11eb-9471-0ffe82eaed5e.png)

**Additional context**
I know the OptionsJsonString will be removed when these options are added to the standard options classes but I need the functionality today.

**Comment by stsrki** [comment]
Instead of `OptionsJsonString` just use `OptionsObject`. It is basically a C# _replacement_ for JSON. eg.

```
object chartOptions = new
{
    Scales = new
    {
        XAxes = new[] {
            new {
                Ticks = new
                {
                    StepSize = 0.5
                }
            }
        }
    }
};
```

`<LineChart @ref="lineChart" TItem="double" OptionsObject="@chartOptions" />`

**Comment by Luk164** [comment]
@stsrki Had no idea that was allowed. I am going to give it a try.

**Comment by Luk164** [comment]
@stsrki Well TIL
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/anonymous-types

**Comment by stsrki** [comment]
@Luk164 sorry, I completely forgot about this issue. Were you able to fix it?

**Comment by Luk164** [comment]
No, I only worked around it by converting my values into two sets. @stsrki

**Comment by stsrki** [comment]
Well, as long as it works I guess it is OK :)

Closing now

**Comment by Luk164** [comment]
Should we close it though? The workaround is very ugly and requires extra work. I would highly prefer if we could just specify the two accessors...

**Comment by Luk164** [comment]
Maybe we should put this in a backlog and implement it once the chart JS library is updated.

**Comment by stsrki** [comment]
Fair enough. OK going on the backlog to be done along with support for v3.0.

**Comment by Luk164** [comment]
Great! I am looking forward to using this once I get to do blazor again.
