### ISSUE TITLE
Fixed row headers on Table and DataGrid

### ISSUE THREAD

**Issue by wartim** [Megabit/Blazorise#2339]
I hope Table and DataGrid can add the function of fixing row headers and columns

**Comment by stsrki** [comment]
Can you explain what is fixing the row headers? Not be able to resize?

**Comment by wartim** [comment]
That is, when the height of the table / DataGrid is limited, a scroll bar will appear in tbody (when the data cannot be displayed completely), and then the contents (table data) can be scrolled, but not the header.

Fixed columns are the same: if I limit the width of the table and the width of each column, then when there are too many columns, the horizontal scroll bar will be displayed. When I scroll the horizontal scroll bar to the right, the fixed columns will not scroll together

![1](https://user-images.githubusercontent.com/6902982/117630626-fa326f80-b1ad-11eb-9992-5d2f7a8a6fe5.png)
![2](https://user-images.githubusercontent.com/6902982/117630635-fb639c80-b1ad-11eb-8d20-17e40a2feb57.png)
![3](https://user-images.githubusercontent.com/6902982/117630640-fbfc3300-b1ad-11eb-8a51-83ab6a5a95e0.png)

**Comment by wartim** [comment]
I can use some CSS styles to control, but it's better to have built-in functions

**Comment by wartim** [comment]
OK, these functions are often used in real projects, and table / DataGrid is a very common and important data presentation component, hoping to integrate more and more powerful practical functions

PS: I ran the chart streaming example in the document. The delay of real-time rendering is very high. I hope it can be improved. Dynamic generation of chart data and display are also common functions of various report pages

**Comment by stsrki** [comment]
@David-Moreira you have worked on the fixed header so maybe you can make the same for the fixed columns? v1.0?

**Comment by David-Moreira** [comment]
God! Do I love these features!!

**Comment by stsrki** [comment]
I don't know, do you? 😂

**Comment by David-Moreira** [comment]
😂...

**Comment by PatThyLad** [comment]
Would love to see this feature in the future. 
Looking foreward to it!

**Comment by stsrki** [comment]
> Is there any workaround in the meantime?

You will most likely need to adjust some CSS. Look at SO for reference https://stackoverflow.com/questions/1312236/how-do-i-create-an-html-table-with-a-fixed-frozen-left-column-and-a-scrollable-b
