### ISSUE TITLE
Role based components

### ISSUE THREAD

**Issue by manasimahajann** [Megabit/Blazorise#2348]
I am not sure if this already exists.. 

In blazor/blazor webassembly -- we are able to have role based view for components using 

`<AuthorizedView Role="test.Read"></AuthorizedView>`

If we want to restrict user from using New/edit/delete buttons in DataGrid - it would be nice to have role based auth on these.

Thank you.

**Comment by stsrki** [comment]
I'm not sure if I would like to implement authorization directly in DataGrid. Not everyone needs it. And I think you can already achieve this by using the templates like NewCommandTemplate, EditCommandTemplate, SaveCommandTemplate, etc.
