### ISSUE TITLE
Use of IBrowserFile instead of file entry?

### ISSUE THREAD

**Issue by StephenOTT** [Megabit/Blazorise#2370]
Noticed that Blazorise implements a custom file interface for file uploads, as per: IFileEntry

as part of 5x here is https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.inputfilechangeeventargs.file?view=aspnetcore-5.0#Microsoft_AspNetCore_Components_Forms_InputFileChangeEventArgs_File

and https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.ibrowserfile?view=aspnetcore-5.0

Thoughts on using this interfaces (+ extension methods where needed for extra helpers?)

latest examples from docs: https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0&pivots=webassembly#upload-files-to-a-server

**Comment by stsrki** [comment]
Blazorise upload was created long ago before Blazor had support for it. It was based on the work from Steve S., https://blog.stevensanderson.com/2019/09/13/blazor-inputfile/

Not sure if it's worth it changing now just to use the same interfaces. If I would to change it, I might be better of use InputFile directly. We'll see.

**Comment by StephenOTT** [comment]
Inputfile would be nice to have (along with the browserfile) so interop with other libraries can be created without having to worry about if it is Blazorise, etc. (and not having to create additional classes for dto between the various possible libs.).

**Comment by stsrki** [comment]
We'll see. It is a major change so I will put it on backlog since we're already full for the next release.

**Comment by stsrki** [comment]
Due to the custom fields that we have on IFileEntry, it would be hard to switch to IBrowserFile. Closing now.
