### ISSUE TITLE
Live streaming Chart 

### ISSUE THREAD

**Issue by OmidRafiee** [Megabit/Blazorise#2373]
Hello
I wanted to know if such a chart can be made with this package?

![image](https://user-images.githubusercontent.com/25098596/118498318-25cbd180-b73b-11eb-8afd-0e176e05f643.png)

**Comment by stsrki** [comment]
This? https://bootstrapdemo.blazorise.com/tests/livecharts

**Comment by OmidRafiee** [comment]
Thanks but I have seen these examples.
I want to be able to change custom
For example, I can create inside each cell at a distance of 1 cm and break it into two

Something like [this](https://www.highcharts.com/demo/combo-meteogram#https://www.yr.no/place/United_Kingdom/England/London/forecast_hour_by_hour.xml)

**Comment by OmidRafiee** [comment]
How can I change  RandomScalingFactor Method to dynamic list  dataList  on Refreshed ?













    @code{

        LineChart<LiveDataPoint> horizontalLineChart;

        IEnumerable<double> datas = new List<double> { 2.5, 3, 5, 4, 1.5, 3.5 };


        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await Task.WhenAll(
                    HandleRedraw(horizontalLineChart, GetLineChartDataset1));
            }

        }

        async Task HandleRedraw<TDataSet, TItem, TOptions, TModel>(BaseChart<TDataSet, TItem, TOptions, TModel> chart, params Func<TDataSet>[] getDataSets)
            where TDataSet : ChartDataset<TItem>
            where TOptions : ChartOptions
            where TModel : ChartModel
        {
            await chart.Clear();

            await chart.AddLabelsDatasetsAndUpdate(Labels, getDataSets.Select(x => x.Invoke()).ToArray());


        }

        public class LiveDataPoint
        {
            public object X { get; set; }

            public object Y { get; set; }
        }

        LineChartDataset<LiveDataPoint> GetLineChartDataset1()
        {
            ClientExcelService.GetDataAsync();
            return new LineChartDataset<LiveDataPoint>
            {
                Data = new List<LiveDataPoint>(),
                Label = "Dataset 1 (linear interpolation)",
                BackgroundColor = backgroundColors[0],
                BorderColor = borderColors[0],
                Fill = false,
                LineTension = 0,
                BorderDash = new List<int> { 8, 4 },
            };
        }
      
        Task OnHorizontalLineRefreshed(ChartStreamingData<LiveDataPoint> data)
        {

            data.Value = new LiveDataPoint
            {
                X = DateTime.Now,
                Y = RandomScalingFactor(),
            };

            return Task.CompletedTask;
        }


        double RandomScalingFactor()
        {

            return (random.NextDouble() > 0.5 ? 1.0 : -1.0) * Math.Round(random.NextDouble() * 100);
        }


        object horizontalLineChartOptions = new
        {
            Title = new
            {
                Display = true,
                Text = "Line chart (horizontal scroll) sample"
            },
            Scales = new
            {
                YAxes = new object[]
                {
                    new {
                        ScaleLabel = new {
                            Display = true, LabelString = "value" }
                    }
                }
            },
            Tooltips = new
            {
                Mode = "nearest",
                Intersect = false
            },
            Hover = new
            {
                Mode = "nearest",
                Intersect = false
            }
        };


    }
