### ISSUE TITLE
EditText/Tab Underline - Theme

### ISSUE THREAD

**Issue by mathi82** [Megabit/Blazorise#2374]
Shouldn't the underline of EditText/Tab underline when active be the same colour as the primary colour?

![image](https://user-images.githubusercontent.com/68622190/118545857-2ce7e500-b725-11eb-879e-52a25a3be979.png)

**Comment by stsrki** [comment]
It should, yes. Just a small bug that I should fix for the next patch. Thanks for letting me know!
