### ISSUE TITLE
AutoComplete Validation

### ISSUE THREAD

**Issue by Zumpel96** [Megabit/Blazorise#2389]
**Is your feature request related to a problem? Please describe.**
I am building a small Web-App, which is heavily reliant on forms. As for now, I really love the implementation of the validation. But since some of my forms use the AutoComplete component, I additionally want to use validation on them as well. As for now, I did not find a way to make the validation work for this component. In my case, I would like to show the error text if no content is selected.

**Describe the solution you'd like**
First of all, I want my Model to look something like this:
```csharp
public class Message
{
    [Required]
    public Category Category { get; set; }

    [StringLength(20, ErrorMessage = "Only a maximum of 20 characters are allowed.")]
    public string Content { get; set; }
}
```

Then I want to create a form which looks something like this:
```html
<Validations Model="@message">
    <Field>
        <FieldLabel>Message Content</FieldLabel>
        <Validation>
            <TextEdit Placeholder="Enter message content (optional)" @bind-Text="@message.Message.Content">
                <Feedback>
                    <ValidationError />
                 </Feedback>
            </TextEdit>
        </Validation>
    </Field>
    <Field>
        <FieldLabel>Category</FieldLabel>
        <Autocomplete TItem="SelectorModel"
              TValue="int"
              Data="@mappedCategories"
              Filter="AutocompleteFilter.Contains"
              TextField="@(item => item.Text)"
              ValueField="@(item => item.Value)"
              SelectedValue="@selectedCategory"
              Placeholder="Select a Category"
              SelectedValueChanged="@CategoryChanged">
            <Feedback>
                <ValidationError />
            </Feedback>
        </Autocomplete> 
    </Field>
</Validations>
```

**Comment by stsrki** [comment]
Autocomplete is a little different from other components since it uses validation internally. You don't need to define Feedback, it will be done for you. Also, validation behaves like it is a regular select component, it will not work on the searched text.

To use autocomplete validation you need to define the `Validator` parameter. eg. https://blazorise.com/docs/components/validation/#example

**Comment by nightroman** [comment]
@stsrki (I was about to ask the similar Q)

What is validated? "Selected value` or "typed value" or both?
E.g. I have a scenario when the completion list is only suggestions, users may type what they want without selecting from the list.

**Comment by stsrki** [comment]
Validated value is the selected value.

**Comment by nightroman** [comment]
So my scenario is not covered with validation, right? It looks legit though...

By the way, getting the typed value is not straightforward, too. Or I miss something. Currently I get and keep it it via `SearchChanged`.

**Comment by stsrki** [comment]
Yes, SearchChanged is the only way to get the typed value.
