### ISSUE TITLE
Switch BootstrapClassProvider wrong class name

### ISSUE THREAD

**Issue by d-oit** [Megabit/Blazorise#2390]
https://github.com/Megabit/Blazorise/blob/master/Source/Blazorise.Bootstrap/BootstrapClassProvider.cs

Bootstrap switch class is `custom-control-input   `https://getbootstrap.com/docs/4.2/components/forms/#switches 
public override string Switch() => UseCustomInputStyles ? "custom-control-input" : "form-check-input";

**`public override string Switch() => UseCustomInputStyles ? "custom-control-input" : "custom-control-input";`**

I could contribute this PR is you like.

**Comment by stsrki** [comment]
"form-check-input" is actually there for a reason, in case UseCustomInputStyles is disabled. This is by design.

**Comment by d-oit** [comment]
Hmm if I use an bootstrap theme then I have to set the UseCustomInputStyles to false. 
It works for all other components.
Bootstrap use also the custom-control-input class for the switch control. With the current version i have a checkbox instead of a switch.

**Comment by stsrki** [comment]
I was planing to remove UseCustomInputStyles and always use custom control styles. It is basically mostly used by the bootstrap provider anyways, eg https://getbootstrap.com/docs/4.6/components/forms/#checkboxes.

**Comment by d-oit** [comment]
I like the idea with the custom style bool. This was the main advantage for me. I could use outbox bootstrap themes without customize all classes. 

What is the disadvantage? Why removing?

**Comment by stsrki** [comment]
Mainly because I think most people want to have custom input that looks nicer. And I thought nobody used the flag :) This is the first time anyone mentioned it.

**Comment by d-oit** [comment]
Not documented ;-)

Themes like this - open settings > look at the select - use css class **form-control** and a separate responive.css (not  b4 reboot custom)
http://eliteadmin.themedesigner.in/demos/bt4/cryptocurrency/employee-profile.html 

If someone use this theme in html, angular or something else it should look the same. Usually you have to customize this which costs you time. With UseInputCustom = false it works out of the box. 

Switch is special - works only as custom control. Have to think about it, you could close issue. 
Thanks for your  response.
