### ISSUE TITLE
DataGrid Button row disappears on small screens.

### ISSUE THREAD

**Issue by tesar-tech** [Megabit/Blazorise#2393]
_See updated issue in comments._
**Describe the bug**
The button row is not show when checking checkbox in demo app.

**To Reproduce**
- https://bootstrapdemo.blazorise.com/tests/datagrid . 
- Checkbox `Show Button Row`  should show button row (this is the [line](https://github.com/Megabit/Blazorise/blob/2e78103bb9e051a395e2cc1821d72ebacd04f689/Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor#L346)) 
- Button row is not shown. 

**Additional context**
I am having similar issue, when **button row is hiding "behind" the paginator on smaller screens**.

**Comment by stsrki** [comment]
It works, but it also needs to have ButtonRow mode enabled.

![image](https://user-images.githubusercontent.com/900302/119039682-d690d580-b9b4-11eb-9166-e0269dfd369d.png)

**Comment by tesar-tech** [comment]
Ok, my fault... But it does **disappear on small screens**. Which was the reason I created this issue in a first place (renaming the issue)

https://user-images.githubusercontent.com/33880579/119084804-b8ea5d00-ba02-11eb-88f2-e54895d09860.mp4

**Comment by David-Moreira** [comment]
@stsrki I can take a look at this.

**Comment by stsrki** [comment]
@David-Moreira  Should I make it part of 0.9.4 milestone?

**Comment by David-Moreira** [comment]
Ye and assign it to me pls.
