### ISSUE TITLE
Poll: Should new date picker be part of DateEdit?

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#2394]
I'm working on an integration of [flatpickr](https://flatpickr.js.org/) as a default date editor for Blazorise. It is working excellent so far and it has all the features I wanted it to have, and even more. 

In current 0.9.3 version, DateEdit is basically `<input type="date">`, while with new flatpickr integration it will be `<input type="text">`. So my concern is mostly, will it make problems for some project!? Since I cannot decide I need your help. So please vote!

Edit* This is how the new picker looks

![image](https://user-images.githubusercontent.com/900302/119115450-77b87400-ba27-11eb-84e6-884926de16d5.png)

[![](https://api.gh-polls.com/poll/01F6708YCD3ZQSSEDQ785FBTRN/Yes%2C%20make%20it%20part%20of%20DateEdit)](https://api.gh-polls.com/poll/01F6708YCD3ZQSSEDQ785FBTRN/Yes%2C%20make%20it%20part%20of%20DateEdit/vote)
[![](https://api.gh-polls.com/poll/01F6708YCD3ZQSSEDQ785FBTRN/No%2C%20make%20it%20a%20separate%20component)](https://api.gh-polls.com/poll/01F6708YCD3ZQSSEDQ785FBTRN/No%2C%20make%20it%20a%20separate%20component/vote)

**Comment by adopilot** [comment]
Most important part is to control be bindable to model values, We need to serialize form easy and to be able to doing posts without converting text to dates.

**Comment by stsrki** [comment]
All conversion will be done automatically by the Blazorise, the same as it is now. Nothing will change regarding the binding or from the programming side. It will be a slightly different picker(UI) and also a more flexible input mask and display format.

**Comment by d-oit** [comment]
+1 for a new com. DatePicker. 
Note: the vote title are not easy to see with the dark theme. 

![image](https://user-images.githubusercontent.com/6849456/119109901-e4c90b00-ba21-11eb-8596-bdd6264b372f.png)

**Comment by stsrki** [comment]
@d-oit Thanks for voting. It seems the issue with dark mode is already reported https://github.com/srph/gh-polls-web/issues/5

**Comment by techierathore** [comment]
I have voted for the second part :) as most of times we are implementing the date css of the theme.

**Comment by stsrki** [comment]
Separate component won and it is almost done #2403 :)
