### ISSUE TITLE
Using Select in DataGrid does not work as expected

### ISSUE THREAD

**Issue by BerndK** [Megabit/Blazorise#2404]
I just want to edit a enum in a DataGrid using a dropdown (Select).
It only works as expected when I use 'strange' code. 

```
<DataGridSelectColumn TItem="Sensor" Field="@nameof(Sensor.SensorType)" Caption="Type2" Editable="true">
    <EditTemplate>
        @*<Select TValue="SensorType">*@
        @*<Select TValue="SensorType" SelectedValue="@(context.Item.SensorType)">*@
        @*<Select TValue="SensorType" SelectedValue="@(context.Item.SensorType)" SelectedValueChanged="@((v) => context.CellValue = v)">*@
        <Select TValue="SensorType" SelectedValue="@(context.Item.SensorType)" SelectedValueChanged="@((v) => { context.CellValue = v; context.Item.SensorType = v; })">
        @*<Select TValue="SensorType" SelectedValue="@(context.Item.SensorType)" SelectedValueChanged="@((v) => context.Item.SensorType = v)">*@
        @foreach (var item in Enum.GetValues<SensorType>())
        {
            <SelectItem Value="@item">@(item.ToString())</SelectItem>
        }
        </Select>
    </EditTemplate>
</DataGridSelectColumn>
```
Unfortunately only the 4th line seems to work. All the commented versions did not store the selected value when I hit the Save button after editing. One reason that I identified is the call of SetValue in DataGrid.OnSaveCommand. that uses the edited cell value. So looking at this, the 3rd line should work (where I populate the CellValue), but unfortunately in this case the selected value is not displayed (it does not change after selection), seems that in this case the cell looks to the underlying object, not on the CellValue!? So I also have to set the objects value too. Does this mixture make sense?

**Expected behavior**
As long as all this code does not do anything (no conversions) - why do I have to provide it. I would expect that this works out of the box. I could accept to provide the SelectedVale code to preselect an item.

Btw. I did not really find code that handles the DataGridSelectColumn in a different way (compared to DataGridColumn)!?
When using a DataGridSelectColumn with a Enum type, the system should automaitally use the enum names without any additional code at all.

**Comment by stsrki** [comment]
I think this is the same problem as #2356. Definitely, a bug so I will schedule it for 0.9.5. If I find the time I will try to make it sooner.

**Comment by BerndK** [comment]
@stsrki 
Hi Mladen,
thanks for the quick answer. I will wait for the next version...

There is another use case that might be worth to take into acount:
I simply want to select from a list of objects - this also seems not to work, because of the frequent conversion to and from string (all items will have the same string 'MyNameSpace.Zone') behind the scenes (that might be a limitation of html).
This was the only code I managed to get working:
```
        <DataGridColumn TItem="Sensor" Field="@nameof(Sensor.Zone)" Caption="Zone" Editable="true">
            <DisplayTemplate>
                @context.Zone.Name
            </DisplayTemplate>
            <EditTemplate>
                <Select TValue="int" SelectedValue="@(context.Item.Zone.Id)" SelectedValueChanged="@((v) => { var zone = Zones.Single(z => z.Id == v); context.CellValue = zone; context.Item.Zone = zone;})">
                    @foreach (var item in Zones)
                    {
                        <SelectItem Value="@item.Id">@(item.Name)</SelectItem>
                    }
                </Select>
            </EditTemplate>
        </DataGridColumn>
```
I would better use just this:
```
        <DataGridColumn TItem="Sensor" Field="@nameof(Sensor.Zone)" Caption="Zone" Editable="true">
            <DisplayTemplate>
                @context.Zone.Name
            </DisplayTemplate>
            <EditTemplate>
                <Select TValue="Zone" SelectedValue="@(context.Item.Zone)" >
                    @foreach (var item in Zones)
                    {
                        <SelectItem Value="@item">@(item.Name)</SelectItem>
                    }
                </Select>
            </EditTemplate>
        </DataGridColumn>
```
Does this make sense to you?
Perhaps we could use ObjectIDGenerator behind the scenes, to create unique IDs for the used objects that can be converted to strings and back!?

regards, Bernd.

**Comment by stsrki** [comment]
Yes, that is a limitation in html. Everything must end as a string value in the DOM so when you have the complex object it doesn't know how to serialize it. You can use the id like you already did, `context.Item.Zone.Id`, or override `ToString()` on your object and return the id.

Example

```cs
class YourObject
{
  public int Id {get;set;}

  public override string ToString()
  {
    return Id;
  }
}
```

**Comment by BerndK** [comment]
Sure that might be a quickfix, but let's assume that there is already an implementation of ToString() which is not dedicated to the ID.
Anyway I have to setup all this stuff and also have to do the conversion back to the object. All that stuff could be done in the background and will hide the html-limitation - to hide kind of html-limitations is the overall value of blazor and blazorise ;-)
Bernd.

**Comment by stsrki** [comment]
Well, I was thinking of adding some kind of converters to the input component(s) that could be used. That way if the internal converter is not enough you can override it with your own. It is still in a planning state, though.

**Comment by BerndK** [comment]
@stsrki 
Hi Mladen,
I revisited the problem and found the solution. As a fool I used the object's value as SelectedValue, I should better use the CellValue!
```
                        <DataGridSelectColumn TItem="Employee" Field="@nameof(Employee.TestEnum)" Caption="TestEnum" Editable="true">
                            <DisplayTemplate>
                                @context.TestEnum.ToString()
                            </DisplayTemplate>
                            <EditTemplate>
                                <Select TValue="TestEnum" SelectedValue="@((TestEnum)context.CellValue)" SelectedValueChanged="@((v) => { context.CellValue = v; })">
                                    @foreach (var testEnum in Enum.GetValues<TestEnum>())
                                    {
                                        <SelectItem TValue="TestEnum" Value="@testEnum">@testEnum.ToString()</SelectItem>
                                    }
                                </Select>
                            </EditTemplate>
                        </DataGridSelectColumn>

```
As far as I understand, there is no way to simplify this as long as the Cell does not know about the implementation in the EditTemplate, I have to handle the CellValue.
So I think there is no bug here, I'm fine with closing the issue. Sorry for my mistake, I just started using your framework.
