### ISSUE TITLE
[Enhancement] AddTemplate DataGrid

### ISSUE THREAD

**Issue by angelru** [Megabit/Blazorise#2407]
In `DataGrid` we have an `EditTemplate `so that when it is in edit mode we choose a design, wouldn't it be good for Add? I have the case that I have to add "objects dynamically" to a list and paint the html, I have to create a custom add, or does the `AddTemplate `make little sense?

**Comment by stsrki** [comment]
`EditTemplate` is meant to be used for both the `new` and the `edit` mode. I don't think adding `AddTemplate` makes much sense. Nothing that a simple `if` statement inside of EditTemplate couldn't handle already.

**Comment by angelru** [comment]
makes sense, did not know that it also works for new
