### ISSUE TITLE
Performing a Click() (via BUnit) on a Table Cell does not fire the onclick method in the page

### ISSUE THREAD

**Issue by Smurf-IV** [Megabit/Blazorise#2412]
**Describe the bug**
As stated.

Tracked here:
https://github.com/bUnit-dev/bUnit/issues/399

_Example project_ included in the above

**Comment by andz-gl** [comment]
Hello!

any update?

for me it does not work also (.Click() on tr/td of Blazorise's DataGrid)

please type here when it is fixed/resolved or you have any workaround

**Comment by stsrki** [comment]
@David-Moreira can you please have a look at this?

**Comment by andz-gl** [comment]
another helpful info is here (at the end of bUnit discussion): https://github.com/bUnit-dev/bUnit/issues/399

specifically last posts, please look, it could help with debigging

**Comment by David-Moreira** [comment]
Hello,
We've debugged on the Blazorise side. We've answered on BUnit's issue as we need help from the author.
Branch : https://github.com/Megabit/Blazorise/tree/rel-0.9.4-BUnit-DataGrid-RowClickTrigger

**Comment by David-Moreira** [comment]
@andz-gl as a temporary workaround, please use the suggestion provided by @egil on the BUnit's issue, setting the click event argument detail to 1.

Also, expect to not need to explicitly set it in the future, as @egil is expecting to fix it in BUnit in the future.

Updated the branch with working example:
```
    public class DataGridComponentTest : TestContext
    {
        public DataGridComponentTest()
        {
            BlazoriseConfig.AddBootstrapProviders( Services );
        }

        [Fact]
        public void DetailRow_OnClick_ShouldRender()
        {
            // Arrange
            var cut = RenderComponent<DataGridComponent>();

            // Act
            var tableRow = cut.Find( "tr.table-row-selectable" );
            tableRow.Click( detail: 1 );

            // Assert
            var detailRow = cut.Find( "span.detail-row" );
            Assert.NotNull( detailRow );
            Assert.NotNull( cut.Instance.SelectedRow );
        }

    }
```

**Comment by andz-gl** [comment]
Click(detail: 1) works. Thank you!

**Comment by David-Moreira** [comment]
Great! Closing issue.
