### ISSUE TITLE
DataGrid inline edit mode forgets text alignment settings

### ISSUE THREAD

**Issue by CaiusJard** [Megabit/Blazorise#2413]
**Describe the bug**
DataGrid; hit edit, and watch any columns that have e.g. TextAlignment="TextAlignment.Center" lose their alignment settings

**To Reproduce**
1. Go to Blazorise Bootstrap Demo / DataGrid
2. Set edit mode INLINE
3. Hit edit on any row; watch the data in # column
4. Watch the data in # column jump from middle to top left

**Expected behavior**
Alignment retained

**Screenshots**
![image](https://user-images.githubusercontent.com/68939130/119545102-58547a80-bd8a-11eb-97ff-a5c29ca9bea7.png)

**Comment by CaiusJard** [comment]
Actually, I'm a bit confused by something... In the screenshot you can see the row taht is in edit mode isn't inside any TR tag

**Comment by stsrki** [comment]
Yeah, that might be a serious bug. I still haven't tried testing it as I need to finish some other work first.
