### ISSUE TITLE
Add Markdown editor component

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#2415]
**Contestants**

- https://github.com/Ionaru/easy-markdown-editor
- https://github.com/nhn/tui.editor
- https://github.com/Grafikart/JS-Markdown-Editor
- https://github.com/markdown-it/markdown-it
- https://github.com/pandao/editor.md

**Comment by CaptainStealthy** [comment]
Found this after discovering #841 and the `RichTextEdit` component.

For my purposes, RichTextEdit and storing the HTML output should work fine, but I was initially hoping to find a Markdown editor, so I'm definitely upvoting and subscribing to this for future updates!

I could also just manually implement something like EasyMDE or SimpleMDE, but I'm already using Blazorise, so I'd much rather make use of a component that you guys have already built! 😀

**Comment by stsrki** [comment]
I have already implemented https://github.com/Ionaru/easy-markdown-editor for our proprietary project. Soon I will release it as part of Blazorise after I clean some things so it is ready for public usage.

**Comment by stsrki** [comment]
PS. see it in action https://support.blazorise.com/

**Comment by CaptainStealthy** [comment]
That would be great! I'll try to hold off until you do that, then! 

Thanks!

**Comment by CaptainStealthy** [comment]
Is this available in the latest preview version of 0.9.4? Or will I need to wait until the stable version is released?

**Comment by stsrki** [comment]
@CaptainStealthy it is already in the preview. Any feedback is welcome until we release final version.
