### ISSUE TITLE
Changing from inline to popup when editing hides the row and causes a wierd button state for new

### ISSUE THREAD

**Issue by sanguinal** [Megabit/Blazorise#2416]
Hi All,

If creating a new row in the datagrid, if one changes to inline to popup, the new row disappears but is in a editable state. Now that popup is selected, the new button is not available and cannot create a new row in popup mode.

If the gridmode is changed back to inline, the previously hidden new row appears. One has to hit cancel before changing the mode.
**To Reproduce**
![image](https://user-images.githubusercontent.com/19567449/119667201-f8171480-be2d-11eb-909f-a9dbb6c7a657.png)

now change mode 
![image](https://user-images.githubusercontent.com/19567449/119667385-2694ef80-be2e-11eb-90d6-5e6482616ffe.png)

There is no 'new' option.

Forcing a reload of the grid, doesn't solve this. Looking further into it now.

Kind Regards,

Sanguinal.

**Comment by stsrki** [comment]
It is a known limitation that we kinda ignored so far. The scenario when a user would change edit mode is almost zero. Most of the time user will be presented with one edit mode that the developer chooses. At least that is my experience so far.

The demo UI is mostly for our testing purposes when we want to quickly test new features.

**Comment by sanguinal** [comment]
Hi Stsrki,

I believe one of the nice things about the blazorise grid is the ability to give the user the option. As far as I can tell, when the mode is changed it doesn't reset the editing state for a row, which when rendering new or editing rows. The grid  checks if it is inline, and won't render it if its pop-up (which makes total sense as the popup panel takes over). One option would be to clear that state for the row being editing as if the  cancel button were clicked changing the state (maybe in the property setter?). Another possible option is to add a function that just does a reset of editing state, like a CancelAllEdits or something. I need to look further into identifying the variable that knows which item(row) is being edited.

I think that would solve it. I'll keep digging.

Thanks again for your time.

Kind Regards,

Sanguinal

**Comment by stsrki** [comment]
Tested and working in the latest version.
