### ISSUE TITLE
Question: DataGrid for large data and uni-directional state flow

### ISSUE THREAD

**Issue by funtogether** [Megabit/Blazorise#2417]
When using an uni-directional state pattern where the application **state** is modified by **reducers** which are triggered by **actions** which where distributed by **dispatcher** and using large data in `DataGrid` trough `ReadData` I am unsure about the way to work with `ReadData`.

image taken from https://github.com/mrpmorris/Fluxor/raw/master/Images/flux-pattern.jpg (just exchange the click on the counter with for example a click on the pageination component of the grid)
![image](https://user-images.githubusercontent.com/46044838/119773859-8d171d80-bec1-11eb-8d15-07fe133b765f.png)

I guess the method that is called by `ReadData` more or less directly depends on `await` in order to provide for example the `LoadingTemplate`.

My question is here: How would one handle such a situation where `ReadData` fires off an action that requests part of the large data from the server and once its finished it mutates the state. The razor component itself (and thus the grid) is bound to the state that gets injected into the component. The state also contains some properties to reflect the UI (e.g. `IsLoading`)?

For example: At the moment the `LoadingTemplate` will not work, as the `OnReadData`-method fires of an action and directly returns.

Some code for clarification:
```xml
<DataGrid TItem="Document" ReadData="@OnReadData" TotalItems="@State.Value.Documents.TotalItemsCount" Data="@State.Value.Documents.Items" 
          Striped="true" Bordered="true" Hoverable="true" Responsive="true" ShowPager="true" PagerPosition="DataGridPagerPosition.Bottom" 
          PageSize="@State.Value.PageSize">    
```

```csharp
public partial class DocumentsView {

        [Inject]
        public IState<DocumentsState> State { get; set; }

        [Inject]
        private IDispatcher Dispatcher { get; set; }

        protected override void OnInitialized()
        {
            base.OnInitialized();
            State.StateChanged += OnStateChanged;
        }

        private void OnStateChanged(object sender, DocumentsState e)
        {
            StateHasChanged();
        }

        void OnReadData(DataGridReadDataEventArgs<Document> e)
        {
            Dispatcher.Dispatch(new FetchDocumentsAction() { Page = e.Page, PageSize = e.PageSize });
        }
    }
```

**Comment by stsrki** [comment]
It shouldn't make difference where you get data from. Blazor components should (almost) always be updated with parameters. In this case setting `TotalItems="@State.Value.Documents.TotalItemsCount" Data="@State.Value.Documents.Items"` should work. And also a simple call to `InvokeAsync(StateHasChanged)`.

**Comment by funtogether** [comment]
Definitly  `TotalItems="@State.Value.Documents.TotalItemsCount" Data="@State.Value.Documents.Items"` works 👍 as the data gets properly upated in the grid.

But the LoadingTemplate will not show as soon as `Dispatcher.Dispatch(new FetchDocumentsAction()...` gets fired off. 
If I put for example an `await` after dispatching the action (see below) the loading template will show:

```csharp
 async Task OnReadDataAsync(DataGridReadDataEventArgs<Document> e)
        {
            Dispatcher.Dispatch(new FetchDocumentsAction() { Page = e.Page, PageSize = e.PageSize });
            await Task.Delay(1000);
        }
```

**Comment by stsrki** [comment]
loading template might be tricky. Usually, it is handled internally by the DataGrid when ReadData is activated. You can try calling the `dataGrid.Reload()` manually but I'm not sure if it is going to help.

**Comment by StefanOssendorf** [comment]
Hey. Maybe you can work around that with modifiyng your action and take a `TaskCompletionSource` which Task you can return. And your Reducer/Effect can set the Task to Completed. Maybe that's a way to go?

**Comment by stsrki** [comment]
Forgot about this. The LoadingTemplate should be fixed by now and I think it would work in this case. CLosing now.
