### ISSUE TITLE
Cannot build Xamarin.IOS Project

### ISSUE THREAD

**Issue by whann0205** [Megabit/Blazorise#2418]
When i try to build the project targetting a locally attached iphone i
get:

Der Pfad "..\..\..\blazorise.bootstrap\0.9.2.5\staticwebassets\blazorise.bootstrap.css" würde zu einer Datei außerhalb des App-Bundles führen und kann nicht verwendet werden.	AssetQueryApp.iOS	C:\Users\hann.HANN-EDV\.nuget\packages\blazorise.bootstrap\0.9.2.5\staticwebassets\blazorise.bootstrap.css

I found the message in english...
“The path .. would result in a file outside the App Bundle and cannot be used”

Its easy to reproduce simply install https://docs.microsoft.com/en-us/mobile-blazor-bindings/walkthroughs/hybrid-hello-world. 
include blazorise nuget
and build the IOS...

The Android Version works and builds flawlessly.

The Version of blazorise used is 0.9.2.5.

**Comment by stsrki** [comment]
We don't have plans to support Xamarin at this time. Our focus is still mainly on web development. If we got enough resources, we might consider it in the future.

Also, 0.9.2.x is an older version. We only give support for the latest version once it is released. Currently, it is 0.9.3.x
