### ISSUE TITLE
New DatePicker recommendations

### ISSUE THREAD

**Issue by robalexclark** [Megabit/Blazorise#2422]
The new datepicker works really well - thanks!

I have a few suggestions to improve it
Default first day of week to Monday
When a min/max is set and the picker is opened ensure that the calendar shows a date that is in the permitted range
Add a calendar icon on the right hand side of the control

**Comment by stsrki** [comment]
Thanks for the suggestion. I think I can make it work.

**Comment by stsrki** [comment]
With the new API it will be possible to add an icon when the date picker is combined with the addon:

```cshtml
<Addons>
    <Addon AddonType="AddonType.Body">
        <DatePicker @ref="@datePicker" TValue="DateTime?" />
    </Addon>
    <Addon AddonType="AddonType.End">
        <Button Color="Color.Light" Clicked="@(()=>datePicker.ToggleAsync())">
            <Icon Name="IconName.CalendarDay" />
        </Button>
    </Addon>
</Addons>
@code{
    DatePicker<DateTime?> datePicker;
}
```

> When a min/max is set and the picker is opened ensure that the calendar shows a date that is in the permitted range

This is already working. When min/max is set, calendar will automatically disable everything else and will focus only to specified range.
