### ISSUE TITLE
"Closing tag supplied for self-closing element" - Link

### ISSUE THREAD

**Issue by Zumpel96** [Megabit/Blazorise#2424]
**Describe the bug**
Smart complete in Visual Studio (16.10.0) shows the message `Closing tag supplied for self-closing element` when you enter a Link element. In addition, the item is not highlighted properly.

**To Reproduce**
1. Create a Link element
2. Enter the display text

**Expected behavior**
The Link element should be highlighted correctly and not display the warning.
![image](https://user-images.githubusercontent.com/17179371/120291296-7149b800-c2c3-11eb-9f02-bfb3720703aa.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/17179371/120290942-1912b600-c2c3-11eb-840d-f5c17f4e605c.png)

**Additional context**

**Comment by stsrki** [comment]
It is a known bug in VS. See #1353 for reference. Just write it as `<Blazorise.Link>`.

I was thinking of using a different name until they fix it but I couldn't think of anything reasonable. Any ideas?

PS. closing since it is not an issue with Blazorise.

**Comment by Jimmys20** [comment]
> I was thinking of using a different name until they fix it but I couldn't think of anything reasonable. Any ideas?

Maybe `<Anchor></Anchor>`
