### ISSUE TITLE
Datagrid allows duplicate entries. This breaks logic when you have EF Core behind a datagrid.

### ISSUE THREAD

**Issue by radunede** [Megabit/Blazorise#2434]
**Describe the bug**
Inserting allows for duplicate entries. When using with EF Core, db set preserves integrity whereas grid still shows the duplicates.

**To Reproduce**
1. Try with any datagrid and try inserting same row twice.

**Expected behavior**
Nothing should happen if you try to insert same record twice.

**Screenshots**
Attached

**Additional context**
With EF Core this is a problem. Ideally you would provide a property which would prevent insert or edit actions which would 
create duplicates in the datagrid.
<img width="792" alt="2021-06-02 11_38_41-Bootstrap Demo" src="https://user-images.githubusercontent.com/1471811/120458429-8f80e800-c397-11eb-8e87-d14c12b47f5b.png">

**Comment by stsrki** [comment]
This is expected behavior. To check for duplicated and cancel insertion you need to use RowInserting event handler. Similar is for updating, a RowUpdating event.

eg.

```cs
private async Task RowInserting( CancellableRowChange<Employee> eventArgs )
{
    if ( await somethingNotRight )
    {
        eventArgs.Cancel = true;

        return;
    }
}
```

**Comment by radunede** [comment]
I just digged in the documentation more. Sorry, did not see that Event method before. Thanks.
