### ISSUE TITLE
DataGrid DisplayTemplate

### ISSUE THREAD

**Issue by angelru** [Megabit/Blazorise#2444]
```
  <DataGridSelectColumn TItem="QuestionnaireResponse" Field="Categoria.IdCategoria" Caption="@localizer["Category"]" Editable="true">
                <DisplayTemplate>
                    @context.Categoria.NombreCategoria
                </DisplayTemplate>
                <EditTemplate>
                    <Select TValue="string" SelectedValue="@((string)(((CellEditContext)context).CellValue))" SelectedValueChanged="@((v) => context.CellValue = v)">
                        <ChildContent>
                            <SelectItem Value="@(string.Empty)"></SelectItem>
                            @foreach (var category in categories)
                            {
                                <SelectItem TValue="string" Value="@category.IdCategoria">@category.NombreCategoria</SelectItem>
                            }
                        </ChildContent>
                    </Select>
                </EditTemplate>
            </DataGridSelectColumn>
```

the problem is that when I edit, the name is not updated in the table, is this the correct behavior?

**Comment by David-Moreira** [comment]
Hello @angelru,
Sorry for the late reply. From looking at your code, 
I can notice that : 
- the field bound to the Column is the `IdCategoria`. 
- the field you are displaying to the user is the Field: `NombreCategoria`.
- the field that you will update from the `select `selection is the `IdCategoria` not the `NombreCategoria` which means `NombreCategoria ` will remain unchanged unless you refresh your data, to requery the correct `NombreCategoria` for that Id.

Let us know if that helped.

**Comment by angelru** [comment]
@David-Moreira  Yes, everything you just said is correct. I understand that I must change the approach.

**Comment by stsrki** [comment]
@angelru can we close this ticket?
