### ISSUE TITLE
Blazorise.Animation doesn't work at all

### ISSUE THREAD

**Issue by richbryant** [Megabit/Blazorise#2446]
**Describe the bug**
Blazorise.Animation doesn't work at all

**To Reproduce**
1. Add it to your project
2. Attempt to animate a component
3. Nothing happens.

**Expected behavior**
Something happens. I'd settle for anything at all this point.

**Additional context**
This is almost certainly a configuarion issue but since there is no documentation on how to configure Blazorise.Animation and the old Blazor.Animation docs are out of date and don't work, I have no idea where to start with it.

**Comment by stsrki** [comment]
Can you pasta some code sample how you used it?

**Comment by richbryant** [comment]
Sure!

I added the Blazorise.Animate nuget package.

I added the line `<script src="_content/BlazorAnimate/blazorise.animate.js"></script>` to index.html last before the call to blazor.webassembly.js. I took the name of the file from the Blazor.Animation source.

I created a test component naamed TestText.razor

`<div><h1>Test Text</h1></div>`

and I added the following to Index.razor

```
<Animate Animation="Animations.FadeUpRight" Duration="TimeSpan.FromSeconds(3)" >
    <TestText/>
</Animate>
```

It displayed as just normal H1 text. No animation.

**Comment by richbryant** [comment]
oh shit, it's the script line isn't it? Rechecking.

**Comment by stsrki** [comment]
Must be. Just tested and it's working.

**Comment by richbryant** [comment]
yeah I just changed it to

`<script src="_content/Blazorise.Animation/blazorise.animate.js"></script> and it didn't

**Comment by richbryant** [comment]
what setup are you using that works?

**Comment by stsrki** [comment]
Did you solve it?

I'm using 

```
<Animate Animation="Animations.FadeUpRight" Duration="TimeSpan.FromSeconds(3)">
    <div><h1>Test Text</h1></div>
</Animate>
```

**Comment by richbryant** [comment]
I did, the problem was not knowing that the base path was /Blazorise.Animate/ and not my guess of /Blazorise.Animation/

Thanks for the heads up.

**Comment by Trimatix** [comment]
for anyone else with similar problems, my issue was that the blazorise.animate.js script version number that I referenced as above didn't exactly match the version of the nuget package that I had installed, since I had recently updated it.
