### ISSUE TITLE
DataGridAggregateType.Average should not include nulls in its calculation

### ISSUE THREAD

**Issue by robalexclark** [Megabit/Blazorise#2450]
For the calculation of an average, a null != 0 so should not be included in the calculation of the average

A possible fix would be for [line 86-88 of DataGridAggregate.cs](https://github.com/Megabit/Blazorise/blob/243bf81aac90cf1b18799c72890cd837789f4467/Source/Extensions/Blazorise.DataGrid/DataGridAggregate.cs#L86) to be changed to 

```
            return ( from item in Data.Where( x => x != null )
                     let value = column.GetValue( item )
                     select Convert.ToDecimal( value ) ).Average();
```

**Comment by stsrki** [comment]
Not checking for null would raise an exception when `column.GetValue( item )` is called.

**Comment by robalexclark** [comment]
I couldn't find a proper solution to this, so in the end just used the aggregation function to filter out nulls


```
<DataGridAggregate TItem="MenstrualCycle" Field="@nameof( MenstrualCycle.Duration )" AggregationFunction=@((values,col)=>values?.Where(v=>v.Duration.HasValue)?.Average(v=>v.Duration))>
                        <DisplayTemplate>
                            <strong>@($"Average: {context.Value}")</strong>
                        </DisplayTemplate>
                    </DataGridAggregate>
```

**Comment by stsrki** [comment]
Yep, that's why we created it.

Sorry I forgot about it being existing :)
