### ISSUE TITLE
Data not loaded before Chart is drawn

### ISSUE THREAD

**Issue by TorbjornEliasson** [Megabit/Blazorise#2455]
I experience random problems with the chart not being drawn with real data from the database. It seems that OnAfterRender is not waiting for OnInitializedAsync all the times.  Is there a preferred/recommended way to load data? The code is like this:

```
  protected override async Task OnInitializedAsync()
  {
     await GetDataFromDatabase();
  }
  protected override async Task OnAfterRenderAsync(bool firstRender)
  {
         if (!firstRender) return;
         await RedrawChart();
  }
  private async Task RedrawChart()
  {
         await StatusChart.Clear();
         await StatusChart.AddLabelsDatasetsAndUpdate(GetLabels().ToArray(), GetChartData());
  }
```

**Comment by stsrki** [comment]
Can you move `await GetDataFromDatabase();` into OnAfterRenderAsync?

**Comment by TorbjornEliasson** [comment]
I have tried that but it does not solve the problem. There is still random problems.

**Comment by stsrki** [comment]
Can you post a full page source?

**Comment by TorbjornEliasson** [comment]
@using Blazor.Components.Misc;
@using Blazorise.Charts;
@using BusinessLogic.Converters;
@using BusinessLogic.Dtos;
@using Microsoft.AspNetCore.Components;
@using Repository;
@using System;
@using System.Collections.Generic;
@using System.Threading;
@using System.Threading.Tasks;
@inject IStringLocalizer<DueDiligenceChartImplementation> Loc
@inherits OwningComponentBase

<Card Margin="Margin.Is4.OnY">
    <CardHeader>
        <CardTitle>@Loc["Implementation"]</CardTitle>
    </CardHeader>
    <CardBody>
        <DoughnutChart @ref="StatusChart" TItem="double" />
    </CardBody>
</Card>
@code
{
    [CascadingParameter] private StateProvider StateProvider { get; set; }
    [Parameter] public int CompanyId { get; set; }
    private DoughnutChart<double> StatusChart = new DoughnutChart<double>();
    private List<DueDiligenceCheckpointDto> DueDiligenceCheckpointDtos = new List<DueDiligenceCheckpointDto>();
    private DueDiligenceRepository DueDiligenceRepository;

    private CancellationTokenSource CancellationTokenSource = new CancellationTokenSource();
    private CancellationToken Token = CancellationToken.None;
    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        Token = CancellationTokenSource.Token;
        DueDiligenceRepository = (DueDiligenceRepository)ScopedServices.GetService(typeof(DueDiligenceRepository));
        await GetDataFromDatabase();
    }
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        await base.OnAfterRenderAsync(firstRender);
        if (!firstRender) return;
        await RedrawChart();
    }
    private async Task GetDataFromDatabase()
    {
        DueDiligenceCheckpointDtos = new DueDiligenceCheckpointConverter().ToDtos(
                            await DueDiligenceRepository.GetCheckpoints(CompanyId, Model.Common.Constants.ContentType.DueDiligenceCheckpoint, Token));
    }
    private async Task RedrawChart()
    {
        await StatusChart.Clear();
        await StatusChart.AddLabelsDatasetsAndUpdate(GetLabels().ToArray(), GetChartData());
    }
    private DoughnutChartDataset<double> GetChartData()
    {
        return new DoughnutChartDataset<double>
        {
            Label = Loc["Implementation"],
            Data = GetData(),
            BackgroundColor = Common.Chart.GetBackgroundColors(),
            BorderColor = Common.Chart.GetBackgroundColors(),
            BorderWidth = 1,
        };
    }
    private List<double> GetData()
    {
        var data = new List<double>();
        foreach (var status in BusinessLogic.BusinessLogic.DueDiligence.GetStatusesForDueDiligence(StateProvider.UserDto.IsProjectAdmin))
        {
            data.Add(CountStatus(status.Code));
        }

        data = AddVerifiedForNotProjectAdmin(data);

        return data;
    }
    private List<double> AddVerifiedForNotProjectAdmin(List<double> list)
    {
        if (StateProvider.UserDto.IsProjectAdmin) return list;
        list[^1] += CountStatus(Model.Common.Constants.Status.Verified);
        return list;
    }
    private int CountStatus(Model.Common.Constants.Status status)
    {
        return DueDiligenceCheckpointDtos
               .FindAll(c => c.CheckpointStatus == status)
               .Count;
    }
    private List<string> GetLabels()
    {
        var labels = new List<string>();
        BusinessLogic.BusinessLogic.DueDiligence.GetStatusesForDueDiligence(StateProvider.UserDto.IsProjectAdmin).ForEach(status => labels.Add(Loc[status.Description()]));
        return labels;
    }

    void IDisposable.Dispose()
    {
        CancellationTokenSource?.Cancel();
        CancellationTokenSource?.Dispose();
        CancellationTokenSource = new CancellationTokenSource();
        Token = CancellationTokenSource.Token;
    }
}

**Comment by stsrki** [comment]
This is an older post so you're probably moved on or managed to make it work. In any case, if it's still a problem please try the newest version, and if not working please reopen it. Thanks.
