### ISSUE TITLE
Use badge as notification sign

### ISSUE THREAD

**Issue by dkonstantinov193** [Megabit/Blazorise#2456]
**Is your feature request related to a problem? Please describe.**
I'm trying to create a pretty standard app notification bell using Badge component but can't combine it together with some icon. 
It would be good to either have some kind of options for Badge component or create a dedicated component so developer will be able to create notifiers like https://mudblazor.com/components/badge using Blazorise.

**Comment by stsrki** [comment]
Our Badge component is based upon https://getbootstrap.com/docs/4.6/components/badge/. All other providers have a similar component. MatBlazot from what I can see has a different behavior, probably based on material guidelines. I'm not sure if creating the new component makes much sense. With little play, I was managed to replicate it.

**Example**

```cshtml
<Div Display="Display.InlineBlock">
    <Button Color="Color.Primary">
        Hello
    </Button>
    <Badge Color="Color.Danger" Style="position:relative;top:-20px;left:-20px;">99+</Badge>
</Div>
```

**Result**

![image](https://user-images.githubusercontent.com/900302/121198495-7635db00-c872-11eb-94a3-98cd3050fc56.png)

![image](https://user-images.githubusercontent.com/900302/121198529-7afa8f00-c872-11eb-86ad-8d39cc6ad143.png)

**Comment by stsrki** [comment]
In 0.9.5 we have introduces many new utilities which will make this easy to do and documented it https://preview.blazorise.com/docs/helpers/utilities/position

**Comment by dkonstantinov193** [comment]
Cool, very helpful.
