### ISSUE TITLE
Autofocus on Buttons

### ISSUE THREAD

**Issue by Enritski** [Megabit/Blazorise#2457]
I see that there is now an Autofocus property on TextEdit and NumericEdit controls, which is great!

Would it be possible to extend this to Buttons as well?  This is so that, for example, I could have a modal dialog with the 'OK' button already focussed so the user can just hit the enter key to acknowledge it.

**Comment by Jimmys20** [comment]
You can achieve similar behaviour using the following code:

```
<Form>
    ...
    <Button Type="ButtonType.Submit" PreventDefaultOnSubmit="true" Click="YourClickHandler">Submit</Button>
</Form>
```
When you press Enter key `YourClickHandler` will get invoked

https://blazorise.com/docs/components/button/#submit-button

**Comment by stsrki** [comment]
Somehow I missed this ticket...

@Jimmys20 answer is the preferred way of doing it.

**Comment by CyberCervin** [comment]
I cannot get this approach to work when using it for a button in a modal. Will this be handled differently for modals?

**Comment by stsrki** [comment]
@CyberCervin Can you post your code? I use it all the time in my projects, should work.

**Comment by CyberCervin** [comment]
`<Modal @ref="_modal" Closing="OnModalClosing">
    <ModalContent Centered="true">
        <ModalBody>
            <Heading Size="HeadingSize.Is4" Color="TextColor.Secondary">Titel</Heading>
            <Paragraph>@_message</Paragraph>
            <Paragraph Class="hide-boder-transition-on-focus" >
                <FieldLabel>Comments</FieldLabel>
                <MemoEdit @bind-Text="@_comment" Disabled="_busy"/>
            </Paragraph>
            <Paragraph  Alignment="TextAlignment.Center">
                <Form>
                    <Button Class="margin-around-button" Type="ButtonType.Submit" PreventDefaultOnSubmit="true" Color="Color.Primary" Clicked="@OnOk" Loading="_busy" Disabled="_busy" >@Localizer["ok-button"]</Button>
                    <Button Class="margin-around-button" Type="ButtonType.Button" Color="Color.Light" Clicked="@OnCancel">@Localizer["cancel-button"]</Button>          
                </Form>
            </Paragraph>
        </ModalBody>
    </ModalContent>
</Modal>`

**Comment by CyberCervin** [comment]
`

    <ModalContent Centered="true">
        <ModalBody>
            <Heading Size="HeadingSize.Is4" Color="TextColor.Secondary">@Localizer["journeyreasondialog-title"]</Heading>
            <Paragraph>@_message</Paragraph>
            <Paragraph Class="hide-boder-transition-on-focus" >
                <FieldLabel>@Localizer["journeyreasondialog-comments"]</FieldLabel>
                <MemoEdit @bind-Text="@_comment" Disabled="_busy"/>
            </Paragraph>
            <Paragraph  Alignment="TextAlignment.Center">
                <Form>
                    <Button Class="margin-around-button" Type="ButtonType.Submit" PreventDefaultOnSubmit="true" Color="Color.Primary" Clicked="@OnOk" Loading="_busy" Disabled="_busy" >@Localizer["ok-button"]</Button>
                    <Button Class="margin-around-button" Type="ButtonType.Button" Color="Color.Light" Clicked="@OnCancel">@Localizer["cancel-button"]</Button>          
                </Form>
            </Paragraph>
        </ModalBody>
    </ModalContent>
</Modal>`

**Comment by stsrki** [comment]
You're missing a `Form` tag

```
<ModalContent Centered="true">
    <ModalBody>
        <Form>
            <Heading Size="HeadingSize.Is4" Color="TextColor.Secondary">@Localizer["journeyreasondialog-title"]</Heading>
            <Paragraph>@_message</Paragraph>
            <Paragraph Class="hide-boder-transition-on-focus">
                <FieldLabel>@Localizer["journeyreasondialog-comments"]</FieldLabel>
                <MemoEdit @bind-Text="@_comment" Disabled="_busy" />
            </Paragraph>
            <Paragraph Alignment="TextAlignment.Center">
                <Form>
                    <Button Class="margin-around-button" Type="ButtonType.Submit" PreventDefaultOnSubmit="true" Color="Color.Primary" Clicked="@OnOk" Loading="_busy" Disabled="_busy">@Localizer["ok-button"]</Button>
                    <Button Class="margin-around-button" Type="ButtonType.Button" Color="Color.Light" Clicked="@OnCancel">@Localizer["cancel-button"]</Button>
                </Form>
            </Paragraph>
        </Form>
    </ModalBody>
</ModalContent>
```

**Comment by CyberCervin** [comment]
No, in the example I have a `Form` tag around the buttons. Placing them around all the paragraphs does not make a difference for me unfortunately. I have also tried using JavaScript to set focus (https://www.meziantou.net/auto-focus-an-input-in-a-blazor-form.htm) but that does not work perfect. I then need to press Enter once to get the button in focus and then Enter a second time to "press" the button. This seems really tricky...

**Comment by Jimmys20** [comment]
Try this:

```
<ModalContent Centered="true">
    <ModalBody>
        <Form>
            <Heading Size="HeadingSize.Is4" Color="TextColor.Secondary">@Localizer["journeyreasondialog-title"]</Heading>
            <Paragraph>@_message</Paragraph>
            <Paragraph Class="hide-boder-transition-on-focus">
                <FieldLabel>@Localizer["journeyreasondialog-comments"]</FieldLabel>
                <MemoEdit @bind-Text="@_comment" Disabled="_busy" Autofocus="true" />
            </Paragraph>
            <Paragraph Alignment="TextAlignment.Center">
                <Button Class="margin-around-button" Type="ButtonType.Submit" PreventDefaultOnSubmit="true" Color="Color.Primary" Clicked="@OnOk" Loading="_busy" Disabled="_busy">@Localizer["ok-button"]</Button>
                <Button Class="margin-around-button" Type="ButtonType.Button" Color="Color.Light" Clicked="@OnCancel">@Localizer["cancel-button"]</Button>
            </Paragraph>
        </Form>
    </ModalBody>
</ModalContent>
```

I added Autofocus="true" in your MemoEdit component so that the form gets focused, then enter key should work.

**Comment by stsrki** [comment]
Sorry, I missed the Form around the buttons. Try @Jimmys20 sample please.

**Comment by CyberCervin** [comment]
@Jimmys20 the MemoEdit gets focused as it should but pressing Enter just creates a new line in the MemoEdit.

I found a workaround however. I use `OnFocus` in MemoEdit to call this method 
` private async Task FocusOkButton()
        {
            await SetFocusOnElementHelper.SetFocusAsync(_okButton.ElementRef);
        }` 
That is turn will use JavaScript to set focus to the button as shown in https://www.meziantou.net/auto-focus-an-input-in-a-blazor-form.htm. Note that you don't need to call the JavaScript in OnAfterRenderAsync as in the tutorial, only in the method above.

**Comment by CyberCervin** [comment]
However, that was a stupid workaround, since I now cannot edit that MemoEdit. Guess you have to add check to see if this is the first time the MemoEdit gets focused....

**Comment by Jimmys20** [comment]
You are right, it works for plain TextEdit, but for MemoEdit it just creates a new line which is expected.

In latest Blazorise 0.9.4 preview version there is a new `VisibleChanged` EventCallback for Modal component so you could do something like this

```
<Modal VisibleChanged="OnVisibleChanged">
    ...
</Modal>

@code {
    private async Task OnVisibleChanged(bool isVisible)
    {
        if (isVisible)
        {
             await SetFocusOnElementHelper.SetFocusAsync(_okButton.ElementRef);
        }
    }
}
```

**Comment by CyberCervin** [comment]
Thanks for the help today! My issue is solved :)
