### ISSUE TITLE
DropDown in a DataGrid does not "open"

### ISSUE THREAD

**Issue by Smurf-IV** [Megabit/Blazorise#2459]
Using the following from _Originally posted by @stsrki in https://github.com/Megabit/Blazorise/issues/853#issuecomment-703824996_

```cshtml
<DataGridColumn TItem="Order" Field="@nameof( Order.Id)" Sortable="false" Filterable="false" Width="120px">
    <DisplayTemplate>
        <Button Color="Color.Primary" Clicked="@(()=>OnSendEmailClicked(context.Id))">
            Send Email
        </Button>
    </DisplayTemplate>
</DataGridColumn>
```
But using a `DropDown` in place of the `Button` does not "Open" the Drop down

More Info:
Using Bootstrap display
Using latest Blazorise
Using .Net 5
Client Side

**Comment by stsrki** [comment]
How do you use Dropdown? I'm using it without problem in my own project.

Eg.

```cshtml
<Dropdown>
    <Button Color="Color.Primary" Clicked="@context.Clicked">
        @context.LocalizationString
    </Button>
    <DropdownToggle Color="Color.Primary" Split />
    <DropdownMenu>
        <DropdownItem Clicked="@(()=>OnSendVerificationEmailClicked(context.Item.Id))">Send verificaion email</DropdownItem>
    </DropdownMenu>
</Dropdown>
```

**Comment by Smurf-IV** [comment]
The run says _**no**_.

![ClickAndNothingHappens](https://user-images.githubusercontent.com/2418812/121364438-b27b4100-c92f-11eb-8680-d98724cbf3d4.gif)

``` c#
<DataGridColumn TItem="UserModel" Field="@nameof(UserModel.Id)" Sortable="false" Filterable="false" Width="120px">
                    <DisplayTemplate>
                    @if (!context.IsExternal)
                    {
                        <Dropdown Direction="Direction.Left">
                            <DropdownToggle Color="Color.Primary">User actions</DropdownToggle>
                            <DropdownMenu>
                                <DropdownItem Clicked="@(() => AssignToRole(context))">Assign to role</DropdownItem>
                                @if (!context.IsConfirmed)
                                {
                                    <DropdownItem Clicked="@(() => DoConfirmation(context))">Do confirmation</DropdownItem>
                                }
                            </DropdownMenu>
                        </Dropdown>
                    }
                    </DisplayTemplate>
                </DataGridColumn>
```

**Comment by Smurf-IV** [comment]
oh, and where did your `Item` come from ?
Or is that part of your `TItem` object and not to be confused with the `EditCommandTemplate` `context.Item` ?

**Comment by stsrki** [comment]
U placed your code into DisplayTemplate of my own grid and it works

![image](https://user-images.githubusercontent.com/900302/121365682-266e1700-c939-11eb-81b6-e34fdaede4ee.png)

Can you inspect in dev tools and see that it actually changes class names on the dropdown menu?

**Comment by Smurf-IV** [comment]
![image](https://user-images.githubusercontent.com/2418812/121366537-7812a380-c931-11eb-868d-94297ab63445.png)

**Comment by stsrki** [comment]
Then something else is overriding menu style. Maybe some css `fixed` rule, or overflow.

**Comment by Smurf-IV** [comment]
Setting the width to 300 doesn't sort it (The Button is still left most)

**Comment by Smurf-IV** [comment]
![image](https://user-images.githubusercontent.com/2418812/121367806-844b3080-c932-11eb-9ffb-7a94550aae0f.png)

**Comment by stsrki** [comment]
Do you have DataGrid Responsive parameter? It can affect dropdown.

**Comment by Smurf-IV** [comment]
And this is the only thing that appears in the `app.css` that "might" have an effect (But doesn't even when deleted)
``` css
.dropdown-toggle.active-dropdown::after {
    transform: rotate(-90deg);
}
```

**Comment by Smurf-IV** [comment]
> 
> 
> Do you have DataGrid Responsive parameter? It can affect dropdown.

One of these?:
![image](https://user-images.githubusercontent.com/2418812/121368316-e4da6d80-c932-11eb-94c1-2421282f323c.png)

**Comment by stsrki** [comment]
Yes, try `Responsive="false"`

**Comment by Smurf-IV** [comment]
That was the one :-)
Will this need a modification to the intellisense on that field to state that it messes with buttons in the row ?

**Comment by Smurf-IV** [comment]
Ok, "Blazorise" cannot fix it, but the intellisense, on the field`Responsive` could either mention it, or refer to the link above.

**Comment by stsrki** [comment]
Yes, I can do that.

**Comment by Smurf-IV** [comment]
And or implement the following
![Uploading image.png…]()

**Comment by stsrki** [comment]
I tried that before but it some use-cases it doesn't work. So I will just add a comment for IntelliSense and add a link to SO.
