### ISSUE TITLE
Time picker TimeChanged stoped firing

### ISSUE THREAD

**Issue by kzemlickas** [Megabit/Blazorise#2462]
OnTimeChangedAsync do not fire after 0.9.3.7 and 0.9.3.8 updates.
0.9.3.6 works fine. 

![image](https://user-images.githubusercontent.com/47169468/121486156-8f0cd080-c9d9-11eb-9b49-d6be49889054.png)

![image](https://user-images.githubusercontent.com/47169468/121487033-5faa9380-c9da-11eb-99f8-c79a4af80479.png)

**Comment by Enritski** [comment]
I'm affected by this issue, too.  Are you expecting to release the fix shortly, or should I downgrade to v0.9.3.6 in the meantime?

Thanks, as always!

**Comment by stsrki** [comment]
I'm now preparing for the release.

**Comment by Enritski** [comment]
Brilliant, thank you!

**Comment by stsrki** [comment]
Relased!

**Comment by Enritski** [comment]
And it works brilliantly!  Thank you once again :)
