### ISSUE TITLE
Demo improvement

### ISSUE THREAD

**Issue by dtitovgis** [Megabit/Blazorise#2465]
https://bootstrapdemo.blazorise.com
Allow users on demo pages view the code for example.

**Comment by stsrki** [comment]
Thanks for contacting us. The complete overhaul of demo apps and docs is already planed. We will start soon and it will include code samples along with the component usages.

**Comment by Luk164** [comment]
@stsrki Great, I was getting a bit annoyed with having to look through the code manually to find how the examples were made.

**Comment by stsrki** [comment]
We already have finished the new docs app with code samples that will be released soon. Demo apps will stay as is, mostly for us to test internally.
