### ISSUE TITLE
Change Size globally - Theming?

### ISSUE THREAD

**Issue by bodeg** [Megabit/Blazorise#2472]
How to  I change the size of my controls (TextEdit, DateEdit, Select, etc.) globally in my app?

For example:
` <TextEdit Size="Size.Small"/>` 

With regards.

**Comment by stsrki** [comment]
Lucky coincidence :) I just wanted to implement the Size parameter through the theming options. It will be available in 0.9.4. Until then only setting the individual Size on each component is the only option.

**Comment by bodeg** [comment]
Thanks!
