### ISSUE TITLE
Show more properties on DataGrid popup edit form

### ISSUE THREAD

**Issue by GilShalit** [Megabit/Blazorise#2473]
This is quite simple - I have a class which is used in a DataGrid for CRUD operations.  The point is that there are more fields than what is feasible to display in the grid, and the DetailsRowTemplate is not a good fit for columns with long notes plus I have other stuff to display there.

So my question is if it is (or will be) possible to mark columns to only display in the popup edit form?

**Comment by stsrki** [comment]
You can use `Displayable="false"` to hide the column from the grid. And `Editable` to show it in edit mode. Also, you have two additional parameters to control the visibility in edit mode, `CellsEditableOnEditCommand` and `CellsEditableOnNewCommand`.

**Comment by GilShalit** [comment]
Man, I just need to ask..  Huge thank you!
