### ISSUE TITLE
API changes for the enum values

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#2479]
Currently for a lot of enum types like `Size`, `Color`, `TextAlignment` and many others, we have a default enum value of `None`. The value `None` means the CSS class name or some other element style will not be set. For the majority of components `None` is OK and doesn't lead to problems. But in some rare cases, `None` has a different meaning. For example `Display.None` doesn't mean style will not be applied. It means an element will be hidden. This inconsistency I would like to solve and I think it is the right time now to do it before we reach v1.0.

---

What I propose is to convert all enum parameters to nullable, eg.

```cs
public Size? Size { get; set; }
```

This will have the benefit where `null` will mean the parameters are not set, and its class names or styles shouldn't need to be applied. With this approach, `None` can be safely removed from the majority of enum types, and we can leave it only on those that actually have a usable meaning.

---

All of these changes are breaking changes and a lot of files will be affected. But I don't think it will be much of a problem since even now when users set the parameter they don't use `Size.None` or `Color.None`. It is already a default value for all parameters. So converting it to null would not be much of a problem. We would need to document all changes and mention it on the migration guide along with v0.9.4 release notes.

**Comment by stsrki** [comment]
I'm currently working on #2472 and without making Size nullable it is impossible to differentiate it from the set or unset value. With null this is possible. Also, making everything nullable will open doors to easier theming on a global application level.

**Comment by stsrki** [comment]
Maybe in the end there are still use cases for `None` being present as an option. Without it, it would be hard to override global theme settings on each individual component.

For example lets's say we have a defined theme options for button, `Theme.ButtonOptions.Size = Size.Small`. All buttons in the app should automatically be made smaller. Remember, `Size` is now nullable on all components. But, if we want to have some buttons to be default sized we would still need to have a `None` enum. So setting `<Button Size="Size.None">` should override theme settings. If we would leave it as `null` it would still use global theme options.

My only concern is since Size parameter is nullable is it better to rename `None` to `Default`. To me `Size="null"` and `Size="Size.None"` might be too similar in term of meaning and could lead to confusion. So, `Size="Size.Default"` would be much better when reading the code.

@David-Moreira ?

**Comment by David-Moreira** [comment]
Yea, agree with `Size.Default`. Would that not be a good replacement for the nullable? Make it be Size.Default instead? Or do you find use cases where the absence of value makes sense?

**Comment by stsrki** [comment]
Note for me: Add implicit `string` operator to `Width` utility. This will allow it to be defined as `Width="150px"`, which at the moment is not possible.
