### ISSUE TITLE
Card Background.Dark not being set

### ISSUE THREAD

**Issue by sturlath** [Megabit/Blazorise#2482]
If I set Background to Background.Dark it is just stays white. Is this a bug or just connected to styling in the abp.io framework I´m using? If so I´ll file a bug there

Here is the code I´m using with Warning that works fine

```xml
<Card Margin="Margin.Is4.FromBottom" Background="Background.Warning" WhiteText="true">
    <CardBody>
        <CardTitle Size="4">Test</CardTitle>
    </CardBody>
    <CardFooter Style="background-color: rgb(10 11 84)">
        <Fields>
            <Field>
                <small class="text-muted">@DateTime.Now().ToShortDateString()</small>
            </Field>
            <Field>
                <small class="text-muted" style="position: absolute; right: 5px;">@DateTime.Now().ToShortTimeString()</small>
            </Field>
        </Fields>
    </CardFooter>
</Card>
```

![image](https://user-images.githubusercontent.com/2386572/122195106-932b6900-ce85-11eb-9f98-d5e65e4613d0.png)

**Comment by stsrki** [comment]
It is working just fine in our demo app.

![image](https://user-images.githubusercontent.com/900302/122197213-42713b80-ce98-11eb-9a8b-8ab0bc59cbe8.png)

Maybe in ABP, there is some special CSS override for background dark? Maybe you have a dark theme so everything is reversed?

**Comment by sturlath** [comment]
I have gone through all the themes (lepton) and they are all like this. So I guess that there is something overriding it in ABP. 

Here is one of the lighter ones Style 5.
![image](https://user-images.githubusercontent.com/2386572/122219653-2b821780-ce9f-11eb-836e-f1685545b15b.png)

**Comment by sturlath** [comment]
I created [another issue in abp.io](https://github.com/abpframework/abp/discussions/10205) and now because I can´t remove shadows from cards (at least). 

Like I comment there, I find it strange that explicitly setting `Shadow="Shadow.None"` on a component doesn´t override the CSS styling of some theme. Is that not correct line of thought?
