### ISSUE TITLE
Background and WhiteText properties to children element of Card?

### ISSUE THREAD

**Issue by sturlath** [Megabit/Blazorise#2483]
Is it possible to add Background and WhiteText properties to CardBody,CradHeader and CardFooter ? 

At the moment Background and WhiteText only applies to CardBody so now I have to manually style to them. But then I loose control of theming. 

```xml
<Card Margin="Margin.Is4.FromBottom" Background="Background.Warning" WhiteText="true">
    <CardBody>
        <CardTitle Size="4">test</CardTitle>
    </CardBody>
    <CardFooter Style="background-color: rgb(10 11 84)">
        <Fields>
            <Field>
                <small class="text-muted">@DateTime.Now().ToShortDateString()</small>
            </Field>
            <Field>
                <small class="text-muted" style="position: absolute; right: 5px;">@DateTime.Now().ToShortTimeString()</small>
            </Field>
        </Fields>
    </CardFooter>
</Card>
```

![image](https://user-images.githubusercontent.com/2386572/122196691-fa95e880-ce86-11eb-96c1-0541f4aa39fc.png)

**Comment by stsrki** [comment]
Yes, but only in v0.9.4. Background, TextColor, TextAlignment, and many other utilities will be/are available for every component so it will be a lot easier to style your app.
