### ISSUE TITLE
File Edit doesn't reste file name or path

### ISSUE THREAD

**Issue by davidjhurtado** [Megabit/Blazorise#2490]
**Describe the bug**
Whe i use a FileEdit control for upload files, it doen's reset the name or file path when the action is complete.
I turn on Autoreset but it doesn't works

**To Reproduce**
1. Insert an FileEdit component on a razor file.
     <FileEdit Changed="OnChangedFileEditTicket"  Multiple="false" @ref="@fileEdit" AutoReset="true"/>
2. Complete the actions on Changed event.

3. The display name or file doen't changed.

**Expected behavior**
I hope that the control be clear o blank when the user complete the action.
Even i close the modal screen and reopen the control has the same text for file path.

**Screenshots**
![image](https://user-images.githubusercontent.com/13089183/122459974-91de6700-cf7f-11eb-9ed7-5cd9970d0d4b.png)

**Additional context**

**Comment by stsrki** [comment]
@davidjhurtado What is your Blazorise version?

I'm testing on the latest v0.9.3.9 and v0.9.4-preview and it works without issues for me.

**Comment by davidjhurtado** [comment]
Version => 0.9.3-preview6

**Comment by stsrki** [comment]
Preview 6!?? That is the really old version. Any chance you could update your project to 0.9.3.x?

**Comment by davidjhurtado** [comment]
Right now i can't update...

**Comment by stsrki** [comment]
Once you update and if the error is still present please open a new ticket. I will close this now since it is working in current conditions.
