### ISSUE TITLE
Buttons : Loading while async Clicked Action is running

### ISSUE THREAD

**Issue by StephenOTT** [Megabit/Blazorise#2496]
**Describe the solution you'd like**

When working with Buttons, a very common use case is to click the button, run some action such as call a API and get the 2xx response.  Would be great if the Clicked action could tie into Loading attribute so we do not need to manually control it.  

When the Clicked Task returns a success then the loading would return to false.

**Comment by stsrki** [comment]
Did you mean this? https://blazorise.com/docs/components/button/#loading

**Comment by StephenOTT** [comment]
Yes i am talking about those buttons and that loading attribute.  To enable/disable the loading, one would need to store the state of Loading (in a boolean var) and/or store the button as a field.

Would it be possible to have the loading trigged (automatically) when calling the `Clicked` async event, and when the event completes / callback returns, `Loading` is returned to `false` ?

**Comment by stsrki** [comment]
I would say it is possible. Similar behavior is already present for the DataGrid component. Although it would be breaking change if the loading state would be controlled internally.

For now, I will schedule it for 0.9.5.

**Comment by StephenOTT** [comment]
Could it be a optional attribute?  `<Button LoadingOnClicked="true">` ?.

**Comment by stsrki** [comment]
Yeah, that might be good idea.

**Comment by stsrki** [comment]
After a little investigation, I think this feature is not going to be worked on. We already support it(with a little more code), and from what I can see in other libraries they also have a similar approach.
