### ISSUE TITLE
MS teams control library support

### ISSUE THREAD

**Issue by StephenOTT** [Megabit/Blazorise#2498]
Potential use case for you that could increase the popularity of blazorise: 
Adding the Teams control library and css as one of the supported Libs. This would allow rapid builds of Ms Teams apps using the blazorise lib.  

https://officedev.github.io/msteams-ui-components/#/

https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-blazor?tabs=vs

**Comment by stsrki** [comment]
Doesn't seem like it is actively maintained. The last commit was a year ago.

From the technical side, it seems easy to implement. They have only some basic components so it would be pretty limited from the Blazorise side.
