### ISSUE TITLE
Refresh single data grid row?

### ISSUE THREAD

**Issue by StephenOTT** [Megabit/Blazorise#2499]
**Is your feature request related to a problem? Please describe.**
Is there an ability to refresh a single data grid row, without reloading the entire grid?

This would enable a user to action something (such as in the Detail Row) and it would cause a refresh of the data in the Row/one of the columns.  The change would not have an affect on the other rows, sort order, or page of the grid and thus a requery/refresh would not always be needed.

**Comment by StephenOTT** [comment]
(although this may lead back to #1573 type of functionality (such as performing an action on a card and only the card refreshes).

**Comment by stsrki** [comment]
We can do it as part of #1994

**Comment by David-Moreira** [comment]
I'd like to work on this one. But I'm not even sure what is exactly intended? Can you guys elaborate a bit?

**What I imagine :** To refresh a single data grid row, I would imagine that technically, you'd have to provide the following:
- `RefreshRow(TItem Item)`, so you can programatically trigger the row you would like to refresh
- `Action<Item> OnRowRefresh`, so you can manipulate and refresh the row?

Is this what's being requested? 
Other than this, could it be:
- It's just a straight up `StateHasChanged` call to the row, so Blazor tries to find any new differences for any reason?
- I would not be sure about changing the ReadDataArguments to handle this "offcase".

**Comment by stsrki** [comment]
I've been thinking about this and I don't see an easy way to refresh just a single row. We would have to have a dictionary of items internally to be able to detect the row by some hash key. It would require major refactoring.

And I don't think it is worth it. From what I can see, simply calling StateHasChanged on a page would refresh the grid if the item has changed.
