### ISSUE TITLE
 Possibility of waiting for a result of a Dialog

### ISSUE THREAD

**Issue by joseazevedo** [Megabit/Blazorise#2504]
Something like this:

async Task ShowModal()
    {
        var moviesModal = Modal.Show<Movies>("My Movies");
        var result = await moviesModal.Result;

        if (result.Cancelled)
        {
            Console.WriteLine("Modal was cancelled");
        }
        else
        {
            Console.WriteLine("Modal was closed");
        }
    }

**Comment by stsrki** [comment]
This is planned to be done in the next 0.9.4 preview. In fact, it is already working on our commercial applications and we just need to move it to public Blazorise. Just a copy/paste basically.

Closing now since it is already planned.
