### ISSUE TITLE
Consider renaming DataGridColumn.Direction to "SortDirection"

### ISSUE THREAD

**Issue by CaiusJard** [Megabit/Blazorise#2505]
While trying to set a grid so that a column was sorted by default I reasoned that the property would be on a column somewhere, but typing "Sort" in to see what intellisense would suggest brought only "Sortable" and "SortDirectionTemplate".

The property `Direction` is what I required, but I think it would be helpful to `[Obsolete]` this for a few releases and provide a mirrored property named `SortDirection` that does the same thing, before eventually removing `Direction` entirely. 

It would establish consistency of naming with the property type (`enum Blazorise.SortDirection`) and other how other properties are named (e.g. `public Blazorise.TextAlignment TextAlignment` uses a property named the same as the enum) and also related props like `SortDirectionTemplate`. It would also result in putting sorting related properties together in Intellisense

I realize it's a breaking change, but looks like a simple enough one that the Obsolete mechanism can easily handle it

**Comment by stsrki** [comment]
Seems like a good idea. I'm currently working on DataGrid API so it should not be a problem.

@David-Moreira Any thoughts?

**Comment by stsrki** [comment]
I have made a new parameter and marked old as Obsolete. Also in the release notes, I have added a migration to a new parameter, just in case.
