### ISSUE TITLE
Boostrap 5 Support

### ISSUE THREAD

**Issue by popcatalin81** [Megabit/Blazorise#2512]
Would be great to have support for Boostsrap 5

Bootstrap 5 has a series of advantages over Bootstrap 4 that makes it more suitable for Blazor and WebAssembly:

- Vanilla JavaScript instead of jQuery
- IE 10 and 11 support removed which greatly simplifies the framework code making it easier to maintain and more powerfull.
- Expanded color palette ($blue-100, $blue-200, $blue-300, etc)
- All new completely semantic, standard form controls with no need of adding extra markups for form controls and labels
... and many more [https://superdevresources.com/bootstrap5-vs-bootstrap4-whats-new/](https://superdevresources.com/bootstrap5-vs-bootstrap4-whats-new/)

**Comment by stsrki** [comment]
Yes, we already have plans for Bootstrap 5: #1103

I would say it will be for v0.9.5 or straight for v1.0 of Blazorise.

Closing now since we already have a tracking ticket.
