### ISSUE TITLE
Question : Tooltip customization

### ISSUE THREAD

**Issue by jerpic** [Megabit/Blazorise#2515]
Hello,

I have two questions about the Tooltip component.

1. Is there a way to customize its appearance like the font size, background color, color etc... ?
2. Currently, the Tooltip displays a text, is it possible to display HTML?

Best Regards,
Jérôme.

**Comment by stsrki** [comment]
It will be possible in v0.9.4. The new Tooltip will be backed by TippyJS and they have support for HTML content https://atomiks.github.io/tippyjs/#html-content

As for font and color options. Currently there is not much customization.

**Comment by jerpic** [comment]
Thanks for your answer, it's a good news!

Do you know when the v0.9.4 will be released?

Best Regards,
Jérôme.

**Comment by stsrki** [comment]
Probably middle of July.

**Comment by jerpic** [comment]
Ok Good, thanks!

**Comment by MartinC1** [comment]
Has there been any updates with being able to edit font size in the tooltip or is this not planned? 

Thanks,
Martin
