### ISSUE TITLE
datagrid column width

### ISSUE THREAD

**Issue by kwackerz** [Megabit/Blazorise#2545]
Hi,

I cannot get columns to change width. I set width="300px" on the column but they are all equal size.
I have  set responsive="true" on the grid as someone else mentioned, but it makes no difference.

Any ideas what i am doing wrong?

**Comment by David-Moreira** [comment]
Hello @kwackerz 
I just tried setting it on Blazorise v0.9.4 and it is working. You should set it using the DatagridColumn Parameter `Width`, with capital W : `Width="300px"`

If you're still having difficulties making it work, please let us know which version are you using. Also we can troubleshoot faster, if you provide a repository showcasing the problem.

![image](https://user-images.githubusercontent.com/22283161/124012067-9d4a7d00-d9d8-11eb-9aa8-f639bf1aa9dc.png)

![image](https://user-images.githubusercontent.com/22283161/124011993-873cbc80-d9d8-11eb-8e7f-ff4aa49e877d.png)

![image](https://user-images.githubusercontent.com/22283161/124012107-a89da880-d9d8-11eb-8b0b-f9b9b8d8be8f.png)

**Comment by kwackerz** [comment]
I have tried it again this morning and it works. I think maybe the reboot sorted it out.
Thanks!

**Comment by benny-adiwijaya** [comment]
Hi,

I cannot change width when there are a lot of columns. is there a way to solve this?

**Comment by benny-adiwijaya** [comment]
Hi @David-Moreira I already open new issue https://github.com/Megabit/Blazorise/issues/3604
