### ISSUE TITLE
DataGridMultiSelectColumn & Filtering Misbehavior

### ISSUE THREAD

**Issue by christophwille** [Megabit/Blazorise#2553]
I had my multi select column defined this way (you know, for good measure add everything to it):

`<DataGridMultiSelectColumn TItem="MyClass" Width="30px" Editable="false" Sortable="false" Filterable="false" />`

The column was followed by a simple column ("Name") that has sorting and filtering enabled, however, I got the following result:

![image](https://user-images.githubusercontent.com/344208/124121789-9c1b5d80-da75-11eb-8a0d-fd06eb94b79b.png)

The filter textboxes were shifted right by one column... once I removed all the extraneous props

`<DataGridMultiSelectColumn TItem="FileInfoShortened" Width="30px" />`

everything was back in place, ie the Name filter textbox in the Name column where it belonged.

**Comment by David-Moreira** [comment]
Hello @christophwille 
The DataGridMultiSelectColumn is a column that is to be used together with the DataGridSelectionMode.Multiple functionality. If you set your Datagrid to Multiple selection, the problem should be gone.
However there should not be an issue in maintaining Filterable set to true, as that column does not render any filter content by default, only the FilterContent if you have set it.
![image](https://user-images.githubusercontent.com/22283161/124174455-4d38ec80-daa4-11eb-8b80-93875139f675.png)

We will still take a look at this specific behaviour and fix it when possible.
