### ISSUE TITLE
Setting `Readonly` in `RichTextEdit`, now causes an exception to be raised

### ISSUE THREAD

**Issue by Smurf-IV** [Megabit/Blazorise#2554]
**Describe the bug**
As above

**To Reproduce**
Using the following code
``` c#
<RichTextEdit @ref="richTextEditRef"
ReadOnly="@readOnly"
ToolbarPosition="Placement.Left">
<Editor>
  <br /><br /><br /><br /><br />
  </Editor>
</RichTextEdit>
```
Raises the following exception stack
![image](https://user-images.githubusercontent.com/2418812/124141476-5c5a7300-da81-11eb-8cbb-09141d44bcc5.png)

**Expected behavior**
For it to work like it did before (`<PackageReference Include="Blazorise.RichTextEdit" Version="0.9.3.6" />`)

**Additional context**
.Net 5
IIS Hosted in Visual Studio
`<PackageReference Include="Blazorise.RichTextEdit" Version="0.9.3.9" />`

**Comment by stsrki** [comment]
I cannot reproduce it on my side. Did you tried clearing cache or hitting Ctrl+F5?

**Comment by Smurf-IV** [comment]
Just found this was closed (No idea why I did not get an update from your comment)
Yes I have been refreshing (A lot - its part of the development process ;-))
But for some reason today after a refresh it's fine..
Very strange.

Thanks for investigating

**Comment by stsrki** [comment]
It's one of those weird bugs that suddenly starts to work :)
