### ISSUE TITLE
v0.9.3.9 - DataGrid -  OnClearFilterCommand function does not clear partial dates of DataGridDateColumn with FilterTemplate containing DateTimeEdit component

### ISSUE THREAD

**Issue by sks-ttaylor** [Megabit/Blazorise#2556]
**Describe the bug**
DataGrid -  OnClearFilterCommand function does not clear partial dates of DataGridDateColumn with FilterTemplate containing DateEdit component

**To Reproduce**
Setup
DataGrid with ButtonRowTemplate containing a Button when clicked calls context.ClearFilterCommand.Clicked
a DataGridDateColumn with a FilterTemplate which contains a DateEdit component

Actions: 
Enter a partial date into the DateEdit component. ex: 06/21/yyyy
Click the ClearFilter button, 
All Columns Filter.SearchValue are set to null
However, the DateTimeEdit still displays a partial date.

**Expected behavior**
OnClearFilterCommand  sets the DateEdit component value to null

**Screenshots**
before and after ClearFilter button clicked
![image](https://user-images.githubusercontent.com/5667162/124160556-fd393600-da61-11eb-8a7b-e587b536af75.png)

**Comment by stsrki** [comment]
I don't think there is much we can do. Partial dates are controlled by the browser. Once it is fully written it will trigger the `onchange` event and Blazorise will receive the value. Until then, in terms of Blazorise, nothing exists.

**Comment by sks-ttaylor** [comment]
Thank you for clarifying this issue.

Do you think setting a dummy value (datetime.minvalue) then setting it back to null would clear the partial value?





On Jul 1, 2021 2:58 PM, Mladen Macanović ***@***.***> wrote:

I don't think there is much we can do. Partial dates are controlled by the browser. Once it is fully written it will trigger the onchange event and Blazorise will receive the value. Until then, in terms of Blazorise, nothing exists.

**Comment by stsrki** [comment]
In theory yes. But the problem is, Blazor(ise) works declaratively. Meaning, a value needs to go through the parameter. Then the component would need to rerender, to activate internal logic. Then to clear it, it would need to repeat the same. It would be a really dirty hack.
