### ISSUE TITLE
Dropdown menu goes behind div content : Bulma

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#2564]
Dropdown menu goes behind div content : Bulma 
Noticed this while testing the new auto complete features. Possibly z-index or some other css adjustment.
![image](https://user-images.githubusercontent.com/22283161/124332936-b2ffa400-db8a-11eb-9ed5-aafa8b2eec53.png)

**Comment by stsrki** [comment]
Yeah, I noticed the same but was never able to fix it.
