### ISSUE TITLE
dropdown.Open(); is unsupported

### ISSUE THREAD

**Issue by tacoWanneeJama** [Megabit/Blazorise#2579]
**Describe the bug**
The example of the Dropdown is not compiling

**To Reproduce**
1. Go to: https://blazorise.com/docs/components/dropdown/
2. Take the example below "Usage"
3. Copy to your Blozise project
4. See error for row: dropdown.Open();

**Expected behavior**
It should compile

**Screenshots**
![image](https://user-images.githubusercontent.com/76042577/124553081-971f2b00-de34-11eb-8da8-bee2dcb91ed5.png)

**Additional context**

**Comment by tacoWanneeJama** [comment]
I am using the newest Blazorise and addons

**Comment by David-Moreira** [comment]
Saying this from memory but Try using Show instead of Open. 
We'll take a look if the docs are wrong.

**Comment by tacoWanneeJama** [comment]
That was the correct syntax. Thanks

**Comment by tacoWanneeJama** [comment]
Shall we close this issue? Or do you keep it as reminder to update the manual?

**Comment by David-Moreira** [comment]
Leave it open as a reminder, please.
Thanks.

**Comment by stsrki** [comment]
We will update documentation for the coming release. Thanks for letting us know!
