### ISSUE TITLE
How to show the color picker in RichTextEdit?

### ISSUE THREAD

**Issue by juchunwei** [Megabit/Blazorise#2604]
Hi, 
I couldn't figure out how to show the color picker, I added this code, it shows the color button but nothing happen when click it.
how to use it?
Thanks!

` <RichTextEditToolbarButton Action="RichTextEditAction.Color" ></RichTextEditToolbarButton>`

**Comment by stsrki** [comment]
@njannink any chance you might give feedback about this?

**Comment by njannink** [comment]
@juchunwei  As you can see in the examples for the color picker you need a different kind of button:

`<RichTextEditToolbarSelect Action="RichTextEditAction.Color" />`

![image](https://user-images.githubusercontent.com/3843546/125096263-9982be80-e09a-11eb-8792-bad4779d118c.png)

**Comment by juchunwei** [comment]
@njannink 
Thank you!
