### ISSUE TITLE
Chart colors only visible on hover

### ISSUE THREAD

**Issue by paiden** [Megabit/Blazorise#2611]
Run the following code sample with Blazorise (Charts) v0.9.3.9

```razor
<BarChart TItem=@double @ref=@this.chart />
@code {
    private BarChart<double> chart = null!;

    protected override Task OnAfterRenderAsync(bool firstRender)
    {
        if(firstRender)
        {
            var labels = Enumerable.Range(1, 10).Select(x => $"L{x}").ToList();

             var data = new BarChartDataset<double>()
             {
                 Label = "Test Data",
                 Data = Enumerable.Range(1, 10).Select(x => (double)x).ToList(),
                 BackgroundColor = new ChartColor(255, 0, 0),
             };

            chart.AddLabelsDatasetsAndUpdate(labels, data);
        }

        return base.OnAfterRenderAsync(firstRender);
    }
}
```

This will produce a chart that only has a color when hovered over. The following image shows the inital chart when the cursor is outside the chart on the left. The right shows the chart when the mouse is near the center of the chart: 

![image](https://user-images.githubusercontent.com/7665273/124970445-33f5ea00-e028-11eb-8bed-bfa136a2b5b3.png)

To get the behavior I would expect I have to change the code line

```razor 
BackgroundColor = new ChartColor(255, 0, 0),
```
to 
```razor
BackgroundColor = (string)new ChartColor(255, 0, 0)
```
With this, the chart bars have correct background color. Here is the screen, with the cursor outside the chart area after this code change.

![image](https://user-images.githubusercontent.com/7665273/124971564-a3b8a480-e029-11eb-8ef5-7aa13c22cf38.png)

Probably the BackgroundColor of `ChartDataSet<T>` should be a `IndexableOption<string>` and not a `IndexableOption<object>`?

**Comment by stsrki** [comment]
Yes, with the first example, we don't have information on how to properly serialize the ChartColor. When you cast it into `(string)` it will convert the value into JS function as a string, eg `rgba(255,0,0,0)` and it will properly be sent to the chart vis JSInterop.

This also works, see `.ToJsRgba()`

```diff
<BarChart TItem=@double @ref=@this.chart />
@code {
    private BarChart<double> chart = null!;

    protected override Task OnAfterRenderAsync( bool firstRender )
    {
        if ( firstRender )
        {
            var labels = Enumerable.Range( 1, 10 ).Select( x => $"L{x}" ).ToList();

            var data = new BarChartDataset<double>()
            {
                Label = "Test Data",
                Data = Enumerable.Range( 1, 10 ).Select( x => (double)x ).ToList(),
+                BackgroundColor = new ChartColor( 255, 0, 0 ).ToJsRgba(),
            };

            chart.AddLabelsDatasetsAndUpdate( labels, data );
        }

        return base.OnAfterRenderAsync( firstRender );
    }
}
```

**Comment by paiden** [comment]
My question here is, would changing the BackgroundColor type to `IndexableOption<string>` help at preventing this error?

Is there any reason whey it is an IndexableOption<object>?

Once you know what the error is, it is easy to fix, but it took me a few hours to find out what is going on. Maybe with the help of the type system this can be prevented?

**Comment by stsrki** [comment]
Changing BackgroundColor type to `IndexableOption<string>` would mean you would have `IndexableOption` inside of `IndexableOption`. It would not work. If you try it you will see an error.

The purpose of `IndexableOption` is to be able to have a single value, OR an array of values. ChartJS works like that and this was the way to support it.
