### ISSUE TITLE
DataGrid Sort API

### ISSUE THREAD

**Issue by redbird19** [Megabit/Blazorise#2612]
I've looked through the source code but don't see any way to retrieve the current sort column/direction for a datagrid.  Can someone point me in the right direction?

What'd I'm looking to do is fairly straightforward, display a list of items in a DataGrid that's pageable, sortable, etc. Then the user clicks an item and is navigated to a separate page to view the item details.  Then the user clicks a "Save" or "Back" button and is returned back to the same list, which has maintained the sort and page they were on.  Simple right?

I planned on embedding/storing the sort and page information in the querystring of the url that links to the item detail page.  Then in the item detail page, I'd embed that same information in the return url used to back to the list page, which would use those variables to initialize the datagrid to the appropriate state.

I see there are events which I can hook into for PageChanged, and PageSizeChanged to capture the page information, but there's no event for "SortChanged"....am I missing something?

**Comment by David-Moreira** [comment]
Hello @redbird19 
For grabbing the current Sort Direction configuration out of the columns.
This field should be available. However you will have to inherit from Datagrid, so you can have access to the internals and do your own logic to grab this.
![image](https://user-images.githubusercontent.com/22283161/124999079-5cd8a800-e045-11eb-9134-2a67dd1e8250.png)

As for restoring the sort information. I'm not sure there is an easy way. Maybe you could do something like this?
![image](https://user-images.githubusercontent.com/22283161/124999415-fd2ecc80-e045-11eb-9407-8c98878785fd.png)

**Comment by David-Moreira** [comment]
On a side note, `SortChanged` event seems like a nice suggestion/addition, what do you think @stsrki ?

**Comment by David-Moreira** [comment]
Also we will expose a couple of APIs as public in the next release of Blazorise.
And one of them is `Sort`, which could be interesting for your case, as long as you can grab the column reference that you'd like to sort. (Should easily be able to, by accessing the datagrid's internal columns by inheriting)
![image](https://user-images.githubusercontent.com/22283161/124999800-da50e800-e046-11eb-9174-9c432ef9128d.png)

@stsrki what about having a more generic Sort API, that let's you sort by field name? THis should be feasible right? The one we're currently releasing in 0.9.4 is a bit tied to having to grab the column reference. Also, could be interesting to straight up set the desired direction, possible as an overload or optional argument? What do you think?

**Comment by redbird19** [comment]
Thanks for the quick reply @David-Moreira 

I attempted to inherit from DataGrid as you suggested, and am able to get the sorted columns, but not the sort direction (the "CurrentDirection" property in DataGridColumn is an internal property so I don't have access to it).  Even if I did though, I'd still need a way to set the initial sort of the grid, sort of like we are able to set the initial page of the grid via the "CurrentPage" property.

**Comment by David-Moreira** [comment]
> Thanks for the quick reply @David-Moreira
> 
> I attempted to inherit from DataGrid as you suggested, and am able to get the sorted columns, but not the sort direction (the "CurrentDirection" property in DataGridColumn is an internal property so I don't have access to it). Even if I did though, I'd still need a way to set the initial sort of the grid, sort of like we are able to set the initial page of the grid via the "CurrentPage" property.

Oh I didn't notice `CurrentDirection` wasn't exposed, @stsrki could we give the info to the user? `GetCurrentSortDirection` or something?

@redbird19 did you try something like this? Setting the `SortDirection` on the `DataGridColumn` should work, since the column, while initializating takes in the parameter `SortDirection` as the initial Sort Direction.

"As for restoring the sort information. I'm not sure there is an easy way. Maybe you could do something like this?
image"
![image](https://user-images.githubusercontent.com/22283161/124999415-fd2ecc80-e045-11eb-9407-8c98878785fd.png)
**PS:** Might still be called just `Direction` on version 0.9.3

**Comment by stsrki** [comment]
Done the first version in #2613

I believe the `SortChanged` event would be enough. I have also exposed CurrentSortDirection getter in case someone likes it that way.

**Comment by redbird19** [comment]
Wow, that was a quick turnaround guys, awesome work!

**Comment by stsrki** [comment]
:) we got to be fast since new release is coming soon.
