### ISSUE TITLE
Documentation mismatch

### ISSUE THREAD

**Issue by Luk164** [Megabit/Blazorise#2617]
**Describe the bug**
There is a mismatch between two parts of documentation regarding material css and js library.  This could be confusing for new users during first time installation.

The http://materialdemo.blazorise.com/ points to http://daemonite.github.io/material/

While https://blazorise.com/docs/usage/material/ points to a newer https://djibe.github.io/material/

I am going to post a PR which changes the deamonite to djibe.

**Additional context**

**Comment by stsrki** [comment]
Can you do it on dev094? We're soon to make a release anyways.

**Comment by Luk164** [comment]
@stsrki Done

**Comment by Luk164** [comment]
@stsrki I really just replaced the link so hopefully nothing will break.
