### ISSUE TITLE
Ambiguities in the description of the plans on https://commercial.blazorise.com/

### ISSUE THREAD

**Issue by iwis** [Megabit/Blazorise#2619]
1. On the https://commercial.blazorise.com/ page in the "Compare plans" section it isn't clear for me what the "Public" and "Private" rows mean. And why is public allowed and private isn't in the Community plan?

2. On the https://commercial.blazorise.com/community page:

 > Any individual developer can use Blazorise Community to create their own free apps.

Can I also create apps that will be paid i.e. my users will pay to use them? Maybe better write: "_Any individual developer can use Blazorise Community to create their own apps for free._"

 > can use Blazorise Community in a Non-Commercial Manner way

Isn't the "way" word superfluous?

**Disclaimer**: I don't speak English fluently so maybe some of my proposals are not valid.

**Comment by stsrki** [comment]
Thanks for the message. We plan to make licensing details more clear and easier to understand. But the general idea is:

- Blazorise is free for all individuals be it for commercial, freelancing, private or public use
- Blazorise is also free for all companies that have less than five or fewer employees
- Blazorise is NOT free for all other companies that have over five employees, OR have over $1M in annual revenue

---

- Public means selling your own software to clients, or third-party users
- Private means use for personal projects, or in-house projects

---

Now I'm not a lawyer so I will try to express myself as clear as possible in the actual license file and on the commercial web.

**Comment by stsrki** [comment]
I have fixed some problems on the commercial web and made FAQ more clear.

**Comment by iwis** [comment]
The bolded parts written in capital letters don't result from [the license](https://commercial.blazorise.com/files/licences/SLA-2021-06.pdf). 

> Thanks for the message. We plan to make licensing details more clear and easier to understand. But the general idea is:
> 
> * Blazorise is free for all individuals be it for **COMMERCIAL**, freelancing, private or public use
> * Blazorise is also free for all companies that **HAVE LESS THAN FIVE OR FEWER EMPLOYEES**
> * Blazorise is not free for all other companies that have over five employees, or have over $1M in annual revenue
> 
> * Public means selling your own software to clients, or third-party users
> * Private means use for personal projects, or in-house projects
> 
> Now I'm not a lawyer so I will try to express myself as clear as possible in the actual license file and on the commercial web.

Why is it important to clarify this? On [Reddit](https://www.reddit.com/r/Blazor/comments/o7wp88/recommendation_for_open_source_free_razor/) somebody said: "_Also if you're using Blazorise in a commercial way then you have to go to the paid tier._" I would like to answer there that individuals and small businesses can use Blazorise commercially for free. However, I cannot write it now, because it doesn't result from the license. The license says something else.

**Comment by stsrki** [comment]
Hi, sorry for the confusion. Our lawyer, the guy who written the SLA, is still on the vacation until the end of the week so we're still waiting for the actual license to be updated based on the points we have written on the commercial page. The updated version should be up by sometime next week.
