### ISSUE TITLE
Is the license going to change?

### ISSUE THREAD

**Issue by Luk164** [Megabit/Blazorise#2620]
I just noticed the new site https://commercial.blazorise.com/. Are you going to change the license from Apache 2.0? Because I have used this in almost every Blazor project of mine and if so I am going to have to be careful not to update to a paid license by accident.

**Comment by stsrki** [comment]
Hi, Blazorise license will stay as Apache 2.0. We changed it recently from MIT. If you didn't please read our pots why we go this way and are the plans for the future: https://blazorise.com/news/changes-to-blazorise-license/

Also, look at #2619 for quick info until we fix the licensing details on the web.

**Comment by Luk164** [comment]
@stsrki Ok, the under 1million$ clause seems more than fair, and would make me and my projects exempt. Thank you and I hope I will be able to keep contributing.

**Comment by stsrki** [comment]
I wanted to be able to give back to the community as much as I can while keeping it fair. That's why I only wanted to charge larger companies.

**Comment by Luk164** [comment]
> 
> 
> I wanted to be able to give back to the community as much as I can while keeping it fair. That's why I only wanted to charge larger companies.

@stsrki  Yeah that is much better than what SyncFusion does, as they limit it on the amount of developers in the company, which does not account for different wages and revenues.

**Comment by stsrki** [comment]
We all know I cannot compete with full-blown companies like SF, or DevEx. I was working alone so far, mostly in my free time. Recently I able to hire @David-Moreira part-time so it is already a lot easier. The plan is to get more developers on board, but since the budget is limited we first need to get enough paid licenses. It is not easy.

**Comment by Luk164** [comment]
@stsrki Well good luck, maybe this is a start of something big. The library itself is already fairly popular, so I believe there is a lot of potential.

**Comment by stsrki** [comment]
Thanks!

**Comment by Luk164** [comment]
> Thanks!

Hell if I wasn't already over my head in uni/work I would be sending you a CV right now :)

**Comment by stsrki** [comment]
One day maybe 😉
