### ISSUE TITLE
Steps navigation

### ISSUE THREAD

**Issue by kofinn** [Megabit/Blazorise#2624]
Hi,

Is it possible to add new parameter, that will make navigation in Steps component unclickable (navigation should be still present, but it should not be used to switch between different steps)

![image](https://user-images.githubusercontent.com/22171329/125177794-0901c680-e1df-11eb-857f-a139f0a720fe.png)

Thank you

**Comment by David-Moreira** [comment]
Hello @kofinn 
I don't think you can, no.
For feature proposal, let me know if this is what you'd like:
1     - Disable Step click navigation
2     - Programmatically select the step that you'd like to navigate to. **(Already possible with `SelectStep`)**
2.1 - `NextStep` and `PreviousStep` API could be usefull, right?

**Comment by kofinn** [comment]
Hi,



> Hello @kofinn
> I don't think you can, no.
> For feature proposal, let me know if this is what you'd like:
> 1 - Disable Step click navigation
> 2 - Programmatically select the step that you'd like to navigate to. **(Already possible with `SelectStep`)**
> 2.1 - `NextStep` and `PreviousStep` API could be usefull, right?

**Comment by kofinn** [comment]
Hi,

ok, currently I have workaround using SelectedStepChanged and SelectStep.

Maybe with these changes it could be new component 

Here is pretty much what I wish to do.
https://bbbootstrap.com/snippets/multi-step-form-wizard-animated-progressbar-53000683

**Comment by David-Moreira** [comment]
Don't think we need a new component. Just a way to disable the click on the steps themselves. And Next Step / Previous Step apis which you can then bind to the buttons as you wish obtaining the same result as in the demo you just sent. 

Feature proposal for us to consider.

**Comment by Jimmys20** [comment]
Hi @stsrki, @David-Moreira, I'm thinking of giving this a try. I have 2 questions:

When there is not any step selected, should the `NextStep` method go the first step or do nothing?
How to approach disabling the click? Add `DisableClickNavigation` parameter to the `Steps` component.
