### ISSUE TITLE
Tooltip text is not updated on @bind-Text

### ISSUE THREAD

**Issue by dkonstantinov193** [Megabit/Blazorise#2629]
**Is your feature request related to a problem? Please describe.**
I'm trying to dynamically update tooltip's text from a variable, but can't get it work - the text stays the same as it was on the first render.

I'm using the following code:
`<Tooltip Fade="true" 
               @bind-Text="@_tooltipText"
               Placement="TooltipPlacement.Right"
               Multiline="true"
               AlwaysActive="false">
           <Icon Name="IconName.QuestionCircle" Style="color:#969392" />
</Tooltip>`

**Describe the solution you'd like**
Would be good if tooltip text would be bindable. Should we add changing event to the component like below to get it work?
`[Parameter] public EventCallback<string> TextChanged { get; set; }`

### Additional context
Environment:
VS 16.11.0 preview 2.0
.Net 6 preview 5
Blazorise 0.9.4-preview5

**Comment by stsrki** [comment]
Current Tooltip only sets the Text on initializing. I didn't anticipate it to be set afterward. It makes sense to have that feature. I will try to implement it for next release.

No need for TextChanged. That would mean Text could change from Tooltip and I don't see a reason for that behavior.

**Comment by dkonstantinov193** [comment]
Great! My current workaround is to create different tooltips and manage them via some IFs but that leads to a lot of code duplicate inside visual part.
