### ISSUE TITLE
Drag and drop functionality

### ISSUE THREAD

**Issue by uzochiapa** [Megabit/Blazorise#2633]
Hi,

It would be nice to have a drag and drop functionality. So developers can easily build interactive functionality for websites.

**Comment by David-Moreira** [comment]
Hello,
So, you'd like some kind of Blazorise tool, where you can drag and drop components and maybe even configure their properties, and then it would generate the corresponding code for you, is this it?
That's a very very huge development cost which I'm not sure we are ready to take on anytime soon, right @stsrki ? 

But we can always save the idea for the future, thank you for your feedback @uzochiapa!

**Comment by David-Moreira** [comment]
Oh...I think I might have missunderstood.

Or would you rather...
For the majority of the Blazorise components, where applicable, have Drag and Drop functionality where:
1- You can set the component to be draggable.
2- You need some kind of container(s), or compatible component(s) to be able to drop them onto

Is this it instead?
Again, thank you for your suggestion/feedback, and please let us know if this is it instead @uzochiapa

**Comment by stsrki** [comment]
I'm also not sure exactly. @uzochiapa can you give us more context what you expect?

---

What I understood and what I did in the past is to have `Draggable` and `Dropzone` components. `Dropzone` is a main container or area where you drop `Draggable`'s. And `Draggable` is a wrapper that you move around and that can contain any component or HTML element.

**Comment by David-Moreira** [comment]
Well even if @uzochiapa  does not get back to us, we could consider the Draggable and Dropzone components feature @stsrki?
Seems like a nice one to have.
