### ISSUE TITLE
DateEdit - workweek in visual

### ISSUE THREAD

**Issue by solvix** [Megabit/Blazorise#2636]
Hi team -
Thanks for all your wonderful contributions to date.  I wanted to see if you had planned to add a workweek to your date picker, something like this one made available in Jira.

![image](https://user-images.githubusercontent.com/4146979/125688380-1612a7e7-3166-42c5-8ce5-616db3f46564.png)

thanks again,
Brent

**Comment by stsrki** [comment]
Not sure if I understand correctly. Did you mean to have a weekend days in red colors?

**Comment by stsrki** [comment]
Hi @solvix can you please provide mora information about the feature you need? Thanks
