### ISSUE TITLE
DataGridDateColumn contains time (minimum to seconds)

### ISSUE THREAD

**Issue by bestpika** [Megabit/Blazorise#2654]
**Is your feature request related to a problem? Please describe.**

I want to be able to modify the date and time directly in the column, but the DataGridDateColumn can only modify the date but not the time.

**Describe the solution you'd like**

Hopefully, you can add a parameter that specifies whether the field is a date or time, or DateTime.

### Additional context

I used to do it this way, but it's a pain in the ass to have to do it again every time, so I hope it can be a built-in feature.

```html
<DataGridDateColumn TItem="..." Field="@nameof(...)" Editable="true">
    <EditTemplate>
        <DateEdit TValue="DateTime?" InputMode="DateInputMode.DateTime"
                  Date="@Convert.ToDateTime(context.CellValue)"
                  DateChanged="@(v => context.CellValue = Convert.ToDateTime(v))" />
    </EditTemplate>
</DataGridDateColumn>
```

In addition, there is a more serious problem is that the input box in the case of the date and time is really too narrow.

![image](https://user-images.githubusercontent.com/5698157/126138485-4a063f02-c4fc-4064-8c40-bb62045e3625.png)

**Comment by stsrki** [comment]
Done. You got it just in time before the release :)
