### ISSUE TITLE
Tweak the UI of Message service?

### ISSUE THREAD

**Issue by nightroman** [Megabit/Blazorise#2669]
The new message service is cool and useful. But the UI is rather strange (well, my opinion). It looks more focused on the icon than the message text.

![image](https://user-images.githubusercontent.com/927533/126299546-c5e07205-b8a1-4245-b9b0-02801d10df38.png)

If this is by design and not configurable I would rather have no icon at all.
Is this possible?

**Comment by stsrki** [comment]
You can disable icon with `options` param, eg

`MessageService.Info( "This is a simple info message!", "Hello", options => options.ShowMessageIcon = false );`

**Comment by nightroman** [comment]
This works, thank you.

Yet I'd be happy if the UI were more focused on the text.

Minor issue 2. I cannot find a way to close the dialog using keys. And it is not closed by clicking outside the dialog. Is this all by design?

**Comment by stsrki** [comment]
Yes, it is by design. The idea was to force the user to actually click on a modal action instead of accidentally closing it with escape key. We can consider adding another parameter to change that behavior or making it customizable.

**Comment by nightroman** [comment]
Thank you, it's all done then, closing.

**Comment by ponchautf** [comment]
Hi,
To continue in this subject, will it be possible to have some more options to customize the modal?
I think on:
 - showing the X close button (as on classic modal)
 - set the css class for buttons. we can set text but it would be great if we can also remplace the default css class.
