### ISSUE TITLE
DataGrid fails to update when items are added/deleted

### ISSUE THREAD

**Issue by mtbayley** [Megabit/Blazorise#2675]
**Describe the bug**
When an item is added/deleted via code triggered by a button, it does not update in the DataGrid.
Note: you can manually trigger a DataGrid to refresh by sorting any column

**To Reproduce**
1. Clone this test repo: [https://github.com/mtbayley/BlazoriseJSExceptionTest](https://github.com/mtbayley/BlazoriseJSExceptionTest)
2. Run, go to /fetchdata
3. Click add item
4. Default table will add item. Blazorise DataGrid below does not update.
5. Change to version 0.9.3.10
6. Do same steps. DataGrid will add/ delete items.

![image](https://user-images.githubusercontent.com/34929316/126374508-7f2cdcd2-f37f-433b-a544-71b1571e7bca.png)

**Comment by David-Moreira** [comment]
Thanks for taking the time to set up a repository reproducing the bug. We'll get back to you asap.
