### ISSUE TITLE
tootlip js exception in 0.9.4

### ISSUE THREAD

**Issue by naefp** [Megabit/Blazorise#2678]
**Describe the bug**
After updating Blazorise from `0.9.4-preview6` to `0.9.4` we are getting the following exception, but beside the exception everything seems to work fine. As I can see, all tooltips are working as expected.

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read property 'querySelector' of null
      TypeError: Cannot read property 'querySelector' of null
          at Object.initialize (https://localhost:5011/_content/Blazorise.Bootstrap/blazorise.bootstrap.js:10:25)
          at https://localhost:5011/_framework/blazor.webassembly.js:1:2669
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:5011/_framework/blazor.webassembly.js:1:2643)
          at Object.ut [as invokeJSFromDotNet] (https://localhost:5011/_framework/blazor.webassembly.js:1:52772)
          at _mono_wasm_invoke_js_blazor (https://localhost:5011/_framework/dotnet.6.0.0-preview.6.21352.12.js:1:207806)
          at <anonymous>:wasm-function[2461]:0x78fb6
          at <anonymous>:wasm-function[2187]:0x6130b
          at <anonymous>:wasm-function[6671]:0x15d556
          at <anonymous>:wasm-function[6495]:0x154eb0

**To Reproduce**
Not sure which use case causes the exception. still trying to find out, and hoping you have an idea... 😄

**Comment by stsrki** [comment]
Did you clear the cache? This usually happens with every new version. Try Ctrl+F5.

If that doesn't help we'll look into it.

**Comment by naefp** [comment]
yes I did, doesn't help.

**Comment by stsrki** [comment]
Does it tell you on what line is error happening?

**Comment by naefp** [comment]
No, unfortunately I can't see where it happens. Just from the exception information and the by looking into bootstrap.js, it seems to be something with the Tooltips. But we have a lot of tooltips in several components and they are working well. Until now, I don't have any idea where to take a closer look.

**Comment by naefp** [comment]
Ok, I just found the component and the 2 tooltips, which are causing the exception. When I comment out these, I don't have no more exceptions. Are we doing something bad here? (At least, these lines worked without exception until 0.9.4-preview6)

```html
<Card Margin="Margin.Is3.FromTop">
  <CardBody>
      <CardTitle>@LanguageContainer.Keys["Dashboard:WorkOpen"]</CardTitle>
      <Fields ColumnSize="ColumnSize.IsFull" Margin="Margin.Is0" Padding="Padding.Is0">
          @if (AclAuthorization.Invoke(GeneralActions.ShowWorkListInvoicesToSend)
               && AclAuthorization.Invoke(InvoiceActions.GenerateInvoicePdf))
          {
              <Field ColumnSize="ColumnSize.IsFull" Margin="Margin.Is0">
                  <Tooltip Text="@LanguageContainer.Keys["Dashboard:OpenWorkList"]">
                      <Button Color="Color.Dark"
                              Disabled="@(_dashboardStats.OpenInvoicesToSend is null or 0)"
                              Clicked="@(() => OpenTab.Invoke(TabFactory.InvoicesToSend, null))">
                          <i class="fas fa-clipboard-list" style="margin-right: 8px;"></i>
                          @_dashboardStats.OpenInvoicesToSend.ToString()
                      </Button>
                  </Tooltip>
                  <Label>@LanguageContainer.Keys["Dashboard:OpenInvoicesToSend"]</Label>
              </Field>
          }
          @if (AclAuthorization.Invoke(GeneralActions.ShowWorkListCustomersOverDue)
               && AclAuthorization.Invoke(InvoiceActions.IncreaseReminderStep))
          {
              <Field ColumnSize="ColumnSize.IsFull" Margin="Margin.Is0.Is2.FromTop">
                  <Tooltip Text="@LanguageContainer.Keys["Dashboard:OpenWorkList"]">
                      <Button Color="Color.Dark"
                              Disabled="@(_dashboardStats.OpenCustomersOverDue is null or 0)"
                              Clicked="@(() => OpenTab.Invoke(TabFactory.CustomersOverDue, null))">
                          <i class="fas fa-clipboard-list" style="margin-right: 8px;"></i>
                          @_dashboardStats.OpenCustomersOverDue.ToString()
                      </Button>
                  </Tooltip>
                  <Label>@LanguageContainer.Keys["Dashboard:OpenCustomersOverDue"]</Label>
              </Field>
          }
      </Fields>
  </CardBody>
</Card>
```

**Comment by naefp** [comment]
@stsrki any idea what could be wrong here?

**Comment by stsrki** [comment]
Not a slight idea unfortunately. Without being able to reproduce it it's really hard to tell.

What browser you have?

**Comment by naefp** [comment]
OK. we have implemented a work around in our project, and everything is working fine:

```js
window.blazoriseBootstrap = {
    tooltip: {
        initialize: (element, elementId, options) => {
            window.blazorise.tooltip.initialize(element, elementId, options);
            
            if (!element) {
                return;
            }

            if (element.querySelector(".custom-control-input,.btn")) {
                element.classList.add("b-tooltip-inline");
            }
        }
    },
```

**Comment by stsrki** [comment]
So you only did a null check on an element? That is a good approach and I should add it to the codebase also. But, the bigger question is why is it null in the first place 🤔

**Comment by stsrki** [comment]
An `element` is sent through `window.blazorise.tooltip.initialize`, where it is used to create a tooltip instance. So if it is null at that point, it should raise an error. But it doesn't. Only when accessed with `element.querySelector` the error happens. It doesn't make sense...

Could it be that Tooltip is somehow created and disposed fast somewhere in your app?

**Comment by naefp** [comment]
That's a good point - this is indeed possible! I will come back to that tomorrow...

**Comment by naefp** [comment]
OK, your right!

Here's what we did on several "refreshable" components for one year now:
```C#
private bool _isLoading;
```

```C#
protected override async Task OnAfterRenderAsync(bool firstRender)
{
    if (firstRender)
    {
        await LoadData();
        //...
    }
    
    await base.OnAfterRenderAsync(firstRender);
}
```

```C#
public async Task LoadData()
{
    _isLoading = true;
    StateHasChanged();

   // ... load some data

    _isLoading = false;
    StateHasChanged();
}
```

```html
@if (_isLoading)
{
    <SpinKitWave/>
}
else
{
    @*......*@
    <Card Margin="Margin.Is3.FromTop">
        @*......*@
        <Tooltip Text="...">
            @*......*@
        </Tooltip>
    </Card>
}
```

### What happened
With updating to .net6 and finally to Blazorise 0.9.4 as well, this became "too fast" and the null exception ton the tooltip element was thrown on one of our components.

### Solution
To fix that I only had to set our "_isLoading" initially to true.
```C#
private bool _isLoading = true;
```

Thank you for your time and the very helpful hint. I can't tell, if the double check on null in the blazorise.bootstrap.js is needed or if it make sense anyway. I removed our override and will now go back to using the default file.

**Comment by stsrki** [comment]
It was a long shot but I guessed it right this time :)

In any case, it's good we were finally able to solve it. Just in case I will also add a null check in Blazorise.
