### ISSUE TITLE
The input area of DataGrid popup mode is too narrow

### ISSUE THREAD

**Issue by bestpika** [Megabit/Blazorise#2683]
**Describe the bug**

The input area of DataGrid popup mode is too narrow, so some long input boxes cannot be displayed completely.

**To Reproduce**

`EditMode="DataGridEditMode.Popup"`

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/5698157/126423143-e5b86e8c-b881-444d-9e44-13fe4a500abf.png)

**Additional context**

**Comment by stsrki** [comment]
There is not much we can do. You can increase the column size in edit mode, eg.

```cshtml
<DataGridDateColumn PopupFieldColumnSize="ColumnSize.Is12" TItem="Employee"
```

**Comment by bestpika** [comment]
I found where there is a problem, some parameters in the wrong place, no wonder I automatically ignore the description.
For example, PopupSize is placed inside the DataGridColumn ......

**Comment by stsrki** [comment]
You're right. It is fixed now. Thanks!

**Comment by stsrki** [comment]
You're right. It is fixed now. Thanks!

**Comment by stsrki** [comment]
You're right. It is fixed now. Thanks!
