### ISSUE TITLE
datgrid - documentation - events edit popup

### ISSUE THREAD

**Issue by drma-dev** [Megabit/Blazorise#2685]
is there somewhere I can find documentation on how the RowInserting and RowInserted events work?

I can't get these events to be called and the popup isn't even closing when I click save.

```
<DataGrid @ref="DataGrid" TItem="ProviderBase" Data="@ListData" Filterable="true" Editable="true" EditMode="DataGridEditMode.Popup" 
    ShowPager="true" PageSize="10" FilterMethod="DataGridFilterMethod.Contains"
    RowInserting="RowInserting" RowInserted="RowInserted" >
    ...
</DataGrid>
```
```
protected async Task RowInserting(CancellableRowChange<ProviderBase, Dictionary<string, object>> e)
    {
        var obj_new = e.Item;
        var obj_old = ListData.First(f => f.provider_id == obj_new.provider_id);

        obj_old = obj_new;
    }

    protected async Task RowInserted(SavedRowItem<ProviderBase, Dictionary<string, object>> e)
    {
        var obj_new = e.Item;
        var obj_old = ListData.First(f => f.provider_id == obj_new.provider_id);

        obj_old = obj_new;
    }
```

**Comment by stsrki** [comment]
You can see an example in our demo app but it is not much different from what you already have. And I cannot see what is wrong with your code. Except that you have `async` but  don't have an `await`.

Try:

```cs
protected Task RowInserting(CancellableRowChange<ProviderBase, Dictionary<string, object>> e)
    {
        var obj_new = e.Item;
        var obj_old = ListData.First(f => f.provider_id == obj_new.provider_id);

        obj_old = obj_new;

        return Task.CompletedTask;
    }

    protected Task RowInserted(SavedRowItem<ProviderBase, Dictionary<string, object>> e)
    {
        var obj_new = e.Item;
        var obj_old = ListData.First(f => f.provider_id == obj_new.provider_id);

        obj_old = obj_new;

        return Task.CompletedTask;
    }
```

Also, can you tell us what type is `ListData`?

**Comment by David-Moreira** [comment]
Hello @drma-dev
Your methods do seem valid from a binding and method contract perspective. And In addition to @stsrki  suggestions. 

Could you take a look at your console? If you're letting us know that the popup isn't closing when you save, and there does not seem to be any validation set up... so it might be that the app is crashing and you might have not noticed? 

This line here might be throwing an exception. Both the methods you're showing are used in the `New` operation.
If the Item is new... the item `provider_id` might be 0 or not exist on the list? 
`var obj_old = ListData.First(f => f.provider_id == obj_new.provider_id);`

This seems like code you might've wanted to use on the `Edit` operation... with the `RowUpdated` and `RowUpdating`?

Let us know if this helps...
Also if for some reason that's not the problem and you can take the time to set up a repository reproducing your problem, we'll be happy to take a look at it and help you.

**Comment by drma-dev** [comment]
@David-Moreira yeah, you were right. my intention was to call the update, not the insert. my mistake.
