### ISSUE TITLE
Border not working on Material design

### ISSUE THREAD

**Issue by Luk164** [Megabit/Blazorise#2689]
**Describe the bug**
Border, as described in https://blazorise.com/docs/helpers/utilities/ is not working for me.

**To Reproduce**
1. Create a new project
2. Install blazorise with material
3. Add spans from aforementioned part of docs

**Expected behavior**
Borders are created as expected

Sample code:

```
<Span Border="Border.Rounded">Rounded</Span>

<Span Border="Border.Is1">Border on all sides</Span>

<Span Border="Border.Primary">Borders with primary color</Span>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/30559213/126482766-588039a6-777f-40d4-ba54-ed0af4a6aa40.png)

**Additional context**
I think there is some CSS missing. In the demo it works but most of the CSS comes from demo.css file, which is obviously not present in my solution.

**Comment by stsrki** [comment]
It's working. It's just that you don't have any styles on the span elements. In the demo, I have added some default styles so that they can be seen and you should also make it for your own project.

**Comment by Luk164** [comment]
@stsrki Oh ok, I thought it was supposed to be built-in like all the other stuff. Maybe consider mentioning that in the docs?

**Comment by stsrki** [comment]
Done!
