### ISSUE TITLE
Switch sizes in material demo broken

### ISSUE THREAD

**Issue by Luk164** [Megabit/Blazorise#2691]
**Describe the bug**
I just noticed the switches in Switch Sizes card at https://materialdemo.blazorise.com/tests/misc-forms are a bit broken.

**To Reproduce**
1. Go to https://materialdemo.blazorise.com/tests/misc-forms
2. See error

**Expected behavior**
A bigger switch is displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/30559213/126487518-62615cd8-fc7c-4b26-8e51-2a71ca8bab2b.png)

**Additional context**
Checked in FF and Edge, both latest.

**Comment by stsrki** [comment]
What happened there 😅? Definitely a bug. Thanks for letting us know.

**Comment by Luk164** [comment]
> 
> 
> What happened there 😅? Definitely a bug. Thanks for letting us know.

If you cut out the active one you could pass it off as "modern art" 🤣
