### ISSUE TITLE
<LayoutHeader Fixed="true"> causes overlap of LayoutContent

### ISSUE THREAD

**Issue by hammie1010** [Megabit/Blazorise#2695]
It seems like in 0.9.4.1 LayoutHeader Fixed="true" causes overlap of LayoutContent

```
<Layout>
    <LayoutHeader Fixed="true">
        <MainMenu></MainMenu>
    </LayoutHeader>
        <LayoutContent>
            @Body
        </LayoutContent>
    <LayoutFooter Fixed="true">
        <MainFooter></MainFooter>
    </LayoutFooter>
</Layout>
```

**Comment by T3charmy** [comment]
I was having this issue on 0.9.4 as well, ended up having to make my own CSS class to fix this temporarily.

For me the css variable `--b-bar-horizontal-height` was undefined according to chrome debugging.

**Comment by stsrki** [comment]
I cannot reproduce it. Can you show a screenshot as an example?

And also please try clearing cache with ctrl+F5.

**Comment by hammie1010** [comment]
![image](https://user-images.githubusercontent.com/12533052/126542676-7bf14e76-e30e-48e9-8782-84d69f5e73ab.png)

vs. (without fixed header)

![image](https://user-images.githubusercontent.com/12533052/126542807-9d67d25e-0c66-4669-9fc0-6b7e4a9729b6.png)

**Comment by T3charmy** [comment]
> > I was having this issue on 0.9.4 as well, ended up having to make my own CSS class to fix this temporarily.
> > For me the css variable `--b-bar-horizontal-height` was undefined according to chrome debugging.
> 
> It was probably undefined because you don't use Blazorise's ThemeProvider.

Are you referring to
```
<Blazorise.ThemeProvider Theme="@theme">
...
</Blazorise.ThemeProvider>
```

in App.Razor? If so I have that in there and same error.

![image](https://user-images.githubusercontent.com/389845/126544831-27981d27-4172-47f3-8b8c-ab5973418900.png)
Is this a value I should be manually assigning or is it calculated automatically?

Looks like the theming is working based on this: 
![image](https://user-images.githubusercontent.com/389845/126544938-a1341582-cfa5-4a9a-b302-0762ca9b4ccc.png)

**Comment by T3charmy** [comment]
> Is this a value I should be manually assigning

Ahh digging through some source code for the theme provider I figured out the issue. This is what I was missing.
```
        BarOptions = new ThemeBarOptions()
        {
            HorizontalHeight = "4.5em"
        }
```

Works now. in both 0.9.4 and 0.9.4.1!

I assumed this was automatically calculated on load, apparently that assumption was wrong.

**Comment by stsrki** [comment]
I don't think I see any issue with your screenshots? LayoutHeader is properly placed about the content.

@hammie1010 Can you try @T3charmy solution?

**Comment by hammie1010** [comment]
> I don't think I see any issue with your screenshots? LayoutHeader is properly placed about the content.
> 
> @hammie1010 Can you try @T3charmy solution?

The LayoutHeader is covering/overlapping the LayoutContent.  No the solution didn't work in my case.

**Comment by guillermodimas** [comment]
> The LayoutHeader is covering/overlapping the LayoutContent. No the solution didn't work in my case.

Having the same issue after updating to 0.9.4.1

**Comment by stsrki** [comment]
Guys, I did more testing, and I have also had the same _issue_ in my new project where the top bar is used without a sidebar, it would mess with the top bar height. The solution is to add HorizontalHeight into theme settings or to define `--b-bar-horizontal-height` CSS variable.

My own example can be seen here: https://github.com/Megabit/Blazorise/pull/2732/files#diff-deb219f50fe5618c34444044a20aa1079044d220afb9099580c90917d5affdb1R20

---

I must admit at first I have completely forgotten about it but was able to track the change in one of the PR I did recently where I had to introduce `--b-bar-horizontal-height` to make the `alone` bar work, BUT without breaking anything. That's why by default the variable is undefined. I should have probably documented it so that there is no confusion.

**Comment by mtbayley** [comment]
Also suddenly experiencing this issue.
Is there a way to get the actual width of the bar? The size of my bar is different depending on the way the text is wrapped in the header. 88px is good for most screen sizes, but not all.

**Comment by stsrki** [comment]
> Also suddenly experiencing this issue.
> Is there a way to get the actual width of the bar? The size of my bar is different depending on the way the text is wrapped in the header. 88px is good for most screen sizes, but not all.

That's actually not a bad idea to get the actual bar size. If theme setting is undefined then I can calculate size and apply the css variable. I will try it and will let you guys know how it goes.

**Comment by stsrki** [comment]
Good news. I was able to calculate bar height and apply the theme variables if it is already undefined.

I will need to do more tests before final merge.
