### ISSUE TITLE
Can I use the component's own functionality directly?

### ISSUE THREAD

**Issue by snowchenlei** [Megabit/Blazorise#2700]
The current component has fewer features and cannot meet usage requirements. For example, some components contain their own features.I want to use,how to
For example, select, table, cascader of antiblazor

**Comment by stsrki** [comment]
Hi, I'm not sure what you mean by "_use the component's own functionality directly_". Can you please explain what is not good with the components and what you want to accomplish? Thanks.

**Comment by snowchenlei** [comment]
For example,now not have [cascader](https://ant-design-blazor.gitee.io/en-US/components/cascader) component,but antiblazor have.I want to use it

**Comment by stsrki** [comment]
Ah, so you want to have a _cascaded_ component so that you can create a hierarchical menu. It could be done with `Dropdown` but we first need to fix some issues with multiple submenus. In any case, it would not be done until v0.9.5 which we just started working on.

Your best option at this time would be to create it with multiple components. Something like in this article https://www.mikesdotnetting.com/article/319/cascading-dropdowns-with-blazor

**Comment by snowchenlei** [comment]
no.
cascaded component is example.Represents all the components that blazorizse does not currently have but use that the ui contains.
 if now can use these non-existent components in some way and then remove them(some way) when blazorizse implements them.
This is best!
This can compensate for the current shortage of blazorizse components.and can have more time to implement components that are not available today.

> like this
``` csharp
<Modal @ref="modalRef">
  <ModalContent Centered="true">
    <ModalBody>
      <Field>
        <FieldLabel>Name</FieldLabel>
        <TextEdit Placeholder="Enter name..." />
      </Field>
      <Field>
        <FieldLabel>Region</FieldLabel>
        # strar AntBlazor
        <AntBlazor.Cascader></AntBlazor.Cascader>
        # end AntBlazor
      </Field>
      <Field>
        <FieldLabel>Region</FieldLabel>
        # strar MatBlazor
        <MatBlazor.MatButton OnClick="ButtonClick">Open</MatBlazor.MatButton>
        # end MatBlazor
      </Field>
    </ModalBody>
  </ModalContent>
</Modal>
```

**Comment by David-Moreira** [comment]
Hello @snowchenlei 
We're having some difficulties understanding what your proposal is. 

1. We understand that somehow you want to mix different vendor components, specially the one's that Blazorise does not support just yet... So far this is it... Right?

2. Most Blazorise components should already provide a RenderFragment which should enable you to render others different component's inside of the Blazorise component's just like you are showing on this Blazorise.Modal example... you've posted...

And the example you have provided does seems like a valid one, isn't it? What's missing here?

**Comment by snowchenlei** [comment]
yes.thanks

**Comment by David-Moreira** [comment]
@snowchenlei 
I'm sorry.. but language barrier isn't helping here. We'd appreciate if you could make an effort to re-explain your situation, or find some friend or way to voice your thoughts that can translate them to enligsh without loosing most of the original meaning.

So... we still have no idea what your proposal is.
> And the example you have provided does seems like a valid one, isn't it? **What's missing here?**
