### ISSUE TITLE
[FR] Multi-select with autocomplete

### ISSUE THREAD

**Issue by bestpika** [Megabit/Blazorise#2703]
**Is your feature request related to a problem? Please describe.**

Now there is a single-select autocomplete, but multi-select no autocomplete, so I hope this feature can be added.

**Describe the solution you'd like**

I hope this feature can be similar to JQuery's Select2 extension.
<https://select2.org/getting-started/basic-usage#multi-select-boxes-pillbox>
![image](https://user-images.githubusercontent.com/5698157/126626491-0dfe69da-ae48-4b59-b2ae-6e9b8f3340bd.png)

### Additional context

Thank you.

**Comment by David-Moreira** [comment]
Hello @bestpika 
We are aware that these type of features are well sought after. Unfortunately we didn't have enough time in 0.9.4 to plan and execute it, but have already made quite a few improvements to AutoComplete in 0.9.4, check out: #2548 

We will consider this for 0.9.5. Also Related: #2528

**Comment by stsrki** [comment]
Thank you for the recommendation but considering we already have a tracking ticket for this feature I will close the ticket.
