### ISSUE TITLE
Missing step in documentation?

### ISSUE THREAD

**Issue by StefH** [Megabit/Blazorise#2705]
In step 2:
https://github.com/Megabit/Blazorise/blob/master/CONTRIBUTING.md#running-documentation

I get an error:
```
stef@DESKTOP-6DD5QI2:/mnt/c/dev/GitHub/_forks/StefH/Blazorise/docs$ bundle exec jekyll serve
Could not find gem 'github-pages' in rubygems repository https://rubygems.org/ or installed locally.
The source does not contain any versions of 'github-pages'
Run `bundle install` to install missing gems.
```

So I think that before you can do `bundle exec jekyll serve`, you need `bundle install`?

**Comment by stsrki** [comment]
Yes, you need to install Jekyll and bundle before running docs.
