### ISSUE TITLE
[Bulma 0.9.4.1] The class .is-rounded is wrongly set

### ISSUE THREAD

**Issue by thepra** [Megabit/Blazorise#2706]
**Describe the bug**
In `blazorise.bulma.css` the class `.is-rounded` is set as `border-radius: 4px !important;` something that doesn't even exist in the official bulma library.

**To Reproduce**
1. Update the NuGet package from `0.9.4` to `0.9.4.1` 
2. Start you front-end and all your roundings are wrong

**Expected behavior**
I expect the class `.is-rounded` to be the same from the original css library.

`<input type="text" class="input is-rounded" />`

**Screenshots**
![immagine](https://user-images.githubusercontent.com/7032509/126653363-1ec6c0f0-11b3-4688-b60b-83b2bb405378.png)

**Comment by stsrki** [comment]
It seems I have chosen the wrong class name for the utility. Thanks for reporting it. I will change it to something else so that doesn't clash with Bulma classes.

Maybe `has-border-rounded`.
