### ISSUE TITLE
DatagridEditMode.Popup don't close Dialog after Save

### ISSUE THREAD

**Issue by HaPre** [Megabit/Blazorise#2722]
I use DatagridEditMode.Popup in my Datagrids. Before 0.9.4 stable, after pressing Save in the dialog, the Popup closes. Now the popup hides the "body", and the header with the title and the footer with "Save" and "Cancel" are still there and the popup don't close anymore.
<img width="1456" alt="BeforeSave" src="https://user-images.githubusercontent.com/84223333/126867330-d30a2c3a-407e-44dd-85ae-eb768f7cfd2a.png">
<img width="1456" alt="AfterSave" src="https://user-images.githubusercontent.com/84223333/126867336-f56a1148-43f9-4314-bf7a-66c8101136d9.png">

**Comment by stsrki** [comment]
@David-Moreira probably something with StateHasChanged. Can you check?
