### ISSUE TITLE
Blazorise.Visibility.None not hide Button

### ISSUE THREAD

**Issue by cyuz** [Megabit/Blazorise#2729]
**Describe the bug**
Set Visibility attribute to None, not hide the button.

**To Reproduce**
`<Button Color="Color.Danger" Visibility=Blazorise.Visibility.None>MyButton</Button>`

**Expected behavior**
The button should be hided

**Screenshots**
![image](https://user-images.githubusercontent.com/8605253/126952392-ff728d4e-724b-4144-b732-8d7f529c3ea7.png)

**Additional context**
.net core 5.0
blazorise 0.9.4.1

**Comment by stsrki** [comment]
I can see the confusion. `None` means the style will not be applied. To actually hide the element you should use `Invisible` enum.

**Example**

```cshtml
<Button Color="Color.Danger" Visibility="Blazorise.Visibility.Invisible">MyButton</Button>
```

---

We are actually planning to change the API to remove `None` or make it something else so that this kind of situation doesn't happen. See #2479.
