### ISSUE TITLE
Datagrid Edit-popup should not close by clicking outside of it

### ISSUE THREAD

**Issue by HaPre** [Megabit/Blazorise#2733]
Until now the Edit popup in the datagrid also closes when clicking outside the popup, it seems not to be modal. There should be a way to make the popup modal, perhaps with EditMode="DatagridEditMode.PopupModal". It happens more often that you click outside the popup and then lose all the entries you have made so far.

**Comment by stsrki** [comment]
Hi @HaPre. I understand the problem and it should be easy to fix. But I don't quite understand what you mean by saying 

> ...it seems not to be modal. There should be a way to make the popup modal...

Our popup is actually a modal, as in, it uses an actual `Modal` component. We just named it Popup in the DataGrid. Maybe that is the confusion here?

**Comment by stsrki** [comment]
Our `Modal` component is more generic so it needs to cover both scenarios. That's why we have a cancellable `Closing` API on the Modal. Example: https://blazorise.com/docs/components/modal/#closing

Now we only need to bring that same API on the DataGrid.

**Comment by HaPre** [comment]
Yea, that's great and would be fine for me, but how can I do this for the datagrid popup? I don't have a @ref for this internally handled Modal. When I open the window, I should be able to set Cancel = false, and after saving, i could set Cancel = true.

**Comment by stsrki** [comment]
It's not possible at the moment. That's why I said we would need to introduce it in the new version :)

**Comment by HaPre** [comment]
That's great!
