### ISSUE TITLE
Suggestion: For DataGrid Virtualize can we change Style=height... to be max-height?

### ISSUE THREAD

**Issue by robalexclark** [Megabit/Blazorise#2740]
I'm using the virtualize datagrid feature along with setting the height using VirtualizeOptions. This works well, except when there are few rows in the datagrid then the datagrid size doesn't shrink to match (when using Paged it does). This means there is a blank space on my page...

Instead of outputting height, can you use max-height (or add another option to output max-height instead of height)

**Comment by stsrki** [comment]
We can add it but I'm not sure everyone would prefer to have `max-height`. And you can easily override it with some custom CSS selector.

@David-Moreira What do you think?

**Comment by robalexclark** [comment]
I can't easily override it in css because I am setting the height dynamically:

` VirtualizeOptions='new() { DataGridHeight = browser.Height-120 + "px" }'`

The browser.Height comes from using Ed Charbenaus BlazorSize package

**Comment by stsrki** [comment]
Yeah, I understand. It makes sense to add DataGridMaxHeight. Then if any option is defined it will be used.

**Comment by David-Moreira** [comment]
@robalexclark 
If you're doing it dynamically... have you tried setting the Datagrid's `Style` parameter to the desired max height? That should work solving your problem.
Let us know if it works.

As for your feature request, we'll take a look if it makes sense to add or not. If we add it, it'll be for 0.9.5.
So to manage expecations... on first tought, it seems more of a standard styling configuration then something that `Virtualize` actually needs configured to work properly like setting the `DataGridHeight`.
But if you are saying you have a different styling behaviour between `Virtualize` and Datagrid with `Paging` we'll take a look to see if that's indeed a mandatory `Virtualize` option to provide.

**Comment by robalexclark** [comment]
Setting the Style didn't work very well because the Style is output on a different element to height.

`<div class="table-responsive table-fixed-header" style="height: 500px"><table id="BulkAllocationsGrid-DataGrid-0" class="b-table table table-striped table-bordered table-sm b-datagrid" style="max-height:1200px">  `

I tried to `unset `the height and that meant I didn't get a fixed header (I'm guessing a height of some sort on that element is needed for virtualisation to work).

**Comment by robalexclark** [comment]
But yes the height of a datagrid does work differently from `Virtualize `to `Paging `presumably because paging doesn't need a height of some sort set (?)

So, if I was being pushy :-), I would sorta say this is a bug because on `Paging `the height is automatically set dynamically whereas on `Virtualize `it becomes fixed (and this issue can be fixed by outputting that height as `max-height` instead of `height`)

**Comment by David-Moreira** [comment]
Oh, I'm sorry setting the Styles on the Datagrid, will change the styling of the underlying table as Datagrid is based on a Table.
So for workaround you'd have to set a fixed css style or if you really want to set it dynamically... do some javascript solution.

Virtualize is based on the OutterDiv for scrolling capabilities... And that's where you need to make the change. 
`<div class="table-responsive table-fixed-header" style="height: 500px">`
max-Height does allow for dynamic height while still providing correct Virtualize capability.
We'll take a look at additionally providing Max-Height as a Virtualize Option.
Thank you @robalexclark

**Comment by robalexclark** [comment]
So I took a look at this in the 0.9.5-preview2.1, and changed my 
`VirtualizeOptions='new() { DataGridHeight = "360px" }'`
to
`VirtualizeOptions='new() { DataGridMaxHeight = "360px" }'`

but it doesn't quite work as expected as there is still a default height style output (at 500px) - if I use chrome tools to unset the height style (so there is only max height) then the datagrid height works wonderfully!

**Comment by robalexclark** [comment]
I can "fix" it by doing a 
.table-responsive.table-fixed-header
{
    height:unset !important;
}

in the css....

**Comment by David-Moreira** [comment]
Are you sure those 500px come from blazorise?
Thanks for testing, I'll take a look ASAP.

**Comment by robalexclark** [comment]
I think so, becuse when I do 
`
VirtualizeOptions='new() { DataGridHeight = "unset" }'`

this fixes the issue as well (and 500px is not output)
