### ISSUE TITLE
Steps Content

### ISSUE THREAD

**Issue by JasonTFifer** [Megabit/Blazorise#2742]
Is there away to get the Steps Items to appear below the Content?  I'm building a set up wizard and when I follow the provided documentation, the Steps appear above the Step content. I'd like to have the Steps appear below. Is this possible?

**Comment by stsrki** [comment]
It is possible but it would require some work. If we're talking about the Bootstrap provider then swapping `step-text` and `step-circle` elements would be enough. You can do it by creating a custom `Step` component that inherits from Blazorise `Step`.

Create a new component name it `ReverseStep.razor` and copy:

**ReverseStep.razor**

```cshtml
@inherits Blazorise.Step
<CascadingValue Value="@this" IsFixed="true">
    <li id="@ElementId" class="@ClassNames" style="@StyleNames" @onclick="@ClickHandler" @attributes="@Attributes">
        @if ( Marker != null || Caption != null )
        {
            <div class="@ContainerClassNames">
                @if ( Caption != null )
                {
                    <span class="@DescriptionClassNames">
                        @Caption
                    </span>
                }
                @if ( Marker != null )
                {
                    <span class="@MarkerClassNames">
                        @Marker
                    </span>
                }
            </div>
        }
        else
        {
            <div class="@ContainerClassNames">
                <span class="@DescriptionClassNames">
                    @ChildContent
                </span>
                <span class="@MarkerClassNames">
                    @CalculatedIndex
                </span>
            </div>
        }
    </li>
</CascadingValue>
```

**ReverseStep.razor.cs**

```cs
public partial class ReverseStep : Blazorise.Step
{
    #region Constructors

    public ReverseStep()
        : base()
    {
        ContainerClassBuilder = new( BuildContainerClasses );
    }

    #endregion

    #region Methods

    protected virtual void BuildContainerClasses( ClassBuilder builder )
    {
        builder.Append( "step-container" );
    }

    protected override void DirtyClasses()
    {
        ContainerClassBuilder.Dirty();

        base.DirtyClasses();
    }

    #endregion

    #region Properties

    protected ClassBuilder ContainerClassBuilder { get; private set; }

    protected string ContainerClassNames
        => ContainerClassBuilder.Class;

    #endregion
}
```

Then override component registration in `Startup.cs`

```diff
builder.Services
    .AddBlazorise( options =>
    {
        options.ChangeTextOnKeyPress = true;
    } )
    .AddBlazoriseRichTextEdit( options =>
    {
        options.UseBubbleTheme = true;
        options.UseShowTheme = true;
    } )
    .AddBootstrapProviders()
    .AddFontAwesomeIcons();

+builder.Services.AddTransient( typeof( Blazorise.Step ), typeof( Blazorise.Demo.Pages.Tests.ReverseStep ) );
```

![image](https://user-images.githubusercontent.com/900302/127398268-7494e536-4b1a-4070-85fd-541a66055471.png)

**Comment by JasonTFifer** [comment]
Sorry, I should've specified. It's for the Bulma provider. I was a little confused regarding the Steps vs StepsContent information on the documentation page. I didn't know if breaking things out to StepsContent would be the way to go or not.

**Comment by stsrki** [comment]
:)

For Bulma it is similar process. I played a little in DevTools and after swapping elements I only needed to adjust some CSS

Same as before, create **ReverseStep.razor**, while **ReverseStep.razor.cs** is not needed in this case.

Copy:

```cshtml
@inherits Blazorise.Step
<CascadingValue Value="@this" IsFixed="true">
    <div id="@ElementId" class="@ClassNames" style="@StyleNames" @onclick="@ClickHandler" @attributes="@Attributes">
        @if ( Marker != null || Caption != null )
        {
            @if ( Caption != null )
            {
                <div class="@DescriptionClassNames">
                    <p class="step-title">
                        @Caption
                    </p>
                </div>
            }
            @if ( Marker != null )
            {
                <div class="@MarkerClassNames">
                    @Marker
                </div>
            }
        }
        else
        {
            <div class="@DescriptionClassNames">
                <p class="step-title">
                    @ChildContent
                </p>
            </div>
            <div class="@MarkerClassNames">
                @CalculatedIndex
            </div>
        }
    </div>
</CascadingValue>
```

and custom CSS somewhere on your site

```css
.steps .step-item:not(:first-child)::before {   
    top: 5rem;
}
```
Adjust if needed.

**Comment by JasonTFifer** [comment]
I'll give it a try and report back. Thanks!

**Comment by JasonTFifer** [comment]
I'm not sure this is going to do what I'm asking. I may not have been clear before.  I'm wanting to move the step bar below the content... instead of how it's appearing above. 
![image](https://user-images.githubusercontent.com/78178498/127406715-afd44f79-1a5a-4f4b-8b6f-a46e39a11a6b.png)

I tried what you had put for the ReverseStep, and maybe I'm missing something, but this appears to only replace the Step control - it doesn't seem to move like I'm hoping to get to.

**Comment by stsrki** [comment]
I was under the impression you want to move the `Step` text content from below the step circle to above the circle. My mistake.

Back to your question. You only need to swap `Steps` and `StepsContent`

```cshtml
<StepsContent SelectedPanel="@selectedStep">
    <StepPanel Name="1">
        <Field>
            <TextEdit Placeholder="Name" />
        </Field>
    </StepPanel>
    <StepPanel Name="2">
        <Field>
            <TextEdit Placeholder="Surname" />
        </Field>
    </StepPanel>
    <StepPanel Name="3">
        <Field>
            <TextEdit Placeholder="Address" />
        </Field>
    </StepPanel>
    <StepPanel Name="4">
        Finish
    </StepPanel>
</StepsContent>
<Steps @bind-SelectedStep="@selectedStep">
    <Step Name="1">
        Step 1
    </Step>
    <Step Name="2">Step 2</Step>
    <Step Name="3">Step 3</Step>
    <Step Name="4">
        Finish
    </Step>
</Steps>
@code{
    string selectedStep = "1";
}
```

**Comment by JasonTFifer** [comment]
I may be running into a bug. And full disclosure, I'm still on 0.9.3.10 because I haven't had a chance to test 0.9.4 yet. But this is what I get when I do StepsContent and Steps as you mentioned above.

![image](https://user-images.githubusercontent.com/78178498/127506143-d78a36ec-35ac-4ed0-8b2f-94d6be8cddd8.png)

Each StepPanel gets rendered to the screen and the Steps never show up. I had actually tried this before I posted the issue but I figured I was doing something wrong or missing a step in the set up. Is this a bug in 0.9.3.10 that's fixed in 0.9.4? Or is there something else I need to do that I'm missing?

Here is my component code:

![image](https://user-images.githubusercontent.com/78178498/127506734-74657a99-53c5-401d-8161-ef024ffce7c9.png)

_selectedStep is a string in a code-behind file. The Steps functionality works if I use Steps by itself, but the Steps are above the Content, which is what I would prefer to change.

**Comment by stsrki** [comment]
Can you remove `<Items>` tag from `Steps`?

**Comment by JasonTFifer** [comment]
Getting closer, but all of the StepPanels are still rendering to the screen. (Main Location and Thanks for Choosing are separate Steps).

![image](https://user-images.githubusercontent.com/78178498/127508479-e9bd2163-3a5a-4017-9e2b-df859018e4a0.png)

**Comment by JasonTFifer** [comment]
I wanted to provide an update. I've updated to 0.9.4.2 and I'm still running into this issue.

**Comment by David-Moreira** [comment]
Hello @JasonTFifer 
From looking at the posted image.
You are missusing the component. The `StepsContent` should be set inside the `Steps` component under the `Content` RenderFragment, otherwise, there's no way for both components to communicate / share state. 

Please also check out our docs for how to structure the `Steps` component 
https://blazorise.com/docs/components/step/

If you're still having difficulties, providing a repository showcasing the problem will be faster for us to be able to help you.

**Comment by stsrki** [comment]
Steps and StepsContent can be used separately. Nothing wrong with that. The only thing I can see that is wrong it the `<Items>` tag inside of the `Steps`. It shouldn't be used when both Steps and StepsContent are used.

**Comment by David-Moreira** [comment]
Oh, so that's also supported? My bad, sorry for missleading. Okay. :)

**Comment by JasonTFifer** [comment]
All the panels are showing at the same time. The Steps are at the bottom, but the Panels all display.

![image](https://user-images.githubusercontent.com/78178498/128953099-e67ff6c9-99e7-4e07-8d1e-87c73a066adb.png)

The "Account", "Admin Account", "Main Location" and "Thanks for choosing" are all StepPanels. If I do the normal code with Items & Content, it works like it should, but the Steps are at the top. If I do what I've posted in these pictures, the Steps show at the bottom like I want, but all the Panels display, which is not what I want (nor think it's supposed to work that way).

![image](https://user-images.githubusercontent.com/78178498/128953310-157c7ca0-3d7b-4b79-b9b2-b2da57724346.png)

If there's some additional code you want to see, let me know. When I originally posted this, I was using 0.9.3.10 but have updated to 0.9.4.2 and it still happens.

**Comment by David-Moreira** [comment]
Yes. Would need to see like...every code that is part of that image.

Can you replace the components inside the step panels with just regular strings and confirm if it still happens or not? Because what I was trying yesterday was pretty much the same, with the exception of having text inside the step panels instead of components... (not that it should matter...but helps troubleshoot ) 

Is it viable for you to share all code somehow? Being that repository is ideal.

**Comment by JasonTFifer** [comment]
I can't post the code for that project because it's an active product we're working on but aren't ready to publish publicly yet. I have reproduced the issue in a throw-away project I created for another issue I posted on here. This project is Blazor WASM and Blazorise only; it does not contain any of my custom code. The issue is still happening.  I'll work on posting the code to Github, but for now here are some screenshots to show it's still an issue.

![image](https://user-images.githubusercontent.com/78178498/129046424-f4f81d60-60af-4233-9053-9507c17ff2e4.png)

![image](https://user-images.githubusercontent.com/78178498/129046547-669ff39c-d273-4bf6-884a-ed6e39ff00fe.png)

![image](https://user-images.githubusercontent.com/78178498/129046619-4d29ee4c-8c46-494d-9d2d-6417604af2f7.png)

![image](https://user-images.githubusercontent.com/78178498/129046828-4d93410d-6204-47d8-9bb3-34c4a408a999.png)

![image](https://user-images.githubusercontent.com/78178498/129046996-0596a0d1-02a8-4dae-84a6-268b078f16fb.png)

![image](https://user-images.githubusercontent.com/78178498/129047342-b03c65a9-5951-4a88-bbdb-09e68b50ca16.png)

**Comment by JasonTFifer** [comment]
That did it. Thank you!
