### ISSUE TITLE
ModalSize.ExtraLarge is same width as Large using Material provider

### ISSUE THREAD

**Issue by LJek77** [Megabit/Blazorise#2745]
ModalSize.ExtraLarge is same width as ModalSize.Large using Material provider

1. Open https://materialdemo.blazorise.com/tests/modals
2. Click on 'Large Modal', remember width of dialog on screen
3. Click on "Extra Large Modal", measure width of dialog
4. Be convinced of similarity

Expected behavior: ExtraLarge size must be wider than Large, as with Bootstrap provider at https://bootstrapdemo.blazorise.com/tests/modals

**Comment by stsrki** [comment]
Hi @LJek77, I have investigated and the reason why it doesn't work is that we have an older version of djibe material. We will update it and release a new demo.

In case you also need to update material you can download it from https://djibe.github.io/material/

**Comment by DomenicoFormoso** [comment]
ModalSize.Extralarge is same width as ModalSize.FullScreen using material. Is normal?

**Comment by stsrki** [comment]
> ModalSize.Extralarge is same width as ModalSize.FullScreen using material. Is normal?

I'm testing it on our live demo and it seems to be working as expected https://materialdemo.blazorise.com/tests/modals

Can you confirm that you have the latest Blazorise version? Also make sure that you have all the CSS file defined for material provider https://blazorise.com/docs/usage/material

**Comment by DomenicoFormoso** [comment]
Hi, the Blazorise version is 1.3.1, CSS installation if OK.
But I want to explain my problem better:  when I use the modal service I specify the size in the options.  There are Small, Large, Extra Large and FullScreen options, using FullScreen or ExtraLarge the result is the same. Using ExtraLarge I expect a size larger than Large but smaller than FullScreen.

**Comment by stsrki** [comment]
@DomenicoFormoso can you please open a new issue so that we can start looking into it?

**Comment by DomenicoFormoso** [comment]
https://bootstrap5demo.blazorise.com/tests/modals >>> The demo with Boostrap gives me what I expect 
![material](https://github.com/Megabit/Blazorise/assets/15198399/63846bd5-3d44-48e3-8513-e8755b4d40b4)

https://materialdemo.blazorise.com/tests/modals >>> The demo with Material returns a dialog equal to FullScreen
![bootstrap](https://github.com/Megabit/Blazorise/assets/15198399/29f486ff-1a6f-48dc-bd87-eebda6b8bc89)
