### ISSUE TITLE
Sider layout with header on top does not render properly

### ISSUE THREAD

**Issue by PatrickBig** [Megabit/Blazorise#2747]
**Describe the bug**
Layout with sider and header on top does not work properly.
See documentation example here:
https://blazorise.com/docs/components/layout/#sider-with-header-on-top

When using this layout the sider pins to the upper left hand corner covering part of the top header.

There is also a gap in the lower left corner that is the same height as the top header.

**To Reproduce**

Currently using the latest version of blazorise.
```html
<Layout>
  <LayoutHeader Fixed="true">
    Header
  </LayoutHeader>
  <Layout Sider="true">
    <LayoutSider>
      <LayoutSiderContent>
        Sider
      </LayoutSiderContent>
    </LayoutSider>
    <Layout>
      <LayoutContent>
        Content
      </LayoutContent>
    </Layout>
  </Layout>
</Layout>
```

**Expected behavior**
Expect the left sider to be pinned to the lower left side of the screen.

**Screenshots**
![blazorise](https://user-images.githubusercontent.com/18059535/127505862-862455d6-fcc3-4c84-b39b-ed19bed6cb31.png)

**Additional context**

**Comment by stsrki** [comment]
Removing `Fixed` from `LayoutHeader` seems to work. Although I agree, it should work with Fixed also.

```
<LayoutHeader>
    Header
  </LayoutHeader>
```
