### ISSUE TITLE
Visual bug BarEnd BarDropdown

### ISSUE THREAD

**Issue by kofinn** [Megabit/Blazorise#2751]
**Describe the bug**
Visual bug, when using Layoutsider + BarEnd + BarDropdown. This bug is present in demo page too (See screenshot).

https://github.com/Megabit/Blazorise/blob/master/Demos/Blazorise.Demo/Layouts/MainLayout.razor#L147

**To Reproduce**
Switch sidebar to small mode and move to Utilities icon. BarDropdown will open downwards and part of it will not be visibile unless you scroll down. IT is causing issue only if there is more than one item.

**Expected behavior**
BarDropdown should open upwards. 
Add direction parameter to BarDropdown like it is for  Dropdown 

**Screenshots**
![image](https://user-images.githubusercontent.com/22171329/127575703-7e87cf65-867f-4d33-bc1d-26352229cc3b.png)

![image](https://user-images.githubusercontent.com/22171329/127576010-d117a914-21f5-42de-8c2c-b38a3dca362a.png)

**Comment by jasonstubbs** [comment]
A workaround for this is to anchor the dropdown container to the bottom of the bar, which will pretty much give the correct behaviour:

```
.b-bar-end .b-bar-dropdown-menu-container {
    bottom: 0;
}
```

The edge case is when there are multiple dropdowns at the end of the bar. For example if there are 5 dropdowns and the top one only has 2 items inside, the dropdown container will be become separated from its toggle. A workaround for _that_ is to anchor it to the bottom of the toggle, but it doesn't feel as natural:

```
.b-bar-end .b-bar-dropdown {
    position: relative;
}
```
