### ISSUE TITLE
Dropdown toggled-event stops working the second time you open the dropdown

### ISSUE THREAD

**Issue by tommykri** [Megabit/Blazorise#2769]
**Describe the bug**
When using the Dropdown-component the Toggled-event stops working the second time you open the dropdown menu.

**To Reproduce**

Using this code:

    <Dropdown Toggled="Toggled">
        <DropdownToggle>Visible: @Visible</DropdownToggle>
        <DropdownMenu>
            <DropdownItem>Action 1</DropdownItem>
            <DropdownItem>Action 2</DropdownItem>
        </DropdownMenu>
    </Dropdown>
        
    @code {
        protected bool Visible { get; set; }
    
        protected void Toggled(bool value)
        {
            Visible = value;
        }
    }

1. Initially you will see "Visible: false". (Expected)
2. Click to open the dropdown. You will see "Visible: true". (Expected)
3. Click to close the dropdown. You will see "Visible: false". (Expected)
4. Click to open the dropdown. You will see "Visible: false". (Not expected)

From this point on, the event will always return false.

**Expected behavior**
I expect the event to always give me the correct visible value regardless of how often the dropdown has been opened.

**Additional context**
Using Blazor Server with Blazorise version 0.9.4.2

**Comment by David-Moreira** [comment]
@stsrki 
problem is with `data-toggle="dropdown"` which instantiates bootstrap's Dropdown js and adds an event listener that stops calling blazor onclick.
![unknown](https://user-images.githubusercontent.com/22283161/128095781-5956dd9b-fbda-46c6-984c-1433778ddd84.png)

Proposed solution is to remove: 
`data-toggle="dropdown"`
After all we are doing the toggling ourselves. No need for the bootstrap js to handle it. And that would be on par with the remaining providers which are also handled by Blazor and not js.
Tested and every dropdown was working. 
However, not 100% like the dropdown from bootstrap js, that does some inline placement according to definitions like `data-boundary`.
![bootstrap dropdown](https://user-images.githubusercontent.com/22283161/128096065-592e0b9d-6d58-4eca-a2c5-abf78fb7f0ac.png)
My proposal is to also take a look at this, and adapt where and if it makes sense, making it so, that all providers also benefit from this.

I also noticed that our material demo is loading bootstrap js incorrectly, which makes it also instatiante the bootstrap js dropdown behaviour, which is incorrect.

Also, redudancy? Keep only one of these in a future version? 
![image](https://user-images.githubusercontent.com/22283161/128096314-494cf8c8-5569-4444-830a-b42e54e549f7.png)
![image](https://user-images.githubusercontent.com/22283161/128096365-9b6074be-e7f0-4c47-9dae-0bd464f4b057.png)
![image](https://user-images.githubusercontent.com/22283161/128096378-26cf4a41-b8e9-4b6c-9dc5-a4bb4c239bdd.png)

Let me know if you're okay with these changes, and I can work on it.

**Comment by stsrki** [comment]
Good job finding the real problem. Unfortunately, removing `data-toggle` breaks the menu. See the `dropright` menu in the screenshot:

![image](https://user-images.githubusercontent.com/900302/128142768-5c9a4621-2a79-44a2-bb3a-dacaba28a5dd.png)

We will need to find a way to calculate menu position without the need for jquery.

---

I agree with the `Toggled` event being redundant. We need to implement a `VisibleChanged` event callback that is along with other toggleable components. And having VisibleChanged will enable us to have two-way binding.
