### ISSUE TITLE
[Question] How to apply current theme color to styles?

### ISSUE THREAD

**Issue by Luk164** [Megabit/Blazorise#2770]
I have a button with an icon. I want the icon to have circle around it, that matches the color of the icon. Right now my style looks like this:
`Style="background-color: transparent; border-radius: 50%; border: 2px solid white; padding: 0;"`

What is the correct way to replace "white" with current font color from theme? Is that even possible? If I try to use \@theme to access color variable I get an error stating that complex content is not supported.

Button code:
```
<Button @ref="button" Color="Color.Success" Size="Size.Large" Style="border-radius: 0; margin: 0;" Clicked="() => Clicked.InvokeAsync()">
            <Blazorise.Icon Name="MaterialIcons.ChevronRight" Style="background-color: transparent; border-radius: 50%; border: 2px solid white; padding: 0;"/>
</Button>
```

Screenshot for illustration of resulting button:
![image](https://user-images.githubusercontent.com/30559213/128014932-e7fb3a80-cb97-4abc-8db7-bbe2da8e101a.png)

**Comment by stsrki** [comment]
Maybe use theme variable?

Example: `var(--b-theme-text-white)`

```
<Button Color="Color.Success" Size="Size.Large" Style="border-radius: 0; margin: 0;">
    <Blazorise.Icon Name="IconName.ChevronRight" Style="background-color: transparent; border-radius: 50%; border: 2px solid var(--b-theme-text-white); padding: 0;" />
</Button>
```

**Comment by Luk164** [comment]
@stsrki Looks good, thx. I would suggest throwing this into theming docs, I forgot that the css even contains our defined colors.
