### ISSUE TITLE
Bar default height should be auto?

### ISSUE THREAD

**Issue by Jimmys20** [Megabit/Blazorise#2787]
Hello, in previous versions of Blazorise I could customize the size of the Bar component by adjusting the vertical paddings. This is the usual way to change navbar height in bootstrap as you can see here https://stackoverflow.com/a/43117693/10839134. I want the Bar height to be responsive (smaller on mobile screen) so I use the following code:

```
<Bar Background="Background.Primary"
     ThemeContrast="ThemeContrast.Dark"
     Padding="Padding.Is1.OnY.OnMobile
                     .Is2.OnY.OnTablet">
    ...
</Bar>
```

On latest version 0.9.4.2 of Blazorise this approach is no longer working because the Bar component has a fixed height in pixels coming from the `--b-bar-horizontal-height` css variable which is calculated here https://github.com/Megabit/Blazorise/blob/4e15766c229c26130859617004d3169bfcf85a92/Source/Blazorise/Components/Bar/Bar.razor.cs#L84

You probably had a reason to add this but my expectation would be `--b-bar-horizontal-height` to be set to `auto` by default based on the `ThemeBarOptions` (or not be set at all when `Theme.ThemeBarOptions` is null).
https://github.com/Megabit/Blazorise/blob/4e15766c229c26130859617004d3169bfcf85a92/Source/Blazorise/Themes/Models/ThemeBarOptions.cs#L31

What do you think?

**Comment by stsrki** [comment]
To tell you the truth, `--b-bar-horizontal-height` is recently giving me too much trouble and I'm already thinking of removing it in favor of just setting Bar height manually via `Style` or padding like you already do.

The main problem is that the layout content is not working properly when the top Bar is fixed. And it messes everything. Still trying to come up with the right solution without breaking changes.

**Comment by Jimmys20** [comment]
I'm not sure if I understand the problem correctly but in Bootstrap when using a fixed navbar it is normal that the layout container is pushed to the top of the window behind the navbar. You have to manually add padding-top or similar css rules to push it below the navbar.

https://getbootstrap.com/docs/4.6/components/navbar/#placement
> Fixed navbars use position: fixed, meaning they’re pulled from the normal flow of the DOM and may require custom CSS (e.g., padding-top on the <body>) to prevent overlap with other elements.

**Comment by stsrki** [comment]
It's just that I'm _overly-trying_ to make it work with Blazorise without the need for custom CSS. But yeah, I know, if everything fails, custom CSS will be required

**Comment by Jimmys20** [comment]
In v0.9.4.3 it looks like you removed the top bar height calculation, so now the `--b-bar-horizontal-height` css variable remains undefined and resolves to `auto` by this css rule `height: var(--b-bar-horizontal-height, auto);`

https://github.com/Megabit/Blazorise/commit/bba39fc1321cd6ab04b89ed5269cc562a6f8dd7a#diff-f248585ee81f26c9e214159f0aad07a66043b6c26f30e7e4927f23d0724be92a

For me this is the expected behavior so this issue can be closed.
