### ISSUE TITLE
Blazorise Wasm Dropdown toggle bug on 0.9.4.2 Bulma Provider

### ISSUE THREAD

**Issue by JasonTFifer** [Megabit/Blazorise#2788]
**Describe the bug**
Clicking a dropdown open appears to generate an error. When clicking to close, it adds an additional toggle icon to the dropdown.

**To Reproduce**
1. Click Dropdown to open
2. Click Dropdown to close

**Expected behavior**
Expecting that the dropdown will display and hide normally, without adding an additional toggle icon and throwing an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/78178498/128591661-a5317158-2f74-4f4b-af0c-470e00f6c726.png)

![image](https://user-images.githubusercontent.com/78178498/128591664-a83e98f1-41a3-402b-bf3d-be3f0f4d925b.png)

![image](https://user-images.githubusercontent.com/78178498/128591668-36405d37-8088-4659-87c1-2c50a084b354.png)

![image](https://user-images.githubusercontent.com/78178498/128591671-490d7f95-014e-4b5f-8fb0-de32b1e8d503.png)

![image](https://user-images.githubusercontent.com/78178498/128591680-cab71eb4-daec-4fa2-97e5-aa7768549908.png)

![image](https://user-images.githubusercontent.com/78178498/128591688-28b585f6-38f2-45a6-a249-8b8a3defae20.png)

**Additional context**
I've added the ?v=0.9.4.2 fix to the js and css files as described in other issues to fix the JSInterop issues. The problem still occurs. I've done CTRL+F5 also and the issue still happens. It was working fine on 0.9.3.x.

**Comment by stsrki** [comment]
I cannot reproduce it on my side. Is there any chance you have some custom JS file that could bind to the dropdown and change the toggle behavior? Can you share the content of your index.html?

**Comment by JasonTFifer** [comment]
Sorry I didn't have a chance to get back to you yesterday. I'll do some more looking and get back to you. I do have some custom JS but it doesn't do anything with the dropdown control. I'm going to create a base project that doesn't include any of my libraries and see what I find. If you'd like me to close the issue for now, that's OK.

**Comment by JasonTFifer** [comment]
OK, I think I figured out what is going on. I've created a base project that doesn't include any of my libraries. I was still seeing the issue. The problem appears to be Font Awesome JS file. If you load FA via their JS and SVG files, the issue happens, but if you load them via the CSS and WebFonts, it does not. But this was not happening with the Blazorise 0.9.3.10 release. I'm seeing it on Edge, Chrome and Firefox. I can attempt to use the CSS/WebFonts instead of the JS/SVG files. There was a specific reason I was using JS/SVG but I don't remember the reason for it right now. Regardless, it looks like something is different between 0.9.3.10 and 0.9.4.2 since it was working OK before. If you want to reproduce, load Font Awesome using the JS method `<script  src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"></script>`.

0.9.3.10
![image](https://user-images.githubusercontent.com/78178498/128732729-41dee372-9cbd-424e-8298-ba2ef41cc7fc.png)

![image](https://user-images.githubusercontent.com/78178498/128732876-1b93cb78-4ec0-4a9b-9c7b-966042620d6c.png)

![image](https://user-images.githubusercontent.com/78178498/128732952-1b7799b9-1d5e-408d-8624-c7fb18b7f8dc.png)

0.9.4.2
![image](https://user-images.githubusercontent.com/78178498/128733440-0cc0070b-0285-4dad-afee-741e643d7b78.png)

![image](https://user-images.githubusercontent.com/78178498/128733585-8c648643-3df9-41e8-8b88-21b4bc23e550.png)

![image](https://user-images.githubusercontent.com/78178498/128733685-c76dcc7a-1024-4bc4-974e-13730e6c0b59.png)

**Comment by stsrki** [comment]
Hmm not that I'm seeing it I remember some time ago I had the same problem. But I don't remember what I did to fix it. I think I just used FA css file https://github.com/Megabit/Blazorise/blob/master/Demos/Blazorise.Demo.Bulma/wwwroot/index.html

**Comment by JasonTFifer** [comment]
I'll try the CSS file. There was a specific reason I was using the JS method, but I can't think of it right now.
