### ISSUE TITLE
10 columns grid - bootstrap

### ISSUE THREAD

**Issue by drma-dev** [Megabit/Blazorise#2790]
I know that there are some workarounds that can be done via css. but is there anything via component configuration that you can say that the row will have 10 columns instead of 12?

**Comment by stsrki** [comment]
Do you mean to have always 10 columns, max? No that is not possible. Blazorise column is, and always will be 12 columns based. We don't have any plans to change that behavior.

**Comment by drma-dev** [comment]
I don't mean always.  in Bootstrap there is a way for you to decide how many columns you want to work by changing the css.  in that case, you would make each column 10% wide.

**Comment by stsrki** [comment]
Yes I know, but even with bootstrap it means for you to manually download source code and then compile it. In the end you're left with a custom bootstrap css that is only valid for you own project. Now imagine doing that for every other Blazorise provider like bulma or AntDesign. It would become a nightmare to support pretty soon.

**Comment by drma-dev** [comment]
I think I found two alternatives, but I can't use any of them: 

if I don't set the column size, the bootstrap automatically adjusts.
```
<div class="row">
   <div class="col">
      xxx
   </div>
   <div class="col">
     xxx
   </div>  
</div>
```
it's equivalent to:
```
<Row>
    <Column>
        xxx
    </Column>
    <Column>
        xxx
    </Column>
</Row>
```
but if i want to define a column for the other resolutions, the component won't let me set null for full hd resolution.
```
<Row>
    <Column ColumnSize="ColumnSize.OnFullHD.Is2.OnDesktop.Is4.OnMobile">

    </Column>
</Row>
```

another solution is that it asks for a string for me to dictate the rules, but the component doesn't accept any value that I try to put:
```
<Row>
    <Column ColumnSize="ColumnSize.Is("width: 10%").OnFullHD.Is2.OnDesktop.Is4.OnMobile">

    </Column>
</Row>
```

**Comment by drma-dev** [comment]
@stsrki

**Comment by stsrki** [comment]
The purpose of `ColumnSize.Is()` is to be able to define custom class name rule, not the style. To define the actual style you can use the `Style` parameter, eg `Style="width:10%;"`.

**Comment by drma-dev** [comment]
@stsrki 
actually what I was trying to say, is that these two ways of using it doesn't even let you compile.

![image](https://user-images.githubusercontent.com/12803050/129429432-23b70579-57df-43f4-80f4-aea004dcc7f6.png)
![image](https://user-images.githubusercontent.com/12803050/129429445-7cccc8e5-722e-433d-96ef-1152982df33e.png)

**Comment by stsrki** [comment]
The rule of column size is to first say **what** to do, and then **where** or **when** to do. So for example, `Is2` is the **what** part. And `OnDesktop` is the **where** part. They both need to come in that order. `OnDesktop` or `OnFullHD` cannot come first. That's why **OnFullHD** on its own is wrong.

Regarding the `Is()` method, it is for the custom rule so there is no way for me to know what can be defined in it. It can practically do anything so in a way it breaks the natural flow of the column rules. That's why it doesn't have **where** rules. I have no way to know how to apply a rule to something that can be practically anything.

**Comment by drma-dev** [comment]
@stsrki  ok, I understand about the `Is()`.

but about the other example, my question is: is there a way (you developed this possibility) to put this WHAT to not apply anything (just class 'col')? So that in a given WHEN apply the following blank template:
```
<div class="row">
   <div class="col">
      xxx
   </div>
   <div class="col">
     xxx
   </div>  
</div>
```
that way I can leave the columns dynamic width only when it's desktop

**Comment by stsrki** [comment]
`col` should be applied by default if you leave it empty, eg `<Column>`.

**Comment by drma-dev** [comment]
yes, i know. for that reason i try to do this
![image](https://user-images.githubusercontent.com/12803050/129482130-be6eb022-02d6-4d7e-980a-781834d3b603.png)

that's why I asked if it is possible to develop a WHAT generating this value? if possible and you have no time to do it, I can do it and send you a PR, no problem.

**Comment by drma-dev** [comment]
Okay, this is the result I want to reach, and the component does not currently allow.
`col-xl col-md-2 col-4`
