### ISSUE TITLE
Animate only works on a limited amount of items

### ISSUE THREAD

**Issue by Luk164** [Megabit/Blazorise#2791]
**Describe the bug**
I wanted to animate items in list appearing one-by-one, but only a few of the items actually animate and the rest becomes stuck.

Here is what the code looks like:

```
@for (var i = 0; i < 10; i++)
{
     foreach (var farm in GlobalModel?.CompanyData?.Farms
         .Where(farm => FuzzySharp.Fuzz.PartialRatio(farm.Name, SearchString) > 65 || string.IsNullOrWhiteSpace(SearchString))
         .Select((value, i) => new { i, value }))
         {
             <Animate Animation="Animations.FadeRight" Duration="TimeSpan.FromSeconds(0.5)" Delay="TimeSpan.FromMilliseconds(farm.i * 250 + 250)">
                  <FarmListEntry FarmInstance="@farm.value" Clicked="@(() => _selectedFarm = farm.value)"/>
             </Animate>
         }
}
```

**To Reproduce**
1. Create a long list of items similar to the one I showed
2. Start the project

**Expected behavior**
Every item in the list appears, one-by-one, each with 250ms delay from the previous one.

**Screenshots**
![image](https://user-images.githubusercontent.com/30559213/128645703-1f775db6-f86f-4426-9f77-bb9dd02e84ce.png)

**Context**
The for cycle is there to artificially increase the amount of items so I can check if everything scrolls correctly.

**Comment by Luk164** [comment]
Update: It seems that only the components visible at the beginning are animated, the rest seem to be waiting to be shown on screen, but never trigger.

**Comment by David-Moreira** [comment]
Easier example to replicate:

```
@for ( var i = 0; i < 100; i++ )
{
    <Blazorise.Animate.Animate Animation="Animations.FadeRight" Duration="TimeSpan.FromSeconds(0.5)" Delay="TimeSpan.FromMilliseconds(i * 500)">
        <div>HELLOOOOOOOOO</div>
    </Blazorise.Animate.Animate>
}
```
First impressions: 
- It seems there is a ceiling, `data-aos-delay="3000"` if value higher then 3000 it won't animate.
![image](https://user-images.githubusercontent.com/22283161/128647576-87acfacb-58cd-4cb7-8647-04d326a03d6f.png)
- Components rendered out of view, are hidden.

We'll take a look, thanks for reporting.

**Comment by David-Moreira** [comment]
Oh wait... 
@Luk164 
![AnimateLimitation](https://user-images.githubusercontent.com/22283161/128647679-0e8da70c-5f5a-4cc0-babe-9da761faacea.png)
and maybe @stsrki can enlighten us about this limitation. I'm pretty sure, there's gonna be a good reason, haha

**Comment by Luk164** [comment]
> Oh wait... 
> @Luk164 
> ![AnimateLimitation](https://user-images.githubusercontent.com/22283161/128647679-0e8da70c-5f5a-4cc0-babe-9da761faacea.png)
> and maybe @stsrki can enlighten us about this limitation. I'm pretty sure, there's gonna be a good reason, haha
> 

There were only three elements in the list in foreach, so I do not think I broke the 3000ms limit.

**Comment by David-Moreira** [comment]
You're right, I'm sorry. 
So your problem is the items rendered out of view, right?

**Comment by David-Moreira** [comment]
I'm testing on Blazorise Demo Page. And having a sidebar seems to affect the scroll detection... Since it works just fine on a regular page. Guessing... something to do with it not having the scroll detection set to the right element. From the AOS examples, not sure if this is configurable...

In the meantime, could you also provide us, with the rest of the components that are on your page?
We'll investigate further...

**Comment by stsrki** [comment]
As far as I know, 3000 ms is the AOS default limit but it can be increased https://github.com/michalsnik/aos/issues/179

**Comment by Luk164** [comment]
@stsrki That is not the point. The problem occurs even if the time is left unset, or set the same for all elements.

**Comment by Luk164** [comment]
Here is a downloaded site to illustrate: 
[Site.zip](https://github.com/Megabit/Blazorise/files/6954085/Site.zip)

**Comment by Luk164** [comment]
Interesting, after using the following code in the default counter site, everything works as I would like to:

```
@for (var i = 0; i < 100; i++)
{
    <Animate Animation="Animations.FadeUp" Duration="TimeSpan.FromSeconds(0.5)">
        <h6>Test</h6>
    </Animate>
}
```

[CounterTest.zip](https://github.com/Megabit/Blazorise/files/6954120/CounterTest.zip)

**Comment by Luk164** [comment]
Possiby related issues on AOS (CSS library used by Animate):
https://github.com/michalsnik/aos/issues/675
https://github.com/michalsnik/aos/issues/675

**Comment by David-Moreira** [comment]
Luk... You're basically just reiterating the analysis previously done...

> I'm testing on Blazorise Demo Page. And having a sidebar seems to affect the scroll detection... Since it works just fine on a regular page. Guessing... something to do with it not having the scroll detection set to the right element. From the AOS examples, not sure if this is configurable...

> In the meantime, could you also provide us, with the rest of the components that are on your page?
We'll investigate further...

Thing is we need to figure out how to handle the scroll detection for these cases.

**Comment by stsrki** [comment]
I have investigated more about the problem and there is not an easy solution. It is a known problem, according to the number of issues people are reporting on the AOS repository.

But, I think I found how to make it work. You need to apply the `data-aos-anchor` attribute. Original source: https://github.com/michalsnik/aos/issues/364

```cshtml
<CardBody ElementId="my-test">
    @for ( var i = 0; i < 100; i++ )
    {
        <Animate data-aos-anchor="#my-test" Animation="Animations.FadeRight" Duration="TimeSpan.FromSeconds(0.5)" Delay="TimeSpan.FromMilliseconds(i * 200)">
            <div>HELLOOOOOOOOO</div>
        </Animate>
    }
</CardBody>
```

But to make it work with that many elements you also need to increase the animation length. Remember, by default AOS is set to work for up to 3000ms, max.

So, it is best to compile the following SCSS yourself(default max is set to 60).

```css
[data-aos] {
    @for $i from 1 through 600 {
        body[data-aos-duration='#{$i * 50}'] &,
        &[data-aos][data-aos-duration='#{$i * 50}'] {
            transition-duration: #{$i * 50}ms;
        }

        body[data-aos-delay='#{$i * 50}'] &,
        &[data-aos][data-aos-delay='#{$i * 50}'] {
            transition-delay: 0s;

            &.aos-animate {
                transition-delay: #{$i * 50}ms;
            }
        }
    }
}
```

We could compile it in Blazorise but then `aos.css` would grow too much. It grew from 26KB to 217KB just with this small change. I think it is best to leave it as it is, and then if you need to have more you can do compile it. Not ideal, I know.

**Comment by Luk164** [comment]
@stsrki Could we make put it into an optional pre-compiled file instead? We can remove it later once a better fix has been found.

**Comment by stsrki** [comment]
Where would that file be located?

**Comment by Luk164** [comment]
@stsrki Bundle it into the animate nuget, then users can optionally reference it if needed? It would slightly increase the size but that should not be problem for a nuget right?

**Comment by stsrki** [comment]
As far as I know, it would increase the content of the DLL. And that would mean WebAssembly applications would have a higher payload when downloading.

**Comment by Luk164** [comment]
@stsrki You are right, that wouldn't work. What about hosting the .css file on something like cloudflare for now? If you need the fix you just reference it and if you need it offline you can download it manually. Seems like a decent solution until a permanent fix is found

**Comment by David-Moreira** [comment]
Maybe the 3000ms limit does not matter for your use case @Luk164 ? And I don't think we should support more then the libraries original default maximum value. If it's there, it's for a reason, and we starting going out of the libraries supported values. 
If you need to go higher, then that's already a custom implementation.

So for your use case, Luk, applying the anchor should be enough?

And I guess it would be enough to document this limitation and the anchor fix, for the scroll detection.
(Might also be worth exposing a self documented property Anchor?)
