### ISSUE TITLE
Indeterminate progress is not animated

### ISSUE THREAD

**Issue by topharley** [Megabit/Blazorise#2798]
**Describe the bug**
Indeterminate progress is not animated.
https://bootstrapdemo.blazorise.com/tests/progressbars and https://bootstrapdemo.blazorise.com/tests/utilities/services are showing correct animated Indeterminate progress, but latest version of sources https://github.com/Megabit/Blazorise is not working in that case anymore

**To Reproduce**
1. Download sources  from https://github.com/Megabit/Blazorise
2. Build and run, open /tests/progressbars 
3. Scroll down to Indeterminate progress, and click it
4. See that there is no Indeterminate progress animation

**Comment by David-Moreira** [comment]
I just ran both **rel-0.9.4** and **master** branch. Couldn't replicate. Which branch did you download and what demo did you run?

**Comment by topharley** [comment]
It is something on my computer, i've checked it on another and it is working fine.
Sorry for inconvenience
