### ISSUE TITLE
Upgrade 0.9.4.1 to 0.9.4.2 causes app to hang (something to do with ShowPager="true"?)

### ISSUE THREAD

**Issue by robalexclark** [Megabit/Blazorise#2800]
In two completely unrelated applications (one work and one at home), the upgrade from 0.9.4.1 to 0.9.4.2 causes the blazor server app to hang - the page with a datagrid on never loads.

Reverting back to 0.9.4.1 fixes the issue with no other code changes. Commenting out the Datagrid razor markup does allow the page to load.

Also, bizarrely, when ShowPager="false"  the app works ok, but when I flip it to ShowPager="true" thats when it hangs (took a lot of trial and error with all the settings!).

In the morning I'll try my work app and see if it shows the same behaviour.

**Comment by David-Moreira** [comment]
Hello @robalexclark 
can you post the stack trace, if there's any? 
Also can you try out the latest RC on https://www.myget.org/feed/blazorise/package/nuget/Blazorise ? So we know if the current RC has the same bug?

Also please post your sample code to reproduce the problem here. Makes it easier for us to test.

**Comment by robalexclark** [comment]
There is no error in the output or point at which I can pinpoint the error occurs (frustrating I know) as it doesn't error, it just hangs before the page loads. The best I could do when I was looking earlier was that it hung on an initial entity framework db call, which at first glance seems totally unrelated to blazorise.... I'm suspecting an async type issue.

Nope, using 0.9.4.3-rc2.1 still results in the same error, but turning showpager=false fixes it, as does switching to a virtualized grid.

**Comment by David-Moreira** [comment]
hmm from 0.9.4.1 to 0.9.4.2 we didn't make too much changes on datagrid, specially on the pager...
only commit I found, was 43fd6122 which introduces a stateHasChanged on the Paginate call, but that should not be an issue at all....

If you're able, we'd appreciate if you could provide us with a repository reproducing the problem.

**Comment by robalexclark** [comment]
Morning - I wired up my home project to the Blazorise repos and toggled between 47fbbd45a35726c8bd4e73f0c3efa316b9ad80d8 and 43fd6122543964910c33dfa51c7fef1d018598e6.

47fbbd45a35726c8bd4e73f0c3efa316b9ad80d8 - works
43fd6122543964910c33dfa51c7fef1d018598e6 - hangs.

Thats all I have time for at the moment but will try and look a bit closer later on.

**Comment by robalexclark** [comment]
I have a repro for you:

https://github.com/robalexclark/BlazoriseBug

Run and click on the menu bar Setup -> Colonies

The attempt to load page Colonies.razor will hang


If you rollback to blazorise 0.9.4.1 and re-run, a basic grid will show.

**Comment by David-Moreira** [comment]
Hello @robalexclark 
Thank you for providing the demo, it really helped.
So in addition to displaying the Pager which is part of the problem. You have to provide a **null collection for the Data property**.
If you provide an empty list it should go back to working normally. So in the meantime, that can be a temporary workaround for you.

**Problem:**
Keeps looping on this getter:
![image](https://user-images.githubusercontent.com/22283161/129634416-d9d41138-ce3b-4849-a181-4e0102ffc061.png)
![image](https://user-images.githubusercontent.com/22283161/129634443-5b980a02-84ad-4fdd-b101-ed651906df31.png)
![image](https://user-images.githubusercontent.com/22283161/129634479-5a328146-cc3f-4991-af60-738a6a2b6f85.png)
![FilterDataState](https://user-images.githubusercontent.com/22283161/129634671-9ef25852-be3a-4742-9a8a-e4d5b2fd1f03.png)
![FilterData](https://user-images.githubusercontent.com/22283161/129634566-c4e89754-e9f3-4ba3-82a1-863a73452da0.png)


The fix should be easy in theory, but I still have to do some testing. Thank you for finding this bug.
