### ISSUE TITLE
.Net 6 and 7 features

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#2801]
In this ticket, we will make note of features that we want to implement in the future but are currently only part of .Net 6

- **generic parameters as numbers** https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-7/#early-net-7-feature-preview-generic-math
- **query string as parameters** https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-7/#supply-blazor-component-parameters-from-the-query-string
- **support for multiple `<select>`** https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-7/#support-for-the-multiple-attribute-on-select-elements-in-blazor
- **modify `head`** content https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-7/#modify-html-head-content-from-blazor-components
- **custom-event-arguments** https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-6.0#custom-event-arguments
- **Error boundaries** https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-6.0#error-boundaries

**Comment by GregBrubaker** [comment]
Doesn't support the new .Net 6 data types For Date Only (There is also a new TimeOnly.)

**Error: Unsupported type System.Nullable`1[System.DateOnly]**

<DatePicker Date="DateOnly.FromDateTime(DateTime.Now)"  TValue="DateOnly?" />

**Comment by David-Moreira** [comment]
Also take a look at the new periodic timer
https://github.com/dotnet/runtime/issues/31525
Might be worth refactoring components that use timer behind the scenes.
