### ISSUE TITLE
Is there any way to change the pagination position(Left and Right) in Datagrid in Blazorise?

### ISSUE THREAD

**Issue by annaarun** [Megabit/Blazorise#2803]
Is there any way to change the pagination position(Left and Right) in Datagrid ?

**Comment by David-Moreira** [comment]
Hello @annaarun 
we don't support it by default. You'll have to play with css to allocate the pager position.
Simple Example:
![image](https://user-images.githubusercontent.com/22283161/129269315-03e81b79-7bcf-4d70-857f-c451fe29b479.png)
