### ISSUE TITLE
MessageService customization error

### ISSUE THREAD

**Issue by hugomarshall** [Megabit/Blazorise#2804]
I´m trying to customize the MessageService text buttons and icons but they ignore my changes...
I´m doing something wrong or it´s a bug ?

`await MessageService.Confirm("Existem dados que ainda não foram sincronizados com o servidor, deseja carrega-los ?", "Carregar dados", options => new MessageOptions { CancelButtonText = "Não", OkButtonText = "Sim", ShowMessageIcon = false })
`

**Comment by stsrki** [comment]
You're using options wrong. You don't need to create a new instance(`new MessageOptions`).

And replace `OkButtonText ` with `ConfirmButtonText`.

```cs
await MessageService.Confirm( "Existem dados que ainda não foram sincronizados com o servidor, deseja carrega-los ?", "Carregar dados", options =>
    {
        options.CancelButtonText = "Não";
        options.ConfirmButtonText = "Sim";
        options.ShowMessageIcon = false;
    } );
```
