### ISSUE TITLE
Datepicker value is reset when using @bind-Text with MemoEdit

### ISSUE THREAD

**Issue by jbarrineau06** [Megabit/Blazorise#2808]
Datepicker value is reset when using @bind-Text with MemoEdit

**Describe the bug**
Typing in a MemoEdit component causes the Datepicker value to be reset to its initial value on load. Unsure if this applies to other controls as well.

**To Reproduce**
I created a new Blazor WASM project, ASP.NET Core hosted PWA, installed Blazorise and Blazorise.Bootstrap packages, and used the following code to test on the Index page

```
<DatePicker Date="Date" InputMode="DateInputMode.DateTime" TimeAs24hr="true" DisplayFormat="MM/dd/yyyy H:m" Max="DateTimeOffset.Now" />
<MemoEdit @bind-Text="Comment" Rows="3" />

@code {
  public string Comment { get; set; }
  public DateTime Date { get; set; } = DateTime.Now;
}
```

Change the date to something other than the current day, and then type in the MemoEdit. The Datepicker's value will be reset.

EDIT:
To add a little more context, we have a keyboard component that we wrap all our text inputs with to enable typing on large touch screen monitors, and it requires us to use the @bind directive instead of just the Text parameter so the keyboard and input can share the input's value.

**Comment by stsrki** [comment]
This is the expected behavior and is how Blazor works in general. You're basically using one-way binding with `Date="Date"` and since Date is always the same on each page refresh it will reset. You need to use two-way binding `@bind-Date="Date"` to make it work.
