### ISSUE TITLE
Blazorise DataGrid dynamic column is not removed on datagrid reload

### ISSUE THREAD

**Issue by umraopushpanjay** [Megabit/Blazorise#2809]
I have created a datagrid using bazorise. The issue I am facing is that when the user adds query to the text box and press the Start query button the data is populated in the gridview. However if the user press the same button again to get the updated data from db, the new columns and values get appended to the datagrid, meanwhile the old columns and value doesn't get disposed.

Note: If you are wondering how clear query works, we are just reloading the whole page. which removes the datagrid alltogether.

![gridissue](https://user-images.githubusercontent.com/11743357/129333835-2a9bfac7-92d0-4480-ae5e-c0ff95fbce2f.PNG)

datagridresult.razor:

`<Card>
            <CardBody>
                <Fields>
                    <Field ColumnSize="ColumnSize.Is12.OnDesktop">
                        <TextEdit TextChanged="@((string value) => QueryService.SetQueryText(value))" />
                    </Field>
                    <Divider />
                    <Field ColumnSize="ColumnSize.IsAuto.OnDesktop">
                        <Button Color="Color.Primary" Clicked="@(() => dataGridRef.Reload())">Start Query</Button>
                    </Field>
                </Fields>
                <DataGrid @ref="dataGridRef"
                          TItem="DataRowView"
                          Data="@queryDataView"
                          ReadData="@OnReadData"
                          ShowPager="true" PageSize="@RowCount"
                          RowStyling="@DataGrid_OnRowStyling"
                          Filterable="false">
                    <NextPageButtonTemplate>
                        Next
                    </NextPageButtonTemplate>
                    <LoadingTemplate>
                        <div class="box">
                            <progress class="progress is-small is-primary" max="100" />
                        </div>
                    </LoadingTemplate>
                    <DataGridColumns>
                        @foreach (DataColumn column in QueryTable.Columns)
                        {
                            <DataGridColumn TItem="DataRowView" Caption="@column.ColumnName" Field="@nameof(DataRowView.RowVersion)" Context="item" Filterable="false">
                                <DisplayTemplate>
                                    @($"{item[column.ColumnName]}")
                                </DisplayTemplate>
                            </DataGridColumn>
                        }
                    </DataGridColumns>
                </DataGrid>
            </CardBody>
        </Card>`

datagridresult.razor.cs:

`async Task OnReadData(DataGridReadDataEventArgs<DataRowView> e)
    {
        if (QueryText != "")
        {
            //dataGridRef = new DataGrid<DataRowView>();
            await Task.Run(() => QueryService.StartTable());
            queryDataView = QueryTable.DefaultView.Cast<DataRowView>();
            displayRefreshField = Display.Always;
            StateHasChanged();
        }
    }`

I am not sure why the code is not showing in a formatted way so attaching screenshot of the same
datagridresult.razor:
![image](https://user-images.githubusercontent.com/11743357/129335738-e2504d5f-6ff4-4021-913b-69a260a869f8.png)

datagridresult.razor.cs:
![image](https://user-images.githubusercontent.com/11743357/129336056-01d651bd-90bb-4e07-a711-e18a07a54b67.png)

**Comment by David-Moreira** [comment]
From a quick look at the issue, it seems we're not correctly "unsubscribing" / removing the columns from DataGrid. And there's not easy workaround for this. I guess you could try re-rendering the DataGrid as a whole for a temporary workaround.

We'll fix it asap.

**Comment by David-Moreira** [comment]
Hello @umraopushpanjay 
Any reason why you've closed this issue?
