### ISSUE TITLE
DateEdit crashing a datagrid popup 

### ISSUE THREAD

**Issue by GilShalit** [Megabit/Blazorise#2812]
Blazorise v 0.9.3.9.  Not updated because of the breaking changes...

I have the following datagrid column:
````
        <DataGridColumn TItem="CourtCase" Field="@nameof(CourtCase.Date)" Caption="Date"
                        Sortable="true" Editable="true" Filterable="false">
            <DisplayTemplate>
                @context.Date.ToString("dd/MM/yyyy")
            </DisplayTemplate>
            <EditTemplate>
                <DateEdit TValue="DateTime?" Date="@((DateTime)( context.CellValue ))" DateChanged="@(( v ) => context.CellValue = v)" />
            </EditTemplate>
        </DataGridColumn>
````

CourtCase.Date is defined using ``public DateTime Date { get; set; }``

if the user types 00 (two zeroes) in the date or month parts of the date, the application crashes with the error messaged copied below.  This does not seem like a validation error as the field does not lose focus.

**How can I prevent or trap this error?** 

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at CrudAuthClient5.Pages.Courtcases.<>c__DisplayClass29_4.<BuildRenderTree>b__80(RenderTreeBuilder __builder3)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Blazorise.DataGrid._DataGridCell`1[[CrudAuthClient5.Model.CourtCase, CrudAuthClient5, Version=0.9.1.0, Culture=neutral, PublicKeyToken=null]].BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

**Comment by David-Moreira** [comment]
Hello @GilShalit 
Your property is a DateTime.
However the TValue from the DateEdit is a Nullable DateTime. So your code is not prepared to handle DateChanged that may be null and crashes.
`DateChanged="@(( v ) => context.CellValue = v)"`

The best way is to just match the types from DateEdit and your property if that's possible. Let me know if this helps.

**Comment by GilShalit** [comment]
Thanks!  changing to ``<DateEdit TValue="DateTime"...`` does prevent the crash on an invalid date, and changes the date to 01/01/0001.

But how can I trap this with a validation rule instead of having the user save this 01010001 date?

**Comment by David-Moreira** [comment]
Hello,
Well in the latest version we do support Datagrid validations... Including data annotations
https://blazorise.com/docs/extensions/datagrid/#validations

On your version you can try validating on the rowupdating / rowinserting callbacks. If the data is not valid you can cancel the update / insert operation.
You can also try imbuing the edit templates with the blazorise validation, but again you would need to check if it's valid or not on the rowupdating / rowinserting callbacks. 

https://blazorise.com/docs/components/validation/

**Comment by David-Moreira** [comment]
And one more thing, check the DateEdit component Min parameter, that might be usefull.

https://blazorise.com/docs/components/date/

**Comment by David-Moreira** [comment]
@GilShalit Let us know if this helped and we may go ahead and close this issue.

**Comment by GilShalit** [comment]
yes thanks! this can be closed
