### ISSUE TITLE
AutoComplete Component

### ISSUE THREAD

**Issue by grumpykiwi** [Megabit/Blazorise#2813]
More of a question.

Is it possible to set the autocomplete component so that it displays the contents of the dropdown list and make the list items selectable?

I have the search functionality working which will be fine for most of my users, but there are some that insist on the old school way, even where in some cases that list might contain > 500 items.

Thanks

Mark

**Comment by stsrki** [comment]
Do you mean to show items when the autocomplete gets the focus? You can do that by setting its MinLength to zero, eg. `MinLength="0"`.

**Comment by grumpykiwi** [comment]
Hi Mladen

That was it. Thanks very much. I asked that question at the end of a long day coding. My brain was a bit fried.

Another issue I ran into this morning. See attached for a screenshot.

The code compiles and runs quite happily. It seems to be an issue in VS 2022 Preview 3. No such error happens in VS 2019 16.11.0

App is targeting .Net 5.0 core by the way. I started off targeting .Net 6.0 but ran into an issue with one of the Blazorise packages trying to use a 5.x version of the Logging extensions package and subsequently failing.

Not a big deal. Had to convert my namespace declarations back to the old way but that's about it. Just thought I'd let you know.

I did notice a weird formatting issue on the docs pages where the attributes are listed. Seems to wrap/cut off the right most column a bit.

Thanks for great products.

Cheers


Mark


Mark Nash
Senior Software Engineer        [cid:PC_42x23_fbb4e57e-65d2-4c41-b09e-ffa9f4a3c468.png]

PartnerComm, Inc.
Winner of 76 IABC Gold Quills
2021 Large Agency of the Year
2304 W Interstate 20, Suite 250
Arlington, TX 76017
        [cid:pcomm25+_471933a4-f842-490b-84d4-910cf0397a29.png]

Office: (817) 465-9277
***@***.***
www.partnercomm.net<http://www.partnercomm.net>





This e-mail transmission may contain confidential information or may be otherwise legally privileged. If you are not the intended recipient you are hereby notified that any use, disclosure, copying, forwarding, or distribution of any of the information contained in or attached to this message is STRICTLY PROHIBITED.

________________________________

**Comment by stsrki** [comment]
I already heard about the issue. The thing is I forgot to update the .net 6 versions for nuget packages. So I will fix it in the next update.

**Comment by grumpykiwi** [comment]
Excellent. Thanks


Mark Nash
Senior Software Engineer        [cid:PC_42x23_fbb4e57e-65d2-4c41-b09e-ffa9f4a3c468.png]

PartnerComm, Inc.
Winner of 76 IABC Gold Quills
2021 Large Agency of the Year
2304 W Interstate 20, Suite 250
Arlington, TX 76017
        [cid:pcomm25+_471933a4-f842-490b-84d4-910cf0397a29.png]

Office: (817) 465-9277
***@***.***
www.partnercomm.net<http://www.partnercomm.net>





This e-mail transmission may contain confidential information or may be otherwise legally privileged. If you are not the intended recipient you are hereby notified that any use, disclosure, copying, forwarding, or distribution of any of the information contained in or attached to this message is STRICTLY PROHIBITED.

________________________________
