### ISSUE TITLE
Slider ignores readonly setting

### ISSUE THREAD

**Issue by Luk164** [Megabit/Blazorise#2814]
**Describe the bug**
Slider ignores readonly setting.

**To Reproduce**
1. Create a page
2. Add `<Slider TValue="short" Value="10" Max="100" ReadOnly="true"/>`
3. Run page and try to change value

**Expected behavior**
When readonly is set, it should be impossible to change the value or move the slider in any way by user.

**Screenshots**
![image](https://user-images.githubusercontent.com/30559213/129567449-03f3f54f-1cf9-48a7-a487-03621074a928.png)
![image](https://user-images.githubusercontent.com/30559213/129567507-46d60989-0647-46ed-8a14-5cda4e5e2ce5.png)

**Additional context**
Screenshots show how I used sliders in my page and those sliders with manually changed values despite having readonly attribute set.

**Comment by stsrki** [comment]
According to this, `readonly` is not supported by the `range` input

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range
- https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly

**Comment by Luk164** [comment]
@stsrki That's weird, why would they do that? Anyway, could we just replace a range input with something that looks the same if readonly is set to true?

**Comment by stsrki** [comment]
Welcome to the weird world of web programming where anything doesn't have a meaning 🤦‍♂️🤷‍♂️

I'm trying to find a way to make it work but nothing works so far. The only thing that works is the Disabled parameter. But then it doesn't look like read-only.

**Comment by Luk164** [comment]
@stsrki Three possible solutions come to mind:

1. Use disabled but add some CSS to make it look active
2. After every change quickly change it back (a bit hacky bit simple and it should work)
3. Replace with similar-looking element that is not actually input range

**Comment by stsrki** [comment]
I must admit this was some nasty bug to fix. But I finally found a native CSS way without any javascript needed 🤯
