### ISSUE TITLE
"Unable to determine the Validator" error in TextEdit

### ISSUE THREAD

**Issue by WayneHiller** [Megabit/Blazorise#2815]
I am getting an "Unable to determine the Validator" error from the TextEdit when using Data Annotation validation and the Text & TextChanged properties. The error does not happen when using @bind-Text

```
<Validation>
  <Field Horizontal="true">
    <FieldLabel ColumnSize="ColumnSize.Is2">Number</FieldLabel>
      <FieldBody ColumnSize="ColumnSize.Is10">
         <TextEdit Text="@context.Number"
                     TextChanged="@(v => OnNumberChanged(v, context))">
           <Feedback>
              <ValidationError>Opps!</ValidationError>
           </Feedback>
        </TextEdit>
     </FieldBody>
   </Field>
 </Validation>

```
![image](https://user-images.githubusercontent.com/1186731/129731825-74491a3f-e362-454f-8113-2280ebfc4878.png)

**Comment by stsrki** [comment]
You're using manual two-way binding with `Text` and `TextChanged` and so the Blazor cannot determine field for validation. You can:

- use `@bind-Text`, or
- use TextExpression, eg `TextExpression="@(()=>model.FieldName)"`

**Comment by WayneHiller** [comment]
Ah ok, that makes sense. Using TextExpression fixed it. Is that in the Documentation under Validation & TextEdit, I did not notice it there?

**Comment by stsrki** [comment]
It's not but it is a good idea to make it part of the documentation.

**Comment by stsrki** [comment]
PS for me! Also need to add to new documentation.

**Comment by WayneHiller** [comment]
The other thing that could help is to change the error message a bit to note that is could be because of using manual binding within a form and an Expression may be missing. Seems this is the most common way to cause the error.

**Comment by WayneHiller** [comment]
@stsrki Just watched you on ASP.NET Community Standup, good informative show :)

**Comment by stsrki** [comment]
@WayneHiller Thank you! It was fun and I hope I sounded good :)

**Comment by WayneHiller** [comment]
@stsrki you did good. It was a good reminder to me just how much there is to Blazorise and the over all goal of the project. I spend a lot of time in the source code as I am always learning the framework and trying  to make to make it do things it was not designed to do lol. This was a nice high level overview

**Comment by stsrki** [comment]
I only scratched the surface. There was no much time to explain everything.

**Comment by WayneHiller** [comment]
Well the first step is to let people know Blazorise exists and get them interested enough to take a look.  You (and others) have done a great job on this project. I will be using/supporting it for years to come.

**Comment by stsrki** [comment]
Thank you once again!

**Comment by MattJamesChampion** [comment]
For the sake of completeness, I just ran into the same error while using `@bind-Text`:

    <Validations Mode="ValidationMode.Auto" @ref="_validations" StatusChanged="ValidationStatusChanged">
        <Field>
            <FieldLabel>Location</FieldLabel>
            <Validation>
                <TextEdit @bind-Text="@_shift.Location">
                    <Feedback>
                        <ValidationError/>
                    </Feedback>
                </TextEdit>
            </Validation>
        </Field>
    </Validations>

In this particular case, I was missing the `Model` parameter from `<Validations>`; changing the first line to

    <Validations Mode="ValidationMode.Auto" @ref="_validations" StatusChanged="ValidationStatusChanged" Model="@_shift">

resolved the issue!
