### ISSUE TITLE
Layout component makes sider occupy full vertical overwriting header despite set up to go under it.

### ISSUE THREAD

**Issue by BrettButcher** [Megabit/Blazorise#2816]
I am trying to create a Layout as per the docs example here [Sider With Header On Top](https://blazorise.com/docs/components/layout/#sider-with-header-on-top).

This was working fine but I noticed the  issue after updating to v 0.9.4.3.
Using the code sample from the docs...
I have changed the theme colours but you can see the issue from this image:
![Capture](https://user-images.githubusercontent.com/39193658/129738545-de6b7c77-1290-4b06-b050-66b6b22a59fd.PNG)
Heres the dev screen text:
![Capture2](https://user-images.githubusercontent.com/39193658/129738670-e7a408b7-cd6c-4450-9059-0f0ab377fffb.PNG)

I did wonder if this was a css issue, so I have updated the index.html using the lates scripts from the docs.
`<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>My Project Title</title>
    <base href="/" />

    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;400;600&display=swap" rel="stylesheet">

    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">

    <link href="_content/Blazorise/blazorise.css" rel="stylesheet" />
    <link href="_content/Blazorise.Bootstrap/blazorise.bootstrap.css" rel="stylesheet" />
    <link href="_content/Blazorise.Snackbar/blazorise.snackbar.css" rel="stylesheet" />
    <link href="_content/Blazorise.SpinKit/blazorise.spinkit.css" rel="stylesheet" />
    

    <link href="css/app.css" rel="stylesheet" />
    <link href="AvailablePlayer.Client.styles.css" rel="stylesheet" />

    <link href="manifest.json" rel="manifest" />
    <link rel="apple-touch-icon" sizes="512x512" href="icon-512.png" />
</head>

<body>
    <div id="app">Loading...</div>

    
    

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

    <script src="_content/Blazorise/blazorise.js"></script>
    <script src="_content/Blazorise.Bootstrap/blazorise.bootstrap.js"></script>
    

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
      
     
    <script src="_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js"></script>
    <script src="_framework/blazor.webassembly.js"></script>
    <script>navigator.serviceWorker.register('service-worker.js');</script>
</body>

</html>
`
At first I thought I might have done something to my page, but having swapped out the sample code, I am now wondering if I missed something I should have changed upgrading to the lates version or?

**Comment by BrettButcher** [comment]
Ok, I found a workaround after seeing this issue, which looks very similar and is probably the same.

By taking out the "Fixed="True" from the <LayoutHeader> tag, it works, though its obvs not quite right.
All the best

**Comment by stsrki** [comment]
I'm trying the example and it is in fact an intended behavior. As someone already explained to me in https://github.com/Megabit/Blazorise/issues/2787#issuecomment-894643039, when you set the fixed header you're pulling it from the normal page flow. So it requires some custom CSS or styling on your side.

The easiest thing to do, and which is the preferred way is to adjust the Bar height. You can do it with the theme settings or with the CSS variable.

1. With the theme settings https://github.com/Megabit/Blazorise/blob/master/Demos/Blazorise.Demo/App.razor

```cs
private Theme theme = new()
{
    BarOptions = new()
    {
        HorizontalHeight = "72px"
    }
};
```

2. With CSS variable

Just define `--b-bar-horizontal-height: 72px;` somewhere in your `app.css`.
