### ISSUE TITLE
 Notification service Location missing

### ISSUE THREAD

**Issue by Mr-Pearce** [Megabit/Blazorise#2830]
**Is your feature request related to a problem? Please describe.**
As mentioned in the Documentation 

> The INotificationService is built on top of Snackbar component and is used for showing simple alerts and notifications.

`Snackbar `has a `Location `Property but the `INotificationService `is missing it so that all the Notifications will hide my buttons in the bottom left corner.

**Describe the solution you'd like**
Please Add the Location Property to INotificationService, Globaly in App.razor and per request would be nice.

Also More Locations (Top/Bottom Left, Top/Bottom Right, Top/Bottom Middle) and maybe an Definable Offset like Margin would be nice.

**Comment by stsrki** [comment]
Location added on NotificationAlert. If you want to see why please read the #2906.

Thanks

**Comment by mtbayley** [comment]
@stsrki I am using the latest version 0.9.5.4 and do not see the `Location` property on `NotificationAlert`
