### ISSUE TITLE
LoadingTemplate has a strange none-moving indicator

### ISSUE THREAD

**Issue by sturlath** [Megabit/Blazorise#2847]
This is probably something interfering from my abp.io framework, **but should this really go so bad together**? Is it possible to "isolate"/override this CSS?

This is all I get when using the code here below
![image](https://user-images.githubusercontent.com/2386572/131365435-28a1c44a-238d-4d01-ba9f-f6738de93418.png)

with this code
```xml
<Card>
    <CardBody>
        <CardTitle Size="1" Alignment="TextAlignment.Justified">@L["UpcomingEvents"]</CardTitle>
            <DataGrid TItem="EventWithNavigationPropertiesDto"
                  Data="UpcomingEventList"
                  ReadData ="@LoadUpcomingEventsFromService" 
                  TotalItems="TotalCount"
                  ShowPager="true"
                  Responsive="true"
                  PageSize="PageSize">
                <ChildContent>
         <DataGridColumn TItem="EventWithNavigationPropertiesDto"
                    Field="EventPriceInfo.LivePrice"
                    Caption="Price">
        </DataGridColumn>
                </ChildContent>
                <EmptyTemplate>
                    <div class="box">
                        No upcoming events found!
                    </div>
                </EmptyTemplate>
                <LoadingTemplate>
                    <div class="box">
                        <progress class="progress is-small is-primary" max="100" />
                    </div>
                </LoadingTemplate>
            </DataGrid>
    </CardBody>
</Card>
```

p.s
I´m going to try out [Spinkit](https://blazorise.com/docs/extensions/spinkit/) to see if I can get something better looking and positioning the progress in the middle of the grid.

**Comment by stsrki** [comment]
What version of Blazorise and ABP you're using? I remember I implemented loading indicators in ABP a few months ago.

**Comment by sturlath** [comment]
I'm using Blazorise 0.9.4.3 and ABP 4.4.0.

Am I maybe just stuck with following the ABP-Blazorise versions? I see that if I create a new ABP 4.4.0 project I get Blazorise 0.9.4.1 packages with it.

**Comment by stsrki** [comment]
Not sure. It was done in Blazorise 0.9.3.x so loading animations should work. Unless someone removed the feature in ABP 4.4.0. Cannot confirm because I don't work on ABP anymore.

In either case, try SpinKit.

**Comment by sturlath** [comment]
Thanks, I just tried SpinKit and looks very nice! 

Btw I'll keep on mixing them since I just love all the new stuff you are dishing out, I can´t be without them!
