### ISSUE TITLE
Documentation: The menu shouldn't be opened for 1 second at page load on a smartphone

### ISSUE THREAD

**Issue by iwis** [Megabit/Blazorise#2863]
**To Reproduce**
1. Go to https://preview.blazorise.com/docs on a smartphone (I tested it in Google Chrome 92 on Samsung Galaxy S7).
2. The menu will open, and then hide after 1 second

I reproduced it also on Windows 10 after selecting Galaxy S5 device (360x640 resolution) in Developer Tools in Google Chrome 92. So I assume it is also reproductible on other smartphones.

**Expected behavior**
Opening menu for 1 second looks strange, I suppose it is a bug. No other component library documentation does this.

**Screenshots**
This menu is displayed for 1 second at page load on my smartphone:

![Screenshot_20210902-114821_Chrome](https://user-images.githubusercontent.com/8080496/131823542-92033c35-d33c-4454-b848-0cfeefe8208f.jpg)

**Comment by stsrki** [comment]
I'm already working on that. The problem is larger than I initially anticipated.
