### ISSUE TITLE
 DropDown the ability not to close an element when you click on it

### ISSUE THREAD

**Issue by DezareD** [Megabit/Blazorise#2865]
Is there any way to turn off automatic closing of DropDown when clicking on any area of ​​this object. That is, leave the ability to close the element by clicking outside the element, but not close when clicking in the element area?

**Comment by stsrki** [comment]
For this, we need to refactor how the closing is done. And we already have an opened ticket #2551 scheduled for the next milestone. Once done it will be easy to implement. Similar to how the modal Closing event is already working.

I will close this ticket now since it will be part of #2551
