### ISSUE TITLE
Container breakpoints

### ISSUE THREAD

**Issue by iwis** [Megabit/Blazorise#2866]
**Describe the bug**
The "Attributes" tables, e.g. on the https://preview.blazorise.com/docs/components/tab page, are difficult to read on a Samsung S8/9/10 phone with a horizontally rotated screen, because Blazorise documentation uses only 510px of the 740px available (see the screenshot below).

**To Reproduce**
1. Open https://preview.blazorise.com/docs/components/tab in Google Chrome on a laptop or computer
2. Open Developer tools (F12) 
3. Decrease window width to 740px
4. Scroll to "Attributes" section

**Expected behavior**
Documentation should use the whole width on a Samsung S8/9/10 phone.

**Additional context**
You use Bootstrap `.container` class [equivalent to](https://stackoverflow.com/questions/61248319/difference-between-bootstrap-container-and-container-sm) `.container-sm` class. The `.container-md`, `.container-lg`, or `.container-xl` class introduced in Bootstrap 4.4 would be better.

**Screenshots**

![Doesn't use full screen](https://user-images.githubusercontent.com/8080496/131986167-78335b60-0598-4da9-9ff2-58670e464be9.png)

**Comment by stsrki** [comment]
We use the native Bootstrap responsive class name for tables. I'm not sure how we could make it better. And setting the `container-{size}` doesn't work.

**Comment by stsrki** [comment]
Actually, it works. I had the wrong screen width. Settings the `container-md` on 720px. works,

**Comment by iwis** [comment]
> Actually, it works. I had the wrong screen width. Settings the `container-md` on 720px. works,

I even done the screenshot in meanwhile :)

![image](https://user-images.githubusercontent.com/8080496/131989404-5c48fe38-c3b3-4ba8-af91-d13c28c64c3d.png)

**Comment by stsrki** [comment]
Thanks. I will do the changes.
