### ISSUE TITLE
Extend Trigger to give more manual control of ToolTip balloon (will make AlwaysActive obsolete)

### ISSUE THREAD

**Issue by CaiusJard** [Megabit/Blazorise#2869]
**Describe the solution you'd like**
Right now we have AlwaysActive bool, which when true. always shows the tip, and when false uses the Trigger to choose how to show the tip. There doesnt't seem a way to never show the tip/prevent the tip from showing other than to remove it from the markup(which means we have to duplicate nested elements) eg

```
if(dontShowToolTip){
  <Some>
    <Nested>
      <Markup />
    </Nested>
  </Some>
} else {
<ToolTip>
  <Some>
    <Nested>
      <Markup />
    </Nested>
  </Some>
</Tooltip>
}
```

 I think it would be useful to maybe do away with AlwaysActive and extend Trigger to have 2 more enums "AlwaysShow" and "NeverShow" so that we can manually toggle the tooltip rather than using user interaction

**Comment by stsrki** [comment]
There is already a `Trigger` parameter that is defined by the TooltipTrigger, that looks like 

```cs
/// <summary>
/// Determines the events that cause the tooltip to show.
/// </summary>
public enum TooltipTrigger
{
    /// <summary>
    /// Tooltip will show on mouse enter and focus event (default option).
    /// </summary>
    MouseEnterFocus = 0,

    /// <summary>
    /// Tooltip will show on click event only.
    /// </summary>
    Click = 1,

    /// <summary>
    /// Tooltip will show on focus event only.
    /// </summary>
    Focus = 2,

    /// <summary>
    /// Tooltip will show on mouse enter and click event.
    /// </summary>
    MouseEnterClick = 3,
}
```

default is `MouseEnterFocus`

**Comment by stsrki** [comment]
We might add new `Manual` options that would be used along with the `Show()` method.

**Comment by stsrki** [comment]
It is now possible to set different target https://blazorise.com/docs/components/tooltip
