### ISSUE TITLE
DataGrid ShowPager

### ISSUE THREAD

**Issue by kofinn** [Megabit/Blazorise#2874]
**Describe the bug**
ShowPager in DataGrid is causing unresponsiveness of page and high memory usage on server

**To Reproduce**
In test repository, there are 2 pages
/categorypage                                           working (without pager)
/categorypagepager                                 not working (with pager)
![image](https://user-images.githubusercontent.com/22171329/132238486-6678565b-52a9-4b9c-9661-96092e3868f9.png)

https://github.com/kofinn/PagerTest

**Comment by David-Moreira** [comment]
Hello, 
I will take a look as soon as possible. But from the issue you are describing it might be fixed on #2818 which is still to be released I think. 

@stsrki can you confirm?

**Comment by stsrki** [comment]
I think it might be the same problem. If yes, then it will be fixed with the next release.

**Comment by kofinn** [comment]
I checked #2818 and it is same issue.
Thank you

**Comment by stsrki** [comment]
OK, I will close this ticket now. New version with the fix should be release by the bond of this week.
