### ISSUE TITLE
Scroll to top when clicked on a link

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#2884]
One thing I find annoying (sorry ;-)) with the docs is that if I have scrolled down on one page and click some other, the new page opens in the same scroll position as the the previous one.

_Originally posted by @sturlath in https://github.com/Megabit/Blazorise/discussions/2854#discussioncomment-1291796_

**Comment by CaiusJard** [comment]
It's funny that behaviors like this are only seen as unreasonable because in the old days multipage nav caused a jump to the top; they're not "wrong" per se, they're just "not what we're used to" :)
