### ISSUE TITLE
Theme bar gradient background

### ISSUE THREAD

**Issue by erikthysell** [Megabit/Blazorise#2885]
How do I give sidebar background color a gradient? I tried with just
```
@code{
        private Theme theme = new Theme
        {
            IsGradient = true,
            SidebarOptions = new ThemeSidebarOptions
            {
               BackgroundColor = "linear-gradient(180deg, rgb(0, 62, 102) 0%, #1d7dfa 70%)"
            }
    };
}
```
But this just resulted in the bootstrap default background gradient.

**Comment by stsrki** [comment]
Theme colors accept only simple color values. In either a HEX or RGBA format. Supported values are in format:

- `"#ffffff"`
- `"rgb(1,2,3)"`
- `"rgba(1,2,3,.5)"`

Meaning anything else will not be parsed. The main reason is that we tend to calculate other element colors based on the supplied color values. And parsing and calculating `"linear-gradient(180deg, rgb(0, 62, 102) 0%, #1d7dfa 70%)"` would be impossible.

So the only way to use gradient is to CSS selectors.

**Comment by erikthysell** [comment]
Ok, what is then the effect of `IsGradient`?

**Comment by stsrki** [comment]
It is not used for the Bar at the moment. A quick test showed that It might work, although I must see if there are any side effects.

![image](https://user-images.githubusercontent.com/900302/132481761-0aa6e606-c497-4787-b591-c97fbdab1b74.png)

I will add it for the next milestone.
