### ISSUE TITLE
Documentation: Scrollbar in the middle of a sample code

### ISSUE THREAD

**Issue by iwis** [Megabit/Blazorise#2891]
I don't like the horizontal scrollbar in the middle of the black window between HTML and C# code (in a div with the `blazorise-codeblock` CSS class) on the https://preview.blazorise.com/docs/components/accordion page and on many other pages, e.g. Components > Alert, Card, Grid etc.
This can be solved by displaying a single scroll bar at the bottom of the black window using this CSS:
```
.blazorise-codeblock pre { overflow: visible; } /* removes separate scrollbars */
.blazorise-codeblock     { overflow: auto; }    /* adds one scrollbar for both HTML and C# code */
```

**Comment by stsrki** [comment]
Thank you. It is working fine with these changes. It will be visible once I publish a new version.
