### ISSUE TITLE
Documentation: Mobile - A blank space at the bottom of the page

### ISSUE THREAD

**Issue by iwis** [Megabit/Blazorise#2892]
**Describe the bug**
The documentation is displayed incorrectly on a smartphone with a horizontally rotated screen - a blank space appears at the bottom of the page.

Tested in:
 - Google Chrome 93 on Android 8 on oldish Samsung Galaxy S7
 - Google Chrome 92 on Android 11 on Samsung Galaxy A41
 - Google Chrome 91 on Android on Samsung Galaxy S20 in the https://live.browserstack.com/ service
 
**To Reproduce on a desktop/laptop**
1. Go to https://preview.blazorise.com/docs/components/alert
2. Open Developer tools (F12)
3. Toggle Device Toolbar
4. Select "Galaxy S5" (this step seems to be optional)
5. Rotate device
6. Scroll to the bottom of the page
7. **Move the mouse pointer a little bit (this step seems to be required on a desktop/laptop, I didn't notice it earlier)**
8. Scroll to the bottom of the page again.
9. The blank space will show at the bottom

Tested in Google Chrome 93 on Windows 10.

**Additional context**
I highlighted `<html>` tag on the screenshot (with the blue color).

**Screenshots**
![image](https://user-images.githubusercontent.com/8080496/132657018-56f6bcf5-4b10-4e05-a711-e5ca8e38d984.png)

**Comment by stsrki** [comment]
I cannot reproduce it on chrome devtools. Do you can any idea how to make it?

**Comment by iwis** [comment]
Yes, I edited the issue and made a better description - see above.

**Comment by stsrki** [comment]
I was able to fix it with your example. Thank you!

**Comment by iwis** [comment]
Was it something with a menu?

**Comment by stsrki** [comment]
Yeah, the menu is using `visibility: hidden` instead of `display: none` to hide. But the problem with visibility is that the space is still occupied when it is collapsed. And with `display: none` the animation would not work.

So I  just added `overflow-y: hidden` for the collapsed menu. And it seems to work just fine.

**Comment by iwis** [comment]
Nice! Indeed, when scrolling, two vertical scroll bars were visible - one from the main page and the other from the menu - see the screenshot. Thank you for the fix and explanation.

![image](https://user-images.githubusercontent.com/8080496/132674498-dd0ec5a5-12ea-4a04-a7f7-495a6820d01a.png)

**Comment by stsrki** [comment]
Thank you, for all the work so far!
