### ISSUE TITLE
Hiding Modal with animation

### ISSUE THREAD

**Issue by Meberem** [Megabit/Blazorise#2893]
**Describe the bug**
I am unable to hide the modal with an animation. 

**To Reproduce**
1. Add css
```
@keyframes slide-in-right {
    0% { right: -100%; }
    100% { right: 0; }
}

@keyframes slide-out-right {
    0% { right: 0; }
    100% { right: -100%; }
}

.modal .modal-dialog {
     animation: slide-out-right 0.5s;
     right: -100%;
}

.modal.show .modal-dialog {
    animation: slide-in-right 0.5s;
    right: 0;
}
```
2. Open modal
2. Close modal

**Expected behavior**
The modal opens and closes with an animation. Manually adding and removing the `show` class on the modal will show the expected behaviour.

**Additional context**
I am using the bootstrap provider and it looks like they use a special check for the [`fade` class and defers the closing until the animation is complete](https://github.com/twbs/bootstrap/blob/v4.6.0/js/src/modal.js#L168), I guess something similar needs to happen for the css animation to complete before the `Visibility` and/or `display: block` is removed. 

Applogies if this is not clear, I am a little unsure of css animations in general

**Comment by stsrki** [comment]
We have a similar concept with the transition state in the Carousel component. So I would say this is doable. I will schedule it for v1.0.

@David-Moreira would you like to work on this?

**Comment by David-Moreira** [comment]
Seems doable. Sure. 👍

**Comment by stsrki** [comment]
@David-Moreira 

I think the same approach can be done for the `Collapse` component. It also needs to have animation support. Which got me thinking. Can we have a general approach to handle animations? Some kind of utility class that keeps the open/close state and then updates the attached component.

**Comment by stsrki** [comment]
Any animated component could be inherited for the same interface that can be used by the utility.

```cs
IAnimatedComponent or IClosableComponent{
  Task Open();
  Task Close();
  bool HasFadeAnimation{get;}

  // or
  Task Animate(bool visible);
}
```
