### ISSUE TITLE
Documentation: OnFocus documentation is wrong

### ISSUE THREAD

**Issue by StefanOssendorf** [Megabit/Blazorise#2896]
**Describe the bug**
The documentation of the `OnFocus` event of the `TextEdit` states the following:
`Occurs when the input box gains or loses focus.`
This is wrong. According to: https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-5.0#event-arguments-1 they use it for the `onfocus` html event. And the html event is documented as: https://developer.mozilla.org/en-US/docs/Web/API/Element/focus_event
There is stated that it only occurs for focus and not "lose focus". Lose focus is indicated by `onblur`.

**Expected behavior**
Documentation should reflect the actual behavior.

**Comment by stsrki** [comment]
Description fixed.
