### ISSUE TITLE
DataGridCheckColumn - render it as a readonly checkbox by default 

### ISSUE THREAD

**Issue by CaiusJard** [Megabit/Blazorise#2897]
Perhaps a logic of:

if no string formatter is set, show a checkbox

OR

if a bool RenderAsCheck is true, show a box, otherwise show a text representation of the value, given by the formatter

**Comment by David-Moreira** [comment]
@CaiusJard  for now you can do:
```
                        <DataGridCheckColumn Field="@nameof(Employee.IsActive)" Caption="Active" Editable Filterable="false">
                            <DisplayTemplate>
                                <Check TValue="bool" Checked="context.IsActive" Disabled ReadOnly />
                            </DisplayTemplate>
                        </DataGridCheckColumn>
```

@stsrki What do you think of this? It kinda makes sense to work like the example above, but by default as that should be the grand majority of cases.... and if for some reason the user needs it to be editable while the DataGrid is in Display mode, then he can override the `DisplayTemplate`.

**Comment by stsrki** [comment]
That means we would have to have a special use-case for check(bool) value. Currently we have this internally

```diff
<TableRowCell @onclick:stopPropagation="column.PreventRowClick" Class="@column.CellClass?.Invoke(Item)" Style="@column.BuildCellStyle(Item)" TextAlignment="@column.TextAlignment" VerticalAlignment="@column.VerticalAlignment"  Display="@column.Display">
    @if ( column.DisplayTemplate != null )
    {
        @column.DisplayTemplate( Item )
    }
    else if ( ParentDataGrid.EmptyCellTemplate != null && column.GetValue( Item ) == null )
    {
        @ParentDataGrid.EmptyCellTemplate( Item )
    }
    else
    {
+        @column.FormatDisplayValue( Item )
    }
</TableRowCell>
```

This means we should override that part just for this. It kinda makes sense and kinda doesn't. 😅

**Comment by David-Moreira** [comment]
Ah the struggle when the code isn't gonna look as nice! 🤣
