### ISSUE TITLE
Import JavaScript on-demand with IJSObjectReference

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#2898]
Sources:

- https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-5.0#javascript-isolation-in-javascript-modules-1
- https://blog.elmah.io/using-js-object-references-in-blazor-wasm-to-wrap-js-libraries/

---

I don't know how I missed this but it seems it is possible to import JS on runtime without needing to manually add `_content` files into the `index.html` or `_Host.cshtml`.

@David-Moreira With this we could split our big JS file into multiple smaller, for modal, date inputs, numerics, etc., and then import them once the component is initialized. We need to see if there are any performance issues. And also how to handle different operations for providers, For example, modal can have `open()` method in Bootstrap, Bulma, and AntDesign.

**Comment by David-Moreira** [comment]
Oh I knew about this. I have used it before. Well for the partial js that should already be done on #2728 if I remember correctly?
But yea, great catch, nice!

**Comment by stsrki** [comment]
Yes, you already made partial JS files. But they still end up as one big file. With this feature, we would only need to have smaller files that will be loaded only when the component is rendered. No configuration is needed by the user. And that makes Blazorise installation even easier.
