### ISSUE TITLE
Change Text color (foreground) globally

### ISSUE THREAD

**Issue by erikthysell** [Megabit/Blazorise#2901]
I naively thought the theme property `TextColorOption.Body` would change the color (foreground) of body text but I can se that `TextColorOptions` relate to background color. I don't see any description of `TextColorOptions` in the [theming ](https://blazorise.com/docs/theming/) documentation either.

How do I globally change the color of text?

**Comment by stsrki** [comment]
`TextColorOption.Body` is controlling the class-name `.text-body`. See https://getbootstrap.com/docs/4.1/utilities/colors/

I am aware that the same color should be used for the `body` color. And we have it planned for the next milestone #2837

**Comment by erikthysell** [comment]
Great, thanks!
