### ISSUE TITLE
TextRole add entry for "tel" 

### ISSUE THREAD

**Issue by sks-ttaylor** [Megabit/Blazorise#2905]
**Is your feature request related to a problem? Please describe.**
I would like to use the type="tel" for my current project

**Describe the solution you'd like**
TextRole.cs:: add enum entry "Tel"
EnumExtensions.cs:: add TextRole.Tel=> "tel",

### Additional context
I would be great if you could get it in v0.9.4.5

**Comment by stsrki** [comment]
Shouldn't be a problem but since it is slightly changing the API I'm still not sure it could go into 0.9.4.x. @David-Moreira what do you think? Should we allow the addition of a new enum?
