### ISSUE TITLE
Carousel with only 1 item has a UI flaw

### ISSUE THREAD

**Issue by Brutiquzz** [Megabit/Blazorise#2910]
![jumpy](https://user-images.githubusercontent.com/33770011/133078997-52e40085-399f-48d0-b768-df1fe7acab28.gif)

When the Carousel component only has one item then it makes an unfortunate UI flaw. I have enclosed a gif showing the flaw. 

I have tried playing around with the AutoPlay property but it makes no difference. 

When there is more than 1 item then there is no issue. 

I am creating my carousel like this

```
<Carousel SelectedSlide="0" Class="border-0" Autoplay="false">
                @{
                    var i = 0;
                    foreach (var item in DataComponentModel.Announcements)
                    {
                        if (item.Announcement is null)
                        {
                            continue;
                        }
                        var name = i.ToString();
                        var id = item.CommunityGroupAnnouncementId ?? 0;
                        <CarouselSlide Name="@name">
                            <div class="community-group-announcement-carousel-item-container-overlay" @onclick="@(() => ShowPopup(id))"></div>
                            <div class="community-group-announcement-carousel-item-container overflow-hidden p-3">
                                @((MarkupString) item.Announcement)
                            </div>
                        </CarouselSlide>
                        i++;
                    }
                }
            </Carousel>
```

I am using version 0.9.4.4

**Comment by David-Moreira** [comment]
Hello,
`AutoRepeat="false"` should help you with this, as there's only one item, and the carousel will no longer attempt to change slides.
But `AutoPlay="false"` does not seem to be working correctly. I'll take a look.
