### ISSUE TITLE
Convert Button Focus into FocusAsync

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#2915]

**Comment by David-Moreira** [comment]
What does this mean? In #2923 you seem to be removing FocusAsync? Right?
![image](https://user-images.githubusercontent.com/22283161/134054028-c34d7127-dfa7-4488-8c79-7c5a9d803011.png)

**Comment by stsrki** [comment]
Yes, I removed all `void` functions that were calling async code internally. Or converted them to return `Task`. We can close this ticket.
