### ISSUE TITLE
Select with nullable Enum is not binding the Null option

### ISSUE THREAD

**Issue by leonardotvd** [Megabit/Blazorise#2921]
I have an Select with type Nullable Enum. It only binds the values that are not Null, if I select the first option it doesn't assign null for the variable.

Here is my code:

```cshtml
<Select TValue="LogSourceEnum?" SelectedValue="@LogFilters.Source" SelectedValueChanged="SourceChanged" Style="width:150px">
  <SelectItem TValue="LogSourceEnum?" Value="null">All</SelectItem>
  <SelectItem TValue="LogSourceEnum?" Value="LogSourceEnum.Server">Server</SelectItem>
  <SelectItem TValue="LogSourceEnum?" Value="LogSourceEnum.Client">Client</SelectItem>
</Select>
```
The SourceChanged method only is called for the second and third options. When I select "All", the method is not called. I've tried to change the Value to:
`<SelectItem TValue="LogSourceEnum?" Value="@((LogSourceEnum?)null)">All</SelectItem>`
But it also didn't work.

**Comment by stsrki** [comment]
This is the same problem as #185

Unfortunately, there is no easy way around it since the problem is in how browsers threats the `option` when it contains null values. Can you try removing `All` and just leave it as `<SelectItem TValue="LogSourceEnum?" Value="null"></SelectItem>`?

**Comment by stsrki** [comment]
PS. check #2919

**Comment by ageiter** [comment]
> Unfortunately, there is no easy way around it since the problem is in how browsers threats the `option` when it contains null values. Can you try removing `All` and just leave it as `<SelectItem TValue="LogSourceEnum?" Value="null"></SelectItem>`?

This works, but then of course you don't see any text when this empty entry is selected. Is there a way to use a placeholder text? So that e.g. the following would stand: "Please select an item".

**Comment by ageiter** [comment]
Ok, then I make the workaround that I use the int as values instead of the enums and insert -1 for the "null" value. Then the conversion happens in the event handler.

```                    
<Select TValue="int?" SelectedValueChanged="SearchProjectByStateAsync">
   <SelectItem TValue="int?" Value="-1">All</SelectItem>
   @{
         foreach (var projectState in Enum.GetValues(typeof(ProjectState)).Cast<ProjectState>())
         {
             <SelectItem TValue="int?" Value="@((int)projectState)">L["Enum:ProjectState." + projectState]</SelectItem>
         }
    }
</Select>


private async Task SearchProjectByStateAsync(int? state)
{
    if (state == -1 || state == null)
    {
        Filter.State = null;
    }
    else
    {
        Filter.State = (ProjectState?)state;
    }
    await SearchAsync();
}
```
