### ISSUE TITLE
TextEdit Plaintext not working in AntDesign BlazorServer 

### ISSUE THREAD

**Issue by Bassist067** [Megabit/Blazorise#2925]
**Describe the bug**
Plaintext attribute disables the TextEdit component

**To Reproduce**
1. Create Blazor Server project
2. Use AntDesign
3. add `<TextEdit Placeholder="Template Name" Plaintext="true" />`

```
<TextEdit Placeholder="Template Name" Plaintext="true" />

<Row>
    <Column>
        <DataGrid TItem="TemplatePropertyDTO" Bordered="true" ShowPager="true" Editable="true"
```

**Screenshots**
![image](https://user-images.githubusercontent.com/19996164/133611550-4fc0d321-13a0-4bd9-98c8-dc0f8ba90811.png)

**Comment by stsrki** [comment]
`Plaintext` parameter is supposed to make TextEdit readonly. See this for example https://getbootstrap.com/docs/4.0/components/forms/#readonly-plain-text

AntDesign doesn't have a similar native feature so when `Plaintext` is enabled we replace input with span while the class names stay the same. But the behavior in both frameworks is still valid.

**Comment by Bassist067** [comment]
Understood. Thanks for clarification, closing the issue. I was searching for some quick inline text edit control, so Plaintext produced the right markup.

Thanks again - Blazorise is the sweetest thing I've used for a long time.

**Comment by stsrki** [comment]
No problem. Thank you :)
