### ISSUE TITLE
Can't toggle Disabled status of DataGrid buttons (change from 9.3.10 to 9.4.0, repro available)

### ISSUE THREAD

**Issue by robalexclark** [Megabit/Blazorise#2930]
In 9.3.10 I could have the disabled status of the New button on a datagrid set dynamically:
```

 <DataGridCommandColumn ElementId="AllocationsGrid-DataGridCommandColumn-0" TItem="Allocation" Width="125px">
        <NewCommandTemplate>
            <Button ElementId="AllocationsGrid-Button-0" Color="Color.Success" Clicked="@((e) => NewAllocation())" Disabled="@NewAllocationDisabled" Class="btn-sm">New</Button>
        </NewCommandTemplate>
.......

  private bool NewAllocationDisabled //determine if the new allocation button is disabled
        {
            get
            {
                if (allocations != null && allocations.Any(x => x.DateProcsCommenced.HasValue && x.DateOfFate.HasValue == false)) 
                {
                    return true; //is disabled
                }
                else
                {
                    return false; //is enabled
                }
            }
        }
```

I tracked down that this no longer works in 9.4.x. I already tried setting StateHasChanged() everywhere! :-) 

I have a repro for you at
https://github.com/robalexclark/BlazoriseDisabledButtonBug 

Currently its setup with 9.3.10 and the New button disabled state can be toggled with the button, but change to 9.4.0 and the Disabled state is ignored.

pls fix and thx!

**Comment by David-Moreira** [comment]
@robalexclark thank you for providing the repository. We really appreciate it, it is indeed a bug, the column should know to refresh itself.
