### ISSUE TITLE
Enhanced Multiselect

### ISSUE THREAD

**Issue by DDDenisSobek** [Megabit/Blazorise#2931]
**Is your feature request related to a problem? Please describe.**
An user should search for and select x items. After one selection of an item seletion should not be closed, so that user can select other item with actual search result without opening selection or searching again. An user should deselect one selected item.

**Describe the solution you'd like**
Like the [Typeahead of LoreSoft](https://blazor.loresoft.com/typeahead/index), but with the enhancement, that the selection template does not be closed after a selection.

**Comment by stsrki** [comment]
We already have it planned for this milestone #2528

**Comment by DDDenisSobek** [comment]
Oh, sorry for that dublicate. :)
