### ISSUE TITLE
Active color on Bar item

### ISSUE THREAD

**Issue by TorbjornEliasson** [Megabit/Blazorise#2937]
Is it possible to change the background color for the active item in a bar?

Regards,
Torbjörn

**Comment by stsrki** [comment]
if you're using Blazorise theming then it is easy to change

```diff
protected Theme Theme = new Theme
{
    ColorOptions = new ThemeColorOptions
    {
        Primary = "#7178c7",
        Secondary = "#6c757d",
        Success = "#19bf90",
        Danger = "#e86d86",
        Warning = "#ffbc00",
        Info = "#39afd1",
        Light = "#eef2f7",
        Dark = "#313a46"
    },
    BackgroundOptions = new ThemeBackgroundOptions
    {
        Primary = "#7178c7",
        Secondary = "#6c757d",
        Success = "#19bf90",
        Danger = "#e86d86",
        Warning = "#ffbc00",
        Info = "#39afd1",
        Light = "#eef2f7",
        Dark = "#313a46"
    },
    TextColorOptions = new ThemeTextColorOptions
    {
        Primary = "#7178c7",
        Secondary = "#6c757d",
        Success = "#19bf90",
        Danger = "#e86d86",
        Warning = "#ffbc00",
        Info = "#39afd1",
        Light = "#eef2f7",
        Dark = "#313a46",
        Body = "#6c757d",
    },
    BarOptions = new ThemeBarOptions
    {
        HorizontalHeight = "72px",
        VerticalWidth = "260px",
        DarkColors = new()
        {
            BackgroundColor = "#313a46",
            DropdownColorOptions = new()
            {
                BackgroundColor = "#313a46",
            },
            ItemColorOptions = new()
            {
+                ActiveBackgroundColor = "#313a46",
+                ActiveColor = "#ffffff",
                HoverBackgroundColor = "#222830",
                HoverColor = "#bccee4",
            },
            Color = "#8391a2",
        }
    },
};
```

Otherwise you can only change with custom CSS selectors.

**Comment by TorbjornEliasson** [comment]
Perfect, that works great!

Is there also a way for changing color on the Collapse button in Bar component. It has the ordinary Link color for Material. Like this: 
![image](https://user-images.githubusercontent.com/71641056/133989907-ea4b6687-e3b2-4cd9-90f1-46e8b20ebabf.png)

Or is this related to the problem described in https://github.com/Megabit/Blazorise/issues/2913?

**Comment by stsrki** [comment]
It seems we don't have any theme options for the toggle button. We can try adding it for one of the next milestones.

For now, you can override it with the CSS selector.

**Comment by danielheddelin** [comment]
@stsrki Could it be the same problem with 'active' on nav-link as well? Here in a tab:
![image](https://user-images.githubusercontent.com/2387854/135230292-0d423cd7-a781-4a20-86db-88a126678839.png)

But also here, on a Checked Radio button in a RadioGroup:
![image](https://user-images.githubusercontent.com/2387854/135230800-8b22c084-0f82-4ca6-a5a2-dffd4473b5f3.png)

**Comment by stsrki** [comment]
Closing since the original problem was solved.
