### ISSUE TITLE
.Net 6: register all components as web elements

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#2952]
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-rc-1/#blazor-custom-elements

**Comment by David-Moreira** [comment]
I saw a demo of this a few days ago. I think it leverages code generation, and I think our users can register themselves if they want to use it. No need to generate all this boiler plate in my opinion.

Also on the presentation I saw, I believe Daniel Roth said this was experimental and would not be part of the oficial release.

**Comment by stsrki** [comment]
> Also on the presentation I saw, I believe Daniel Roth said this was experimental and would not be part of the oficial release.

Hmm didn't know this. But why would they make it part or RC1 if they will not release it?

**Comment by David-Moreira** [comment]
I guess they are experimenting... Also I don't think its part of the net 6 assemblies, its a nuget package.

**Comment by njannink** [comment]
You could provide a helper method for users to have the custom elements registered. So users who want to do this can use it. But you probably need to add some prefix to not override users own registrations.

    options.RegisterBlazoriseCustomElements(prefix: "bz");

**Comment by David-Moreira** [comment]
Hello as mentioned, I doubt its part of the oficial release.
Howveer this one 
"Render Blazor components from Javascript"
We could support as per @njannink suggestion.
