### ISSUE TITLE
There is no `staticwebassets` folder in `0.9.5-preview2` version.

### ISSUE THREAD

**Issue by maliming** [Megabit/Blazorise#2958]
hi

Is this a breaking change or a bug?

![1632315295](https://user-images.githubusercontent.com/6908465/134347296-88f9ba3a-2d9b-4172-9c44-ed2e7a17624e.jpg)

**Comment by stsrki** [comment]
I was able to do some workarounds to include the `staticwebassets ` folder. They are now published as **0.9.5-preview2.1** so please try updating your projects.

I have also reported an issue on the aspnetcore repo as a possible SDK bug.

**Comment by jmoerdyk** [comment]
Thanks for that, I have at least the skeleton of a net6.0 Blazor Server app building and running now.
