### ISSUE TITLE
In the Tab control, how can I use same content for the TabPanel with different category?

### ISSUE THREAD

**Issue by ScriptBox99** [Megabit/Blazorise#2966]
Hello dear Blazorize and community members.

I would like to apply Tab control with same content for the TabPanel but with different category.
That mean, only logic and other controls and elements are same but by category to display filtering the list.
How can I try like that with Tab control:
```html
<Tabs> 
  <Items>
     <Tab Name="all">All</Tab>
     <Tab Name="category1">Category1</Tab>
    <Tab Name="category2">Category2</Tab>
  </Items>
  <Content>
     <TabPanel Name="all">
     </TabPanel>
     <TabPanel Name="category1">
     </TabPanel>
     <TabPanel Name="category2">
     </TabPanel>
    </Content>
</Tabs>
```
Should I paste same tag elements into the each TabPanel to do ?
Thanks.

**Comment by stsrki** [comment]
I'm not sure if I understood correctly? Do you want to have the same content on two different panels? If so, then it is best to create a separate component that will contain the content you want and then just place it inside of TabPanel's.

```cshtml
<Tabs> 
  <Items>
     <Tab Name="all">All</Tab>
     <Tab Name="category1">Category1</Tab>
    <Tab Name="category2">Category2</Tab>
  </Items>
  <Content>
     <TabPanel Name="all">
     </TabPanel>
     <TabPanel Name="category1">
       <YourCustomComponent />
     </TabPanel>
     <TabPanel Name="category2">
       <YourCustomComponent />
     </TabPanel>
    </Content>
</Tabs>
```

**Comment by David-Moreira** [comment]
You can also inline render fragments as reusable fields so you don't incur the cost of a whole component if you don't need it.

**Comment by David-Moreira** [comment]
> You can also inline render fragments as reusable fields so you don't incur the cost of a whole component if you don't need it.

Example 
```
<Tabs> 
  <Items>
     <Tab Name="all">All</Tab>
     <Tab Name="category1">Category1</Tab>
    <Tab Name="category2">Category2</Tab>
  </Items>
  <Content>
     <TabPanel Name="all">
     </TabPanel>
     <TabPanel Name="category1">
       @example
     </TabPanel>
     <TabPanel Name="category2">
       @example
     </TabPanel>
    </Content>
</Tabs>

@code{
    private RenderFragment example = @<div>Reusing fragment</div>;
}
```

**Comment by David-Moreira** [comment]
@ScriptBox99 were you able to figure this out? :)
