### ISSUE TITLE
Could not find 'blazoriseCharts.initialize' ('blazoriseCharts' was undefined).

### ISSUE THREAD

**Issue by JezPops** [Megabit/Blazorise#2976]
Updating to any 0.9.4 versions causes blazoriseCharts undefined error. BOTH on wasm and server. 
Updating to ALL others before 9.4 causes no issue. (Can upgrade and downgrade all day long with anything before 0.9.4)

**To Reproduce**
Create new project. either wasm or server.
Install all Blazorise Nuget packages through vs 2019.
Add references to hosts or index.
Create a single page with the code for a line chart as provided here https://blazorise.com/docs/extensions/chart/

WASM: 
Unhandled exception rendering component: Could not find 'blazoriseCharts.initialize' ('blazoriseCharts' was undefined).
Error: Could not find 'blazoriseCharts.initialize' ('blazoriseCharts' was undefined).
    at https://localhost:44359/_framework/blazor.webassembly.js:1:1287

SERVER:
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: Could not find 'blazoriseCharts.initialize' ('blazoriseCharts' was undefined).
Error: Could not find 'blazoriseCharts.initialize' ('blazoriseCharts' was undefined).
    at https://localhost:44370/_framework/blazor.server.js:1:67714

**Expected behavior**
The charts should render as they do in the demo. Why the update has broken everything is not clear. 
I am adding 0.9.4.4 at the end of the js and css files.
I have all them in the order of the demo.

simplified heavily commented version here (you can comment out the data connections in app razor)
https://github.com/JezPops/IIS-V4

**Comment by stsrki** [comment]
Hi, sorry for not getting sooner to you.

I've tried your project but I am unable to run it. Probably missing some configuration or DB settings. In any case, did you try clearing the cache with Ctrl+F5? The error usually happened when you have older JS file cached by the browser.

It is a good approach to always add a version when defining JS static content. eg `<script src="_content/Blazorise/blazorise.js?v=0.9.4.4"></script>`.

Closing now, if the error persists please reopen.

**Comment by JezPops** [comment]
Hi mate
Figured out what the problem is when updating from 9.3 to anything above.
Its actually the razor code:
<PieChart @ref="profitPie" Type="ChartType.Pie" TItem="double"
***@***.***/>

If I update and remove the  OptionsObject  it runs. But how do I now get at
those options?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
