### ISSUE TITLE
Support for Offcanvas in BS5

### ISSUE THREAD

**Issue by jasonhill** [Megabit/Blazorise#2989]
Just wondering if there are plans to support the new Offcanvas sidebar component in Bootstrap 5.

**Comment by stsrki** [comment]
We might consider it if there is enough time in the current milestone. Seems like a rather non-complicated component to have but as always it can be a nightmare in disguise. :)

**Comment by jasonhill** [comment]
Awesome, thanks. Yes, the devil is always in the detail!

**Comment by WillianGruber** [comment]
I'd love to use that component

**Comment by stsrki** [comment]
Postponed until v1.1 since we're now focused to finish v1.0 and clean the API.

**Comment by f4n0** [comment]
Hi, sorry to bother!
Is there any ETA?

**Comment by stsrki** [comment]
We are going to do it in the 1.3. The current milestone is already done, and we're closing the last few tickets.
