### ISSUE TITLE
Hover effect doesn't work on DataGrid

### ISSUE THREAD

**Issue by enisn** [Megabit/Blazorise#2990]
When **Hoverable** is set as `true`, nothing happens on UI

```cshtml
<DataGrid TItem="AwesomeDto"
                  Data="AwesomeList"
                  ReadData="OnDataGridReadAsync"
                  TotalItems="TotalCount"
                  Hoverable="true"
                  ShowPager="true"
                  Responsive="true"
                  PageSize="PageSize">
           <!-- ...  -->
</DataGrid>
```
Nothing happens while hovering with mouse:
![image](https://user-images.githubusercontent.com/23705418/135962664-b612314a-e13c-49ef-bdad-e80e8f7da6c5.png)

**Comment by stsrki** [comment]
Seems to me like the ABP theme could be overriding bootstrap classes. Can you check in dev tools to see what might cause it?
