### ISSUE TITLE
JS Interlop error on page refresh with blazorise controls ( blazorise 0.9.4.6 on net 6 rc 1 )

### ISSUE THREAD

**Issue by killerobi13** [Megabit/Blazorise#2994]
**Describe the bug**
I get the following error on page refresh if I use blazorise button on 0.9.4.6 on net 6 rc 1 : "Unhandled exception rendering component: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed."

**To Reproduce**
1. New project.
2. Add blazorise button or text edit.
3. Refresh page from browser

**Expected behavior**
1. Clean Refresh

**Screenshots**
![image](https://user-images.githubusercontent.com/58951712/136035734-6f192263-a001-4cdb-a51e-e47d815a1f31.png)

**Comment by stsrki** [comment]
Sorry for the inconvenience.
 
It is already fixed with #2944. The fix will be available in 0.9.4.7.
