### ISSUE TITLE
BUG: <Check/> : Tristate / Indeterminate functionality doesn't work as expected

### ISSUE THREAD

**Issue by GordonRudman** [Megabit/Blazorise#3003]
**Describe the bug**
Thank you so much for adding the Tri-state /  three-state / Indeterminate-state functionality (whatever you want to call it), this is exactly what I need for my application! Unfortunately it doesn't work as one would expect.

**To Reproduce**
Here's some example code:
Example 1:
`<Check TValue="bool?"/>`

Example 2:
`<Check TValue="bool?" Indeterminate=true/>`

Example 3:
`<Check TValue="bool?" @bind-Checked="@checked" Indeterminate=true/>`
private bool? checked;

Example 4:
`<Check TValue="bool"/>`   - This is just a little ugly

**Expected behavior**
In examples 1, 2 & 3 I would expect the control to cycle through the following states as the user clicks on the control:
1. Unchecked
2. Intermediate state / half-checked
3. Checked
Repeat

At the moment it basically only does the following unless you bind a 2nd variable to the Indeterminate property and manage the state yourself (which kind of defeats the point of having a control):
1. Unchecked
2. Checked
Repeat
It never goes back to half-checked by itself.

In example 3:
If TValue="bool?" or  Indeterminate=true then I would expect the control to get it's indeterminate value from the variable it is bound to using @bind-Checked. I shouldn't need a second variable to represent the third state as that should be inferred from the null value. So that also means the Indeterminate property isn't actually necessary at all, because you could figure out that we want Tri-state functionality just because we're using TValue="bool?"

**Additional context**
Something else I found strange/slightly annoying is that I'm forced to using < Check TValue="bool" /> to create a normal checkbox, which isn't expected (but understandable because of the tri-state logic).

So I have a suggestion:
How about just having 2 separate controls (because they will be used in different types of scenarios): 
1. The standard (and clean) < Check/ > for standard checked/unchecked logic only.
2. A separate < TristateCheck /> or < IntermediateCheck /> control with the more advanced tri-state / intermediate-state logic.
That means we could completely get rid of the less than desirable TValue="bool" and TValue="bool?" stuff everywhere.

Many thanks again for implementing this.

**Comment by GordonRudman** [comment]
I changed the Markdown a little so that the text is rendered correctly

**Comment by David-Moreira** [comment]
For future reference, You can just wrap those as code tags, like I did for your examples above.
`<Example Code> blabla </ExampleCode>`
![image](https://user-images.githubusercontent.com/22283161/136668160-d65a2225-5cbe-40ac-a786-b2fef4cf21cb.png)

**Comment by GordonRudman** [comment]
Thanks :-)

**Comment by GordonRudman** [comment]
Hi @stsrki , what was the resolution to this issue?
Thanks

**Comment by stsrki** [comment]
Hi @GordonRudman 

There is no resolution, unfortunately. The `Check` is working as expected, and it was never meant to toggle between checked/unchecked/indeterminate state. An Indeterminate is used only as a flag to tell the browser that the checkbox can be rendered differently. It is by the design https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#attr-indeterminate

**Comment by GordonRudman** [comment]
Ah, OK. 
I guess I'll need to create my own controls on top of this one then, I was hoping to avoid that, and I'm guessing a lot of other people will also need to do the same. If I get the time to do it I'll try post the code here, and you can decide if you want include it in the library or not - no pressure.
