### ISSUE TITLE
TextEdit slow after loading DataGrid

### ISSUE THREAD

**Issue by rcordeiro03** [Megabit/Blazorise#3023]
Hello,

I'm using a TextEdit and on the Keypress event after the user hit "Enter", I'm loading the DataGrid, for some reason after the DataGrid has been loaded, except for very few items, the issue start at about 5 records, all TextEdits become very slow to type, more than 1 sec. 

I'm using version 0.9.4.6

**Comment by stsrki** [comment]
I'm trying to reproduce it but it works on my side. No slowing down. Can you create a small project where we can test and reproduce the issue?

**Comment by David-Moreira** [comment]
Hello @rcordeiro03 
You're right it gets quite slow. Unfortunately that's a known issue with issuing updates on every key stroke. And with the addition of the `DataGrid` to the page that also does some work when it detects updates, it can be heavy.

I suggest that you either tinker with our `DelayTextOnKeyPress` setting or set `ChangeTextOnKeyPress` to `false` if you don't plan on using the feature. You may set it globally by using the global options on your program.cs registration `builder.Services.AddBlazorise(options => { options.ChangeTextOnKeyPress = false; })`
or as a `Parameter` on the `TextField` itself.

**Docs:** https://blazorise.com/docs/components/text

**Comment by stsrki** [comment]
I agree with @David-Moreira. Making use of `DelayTextOnKeyPress` or disabling the `ChangeTextOnKeyPress` is the best option as there is no other way to prevent Blazor to stop re-rendering the page.
