### ISSUE TITLE
Default PageSize when ShowPageSizes = true on the Datagrid

### ISSUE THREAD

**Issue by GilShalit** [Megabit/Blazorise#3026]
I don't see a way to specify a PageSize > 5 on startup when using the PageSize selector for the DataGrid.

Am I missing something?

**Comment by stsrki** [comment]
How do you assign the PageSize? I have just tried it and it worked.

**Comment by GilShalit** [comment]
am I supposed to have a PageSize="@myPageSize" parameter on the datagrid?  If I do that and initialize myPageSize to 20, I get the following 
![image](https://user-images.githubusercontent.com/34002589/137587725-ca6b8b89-f261-46f3-a9cb-cac0ce26d1f8.png)
