### ISSUE TITLE
Chart axis max and min

### ISSUE THREAD

**Issue by erikthysell** [Megabit/Blazorise#3032]
I would like to have the possibility to set axis max and min (and have it stay / not change on data changes).

It could be something along the line of:
`await lineChart.SetOptions(new LineChartOptions() { Scales=new Scales() { YAxes = new List<Axis> { new Axis() { Max = 51.2, Min = 19.5 } } } })`

I can see that the option exists in Chart.js so perhaps it is not a huge undertaking.

**Comment by stsrki** [comment]
It shouldn't be a problem. Until we add it you can always use the `OptionsObject`.

```
object options = new
{
    Scales = new
    {
        YAxes = new object[]
        {
            new
            {
                Max = 51.2,
                Min = 19.5,
            }
        }
    }
};

await lineChart.SetOptionsObject(options);
```
