### ISSUE TITLE
Cannot create a "ValidationsStatusChangedEventHandler"

### ISSUE THREAD

**Issue by emiliojoseav** [Megabit/Blazorise#3059]
Hi I'm using Blazorise 0.9.3.10 and working with Validations in a component.
Once I have the validation result, I have to invoke an **ValidationsStatusChangedEventHandler**
    ` ValidationSucceeded?.Invoke(new ValidationsStatusChangedEventHandler(arguments ...));`

If I'm not wrong, "**ValidationsStatusChangedEventHandler**" has as argument a "**ValidationsStatusChangedEventArgs**", and this has 2 args:
    -> **ValidationStatus Status**
    -> **IReadOnlyCollection<string> Messages**

So, I create the event with those 2 args
```
IReadOnlyCollection<string> readOnlyResults = new List<string>() { (String)args.Value };
ValidationSucceeded?.Invoke(new ValidationsStatusChangedEventHandler(new ValidationsStatusChangedEventArgs(args.Status, readOnlyResults)));
```

But VisualStudio prompt me this error: **Method name expected**

I tried to instead of create a "new ValidationsStatusChangedEventArgs", create a method that returns it, and write the method name:
```
static ValidationsStatusChangedEventArgs GetValidationsStatusChangedEventArgs(ValidatorEventArgs args)
                        {
                            IReadOnlyCollection<string> readOnlyResults = new List<string>() { (String)args.Value };
                            return new ValidationsStatusChangedEventArgs(args.Status, readOnlyResults);
                        };
ValidationSucceeded?.Invoke(new ValidationsStatusChangedEventHandler(GetValidationsStatusChangedEventArgs));
```

But I have another error: **No overload for GetValidationsStatusChangedEventArgs matches delegate ValidationsStatusChangedEventHandler**

So, I do not know if Blazorise has a bug, and is not able to create the event ValidationsStatusChangedEventHandler, or I'm doing it wrong.

Thank you!
Best regards, Emilio.

**Comment by emiliojoseav** [comment]
Hi, validations are working fine
Thank you!!

**Comment by stsrki** [comment]
Great. Closing now.

**Comment by emiliojoseav** [comment]
Hi Stsrki, you told me that I will have some problems with validations in Blazorise 0.9.5.0, because now validations are async, and you are right!

I migrated to Blazorsie 0.9.4.7 and everything was fine. 
But now, I'm migrating to **Blazorise 0.9.5.0 and netCore6**, and I have errors like "**Cannot convert implicity Task<bool> to bool**"
Also, VisualStudio2022 do not recognize "**ValidatingAllEventArgs**" and "**ValidatingAllEventHandler**"

The following code was working fine under Blazorise0.9.4.7
Any Idea how can I convert it to Blazorise0.9.5.0??

```
            private bool TryValidateAll()
            {
                var validated = true;

                var handler = ValidatingAll;

                if (handler != null)
                {
                    var args = new ValidatingAllEventArgs(false);

                    foreach (ValidatingAllEventHandler subHandler in handler?.GetInvocationList())
                    {
                        subHandler(args);

                        if (args.Cancel)
                        {
                            validated = false;
                        }
                    }
                }

                return validated;
            }
```

Thank you in advance, your help is greatly appreciated.
Best regards, Emilio.

**Comment by stsrki** [comment]
Well, to start remove all mention `ValidatingAll*`. We have removed them from the validation as they were not used anymore. Then convert all `void MethodName` to `Task MethodName` where needed.

**Comment by emiliojoseav** [comment]
Are you saying that I have to remove ValidatingAllEventArgs, and ValidatingAllEventHandler?
but wich are the alternatives of them?
Because, now my code depends of them.

Thank you.

**Comment by stsrki** [comment]
I think the best option at this stage is that you re-introduce those types back. Since you are already overriding our classes you have full control over them. You can copy them from https://github.com/Megabit/Blazorise/tree/rel-0.9.4/Source/Blazorise under EventHandlers and EventArguments folders.

**Comment by emiliojoseav** [comment]
Good idea Strski, thanks for the tip!

Best,
Emilio.

**Comment by emiliojoseav** [comment]
One important question about using 0.9.4 source code
¿Can I use the full source code of this release?
You have to know that our app has commercial purposes

Thank you.

**Comment by stsrki** [comment]
Yes, you can. If your company is:

- over than $1M in annual revenue, it is considered a Large Entity and they need to purchase a license.
- if it is less than $1M it is considered as a Small Entity and falls to the Community version, and licensing is not required.

In both ways, it is allowed to be used commercially.

**Comment by emiliojoseav** [comment]
That's a important matter that I have to talk with my team.

¿Is there any way to check the code from 0.93 releases or previous?

Sorry, but I only have seen in [GitHub ](https://github.com/Megabit/Blazorise)the source code of 0.9.4 and 0.9.5 releases
Just to check if I can find better solutions for our custom types in those release.

Best,
Emilio.

**Comment by stsrki** [comment]
> ¿Is there any way to check the code from 0.9.3 releases or previous?

Unfortunately no. We removed older branches because we don't plan to support than anymore.

**Comment by emiliojoseav** [comment]
Ok strski, no worries, in any case your are being in a great help
Thank you
