### ISSUE TITLE
📣 Who is using Blazorise? 🔍

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#3063]
We would like to know how and where is Blazorise used to learn more about our users. If you or your company is using Blazorise for a public or internal application, we would like to showcase it on our website.

- Product/Name/Title
- Description
- Screenshot
- Link (optional)

_Please note that for the website we will pick the ones that stick out, but feel free to show it off here anyway._

**Comment by Jinjinov** [comment]
# ididit!

Progressive Web Application that tracks when was the last time you did something.

https://github.com/Jinjinov/TheLastTime

https://ididit.today/

![ididit](https://user-images.githubusercontent.com/20396198/140494932-c71df570-6f1c-4668-94e0-b66be74f9c4e.png)

**Comment by itsLollo1000** [comment]
> Product/Name/Title : MoveIT DSM Manger
> Description : Software/Computer management tool, server side based.
> State : still in development, started in Novemeber 2021

![DSMManager2](https://user-images.githubusercontent.com/10349466/141287069-4471c250-f9d0-4134-b610-521f853d3933.png)
![DSMManager1](https://user-images.githubusercontent.com/10349466/141287494-b64e2797-eab4-4379-9859-add58b99efa1.png)
![DSMManager3](https://user-images.githubusercontent.com/10349466/141307983-61561e01-aa12-4025-a73b-a127df4a0902.png)
![DSMManager4](https://user-images.githubusercontent.com/10349466/141287732-1dc39806-5644-4aaf-b45d-b2f4b7d63c28.png)

**Comment by dkonstantinov193** [comment]
Product/Name/Title: Venando
Description: VK social network parsing tool
Screenshot: ![image](https://user-images.githubusercontent.com/71480348/145710370-3c0bdf39-e885-4bcc-a624-05ae90688ad4.png)
Link: https://app.venando.ru

**Comment by edgarssults** [comment]
Name: Bannerboard
Description: A mod for Mount & Blade II: Bannerlord that lets players view game data in real time on a dashboard in a browser
Site: https://github.com/edgarssults/Bannerboard

![image](https://user-images.githubusercontent.com/8101338/147879805-ee7e1732-491d-4cf1-80c6-d42f13d8a096.png)

**Comment by janseris** [comment]
dev phase of online doctor registration instead of custom Bootstrap 5 Blazor components which took eternity to implement
![image](https://user-images.githubusercontent.com/64279914/148849181-f05f7262-6a08-43bf-a689-f3a5d1668ba5.png)

**Comment by Jinjinov** [comment]
ididit! - Take notes, manage tasks, track habits.

https://ididit.today/

https://github.com/Jinjinov/Ididit

I abandoned the previous version https://github.com/Jinjinov/TheLastTime and wrote the new one completely from scratch

![superhero](https://user-images.githubusercontent.com/20396198/183245565-8bffdc21-5035-4009-8df4-defae641baf0.png)

**Comment by svenbaus** [comment]
AudioCuesheetEditor

AudioCuesheetEditor is a Blazor based web application for writing audio cuesheets. There is much validation that helps the user to write a valid cuesheet. You can import external data (like text files, xml files, etc.) and analyse them directly in GUI. There are also much export variations like CSV, but you can customize export freely. 

![grafik](https://user-images.githubusercontent.com/86463105/189674853-12151d50-50e2-43b9-b38f-8eea24d36714.png)


https://neocodermatrix86.github.io/AudioCuesheetEditor/

**Comment by stsrki** [comment]
> First I would like to mention that it is very easy to use Blazorise in Blazor applications. We create application for bank dealers.
> 
> Product name - Ameta. Description - dealing application for bank dealers. For backend we used gRPC ASP.NET Core. Link - private project, but I planned to create article how to create a very fast app using use Blazorise and gRPC.

Happy to see the article. Once you write it, we would like it to be featured as a guest blog on our web.

**Comment by GevorDanielyan** [comment]
> > First I would like to mention that it is very easy to use Blazorise in Blazor applications. We create application for bank dealers.
> > Product name - Ameta. Description - dealing application for bank dealers. For backend we used gRPC ASP.NET Core. Link - private project, but I planned to create article how to create a very fast app using use Blazorise and gRPC.
> 
> Happy to see the article. Once you write it, we would like it to be featured as a guest blog on our web.

Definitely, it's just a matter of time․

**Comment by WayneHiller** [comment]
Allied Business Solutions (ABS).
Line of Business app for Equipment Parts Dealers.
This is our premiere product. 

![image](https://github.com/Megabit/Blazorise/assets/1186731/8274a4d4-30b2-4539-9af6-7ad561aaf046)

**Comment by stsrki** [comment]
> Allied Business Solutions (ABS). Line of Business app for Equipment Parts Dealers. This is our premiere product.
> 
> ![image](https://user-images.githubusercontent.com/1186731/265130814-8274a4d4-30b2-4539-9af6-7ad561aaf046.png)

Look really good. I love the color scheme, very easy on the eyes.

**Comment by WayneHiller** [comment]
> > Allied Business Solutions (ABS). Line of Business app for Equipment Parts Dealers. This is our premiere product.
> 
> Look really good. I love the color scheme, very easy on the eyes.

Based on a Bootswatch theme (Darkly) , also have light of course.
