### ISSUE TITLE
Lazy Load Modal Content

### ISSUE THREAD

**Issue by muratyuceer** [Megabit/Blazorise#3068]
Hello, in some case for performance we need to load modal contents when modal showed (lazy).

What is true technic to do that, could you give example

**Comment by stsrki** [comment]
You didn't initialize it. Hence the null error.

`private NotificationList notificationListRef { get; set; } = new NotificationList();`

**Comment by muratyuceer** [comment]
> You didn't initialize it. Hence the null error.
> 
> `private NotificationList notificationListRef { get; set; } = new NotificationList();`

NotificationList is a blazor component (razor) => <NotificationList @ref="notificationListRef" />

**Comment by David-Moreira** [comment]
You have a visible flag set to false. The component isn't rendered therefore there isn't a reference.

**Comment by stsrki** [comment]
`modalRef.Show` is available only in 0.9.5.

**Comment by muratyuceer** [comment]
> You have a visible flag set to false. The component isn't rendered therefore there isn't a reference.

I know, I resolve it like below. If i use 0.9.5 can i fix this problem with await modalRef.Show ??

```
    public async Task OpenModal()
    {
        LoadModalContent = true;
        Modal.Show();
        await InvokeAsync(StateHasChanged);
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (LoadModalContent)
        {
            LoadModalContent = false;
            await NotificationList.LoadList(_filterOptions);
        }
    }
```

**Comment by David-Moreira** [comment]
Yep if it's awaitable you can try, seems like a race condition. Another way to achieve what you want is to move the Load List inside the OnInitialized of the NotificationList itself, since it only initializes once the flag visible is true.

**Comment by stsrki** [comment]
You can try 0.9.5 if you're willing to go preview. We always need more early testers :).

All changes to migrate are documented at https://preview.blazorise.com/news/release-notes/095

**Comment by stsrki** [comment]
PS. https://github.com/Megabit/Blazorise#try-preview

**Comment by muratyuceer** [comment]
> PS. https://github.com/Megabit/Blazorise#try-preview

Current abp version depended older blazorise version. If it doesn't cause any problems i will try..

Thanks

**Comment by stsrki** [comment]
Ahh, you're using ABP. 🤔 I believe they migrated to 0.9.5 preview recently, but I'm not sure if it is already released.

**Comment by muratyuceer** [comment]
> `modalRef.Show` is available only in 0.9.5.

Hello, stsrki
I tried with await but didnt work, do you have solution?

**Comment by stsrki** [comment]
@muratyuceer check your project references if you're using the ABP framework. It's possible that it is still using Blazorise 0.9.5-preview. As far as I know, the new release of ABP is scheduled for mid-December, possibly next week.

**Comment by muratyuceer** [comment]
They use 0.9.5. I see Show method return Task. But even await still its have problem about null reference. Can you try how will you overcome this problem?

**Comment by stsrki** [comment]
Did you set the modal ref? eg `<Modal @ref="@modalRef">`

**Comment by muratyuceer** [comment]
Hello,
I created example project, its contain modal also I add divider its look like wrong
When you click button you will show error
[BlazoriseTest.zip](https://github.com/Megabit/Blazorise/files/7698924/BlazoriseTest.zip)

**Comment by stsrki** [comment]
I have checked your project and the Modal is working fine. The problem is in how Blazor is working. You're rendering `Counter` component behind the `if` statement, meaning unless it is `true`, it will not be created in the DOM. That's why it breaks as soon as you try to access `Counter.Reset()`.

The solution is to call it after Blazor does its stuff and rerenders the page.


```cshtml
<Modal @ref="Modal">
    <ModalContent Size="ModalSize.ExtraLarge">
        <Form>
            <ModalHeader>
                <ModalTitle>Bildirimler</ModalTitle>
                <CloseButton />
            </ModalHeader>
            <ModalBody Class="p-3">
                @if ( ShowModalContentFlag )
                {
                    <Counter @ref="Counter"></Counter>
                }
            </ModalBody>
            <ModalFooter>
                <Button Color="Color.Secondary"
                        Clicked="async () => await Modal.Hide()">
                    Close
                </Button>
            </ModalFooter>
        </Form>
    </ModalContent>
</Modal>


@code {
    Modal Modal;
    Counter Counter;

    bool ShowModalContentFlag;

    protected override async Task OnAfterRenderAsync( bool firstRender )
    {
        // 2. after modal is re-rendered we can assume the Counter ref is now safe to access
        if ( !firstRender && ShowModalContentFlag )
        {
            await Counter.Reset();
        }

        await base.OnAfterRenderAsync( firstRender );
    }

    public async Task Show()
    {
        ShowModalContentFlag = true;
   
        // 1. show the modal which will trigger re-render
        await Modal.Show();
    }
}
```

**Comment by muratyuceer** [comment]
Hello,
Thanks for help. This is the method I used before. I was hopeful because we thought it would be fixed after this feature came. I mean async show..

**Comment by muratyuceer** [comment]
How I use

@using Exchanger.Ewp.Notifications
@inherits ExchangerComponentBase

<Modal @ref="Modal" Closing="@OnModalClosing">
    <ModalContent Size="ModalSize.ExtraLarge">
        <Form id="AgreementFromEwpModal">
            <ModalHeader>
                <ModalTitle>Bildirimler</ModalTitle>
                <CloseButton Clicked="CloseModal" />
            </ModalHeader>
            <ModalBody Class="p-3">
                @if (ShowModalContentFlag)
                {
                    <NotificationList @ref="NotificationListRef" />
                }
            </ModalBody>
            <ModalFooter>
                <Button Color="Color.Secondary"
                        Clicked="CloseModal">
                    @L["Close"]
                </Button>
            </ModalFooter>
        </Form>
    </ModalContent>
</Modal>

@code {
    NotificationList NotificationListRef { get; set; }

    GetNotificationsInput Filter;
    Modal Modal;
    bool ShowModalContentFlag, LoadModalContentFlag;


    public async Task OpenModal(GetNotificationsInput filter = null)
    {
        Filter = filter;
        ShowModalContentFlag = LoadModalContentFlag = true;
        await Modal.Show();
        await InvokeAsync(StateHasChanged);
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (LoadModalContentFlag)
        {
            LoadModalContentFlag = false;
            await NotificationListRef.LoadData(Filter);
        }

        await base.OnAfterRenderAsync(firstRender);
    }

    public async Task CloseModal()
    {
        ShowModalContentFlag = false;
        await Modal.Hide();
    }

    private Task OnModalClosing(ModalClosingEventArgs modalClosingEventArgs)
    {
        if (modalClosingEventArgs.CloseReason != CloseReason.UserClosing)
            modalClosingEventArgs.Cancel = true;
        return Task.CompletedTask;
    }
}

**Comment by stsrki** [comment]
I don't think there is anything to fix here. Blazor works in a declarative way, and in your example, you're mixing declarative with imperative code. In most cases, mixing it will work but in this example, the problem is that you have an `if` statement. So let's break down what happens here.

1. You have a modal that is defined declaratively.
2. The modal is always rendered in the DOM, just its visibility is handled through the `display` attribute.
3. You have `<NotificationList>` defined behind the `if` statement. Only when the `if` statement is `true`, it will be rendered in the DOM tree.

---

Now, what happens when you run the app.

1. You navigate to the page.
2. Modal gets rendered and `@ref` is assigned to the `Modal` variable.
3. `ShowModalContentFlag` is false and `NotificationList` is not rendered. `@ref` is also not assigned to the `NotificationListRef`.
4. You click on the Button and set `ShowModalContentFlag` to true, and show the modal with `Modal.Show()`.
5. Blazor must trigger render.
6. Since `ShowModalContentFlag` is now enabled it will render `NotificationList` and in turn  `@ref` is now assigned to the `NotificationListRef`.

All of this must happen to show the content of `NotificationList`.

---

If you wish you can switch everything to declarative code by adding the parameter to the `NotificationList`, eg `<NotificationList Visible="@visible" />`. That way you don't need to have an `if` statement or call the `Modal.Show()`. The same variable can be used on the modal, `Visible="@visible"` also.

**Comment by muratyuceer** [comment]
I was think, when you convert Modal.Show to async on new version, blazor will rerender dom until next line (await Modal.Show()) and ref will be not null. But i realized that it doesn't work like that. I was trying to tell blazor, run next line after rerender without use OnAfterRenderAsync etc.. to simple.

I will think about <NotificationList Visible="@visible" /> approach
I can like <NotificationList Visible="@Modal.Visible" />
**But I think Modal.Visible value does not sync in the latest version?**

If the page has many components, the number of components becomes important for performance. Blazor server causing delays.

**Comment by stsrki** [comment]
You must set the two-way binding on modal `Visible` to make it update your variable on change, eg. `<Modal @bind-Visible="@visible">`.

**Comment by muratyuceer** [comment]
I update as you said, thanks for help
