### ISSUE TITLE
Autocomplete dropdown in modal dialog closes when scroll bar used (repro available)

### ISSUE THREAD

**Issue by robalexclark** [Megabit/Blazorise#3069]
When an autocomplete is used in a modal dialog and the scroll bar of the autocomplete dropdown is clicked on, the dropdown closes before any selection can be made.

this seems to only be when a dialog is used, otherwise this does not occur.

scroll wheel does work but if trying to use the mouse pointer to scroll down there is a problem.

A repro is available at:
https://github.com/robalexclark/BlazoriseAutocompleteInModalBug

Instructions:
1) Click on Setup-> Colonies
2) Click on Open Picker
3) In the dropdown start searching using  AAA-  to get the dropdown to open.
4) click on the scroll bar with the mouse pointer, the dropdown will close prematurely.

**Comment by David-Moreira** [comment]
Have no idea yet how to fix this, at least without doing too much rework... still thinking....
`TextEdit` calls `OnBlurHandler` when inside `Modal`, but not outside... Dunno if smthg to do with styling....?

Any ideas?

**Comment by David-Moreira** [comment]
Web programming is so fun....
Here's the culprit.... html attribute on modal div: `tabindex="-1"`

Kinda tired for today. I'll investigate what can be done about that tomorrow... In the meantime any toughts about that @stsrki ?

**Comment by stsrki** [comment]
We can remove `tabindex`, but I have no idea if that would have any side effects.

**Comment by MichalCadecky** [comment]
This is happening again (Blazorise 1.0.2, ABP 5.2) and `tabindex=-"1"` is not present on the rendered modal element. @stsrki am I supposed to open a new issue or should this be reopened? Thank you.
