### ISSUE TITLE
DataGrid RowSelectable EventArgs

### ISSUE THREAD

**Issue by xadzax** [Megabit/Blazorise#3092]
Hello, 
We have an application where we are utilizing datagrid with a checkbox (DataGridMultiSelectColumn). We intentionally wanted row selection to be explicit via checkbox by setting :
RowSelectable="@(_=>false)"
When upgrading to 0.9.4.7 from 0.9.3.8 we noticed this breaks the ability to use the checkboxes to select the rows, and therefore nothing is selectable.

**Comment by David-Moreira** [comment]
Hello @xadzax 
In 0.9.4 We changed multi select to function closer to how an actual row click would work, that means that it also evaluates common logic to regular clicks, which at the moment is the `RowSelectable`. Sorry if that means, that it now breaks your app. I don't think this behaviour is wrong and I would mantain it. 
However, maybe we could take a look at allowing the behaviour you mentioned for the next release. 0.9.5 release should be in a couple of days. 

Maybe a MultiSelectRowSelectable Parameter... ?
| RowSelectable | MultiSelectRowSelectable | Click  | MultiSelectClick |
| :---:   | :-: | :-: | :-: |
| True | True | Yes | Yes |
| True | False | Yes | No |
| False | True | No | Yes |
| False | False | No| No |

What do you think @stsrki ?

**Comment by xadzax** [comment]
@David-Moreira,
I like your idea of having a possible MultiSelectRowSelectable parameter... As another argument for having the rows not be selectable other than the check boxes, we have a link in one of our columns which opens up a modal for more info.  When that link is clicked, the row is also selected which is not the behavior we would want. Thanks

**Comment by stsrki** [comment]
Adding another parameter seems like the best way to proceed as the current behavior is working as expected.

I have also another idea. Change the `RowSelectable` attribute and instead of `TItem` have something like `RowSelectableEventArgs` that could have a field like `enum SelectReason { RowClick, CheckClick, etc. }`. That way you can target a specific event and enable or disable it.

**Comment by stsrki** [comment]
@David-Moreira our milestone is basically done. If you want to work on this we have more than enough time until the release on the 15th.
