### ISSUE TITLE
Virtualize Row/Column issue

### ISSUE THREAD

**Issue by samliu319** [Megabit/Blazorise#3095]
I modified the sample code from "BlazoriseCommunityStandup.ECommerce". 

Usually there are a lot of products in the store. However, virtualization technology is not used in the sample code. So I tried to modify as follows.

**CategoryPage.razor**
![image](https://user-images.githubusercontent.com/1710990/140457749-173b4bcc-6e37-4ae7-891a-8aae04d48716.png)

But the virtualized product list is very weird. It flickers when scrolling on the y-axis. And the content of the product is not as expected.

![錄製_2021_11_05_12_34_44_901](https://user-images.githubusercontent.com/1710990/140458722-d4ee8941-32d3-4f4c-b86d-17e1e89e3243.gif)

I don't know if this is the wrong way of using virtualization? Or a bug?

In addition to the ECommerce, I also want to develop a photo album service similar to ig. They have the same large list of photos and need virtualization technology very much. I hope you can develop specialized virtualization components for Blazorise. Thank's a lot.

**Comment by stsrki** [comment]
The `BlazoriseCommunityStandup.ECommerce` app was done in just a couple of days so it is perfectly possible there are some bugs.

Also, Virtualize component works in a way that it calculates the row sizes based on the total number of items in a data list. And it kinda stays static. So if you have anything that dynamically changes, like an image, for example, it can flicker or scroll can jump. I know it is not perfect but it is the best way for now.

Regarding your question about the native Blazorise virtualization component. It is not planned at the moment. Maybe in the future :)
