### ISSUE TITLE
Set MemoEdit height to show all text

### ISSUE THREAD

**Issue by Jinjinov** [Megabit/Blazorise#3096]
**Is your feature request related to a problem? Please describe.**

In `MemoEdit` we can set `Rows` to something like `Text.Count(c => c == '\n') + 1;` to show all lines, but that doesn't work when a line breaks because it is too long.

**Describe the solution you'd like**

Add a `bool` property to `MemoEdit` to show all text (without scrollbar) even when lines are longer than MemoEdit width.

**Comment by stsrki** [comment]
Can you try this approach as a workaround?

https://css-tricks.com/the-cleanest-trick-for-autogrowing-textareas/

**Comment by Jinjinov** [comment]
Oh, a CSS only solution, interesting... unfortunately it won't work when a user switches a theme and font changes. I really don't want to make a workaround for that too...

I found this:

https://stackoverflow.com/questions/2803880/is-there-a-way-to-get-a-textarea-to-stretch-to-fit-its-content-without-using-php

https://stackoverflow.com/questions/17772260/textarea-auto-height

but I would really like it if this was a part of Blazorise :)

**Comment by stsrki** [comment]
We both looked at the same sources :)

I can try to come up with something as we have enough time until release.
