### ISSUE TITLE
PaginationLink does not respect contents

### ISSUE THREAD

**Issue by johnyjp** [Megabit/Blazorise#3099]
Hi, Trying to add Pagination items in a loop, using Blazorise 0.9.4.7

Heres some code to reproduce the problem

        <Pagination>
            @for (int i = 1; i <= 6; i++)
            {
                @i
            <PaginationItem>
                <PaginationLink>
                    @i
                </PaginationLink>
            </PaginationItem>
            }
        </Pagination>

Note that the @i is displayed both outside and inside a PaginationItem and PaginationLink

The output looks like this.

1 7 2 7 3 7 4 7 5 7 6 7

The numbers from outside the PaginationItem display as expected, but those inside the PaginationItem are of the right count (there are 6 of them) but are always 1 more than the maximum. 

eg. if I loop through 1 to 4 the output is

1 5 2 5 3 5 4 
![Capture](https://user-images.githubusercontent.com/1185870/140554237-0e1acaa4-11da-4a0c-ba74-7823421705a1.PNG)
5

**Comment by stsrki** [comment]
This is the famous Blazor issue. You need to save `i` into a tempo variable and use it to render.

```
<Pagination>
      @for (int i = 1; i <= 6; i++)
      {
          var temp = i;

          <PaginationItem>
              <PaginationLink>
                  @temp
              </PaginationLink>
          </PaginationItem>
      }
  </Pagination>
```

**Comment by stsrki** [comment]
@johnyjp Did it help?

**Comment by David-Moreira** [comment]
I guess the silence answers your question... :P 
Closing this as the answer provided should be it.

**Comment by johnyjp** [comment]
Sorry, was away, yes this solved the issue - thank you...
