### ISSUE TITLE
Datagrid: Show All Items (no pager)

### ISSUE THREAD

**Issue by f4n0** [Megabit/Blazorise#3108]
Hi,
I would like to show all the data in the DataGrid without using the Pager, is that possible? 
I've tried to set the page size to 0 but it will show me 0 data 
I've also set ShowPager to false but it will keep paging the data by 5s.

There is some property that I'm missing?

Thanks

**Comment by stsrki** [comment]
Can you try `PageSize="int.Max"`?

**Comment by f4n0** [comment]
yes, it works. 
I think (if it is possible) to add something like "ShowAll" so it is handled that way.
But for now it works

**Comment by stsrki** [comment]
Adding `ShowAll` would add unnecessary noise to the parameters, I think. We already have them too many 😅

Better to leave it as is now, and just define it with `PageSize="int.Max"`.
