### ISSUE TITLE
The question of selecting row by default when loading data in DataGrid

### ISSUE THREAD

**Issue by bestpika** [Megabit/Blazorise#3113]
I specified SelectedRow (using @bind-SelectedRow) in the DataGrid when loading the data and I don't seem to see the row selected after the data is loaded?

```c#
...
    protected override void OnParametersSet()
    {
        base.OnParametersSet();
        selectedRow = Sth.Where(...).SingleOrDefault();
    }
...
```

**Comment by David-Moreira** [comment]
Hello @bestpika 
Maybe you are missing a `StateHasChanged` call?
But we do provide an API for selecting, can you try our provided `Select( TItem item )` API?
Let us know if this helps.

**Comment by bestpika** [comment]
I know what the problem is, if my data is empty at the beginning, even if I put it in later, it won't highlight correctly.
