### ISSUE TITLE
Charts JsonNumberHandlingAttribute 

### ISSUE THREAD

**Issue by angelru** [Megabit/Blazorise#3116]
`JsonNumberHandlingAttribute is only valid on a number or a collection of numbers when applied to a property or field. See member 'Data' on type 'Blazorise.Charts.ChartDataset1[System.String].`

Charts have always worked fine for me, but now I get this error.

**Comment by stsrki** [comment]
What version you're using?

**Comment by angelru** [comment]
0.9.4.8 and .NET 6 with Refit 6.1.15

**Comment by stsrki** [comment]
Yeah, I know what is wrong. I removed that attribute yesterday on the 095 branch.  https://github.com/Megabit/Blazorise/commit/612a1f13fd247da825a39f51da2e0b499b4c1a53

But now that I see it, I should probably do the same on the 094 branch. Or even better use it only for NET5.

**Comment by angelru** [comment]
Sorry, I don't know very well that I have to downgrade all my packages for NET 5?

**Comment by stsrki** [comment]
Yes, for now. Until the issue is fixed.

**Comment by angelru** [comment]
but this is a .NET or Blazorise.Charts bug?

**Comment by stsrki** [comment]
I would say in NET6 they changed something regarding the number serialization.

**Comment by angelru** [comment]
@stsrki 
At the moment I can't go back to .net 5 (I get other errors that I can't solve)
the charts are not compatible with .net 6 or should I wait for 0.9.4.9?

**Comment by stsrki** [comment]
In that case, it's best to wait for 0.9.4.9 or migrate to 0.9.5. Both are going out next week :)

**Comment by stsrki** [comment]
0.9.4.9 is now released.
