### ISSUE TITLE
GroupBy in DataGrid

### ISSUE THREAD

**Issue by mtbayley** [Megabit/Blazorise#3120]
I would like to be able to group by a property in my DataGrid. I don't think there's a way to do this currently.

Something like this:

![image](https://user-images.githubusercontent.com/34929316/141796442-ac089b94-e860-4f19-9c0f-95ba97e66661.png)

**Comment by David-Moreira** [comment]
Unfortunately we don't support this natively and I don't see an easy way to do this with the current DataGrid component.

If you don't plan on using much of the Datagrid's features, It's probably better to build something custom?

However if you do plan to try using some of the Datagrid's feature, like sorting etc...
Maybe you could build a component that loads DataGrid's dynamically for each group of data?

We do have this component planned, which can help you with this type of grouping in the future:
https://github.com/Megabit/Blazorise/issues/2668

**Comment by mtbayley** [comment]
I think PivotGrid would get me what I am looking for. 
For now I just did the grouping outside of the DataGrid, then rendered a new DataGrid for each group.

**Comment by stsrki** [comment]
I think this feature could be possible. When you think about it, a grouped row is just a set it `td`'s with a rowspan = num of columns. So in theory we should be able to put anything on that. I'm looking at other components library for example and they are doing it the same way.

**Comment by stsrki** [comment]
@David-Moreira, this is a TOP priority for the next milestone. If possible, for 1.2. Otherwise 1.3. You can decide.

**Comment by stsrki** [comment]
I'm thinking of the API:

**Proposal**

- `bool Grouping` if true, columns is grouped automatically. The Default value for grouping is the `Field` parameter.
- `Func<TItem, object> GroupBy` custom function the user can use to group the items.
- `bool Groupable` to disable some columns from grouping. This feature can be done in future versions and will be needed when we add drag-drop support for grouping columns
 
**Example**

`<DataGridColumn Field="..." Grouping="true" GroupBy="@(item => item.Country)"`

@David-Moreira thoughts?

**Comment by David-Moreira** [comment]
I kinda had tought this as more of a Datagrid generic feature, where you would define those but at the Datagrid level, I'm wondering if it makes sense at column level?

`<DataGrid Groupable GroupBy="Func">`

**Comment by stsrki** [comment]
If it were at the grid level, how would you know how to visually group data? Making it on a column level is much more flexible.

Having `bool Groupable` on a grid level makes sense, though. That way, grouping can be disabled, and the drop area will hide.

**Comment by David-Moreira** [comment]
> If it were at the grid level, how would you know how to visually group data? Making it on a column level is much more flexible.
> 
> Having `bool Groupable` on a grid level makes sense, though. That way, grouping can be disabled, and the drop area will hide.

I'm not sure I follow. It's the group by Func that tells you how to group the data.
Visually you still display all rows but have them be grouped for example inside a collapsible row that takes all available width?

**Comment by stsrki** [comment]
But what if you need to have multiple levels of grouping?

Example

![image](https://user-images.githubusercontent.com/900302/210550478-8aa29726-b25c-4c4f-929e-4174e4fd1b35.png)

**Comment by David-Moreira** [comment]
Ahhh I gotcha now. I was only thinking in a simple grouping. It could still make sense if you'd allow to provide an array of group by functions. Because if you think about it, you will need at least as much columns as there are groups in that version. 

I guess there are pros and cons to both. But both would be feasible. 
if the 'industry' standard is to do it on columns, I guess we should to.
