### ISSUE TITLE
Documentation menu does not open

### ISSUE THREAD

**Issue by mtbayley** [Megabit/Blazorise#3121]
Documentation menu does not open. Tested on latest versions of Edge and Chrome

https://blazorise.com/docs

![image](https://user-images.githubusercontent.com/34929316/141804856-ce43f23d-172f-48c3-9505-68d0e097ca53.png)

![image](https://user-images.githubusercontent.com/34929316/141805095-e2ebc97d-53a4-43e1-a20e-09d1c807c7b8.png)

**Comment by mtbayley** [comment]
A good problem to have. We're all excited for 0.9.5

**Comment by stsrki** [comment]
Now I need to become DevOps :)
