### ISSUE TITLE
[Enhancement] Change name of tasks

### ISSUE THREAD

**Issue by angelru** [Megabit/Blazorise#3124]
I think it would be nice (maybe for version 1, that's already up to you).
Rename the methods that are tasks to follow conventions/nomenclatures.

Before                                            
`Task Show() `  
                             
 After
 ` Task ShowAsync()`

This helps the readability of the code and we can detect in which methods await can be used.

**Comment by stsrki** [comment]
We actually had an internal discussion regarding this. And we also did a poll on a Gitter forum asking the same question. The general consensus was that if there will be only an asynchronous method then we can omit the `Async` sufix. So we decided just that. And while I agree it is not completely on the standard I find it easier to read this way. And we already have IntelliSense to give us a suggestion, along with the compile warnings if we ever miss to `await` the Task-ed method. So, the plan is to continue with this approach.
