### ISSUE TITLE
ExtractHexDigits high CPU Usage + Time

### ISSUE THREAD

**Issue by itsLollo1000** [Megabit/Blazorise#3133]
Using Theme Provider slows down the whole application. This is caused by ExtractHexDigits being called multiple 1000 times.
Taking up to 3500ms for 2500 calls.

Use the method:
https://github.com/Megabit/Blazorise/blob/e0f1f9a641114705d127ddb6b4d60dac143e60f1/Source/Blazorise/Themes/ThemeGenerator.cs#L1317

Fill it with any hex color string and run it 2500 times in a loop.
This will take arround 2600ms.

2500 runs taking only couple of ms.

Simple fix to reduce the time and usage drasticly:
```
private static Regex isHexDigit = new( "[abcdefABCDEF\\d]+", RegexOptions.Compiled );

    protected static string ExtractHexDigits( string input )
    {
        // remove any characters that are not digits (like #)
        string newnum = "";
        foreach ( char c in input )
        {
            if ( isHexDigit.IsMatch( c.ToString() ) )
                newnum += c.ToString();
        }
        return newnum;
    }
```
Declaring the same regex each time the function is called slows it down.

**Comment by itsLollo1000** [comment]
This bug gets extremely noticable when using a grid with a huge amount of data and switching between pages with different grids.

Shortly tested again. Without static declaration of the regex 50 calls take 91ms. Declaring the regex outside of the method and calling it 10.000 times only takes 42ms.

**Comment by David-Moreira** [comment]
Nice catch, thanks for troubleshooting.
Regex should generally be cached in hot paths, yes. We'll benchmark and take a look! Thanks!

**Comment by itsLollo1000** [comment]
Sure no problem! 
Also I was a bit curious what the real profit of this function is?
Basically it clears the string to be a hex string but why is it needed?

**Comment by stsrki** [comment]
It is used just as an extra step to make sure the end string contains a valid value that can be converted to the real `Color`.

**Comment by itsLollo1000** [comment]
Hm okay we have also thought that. So it is kind of much needed? Otherwise I would have just removed it :rofl:

**Comment by stsrki** [comment]
I would leave. You have no idea what users could try to enter :)

**Comment by itsLollo1000** [comment]
Fair enough haha :rofl:
