### ISSUE TITLE
Close button for Alerts no longer aligned right in Bootstrap5 provider

### ISSUE THREAD

**Issue by mtbayley** [Megabit/Blazorise#3146]
Bootstrap 4
![image](https://user-images.githubusercontent.com/34929316/142694845-97a81718-9092-4ad6-ae67-fa8e6171c914.png)

Bootstrap 5
![image](https://user-images.githubusercontent.com/34929316/142694968-ff75a920-1ef9-47de-aa1d-c43147dff3a2.png)

I think it looks a little cluttered when the 'X' is right at the end.

**Comment by stsrki** [comment]
Note for me. Alert is missing `alert-dismissible` class.

**Comment by stsrki** [comment]
I have checked this now and it is already fixed. Closing now.
