### ISSUE TITLE
In .NET 6 the .js resources not generated at Publish

### ISSUE THREAD

**Issue by thepra** [Megabit/Blazorise#3148]
**Describe the bug**
As in the following picture this 2 js files no longer appear at Publish of the solution:
![immagine](https://user-images.githubusercontent.com/7032509/142738966-8839b100-21de-4433-a207-54e7a567abd5.png)

**To Reproduce**
1. Upgrade the solution to .NET 6
2. Publish
3. See the absence of those files

**Expected behavior**
Those files should be published

**Comment by stsrki** [comment]
The files you mention are obsolete, starting from the 0.9.5 release. They are replaced with JS modules that are loaded dynamically when needed. You can see it in our release notes https://blazorise.com/news/release-notes/095

**Comment by thepra** [comment]
Ok, here's the deal with dynamically loaded modules:
great from a technical point of view because they post-pone the loading of extra code making the first time loading a little bit faster, **BUT**, and this is a big, real world **BUT**, they **break** the every WebApp(PWA) with offline capability in real world scenarios.

How? Here's a step by step UX example:
1) A user lands on an offline capable Blazor WebApp through their usual browser
2) The user starts interacting with the WebApp without reaching yet any page/component that does use the library components/DI
3) Suddenly the user doesn't have any internet connection, but it's not a problem, the WebApp has cached so far what it does need to resolve `*.js` libraries from the cache
4) (offline) The user reaches a part of the WebApp that does rely on the library that does dynamically load js modules
5) (offline) The WebApp breaks, **DI is broken**, **components break everywhere**, the offline experience is broken and the user leaves the WebApp unhappy

Did you spot the issue? In the end, no cache == no working WebApp when offline

[This](https://github.com/Megabit/Blazorise/blob/master/Source/Blazorise/Modules/BaseJSModule.cs) kind of loading is the issue and [here](https://blog.thepra.dev/please-stop-runtime-loading-libraries/) is my mini rant because this is not the first Blazor library that does rely on this technique, which makes the development of Blazor WebApps more annoying for developers and breaking for the users if not taken care.

Please, if you can, reconsider dynamically loading anything at all.

**Comment by David-Moreira** [comment]
Hello,
We understand your problem, let's try to address it. :)

So if you have this use case... and I'd have to do some testing, but I think you can still cache our js by explicitly calling them as resources?
Would be cool if you could test it, otherwise I'll let you know once we have tested it.

**Comment by thepra** [comment]
@David-Moreira In the same blog post I did found a workaround, which was to [search](https://github.com/Megabit/Blazorise/search?q=ModuleFileName) around the open-source library all the modules strings and add the sources to the `index.html`, example:
```js
/* <other usual js inclusions...> */

/* BASE */
<script src="_content/Blazorise/io.js" type="module">
<script src="_content/Blazorise/closable.js" type="module">
<script src="_content/Blazorise/button.js" type="module">
<script src="_content/Blazorise/textEdit.js" type="module">
<script src="_content/Blazorise/breakpoint.js" type="module">
<script src="_content/Blazorise/memoEdit.js" type="module">
<script src="_content/Blazorise/numericEdit.js" type="module">
<script src="_content/Blazorise/inputMask.js" type="module">
<script src="_content/Blazorise/select.js" type="module">
<script src="_content/Blazorise/fileEdit.js" type="module">
<script src="_content/Blazorise/table.js" type="module">
<script src="_content/Blazorise/colorPicker.js" type="module">
<script src="_content/Blazorise/datePicker.js" type="module">
<script src="_content/Blazorise/timePicker.js" type="module">
<script src="_content/Blazorise/utilities.js" type="module">

/* FRAMEWORKS/EXTENSIONS, pick and choose */
<script src="_content/Blazorise.Bootstrap/modal.js" type="module">
<script src="_content/Blazorise.Bootstrap/tooltip.js" type="module">

<script src="_content/Blazorise.Bootstrap5/modal.js" type="module">
<script src="_content/Blazorise.Bootstrap5/tooltip.js" type="module">

<script src="_content/Blazorise.Bulma/modal.js" type="module">

<script src="_content/Blazorise.Material/tooltip.js" type="module">
<script src="_content/Blazorise.Material/modal.js" type="module">

<script src="_content/Blazorise.AntDesign/modal.js" type="module">
<script src="_content/Blazorise.AntDesign/tooltip.js" type="module">

<script src="_content/Blazorise.Charts/charts.js" type="module">
<script src="_content/Blazorise.Charts.Streaming/charts.streaming.js" type="module">

<script src="_content/Blazorise.DataGrid/datagrid.js" type="module">

<script src="_content/Blazorise.Markdown/markdown.js" type="module">

<script src="_content/Blazorise.RichTextEdit/richtextedit.js" type="module">
```

In this way it does work indeed, but you can't pretend that every other library recognize this issue and provide this kind of documentation. Plus if the library is closed-source, there you have another, more difficult, roadblock as a developer.

I mean PWAs weren't supposed to work more or less offline seamlessly by default?
How does dynamically loading code when there's no internet aids to such intent?

**Comment by stsrki** [comment]
> 3\. Suddenly the user doesn't have any internet connection

To me, this is more of an edge case. If this happens it is expected for any web-based app to stop working. I think any user that works on the web would understand this.

And if you want to be sure and make it truly off-line then making the workaround and specifying the files manually is the only way.

**Comment by thepra** [comment]
You can't immagine how many places with good or scarce connectivity have maaany spotty areas, your "edge case" has been my norm for most of my life and in different places too.

So let's not pretend that that's an "edge case" because it's like saying that the UX is a joke(or a chore for those devs that do care about UX and have to put in extra work when it's totally avoidable) **or** the user is supposed to move/travel and live within areas with decent and never spotty internet connection, both points are extreme but not far from truth.

**Comment by bgriffy** [comment]
> > 3. Suddenly the user doesn't have any internet connection
> 
> To me, this is more of an edge case. If this happens it is expected for any web-based app to stop working. I think any user that works on the web would understand this.
> 
> And if you want to be sure and make it truly off-line then making the workaround and specifying the files manually is the only way.

I'd just like to mention that I'm also experiencing the same issues as @thepra after upgrading to the latest version of Blazorise. I have a PWA application that offers offline capabilities. Users will run the app on a mobile device, and as they walk through out a facility, they will often temporarily lose network connectivity. 

From the Blazorise end, I'm unsure if it would be possible or feasible for you guys to somehow add a work-around for this, I.E. add a way for us to specify that we never want to dynamically load the modules. But, it might at least be good to make a note of this issue in the Blazorise documentation. PWAs with offline capabilities are becoming increasingly more popular, so this issue may start to affect more Blazorise users down the line.

**Comment by mvdgun** [comment]
Reviving this old thread, hope that is okay. In my case I would like to load all the JS upfront instead of the offered dynamically loading. My main reason for this is caching, I am using a CDN with which I cache all the JS resources needed to run my app. I really love Blazorise and would love an option that let's me determine the JS auto loading strategy (enabled/disabled). In my apps we optimize all the JS through webpack and let webpack inject it with the correct CDN base URI into the index.html file (Blazor WASM).
