### ISSUE TITLE
Problem in PopupClosing Event of Datagrid

### ISSUE THREAD

**Issue by HaPre** [Megabit/Blazorise#3149]
When you want to prevent closing the Edit Popup you can use PopupClosing Event of the Datagrid. When you set the Cancel property on FocusLostClosing the CloseReason property stays with FocusLostClosing and the Popup never closes again.

I have attached an example project.

[BlazoriseTest.zip](https://github.com/Megabit/Blazorise/files/7576376/BlazoriseTest.zip)

**Comment by David-Moreira** [comment]
Hello @HaPre 
Thank you for providing us with an example project.
This does seem like a bug, maybe even with stand alone Modal. We'll take a look and let you know as soon as we have news.

**Comment by stsrki** [comment]
@David-Moreira Seems that this is still not working fully. Message from the Gitter room:

> @stsrki Thanks for fixing the bug "Problem in PopupClosing Event of Datagrid #3149" with 0951. But ... it was partly fixed ;-) When I click outside the modal dialog and than I click the close button, all works fine now. The fix fixed it. But when I click outside the modal dialog and than I click the Save button, the Save function is execute but the PopupClosing even still get's a "FocusLostClosing" CloseReason event, and therefor it doesn't close. You can see this behaviour in my test project which i have uploaded last on GitHub.

**Comment by David-Moreira** [comment]
Oh... My bad... Right makes sense... We didn't change anything in the save functionality... I'll take a look, it should be the same as for cancel.
