### ISSUE TITLE
TableHeaderCell in DetailRowTemplate of virtualized DataGrid is shifted

### ISSUE THREAD

**Issue by mtbayley** [Megabit/Blazorise#3151]
**Describe the bug**
When a table is added as the DetailRowTemplate in a DataGrid, the header row is shifted down by an X amount of px

**To Reproduce**
1. Add a virtualized DataGrid with a table in row details.
2. When the row is selected, show the details row
3. Row will be shifted down

**Example**
https://github.com/mtbayley/BlazoriseTableBug

**Screenshots**

![image](https://user-images.githubusercontent.com/34929316/142885937-cd59ac72-efc6-4967-8890-d919f4610e93.png)

![image](https://user-images.githubusercontent.com/34929316/142885978-de2a724e-bdc4-4cb4-b46b-745999539dcf.png)

![image](https://user-images.githubusercontent.com/34929316/142886509-37048a5f-63f7-4c8b-8de5-4436810de767.png)

**Additional context**

As a workaround, remove TableRow from table header. This does not seem to cause any issues except that it does not follow the documentation. OR, do not use a virtualized DataGrid

**Comment by David-Moreira** [comment]
Hello @mtbayley 
Thanks for the demo it really helps!

Can confirm it's a bug in our "FixedHeader" table feature which is used in Virtualize mode. The QuerySelector is taking in every existing thead below the table incorrectly. We'll change it to only take in the first as expected.
