### ISSUE TITLE
Markdown extension and highlight.js

### ISSUE THREAD

**Issue by njannink** [Megabit/Blazorise#3153]
I'm looking at the new markdown extension of Blazorise and I wonder why the `highlight.js` script is used and if it's mandatory to use.

**Comment by stsrki** [comment]
It is mandatory. Mainly for better support for code blocks formating.

**Comment by njannink** [comment]
But in my opinion this should be optional. In our case I don't need code blocks. And the default behavior of of SimpleMDE for code formatting is sufficient.

**Comment by stsrki** [comment]
I have just checked. You can just remove `highlight.js` from `index.html` and it will work without any issues. It is not mandatory after all 😅
