### ISSUE TITLE
Backspace bug in a NumericEdit 

### ISSUE THREAD

**Issue by baltazarO** [Megabit/Blazorise#3154]
I enter a decimal number with one number after the decimal place, for example 23.3, into a NumericEdit component. After I type it in, I press backspace and am left with (     23     ) instead of (      23.       ) In other words, I expect 23. (with the decimal) but I get 23

**Comment by stsrki** [comment]
It will work in v1.0. We have created a new NumericPicker component that has many features, including this. https://preview.blazorise.com/docs/components/numeric-picker
