### ISSUE TITLE
Check inside Dropdown doesn't work anymore

### ISSUE THREAD

**Issue by ivancavlek** [Megabit/Blazorise#3171]
**Describe the bug**
I have a Check inside Dropdown.
Prior to v0.9.5 it worked perfectly!
After I've updated to v0.9.5 it doesn't work anymore. Check can't be checked or unchecked anymore.

**To Reproduce**
This is a basic example to reproduce the bug:

``` C#
<Dropdown>
    <DropdownToggle Color="Color.Info">
        Test
    </DropdownToggle>
    <DropdownMenu>
        <DropdownItem Flex="Flex.JustifyContent.Between.AlignItems.Center">
            <Check TValue="bool"
                   @bind-Checked="_isFilterVisible">
                Bla
            </Check>
        </DropdownItem>
    </DropdownMenu>
</Dropdown>

@code{
    bool _isFilterVisible;
}
```

**Comment by stsrki** [comment]
I can confirm on our side, thank you for the code sample.

@David-Moreira I found this is happening because we have added `@onclick:preventDefault @onclick:stopPropagation` on `DropdownItem`. If I remove it, it seems to be working fine without. Do you remember why we needed it?

**Comment by David-Moreira** [comment]
Well apparently I added it on 
Nested dropdowns and refactor of closeable components #2954 #2ada4dbcfe5d4d9a73370be476feca4a38a9e52c

Maybe on the first version I was doing it made sense... I did remove it also, seems fine on all providers. I guess we should remove it.
