### ISSUE TITLE
ToolTip bind-Text to readonly property

### ISSUE THREAD

**Issue by erikthysell** [Megabit/Blazorise#3176]
I would like to do the following:
```
<Tooltip @bind-Text="@_saveFileToolTip">
    <Button Clicked="@(async ()=> await OnSaveGeneratedFile())" Disabled=@(!_isFileGenerated)>
        Save generated file
    </Button>
</Tooltip>

@code
{
    private bool _saveFileToolTip => _isFileGenerated 
                                   ? "Save the generated file" 
                                   : "You must first generate the file before saving";
}

```
However the compiler complains about 

> error CS0200: Property or indexer 'MyTestPage._saveFileToolTip' cannot be assigned to -- it is read only

I don't know if it is possible but it would be nice if I could accomplish the above without compiler errors.. :)

EDIT:

What I am really after is:
```
<Tooltip Text="@_saveFileToolTip">
    <Button Clicked="@(async ()=> await OnSaveGeneratedFile())" Disabled=@(!_isFileGenerated)>
        Save generated file
    </Button>
</Tooltip>

```
To update the tooltip text when `_isFileGenerated` is changed. This does not happen as it is now. (Blazorise 0.9.5, VS 2022, .NET 6)

**Comment by David-Moreira** [comment]
That property has an expression body, which pretty much acts like calling a method.
@bind only supports binding to properties as it needs to be able to set the value behind the scenes.

@bind- is also just a blazor convention that behind the scenes creates code that binds a property to Value and ValueChanged. 

So, for what you are looking for... 
You will have to do set Value and ValueChanged separately and manage accordingly. 
https://blazor-university.com/components/two-way-binding/

**Comment by erikthysell** [comment]
@David-Moreira  I am not entirely sure I understand what you mean but I think I am after the opposite of what you mean.
I would like the Text property of the ToolTip to be updated when `_saveFileToolTip` change. This does not happen, that's why I in my  ignorance tried with `@bind-Text` but I can see now that I should reformulate.

**Comment by stsrki** [comment]
`Tooltip` has a mechanism to update content when `Text `is changed. Maybe all you're missing is call to `StateHasChanges` when something changes in your app?

**Comment by David-Moreira** [comment]
Ah gotcha. Yes ur edited code now seems correct. Yea like strski said, seems like it might be missing some state had changed notification. If you are still having problems with making it work, just create a sample app and we'll take a look at what it is.
