### ISSUE TITLE
Value List of Autocomplete not shown in Datagrid

### ISSUE THREAD

**Issue by muzkaviy** [Megabit/Blazorise#3182]
**Describe the bug**
Hi,
I used a Blazorise.Components.Autocomplete in Blazorise.DataGrid.DataGridColumns.DataGridColumn.EditTemplate. When I start typing something, value list not showing. But when I press Down Arrow Button in Keyboard after typing something, the matched value appears on the textbox. Everything is OK if I use Autocomplete outside of DataGrid.

**To Reproduce**
1. Try to use Blazorise.Components.Autocomplete in Blazorise.DataGrid.DataGridColumns.DataGridColumn.EditTemplate
2. See there is no list when you start typing in textbox of autocomplete

**Expected behavior**
I expect Value List when I start typing something in datasource

Also please provide a sample code or point us to a minimalistic GitHub repo

**Screenshots**
<Row>
    <Column ColumnSize="ColumnSize.Is12">
        <Card>
            <CardBody>
                <DataGrid TItem="TransferDto"
                          Data="TransferList"
                          SelectionMode="DataGridSelectionMode.Multiple"
                          @bind-SelectedRow="SelectedTransfer"
                          @bind-SelectedRows="SelectedTransfers"
                          Editable="@CanEditTransfer"
                          EditMode="DataGridEditMode.Inline"
                          UseInternalEditing="true"
                          ReadData="OnDataGridReadAsync"
                          RowInserted="@OnRowInserted"
                          RowUpdated="@OnRowUpdated"
                          RowRemoved="@OnRowRemoved"
                          NewItemDefaultSetter="@OnNewItemDefaultSetter"
                          TotalItems="TotalTransferCount"
                          AggregateData="TransferList"
                          PageSize="TransferPageSize"
                          ShowPager="true"
                          Filterable="false"
                          Sortable="true"
                          Striped="true"
                          Bordered="true"
                          Hoverable="true"
                          Responsive="true"
                          Style="@("width: 1750px;")">
                    <DataGridColumns>
                        <DataGridMultiSelectColumn TItem="TransferDto"
                                                   Width="25px">
                        </DataGridMultiSelectColumn>

                        <DataGridCommandColumn Width="@("40px")"
                                               TItem="TransferDto"
                                               CellsEditableOnEditCommand="true"
                                               TextAlignment="TextAlignment.Center">
                            <NewCommandTemplate>.. </NewCommandTemplate>
                            <SaveCommandTemplate>.. </SaveCommandTemplate>
                            <EditCommandTemplate>..  </EditCommandTemplate>
                            <DeleteCommandTemplate>.. </DeleteCommandTemplate>
                            <CancelCommandTemplate>.. </CancelCommandTemplate>
                            <ClearFilterCommandTemplate>.. </ClearFilterCommandTemplate>
                        </DataGridCommandColumn>

                            <DataGridColumn Width="@("75px")"
                                            TItem="TransferDto"
                                            Field="@nameof(TransferDto.FromLocationId)"
                                            Caption="@L["From2"]"
                                            Editable="@CanEditAllFields">
                                <DisplayTemplate>
                                    @context.FromLocation
                                </DisplayTemplate>
                                <EditTemplate>

                                    <Autocomplete TItem="TransferLocationDto"
                                                  TValue="Guid"
                                                  Data="LocationList"
                                                  TextField="@( (item) => item.Name )"
                                                  ValueField="@( (item) => item.Id )"
                                                  SelectedValue="@((Guid)( ( (CellEditContext)context).CellValue ))"
                                                  SelectedValueChanged="@((v) => ( (CellEditContext)context).CellValue = (Guid)v)"
                                                  Placeholder="Select from location"
                                                  Filter="AutocompleteFilter.Contains"
                                                  FreeTyping="false"
                                                  CustomFilter="@( (item, searchValue) => item.Name.Contains(searchValue, StringComparison.CurrentCultureIgnoreCase) )">
                                    </Autocomplete>
                                </EditTemplate>
                            </DataGridColumn>
...

**Additional context**
Add any other context about the
![autocomplete3 afterkeydownpress](https://user-images.githubusercontent.com/4332013/143780874-0bb42d5a-826a-4cb4-adcf-9e522a09b82b.png)
 problem here
![autocomplete1](https://user-images.githubusercontent.com/4332013/143780865-84864744-742a-486d-bb1d-75f200843e10.pn
![autocomplete2](https://user-images.githubusercontent.com/4332013/143780870-4501f5bc-3b00-4425-8bc6-ab446d0e4df7.png)
g)
.

**Comment by muzkaviy** [comment]
![autocomplete3 afterkeydownpress](https://user-images.githubusercontent.com/4332013/143780891-a40fabee-3a13-4f57-b99c-e78b1b650eac.png)
after keydownpress

**Comment by David-Moreira** [comment]
Hello @muzkaviy 
Thanks for the reproducable example.
The app is going into a broken state because you are binding null values here: 
```
SelectedValue="@((Guid)( ( (CellEditContext)context).CellValue ))"
SelectedValueChanged="@((v) => ( (CellEditContext)context).CellValue = (Guid)v)"
```
And the Text/Value Fields are trying to resolve the Field on a null object.

Try null checking like this:
```
TextField="@( (item) => item?.Name )"
ValueField="@( (item) => item?.Id ?? Guid.Empty )"
```

Let us know if this helps.

**Comment by muzkaviy** [comment]
Hi David,
Thanks for the quick response.

Actually, everything is OK if I use Autocomplete outside of DataGrid.

On the other hand, I tried your suggestions.

I changed the code like this:

                                    <Autocomplete TItem="TransferLocationDto"
                                                  TValue="Guid"
                                                  Data="LocationList"
                                                  TextField="@( (item) => item?.Name )"
                                                  ValueField="@( (item) => item?.Id ?? Guid.Empty )"
                                                  Placeholder="Select from location"
                                                  Filter="AutocompleteFilter.Contains"
                                                  FreeTyping="false"
                                                  CustomFilter="@( (item, searchValue) => item.Name.Contains(searchValue, StringComparison.CurrentCultureIgnoreCase) )">
                                    </Autocomplete>
                                    
(Removed SelectedValue* props & Handled null values on TextField, ValueField)

It still does not show value list. However After I press down key, a matched value appears on the textbox.

**Comment by David-Moreira** [comment]
Hello,
If you are telling me that when you press the down key a match values appears...
Then that seems like styling related? Maybe the Autocomplete box is actually showing up inside the datagrid when you click, you just can't see it? I'll see if I can replicate that.

Can you take a look at the html generated on your end, when you click the auto complete that's inside the datagrid?

**Comment by muzkaviy** [comment]
Hi,
Actually, before open this thread, I configured z-index of autocomplete to be shown front of all other components. But It did not work.

![autocomplete](https://user-images.githubusercontent.com/4332013/143929261-1666abb1-6da5-4dc8-83c9-739c16490d6c.png)

**Comment by David-Moreira** [comment]
The zindex should be configured on the actual HTML menu that's gonna show. So if you click the HTML menu isn't filled behind the scenes?

**Comment by David-Moreira** [comment]
I just retested. It's working. I think it might be styling. 
Can you re-open the elements tab in your browser DevTools and check if the dropdown-menu div besides the `Autocomplete` input gets the `show` class when you type a valid value in the `Autocomplete`?

![image](https://user-images.githubusercontent.com/22283161/143962597-f1893ad2-11c1-4b69-9caa-1d5ba356ac00.png)

I don't know your app styling but try adding this css:
```
.dropdown-menu{
    position: relative;
    z-index: 999;
}
```
![image](https://user-images.githubusercontent.com/22283161/143962443-ec1f6a94-95e0-4af3-b61b-0bd2037688d3.png)

Let us know how it goes.

**Comment by muzkaviy** [comment]
Hi David,

As you see below 2 pics, When I change position attrib from absolute to relative (dropdown-menu show), the list appears.
To be honest, it looks ugly, but acceptable.

But, When I add style (position:relative) prop to Autocomplete, Html renderer adds it to upper html tag as you see last 2 pics.

How can I manipulate inner Html tag style via Autocomplete<>?

![autocomplete01](https://user-images.githubusercontent.com/4332013/144051680-38bda39b-d9aa-4663-b80e-0284e2e270c8.png)

![autocomplete02](https://user-images.githubusercontent.com/4332013/144051698-5fdf7a9d-cb05-4dde-9f87-4d036490ab98.png)

![autocomplete03](https://user-images.githubusercontent.com/4332013/144052138-406bd485-1fb0-4a2f-ad2a-276f1775249a.png)

![autocomplete04](https://user-images.githubusercontent.com/4332013/144052158-7d571ea4-ab0d-4aca-908f-718400ea4ef0.png)

**Comment by David-Moreira** [comment]
Glad you got it solved. 
No problem, I'm sure you'll be able to make it look better! :)
