### ISSUE TITLE
Improved scoped css support

### ISSUE THREAD

**Issue by njannink** [Megabit/Blazorise#3184]
When I do the following it doesn't work.

```
// homepage.razor
<Container>
   <Row>
       <Column>
           <Button Class="my-button" />
       </Column>
   </Row>
</Container>

// homepage.razor.css
::deep .my-button { color:red; }
```

At the moment I have to wrap it all in a `<div>` to get the `::deep .my-botton` style to be applied.

I don't know if this is a Blazor issue or something that can be improved in Blazorise

**Comment by stsrki** [comment]
This is Blazor's issue. If you inspect your `div` element you will see a special `b-*` attribute. That must be created at compile time. And since Blazorise components are already compiled there is no way to create that attribute. This is true for all component libraries, unfortunately.

**Comment by njannink** [comment]
Mhm I was already affraid this is the case. Now I have to add these wrapping divs everywhere

**Comment by stsrki** [comment]
You can also read it here https://docs.telerik.com/blazor-ui/knowledge-base/common-css-isolation
