### ISSUE TITLE
Update Releases Page for 9.5.1

### ISSUE THREAD

**Issue by markdav-is** [Megabit/Blazorise#3186]
I'm trying to see what's new in 9.5.1
The releases docs page is empty
https://blazorise.com/docs/releases/

trying to determine what controls are affected and if we should upgrade.  I'll poke around in the repo looking for commits.

**Comment by David-Moreira** [comment]
Hello @markdav-is 
Sorry about that.

Please take a look at our news page: 
https://blazorise.com/news

Here's the 0.9.5.1 release notes:
https://blazorise.com/news/release-notes/095-1

**Comment by markdav-is** [comment]
thanks!
