### ISSUE TITLE
DataGridMaxHeigh Missing in DataGrid FixedHeaderDataGridHeight ignored on Virtualize=true

### ISSUE THREAD

**Issue by Mr-Pearce** [Megabit/Blazorise#3194]
**Describe the bug**
When Setting `Virtualize="true"` on DataGrid
`FixedHeaderDataGridHeight=""`
and
`FixedHeaderDataGridMaxHeight=""`
are ignored.

In https://blazorise.com/docs/extensions/datagrid/getting-started you list 
`DataGridMaxHeigh`  _Sets the DataGrid height when Virtualize feature is enabled._ 

But in the current version 9.5.1 the `DataGridMaxHeigh` property is missing.
![grafik](https://user-images.githubusercontent.com/13457314/144201235-682c2931-26b3-42ea-8239-554eb58155bc.png)
Also, the code compiles but gives an Error at runtime! (in firefox developer log)
`Error: System.InvalidOperationException: Object of type 'Blazorise.DataGrid.DataGrid1[[MyType, MyNamespace, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' does not have a property matching the name 'DataGridMaxHeigh'.`

Also: shouldnt there also be an `DataGridMinHeigh `property? 
When setting `Virtualize="true"`  `style="height: 500px; max-height: 500px` is added
**To Reproduce**
1. Create a DataGrid like in the screenshot above.
2. Run Project
3. See error

**Expected behavior**
`DataGridMaxHeigh` shouldn't be missing.

Also please provide a sample code or point us to a minimalistic GitHub repo

**Screenshots**
see Screenshot above

**Additional context**

**Comment by David-Moreira** [comment]
`DataGridMaxHeigh`? Or `DataGridMaxHeight`?
Seems like a spelling error in our docs. Have you tried `DataGridMaxHeight`?

**Comment by Mr-Pearce** [comment]
> `DataGridMaxHeigh`? Or `DataGridMaxHeight`? Seems like a spelling error in our docs. Have you tried `DataGridMaxHeight`?

Doesnt make any difference.
Intellicode cant even find any "DataGrid'max anything'"
![grafik](https://user-images.githubusercontent.com/13457314/144384288-9bc0a2e0-5c03-4105-8c1b-83480759d1eb.png)

But i just found out that it is under `VirtualizeOptions`.
Maybe that is the error in the docs?
![grafik](https://user-images.githubusercontent.com/13457314/144384502-5a1cb66a-9f60-42ea-aabd-56d4e3f0584a.png)

**Comment by David-Moreira** [comment]
Oh, that's it haha. We'll fix the docs.
