### ISSUE TITLE
More options for IMessageService

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#3195]
Hi,
To continue in this subject, will it be possible to have some more options to customize the modal?
I think on:
 - showing the X close button (as on classic modal)
 - set the css class for buttons. we can set text but it would be great if we can also remplace the default css class.

_Originally posted by @ponchautf in https://github.com/Megabit/Blazorise/issues/2669#issuecomment-983610157_

**Comment by Mr-Pearce** [comment]
If would also help if we could just change the Button Colors.

```
await MessageService.Confirm($"Should it be Deleted", "Test", (x) =>
            {
                x.ShowMessageIcon = false;
                x.CancelButtonText = "Cancel";
                x.ConfirmButtonText = "Delete";
            }))
```
Creates a color wise unintuitive modal.
![grafik](https://user-images.githubusercontent.com/13457314/149975287-c96c2bf0-e5d0-4ff0-ac52-56df546d50e7.png)

x.`CancelButtonColor` and x.`ConfirmButtonColor `
would be nice here.
