### ISSUE TITLE
Button not showing up after 0.9.5 version

### ISSUE THREAD

**Issue by polonskyg** [Megabit/Blazorise#3204]
**Describe the bug**
I'm using .NET 5 with Blazorise 0.9.5.2 now. I'm using mapbox and on top of it I show a few things like buttons. They were showing previously and they are not shown anymore.

**To Reproduce**
The component I'm using on top of mapbox is like this

```
@using Blazorise.Snackbar

<div style="float: left; padding-left: 20%; padding-right: 20%; ">
    <Buttons Class="editor" Style="@($"direction:{AppStateInstance.GetDirection()}")">
        <Buttons Role="ButtonsRole.Toolbar" Margin="Margin.Is2.FromRight">
            <Button Clicked="ConfirmChanges" Color="Color.Secondary" Disabled="(Counter == 0)">
                <Badge Color="Color.Light" Margin="Margin.Is2">@Counter</Badge>
                @switch (EditType)
                {
                    case Type.ADD:
                        Add
                        break;
                    case Type.REMOVE:
                        Delete
                        break;
                }
                Name
            </Button>
            <Button Color="Color.Secondary" Clicked="Change">
                remove
            </Button>
            <Button Color="Color.Secondary" Clicked="Dispose">
                <Icon Class="fa-sign-out-alt" />
                quit
            </Button>
        </Buttons>
        <RadioGroup TValue="bool" Buttons="true" CheckedValue="Do" CheckedValueChanged="Act" Margin="Margin.Is2.FromRight">
            <Radio Value="true"><Icon Class="fa-draw-polygon" /></Radio>
            <Radio Value="false"><Icon Class="fa-hand-pointer" /></Radio>
        </RadioGroup>
    </Buttons>

    <Snackbar @ref="snackBar" Color="SnackbarColor.Secondary" Interval="10000">
        <SnackbarBody Style="@($"direction:{AppStateInstance.GetDirection()}")">
            test1
        </SnackbarBody>
    </Snackbar>
</div>
```

**editor class (css)**
```
.editor {
    display: none;
    position: absolute;
    top: 2%;
    left: 40%;
    z-index: 1;
}

```**Expected behavior**
The button should be seen on top of mapbox

**Comment by polonskyg** [comment]
It seems something around css is the problem as I changed display: none with display: block and I see now the buttons for not aligned correctly...Was any css change introduced in 0.9.5?

**Comment by polonskyg** [comment]
Changing the css made it work, but don't know why I had to change it when I upgraded blazorise.

**Comment by stsrki** [comment]
According to the Bootstrap documentation https://getbootstrap.com/docs/4.6/components/button-group/, `btn-group` has a `position: relative;`.

![image](https://user-images.githubusercontent.com/900302/144650157-00e6f46f-d03e-457e-ac23-a4d57b5dd3ef.png)

---

With `.editor` you made it `position: absolute;` which breaks default styles so it is needed to adjust CSS to make it work for your project. Not sure it break after the update, but possibly there were different versions of bootstrap?
