### ISSUE TITLE
Documentation - Docs/Components/Selects/SelectPage.razor could use more detail

### ISSUE THREAD

**Issue by SomeoneElseOSM** [Megabit/Blazorise#3207]
There are a couple of issues with https://blazorise.com/docs/components/select/ :

* A bit more detail throughout would be helpful
* Specifically, highlight that the Blazorise component is `<Select>` not the (completely valid, but not Blazorise) `<select>`.

Blazor itself doesn't always react well to errors, but this isn't really a Blazor problem; when a component contains something that is valid ASP but makes no sense in Blazorise (misuse of Blazorise components, for example `<select>` instead of `<Select>` it can't be expected to say "you probably meant (completely legal but meaningful) thing B rather than (also completely legal but meaningless in Blazorise) thing A".

I'm happy to submit a pull request (adding a "Note" similar to the "Otherwise the Select will not behave as expected." one lower down) if desired.

**Comment by stsrki** [comment]
I don't think this is wrong. We could add a note, it's not difficult to do so. But, the naming convention for Blazor components is that everything with an uppercase is a component, and everything with lowercase is an element. This is per ASP.NET documentation https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-6.0#names.

A similar pattern is for other SPA frameworks, so I would say it is somewhat a standard way of naming components.

**Comment by David-Moreira** [comment]
I don't see a problem here either.. But a note can't hurt I guess. :)

**Comment by stsrki** [comment]
I agree, a note can be added to the docs.

**Comment by David-Moreira** [comment]
@SomeoneElseOSM can you elaborate on this point?

>- A bit more detail throughout would be helpful

What kind of detail do you think we should add that would be more helpful in using this particular component?
Thanks!
