### ISSUE TITLE
List View component missing in Blazorise.Bootstrap5 NuGet package 0.9.5-preview2.1?

### ISSUE THREAD

**Issue by Stirda** [Megabit/Blazorise#3215]
I don't find `<ListView>` component in `Blazorise.Bootstrap5` NuGet package `0.9.5-preview2.1`. Will it come back? (I am using ABP 5 so cannot update to 0.9.5 final)

**Comment by stsrki** [comment]
I don't think there was a `ListView` component in the `0.9.5-preview2.1`. It was added after.

Also, `ListView` is part of the `Blazorise.Components` package.

**Comment by Stirda** [comment]
My bad. I would have never thought that this component was so young. Blazorise is growing so fast :) Just have to wait one week before ABP 5 final comes (and be compatible) with Blazorise `0.9.5` (final). Meanwhile I will use `<ListGroup>`...

**Comment by stsrki** [comment]
> Blazorise is growing so fast :)

You have no idea 😅
