### ISSUE TITLE
Button Visibility Unexpected Behaviour

### ISSUE THREAD

**Issue by TorreyGarland** [Megabit/Blazorise#3217]
Possibly related to Issue #2729.

I have a Blazorise Field with three (3) buttons.  I want to conditionally hide or display the middle button.

Setting its visibility to invisible does hide the button, but the space that it occupies remains instead of collapsing the third/last button next to the first one.

Any ideas?

**Comment by stsrki** [comment]
`Visibility` is used to hide the element while still preserving the space. To really hide the element use the `Display` parameter. Eg.

`Display="Display.None"` to hide it, and ``Display="Display.Block"`` to show it.

**Comment by David-Moreira** [comment]
@TorreyGarland I'm guessing this solved your problem, right?
It is known that in html you can either have an invisible element, or straight up not display it, so closing issue as this does not seem like a bug.

**Comment by TorreyGarland** [comment]
apologies for the delay.  yes, it did fix the problem.

**Comment by ruisantos78** [comment]
Using Display to hide a button doesn't make sense in an MVVM scenario.

Since Visibility is an enum, could it include a "Collapse" option to hide the element like display none?

**Comment by stsrki** [comment]
> Using Display to hide a button doesn't make sense in an MVVM scenario.
> 
> Since Visibility is an enum, could it include a "Collapse" option to hide the element like display none?

It seems like a good idea, and fairly simple to do. Can you open a new ticket?

**Comment by TorreyGarland** [comment]
No.

**Comment by stsrki** [comment]
> No.

I'm sorry, but did we offend you in any way?

**Comment by TorreyGarland** [comment]
Not at all.  I have a solution that is a little more flexible.
