### ISSUE TITLE
Customize <PageButtonTemplate> background color 

### ISSUE THREAD

**Issue by ChemaMoToCanFor** [Megabit/Blazorise#3220]
Hi,

I'm tryimg to change the background color of selected page in DataGrid. I can change text color using this code found in Demos/Blazorise.Demo/Pages/Tests/DataGrid/PagerPage.razor

`                    <PageButtonTemplate>
                        <Span TextColor="TextColor.Success">
                            @context.PageNumer
                        </Span>
                    </PageButtonTemplate>`

but not the background. Any help, please?

**Comment by David-Moreira** [comment]
Hello,

Either you change your Blazorise Theme's Primary Color accordingly...
https://blazorise.com/docs/theming

Or you should use css to achieve this, as the buttons are wrapped in an anchor that takes in the Primary Background color.

If you want to only change the background of the pager buttons specifically, use this selector :

![image](https://user-images.githubusercontent.com/22283161/145317303-6ad94b98-ba65-4ac0-9f54-9b3978e30811.png)

**Comment by ChemaMoToCanFor** [comment]
Thanks, I'll try it asap...
