### ISSUE TITLE
Samples on how to use SelectedRowChanged?

### ISSUE THREAD

**Issue by improwise** [Megabit/Blazorise#3223]
Where can I find a sample on how to use SelectedRowChanged as the documentation for this is almost not existent? Imagine something like a master/detail but with the details outside of the DataGrid. Were able to get something like @bind-SelectedRow="@SelectedCorporateCustomer" working but that isn't well suited to more advanced handling of selection events. 

Thanks.

**Comment by stsrki** [comment]
`SelectedRowChanged` is an event that is handled automatically by the Blazor when you use `@bind-*`. It is a shorthand for `SelectedRow="@SelectedCorporateCustomer" SelectedRowChanged="@OnCorporateCustomerChanged"`.

So you just need to not use `@bind-*` and you can switch to the "manual" mode.

**Comment by improwise** [comment]
Thanks. Bur what arguments are we to receive in the event handler etc? This is why we tried to find a sample as the documentation is lacking. Thanks.

**Comment by David-Moreira** [comment]
Hello SelectedRowChanged is an EventCallback that can take in a generic. This means that you can bind any method to it that is compatible. In this case it would be a method that takes your TItem as an argument. 

Blazorise has documentation about its components and how to use them. Your question seems more about how Blazor works and I suggest reading this resource : https://blazor-university.com/components/component-events/

However we are here to help, just let us know if you still have doubts.

**Comment by improwise** [comment]
Turned out we had gotten a bit to creative with the casting of input parameters which produced an error message that wasn't to obvious. Seems to be working fine now. Thanks.

**Comment by stsrki** [comment]
You can make the method `Task`-able and in most cases, you don't need to call `StateHasChanged` to refresh the page. It will be handled by the Blazor.

```cs
private async Task OnSelectedRowChangedAsync(CorporateCustomerWithNavigationPropertiesDto corporateCustomerWithNavigationPropertiesDto)
{     
  //await Do some get or whatever with the id from the model...
}
```

**Comment by David-Moreira** [comment]
Yes, EventCallback has an implicit statehaschanged call done by the blazor framework.
