### ISSUE TITLE
DetailRowTrigger Bug

### ISSUE THREAD

**Issue by itsLollo1000** [Megabit/Blazorise#3226]
After opening a DetailRow it is possible to close the DetailRow by clicking on the parent cell of the DetailRow.
Normally this behavior is expected, but our DetailRow is openend by a button inside of the parent row with a additional method.

Create a grid and open a DetailRow then click on its parent DetailRow. 

`DetailRowTrigger=@((item) => selectedPatches.Contains(item.ID))`
This is used to know which row is opened. Our button simply adds the of a row to the List which then opens the DetailRow.

**Comment by David-Moreira** [comment]
If selection is not needed for your DataGrid you can use `ParentDataGrid.RowSelectable` and make it so the row is not selectable, this way `DetailRowTrigger` will not be triggered.

Otherwise, as a workaround, you can use the `ToggleDetailRow` Api to force the detail back on.
And you are right, that seems a valid use case. To have the option for "always on" DetailRow, meaning that consequent clicks will not close it, right @stsrki ?

**Comment by stsrki** [comment]
I believe with some extra code this can already be achieved with the `DetailRowTrigger`. Instead of just checking for the ID in the list you also check some other variable, eg `DetailRowTrigger=@((item) => selectedPatches.Contains(item.ID) && !alreadyOpenedOrSomething)`.

**Comment by itsLollo1000** [comment]
Well then maybe I wrote it wrong so you misunderstood. I will create a test repo tomorrow. It used to work before. Now it is sort of a bug. You will see it in my project tomorrow. :)

**Comment by itsLollo1000** [comment]
So here I recreated a bit of our code.

Now it is possible to open a DetailRow via double click a row or the button in the front. 

Once you have openend a DetailRow, just click once anywhere on the parent row (marked red) and it is possible to open and close the DetailRow as often as you want.
![Screenshot 2021-12-10 100318](https://user-images.githubusercontent.com/10349466/145547111-b08ba62a-7b96-40c5-abd5-4ab313d111c2.png)

This behavior stops after closing the DetailRow with a double click or via the button.

https://github.com/itsLollo1000/BlazorGridTesting

**Comment by David-Moreira** [comment]
Hello @itsLollo1000 
isn't this what you're looking for? You don't need to track dbl click as regular click is always triggered.

```
@page "/"

<PageTitle>Index</PageTitle>

<DataGrid 
          TItem=TestItem
          Data=@testing
          Bordered=true
          Sortable=true
          Filterable=true
          ShowPager=false
          PageSize=25
          Hoverable=false
          RowClicked=@RowClicked
          DetailRowTrigger=@((item) => selectedPatches.Contains(item.ID))>
    <DataGridColumns>
        <DataGridColumn TItem=TestItem Field="Name" Filterable="false">
            <DisplayTemplate>
                <div style="text-align: center;">
                    <Button><Icon Name="@((selectedPatches.Contains(context.ID)) ? "fa-angle-down" : "fa-angle-right")" /></Button>
                </div>
            </DisplayTemplate>
        </DataGridColumn>
        <DataGridColumn TItem=TestItem Field="Name" />
        <DataGridColumn TItem=TestItem Field="ID" />
    </DataGridColumns>
    <DetailRowTemplate>
        <Icon Name=IconName.BirthdayCake Style="width: 10em;" />
    </DetailRowTemplate>
</DataGrid>

@code {
    List<TestItem> testing = new List<TestItem>();
    private List<int> selectedPatches = new();

    protected override void OnInitialized()
    {
        for (int i = 0; i < 20; i++)
            testing.Add(new TestItem("Test " + i, i));
    }

    protected void RowClicked(DataGridRowMouseEventArgs<TestItem> temp)
    {
        var patch = temp.Item;;
        OnRowPatchesClicked(patch);
    }

    public bool OnRowPatchesClicked(TestItem patchPolicy)
    {
        if (selectedPatches.Contains(patchPolicy.ID))
        {
            selectedPatches.Remove(patchPolicy.ID);
            return false;
        }
        else
        {
            selectedPatches.Add(patchPolicy.ID);
            return true;
        }
    }

    public class TestItem
    {
        public string Name { get; set; }
        public int ID { get; set; }

        public TestItem(string Name, int ID)
        {
            this.Name = Name;
            this.ID = ID;
        }
    }
}
```

**Comment by itsLollo1000** [comment]
> Hello @itsLollo1000 
> 
> isn't this what you're looking for? You don't need to track dbl click as regular click is always triggered.
> 
> 
> 
> ```
> 
> @page "/"
> 
> 
> 
> <PageTitle>Index</PageTitle>
> 
> 
> 
> <DataGrid 
> 
>           TItem=TestItem
> 
>           Data=@testing
> 
>           Bordered=true
> 
>           Sortable=true
> 
>           Filterable=true
> 
>           ShowPager=false
> 
>           PageSize=25
> 
>           Hoverable=false
> 
>           RowClicked=@RowClicked
> 
>           DetailRowTrigger=@((item) => selectedPatches.Contains(item.ID))>
> 
>     <DataGridColumns>
> 
>         <DataGridColumn TItem=TestItem Field="Name" Filterable="false">
> 
>             <DisplayTemplate>
> 
>                 <div style="text-align: center;">
> 
>                     <Button><Icon Name="@((selectedPatches.Contains(context.ID)) ? "fa-angle-down" : "fa-angle-right")" /></Button>
> 
>                 </div>
> 
>             </DisplayTemplate>
> 
>         </DataGridColumn>
> 
>         <DataGridColumn TItem=TestItem Field="Name" />
> 
>         <DataGridColumn TItem=TestItem Field="ID" />
> 
>     </DataGridColumns>
> 
>     <DetailRowTemplate>
> 
>         <Icon Name=IconName.BirthdayCake Style="width: 10em;" />
> 
>     </DetailRowTemplate>
> 
> </DataGrid>
> 
> 
> 
> @code {
> 
>     List<TestItem> testing = new List<TestItem>();
> 
>     private List<int> selectedPatches = new();
> 
> 
> 
>     protected override void OnInitialized()
> 
>     {
> 
>         for (int i = 0; i < 20; i++)
> 
>             testing.Add(new TestItem("Test " + i, i));
> 
>     }
> 
> 
> 
>     protected void RowClicked(DataGridRowMouseEventArgs<TestItem> temp)
> 
>     {
> 
>         var patch = temp.Item;;
> 
>         OnRowPatchesClicked(patch);
> 
>     }
> 
> 
> 
>     public bool OnRowPatchesClicked(TestItem patchPolicy)
> 
>     {
> 
>         if (selectedPatches.Contains(patchPolicy.ID))
> 
>         {
> 
>             selectedPatches.Remove(patchPolicy.ID);
> 
>             return false;
> 
>         }
> 
>         else
> 
>         {
> 
>             selectedPatches.Add(patchPolicy.ID);
> 
>             return true;
> 
>         }
> 
>     }
> 
> 
> 
>     public class TestItem
> 
>     {
> 
>         public string Name { get; set; }
> 
>         public int ID { get; set; }
> 
> 
> 
>         public TestItem(string Name, int ID)
> 
>         {
> 
>             this.Name = Name;
> 
>             this.ID = ID;
> 
>         }
> 
>     }
> 
> }
> 
> ```

Well not really we only want to DetailRow to trigger trigger on a double click. Since there is a lot of details that are loaded we don't want the user to have a single click expanding all of that.

But still it feels like a bug when the double expands a DetailRow and then after it's expanded a single click will collapse and expand it infinitely(without referencing it to the grid), until I "fully" close it with the double click referenced to the grid.

**Comment by David-Moreira** [comment]
DetailRow is now evaluated on a per click basis with the option to use the `ToggleDetailRow` Api  to trigger it manually.
If that's your requirements, this should be what you're looking for:


```
@page "/"

<PageTitle>Index</PageTitle>

<DataGrid   
            @ref="dataGridRef"
            TItem=TestItem
            Data=@testing
            Bordered=true
            Sortable=true
            Filterable=true
            ShowPager=false
            PageSize=25
            Hoverable=false
            RowDoubleClicked=@RowDoubleClicked
            RowSelectable="@((item) => false)"
            DetailRowTrigger=@((item) => selectedPatches.Contains(item.ID))>
        <DataGridColumns>
            <DataGridColumn TItem=TestItem Field="Name" Filterable="false">
                <DisplayTemplate>
                    <div style="text-align: center;">
                        <Button Clicked="@(async () => await OnRowPatchesClicked(context))"><Icon Name="@((selectedPatches.Contains(context.ID)) ? "fa-angle-down" : "fa-angle-right")" /></Button>
                    </div>
                </DisplayTemplate>
            </DataGridColumn>
            <DataGridColumn TItem=TestItem Field="Name" />
            <DataGridColumn TItem=TestItem Field="ID" />
        </DataGridColumns>
        <DetailRowTemplate>
            <Icon Name=IconName.BirthdayCake Style="width: 10em;" />
        </DetailRowTemplate>
</DataGrid>

@code {
    DataGrid<TestItem> dataGridRef;
    List<TestItem> testing = new List<TestItem>();
    private List<int> selectedPatches = new();

    protected override void OnInitialized()
    {
        for (int i = 0; i < 20; i++)
            testing.Add(new TestItem("Test " + i, i));
    }

    protected Task RowDoubleClicked(DataGridRowMouseEventArgs<TestItem> temp)
    {
        var patch = temp.Item;
        return OnRowPatchesClicked(patch);
    }

    public Task OnRowPatchesClicked(TestItem patchPolicy)
    {
        if (selectedPatches.Contains(patchPolicy.ID))
            selectedPatches.Remove(patchPolicy.ID);
        else
            selectedPatches.Add(patchPolicy.ID);
        
        return dataGridRef.ToggleDetailRow(patchPolicy);
    }

    public class TestItem
    {
        public string Name { get; set; }
        public int ID { get; set; }

        public TestItem(string Name, int ID)
        {
            this.Name = Name;
            this.ID = ID;
        }
    }
}
```

**Comment by itsLollo1000** [comment]
> DetailRow is now evaluated on a per click basis with the option to use the `ToggleDetailRow` Api  to trigger it manually.
> 
> If that's your requirements, this should be what you're looking for:
> 
> 
> 
> 
> 
> ```
> 
> @page "/"
> 
> 
> 
> <PageTitle>Index</PageTitle>
> 
> 
> 
> <DataGrid   
> 
>             @ref="dataGridRef"
> 
>             TItem=TestItem
> 
>             Data=@testing
> 
>             Bordered=true
> 
>             Sortable=true
> 
>             Filterable=true
> 
>             ShowPager=false
> 
>             PageSize=25
> 
>             Hoverable=false
> 
>             RowDoubleClicked=@RowDoubleClicked
> 
>             RowSelectable="@((item) => false)"
> 
>             DetailRowTrigger=@((item) => selectedPatches.Contains(item.ID))>
> 
>         <DataGridColumns>
> 
>             <DataGridColumn TItem=TestItem Field="Name" Filterable="false">
> 
>                 <DisplayTemplate>
> 
>                     <div style="text-align: center;">
> 
>                         <Button Clicked="@(async () => await OnRowPatchesClicked(context))"><Icon Name="@((selectedPatches.Contains(context.ID)) ? "fa-angle-down" : "fa-angle-right")" /></Button>
> 
>                     </div>
> 
>                 </DisplayTemplate>
> 
>             </DataGridColumn>
> 
>             <DataGridColumn TItem=TestItem Field="Name" />
> 
>             <DataGridColumn TItem=TestItem Field="ID" />
> 
>         </DataGridColumns>
> 
>         <DetailRowTemplate>
> 
>             <Icon Name=IconName.BirthdayCake Style="width: 10em;" />
> 
>         </DetailRowTemplate>
> 
> </DataGrid>
> 
> 
> 
> @code {
> 
>     DataGrid<TestItem> dataGridRef;
> 
>     List<TestItem> testing = new List<TestItem>();
> 
>     private List<int> selectedPatches = new();
> 
> 
> 
>     protected override void OnInitialized()
> 
>     {
> 
>         for (int i = 0; i < 20; i++)
> 
>             testing.Add(new TestItem("Test " + i, i));
> 
>     }
> 
> 
> 
>     protected Task RowDoubleClicked(DataGridRowMouseEventArgs<TestItem> temp)
> 
>     {
> 
>         var patch = temp.Item;
> 
>         return OnRowPatchesClicked(patch);
> 
>     }
> 
> 
> 
>     public Task OnRowPatchesClicked(TestItem patchPolicy)
> 
>     {
> 
>         if (selectedPatches.Contains(patchPolicy.ID))
> 
>             selectedPatches.Remove(patchPolicy.ID);
> 
>         else
> 
>             selectedPatches.Add(patchPolicy.ID);
> 
>         
> 
>         return dataGridRef.ToggleDetailRow(patchPolicy);
> 
>     }
> 
> 
> 
>     public class TestItem
> 
>     {
> 
>         public string Name { get; set; }
> 
>         public int ID { get; set; }
> 
> 
> 
>         public TestItem(string Name, int ID)
> 
>         {
> 
>             this.Name = Name;
> 
>             this.ID = ID;
> 
>         }
> 
>     }
> 
> }
> 
> ```

Okay thank you will test it tomorrow! 

Did this change with the recent 0.9.X update?

**Comment by David-Moreira** [comment]
https://blazorise.com/news/release-notes/095

![image](https://user-images.githubusercontent.com/22283161/146101060-1a96c712-650d-43df-a904-735d1a4be376.png)

**Comment by itsLollo1000** [comment]
Well your last code snippet sort of fixed it, but then I noticed that the code disables the RowSelectable, which we sort of also want...

The thing is, that the changes mentioned in 0.9.5 changed our runing system haha. Before everything worked like expected.

I will take this as fix for now. But it might be worth keeping in mind, that those changes sort of leed to unexpected behaviour. Since it breaks the feature of having a double click and a DetailRow.

**Comment by David-Moreira** [comment]
Ah, I see. You are right.

You might still be able to achieve what you want with `RowSelectable` on. Just that you have to re-trigger `ToggleDetailRow`. So that it toggles it back on, ah?

I don't think our change in making it so that it now only evaluates on row click is wrong. However, it did change how it works in that aspect, you're right.
- Select Row 1 
- DetailRow will show
- Select Row 1 again
- DetailRow will hide, because `DetailRowTrigger` will evaluate to true again but it will toggle it. (Previously it would stay activated here, as row 1 item remains selected, you're right)
  - (Here you could argue it should not toggle it (hide if shown, vice-versa) )
    - But if you don't toggle, then you loose that feature which is also pretty good in my opinion....

But maybe we just need to give more control/configuration. 
What if we make it so `DetailRowTrigger` has an associated context (`DetailRowContext`), easier for us to extend in the future without being a breaking change again, and we could introduce something like one or multiple of these
 `TriggerOnRowClick`, `TriggerOnSelectedItem`, `Toggleable`? This should solve your problem

@stsrki ?

**Comment by itsLollo1000** [comment]
> Ah, I see. You are right.
> 
> You might still be able to achieve what you want with `RowSelectable` on. Just that you have to re-trigger `ToggleDetailRow`. So that it toggles it back on, ah?
> 
> I don't think our change in making it so that it now only evaluates on row click is wrong. However, it did change how it works in that aspect, you're right.
> 
> * Select Row 1
> * DetailRow will show
> * Select Row 1 again
> * DetailRow will hide, because `DetailRowTrigger` will evaluate to true again but it will toggle it. (Previously it would stay activated here, as row 1 item remains selected, you're right)
>   
>   * (Here you could argue it should not toggle it (hide if shown, vice-versa) )
>     
>     * But if you don't toggle, then you loose that feature which is also pretty good in my opinion....
> 
> But maybe we just need to give more control/configuration. What if we make it so `DetailRowTrigger` has an associated context (`DetailRowContext`), easier for us to extend in the future without being a breaking change again, and we could introduce something like one or multiple of these `TriggerOnRowClick`, `TriggerOnSelectedItem`, `Toggleable`? This should solve your problem
> 
> @stsrki ?
Well you are right. It is not a bug but for our use it sort of is. Currently we have disabled RowSelectable since re-trigger the DetailRow would cause it to reload all that data again. 

This sounds quite good! So that you have different options on what should happen on a row click. This then should add the old behaviour back. :)

**Comment by David-Moreira** [comment]
>Ah, I see. You are right.

>You might still be able to achieve what you want with RowSelectable on. Just that you have to re-trigger ToggleDetailRow. So that it toggles it back on, ah?

>I don't think our change in making it so that it now only evaluates on row click is wrong. However, it did change how it works in that aspect, you're right.

>Select Row 1
DetailRow will show
Select Row 1 again
DetailRow will hide, because DetailRowTrigger will evaluate to true again but it will toggle it. (Previously it would stay activated here, as row 1 item remains selected, you're right)
(Here you could argue it should not toggle it (hide if shown, vice-versa) )
But if you don't toggle, then you loose that feature which is also pretty good in my opinion....
But maybe we just need to give more control/configuration.
What if we make it so DetailRowTrigger has an associated context (DetailRowContext), easier for us to extend in the future without being a breaking change again, and we could introduce something like one or multiple of these
TriggerOnRowClick, TriggerOnSelectedItem, Toggleable? This should solve your problem

@stsrki ?

**Comment by stsrki** [comment]
> What if we make it so `DetailRowTrigger` has an associated context (`DetailRowContext`), easier for us to extend in the future without being a breaking change again, and we could introduce something like one or multiple of these
> `TriggerOnRowClick`, `TriggerOnSelectedItem`, `Toggleable`? This should solve your problem

I'm not completely sure that I understood this. Do you want to replace the `TItem` argument with the `DetailRowTriggerContext`? And then `TriggerOnRowClick`, `TriggerOnSelectedItem`, `Toggleable` would be an enum argument with the information of how the row was triggered?

**Comment by David-Moreira** [comment]
Yes, that's it. That should solve a feature which we've kinda altered slightly. And let us have that context if we want to add in more stuff in the future.

The `Toggleable` would probably be a flag, not sure yet. (And this is the thing that's different from the previous version, since now it's "toggleable").
The `TriggerOnRowClick`, `TriggerOnSelectedItem` could be an enum.

Altough `TriggerOnRowClick` , `TriggerOnSelectedItem` should be almost logically the same (though an item might be already selected on row click.)

**Comment by David-Moreira** [comment]
@stsrki agree?

**Comment by stsrki** [comment]
@David-Moreira Yes, seems good to me.
