### ISSUE TITLE
Getting the current data displayed by a grid

### ISSUE THREAD

**Issue by itsLollo1000** [Megabit/Blazorise#3227]
Hey,

a well wanted feature of the grid would be to have a function, which gives me a list or something of the current displayed data after a filter is applied. This would reduce a lot of work and time for us, instead of refiltering all the data.

I dont know how much effort this "function" is but we would greatly appreciate it. (very usefull for exporting and other stuff)

Thanks

**Comment by David-Moreira** [comment]
We already have that calculated internally, I guess it can't hurt exposing our getter for `IEnumerable<TItem> DisplayData`.
As a temporary workaround you can use reflection to obtain it. (This isn't recommended in the long run, it's just as you wait that Blazorise exposes this.)

**Comment by stsrki** [comment]
I guess we can do that for v1.0.
