### ISSUE TITLE
Bar Mode attribute prevents anonymous users from seeing LayoutSider content

### ISSUE THREAD

**Issue by PunzunLtd** [Megabit/Blazorise#3236]
Cross-posted with [StackOverflow](https://stackoverflow.com/questions/70372290/blazorise-layoutsider-not-visible-to-anonymous-users)

I'm building a .NET 6.0 Blazor Web Server app using OpenID authentication. I have determined that the presence of the Mode attribute in a Bar inside a LayoutSider prevents anonymous users from seeing any of the content within the layout sider area.

MainLayout.razor:

```
<Layout Sider="true">
        <LayoutSider>
            <LayoutSiderContent>
                <Bar Breakpoint="Breakpoint.Desktop" NavigationBreakpoint="Breakpoint.Tablet" ThemeContrast="ThemeContrast.Dark"
                      Mode="BarMode.VerticalInline" CollapseMode="BarCollapseMode.Small">
                    <BarToggler />
                    <BarBrand>
                        <BarItem>
                            <BarLink To="">
                                <BarIcon IconName="_customIcon" />
                                My SIte
                            </BarLink>
                        </BarItem>
                    </BarBrand>
                    <NavMenu />
                </Bar>
            </LayoutSiderContent>
        </LayoutSider>

        <Layout>
            <LayoutHeader Fixed="true">
                <Bar @bind-Visible="@_topbarVisible" Breakpoint="Breakpoint.Desktop" Background="Background.Primary" ThemeContrast="ThemeContrast.Light">
                    <BarBrand>
                        <BarItem>
                            <BarLink To="">
                                <BarIcon IconName="FontAwesomeIcons.CloudSun" />
                                My Site
                            </BarLink>
                        </BarItem>
                    </BarBrand>
                    @* ReSharper disable once UnknownCssClass *@
                    <BarMenu Class="justify-content-end">
                        <BarEnd>
                            <AuthorizeView>
                                <Authorized>
                                    <BarItem>
                                        <Blazorise.Icon Name="FontAwesomeIcons.User" Visibility="Visibility.Visible" />
                                        Hi, @context?.User?.Identity?.Name
                                    </BarItem>
                                </Authorized>
                            </AuthorizeView>
                            <BarItem>
                                <LoginDisplay />
                            </BarItem>
                        </BarEnd>
                    </BarMenu>
                </Bar>
            </LayoutHeader>

            <LayoutContent Padding="Padding.Is4.OnX">
                @Body
            </LayoutContent>

            <LayoutFooter Fixed="true" Padding="Padding.Is4.OnX">
                Copyright &copy;@DateTimeOffset.UtcNow.Year Inner Drive Technology.
            </LayoutFooter>
        </Layout>

    </Layout>
```

Program.cs contains:

```
builder.Services.AddRazorPages(options =>
{
    options.Conventions.AllowAnonymousToFolder("/");
    options.Conventions.AllowAnonymousToPage("/Index");
    options.Conventions.AllowAnonymousToFolder("/_content");
    options.Conventions.AllowAnonymousToFolder("/Pages");
    options.Conventions.AllowAnonymousToFolder("/Shared");
});
```
 
In the Bar tag within the LayoutSiderContent tag, when the Mode attribute is present, the entire sider is hidden for anonymous users. When it's absent, the entire sider is visible. Any value of the Mode attribute causes the problem.

The source code is the same whether the user is logged in or not. Chrome tools show no "unauthorized" errors when downloading JavaScript or CSS assets.

**Comment by PunzunLtd** [comment]
More info:

1. When not authenticated, the `b-bar-initial` class applies to the `<nav>` tag just inside the `b-layout-sider-content` `<div>`. Also present on the `<nav>` is `data-broken="true"`. Tracing through the Blazorise code, it looks like this means the UI doesn't believe it has finished initializing when it stops receiving data from the host.
2. The dev tools window shows that there is a Cross-Origin Read Block (CORB) on the response from https://logon.microsoftonline.com.
3. There is also a Failed to Fetch error in `blazor.server.js`.

Hypothesis: the CORB error causes the Blazorise JS code to fail, so initialization never finishes. I'm now trying to figure out how to allow the app to ignore CORS on logon.microsoftonline.com

**Comment by David-Moreira** [comment]
That seems something on your side that's causing the components not to initialize properly. Right?
Keep us posted.

If you want us to take a look and help you out, it's easier to actually prepare a sample repository if you'd be so kind!

**Comment by PunzunLtd** [comment]
OK, if I can't get this solved (or at least identified) in another couple of hours, I'll try to reproduce it in another repository.

**Comment by PunzunLtd** [comment]
I'm getting this when not authenticated:

```
Access to fetch at 'https://login.microsoftonline.com/{app ID}/oauth2/v2.0/authorize?client_id={client ID}&redirect_uri=https%3A%2F%2Flocalhost%3A7103%2Fsignin-oidc&response_type=id_token&scope=openid%20profile&response_mode=form_post&nonce={nonce}&client_info=1&x-client-brkrver=IDWeb.1.21.1.0&state={state}&x-client-ver=6.15.0.0' (redirected from 'https://localhost:7103/_blazor/initializers') from origin 'https://localhost:7103' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
blazor.server.js:1 GET https://login.microsoftonline.com/{app ID}/oauth2/v2.0/authorize?client_id={client ID}&redirect_uri=https%3A%2F%2Flocalhost%3A7103%2Fsignin-oidc&response_type=id_token&scope=openid%20profile&response_mode=form_post&nonce={nonce}&client_info=1&x-client-brkrver=IDWeb.1.21.1.0&state={state}&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=6.15.0.0 net::ERR_FAILED 200
(anonymous) @ blazor.server.js:1
Gn @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
blazor.server.js:1   Uncaught (in promise) TypeError: Failed to fetch
    at blazor.server.js:1
    at Gn (blazor.server.js:1)
    at blazor.server.js:1
    at blazor.server.js:1
```

**Comment by David-Moreira** [comment]
Yep it seems it's causing your blazor server app to crash. 

You'll have to figure out that cors issue. Unfortunatly I prsonally haven't implemented Open Auth in recent times so I can't really help you... 

That seems like an ajax request that's being issued behind the scenes? I think you'll have to configure CORS to permit access to the resource by using the 'Access-Control-Allow-Origin' header. But then again, not sure what libraries are you using and how is that abstracted from you....

**Comment by PunzunLtd** [comment]
Here's the minimum app that exhibits the problem. It's an out-of-the-box .NET 6 Blazor app with Blazorise added. [Demo app](https://weathernow5.blob.core.windows.net/images/BlazorCorsProblem.zip)

**Comment by PunzunLtd** [comment]
OK, I am able to get the CORS error in the out-of-the-box Blazor Server app simply by adding this:

```
builder.Services.AddRazorPages(options =>
{
	options.Conventions.AllowAnonymousToFolder("/");
	options.Conventions.AllowAnonymousToPage("/Index");
	options.Conventions.AllowAnonymousToFolder("/_blazor");
	options.Conventions.AllowAnonymousToFolder("/_content");
	options.Conventions.AllowAnonymousToFolder("/Pages");
	options.Conventions.AllowAnonymousToFolder("/Shared");
});
```

The key difference is that the OG Blazor app displays the side nav menu and the Blazorise app does not. I think the problem is that a Blazorise component somewhere decides that the fetch exception is fatal, and stops trying to load the sidebar. Or alternately, that it loads things in a different order, so that the OG version has already rendered everything when the exception pops while the Blazorise version has not.

**Comment by PunzunLtd** [comment]
Well, this was fun. And all that CORS stuff was a red herring.

The issue: the default AddAuthorization service provider options blocked a request somewhere, so removing it allowed all the page components to load, even while keeping the authentication-required bits hidden.

```
builder.Services.AddAuthorization(options =>
{
	// By default, all incoming requests will be authorized according to the default policy
	//options.FallbackPolicy = options.DefaultPolicy; // Removed this line
});
```

**Comment by svenbatalla** [comment]
I can confirm that I received a similar issue complaining of CORS problems when the user was not authenticated. This broke initialization and caused the app to stop working. Applying the fix suggested by @PunzunLtd resolved the issue. If I could somehow give you upvotes, I would.
