### ISSUE TITLE
(Blazor) Modal which is shown off screen on animated page when page scrolled scrolled down

### ISSUE THREAD

**Issue by marcdieters** [Megabit/Blazorise#3237]
**Describe the bug**
(Blazor) Modal which is shown when browser window is scrolled down is shown of screen.
![image](https://user-images.githubusercontent.com/24914093/146526126-669f632a-fd4d-4692-ba3e-a14dfcc0387e.png)

Is this case, I clicked on the hamburger button in the bottom right corner of an item. 
When removing the animation tag from the page, the modal is shown centered, as expected.

I tried a normal bootstrap modal as well as a Blasorize modal, both have same behaviour.

**To Reproduce**
1. Add animation tag to a page <Animate Animation="Animations.FadeIn" Duration="TimeSpan.FromSeconds(1)">
2. Create a basic blasorize modal

```
<Modal @ref="modalRef" ShowBackdrop="false">
    <ModalContent Size="ModalSize.Large" Centered="false">
        <ModalHeader>
            <ModalTitle>
                <h5 class="modal-title" id="titleLabel">@Name Options</h5>
            </ModalTitle>
            <CloseButton />
        </ModalHeader>
        <ModalBody>
            <p>
            </p>
        </ModalBody>
        <ModalFooter>
            <a class="btn btn-outline-primary" @onclick="@Close">Close</a>
        </ModalFooter>
    </ModalContent>
</Modal>
```

**Expected behavior**
I would expect the modal to behave the same way as it would without the <animate> tags

**Comment by David-Moreira** [comment]
DUplicate issue. #3238
Closing.
