### ISSUE TITLE
Remove inline styles from Blazorise

### ISSUE THREAD

**Issue by damienbod** [Megabit/Blazorise#3242]
Thanks for this great project!

Would it be possible to remove all inline styles from any components. It would be good to support this so that a stronger CSP can be defined for Blazor production deployments.

The header in the DataGrid uses the style attribute. Could this be replaced by a class definition?

```
<th scope="col" style="cursor: pointer">Subject</th>
```

Greetings Damien

**Comment by stsrki** [comment]
Yeah, I think it could be done. Inline-styles are used rarely in Blazorise. Mostly in places where it needs to match CSS providers (eg, Bootstrap, or Bulma). Although they cannot be removed completely we will try to remove them where we can.

**Comment by stsrki** [comment]
It is, but it is going into the next milestone.

**Comment by damienbod** [comment]
@stsrki Thanks
