### ISSUE TITLE
Do you have setting for showing DataGridAggregate row on the top of table?

### ISSUE THREAD

**Issue by tatti9018** [Megabit/Blazorise#3246]
Do you have setting for showing DataGridAggregate row on the top of table?

It would be very helpful if DataGrid has setting for showing DataGridAggregate row on the top of table (after header row)

And can you add setting css class to DataGridAggregate component ?

**Comment by David-Moreira** [comment]
I guess we could take it as a feature and implement similar to how `PagerPosition` works. Meaning that they'd likelly be placed under the filter row in the table header for `Position.Top`
Agree @stsrki ?

**Comment by stsrki** [comment]
I'm not exactly sure what would be the right place to place the aggregates. @tatti9018 Do you have an example with the screenshot? It could help us.

**Comment by tatti9018** [comment]
As for example
![image](https://user-images.githubusercontent.com/61416594/147752755-86200811-ca3f-44ae-8e5b-542ca4d1f699.png)

**Comment by tatti9018** [comment]
Hello @stsrki  and @David-Moreira. Please say if you're going to work on this feature, because I'm deciding whether to use this component or not and I need to have the summary on top as necessary.

**Comment by David-Moreira** [comment]
Seems worth it in my opnion. Below the current filter row, close to the rows containing the data is what seems best.
@stsrki ?

**Comment by stsrki** [comment]
@David-Moreira That seems like a good place to put the aggregate row. We also need to have `GroupPosition` with `Bottom` and `Top` values to define its location.
