### ISSUE TITLE
Date in the new section

### ISSUE THREAD

**Issue by itsLollo1000** [Megabit/Blazorise#3248]
Hey,

as part of using your Component Library, I more often find myself reading your [news](https://blazorise.com/news). 
But I sometimes miss the information of when a certain post was released. 

Maybe you could add a tag or something which tells me when the news came out 💯 

Kind regards

**Comment by stsrki** [comment]
Good idea. I will add:

- post date
- creator name(s)

**Comment by stsrki** [comment]
![image](https://user-images.githubusercontent.com/900302/146952164-deff7e72-3fdf-47e8-a12d-d8b45d2ef7ea.png)

How about this?

**Comment by itsLollo1000** [comment]
> ![image](https://user-images.githubusercontent.com/900302/146952164-deff7e72-3fdf-47e8-a12d-d8b45d2ef7ea.png)
> 
> How about this?

Yes that looks very good!

**Comment by stsrki** [comment]
Cool. It's already up :)

Closing now!

**Comment by itsLollo1000** [comment]
> 

Yes have seen it a minute ago! Very happy :) and cool feature with the reading time ;) at first I thought it tells something like 3 mins ago.
