### ISSUE TITLE
DataGrid multiselection crash in docs

### ISSUE THREAD

**Issue by itsLollo1000** [Megabit/Blazorise#3249]
Hey,

I was scrolling through the docs for the new [selection](https://blazorise.com/docs/extensions/datagrid/selection) changes and noticed, when trying to deselect the last item in multi-selection it crashes.

To reproduce: 
Select any item from one of the two grids at the bottom. Then try to deselect it.

![image](https://user-images.githubusercontent.com/10349466/146960980-55afb439-1ea3-4395-8180-982a26475c12.png)
![image](https://user-images.githubusercontent.com/10349466/146961426-65a91b3c-91d6-4f5d-b4e8-a3a4976841a0.png)

Kind regards

**Comment by David-Moreira** [comment]
Thanks for noticing it is indeed a bug introduced on the last release.

**Comment by itsLollo1000** [comment]
No problem ;)

**Comment by Mr-Pearce** [comment]
Just updated to 0.9.5.3 and it crashes with my datagrid like in the example i made with the bug before https://github.com/Megabit/Blazorise/issues/3233#issuecomment-994433885
The example also crashes when deselecting everything like in the original post above
**Error in Firefox log** 
```
[2021-12-28T14:57:59.437Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazorise.DataGrid.DataGrid`1.CheckMultipleSelectionSetEmpty(ParameterView parameters)
   at Blazorise.DataGrid.DataGrid`1.SetParametersAsync(ParameterView parameters) blazor.server.js:21:24815
```

Its Probably the same error?

**Comment by David-Moreira** [comment]
Seems like it.
@stsrki  has it been released?
