### ISSUE TITLE
SelectedValue - Cannot Be Empty String

### ISSUE THREAD

**Issue by LeanTolo** [Megabit/Blazorise#3254]
I would like to Set default SelectedValue as an empty string, also that the empty string be a Select Item with Value="" bue always say that cannot be empty or whitespace.

`<Field>
     <FieldLabel>Jurisdicciones</FieldLabel>
         <Select TValue="string" SelectedValue="" SelectedValueChanged="@OnSelectedValueChangedIIBB">
         <SelectItem Value=""></SelectItem>
                             ...foreach with real values....                                                       
         </Select>
</Field>
`

Don't want to report it as a bug but i didnt found any solution to this!

**Comment by David-Moreira** [comment]
I think you are confusing things haha.
SelectedValue should be bound to a field or property, in this case of type string. That field or property can have a starting value of empty.

So, something like this:
`<Field> <FieldLabel>Jurisdicciones</FieldLabel> <Select TValue="string" SelectedValue="MySelectedValue" SelectedValueChanged="@OnSelectedValueChangedIIBB"> <SelectItem Value=""></SelectItem> ...foreach with real values.... </Select> </Field>`

Let us know if this helps!

**Comment by stsrki** [comment]
When you don't bind to a variable, like `SelectedValue="@(string.Empty)" `, the component value will be resetting every time anything on page is refreshed. That's how declarative(Blazor) code works. The rule of thumb is, always bind to variable.

**Comment by David-Moreira** [comment]
Yep, right. That's what lead to my initial answer. I was just showcasing the exact working example that @LeanTolo was looking for.
Up to him and his use case on how to implement it. :)

**Comment by David-Moreira** [comment]
These response's should have helped OP. Closing issue. Just let us know if you have any other doubts or issues.
