### ISSUE TITLE
📅 - Blazorise Roadmap

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#3256]
These are the general things that we plan. Keep in mind that it may change.

## v1.2

- [ ] TailwindCSS support
- [ ] PivotGrid component

## v1.3

- [ ] Scheduler component
- [ ] Calendar component
- [ ] RTL support

## TBA

- [ ] Material 5 support

**Comment by kamilkosek** [comment]
Hi Mladen,
I saw you already mentioned the scheduler component. 
Also a nice feature would be a calendar component like [this](https://observablehq.com/@d3/calendar) or [this](https://nivo.rocks/calendar/)
This way it would be possible to combine them bouth, i.e. select a week/day from the calendar and view the schedule.

Regards,
Kamil

**Comment by wojtj** [comment]
I'd love to be able to use DatePicker with the [Inline flag from flatpickr](https://flatpickr.js.org/examples/#inline-calendar).

Even more so if the text box can be hidden as well. Would help support a scheduler.

**Comment by kwackerz** [comment]
is there any chance of adding grouping to the datagrid? 
where the user can drag  column headers to a grouping area  
that would be amazing!

**Comment by David-Moreira** [comment]
@kwackerz 
- #3120
- #2668

**Comment by MrExpreess** [comment]
What about RTL (Right-to-Left) support,  do you have plan to support it?

**Comment by stsrki** [comment]
Definitely yes. That's why we have renamed all our enums from Left/Right to Start/End in the last release. It was preparation for RTL support. Not sure is it going to be in v1.1 as it is quite full, but we can make it for 1.2.

**Comment by paulsterling** [comment]
Hi @stsrki and @David-Moreira -

We're looking forward to the Scheduler / Calendar features planned for 1.2. We currently are using the [https://github.com/gismofx/toast_ui.blazor_calendar](https://github.com/gismofx/toast_ui.blazor_calendar) wrapper for the javascript TUI Calendar and it works "okay" but is lacking some features and robustness. We've extended the component  for our use (adding some specific timezone logic and our custom UI using Blazorise Modals) and are happy enough. When you get to the planning phase for 1.2 I'd be happy to add my insight based on our experience with toast_ui.blazor_calendar wrapper. Please feel free to reach out if that might be useful.

Thanks for the work on Blazorise! We are a Professional Plan subscriber and have our v1.0 Go Live set for 16 May 2022...fingers crossed!

**Comment by timahrentlov** [comment]
Really looking forward to the Tailwind support!

**Comment by stsrki** [comment]
> Really looking forward to the Tailwind support!

Tailwind is planned for the next release. You can keep track on all ideas how to make it https://github.com/Megabit/Blazorise/issues/825

Any advice is much appreciated.
