### ISSUE TITLE
Select Multiple doesn't highlight selected values

### ISSUE THREAD

**Issue by gdunit** [Megabit/Blazorise#3257]
**Describe the bug**
I'm having trouble getting a [Flags] enum representing working days to work with the `<select>` component in Multiple mode.
The enum allows selection of one or more days of the week (or also a 'none' default value).

The selections, when made, flash up briefly on the select list but then appear to be cleared immediately afterwards.

My view model has a flags enum property - WorkingDays.
As the multiple mode has to bind to an IReadOnlyList<WorkingDay> , I created another property in my view model to represent this:

```
  // The actual flags enum property
  public WorkingDays WorkingDays { get; set;}

  // Value that can work with <Select> in multiple mode
  public IReadOnlyList<WorkingDays> WorkingDaysList
  {
      get
      {
          // This turns the flags enum value into an IReadOnlyList<WorkingDays>
          return GetWorkingDaysList();
      }
      set
      {
          // You guessed it, same in reverse - updates the flags enum value from changed list
          SetWorkingDaysFromList(value);
      }
  }
```

My select component markup then looks like this:

```
    <Select Multiple="true" TValue="WorkingDays" @bind-SelectedValues="ViewModel.WorkingDaysList">
        @foreach (WorkingDays wd in Enum.GetValues<WorkingDays>())
        {
            <SelectItem TValue="WorkingDays" Value="@wd">
                @wd.ToString()
            </SelectItem>
        }             
    </Select>
```

I have created a repro, please see below:

**To Reproduce**
1. See repro - https://github.com/gdunit/FlagsEnumSelectRepro
2. The select component does not display the default value set in the OnInitializedAsync() method (no select items are highlighted)
3. When selecting one or more values, the selection flashes on and off almost immediately

**Expected behavior**
When the select component is initialized, the values should be shown highlighted
When the values are changed, the currently selected ones should be shown highlighted

**Comment by David-Moreira** [comment]
Hello,
Can confirm we are not handling enums correctly, out internal value setter is sending the enum numbers instead of the string representation to the js setter.

We'll let you know as soon as we fix this. 
In the meantime, here's a workaround for your problem, by using strings instead:
```
<Select Multiple="true" TValue="string" @bind-SelectedValues="WorkingDaysValueList">
    @foreach (WorkingDays wd in Enum.GetValues<WorkingDays>())
    {
        <SelectItem TValue="WorkingDays" Value="@wd">
            @wd.ToString()
        </SelectItem>
    }             
</Select>

<Div>
    Your Selection is: 
    @WorkingDaysValue.ToString()
</Div>
@code {
        protected WorkingDays WorkingDaysValue { get; set; }

        protected IReadOnlyList<string> WorkingDaysValueList 
        {
            get
            {
                return GetWorkingDaysList();
            }
            set
            {
                SetWorkingDaysFromList(value);
            }
        }

        public List<string> GetWorkingDaysList()
        {
            List<string> result = new List<string>();
            // Iterate over the flags
            foreach (WorkingDays wd in Enum.GetValues(typeof(WorkingDays)))
            {
                if (WorkingDaysValue.HasFlag(wd) && wd != WorkingDays.None)
                {
                    result.Add(wd.ToString("g"));
                }
            }
            if (result.Count == 0)
            {
                result.Add(WorkingDays.None.ToString("g"));
            }
            return result;
        }

        public void SetWorkingDaysFromList(IReadOnlyList<string> input)
        {
            // Iterate over the flags
            foreach (WorkingDays wd in Enum.GetValues(typeof(WorkingDays)))
            {
                if (input.Contains(wd.ToString("g")))
                {
                    if (!WorkingDaysValue.HasFlag(wd))
                    {
                        WorkingDaysValue |= wd;
                    }
                    else
                    {
                        WorkingDaysValue &= ~wd;
                    }
                }
            }
        }

        protected override async Task OnInitializedAsync()
        {
            // Simulate loading data from db
            await Task.Delay(1000);
            await Task.Run(() => { WorkingDaysValue = WorkingDays.Monday | WorkingDays.Tuesday; });
            await base.OnInitializedAsync();
        }

        [Flags]
        public enum WorkingDays
        {
            None = 0,
            Sunday = 1,
            Monday = 2,
            Tuesday = 4,
            Wednesday = 8,
            Thursday = 16,
            Friday = 32,
            Saturday = 64

        }
}
```

**Comment by stsrki** [comment]
@David-Moreira I don't think we do anything wrong here. The app serializer should be responsible for sending the appropriate values to the JS. We should not be responsible to decide what is the right way. One project can use enum values, the other can use enum names. It all depends from project to project. And it must be defined in the app Startup by the developers themselves.

**Comment by David-Moreira** [comment]
I don't know... That's usually a global change? What if the project wants to serialize enum values, but still want Select to work with enum names, like here?

And it didn't actually hit me you could configure the javascript serializer to change the behaviour, I'll try that out later. haha

**Comment by David-Moreira** [comment]
Ok, so according to what @stsrki said, I found this additional solution which works pretty well. So I guess there are pretty good solutions by configuring accordingly, and we do not need to do anything here, just that in my opinion the docs should reflect this caveat.
@stsrki agree with updating the docs mentioning that the javascript serializer defaults should be taken into account when dealing with `enums`? 

```
  [Flags]
  [JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))] 
        public enum WorkingDays
        {
            None = 0,
            Sunday = 1,
            Monday = 2,
            Tuesday = 4,
            Wednesday = 8,
            Thursday = 16,
            Friday = 32,
            Saturday = 64

        } 
```

Also I didn't actually find a way to set the defaults globally for Blazor... similar to how you do it with controllers:
```
    services.AddControllers().AddJsonOptions( options =>
    {
        options.JsonSerializerOptions.Converters.Add( new JsonStringEnumConverter() );
    } );
```
Do you happen to know it? haha

**Comment by stsrki** [comment]
@David-Moreira That seems like a great solution. And it might be good to mention it in the docs. Also, plan it for a community article?

For your question with global JSON settings. As far as I know, it is only possible if you inherit and implement your own `JsonStringEnumConverter`. There is no simple attribute to use.

**Comment by gdunit** [comment]
Thanks both for the solution. I can confirm that specifying the JsonConverter attribute as JsonStringEnumConverter against the enum works a treat.
