### ISSUE TITLE
AutoComplete: AsyncValidator

### ISSUE THREAD

**Issue by KevinBassaDevelopment** [Megabit/Blazorise#3259]
With version 0.9.4 we got async validation for fields: ` <Validation AsyncValidator="@ValidateNameAsync">`

It would be really nice if Autocomplete also gets the AsyncValidator option, as the current one does not support async!

**Comment by stsrki** [comment]
I was sure it was done in 0.9.5 but apparently not. Thanks for letting us know. We will do it for v1.0.

**Comment by KevinBassaDevelopment** [comment]
Great to hear!
