### ISSUE TITLE
Charts: Support for Time Cartesian Axis

### ISSUE THREAD

**Issue by InzeNL** [Megabit/Blazorise#3263]
For charts, there is a very limited implementation of the Time Cartesian Axis.
Currently, this axis *can* be created, by setting the "type" configuration option, this makes the axis work as expected.

However, it is missing some of the nice features Chart.js has when it comes to handling these time labels.
It would be nice to see the other configuration options from the documentation ([https://www.chartjs.org/docs/2.9.4/axes/cartesian/time.html](https://www.chartjs.org/docs/2.9.4/axes/cartesian/time.html)) as part of the `Axis` object

## Additional context
After implementation, this Axis should be able to work:
```csharp
new Axis()
{
    Type = "time",
    Distribution = "linear",
    Bounds = "data",
    Ticks = new {
        Source = "auto"
    },
    Time = new {
        DisplayFormats = new {
            Millisecond = "h:mm:ss.SSS a",
            Second = "h:mm:ss a",
            Minute = "h:mm a",
            Hour = "hA",
            Day = "MMM D",
            Week = "ll",
            Month = "MMM YYYY",
            Quarter = "[Q]Q - YYYY",
            Year = "YYYY"
        },
        IsoWeekday = false,
        Parser = "dddd, MMMM Do YYYY, h:mm:ss a",
        Round = "millisecond",
        TooltipFormat = "dddd, MMMM Do YYYY, h:mm:ss a",
        Unit = "second",
        StepSize = 1,
        MinUnit = "millisecond"
    }
}
```
In the code above, I use anonymous objects as parameters, I reckon it would be better to make these pre-defined objects. (For example, Ticks is already an object, this `Source` parameter would be added to that existing object.

**Comment by InzeNL** [comment]
Some notes:
* *Adapters.Date*:
Described in the chart.js documentation. Since it is an anonymous object, we could just opt to add this, and leave all implementation to the user.

* *DisplayFormat*:
For the display formats, I am currently using the Moment.js format, since this is what Cart.js uses. Would we want that format to stay this way, or would we want a converter put in, that translates it from the C# format (https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings) to Moment.js format (https://momentjs.com/docs/#/displaying/format/). Personally I don't think this would be worth the effort of creating a converter to, since the format is not used in the C# way, ever.

* *Parser*:
Currently, I think having just the string as a parser should be fine. I don't have an approach for having the function parameter here.

* *Round* and *Unit*:
These variables are a string, but can also be `false` (because: JavaScript), what would be a proper approach of allowing this as a value. Since it is the default value, we could opt that `null == false`

**Comment by stsrki** [comment]
I can schedule it for v1.0 if there is enough room. Shouldn't need to be too hard. https://www.chartjs.org/docs/latest/axes/cartesian/time.html

Just a note. In the next version, we're switching to Charts v3.x.
