### ISSUE TITLE
Autocomplete Multiple does not appear to display selected text inside the textbox

### ISSUE THREAD

**Issue by ledpup** [Megabit/Blazorise#3268]
Using the following autocomplete code, I get:

![image](https://user-images.githubusercontent.com/1639322/147610585-4f81094f-e31e-4f7e-b267-f46b60f62ae8.png)

I was expecting the textbox to look like the "Multiple" example, except "1930" appearing the textbox.

![image](https://user-images.githubusercontent.com/1639322/147610662-ee42fd5a-8b43-44b0-8100-0f2eb2e2d0fb.png)

The autocomplete component otherwise appears to function like an autocomplete. I can add a new entry and it updates. I've tried DataYears as a class with a string and short for text and value; it didn't make a difference. The textbox looks more like a single, not a multiple. Am I missing a CSS file perhaps??

```
<Column ColumnSize="ColumnSize.Is3">
    <Autocomplete TItem="short"
            TValue="short"
            Data="@DataYears"
            TextField="@((item) => item.ToString())"
            ValueField="@((item) => item)"
            Placeholder="Search..."
            Multiple
            FreeTyping
            SelectedValuesChanged="@OnSelectedValuesChanged"
            SelectedValues="@multipleSelectionData"
            SelectedTexts="@multipleSelectionTexts"
    >
        <NotFoundContent>@context was not found</NotFoundContent>
    </Autocomplete>
</Column>

<Field Horizontal="true">
    <FieldBody ColumnSize="ColumnSize.Is12">
        Selected Values: @string.Join(',', multipleSelectionData)
    </FieldBody>
    <FieldBody ColumnSize="ColumnSize.Is12">
        Selected Texts: @string.Join(',', multipleSelectionTexts)
    </FieldBody>
</Field>

@code {
    List<short> DataYears { get; set; }
    List<short> multipleSelectionData;
    List<string> multipleSelectionTexts = new();

    async Task OnSelectedValuesChanged(List<short> values)
    {
        await InvokeAsync(StateHasChanged);
    }

    protected override async Task OnInitializedAsync()
    {
        DataYears = new List<short> { 1930, 1931 };
        multipleSelectionData = new List<short> { 1930 };
        multipleSelectionTexts = multipleSelectionData.Select(x => x.ToString()).ToList();
    }
}
```

**Comment by David-Moreira** [comment]
Hello,
I think you are missing styling somehow yes.

![image](https://user-images.githubusercontent.com/22283161/147615063-87d07264-fc36-4d3f-acf5-68e0352a38f5.png)

What provider are you using? Bootstrap? Can you provide a repository or information about the styles being loaded in your `<head>` section, please.

**Comment by ledpup** [comment]
Yess, it's styling. I fully implemented the usage for bootstrap5 at https://blazorise.com/docs/usage/bootstrap5.

I now get the NavMenu (out of the box Blazor NavMenu) disappearing on me when doing that, but that has nothing to do with autocomplete, which seems to be working perfectly now.

THANKYOU!

**Comment by David-Moreira** [comment]
Great, no problem, Glad you worked it out! 👍
