### ISSUE TITLE
Modal fullscreen mode not working when modal content size is not default value. 

### ISSUE THREAD

**Issue by tpGroupcare** [Megabit/Blazorise#3271]
**Describe the bug**
Whenever I want a modal where i want to implement a toggle button for fullscreen mode then if the size of modal content is not default value then the fullscreen mode does not go into fullscreen. more like half-screen aligned to the left. Here is a screenshot. 
![image](https://user-images.githubusercontent.com/88434247/147749963-150830d0-c3e4-468f-bf3a-12608ceb9356.png)

I have pretty much copy-pasted your demo example and added a toggle button and set the size to extra large
````
@page "/Test"
<Button Color="Color.Primary" Clicked="@ShowModal">Show Modal</Button>

<Modal @ref="modalRef" >
    <ModalContent Centered="@true" Size="ModalSize.ExtraLarge" Fullscreen="@_fullScreen">
        <ModalHeader>
            <ModalTitle>Employee edit</ModalTitle>
            <Button Clicked="@(() => _fullScreen = !_fullScreen)">toggle fullscreen</Button>
            <CloseButton />
        </ModalHeader>
        <ModalBody>
            <Field>
                <FieldLabel>Name</FieldLabel>
                <TextEdit Placeholder="Enter name..." />
            </Field>
            <Field>
                <FieldLabel>Surname</FieldLabel>
                <TextEdit Placeholder="Enter surname..." />
            </Field>
        </ModalBody>
        <ModalFooter>
            <Button Color="Color.Secondary" Clicked="@HideModal">Close</Button>
            <Button Color="Color.Primary" Clicked="@HideModal">Save Changes</Button>
        </ModalFooter>
    </ModalContent>
</Modal>

@code{
    // reference to the modal component
    private Modal? modalRef;

    private bool _fullScreen = false;

    private Task ShowModal()
    {
        return modalRef!.Show();
    }

    private Task HideModal()
    {
        return modalRef!.Hide();
    }
}
````

If you set size to ModalSize.Default then there is no issue. Hence there lies a workaround where you can toggle the Size to default when ever going into fullscreen mode.

**Comment by stsrki** [comment]
Seems like something your page layout is messing with the CSS. Can you inspect in dev tools and see what might affect it?

**Comment by tpGroupcare** [comment]
hmm I don't think so because I have just commented out everything in my MainLayout.razor except `@Body` So there is no page layout there is only the page generated from the code shown above. 

This is the following html that gets generated. 
![image](https://user-images.githubusercontent.com/88434247/147759536-148a28b0-402f-4809-af27-3dcb195b1871.png)
When i removed xl from the modal-content div then it takes up the fullscreen. 

I have also tried your demo at https://blazorise.com/docs/components/modal and added the modal-xl class to the modal-content div. The exact same thing happens. 
![image](https://user-images.githubusercontent.com/88434247/147759979-9c413d87-a17b-4067-a9e5-92d33c331819.png)

**Comment by stsrki** [comment]
Ah, you don't you to use `Size="ModalSize.ExtraLarge"`. You can remove it.

We might check internally if `Fullscreen` is enabled and then ignore the `Size` parameter.

**Comment by tpGroupcare** [comment]
To be clear I want a button in my modal header where the user can toggle if he/she wants the modal to be fullscreen or not. But besides that I want the non-fullscreen mode to show the modal as size extra large because the default is too small. 

But because things are as they are then when toggling then not only will I have to toggle the `FullScreen` parameter I also have to toggle the `Size` parameter. This just didn't seem like something as by design to me. 

But I have my workaround so no worries.

**Comment by tpGroupcare** [comment]
Now this probably turns more into a suggestion than a bug. But why is `FullScreen` an independent boolean parameter in the `ModalContent` component. Why not extend the `ModalSize` with a fullscreen option along side small, default, large, ExtraLarge

**Comment by stsrki** [comment]
I must admit it's not a bad idea to merge `FullScreen` into `ModalSize` enum. I will try to make it for v1.0.
