### ISSUE TITLE
Configuring the DataGrid popup

### ISSUE THREAD

**Issue by GilShalit** [Megabit/Blazorise#3276]
Hi, is it possible to configure the DataGrid Edit PopUp so that it displays an "Extended Edit" button, which will pass the current entity to an associated procedure?

Thanks!

**Comment by David-Moreira** [comment]
Hello @GilShalit 
Could you elaborate on the feature you're looking for?

I'm pretty sure we already give you enough tools to do what you're requesting.
You set up the DataGrid edit mode to popup, then handle the entity saving in the RowUpdating / RowInserting methods... you can do whatever you want to do... like calling a procedure.

**Comment by David-Moreira** [comment]
Closing the issue. Just let us know if you have any doubts or issues.
