### ISSUE TITLE
Live Chart JavaScript error when hovering over chart. Stops Auto scrolling.

### ISSUE THREAD

**Issue by johndcollins** [Megabit/Blazorise#3282]
**Describe the bug**
"Uncaught TypeError: Cannot read properties of undefined (reading 'skip')" in Live Charts.

**To Reproduce**
1. Go to the Bootstrap 5 Demo site and click on Live Charts under Extensions
2. Open browser console (F12)
3. Hover over the top left Line Chart
4. The Chart will eventually stop scrolling

**Expected behavior**
No js errors and continue scrolling

**Screenshots**
![image](https://user-images.githubusercontent.com/1684130/148022484-b8ef652f-4330-4bc8-83c5-fe301754dd97.png)

**Comment by stsrki** [comment]
This is a known issue in the streaming library that is happening in charts v2.x. Unfortunately, it cannot be fixed on our side.

The good news is, we have recently upgraded everything to charts v3.x and the error has gone. It will be available as part of the Blazorise v1.0, sometime in February.

Closing now.
