### ISSUE TITLE
How to unit test pages that use blazorise?

### ISSUE THREAD

**Issue by baltazarO** [Megabit/Blazorise#3286]
Hello I am trying to use Bunit to unit test my pages. Is there a way to do this? My project uses blazorise 0.9.4.3. From my understanding blazorise has many services that must be mocked for example IJSRunner.

**Comment by David-Moreira** [comment]
Hello,
My guess is that the essential to mock is the js calls yes. 
Please take a look at our existing tests for some examples.
https://github.com/Megabit/Blazorise/tree/master/Tests/Blazorise.Tests/Components

**Comment by baltazarO** [comment]
I am currently using the BlazoriseConfig class in https://github.com/Megabit/Blazorise/blob/master/Tests/Blazorise.Tests/Helpers/BlazoriseConfig.cs. 

So I get an exception for not having a JSRunner for Blazorise.Alert (System.InvalidOperationException : Cannot provide a value for property 'JSRunner' on type 'Blazorise.Alert'.) because my page has an alert component in it. 

Would I have to add in a function in the BlazoriseConfig similar to this:

```public static void AddTextEdit( BunitJSInterop jsInterop )
            {
                AddUtilities( jsInterop );

                var module = jsInterop.SetupModule( new JSTextEditModule( jsInterop.JSRuntime, new VersionProvider() ).ModuleFileName );
                module.SetupVoid( "import", _ => true );
                module.SetupVoid( "initialize", _ => true );
                module.SetupVoid( "destroy", _ => true );
            }```

**Comment by stsrki** [comment]
You're using an older 0.9.4 version, while our `master` branch is on 0.9.5 and up. There were many changes in our JS system and JSRunner is no longer needed. We have moved to the JS modules.

Check here: https://github.com/Megabit/Blazorise/tree/rel-0.9.4/Tests/Blazorise.Tests/Components

**Comment by baltazarO** [comment]
Got a unit test to run. I am doing almost exactly what you guys did. Using the blazoriseConfig to mock the dependencies like jsrunner.

**Comment by stsrki** [comment]
Great to hear that. Is it safe to close the ticket now?

**Comment by baltazarO** [comment]
Yes, if I encounter anything I will open another issue. Thank you guys.
