### ISSUE TITLE
Columns for complex types are not shown

### ISSUE THREAD

**Issue by martinb69** [Megabit/Blazorise#3290]
I am trying to show a grid with data that is composed of objects with 1:1 relation. If I try to achieve this i get unexpected results. In the example below the grid column is ignored. In my full application I get an object already disposed exception. 

**Example data to reproduce**
```
    class Bar
    {
        public string BarValue { get; set; } = "Bar";
    }

    class Foo
    {
        public string FooValue { get; set; } = "Foo";
        public Bar Bar { get; set; } = new Bar();
    }
```
**Expected grid configuration example**
```
<DataGrid TItem="Foo"
          Data="new List<Foo>() { new Foo() }">

    <DataGridColumns>
        <DataGridColumn TItem="Foo" Field="@nameof(Foo.FooValue)" Caption="Foo"/>
        <DataGridColumn TItem="Bar" Field="@nameof(Foo.Bar.BarValue)" Caption="Bar"/>
    </DataGridColumns>
</DataGrid>
```
The "Bar" column is not displayed in the grid while both columns "Foo" and "Bar" were expected.

**Comment by stsrki** [comment]
For nested fields use `<DataGridColumn TItem="Bar" Field="Bar.BarValue" Caption="Bar"/>`.

When `nameof` is used it will only get the last field name, in this case, `BarValue`, which cannot be found in the `TItem`.

**Comment by martinb69** [comment]
Thanks, and yes that was a indeed a mistake in the provided example. 
However, I just checked but after modification it still does not work as expected. When I leave out nameof() for both then I get a System.ArgumentException and when I check with the modified example code below I still get just one column for "Bar". 
```
<DataGrid TItem="Foo"
          Data="new List<Foo>() { new Foo() }">

    <DataGridColumns>
        <DataGridColumn TItem="Foo" Field="@nameof(Foo.FooValue)" Caption="Foo"/>
        <DataGridColumn TItem="Bar" Field="Bar.BarValue" Caption="Bar"/>
    </DataGridColumns>
</DataGrid>
```

**Comment by stsrki** [comment]
TItem must be the same for all columns. Use `TItem="Foo"`.

**Comment by martinb69** [comment]
I have applied your suggestion and the example and production code are now working.
Did I miss some documentation about nested fields or is this part undocumented?

Thanks for the swift support!

**Comment by stsrki** [comment]
They are mentioned in the docs https://blazorise.com/docs/extensions/datagrid/getting-started

But maybe it is hard to miss. We could make it more noticeable.
