### ISSUE TITLE
AutoComplete not working correctly if Data is changed

### ISSUE THREAD

**Issue by GilShalit** [Megabit/Blazorise#3296]
I have a form with a modal dialog that shows an AutoComplete dropdown component.  This works fine.  

The problem is I am trying to load different lists of items into it, so it can be used for multiple tasks. When I replace the list with a different list, the selection made with the previous list is still shown, although that value does not exist in the new list.  If I try to return selectedSearchValue and selectedAutoCompleteText to null before changing the list, I get an error.

How can I flush the autoComplete component so it can be re-used?

I have created a repo of this at https://github.com/GilShalit/AutoComplete-repo

Thanks!

**Comment by David-Moreira** [comment]
Hello @GilShalit 
this is what I get when I run your app. I don't see any AutoComplete? Have you fully commited the example?

![image](https://user-images.githubusercontent.com/22283161/148860473-6731b4d6-9d2c-430a-b6a4-144a0868c670.png)
![image](https://user-images.githubusercontent.com/22283161/148860541-4a1f1237-297f-44c1-af21-ad2f76fda333.png)

**Comment by GilShalit** [comment]
Hi @David-Moreira , you are right obviously - committed but not pushed.

All fixed now.

Thanks!

**Comment by GilShalit** [comment]
Sorry - the solution is quite simple - set selectedSearchValue  = "" to flush the component.  Not sure why I was so sure it needed to be returned to null.

Closing.
