### ISSUE TITLE
Notification (snackbar) css is missing in tutorial and there is probably wrong color in SnackBar package css

### ISSUE THREAD

**Issue by janseris** [Megabit/Blazorise#3303]
Hello, I am trying to use Messages and Notifications.
I use Bootstrap 5. 
In this https://blazorise.com/docs/services/notification tutorial, no css to include is shown (for example for spinkit, css include is shown in tutorial).
Messages work without additional CSS.
Notifications do not work without additional CSS (broken formatting, no colors).

Moreover, you have different "warn" Notification yellow here https://blazorise.com/docs/services/notification and here https://bootstrap5demo.blazorise.com/tests/utilities/services vs in the css included with the Components package, that yellow in the package is much more pale - "background-color: DARKEN(var(--b-snackbar-background, #323232), 30%);"

I use 5.1.3 which is newest now and the https://blazorise.com/docs/usage/bootstrap5 tutorial shows 5.1.1 but that doesn't change the result.

**To Reproduce**
1. install Blazorise.Boostrap, Boostrap5, Components
2. use the following in main <head> definition (_Layout component):

```
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">//required for Blazorise icons
<link href="_content/Blazorise.Bootstrap5/blazorise.bootstrap5.css" rel="stylesheet" /> //required for Blazorise
<link href="_content/Blazorise.SpinKit/blazorise.spinkit.css" rel="stylesheet" /> // required for Blazorise Spinkit
<link href="_content/Blazorise.SnackBar/blazorise.snackbar.css" rel="stylesheet" /> // required for Blazorise Notifications

```

**Expected behavior**
The color matches the tutorial color
Or at least it matches the bootstrap 5 color but neither is true (and what is worse, 

**Screenshots**
![blazorise yellow problem](https://user-images.githubusercontent.com/64279914/148848279-8d82f903-1379-4011-9f3a-dda3d811b02a.png)

**Comment by stsrki** [comment]
Do you have the `ThemeProvider` in the `App.razor`? That is the only difference I can think of that is between our demo and your app.

**Comment by janseris** [comment]
> Do you have the `ThemeProvider` in the `App.razor`? That is the only difference I can think of that is between our demo and your app.

So the thing is that the colors of mine are original and yours are custom Theme? That could be the reason. Because I don't have any custom theme applied and it was not required by any of the tutorials.

**Comment by stsrki** [comment]
Yes, in the demo we have theming enabled by default. If disabled it will use the color scheme from Bootstrap.

**Comment by janseris** [comment]
Great, thank you for quick feedback! You can mark it as solved as it is not a bug.
