### ISSUE TITLE
We need a way to configure SaveCommand and a CancelCommand with ButtonRow

### ISSUE THREAD

**Issue by GilShalit** [Megabit/Blazorise#3306]
In the DataGrid, when using the DataGridCommandColumn, it is possible to configure the Save and Cancel buttons of the Edit PopUp dialog using the SaveCommandTemplate and CancelCommandTemplate.

When using a ButtonRowTemplate instead, I don't see a way to configure those buttons, besides working with the cascading classes these buttons are included in (probably modal-footer).

Is there a better way?

Also, this is not only for the CSS - using the CancelCommandTemplate it is possible to change the button's text from Cancel to Close if the user does not have editing rights.

Thanks!

**Comment by David-Moreira** [comment]
They are still command columns. Can you not use `DataGridCommandColumn` to configure them, while still having ButtonRowTemplate set? 
Just that you will not use the `DataGridCommandColumn` CREATE/EDIT/DELETE buttons.

**Comment by GilShalit** [comment]
OK, so to make this work, I included a command column with templates for save and cancel, but kept
```CommandMode="DataGridCommandMode.ButtonRow"```.
Unless you do that, Edit, Delete and Clear Filter links will appear in each row, unformatted.

So this works perfectly well to configure the Save and Cancel buttons in the Edit popup but is somewhat un-intuitive... Maybe there should be a way to configure these buttons independent of the CommandColumn.

Thanks!

**Comment by stsrki** [comment]
@David-Moreira You could add a note to the documentation?

**Comment by David-Moreira** [comment]
Seems redudant to make these available on the `ButtonRowTemplate`, as that does not seem to be the button row responsability to configure if you think about it, it's a Button Row.

The Save/Cancel buttons are indeed Commands and in my opinion are rightly placed, altought you could argue that they should be outside of `DataGridCommandColumn` instead. 

Just that you need to configure it accordingly, **so agreed with the note.**
