### ISSUE TITLE
NotificationAlert Location

### ISSUE THREAD

**Issue by mtbayley** [Megabit/Blazorise#3316]
As far as I can see, there is still no Location property for NotificationAlert

Did #2906 ever make it to a release?

**Comment by stsrki** [comment]
That is really strange. I can clearly see it in the PR but nothing in the git history. Could be that something went wrong with one of the merged?!

@David-Moreira If we would add it now into 095 branches that would mean changing the API. Should we re-add it into 1.0 instead?

**Comment by David-Moreira** [comment]
Well if it didn't make it, it didn't make it... 1.0... haha

**Comment by stsrki** [comment]
I have recreated the previous PR. What I'm most concerned about is that we cannot know if there were any other merging problems like this.
