### ISSUE TITLE
Shown but disabled dropdown item in a DataGrid?

### ISSUE THREAD

**Issue by sturlath** [Megabit/Blazorise#3325]
After searching the docs I think that this feature is not in Blazorise DataGrid but correct me if I´m wrong.

I have a `EntityAction`  dropdown from **abp.io** that I like to disable. So show the dropdown but in disabled state. I have tried things like `disabled="disabled"` and of course I just get some rendering errors.

Would also be cool if it was possible to have tooltip with it.

**Comment by stsrki** [comment]
`EntityAction` is an ABP component so I think they should implement it on their side as a parameter. Then proxy it the Dropdown or other buttons.

**Comment by David-Moreira** [comment]
Closing this as I believe apb has taken action.
@sturlath just re-open if you have any other difficulties related to this.
