### ISSUE TITLE
pressing Button with Clicked handler resets all checkboxes in a component

### ISSUE THREAD

**Issue by janseris** [Megabit/Blazorise#3329]
**Describe the bug**
Blazorise.Check and Blazorise.Bootstrap5.Check are reset to default value of their bound boolean variable when a button (Blazorise.Bootstrap5.Button) with Clicked eventhandler (even empty) is pressed

**To Reproduce**

Place some checkboxes into a component and then one or more buttons with Clicked event handler. Clicking any button will reset the checkboxes.

**Expected behavior**
The button does not reset the Check components

```

@page "/login"

<PageTitle>Přihlášení</PageTitle>

<div class="d-flex flex-column justify-content-center align-items-center">
    <h1>Přihlášení</h1>
    <Blazorise.Bootstrap5.Card>

        <CardBody>
  <Check5 Checked=KeepMeLoggedIn>Zůstat přihlášený/á</Check5>
            <Blazorise.Check Checked=TestBool>Test check</Blazorise.Check>

            <Check5 Checked=SaveInSessionStorage>Přihlásit jen v této záložce prohlížeče</Check5>
            <Button5 Color="Color.Primary" Class="mt-3" Clicked=LogIn>Přihlásit</Button5>

        </CardBody>

        <CardFooter>
            <div class="d-flex flex-row align-items-center">
                <span>Nemáte ještě uživatelský účet?</span>
                <Button5 Class="btn-link" Type="ButtonType.Link" Clicked=RedirectToRegister>Založit nyní</Button5>
            </div>
        </CardFooter>
    </Blazorise.Bootstrap5.Card>
</div>

            <Check5 Checked=KeepMeLoggedIn2>Zůstat přihlášený/á</Check5>
            <Blazorise.Check Checked=TestBool2>Test check</Blazorise.Check>

            <Check5 Checked=SaveInSessionStorage2>Přihlásit jen v této záložce prohlížeče</Check5>
            <Button5 Color="Color.Primary" Class="mt-3" Clicked=LogIn>Přihlásit</Button5>

@code {

        private bool KeepMeLoggedIn2 { get; set; } = true;
    private bool TestBool2 { get; set; } = false;

    private bool SaveInSessionStorage2 { get; set; } = true;


    private bool KeepMeLoggedIn { get; set; } = true;
    private bool TestBool { get; set; } = false;

    private bool SaveInSessionStorage { get; set; } = true;

    private async Task LogIn()
    {
        //do nothing
    }
}

```

**Screenshots**
![blazorise bug](https://user-images.githubusercontent.com/64279914/149660140-83dbe586-91db-4aee-bcbe-8842ba3e848d.png)

**Additional context**
Note: Button5 and Check5 are my own shortcuts for Blazorise.Bootstrap5.Button because writing just Button collides with Blazorise.Button etc.

**Comment by stsrki** [comment]
That's by design. When you define a parameter like `Checked=TestBool` it is a one-way binding, meaning every time page refresh it will be reset to the current `TestBool` value. You need to use two-way binding to let know `TestBool` has changed, eg. `@bind-Checked=TestBool`.

**Comment by janseris** [comment]
but I do not do any page refresh, I only click a button which does nothing and it resets all Check controls which could but also could not be related. Imagine there is a help button near a field and when I click it it would reset my form for no reason

**Comment by stsrki** [comment]
You don't do it, but Blazor do it implicitly for you. Every event is based on EventCallback and once the event finishes Blazor will trigger re-render on the same level in a tree. That can be on a page level or on a same parent level.

**Comment by janseris** [comment]
ah yes I understand, the text fields aren't reset because they probably use two-way binding (by reference) compared to the Check controls which use one-way binding (by value)
so you mean that the control is rerendered when button is pressed, is it like that? (althought I am not sure why the checkboxes inthe same component are rerendered when a button is clicked - only button should be rerendered, right?)

**Comment by stsrki** [comment]
Blazor will re-render only the same level of the page. What does that mean? Let's say you have two Cards that separate some of the input components. When you activate an event on one input element inside of one of the Cards, it will re-render only that same parent Card and possibly other sibling components and child components. It will not do anything on the other Card. That is one of the Blazor optimizations. It keeps track of the page structure.
