### ISSUE TITLE
Specifying number of lines in MemoEdit does not change height

### ISSUE THREAD

**Issue by lariosm** [Megabit/Blazorise#3343]
As the title suggests, when I specify the number of lines in the MemoEdit component using the following code snippet, `<MemoEdit Rows="5" />`, it doesn't seem to increase the height of the component as expected. Oddly enough, if I comment out the following CSS reference in _Layout.cshtml, `<link href="_content/Blazorise.Material/blazorise.material.css" rel="stylesheet" />`, the height of the component increases as expected. That being said, I'm not sure if the Blazorise Material CSS is to blame.

In any case, I've put together a small throwaway project in my [repository](https://github.com/lariosm/ta-blazor-project) that demonstrates the issue I'm having, should you decide to look into this further. I've put the code snippet in Index.razor.

# Summary
**Issue**
Specifying the number of lines in MemoEdit does not increase the height of the component as expected.

**Expected behavior**
Specifying the number of lines in MemoEdit increases the height of the component.

**Actual behavior**
Specifying the number of lines in MemoEdit does not change the height of the component.

**To Reproduce**
1. Add `<MemoEdit Rows="5" />` somewhere in a razor page. (Can be anywhere, really.)
2. Build and run the project in IIS Express.
3. Navigate to the razor page
4. You'll notice the height of the MemoEdit component does not change from its original size.

**Comment by stsrki** [comment]
It seems we have accidentally set height on the `.form-control` class, the same one that is used for all text input. It is a bug. Thanks for reporting it.
