### ISSUE TITLE
[HELP] Simple new Project - Server

### ISSUE THREAD

**Issue by kevinvenclovas** [Megabit/Blazorise#3349]
Hi, 
Using: .net 5 with Blazorise 0.9.5.4

when i start a simple new blazor project all is looking fine.
![image](https://user-images.githubusercontent.com/7681603/150634011-f33347d1-3f43-44b7-8538-c77921c4cc92.png)

Steps:

1. Install Blazorise.Bulma
2. Install Blazorise.Icons.FontAwesome
3. Add css on _Host.cshtml
![image](https://user-images.githubusercontent.com/7681603/150634090-084fc3df-0d03-4013-946d-a31e83be30a3.png)
4. Add @using Blazorise to _Imports.razor
5. Change Startup
![image](https://user-images.githubusercontent.com/7681603/150634183-190eed2b-67f5-4271-897b-2519f4b125ca.png) 
![image](https://user-images.githubusercontent.com/7681603/150634198-9f1d8c4a-88b1-4b86-bae3-16d275a34820.png)
6. Remove bootstrap.min.css
![image](https://user-images.githubusercontent.com/7681603/150634221-c4ca1eb0-072d-4a68-a34f-dc2b01321998.png)

On restart the app menu and the font is disappear

![image](https://user-images.githubusercontent.com/7681603/150634257-3c375de4-fa24-4173-948b-b216b69d2870.png)

**What am I doing wrong? Is there anything missing here to completely integrate Bulma?**

Thanks for help!

**Comment by stsrki** [comment]
The sidebar on the image that comes with the default Blazor project template is based on Bootstrap. That's why it doesn't work. If you inspect it in DevTools you will see the menu items, But since you're now using Bulma CSS they are not recognized.

You need to remove it and use our Bar component instead. https://blazorise.com/docs/components/bar

Our demo app where you can look for example: https://github.com/Megabit/Blazorise/blob/master/Demos/Blazorise.Demo/Layouts/MainLayout.razor

**Comment by kevinvenclovas** [comment]
Hi @stsrki, 

thank you!

I have a little bit starting problems maybe you can help me out.
Can you create me a new blazor project only with the most important files to start building my app? I want the same navigation as in the documentation, but I just can't get it.

![image](https://user-images.githubusercontent.com/7681603/150653755-e2cf7d59-537e-4620-8c0c-d510bf648ed8.png)

**Comment by stsrki** [comment]
Here is a quick template to get you started

[BlazoriseTemplate.zip](https://github.com/Megabit/Blazorise/files/7920093/BlazoriseTemplate.zip)

**Comment by kevinvenclovas** [comment]
Thank you so much! Maybe you can add this to the documentation!

**Comment by stsrki** [comment]
No need. We already have in plan to create a project template for VS. And possibly a CLI tool too.
