### ISSUE TITLE
Markdown: flip-flopping of user input when Task is delayed before value is set

### ISSUE THREAD

**Issue by WolfgangKluge** [Megabit/Blazorise#3355]
**Describe the bug**
When I type into a markdown field (where the value is written to the variable after a task is awaited), the value is changed back an forth forever.

**To Reproduce**
1. Use the source
   ```csharp
   @using Blazorise.Markdown
   @code {
       private string Value { get; set; } = "Test";

       private async Task OnValueChanged(string val) {
           await Task.Delay(1);
           Value = val;
       }
   }
   <Markdown Value="@Value" ValueChanged="@OnValueChanged" />
   ```
2. Set the cursor at the beginning of the string
3. type some letters (quick - but most of the time a single letter is sufficient)
4. See the text changes from "Test" to "asdfTest" (or whatever you typed) and back

**Expected behavior**
No flip-flopping of the text

**Additional context**
If you change the order of commands inside `OnValueChanged`, everything works like a charm

**Comment by David-Moreira** [comment]
Hello @WolfgangKluge 
You're basically purposedly adding a race condition, where multiple running async tasks are going to complete mutating the value.... I would advise against that, set `Value = val;` immediately for more coherent results. Otherwise you could try implementing some locking/expiring mechanism. 

Is there an actual use case where you would absolutely need this behaviour?

**Comment by stsrki** [comment]
As @David-Moreira already have mentioned. The value needs to be assigned as soon as possible otherwise an actual input and Blazor event handling will be out of sync. This same problem can be seen in any SPA framework, including React and Angular.

**Comment by WolfgangKluge** [comment]
I've worked around it in my special case - so I don't have any urge on that.
The use case was a replace-as-you-type solution.

I'm aware of the race condition and there could be absolute no good solution - but there might be better ones than flip-flopping forever (I tracked it down to `BaseAfterRenderComponent`).

Maybe there's a way to cancel the previous, not finished tasks - in hopes that this breaks the "endless" part.
But yes - I understand the problem here and that there's no way to get around it ideally.

**Comment by stsrki** [comment]
Cancellation would mean that `ValueChanged` would have to have a cancellation token as n additional parameter. We could do that but then two-way binding would practically stop working. Blazor, unfortunately, doesn't support that scenario. `ValueChanged` is required to have a single parameter that is the same as the `Value` type.

Maybe we could raise a features request on NetCore repository asking about it?
