### ISSUE TITLE
DataGrid: Custom Sort handler

### ISSUE THREAD

**Issue by WolfgangKluge** [Megabit/Blazorise#3360]
**Is your feature request related to a problem? Please describe.**
I want the DataGrid to be sorted in `Single` mode per default and in `Multi` mode when the user holds `Shift` while clicking the header. A bit like the windows explorer.

**Describe the solution you'd like**
Maybe it's worth a `Mixed` sort mode, but since this might be a very specific configuration, I want you to provide the `MouseEventArgs` in the [`HandleSortColumn`](https://github.com/Megabit/Blazorise/blob/180802f68bf83c6ad5f2abe071ad1de87475fff5/Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs#L1022) method as optional parameter so I can override and use them.

**Comment by David-Moreira** [comment]
I didn't know about this feature in windows haha.
What do you think @stsrki ?
I'd prefer to provide the feature with a new mode like : `MultiOnShiftClick`
then providing the `MouseEventArgs` in the `HandleSortColumn` as that seems to be littering the api with new arguments just for the sake of overriding.

**Comment by stsrki** [comment]
I knew about this but I rarely used it. It's not that common. We can think about doing it in a later version . Maybe v1.2.

**Comment by WolfgangKluge** [comment]
To provide a proposal:
Since there are so many possibilities like `MultiOnCtrlClick` or `SingleOnShiftClick`/`SingleOnCtrlClick`, `MultiOnRightClick`, maybe a customizable behavior class would be helpful..

```csharp
public class DataGridSortBehavior {
    public static DataGridSortBehavior Single { get; } = new DataGridSortBehavior(...);
    public static DataGridSortBehavior Multi { get; } = new DataGridSortBehavior(...);

    public DataGridSortBehavior(Action<MouseEventArgs, SortingInformation> onHeaderClick) {}

    public virtual void OnHeaderClick(MouseEventArgs eventArgs, SortingInformation info) {
        onHeaderClick?.Invoke(eventArgs, info);
    }
}
```

This would lead to only a minor (but still) breaking change (it's not an enum anymore - so some users could run into problems) but is fully customizable without the need to override the whole datagrid - and the datagrid loses some complexity.

Maybe you can even go a bit further and allow more control (think of e.g. two icons in the header where I can directly select the direction of the sort (instead of triggering it with the whole header cell), and/or icons that imply that the click will add a new column to the sorting columns..).

Thus an extension to the `SortDirectionTemplate` could be useful, too (context should expose more information, e.g. how many sort columns are there and the events to trigger)

**Comment by WolfgangKluge** [comment]
If you look at e.g. teleriks data grid, the multisort-functionality is a bit different

E.g. if you have 

|Header1|Header2|Header3|
|---|---|---|

Click on `Header1`
|Header1 `↑`|Header2|Header3|
|---|---|---|

Click on `Header2`
|Header1 `↑1`|Header2`↑2`|Header3|
|---|---|---|

Click again on `Header2`
|Header1 `↑1`|Header2`↓2`|Header3|
|---|---|---|

Click on `Header1`
|Header1 `↓2`|Header2`↓1`|Header3|
|---|---|---|

Notice the change of the order (in Blazorise, the order is not changed until you remove a column from sorting).. Would be great if something like this could be implemented, too (with a behavior-class as shown above).

**Comment by David-Moreira** [comment]
I'll look into what needs to be changed and implemented first I'll let you know. Do you agree with a more fine control like @WolfgangKluge proposed?

**Comment by stsrki** [comment]
Seems like an expandable approach. We can try something along that lines.

**Comment by David-Moreira** [comment]
Yea seems feasible, let me see if I can get group by done first.

**Comment by stsrki** [comment]
> If you look at e.g. teleriks data grid, the multisort-functionality is a bit different
> 
> E.g. if you have
> 
> Header1	Header2	Header3
> Click on `Header1`
> 
> Header1 `↑`	Header2	Header3
> Click on `Header2`
> 
> Header1 `↑1`	Header2`↑2`	Header3
> Click again on `Header2`
> 
> Header1 `↑1`	Header2`↓2`	Header3
> Click on `Header1`
> 
> Header1 `↓2`	Header2`↓1`	Header3
> Notice the change of the order (in Blazorise, the order is not changed until you remove a column from sorting).. Would be great if something like this could be implemented, too (with a behavior-class as shown above).

I have tested this in our demo with Multiple sort enabled and it behaves the same as you described it.
