### ISSUE TITLE
Tab BUG: auto change the select tab while enter value

### ISSUE THREAD

**Issue by rqx110** [Megabit/Blazorise#3362]
To Reproduce, see the screen short: I select the `Tab2` first, and input something in the textbox of tab2, while press a key the tab will change to `Tab1` automatically
![tab](https://user-images.githubusercontent.com/1829209/151287400-5bd991c7-13ff-4f18-84cf-b2f4924ab5ef.gif)

create a project to reproduce this bug
[BlazorServerApp.zip](https://github.com/Megabit/Blazorise/files/7947372/BlazorServerApp.zip)

**Comment by stsrki** [comment]
It is working as expected. Every time a `input` value changes, Blazor itself will trigger re-render and since you have a one-way binding on the `Tabs` component it will reset the selected tab every time.

Solution is simple. You need to use two-way binding, eg `<Tabs @bind-SelectedTab="@tab1">`.

**Comment by rqx110** [comment]
got it, Thanks!
