### ISSUE TITLE
Component inside custom component overrides validation Value object

### ISSUE THREAD

**Issue by puschie286** [Megabit/Blazorise#3369]
**Describe the bug**
blazorise input components override inputComponent of a validation component. this prevents the use of complex objects for validation.

**Example**
Note: this is demonstration code that doesnt implement all required methods / properties

ExampleData.cs:
```
class ExampleData
{
    public int A = 0;
    public int B = 100;
}
```
Example.razor:
```
@inherits BaseInputComponent<ExampleData>
<Div>
   <NumericEdit TValue="int" @bind-Value="InternalValue.A" />
   <NumericEdit TValue="int" @bind-Value="InternalValue.B" />
</Div>

@code
{
   protected override ExampleData InternalValue { get; set; } = new();

   public override async Task SetParametersAsync( ParameterView parameters )
   {
	await base.SetParametersAsync( parameters );
	if( ParentValidation != null ) await InitializeValidation();
   }
}
```

Page.razor:
```
<Validaton Validator="@ValidateExample">
   <Example />
</Validation>

@code
{
   private void ValidateExample( ValidatorEventArgs e, CancellationToken cancellationToken )
   {
      // exspected e.Value to be ExampleData, but it is int ( 100 )
   }
}
```

**Possible Solution**
I see two solutions:
1 => parameter to disable InitializeValidation on all InputComponents
2 => component that block the initilization cascade

**Comment by stsrki** [comment]
`Validation` component was never meant to be used for complex object. It is only used for validating a single value. To validate an object or to validate multiple values you need to use the `Validations`  component and assign it the `Model` parameter.

**Comment by puschie286** [comment]
oh, thank, that makes sense - i will try to implement it with nested validations.

its pretty hard to find any usefull information about this topic ( most people / frameworks are using data notation validation only )

would be great if we could have a example / demo page for nested validation and linked validations ( there is already the menu for nested validation )
-> linked validation would be multiple inputs that are either all invalid ( if one is invalid ) or all valid

@stsrki should i create a new feature request for this ?

**Comment by stsrki** [comment]
We also have data-annotations https://blazorise.com/docs/components/validation

For nested validations(where Validations is inside of another Validation component) I'm really not sure how it would play. But it might work as long as models are not the same.

**Comment by puschie286** [comment]
my point is that we cant use data annotation for complex validation rules that require data across different objects / data sources - so we need to use the blazorise validation component.

after a lot of test with different approches, the only stable solution is to wrap the custom component in a Validations with ValidationSummary and a single Validation. this way all your input components inside your custom component are linked together and have the same ValidationStatus and one error message.

Here an example:
```
<Validations ValidateOnLoad="false">
	<ValidationSummary />
	<Validation Validator="@ValidateSumOver10">
		<Field>
			<NumericEdit @bind-Value="A">
		</Field>
		<Field>
			<NumericEdit @bind-Value="B">
		</Field>
	</Validation>
</Validations>

@code {
	private int A { get; set; }
	private int B { get; set; }
	
	private void ValidateSumOver10( ValidatorEventArgs e )
	{
		e.Status = ( A + B > 10 ) ? ValidationStatus.Success : ValidationStatus.Error;
	}
}
```
The only downside of this approche is that you cant provide multiple error messages. This could be achived with a different approch ( with the downside that you need to provide an error message for each Validation component to prevent the MissingFieldsErrorMessage )

**Comment by puschie286** [comment]
https://github.com/Megabit/Blazorise/issues/3371
