### ISSUE TITLE
DataGrid Functionality Question

### ISSUE THREAD

**Issue by grumpykiwi** [Megabit/Blazorise#3376]
Hi

I have a datagrid that shows user info from Teams(R). One of the columns is "Status" which is a calculated value to indicate whether a user is in office, away, vacation etc.

If the user viewing the page is an Admin, I would like them to be able to click on someone's status to change it. Ideally this will enter Edit Mode in a popup. In the popup, Status should be a dropdown with a list of available statuses. On save, I want to capture the event so I can fire off an update via Graph API, refresh the data and exit Edit mode.

What is the best way to do this?

Thanks

Mark

**Comment by grumpykiwi** [comment]
I have it working kind of using onRowSelect and then calling
`	protected void RowClicked(DataGridRowMouseEventArgs<GroupUser> item)
	{
		Console.WriteLine("ID: " + item.Item.ID);
		if (IsAdmin)
		{
			dataGrid.Edit(item.Item);
		}
	}`

The problem is, the modal popup does not get focus, rendering the form uneditable. 

Any ideas?
![Modal Focus Issue](https://user-images.githubusercontent.com/43825887/151685648-efd515eb-6235-4b82-93f3-3eef9aa15685.png)

**Comment by stsrki** [comment]
If I understand correctly, you want to do something while the row is saving and before it is actually saved?

You can use `RowUpdating` event, call the API to process it, and if something breaks you can cancel the event.

**Comment by grumpykiwi** [comment]
Thanks. That hit the spot perfectly once I figured out how to wire it up and how to retrieve the before and after values. For those following along and maybe it will help someone:

```
	protected void OnRowUpdating(CancellableRowChange<GroupUser, Dictionary<string, object>> e)
	{
		GroupUser user = e.Item;
		Console.WriteLine($"RowUpdating Old Status: {user.Status}. New Status: {e.Values.Where(x => x.Key == "Status").First().Value}. ID: {user.ID}");
	}
	protected void OnRowClicked(DataGridRowMouseEventArgs<GroupUser> item)
	{
		Console.WriteLine("RowClicked ID: " + item.Item.ID);
		if (IsAdmin)
		{
			dataGrid.Edit(item.Item);
		}
	}
	protected void OnRowUpdated(SavedRowItem<GroupUser, Dictionary<string, object>> e)
	{
		GroupUser user = e.Item;
		Console.WriteLine($"OnRowUpdated Status: {user.Status}");
	}
```
And the lines in the DataGrid definition
```
UseInternalEditing="true"
RowUpdating="@OnRowUpdating" 
RowUpdated="@OnRowUpdated"
RowClicked="@OnRowClicked"
```
The issue reported above where the modal was not receiving focus was caused by an old CSS file reference. It was a debug CSS file I was using previously when laying out a popup modal to display an enlarged image. Once I removed that reference, everything worked fine.

Thanks to Mladen for your help. I am loving the Blazorise components. Why waste a king's ransom on Teleric?

Cheers


Mark
