### ISSUE TITLE
DataGrid: Ability to prevent row selection

### ISSUE THREAD

**Issue by WolfgangKluge** [Megabit/Blazorise#3377]
**Is your feature request related to a problem? Please describe.**
I want to be able to prevent the `RowClicked` and/or `SelectedRowChange` event, depending on a column event. The use case is a table, where `RowClicked` navigates away, but a click on a (custom) command button should not trigger `RowClicked`.

**Describe the solution you'd like**
I've multiple ideas how to solve it. The natural choice might be a column information on `SelectedRowChange`.
Another (and eventually easier way) could be to allow click events to abort in general (call `stopPropagation`).
The last one is a `Clicked` event on the column (triggered on each cell individually). This might be useful anyways to allow different click events on different columns.

### Additional context
Is there a way to set `stopPropagation` and `preventDefault` on a Blazorise `Clicked` event? Like
```html
  <button
      @onclick="(() => { /*...*/ })"
      @onclick:stopPropagation="true"
      @onclick:preventDefault="true">
```

This, together with a Column-Clicked event, would be sufficient (if not perfect for me).

**Comment by stsrki** [comment]
@David-Moreira if I'm not mistaken this is possible with #3330 ?

**Comment by David-Moreira** [comment]
#3330 is related to DetailRowTrigger handling. 
I think what the OP is looking for is that certain clicks inside certain elements of a row (like a button) do not trigger the RowClicked event and therefore row selection. Which I think is already possible by manually setting the datagridcolumn templates and set the buttons or elements to stop the clickPropagation, is it not? 

Otherwise a possible feature would be to expose an api similar to the Inserting/Updating/Removing Apis, that allow you to cancel the process.

**Comment by stsrki** [comment]
Ah, I get it. And yes, using the DataGridColumn templates and adding the manual button with the `@onclick:stopPropagation` and `@onclick:preventDefault` is the right way to do it.

**Comment by David-Moreira** [comment]
@WolfgangKluge have you tried our suggestion?

**Comment by WolfgangKluge** [comment]
Yes, @David-Moreira, that's my workaround and it works mostly/for my needs that is sufficient.

Personally, I would keep this feature request still open (rename it to "Add CellClicked-event"), since I think it would be even better, if there is built-in support.

Here's a small example:

```razor
@code {
    public class Test {
        public int A { get; set; }
    }
    private List<Test> Data = Enumerable.Range(0, 5).Select(i => new Test { A = i }).ToList();
}

<DataGrid TItem="Test"
    Data="@Data"
    EditMode="DataGridEditMode.Inline"
    Editable="true"
    RowClicked="@(r => r.Item.A = r.Item.A + 1)">
    <DataGridColumns>
        <DataGridColumn TItem="Test" Field="A" />
        <DataGridCommandColumn TItem="Test" />
    </DataGridColumns>
</DataGrid>
```

I want that a click on `Edit` or `Delete` does not trigger `RowClicked` and the solution is something like
```razor
<DataGridCommandColumn TItem="Test">
    <EditCommandTemplate>
        <a href="#" class="btn btn-link" @onclick="@context.Clicked" @onclick:stopPropagation="true" @onclick:preventDefault="true">
            @context.LocalizationString
        </a>
    </EditCommandTemplate>
    <DeleteCommandTemplate>
        <a href="#" class="btn btn-link" @onclick="@context.Clicked" @onclick:stopPropagation="true" @onclick:preventDefault="true">
            @context.LocalizationString
        </a>
    </DeleteCommandTemplate>
</DataGridCommandColumn>
```

But this prevents the `RowClicked` only, if I hit exactly the links + padding (not the space around the link text).

Furthermore, I think a cancelable `CellClicked`-event would be helpful for other use cases, too.
But it's your project :)

**Comment by David-Moreira** [comment]
@stsrki your thoughts? 
Personally I like the Idea of a `RowClicked` `event` with relevant context and the cancel option.

**Comment by stsrki** [comment]
`RowClicked` sounds good to me. But, now I'm thinking more and more about why we just don't prevent events bubbling internally. We can just add `@onclick:stopPropagation` to the Edit, Save, Cancel, etc. buttons and they will not affect the actual row clicks.

**Comment by David-Moreira** [comment]
I guess we can improve that internally. `RowClicked` is just a nice to have new feature overall in my opinion.
No point in messing with 0.9.5. Let's try for 1.0.0?

**Comment by David-Moreira** [comment]
<DataGridCommandColumn TItem="Test"> 
Do you think a `PreventClick` parameter would actually be worth it on the column itself? 
Because I was thinking... and people sometimes have the weirdest requirements... they might require the row click to go through, like it does now?

**Comment by stsrki** [comment]
> `<DataGridCommandColumn TItem="Test" PreventRowClick> ` Do you think a `PreventRowClick` parameter would actually be worth it on the column itself? Because I was thinking... and people sometimes have the weirdest requirements... they might require the row click to go through, like it does now?

Yeah, I think that is actually a good place to have it.
