### ISSUE TITLE
Js modules vs PWA and offline capabilities

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#3379]
> We are also aware that there might need to be extra setup when dealing with PWA and offline capabilities if you want your app to remain responsive. We are working on providing you with clear steps for these use cases.

**Comment by stsrki** [comment]
Do you remember what we need to do here? DO we have enough time for v1.0?

**Comment by David-Moreira** [comment]
Yea, setup a PWA and figure out an optional setup to load our modules on initial app load, giving the users that option that is interesting in the case of a PWA. Also just general docs about the caveats in our modules vs pwa...
Pretending to do this over the weekend. When are you planning the release?

**Comment by stsrki** [comment]
I have rescheduled it for another 10 days, on February 28. Should be enough time i think.
