### ISSUE TITLE
Blazorise internals, demos && docs | Prefer tag like bool parameters

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#3380]
Clean up / normalize components bool parameters api

**Prefer** 
`<Component ReadOnly />`

**Over**
`<Component ReadOnly="true" />`

Simple Find & replace ="true" with some attention might be enough.

**Comment by stsrki** [comment]
I agree. This is a nice Blazor/ +Razor feature that more people should know about.
