### ISSUE TITLE
Markdown: Mermaid support

### ISSUE THREAD

**Issue by WillianGruber** [Megabit/Blazorise#3383]
Hi,

Would it be possible to support mermaid in markdown?
https://mermaid-js.github.io/mermaid/#/
Azure Devops Wiki supports an old version of it and I found it to be really helpfull. If this support is added it would be wonderful!

Thanks!

**Comment by stsrki** [comment]
I don't think we will be supporting this.

**Comment by WillianGruber** [comment]
Ok, thanks for your time!
