### ISSUE TITLE
Can't set Location in NotificationAlert component

### ISSUE THREAD

**Issue by federicodibe** [Megabit/Blazorise#3389]
Inside the **NotificationAlert** component it is not possible to specify the Location attribute, in order to change the position of the popup window.

I have updated the Blazorise.Components library to version 0.9.5.5, but nothing has changed.

I need to display it in the top center.

Am I forgetting something or is there a bug?

Thanks

![02-02-2022 10-48-51](https://user-images.githubusercontent.com/62238562/152130714-3e2e39a0-1b04-4904-8c71-7a72a1a3ebda.jpg)

**Comment by stsrki** [comment]
Location will be available in v1.0. We had some merge problems in v0.9.5 so some APIs got lost. v1.0 will be released in about two weeks.
