### ISSUE TITLE
Add Bootstrap Icons

### ISSUE THREAD

**Issue by Xeevis** [Megabit/Blazorise#3390]
[Bootstrap icons](https://icons.getbootstrap.com) are free, MIT licensed, ever expanding collection of high quality, open source icons with almost 1,700 icons and growing. Can be used with or without Bootstrap in any project. And I think it would be great if they were included as part of Blazorise.

![image](https://user-images.githubusercontent.com/5835044/152148063-03c2a0d2-7f20-4178-9250-d95cde6e3c25.png)

I can open PR with all 1683 icons auto-parsed as fields and keep them updated, but I'm not quite sure how to tackle `IconName` mappings. I understand it was meant to create common ground for various icon providers, but I'm not convinced that's ever going to work as intended. It covers barely couple % of icons and many if not most of them don't click across various providers. It's a nightmare to find matching icons (what one calls "adjust" another calls "circle-half"), others aren't there at all and trying to switch between providers will be poor experience either way. Not to mention it's going to be nightmare to maintain and even then it will be barely usable to find specific icons you might want, it's highly opinionated ... Arrow down? There could be 6 versions of it.

Bootstrap icons don't have "styles", everything is a different icon. Some icons have filled variants some don't, some have circle/square variants etc. I don't know how to deal with this.

```razor
<Icon Name="BootstrapIcons.ArrowDown"></Icon>
<Icon Name="BootstrapIcons.ArrowDownShort"></Icon>
<Icon Name="BootstrapIcons.ArrowDownCircle"></Icon>
<Icon Name="BootstrapIcons.ArrowDownSquare"></Icon>
<Icon Name="BootstrapIcons.ArrowDownSquareFill"></Icon>
```

**Comment by stsrki** [comment]
Thanks for raising this ticket. I always forget about Bootstrap icons.

Back to your "head-scratching". IconName was never meant to cover all icons. Only the most common and most used icons. This way I don't need to bother with different naming patterns in different libraries.

Also, since it is hard to map icons I have created a [tool to merge them](https://github.com/stsrki/IconsMergerGUI). It's not perfect but it worked. We'll see how it goes with Bootstrap icons.

And if any icon can't be mapped we will just make them all part of the `static` fields in a utility class, eg `FontAwesomeIcons`.

**Comment by janseris** [comment]
Seems there is sort of telepathy. I have independently just created just the same ticket. 
This feature would be very welcome!

**Comment by Xeevis** [comment]
> What about something like `<Icon Name="BI.BoostrapIconName"/>`? That would be shorter (prevent common XAML bloat) but at the same time probably clear because of the original` <span class="bi bi-bootstrapIconName"></span>` syntax.

I've stuck with long name because it's more readable and consistent with existing providers. You can always create your own aliases in `_Imports.razor`
```razor
@using I = Blazorise.IconName
@using BI = Blazorise.Icons.Bootstrap.BootstrapIcons
@using FA = Blazorise.Icons.FontAwesome.FontAwesomeIcons
@using MA = Blazorise.Icons.Material.MaterialIcons
```
And then in any `.razor` you can go with format you desire
```razor
<Icon Name="I.Archive" IconSize="IconSize.x5" />
<Icon Name="BI.YinYang" />
<Icon Name="FA.Allergies" IconStyle="IconStyle.Solid" />
<Icon Name="MA.Android" />
<Icon Name="IconName.Bell" />
<Icon Name="BootstrapIcons.Mailbox" />
<Icon Name="@("bi-mailbox")" />
<Icon Name="@("fa-phone")" />
```

**Comment by David-Moreira** [comment]
I agree with the long descriptive names. :) Does not require user knowledge of acronyms. 
And alias works great for these use cases if the developer so wishes!

**Comment by janseris** [comment]
> @using I = Blazorise.IconName

Great, I thought that aliases don't work in Blazor syntax but they only don't for aliasing Blazor components.
