### ISSUE TITLE
SpinKit showcase GIF/MP4 for documentation

### ISSUE THREAD

**Issue by janseris** [Megabit/Blazorise#3400]
Hello, I missed this in documentation so I created it.Here it is:

```
@foreach (SpinKitType spinKitType in ((SpinKitType[])Enum.GetValues(typeof(SpinKitType))).OrderBy(x => Enum.GetName(x)))
    {
        <div class="d-flex gap-3 align-items-center my-2 justify-content-center">
                <SpinKit Type=spinKitType Size="2rem"></SpinKit>
                @Enum.GetName(spinKitType)
        </div>
    }

```
https://user-images.githubusercontent.com/64279914/152635607-3b13c482-f2f0-4abd-9057-43b0ea90944e.mp4

![Blazorise SpinKit showcase](https://user-images.githubusercontent.com/64279914/152635613-adb2e022-7eb3-4855-a129-041fc9ccb68d.gif)

**Comment by stsrki** [comment]
Can you explain? We actually have SpinKit in the documentation https://blazorise.com/docs/extensions/spinkit

**Comment by janseris** [comment]
Yes but there is only 1 example.

**Comment by stsrki** [comment]
We might add this example into the documentation. But we're more focused on making smaller code snippets. Users can always experiment and see what is inside of `SpinKitType`.

**Comment by janseris** [comment]
OK. I just thought according to my personal experience, that it is important to show what you have to make users decide for your project instead of other project when choosing a Blazor library. They will often decide by exploring the libraries and their documentation online as that is much faster than having to install the library and try it in code or even explore source code
