### ISSUE TITLE
Autocomplete: Multiple selection with checkboxes

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#3401]
### Discussed in https://github.com/Megabit/Blazorise/discussions/3397

<div type='discussions-op-text'>

<sup>Originally posted by **Lasoty** February  4, 2022</sup>
A very useful component would be DropDown with a checkbox list.

![image](https://user-images.githubusercontent.com/23433922/152559234-23c4ffb9-23ee-4110-9999-499640aab805.png)
</div>

**Comment by David-Moreira** [comment]
Starting work on this.
For this to make sense, then we need to have a "mode" where the selected items are still part of the list, right?
@stsrki ?

Because at the moment we remove the selected items from the search list:

Image below shows : Selected Western Sahara, and it is removed from the search list
![image](https://user-images.githubusercontent.com/22283161/171519027-0c203022-841a-4dd6-85ba-1fa5351216bb.png)

Also not sure where the check all checkbox will be, it makes sense to be right besides where you type, but I think it's going to look weird, unless you make it look like in the example image in the first post, placed below.

**Comment by stsrki** [comment]
Aren't this going to be a part of DropdownList, not autocomplete? Or do you want to make it with autocomplete?

**Comment by David-Moreira** [comment]
Oh I was going to do as part of `AutoComplete` haha. Which should be the component used for more advanced/complex features, in my opinion.

If we implement on DropdownList, then we need to make it so DropdownList now also supports multiple selection, etc... then people would want it to be able to search also (like seen in the image)... and you end up having a second `AutoComplete` like component?

**Comment by stsrki** [comment]
Now that I think about it. There were feature requests to have checks boxes on Autocomplete also 😅
