### ISSUE TITLE
Feature - QR-Code extension

### ISSUE THREAD

**Issue by njannink** [Megabit/Blazorise#3410]
Component for generating QR codes based on something like

https://github.com/codebude/QRCoder

    <Blazorise.QRCode Text="https://blazorise.com" ECCLevel="L" EciMode="Default" DarkColor="Black" LightColor="White" />

or
   
    <Blazorise.QRCode ECCLevel="L" EciMode="Default" DarkColor="Black" LightColor="White">
        https://blazorise.com
    </Blazorise.QRCode>

**Comment by stsrki** [comment]
There might be some problems with this approach https://github.com/codebude/QRCoder/issues/361#issuecomment-992152570

**Comment by njannink** [comment]
My project is still on net5 but we plan to move to net6 in some months. I will have a look if it works or not. I believe system.drawing.common just works in Blazor

**Comment by njannink** [comment]
generate a base64 image and use that as source on the image

**Comment by njannink** [comment]
I will create a PR when I have it working for you to have a look and then you can decide to incorporate it or not
