### ISSUE TITLE
Document Blazorise conventions and best practices

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#3424]
Add:

- naming guidelines
- formating
- code conventions
- etc.

**Comment by David-Moreira** [comment]
Notes: 
- Prefer prefixless booleans, example: `Loading` over `IsLoading`

**Comment by stsrki** [comment]
> Notes:
> 
> * Prefer prefixless booleans, example: `Loading` over `IsLoading`
> * Follow Regions template Members/Properties/etc... Provide the template.

`IsLoading `is allowed for property getters in case when we need to determine something from multiple sources, eg

`IsLoading => Options?.Loading ?? Loading ?? false;`
