### ISSUE TITLE
OnKeypress Binding resulting in unwanted behavior

### ISSUE THREAD

**Issue by ninjanerdbgm** [Megabit/Blazorise#3435]
Is there a way to change the binding (both manual and Two-Way) to trigger OnKeyUp instead of OnKeyPress?

The reason I ask is because non-character keys, like backspace, do not trigger the binding.  This results in unwanted behavior, such as the bound variables not getting assigned correctly when a user types something, then uses the backspace key without touching another key afterwards.

**Comment by David-Moreira** [comment]
Man... such quirks with different browsers always... :(
Need to check other text based inputs... might have same problem? 

What browser did you use?

**Comment by stsrki** [comment]
I have tested it with Firefox, Chrome, and Edge and all is working. I can't test Safari as I don't have it.

Btw, I had to add a null check for the variable so try it also on your side. Maybe it is silently failing for you.

```cshtml
<MemoEdit @bind-Text="@MemoText" Class="@((MemoText?.Length ?? 0) == 0 ? "bg-highlight" : "")" Rows="5" />

<Div>
    @MemoText
</Div>

@code {
    string MemoText;
}
```

**Comment by David-Moreira** [comment]
@ninjanerdbgm were you able to test this out?

**Comment by David-Moreira** [comment]
@ninjanerdbgm friendly reminder!
