### ISSUE TITLE
Autocomplete : Load data on demand (Similar to ReadData on DataGrid) : Feature

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#3450]
Autocomplete : Load data on demand (Similar to ReadData on DataGrid) : Feature

Requested on #410

**Comment by angelru** [comment]
when will it be available?

**Comment by stsrki** [comment]
I'm not sure if we would have enough time to make it for 1.1. @David-Moreira what do you think? Should we leave it or move to 1.2?

**Comment by David-Moreira** [comment]
We can try, ReadData on this and TreeView are much needed.
Let me see if I have enough time over this weekend.
