### ISSUE TITLE
DataGridColumn: Responsive Hide

### ISSUE THREAD

**Issue by gkochera** [Megabit/Blazorise#3451]
## Problem I'm Trying to Solve
I'd like the ability to hide columns based on the available width of the screen. This could be done with predefined breakpoints, or by allowing the ability to apply a custom CSS class to a `DataGridColumn` element and defining our own CSS after the fact.

## Possible Solutions
Option 1:
```html
<DataGridColumn TItem="Item" ... Hides="Breakpoint.Tablet" />
# Column will not display on Tablet size viewport and lower. A Hides parameter would take one of the Breakpoint enums.
```

Option 2:
```html
<DataGridColumn TItem="Item" ... Class="d-none d-lg-table-cell" />
# Column will not display on Bootstrap 5 large breakpoint and lower. 
```

## Additional Context
The `Responsive` parameter is nice, and definitely works in a pinch, but for those who would like more control over the UI appearance, I feel like this would be a really nice addition. 

The `DataGridColumn` component does have a `Displayable` property that can take a `boolean` value currently. The problem that I have run into is the ability to change that based on available size (particularly the width) of the viewport without using JSInterop to get that value. I'd like a native C#/Blazor solution to this issue, if at all possible.

**Comment by stsrki** [comment]
Did you tried the Display utility? eg. `<DataGridColumn Display="Display.None.TableCell.OnWidescreen">`

**Comment by stsrki** [comment]
Ah, it seems we missed applying the styling to the header. We can fix that. So, the solution would be OK for you once it is fixed?

**Comment by gkochera** [comment]
Absolutely! That would be perfect!

**Comment by gkochera** [comment]
Yea, I'll try it now.

**Comment by gkochera** [comment]
Yup, this worked perfectly! Great solution.

```blazor
    <DataGridColumns>
        <DataGridColumn 
            Display="Display.None.TableCell.OnTablet" 
            HeaderDisplay="Display.None.TableCell.OnTablet"
            TItem="Item" 
            Caption="Name" 
            Field="Name" 
            Sortable=true>
    </DataGridColumns>
```

**Comment by stsrki** [comment]
Great :) Closing now.
