### ISSUE TITLE
Leave the `text-center` setting to the user in bs5 `CardDesk` component

### ISSUE THREAD

**Issue by rqx110** [Megabit/Blazorise#3468]
it is better leave the `text-center` setting to the user
https://github.com/Megabit/Blazorise/blob/ef8b9b47d50ee1fba181d97dbb356e807c884b54/Source/Blazorise.Bootstrap5/Bootstrap5ClassProvider.cs#L563

**Comment by stsrki** [comment]
I think it might be done.
