### ISSUE TITLE
Autocomplete should allow adding a new value by method call

### ISSUE THREAD

**Issue by kencherasaro** [Megabit/Blazorise#3475]
**Describe the solution you'd like**
Using Autocomplete with single select, I would like to be able to add a new value(complex object) via a method call. 

### Additional context
A component named Blazored.TypeAhead has such a feature seen in their sample [(Blazored.TypeAhead)](https://github.com/Blazored/Typeahead/blob/main/samples/BlazorWebAssembly/Pages/Index.razor).  The sample is "Multi-select - Adding items on empty search result" and though the sample is multi-select I have it working for single select.  The method signature must return the type of item that the control is expecting.  I have it working such that the method invokes a modal on which the data for the new type is entered (and actually persisted to a database via api call) and the new object is returned.

**Comment by TorreyGarland** [comment]
I would like to see this also.

**Comment by David-Moreira** [comment]
Hello @kencherasaro @TorreyGarland 
Could you guys take a look at `FreeTyping` and `NotFoundContent` Autocomplete features? Together I think these would be the same as the requested feature.

**Comment by kencherasaro** [comment]
@David-Moreira , I was just looking at [Blazorise Auitocomplete](https://blazorise.com/docs/extensions/autocomplete) specifically at the Searching Single Value example.  I see it has FreeType and NotFoundContent.  The NotFoundContent appear to be somewhat static though it can display the context (Free typing).  In my original question I was looking for something more.  Perhaps you could provide an example where a NotFound allows for acting on it by allowing the user to add that entry to a data store (database).

**Comment by David-Moreira** [comment]
Ah I get it, you're right. Seems like a good feature.
`NotFound` eventcallback, where you can listen to it, and should be able to modify the data.

**Comment by David-Moreira** [comment]
But #3856 with `ReadData` support, might precisely help you. You'll be providing the user data as he searches. So you can control it as you wish.

I was just taking a look, and `NotFound` eventcallback already exists, are you not able to use it succesfully to achieve what you want?
