### ISSUE TITLE
Datagrid selection stops working

### ISSUE THREAD

**Issue by WillianGruber** [Megabit/Blazorise#3480]
**Describe the bug**
Datagrid selection stops working

**To Reproduce**
1. Go to https://bootstrapdemo.blazorise.com/tests/datagrid
2. Change  Command Mode  to Button Row
3. Select a row
4. Click Edit button
5. Click Delete button
6. Try to select a line. =====> This wont work <=====
7. Click New button
8. Click Cancel button
9. Try to select a line. This works again

I believe selection gets turned off when in edit mode, and will only come back after the user explicitly clicks Cancel button. If he deletes the line without canceling the Edit, selection stops working.

**Expected behavior**
When the edit mode is finished by any action other than by clicking the Cancel button, the selection option should work again.

**Comment by David-Moreira** [comment]
Edge case.... haha
