### ISSUE TITLE
DateEdit time not fixed format (both AM/PM and 24hour)

### ISSUE THREAD

**Issue by sturlath** [Megabit/Blazorise#3484]
I saw one of my test user that his DateEdit showed PM information but when I always get 24hour clock. 

I can´t see that I can control this at all but I would like to be able to **fix this to 24 hours** as DatePiker's TimeAs24hr.

Is this possible? Or is this just picked up from some localization settings of the user?

**Comment by stsrki** [comment]
DateEdit is based on `input type="date"` so it is fully controlled by the browser and the user system settings. We don't have much control over it. Your only option is to use DatePicker which has much more features, including 24h mode.

**Comment by sturlath** [comment]
OK I think I will move to the DatePicker. Thanks for the answer!
