### ISSUE TITLE
Pattern Validation for MemoEdit

### ISSUE THREAD

**Issue by Keltanis** [Megabit/Blazorise#3501]
My TextEdits and MemoEdit do not use @text-Bind; rather, it uses Text and therefore instead of utilizing data annotations for my pattern validations, I have to use Manual Validation and using the Pattern attribute for the fields. This works great for everything BUT the MemoEdit. 

Request that MemoEdit utilizes the Pattern attribute for Manual Validation. 

This is only a problem because we are using a data grid where you add/edit items using a modal. When making changes I. The modal while @text-Bind is being used, the changes reflect in the data grid and do not clear those changes out on cancellation of the modal.

**Comment by stsrki** [comment]
It's tricky. Unlike regular `input` element, `textarea` doesn't support pattern attribute: https://stackoverflow.com/questions/13643417/how-to-validate-pattern-matching-in-textarea

If we would add the `Pattern` parameter that would mean that it would behave differently from the `TextEdit` and it would be used only for the validation process.

**Comment by stsrki** [comment]
@David-Moreira what do you think? Should we add `Pattern` on `MemoEdit` even if it is not supported on the underline `textarea`?

**Comment by stsrki** [comment]
PS. maybe fake it with the `data-pattern` attribute?
