### ISSUE TITLE
Provide cancellation token to IFileEntry.WriteToStreamAsync

### ISSUE THREAD

**Issue by mtbayley** [Megabit/Blazorise#3503]
Is it possible to allow a cancellation token to be passed here instead of CancellationToken.None? I would like to cancel a file upload before it has finished writing to file.

https://github.com/Megabit/Blazorise/blob/fc1479bde282ad4df5c0fba5652f29bb2c33e7e3/Source/Blazorise/Components/FileEdit/FileEdit.razor.cs#L198

**Comment by David-Moreira** [comment]
Fixed in #3744. Will be available in the next release. Thank you for reporting.
Closing.
