### ISSUE TITLE
Multiple Axis Data Binding

### ISSUE THREAD

**Issue by JonathanShrek** [Megabit/Blazorise#3512]
Does Blazorise support binding data to multiple axes? For example:

https://plotly.com/javascript/multiple-axes/

**Comment by stsrki** [comment]
This is possible. You just need to add multiple datasets to the chart and they will be automatically be handled. If you follow our example in the [docs](https://blazorise.com/docs/extensions/chart) you can see the line `await lineChart.AddLabelsDatasetsAndUpdate( Labels, GetLineChartDataset() );`

The second parameter can accept the array, so you could just do:

```cs
await lineChart.AddLabelsDatasetsAndUpdate( Labels,
  GetLineChartDataset1(),
  GetLineChartDataset2(),
  GetLineChartDataset3(),
  GetLineChartDataset4() );
```

**Comment by ElgersNiels** [comment]
> You just need to add multiple datasets to the chart

Doing so indeed adds another dataset, but it uses the same y-axis. Not a new one.

![image](https://user-images.githubusercontent.com/7439596/159142278-fdb41b27-b041-4cfd-a345-7ad2698a04ae.png)

Is there a way to add a second Y-axis like in OP's example? There are Y-axis both left and right.
