### ISSUE TITLE
DataGrid: in VirtualizeManualReadMode, if ReadData returns synchronously, sorting would not work

### ISSUE THREAD

**Issue by hillin** [Megabit/Blazorise#3516]
**Describe the bug**
In the DataGrid component, if Virtualize is enabled and data is read with the `ReadData` callback, and the callback returns synchronously, the sorting (by clicking on column headers) would not work correctly.

This is because in such scenario, the updated (sorted) `Data` would not be reflected to the DataGrid component in time, the DataGrid will use old `Data` to render; i.e. [`SetParametersAsync`](https://github.com/Megabit/Blazorise/blob/b8cdc71b1352010832fef3f54a6650557ad5a231/Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs#L241) is called after [`VirtualizeItemsProviderHandler`](https://github.com/Megabit/Blazorise/blob/b8cdc71b1352010832fef3f54a6650557ad5a231/Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs#L1044).

**Comment by hillin** [comment]
A repro has been pushed to https://github.com/hillin/BlazoriseIssues (use the Blazorise3516 project):
- Click on the `Name` column header, it appears we are sorting with the `Name` field ascendingly, but the list content won't change;
- Click again, it appears we are sorting with the `Name` field descendingly, but actually data is shown ascendingly sorted. Scroll down a bit to trigger another data read, you can see now the data is sorted descendingly
- Click again, we should not be sorting with the `Name` field, but the data is still sorted descendingly. Scroll down a bit to trigger another data read, you can see now the data is unsorted.

**Comment by hillin** [comment]
Returns synchronously means, despite the method is an async method which returns a `Task`, nothing in it is awaited. A method which returns `Task.CompletedTask` is exactly such a synchronous method. 

If you have cloned the repro, you can try to remove the `async` modifier in the `OnReadDataAsync` method and return `Task.CompletedTask` in it, this won't change the behavior of the bug.

**Comment by stsrki** [comment]
Adding `await Task.Yield();` works.

```cs
private async Task OnReadDataAsync( DataGridReadDataEventArgs<ListItem> e )
{
    await Task.Yield();

    var query = FakeData.AsQueryable();

    foreach ( var column in e.Columns.OrderBy( c => c.SortIndex ) )
    {
        switch ( column.SortDirection )
        {
            case SortDirection.Ascending:
                query = query.OrderBy( column.Field );
                break;

            case SortDirection.Descending:
                query = query.OrderBy( column.Field + " desc" );
                break;
        }
    }

    Data = query.Skip( e.VirtualizeOffset ).Take( e.VirtualizeCount )
        .ToArray();
}
```

@David-Moreira Can you investigate this? I think it is indeed a bug and it should work without having to `Task.Yield()`.

---

@hillin I have noticed a flaw in your orderby expression and you should incorporate `ThenBy` if you want to link multiple sort fields. Here are some extension methods that could help you.

```cs
using System.Linq;
using System.Linq.Dynamic.Core;
using System.Linq.Expressions;

namespace Blazorise3516
{
    public static class IQueryableExtension
    {
        public static bool IsOrdered<T>( this IQueryable<T> queryable )
        {
            if ( queryable == null )
            {
                throw new ArgumentNullException( "queryable" );
            }

            return queryable.Expression.Type == typeof( IOrderedQueryable<T> );
        }

        public static IQueryable<T> SmartOrderBy<T>( this IQueryable<T> queryable, string ordering )
        {
            if ( queryable.IsOrdered() )
            {
                var orderedQuery = queryable as IOrderedQueryable<T>;
                return orderedQuery.ThenBy( ordering );
            }
            else
            {
                return queryable.OrderBy( ordering );
            }
        }

        public static IQueryable<T> SmartOrderByDescending<T>( this IQueryable<T> queryable, string ordering )
        {
            if ( queryable.IsOrdered() )
            {
                var orderedQuery = queryable as IOrderedQueryable<T>;
                return orderedQuery.ThenBy( ordering + " desc" );
            }
            else
            {
                return queryable.OrderBy( ordering + " desc" );
            }
        }
    }
}
```

**Comment by hillin** [comment]
Indeed, adding `await Task.Yield()` (or practically anything awaitable) can be a workaround, because it throws anything after the `await` onto a thread pool thread to execute (rather than on the thread of the current dispatcher), so the dispatcher can just go ahead and trigger the `SetParametersAsync` event which makes data binding updated.

For the `OrderBy` part - thanks! This is just a demonstration of the bug so we didn't pay attention to the details. In the real world we generate a sort query and use [Dynamic Linq](https://dynamic-linq.net/) to handle the sorting on the server side.
