### ISSUE TITLE
Question about DataGrid pager button sizes

### ISSUE THREAD

**Issue by TorreyGarland** [Megabit/Blazorise#3528]
How do you change the button sizes of the pager buttons?

Is there a setting or enum to change the built-in button sizes?

**Comment by stsrki** [comment]
At the moment you can only do it with the templates

- `PageButtonTemplate`. 
- `FirstPageButtonTemplate`
- `LastPageButtonTemplate`
- `PreviousPageButtonTemplate`
- `NextPageButtonTemplate`

Having a simple size parameter might be a good feature to have. Going on the list.
