### ISSUE TITLE
NumericPicker with CurrencySymbol can't set value

### ISSUE THREAD

**Issue by mtbayley** [Megabit/Blazorise#3529]
I am having problems with the new NumericPicker setting a value when CurrencySymbol is enabled

It can be recreated in the demo:

![Animation](https://user-images.githubusercontent.com/34929316/156817097-a44f19e3-5baa-4baa-81a6-8716fcbe84d3.gif)

**Comment by stsrki** [comment]
I can reproduce the issue. Until it is fixed, can you try with `Debounce="true"`?
