### ISSUE TITLE
Better formatting of default sort template

### ISSUE THREAD

**Issue by mtbayley** [Megabit/Blazorise#3530]
The formatting of the sort template does not look nice. It would be better if the Sort icon has a bit of whitespace between the header text and the sort icon.

![image](https://user-images.githubusercontent.com/34929316/156823312-bc37917e-3599-4cea-bda8-6b48e1ada7a4.png)

#3495 Applies the sort icon to all of the sortable DataGrid columns. When you have a lot of columns, it can start to look ugly IMO.

Any other suggestions?

**Comment by mtbayley** [comment]
Do we even need the default sort icon at all? Looking at other grids out there, many of them don't have a default sort icon. Is it possible to have this as an opt in option?

**Comment by stsrki** [comment]
Yeah, we might add an opt-in parameter. In the meantime, you can render your own icons by using the `SortDirectionTemplate`.

**Comment by mtbayley** [comment]
My only problem with that is that you have to define that for every column. It would be nice to do that at the table level.

**Comment by David-Moreira** [comment]
You could also do your own column implementation with these defined in a single place.

**Comment by mtbayley** [comment]
Yes, I could do that.

I just think that this showing the icon should not be default as it was before 1.0. Especially with how it looks.

**Comment by stsrki** [comment]
@David-Moreira What do you think we revert to previous without the icon? And then for 1.1, we introduce a new opt-in API to show or hide the sort icon?

I think it is less problematic to revert now as it is not a big change.

**Comment by David-Moreira** [comment]
I guess it's okay

**Comment by mtbayley** [comment]
Appreciate the quick change. Thank you!
