### ISSUE TITLE
Documentation of BlazoriseOptions.EnableNumericStep outdated

### ISSUE THREAD

**Issue by StefanOssendorf** [Megabit/Blazorise#3542]
**Describe the bug**
The XML doc of BlazoriseOptions.EnableNumericStep still points to the `NumericEdit` but sould have beend changed to `NumericPicker` of the v1.0 release.

**Expected behavior**
Correct intellisense pointing to `NumericPick`.

**Comment by stsrki** [comment]
Fixed
