### ISSUE TITLE
Markdown exception when binding on first use

### ISSUE THREAD

**Issue by blakepell** [Megabit/Blazorise#3545]
**Describe the bug**

I'm using the Markdown control and I'm receiving an exception the first time it's used if I'm binding to it.  Subsequent calls from any page work (making an assumption that something is initialized at that point).  It appears that it could be some kind of race condition which I will explain farther down.

#### JavaScript exception

``` javascript
  // Unhandled exception rendering component: Cannot read properties of undefined (reading 'on')
  easyMDE.codemirror.on("change", function () {
```

#### Blazor Exception

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read properties of undefined (reading 'on')
      TypeError: Cannot read properties of undefined (reading 'on')
          at Module.initialize (https://localhost:7146/_content/Blazorise.Markdown/markdown.js?v=1.0.0.0:141:24)
          at https://localhost:7146/_framework/blazor.webassembly.js:1:3332
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:7146/_framework/blazor.webassembly.js:1:3306)
          at Object.St [as invokeJSFromDotNet] (https://localhost:7146/_framework/blazor.webassembly.js:1:59849)
          at _mono_wasm_invoke_js_blazor (https://localhost:7146/_framework/dotnet.6.0.2.47dvak3dg5.js:1:194973)
          at wasm://wasm/00970812:wasm-function[219]:0x1a129
          at wasm://wasm/00970812:wasm-function[167]:0xcaf7
          at wasm://wasm/00970812:wasm-function[166]:0xba0a
          at wasm://wasm/00970812:wasm-function[2810]:0xabacf
Microsoft.JSInterop.JSException: Cannot read properties of undefined (reading 'on')
TypeError: Cannot read properties of undefined (reading 'on')
    at Module.initialize (https://localhost:7146/_content/Blazorise.Markdown/markdown.js?v=1.0.0.0:141:24)
    at https://localhost:7146/_framework/blazor.webassembly.js:1:3332
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:7146/_framework/blazor.webassembly.js:1:3306)
    at Object.St [as invokeJSFromDotNet] (https://localhost:7146/_framework/blazor.webassembly.js:1:59849)
    at _mono_wasm_invoke_js_blazor (https://localhost:7146/_framework/dotnet.6.0.2.47dvak3dg5.js:1:194973)
    at wasm://wasm/00970812:wasm-function[219]:0x1a129
    at wasm://wasm/00970812:wasm-function[167]:0xcaf7
    at wasm://wasm/00970812:wasm-function[166]:0xba0a
    at wasm://wasm/00970812:wasm-function[2810]:0xabacf
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at Blazorise.Markdown.JSMarkdownModule.Initialize(DotNetObjectReference`1 dotNetObjectRef, ElementReference elementRef, String elementId, Object options)
   at Blazorise.Markdown.Markdown.OnAfterRenderAsync(Boolean firstRender)
```

When I load markup from an API, it typically shows the markup but also an unhandled exception.  If I add a `await Task.Delay(1000)` in that function, it seems to work (which is why I think it's a race condition, possibly because I'm doing something wrong).  I can consistently recreate in Edge/Chrome but not in FireFox.

``` razor
<Markdown @bind-Value="issueModel.Markdown">
</Markdown>
```

``` csharp
protected override async Task OnParametersSetAsync()
{
    issueModel = await Http.GetFromJsonAsync<Issue>($"Issue/Get/{this.Id}");

    if (issueModel == null)
    {
        NavManager.NavigateTo("/");
        return;
    }
}
```

In my `Index.html` I include these references:

```
<link href="https://unpkg.com/easymde/dist/easymde.min.css" rel="stylesheet" />
<script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
<script src="https://cdn.jsdelivr.net/highlight.js/latest/highlight.min.js"></script>
<script src="_content/Blazorise.Markdown/markdown.js" type="module"></script>
```

**To Reproduce**

1. Add a markdown control bound a model property that holds markdown.
2. Load the model in  `OnParametersSetAsync()`.

**Expected behavior**

The unhandled exception on "codemirror.on" doesn't occur.

**Comment by stsrki** [comment]
Where do you call the API to load the content?

**Comment by blakepell** [comment]
On the client in `OnParametersSetAsync()` (included in the above post).  On the Server in an API controller in a get method (included below).  I should note, the object is returned from the controller and it puts the content into the markdown control (even with that exception).

```
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [Route("Get/{id}")]
        [HttpGet]
        public Issue? Get(int id)
        {
            return _context.Issues.FirstOrDefault(x => x.Id == id);
        }
```

<img width="551" alt="image" src="https://user-images.githubusercontent.com/5958430/157115370-0f779b6a-92fe-4e1a-a87e-2e831c8da95f.png">

**Comment by blakepell** [comment]
So, I put a break point in `OnParametersSetAsync()` and check this out, you can see at the point the data has returned (and the model is valid and has data) that the `Markdown` editor hasn't initialized totally.  If I put a `await Task.Delay(1000)` then that editor initializes and you can see it on the screen (with no exception).  I'm only using `Task.Delay` to simulate a scenario where the editor has more time to initialize.

#### Without Task.Delay

![image](https://user-images.githubusercontent.com/5958430/157126323-6b4edb75-0e98-45c0-bcdc-0c86c601ca3e.png)

#### With Task.Delay (once the delay is done, the markdown appears).

<img width="729" alt="image" src="https://user-images.githubusercontent.com/5958430/157126516-eb9b9fd8-5b2c-4ce5-8596-12f81a08fe75.png">

**Comment by blakepell** [comment]
Ok.. I have a work around (I know it's not pretty).  On my landing page, I put an empty markdown control inside of an invisible div.  Any subsequent usages of the markdown control from other pages work then.

``` razor
<div style="visibility: hidden">
    <Markdown></Markdown>
</div>
```

**Comment by Jimmys20** [comment]
Hello, might be a stupid idea but you could try to load the data from your service inside `OnInitializedAsync` instead of `OnParametersSetAsync`

**Comment by stsrki** [comment]
Yeah, don't put you data loading in `OnParametersSetAsync`. It is called EVERY time you do any interaction on a page. Meaning you will call API every time also. Do it in `OnAfterRenderAsync`, and if `firstRender` is true.

**Comment by blakepell** [comment]
Thank you, this does fix the javascript exception.  The only additional thing I had to call was `StateHasChanged()` in order to see the values update on the page.

Thank you again @stsrki and @Jimmys20.  It is sincerely appreciated.

```
protected override async Task OnAfterRenderAsync(bool firstRender)
{
    if (firstRender)
    {
        issueModel = await Http.GetFromJsonAsync<Issue>($"Issue/Get/{this.Id}");

        if (issueModel == null)
        {
            NavManager.NavigateTo("/");
            return;
        }

        this.StateHasChanged();
    }

    return;
}
```

**Comment by stsrki** [comment]
One last thing, prefer to call `StateHasChanged` like:

- `InvokeAsync(StateHasChanged)` or
- `await InvokeAsync(StateHasChanged)`

It would save you a lot of trouble with potential deadlocks in the future.

**Comment by blakepell** [comment]
Thank you very much for the tip (first Blazor project I've worked on).  I'll go change my usages of it now. :)
