### ISSUE TITLE
NumericPicker does not bind value when using CurrencySymbolPlacement and CurrencySymbol

### ISSUE THREAD

**Issue by badruby** [Megabit/Blazorise#3547]
Following code should bind value to "test", however it does not.  If one would remove CurrencySymbolPlacement and CurrencySymbol. it does bind.

<NumericPicker TValue="int" Decimals="0" CurrencySymbolPlacement="CurrencySymbolPlacement.Suffix" CurrencySymbol="kr" @bind-Value="test"></NumericPicker>

code{
public int test = new int();
}

**Comment by stsrki** [comment]
The fix is already worked on. We had some small issues with NumericPicker. #3544

**Comment by badruby** [comment]
great news =)
