### ISSUE TITLE
Datagrid: when selection changes, PageSize gets reset to default

### ISSUE THREAD

**Issue by WillianGruber** [Megabit/Blazorise#3548]
Datagrid: when selection changes, PageSize gets reset to default

In Datagrid:
PageSize="@pageSize"
or
PageSize="10"

In code:
private int pageSize = 10;

after selecting other value for page size (5 or 25 for example), and then selecting a row, the page size gets reset

**Comment by stsrki** [comment]
You're missing bind. Try `@bind-PageSize="@pageSize"`.

**Comment by David-Moreira** [comment]
@WillianGruber as this worked out for you? :)
