### ISSUE TITLE
Datagrid multi selection not working properly

### ISSUE THREAD

**Issue by itsLollo1000** [Megabit/Blazorise#3551]
Hey,
when selecting a row by its check box the row may be selected and highlighted but the checkbox doesnt change to checked.

Change DataGrid selection-mode to Multi-Selection
Check any row with its Checkbox

**Expected behavior**
Checkbox should be checked

Also please provide a sample code or point us to a minimalistic GitHub repo

![image](https://user-images.githubusercontent.com/10349466/157229776-2e74d0a4-a89d-4b36-8ef0-151d43736284.png)

**Comment by stsrki** [comment]
@David-Moreira  Tested it on https://bootstrap5demo.blazorise.com/tests/datagrid and it is not working.

**Comment by itsLollo1000** [comment]
> @David-Moreira Tested it on https://bootstrap5demo.blazorise.com/tests/datagrid and it is not working.

https://gyazo.com/61bf5f79e594651ca376a81335496a40

**Comment by itsLollo1000** [comment]
@PavloParafiloCricut & @stsrki does this issue still exist?

When I try it on https://bootstrap5demo.blazorise.com/tests/datagrid it seems to.

**Comment by stsrki** [comment]
It should be fixed on NuGet. I just didn't upload demos yet. My internet speed is too slow so I tend to skip demos if there are no major changes to upload 😅
