### ISSUE TITLE
Date Range Picker settings

### ISSUE THREAD

**Issue by itsLollo1000** [Megabit/Blazorise#3552]
Hey,

just seen you guys have added a new Date Picker.
I sort of like it! But I would like to suggest some changes/features to it.

Would it be possible to change the text of the range selection for example: from "to" into "-".
This could simplify the process of manually typing a date range.

Secondly I also like the multi selection of single dates. 
But would it be possible to combine the two Date Picker selection modes into one? Where you select a range when holding shift and still can pick and add a single day?

Last but not least, congrats on the release of 1.0.0 🎉 !!!

Kind Regards
Sebastian Gerner

**Comment by stsrki** [comment]
Not promising but we can try.

**Comment by itsLollo1000** [comment]
No worries! 

Just some random ideas!
