### ISSUE TITLE
DataGrid: opt-in parameter to use default sort icon

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#3554]
@David-Moreira What do you think we revert to previous without the icon? And then for 1.1, we introduce a new opt-in API to show or hide the sort icon?

I think it is less problematic to revert now as it is not a big change.

_Originally posted by @stsrki in https://github.com/Megabit/Blazorise/issues/3530#issuecomment-1060606472_

**Comment by itsLollo1000** [comment]
Haha just changed it in everygrid column, because I did not like the new one 🤣
