### ISSUE TITLE
TextColor Enums in 1.0.1 Not Working

### ISSUE THREAD

**Issue by stevenlupo** [Megabit/Blazorise#3558]
Just upgraded to 1.0.1 and it seems the `TextColor` enums are not working. For example, `TextColor.Danger` has no effect.

I read the release notes and I see there were some changes in that area. Maybe I'm just missing something simple.

**Comment by stsrki** [comment]
Can you post the code snippet of how you're using it?

**Comment by stevenlupo** [comment]
```
<Paragraph Color="TextColor.White">
  some text here
</Paragraph>
```

**Comment by stsrki** [comment]
Try

```
<Paragraph TextColor="TextColor.White">
  some text here
</Paragraph>
```

The Color parameter, with some others was marked obsolete in previous versions, and in v1 we have replaced them with new names. It was mentioned in the release notes under migration.

**Comment by stevenlupo** [comment]
Yes, I figured that out just as you replied.

Thanks.
