### ISSUE TITLE
Filterable  Datagrid - result to new List

### ISSUE THREAD

**Issue by HansMeiser234** [Megabit/Blazorise#3561]
Hello,

iam new to c# and blazor, but it is really fun and blazorise lets you achieve great things.

Currently is use datagrids to display my by SQL collected data (only a few lines). The Filterable Feature ist really helpful to reduce to really interesting data.
But filtering is only optical by hidding not fitting list items in website, it is not affecting any dataobjects.
Iam looking for a way to achive this.  I try to work further with filtered data, but you dont have any idea of filtered data nor the filter which was used in every column.
May be the filtered data could be filled in a new resulting list, ready to get processed.
It would be nice to have such a comfortable way in blazorise.
Or is there already a solution which i missed?

Thanks,
Hans

**Comment by stsrki** [comment]
Do you mean to get the filter data, that are currently visible?

You can have that already:

First, define a member variable to hold the grid reference

`private DataGrid dataGridRef;`

the assign it

`<DataGrid @ref="@dataGridRef" >`

and read it through property getter

`var data = dataGridRef.FilteredData;`

**Comment by HansMeiser234** [comment]
Hello,

that was quick.

You are right. As a newbie i had to bite a little bit but now it works and i learned something about c#.

Thanks,
Hans

**Comment by David-Moreira** [comment]
Closing this as it does seem to be solved. Just let us know if you have any other doubts. If you're not sure if it's an actual issue you can go ahead and open a thread over at Discussions or ask on our Discord Channel.
