### ISSUE TITLE
Internals : Replace System.Timers.Timer with PeriodicTimer

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#3564]
Investigate https://docs.microsoft.com/en-us/dotnet/api/system.threading.periodictimer?view=net-6.0
as a replacement for **System.Timers.Timer**

For example in Carousel usage.

**Comment by stsrki** [comment]
Seems like a good feature.

**Comment by David-Moreira** [comment]
Abandoned implementation as it was apparently not quite better then the current implementation.
