### ISSUE TITLE
DataGrid: dynamic columns and editing

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#3579]
Create a new generator for columns based on the model and data annotations. End result would allow having a DataGrid that is only defined by the `Data` and `TItem`.

Eg.

`<DataGrid TItem="Student" Data="@students" />`

All columns and edit fields would be generated dynamically.

**Comment by David-Moreira** [comment]
And probably the additional AutoGenerate parameter or smthg 😆

**Comment by stsrki** [comment]
Not necessarily. If columns are not explicitly defined that means we will autogenerate them.

**Comment by David-Moreira** [comment]
OK well see... I think it's easier with explicit parameter, otherwise you probably have to recheck constantly? 

User can also have his own dynamic implementation... Or switch between both for some reason which the. Explicit parameter would make it easier.

Matter of trying, good feature, very clean for simple crud grids.

**Comment by stsrki** [comment]
Well, we do know if columns are used by the user dynamically or manually. Once placed inside of grid it will internally call `AddColumn`. And even if the users are calling it still means it is not dynamic. Meaning it will be manual mode, So we do have the means to know.

**Comment by David-Moreira** [comment]
I guess... i was actually talking about a foreach with the columns, still we know. 

>  And even if the users are calling it still means it is not dynamic.

Users can do a dynamic implementation currently if they want. But yea I gotcha.

**Comment by jamescurran** [comment]
> Users can do a dynamic implementation currently if they want. 

Actually, it seems that users cannot do a dynamic implementation currently.

Calling `grid.AddColulmn(col);`   with a `col` created by `new DataColumn() {....}`;  will throw an exception.  `new` creates the column in an invalid state.  A functioning DataColumn object needs values injected from the IoC container, and then having the (protected) `OnInitialize()` called.

**Comment by David-Moreira** [comment]
It's been a while. 

I don't know whether I meant they could dynamically generate by using `grid.AddColumn` or by just having a system rendering columns conditionally, which I have seen a few successful implementations here and there. 

But yes, we have not tested & approved programmatically being able to set the columns. The DataGrid is still currently limited in that department.

@stsrki what do you think on moving this one to **v1.4**?

Also looking at this again, I still think the `AutoGenerate` parameter is best. If you have to figure out whether columns exist, that means, you have to do checks later on the lifecycle of the component? But we can try without it, if you're still adamant on it being magical. :D

**Comment by stsrki** [comment]
> But we can try without it, if you're still adamant on it being magical. :D

Yes, do the magic 🤣

Moving to 1.4

**Comment by stsrki** [comment]
For reference: https://docs.abp.io/en/abp/latest/UI/AspNetCore/Tag-Helpers/Dynamic-Forms
