### ISSUE TITLE
Add an option to disable row moving to top of datagrid when being edited with virtualize enabled

### ISSUE THREAD

**Issue by JonathanShrek** [Megabit/Blazorise#3588]
I have a datagrid that I can inline edit. When I use Virtualize on the datagrid and I double click to edit the row it suddenly jumps to the top of the datagrid. Is there a way that I can use virtualize without it moving the row I'm editing to the top of the table?

I'd like an option within the virtualize options to disable this behavior from occurring.

**Comment by David-Moreira** [comment]
I think there was a technical reason why we had to implement this behaviour, I have to remember why, I'll let you know.

**Comment by stsrki** [comment]
If was because the Edit form would be mostly hidden when we inter into edit mode. So we had to scroll down. Maybe Inline mode can stay as it is without moving to the top. Need to test to make sure.

**Comment by David-Moreira** [comment]
Right but we do have the `VirtualizeOptions` api, so we can still leave it on by default, and just harmlessly add an option to disable this behaviour.
