### ISSUE TITLE
MessageService: option to change the modal sIze

### ISSUE THREAD

**Issue by Keltanis** [Megabit/Blazorise#3593]
**Describe the bug**
When incorporating Messages, the modal takes up the entire page (height-wise), even though the message is very short.

**To Reproduce**
4. See an error

**Expected behavior**
The size or height should be able to be set.

Also please provide a sample code or point us to a minimalistic GitHub repo

**Screenshots**

**Additional context**

**Comment by stsrki** [comment]
Can you post any code to reproduce it?

**Comment by stsrki** [comment]
OK, I will change the title accordingly.
