### ISSUE TITLE
Vertical Divider

### ISSUE THREAD

**Issue by bastigerner** [Megabit/Blazorise#3594]
Hey,

as far as I am aware, currently blazorise only has a horizontal divider.

Would be cool if the divider would have an option to select whether it is horizontally or vertically.

Kind regards
Sebastian Gerner

**Comment by stsrki** [comment]
We can consider it for one of the next milestones.

**Comment by itsLollo1000** [comment]
`<Div Style="border-left: var(--b-divider-thickness, 1px) solid var(--b-divider-color, #999);" />
`
Currently using this as a solution

**Comment by stsrki** [comment]
To have a vertical divider, the surrounding element should be placed in a container that would somehow need to be organized. Possibly with a flow or grid CSS.

We have decided that we will not be following this feature. The main reason is that it would "break" the flow of the page, according to the discussion on https://stackoverflow.com/questions/571900/is-there-a-vr-vertical-rule-in-html
