### ISSUE TITLE
Binding of Text for TextEdit Not Working

### ISSUE THREAD

**Issue by Keltanis** [Megabit/Blazorise#3600]
**Describe the bug**
When using @bind-Text on a TextEdit component and submission occurs, The value is not passed.

**Expected behavior**
The value should be passed thru the Parmeter from the binding to the variable.

Currently, I have 2 Razor files and their Code-behinds. One Razor (**R2**) page is a component. The other (**R1**) page renders **R2**.
**R1** Contains:

```
<R2 ...
    FirstValue="@firstValue"
    SecondValue="@secondValue"
    ... />
```

The **R1 Code-behind** has the following:

```
private string firstValue= string.Empty;
private string secondValue= string.Empty;

public ...()
{
    if (firstValue!= string.Empty && secondValue!= string.Empty)
    {
        // Do Something. BUT firstValue and secondValue are ALWAYS empty.
    }
}
```

**R2** contains the following:

```
<Table>
    <TableBody>
        <TableRow>
            <TableRowCell>
                <TextEdit Placeholder="Enter Value" @bind-Text="@FirstValue"></TextEdit>>
            </TableRowCell>
            <TableRowCell>
                <TextEdit Placeholder="Enter Value" @bind-Text="@SecondValue"></TextEdit>
            </TableRowCell>
        </TableRow>
    </TableBody>
</Table>
```

The **R2 Code-behind** contains:

```
[Parameter]
public string FirstValue{ get; set; }
[Parameter]
public string SecondValue{ get; set; }
```

When submitting with text, the firstValue and secondValue come up as empty strings

**Comment by stsrki** [comment]
You're not having the same variables used

![image](https://user-images.githubusercontent.com/900302/158749779-ab601191-96bc-4237-b28e-5de46d8ca48b.png)

**Comment by Keltanis** [comment]
That’s why I’m my R2 component, when called by R1, I set the parameters. I.g. FirstValue = ***@***.***”. That way, the binding should map. Works with other parameters that I map, just not these for some reason. 




Wednesday, March 16, 2022, 11:27 PM -0700 from ***@***.***  ***@***.***>:

**Comment by stsrki** [comment]
It's because you only have one-way binding with `FirstValue="@firstValue"`. To make it able to return value from R2 you need to have `@bind-FirstValue="@firstValue"`.

But then you also need to add `FirstValue` inside of R2. 

And:

```
<TextEdit Placeholder="Enter Value" Text="@FirstValue" TextChanged="@OnFirstValueChanged"></TextEdit>

@code{
  Task OnFirstValueChanged(string value)
  {
    FirstValue = value;
    return FirstValueChanged.InvokeAsync(FirstValue);
  }

  [Parameter]
  public string FirstValue{ get; set; }
  
  [Parameter]
  public EventCallback<string> FirstValueChanged{ get; set; }
}
```

**Comment by Keltanis** [comment]
Okay, will try it out and let you know. Thanks!




Thursday, March 17, 2022, 3:26 AM -0700 from ***@***.***  ***@***.***>:
>It's because you only have one-way binding with ***@***.***". To make it able to return value from R2 you need to have @***@***.***".
>But then you also need to add FirstValue inside of R2.
>And:
><TextEdit Placeholder="Enter Value" ***@***.***" ***@***.***"></TextEdit>
>
***@***.***{

**Comment by stsrki** [comment]
Any news? Did it help you?

**Comment by Keltanis** [comment]
It did. Thanks!
    	Brent Ricks
    
  

 From: Mladen Macanović ***@***.***>Sent: Wednesday, March 30, 2022 6:59 AMTo: Megabit/Blazorise ***@***.***>Cc: Keltanis ***@***.***>; Author ***@***.***>Subject: Re: [Megabit/Blazorise] Binding of Text for TextEdit Not Working (Issue #3600) 
Any news? Did it help you?
