### ISSUE TITLE
Unit tests for components with DataGrid fail after upgrade to 1.0.1

### ISSUE THREAD

**Issue by gkapelevich** [Megabit/Blazorise#3603]
**Describe the bug**
Unit tests for pages with DataGrid fail after upgrade to 1.0.1.  The page works fine (see example below).

**To Reproduce**
The page:
```
@page "/test"

<h3>TestPage</h3>

<DataGrid TItem="UserListItem" Data="@users" ReadData="@onReadData">
    <ChildContent>
        <DataGridColumn TItem="UserListItem" Field="UserName" Caption="User Name" />
        <DataGridColumn TItem="UserListItem" Field="Email" Caption="Email" />
    </ChildContent>
</DataGrid>

@code {
    private IEnumerable<UserListItem> users;

    private void onReadData(DataGridReadDataEventArgs<UserListItem> e)
    {
        users = new List<UserListItem>()
        {
            new UserListItem() { UserName = "Bob", Email="bob@test.com" },
            new UserListItem() { UserName = "Joe", Email="joe@test.com" },
        };
    }
}
```

Unit Tests:
```
using System.Linq;
using Bunit;
using FluentAssertions;
using Xunit;

namespace MyProject.Tests
{
    public class TestPageTests : TestContext
    {
        public TestPageTests()
        {
            BlazoriseConfig.AddBootstrapProviders(this.Services);
            this.JSInterop.Mode = JSRuntimeMode.Loose;
            BlazoriseConfig.JSInterop.AddDataGrid(this.JSInterop);
        }

        [Fact]
        public void Page_ShouldLoad()
        {
            // Act
            var component = RenderComponent<TestPage>();

            // Assert
            component.Find("h3").TextContent.MarkupMatches("TestPage");
        }

        [Fact]
        public void Page_ShouldLoadData()
        {
            // Act
            var component = RenderComponent<TestPage>();
            component.WaitForState(() => component.FindAll(".table-row-selectable").Any());  // Wait for data to load

            // Assert
            component.FindAll(".table-row-selectable").Count().Should().Be(2);
        }
    }
}
```
Page_ShouldLoad test passes, but Page_ShouldLoadData test fails because data rows are never added to the grid.  `onReadData `method doesn't execute.

Error details:
```
TestPageTests.Page_ShouldLoadData
   Source: TestPageTests.cs line 30
   Duration: 1.1 sec

  Message: 
    Bunit.Extensions.WaitForHelpers.WaitForFailedException : The state predicate did not pass before the timeout period passed.

  Stack Trace: 
    RenderedFragmentWaitForHelperExtensions.WaitForState(IRenderedFragmentBase renderedFragment, Func`1 statePredicate, Nullable`1 timeout) line 28
    --- End of stack trace from previous location ---
    RenderedFragmentWaitForHelperExtensions.WaitForState(IRenderedFragmentBase renderedFragment, Func`1 statePredicate, Nullable`1 timeout) line 38
    TestPageTests.Page_ShouldLoadData() line 34
```

**Expected behavior**
DataGrid should load data during unit test.

**Comment by gkapelevich** [comment]
I updated my BlazoriseConfig to match the one in Blazorise repo.  I had to comment out following lines:

```
//services.AddSingleton<Blazorise.IBehaviourProvider>(new Blazorise.Bootstrap.BootstrapBehaviourProvider());

//services.AddMemoryCache();
//services.AddScoped<Blazorise.Shared.Data.EmployeeData>();
//services.AddScoped<Blazorise.Shared.Data.CountryData>();
```

I'm not sure if this is relevant to this issue.

**Comment by David-Moreira** [comment]
Hello @gkapelevich ,
Just to keep you posted.

We've recently added some js that needs to initialize on the Datagrid's first render. 
Now the call isn't being returned back to the caller successfully, it probably deadlocks.
Tried adding ConfigureAwait(false) with no success, I am not yet sure if this is an issue with how **BUnit** is handling the js mocking and async execution that may be blocking the async code. So we'll probably have to troubleshoot together with **BUnit**'s team
![Sem Título](https://user-images.githubusercontent.com/22283161/160020088-9bfbb5ab-4f87-4d44-b92d-b42f2c3607ad.png)

I guess as a temporary workaround you can just bind the data directly and dismiss the ReadData.

We'll let you know as soon as we figure out a fix to this.

Also, could you also provide us with the previous version you were using.

**Comment by illiniguy** [comment]
I'm working with @gkapelevich on our upgrade. He'll still be main 'contact' about it but FYI we are currently at 0.9.5.5 of Blazorise, aiming to go to 1.0.1.

**Comment by David-Moreira** [comment]
Hello @illiniguy  // @gkapelevich 
Following Bunit's recommendations the mocked calls should call `SetVoidResult()` or `SetResult(TGeneric)` accordingly. 

We'll be updating our js mocks to reflect this.

Please, do try to update on your side following these recommendations and let us know your results. Thanks!

**Comment by gkapelevich** [comment]
Yes, adding `SetVoidResult()` or `SetResult(TGeneric)` fixed our DataGrid unit tests.  Thanks!
