### ISSUE TITLE
datagrid width not working with a lot of columns

### ISSUE THREAD

**Issue by benny-adiwijaya** [Megabit/Blazorise#3604]
Hi,

I cannot change width when there are a lot of columns.

this is my simple sample code

@page  "/testdatagrid"

<DataGrid TItem="Employee"
          Data="@employeeList"
          @bind-SelectedRow="@selectedEmployee"
          Responsive="true">
  

> 

   

> <DataGridCommandColumn />

    <DataGridColumn Field="@nameof(Employee.Id)" Caption="#" Sortable="false" Width="600px" />
    <DataGridColumn Field="@nameof(Employee.FirstName)" Caption="First Name" Editable />
    <DataGridColumn Field="@nameof(Employee.LastName)" Caption="Last Name" Editable />
    <DataGridColumn Field="@nameof(Employee.Email)" Caption="Email" Editable />
    <DataGridColumn Field="@nameof(Employee.Salary)" Caption="Salary" DisplayFormat="{0:C}" DisplayFormatProvider="@System.Globalization.CultureInfo.GetCultureInfo("fr-FR")" Editable>
        <EditTemplate>
            <NumericEdit TValue="decimal" Value="@((decimal)context.CellValue)" ValueChanged="@( v => context.CellValue = v)" />
        </EditTemplate>
    </DataGridColumn>
</DataGrid>

@code{

    private List<Employee> employeeList { get; set; } = new List<Employee>();
    private Employee selectedEmployee;

    protected override void OnInitialized()
    {

        employeeList.Add(new Employee
        {
            Id = 1,
            FirstName = "Adam",
            LastName = "Smith",
            Email = "adam@mail.com",
            Salary = 5000
        });
        employeeList.Add(new Employee
        {
            Id = 2,
            FirstName = "Ben",
            LastName = "John",
            Email = "ben@mail.com",
            Salary = 5000
        });
    }

    public class Employee
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public decimal Salary { get; set; }
    }
}

Its working when using that sample code, but when I duplicate column to more than 20 column it doesnt seem work. Is it possible to modify width with many columns?

**Comment by David-Moreira** [comment]
Have you tried setting Responsive to false? Otherwise it will probably resize the columns according to window size.

**Comment by benny-adiwijaya** [comment]
Setting responsive to false doesnt seem work either, Is there any way to force column width as we expected?
