### ISSUE TITLE
Modal : Focus First Element [Suggestion]

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#3619]
Now with Modal FocusTrap, another good feature would be to be able to optionally focus the first element.

**Comment by stsrki** [comment]
It is already working. We already had an AutoFocus on an input, so if any component has it, it will be focused.

**Comment by David-Moreira** [comment]
So if I set AutoFocus on Modal, will it focus the first element? For example a Textfield? It's pretty common for formularies for example.

**Comment by stsrki** [comment]
You set it on text field, not the modal. This was always the case. You can try it in the demo on both modal page and trapfocus page.

**Comment by David-Moreira** [comment]
I see. This feature is not needed.
