### ISSUE TITLE
ChangeTextOnKeyPress, DelayTextOnKeyPress, DelayTextOnKeyPressInterval

### ISSUE THREAD

**Issue by elshorbagy** [Megabit/Blazorise#3621]
Hello,

I upgraded my Blazorise from 0.9.3.3 to 1.0.1 and after that  these 3 properties disappeared:
**ChangeTextOnKeyPress, DelayTextOnKeyPress, DelayTextOnKeyPressInterval**

This is my code
`public static IServiceCollection AddOpsWorkbenchBlazorise(this IServiceCollection services)
        {
            services
               .AddBlazorise(options =>
               {
                   options.ChangeTextOnKeyPress = false;
                   options.DelayTextOnKeyPress = true;
                   options.DelayTextOnKeyPressInterval = 600;
               }) 
               .AddMaterialProviders()               
               .AddMaterialIcons();
            return services;
        }`
        
        Any idea how to fix that?
        
        Thanks

**Comment by stsrki** [comment]
It seems you have missed out on our migration notes. Look at the https://blazorise.com/news/release-notes/100

They're now named `Immediate` and `Debounce`.
