### ISSUE TITLE
Validate single inputfield with Mode = "ValidationMode.Manual"

### ISSUE THREAD

**Issue by badruby** [Megabit/Blazorise#3623]
Dont know if this is by design or if im doing something wrong. It seems to be inpossible to trigger a validation for a single inputfield when using manual validation. validator.validateall() works. but isnt there a way to specify a single fieldidentifier to just validate single field?

**Comment by stsrki** [comment]
It shouldn't be a problem to have 1 or 100 fields. Can you show us your code?

**Comment by badruby** [comment]
<Validations @ref="validations" Model="@BestallningForm.GeneralForm"  Mode="ValidationMode.Manual"> 
            <Validation Validator="@ValidateSingleField" >
                <Field>
                    <TextEdit @bind-Text="MyObject .test1">
                        <Feedback>
                            <ValidationError />
                        </Feedback>
                    </TextEdit>
                </Field>
            </Validation>
            <Validation Validator>
                <Field>
                    <TextEdit @bind-Text="MyObject test2">
                        <Feedback>
                            <ValidationError />
                        </Feedback>
                    </TextEdit>
                </Field>
            </Validation>
        </div>
<Validations>
code{
    public class Test
    {
        [Required(ErrorMessage = "errormessage here1")]
        public string text1 { get; set; }
        [Required(ErrorMessage = "errormessage here2")]
        public string text2 { get; set; }

    }
    public partial class stuff: ComponentBase
    {
         Validations validations; 
         public Test MyObject { get; set; } = new();

         public void ValidateSingleField(ValidationRequestedEventArgs args)
        {
            //do stuff with text1 here, that doesnt trigger any validation for test2
        }

        public void ValidateAll(ValidationRequestedEventArgs args)
        {

            //validate whole form. both text1 and text2
        }
    }
}

**Comment by badruby** [comment]
im clearly to stupid to paste my testcode here without it becomes messed up in the editor

**Comment by stsrki** [comment]
Seems good to me, although this is strange

![image](https://user-images.githubusercontent.com/900302/159699303-b0a5b831-1b56-4eb9-9207-3b650bdf0f73.png)

---

Back to your question. Are you actually asking to not have `<Validations>` when only one field is used?

**Comment by badruby** [comment]
Thats just a typo from my side =S

Thing is, i have maybe 300 fields. This makes the Auto mode too slow, for user. So. My thought was to have ONE submitbutton to validate everything.  Lets say if 10 fields turn red(couse of missing input). when user then fills these inputs. i want to validate THAT specific field without haven to validate all others fields once again.

**Comment by badruby** [comment]
Something like this but not with editform

![image](https://user-images.githubusercontent.com/9694495/159702076-de16265f-6ef2-42aa-95a9-c4b3789a9366.png)

**Comment by stsrki** [comment]
Ah, that. No, it is not possible. You can only validate all fields at once.

**Comment by badruby** [comment]
damn.. =(

**Comment by stsrki** [comment]
It shouldn't be that problematic. Validation will trigger only those fields that failed.

**Comment by badruby** [comment]
i understand. UI is very slow. starting to think that it has something to do with using a large amount of "numericpicker" and all logic that it contains.

**Comment by stsrki** [comment]
Well, 300 fields is a LOT. You can try split them into a separate sub-group-components.

Like:

- AddressFields.razor
- BillingFields.razor
- etc.

Then on your form use it like

```
<AddressFields Model="@model" />
<BillingFields Model="@model" />
```

where Model is a parameter that you need to create.

The good part is that validation will work but once the change is triggered it will only re-render that part of the form, the inside of the parent component.
