### ISSUE TITLE
AutoComplete Control - Pre-Loaded Values Don't Appear until Mouse Hovers.

### ISSUE THREAD

**Issue by DonSagiv** [Megabit/Blazorise#3627]
**Description**

With the **AutoComplete** Control, whenever I pre-load a selected value, the text for that value does not appear until I hover the cursor over it. 

I use:
- Blazor Server on .NET Version 6 
- Blazorise 1.0.1
- Brave Browser

**To Reproduce**

1. Create an AutoComplete control inside a foreach loop in the Razor page.
2. Pre-load any data for the AutoComplete in the **OnInitializedAsync()** method.
3. See that there the selected text for the value is not pre-populated in each of the textboxes for the AutoComplete control.
4. Hover the mouse over any of the AutoComplete controls, and watch the text for the selected value appear (Shown in the animated GIF below)

Please see the example provided in this GitHub repo: https://github.com/DonSagiv/asagiv.dbmanager/blob/220220_TryBlazorise/asagiv.dbmanager.webportal/Pages/EventGiftInfo.razor

**Expected behavior**

- Upon pre-loading a selected value, the selected value's text should appear on the AutoComplete control's text box without having to hover the mouse over it.

**Screenshots**

![brave_SNeHJQoTnc](https://user-images.githubusercontent.com/13925038/159787906-dd8e11e6-bfd8-41ae-bdfd-7c856e399159.gif)

**Comment by David-Moreira** [comment]
Hello,
I cannot quite run the repository right away, there's a lot of dependencies, could I ask that you make it ready to run?

Thanks!

**Comment by DonSagiv** [comment]
David --

Sure thing, I didn't know you wanted to try to run it. I'll see what I can do and will get back to you once I've made the modifications.

-- Ari

**Comment by DonSagiv** [comment]
Hi, @David-Moreira 

Sorry for taking so long to respond.

I've created a new public repo that reproduces the issue. 

https://github.com/DonSagiv/Megabit_Blazorise_Issue3627

The only dependencies are your Blazorise libraries. Let me know if you have any issues.

-- Ari

**Comment by David-Moreira** [comment]
Thanks for taking the time. :)

**Comment by DonSagiv** [comment]
Can confirm this issue was fixed in 1.0.3.

Thanks for your hard work, @David-Moreira and @stsrki!
