### ISSUE TITLE
Message Service Popup Scaling to 100% Height

### ISSUE THREAD

**Issue by Keltanis** [Megabit/Blazorise#3630]
**Describe the bug**
Guess my discussion should really be a bug?

https://github.com/Megabit/Blazorise/discussions/3629

**To Reproduce**
See info and screenshots in discussion. 

**Expected behavior**
I expect that the displayed window/dialog for Messages and Alerts to auto-scale based on content and not parent size when working with models; otherwise, have the messages and alerts have additional options/attributes to control size, if needed.

**Comment by stsrki** [comment]
Having a minimal project to reproduce it would really help.

**Comment by Keltanis** [comment]
The issue turned out to be a result of overwriting Bootsrap defaults.
