### ISSUE TITLE
TabIndex for form inputs

### ISSUE THREAD

**Issue by HansMeiser234** [Megabit/Blazorise#3646]
Hello,

iam new to c# and blazorise, i have a question to use html-features in Blazorise-Webforms. 
Currently iam looking for a way to have tabindex-HTML Feature in Blazorise. I saw the hint on https://github.com/Megabit/Blazorise/issues/1472 that tabindex was added to all input components, but i miss a hint to the docs how it is to use and is working.
Currently i try to make a small webapplication to gather some data by a handheld scanner.  A handheld scanner works just like a keyboard, you can scan barcodes with data and this data contains also controls like \n Enter or \t for Tab. So you can scan barcodes and submit forms all by scanned input, no need of using a keyboard.
My problem is that my form has 6 input components: selectfield, checkbox, 3 textfields and submitbutton.  selectfield, checkbox and one textfield only have static values which apply for the whole scanprocess. Only 2 of my textfields contain the scanned data and submitbutton adds data to the list. 
When typing tab in form then focus jumps from one field to another and is reaching every single inputfield. I want to achive that tab only switches focus between my 2 inputfields and submit button so you can handle the whole scanprocess by handheld scanner and there is no need of using a keyboard.
Is this achievable with BlazoriseComponents? Or is there any workaround?

I use all blazorise Components in Version 1.0.0.

Thanks for your help and great components,
Hans

**Comment by stsrki** [comment]
This will be possible with the use of the new `FocusTrap` component. But it will only be available in v1.0. We will release a preview soon and you can try it once it is out.

**Comment by HansMeiser234** [comment]
Hello,

great news. I hope we have v1.0 soon, so i can try this new component.
Thanks for your work.

Hans

**Comment by stsrki** [comment]
I realize I have made a typo. It will be available in v1.1 :)

v1.0 is already out.
