### ISSUE TITLE
Global icon options

### ISSUE THREAD

**Issue by ivancavlek** [Megabit/Blazorise#3648]
**Describe the solution you'd like**
It would be great if we could set default parameters for (FontAwesome) Icons in _Program.cs_ which would be default unless we set it differently locally in a component, e.g.
```C#
// Program.cs
builder.Services.AddFontAwesomeIcons(icn => icn.IconStyle = IconStyle.Light); // default setup
```

```C#
// some Component.razor
<Icon IconStyle="IconStyle.Solid" /> // overrides default setup
```

**Comment by stsrki** [comment]
That is a good idea, and it is fairly easy to do. Going on the list.
