### ISSUE TITLE
Autocomplete : Investigate if resetting/clearing values works right

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#3658]
Autocomplete : Investigate if clear values works right

Related issue #142 

>@howardgod hey man , you can do this....i have the same problem on 1.0.1 , i need clean the autocomplete value / text on edit template for grid , but its imposible

**Comment by David-Moreira** [comment]
@rgomezia 

I just tested with this code and it worked. Can you try it on your side? 

```
    private void ResetValue()
    {
        selectedAutoCompleteSearchValue = null;

    }
```

If it still does not work, can I ask that you create a repro?

**Comment by rgomezia** [comment]
@David-Moreira its works , damn bro i thing  in  string all time  ,  i was used to clean  selectedAutoCompleteSearchValue = "" ; and selectedAutoCompleteSearchValue  = string.empty;  I drowned in a glass of water , ty so much!

**Comment by stsrki** [comment]
Glad it worked ;) Closing the ticket now.
