### ISSUE TITLE
Borders not shown after update to .Net 6.0.201 and Blazorise 1.0.2

### ISSUE THREAD

**Issue by samuelhurni** [Megabit/Blazorise#3672]
After a update to the Blazorise Version 1.0.2 and .Net 6.0.201 the borders in Columns and Rows are not displayed. 

I already checked the DevTools and did not found a css style definition for the defined style in the div class.

Example:

`<Row Padding="Padding.Is2" Border="Border.Is2">`

DevTools:

`<div class="row p-2 border-2">`

--> 	no css style found for "border-2"

![image](https://user-images.githubusercontent.com/55551683/161424665-fcc914b5-de3c-4a42-a621-42ac006e9637.png)

**Comment by stsrki** [comment]
Can you try clearing the cache? Ctrl+F5 usually helps in chrome.

**Comment by samuelhurni** [comment]
Ok sry that was my fault, 

clearing the cache solve the problem
