### ISSUE TITLE
Change disabled Check color

### ISSUE THREAD

**Issue by f4n0** [Megabit/Blazorise#3684]
Hi, 
I was able to change the color of a checkbox via themes but if I set the checkbox to "Disabled" it force me to the standard blueish checkbox. 

The check that I'm using is this one:

```
<DataGridCheckColumn TItem="ApiKeyConfiguration"
				 Field="@nameof(ApiKeyConfiguration.EnableLog)"
				 Caption="@nameof(ApiKeyConfiguration.EnableLog)" Editable="true">
	<DisplayTemplate>
		<Check TValue="bool" Checked="@context.EnableLog" ReadOnly Disabled="true" />
	</DisplayTemplate>
</DataGridCheckColumn>
```
I've tried with CSSs, other themes and so on  (also with this issue https://github.com/Megabit/Blazorise/issues/2264 didn't help me)

Am I doing something wrong?

**Comment by stsrki** [comment]
We probably didn't apply CSS for the disabled state in the theme generator.

**Comment by f4n0** [comment]
Thanks for the quick reply!
In the meanwhile, by chance, do you know any workaround that I could use?

**Comment by stsrki** [comment]
Well, you inspect the check elements to see what CSS selectors are used and then adjust them manually in your `site.css`.
