### ISSUE TITLE
Autocomplete Multiple -> css bug

### ISSUE THREAD

**Issue by ArneCools** [Megabit/Blazorise#3686]
**Describe the bug**
When selecting more options than the full width of the input box. The selected options go out of bounds. Example in the official demo:
![image](https://user-images.githubusercontent.com/1440244/162051401-ebd58000-7d00-495c-9933-ec50a9c42176.png)

I managed to fix it using this css:
.b-is-autocomplete.b-is-autocomplete-multipleselection {
    height: auto!important;
}

**Comment by David-Moreira** [comment]
Nice, thanks for noticing, I guess it should auto-grow on multiple selection haha
