### ISSUE TITLE
Prevent mouse wheel to change value on numeric picker

### ISSUE THREAD

**Issue by benny-adiwijaya** [Megabit/Blazorise#3688]
Hi, I want to prevent mouse wheel to change value on numeric picker. I already tried this code but it still change the value by one

```
document.addEventListener("wheel", (e) => {
        if (document.activeElement.className === "form-control text- numeric-picker") {
            e.target.blur();
        }
    });
```
Is it possible to prevent mouse wheel to change value on numeric picker?

**Comment by David-Moreira** [comment]
Hello,
It's probably possible, but you should most likelly add the eventListener to the element itself instead and try `e.preventDefault()`
Could probably also be an opt-in option on NumericPicker, @stsrki what do you think?

**Comment by stsrki** [comment]
I was actually thinking of adding opt-in for the mouse wheel but I forgot TBH. I can disable it in 1.0.3 as a quick fix, and later for 1.1, I can add an option to control it.

**Comment by danielheddelin** [comment]
RN says this was fixed in v1.0.3. I just updated to 1.0.4 and the new attribute isn't there. Was it missed in the release?

**Comment by stsrki** [comment]
In v1.0.4 we only disabled the mouse wheel on the numeric picker so that the API doesn't change. And in v1.1 we will introduce new attribute to control the mouse wheel behavior.

**Comment by danielheddelin** [comment]
Ah a complete disable. Thanks, good job!
