### ISSUE TITLE
Chart doesnt draw x-axis for numeric types

### ISSUE THREAD

**Issue by puschie286** [Megabit/Blazorise#3714]
**Describe the bug**
Using chart with complex objects ( objects with custom properties ) ignore all numeric x values

**To Reproduce**
1. Copy the Chart ["Complex Data" example](https://blazorise.com/docs/extensions/chart)
2. Change WatcherEvent.Sector from string to int
3. Adjust Sector values in GetLineChartDataset to 0, 1, 2 and 3
4. See all data on the y-axis ( and note that all points have x value of 0 )

( Used v1.0,2 )

**Expected behavior**
Chart is drawn with the correct data

**Screenshots**
![image](https://user-images.githubusercontent.com/2429036/163155893-303ac2eb-7bc8-4535-bf0c-f33305483b51.png)

**Comment by stsrki** [comment]
@puschie286 I have contacted chart.js creators regarding this problem(https://github.com/chartjs/Chart.js/issues/10304), and apparently, the thing is that sector must be a `string` type to make it work.

Also, their workaround with settings the X `scales` options to linear also works.

```
LineChartOptions lineChartOptions = new()
{
    Parsing = new ChartParsing
    {
        XAxisKey = "sector",
        YAxisKey = "count",
    },
    Scales = new ChartScales
    {
        X = new ChartAxis
        {
            Type = "linear"
        }
    }
};
```

Considering it is not a bug I will make a note in the documentation for future references.

**Comment by puschie286** [comment]
@stsrki great, would not have thought that this is also the case in the js version - big thanks for forwarding the question / problem to the chart project :)

**Comment by stsrki** [comment]
I will leave it open until the docs is updated.
