### ISSUE TITLE
Prevent on enter key pressed submit form on autocomplete freetyping multiple input

### ISSUE THREAD

**Issue by benny-adiwijaya** [Megabit/Blazorise#3717]
Hi, I am using autocomplete freetyping with multiple input, when user input new value by pressing enter, its also submit the form. Is there a way to avoid submit form on enter key pressed in autocomplete freetyping?

**Comment by stsrki** [comment]
Does it only behave like that when the focus is inside of the autocomplete? Without any code to reproduce it I can only tell you to add the following on a Button that is used for form submission.

`<Button Color="Color.Primary" Type="ButtonType.Submit" PreventDefaultOnSubmit>Submit</Button>`

**Comment by benny-adiwijaya** [comment]
It happen when the focus is inside autocomplete. I already found the solution by adding onkeypress="return event.keyCode!=13" on autocomplete
