### ISSUE TITLE
Notification Service documentation issue

### ISSUE THREAD

**Issue by ilcsikbalazs** [Megabit/Blazorise#3718]
Hi. 

I've found that the documentation regarding the Notification Service is missing some installation steps.
https://blazorise.com/docs/services/notification/

To use the service, its prerequisite is installing the Snackbar component and its css!

I'm suggesting to include this in the documentation, because I was troubleshooting for about 1 hour, before finding the solution in the source code.

Thank you, take care!

**Comment by stsrki** [comment]
At first, I was confused as there was `Install-Package Blazorise.Components` stated in the docs. But then I figured you meant to include the namespace for `Snackbar`. Yeah, that makes sense, and you're right it should be mentioned. Thanks for the hint.
