### ISSUE TITLE
Drag and drop reordering inside a list

### ISSUE THREAD

**Issue by ivancavlek** [Megabit/Blazorise#3733]
Drag and drop component is great!
But, we can't reorder the items inside a DropZone and it'd be great if we could have a list where we could reorder the items within a list and not just between DroZones, something like this => https://codepad.co/snippet/sortable-list-with-drag-and-drop
In order to distinguish it from similar components it should emit a position inside a list on draggable event.

**Comment by stsrki** [comment]
It's a good feature to have. We will definitely add it.

**Comment by Jinjinov** [comment]
I also need drag & drop with reordering :)

I might look into this, if I have the time:
https://stackoverflow.com/questions/59302823/blazor-re-ordering-a-list-with-drag-and-drop
https://blazorfiddle.com/s/8jurefka
https://github.com/tesar-tech/DragAndDropList

https://github.com/Postlagerkarte/blazor-dragdrop

I would also need:
- drag & drop between two `DropContainer`
- drag & drop working with `TreeView`

Just like drag & drop in Windows File Explorer :)
I will create separate Feature request issues for this, when I have the time to look into this.

**Comment by njannink** [comment]
We also need this sortable list. Would be great if this could be added.

**Comment by stsrki** [comment]
I guess I should start working on it soon :)
