### ISSUE TITLE
What's the usage of ChartAxisTimeDisplayFormat

### ISSUE THREAD

**Issue by carlblanchard** [Megabit/Blazorise#3736]
**Describe the bug**
I am trying to format DateTime property to display just the date only not the time. When setting ChartScales using ChartAxisTimeDisplayFormat I can only reference properties called Day, Month etc. I am thinking these should be enums? If I am wrong can you show me the usage of these properties as I can't work it out? 

The chartjs docs say set unit to either day, hour week etc. so shouldn't the DisplayFormat just point to a ChartAxisTimeDisplayFormat enum with all the values?
https://www.chartjs.org/docs/latest/axes/cartesian/time.html

```C#

Scales = new ChartScales
            {
                X = new ChartAxis
                {
                     Time = new ChartAxisTime
                     {
                          DisplayFormat = new ChartAxisTimeDisplayFormat
                          {
                              Day = "day"
                          }
                     }
                }
            }

**Comment by Kog008** [comment]
The time unit defines the most smallest desired unit to be shown at the corresponding axis. Its DisplayFormat points to a pattern, that is used for displaying the unit. But giving a pattern like "YYYY-MM-DD" seems not working properly. Respectively, I don't know how to use it properly. ^^

In my opintion your enum is better suited to the time.unit property.

**Comment by carlblanchard** [comment]
I've updated the library to the latest version, still can't work out how to format just the date (without the time) It looks ugly... Any ideas? 

![image](https://github.com/Megabit/Blazorise/assets/18427214/a16da75d-a381-4174-87ad-94adb1e07cfc)

**Comment by stsrki** [comment]
Hello, can you try the sample from https://github.com/Megabit/Blazorise/discussions/5554

**Comment by carlblanchard** [comment]
Sorry, @stsrki  I didn't see your previous message, I am a little confused about how you'd implement the sample in the solution I provided.

**Comment by stsrki** [comment]
I made it to work: Here is the right options.

```cs
options.Scales = new ChartScales
{
    X = new ChartAxis
    {
        Display = true,
        Type = "time",
        Time = new ChartAxisTime
        {
            DisplayFormats = new ChartAxisTimeDisplayFormat
            {
                Day = "dd/MM/yyyy" 
            }
        }
    }
};
```

But, there is a problem. `DisplayFormats` is the right property name, not `DisplayFormat`, as in our current version. I will need to fix that.

Until then, as a workaround use `OptionsObject`:

```razor
<Blazorise.Charts.LineChart @ref="LineChart" TItem="ChartDataItem" OptionsObject="@GetLineChartOptions()" />
```

```cs
public object GetLineChartOptions()
{
    return new
    {
        Parsing = new
        {
            XAxisKey = nameof(ChartDataItem.Date).ToLower(),
            YAxisKey = nameof(ChartDataItem.Count).ToLower(),
        },
        Scales = new
        {
            X = new
            {
                Display = true,
                Type = "time",
                Time = new
                {
                    DisplayFormats = new
                    {
                        Day = "dd/MM/yyyy"
                    }
                }
            }
        }
    };
}
```

**Comment by carlblanchard** [comment]
I've tried the workaround and updated Nuget to 1.6.1 get a not-implemented exception being thrown? I have updated the repo https://github.com/carlblanchard/blazoriseissues Click on the Problem 3 link. So you can see  

![image](https://github.com/user-attachments/assets/d140d054-780e-4fb1-8d2e-39c033eaae91)
