### ISSUE TITLE
FileEdit does not reset when closing/opening a modal

### ISSUE THREAD

**Issue by sturlath** [Megabit/Blazorise#3740]
Maybe this is just supposed to work like this but when I read "By default after each file upload has finished, file input will automatically reset to it’s initial state." **I thought that closing a modal would do a reset when it when "out of scope"**... a feature? 🧐

But if I open the following code in a modal, select an image and close the modal, the image name is not reset when I reopen the modal.

```xml
<FileEdit Filter="image/jpeg, image/jpg, image/gif"  Changed="@OnImageChanged" Multiple="false">
    <Feedback>
        <ValidationError />
    </Feedback>
</FileEdit>
```

This here fixes it (just like the docs propose)

```xml
<FileEdit @ref="@fileEdit" AutoReset="false" Filter="image/jpeg, image/jpg, image/gif"  Changed="@OnImageChanged" Multiple="false">
    <Feedback>
        <ValidationError />
    </Feedback>
</FileEdit>
```

and then on modal closing
```csharp
await fileEdit.Reset().AsTask();
```

**Comment by stsrki** [comment]
Modal is basically always present on the page. It is just hidden with the simple `display:none;`. That's why you need to manually update your input fields before showing them.

`await fileEdit.Reset().AsTask();` is a good approach.

**Comment by sturlath** [comment]
Yes I thought so (after I had written most of the ticket). Thought I´d still post it for somebody else´s future benefit.

Now closing this. Thanks

**Comment by stsrki** [comment]
> Thought I´d still post it for somebody else´s future benefit.

And this is what everyone should do. Thank you!
