### ISSUE TITLE
NumericPicker does not show keyboard with decimal on iOS

### ISSUE THREAD

**Issue by mtbayley** [Megabit/Blazorise#3749]
NumericPicker does not render a keyboard with a decimal point on iOS devices. 

![image](https://user-images.githubusercontent.com/34929316/165354877-c8b221e1-637b-435c-86f0-e180dac473a5.png)

[According to this article](https://css-tricks.com/everything-you-ever-wanted-to-know-about-inputmode), inputtype=decimal may be the correct option.

**Comment by mtbayley** [comment]
Found #3735, which would fix the problem

**Comment by stsrki** [comment]
Should we close the ticket or do you want to leave it open until the PR is merged?

**Comment by mtbayley** [comment]
We can close. Not a big deal. I'm sure it will make it into a release soon 👍
