### ISSUE TITLE
Modal still flicker in 1.0.4

### ISSUE THREAD

**Issue by rwecho** [Megabit/Blazorise#3753]
Just show then hide the modal. it will flicker.

[here](https://github.com/rwecho/BlazoriseModalFlickerDemo.git) is a reproduction

![Animation](https://user-images.githubusercontent.com/8048753/165969078-d62f4e95-2fae-436d-8ec0-7c83b9ee820d.gif)

thanks.

**Comment by stsrki** [comment]
You need to `await` modal Show and Hide methods. Can you modify and try again?

**Comment by rwecho** [comment]
Yes, I missed the "await".
Thanks. It works
