### ISSUE TITLE
DataGrid.DetailRowTrigger crach after call async method

### ISSUE THREAD

**Issue by Lasoty** [Megabit/Blazorise#3759]
When the async method is called from the DetailRowTrigger delegate, an error is returned:
`crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot wait on monitors on this runtime.
System.PlatformNotSupportedException: Cannot wait on monitors on this runtime.`

**To Reproduce**
1. Added method to delegate: `DetailRowTrigger="@((e) => OnReceivedRowReaded(e.Item))"`
2. On this method I called my API: `var result = httpClient.GetFromJsonAsync<Result>($"{MessagesApi.MarkAsRead}/{messageId}").Result;`
3. Method crashed.

**Comment by stsrki** [comment]
The `DetailRowTrigger` is a sync method that should be handled as soon as possible. You could try with `.GetAwaiter().GetResult()` instead of `.Result` but in any case, it's not something I would encourage.
