### ISSUE TITLE
Reusable RenderFragment

### ISSUE THREAD

**Issue by gkochera** [Megabit/Blazorise#3760]
I'm not sure, this might be slightly related to #1926 but I *think* my use-case is different.

Long story short: Trying to avoid repeating the following code across multiple components in my Blazor project.
```C#
<SortDirectionTemplate>
    @if(SortDirectionContext == SortDirection.Default)
    {
        <Icon Margin="Margin.Is2.FromStart" Name="@IconName.Sort" />
    } 
    else if (SortDirectionContext == SortDirection.Ascending)
    {
        <Icon Margin="Margin.Is2.FromStart" Name="@IconName.SortUp" />
    }
    else if (SortDirectionContext == SortDirection.Descending)
    {
        <Icon Margin = "Margin.Is2.FromStart" Name="@IconName.SortDown" />
    }
</SortDirectionTemplate>
```

I currently have to do this for each column in each DataGrid and as you can imagine, this duplicates the code a ton! Not DRY. 

So I endeavored to simplify and arrived at this:

```C#
<DataGrid ...>
    <DataGridColumns ...>
        <DataGridColumn ...>
            @*Use as needed throughout the codebase in each Razor page*@
            <SortDirectionTemplate>@GetSortDirectionIcon(context)</SortDirectionTemplate> 
        </DataGridColumn>
    </DataGridColumns>
</DataGrid>

@code {
    private RenderFragment GetSortDirectionIcon(SortDirection _sortDirection)
    {
        switch (_sortDirection)
        {
            case SortDirection.Default:
                return @<Icon Margin="Margin.Is2.FromStart" Name="@IconName.Sort" />;

            case SortDirection.Ascending:
                return @<Icon Margin="Margin.Is2.FromStart" Name="@IconName.SortUp" />;

            default:
                return @<Icon Margin="Margin.Is2.FromStart" Name="@IconName.SortDown" />;
        }
    }
}
```

This seems better and I could likely just pull that function into its own static method... but... the syntax `@<Icon Margin="Margin.Is2.FromStart" Name="@IconName.SortUp" />;` isn't valid in a standalone C# file which means I seemingly need to repeat the function part in each Razor component where I use this, or maybe I'm missing something there.

<img width="721" alt="image" src="https://user-images.githubusercontent.com/54916850/166584365-f3a9366e-9a9e-44b1-b7fb-4201f43a6c4c.png">

Ideally, I'd like to place the `SortDirectionTemplate` RenderFragment in its own component, and then just reuse that customized RenderFragment throughout my project as needed. Has anyone done this, if so, how did you go about doing it?

**Comment by Jimmys20** [comment]
Hello, just a suggestion that might help you. You can create a razor component called e.g. `SortDirectionIcon.razor`

```
<Icon Margin="Margin.Is2.FromStart" Name="@GetIconName()" />

@code {
  [Parameter]
  public SortDirection Direction { get; set; }

  private IconName GetIconName()
  {
    switch (Direction)
    {
      case SortDirection.Default:
        return IconName.Sort;

      case SortDirection.Ascending:
        return IconName.SortUp;

      case SortDirection.Descending:
        return IconName.SortDown;

      default:
        throw new Exception("Invalid SortDirection");
    }
  }
}
```

And then simply use it wherever needed like this:
```
<SortDirectionTemplate>
  <SortDirectionIcon Direction="@context" />
</SortDirectionTemplate>
```

**Comment by gkochera** [comment]
> Hello, just a suggestion that might help you. You can create a razor component called e.g. `SortDirectionIcon.razor`
> 
> ```
> <Icon Margin="Margin.Is2.FromStart" Name="@GetIconName()" />
> 
> @code {
>   [Parameter]
>   public SortDirection Direction { get; set; }
> 
>   private IconName GetIconName()
>   {
>     switch (Direction)
>     {
>       case SortDirection.Default:
>         return IconName.Sort;
> 
>       case SortDirection.Ascending:
>         return IconName.SortUp;
> 
>       case SortDirection.Descending:
>         return IconName.SortDown;
> 
>       default:
>         throw new Exception("Invalid SortDirection");
>     }
>   }
> }
> ```
> 
> And then simply use it wherever needed like this:
> 
> ```
> <SortDirectionTemplate>
>   <SortDirectionIcon Direction="@context" />
> </SortDirectionTemplate>
> ```

This works pretty good. I can get the bulk into a single component now and reuse it across my project. Thank you @Jimmys20 for the suggestion.
