### ISSUE TITLE
Microsoft.JSInterop.JSException: 'Cannot read properties of undefined (reading 'canvas')

### ISSUE THREAD

**Issue by thomaspb88** [Megabit/Blazorise#3761]
Hello,

I'm trying to update a line chart after it has been rendered. When I attempt to interact (clear, update etc) with the line chart I'm experiencing the following exception:

`Microsoft.JSInterop.JSException: 'Cannot read properties of undefined (reading 'canvas')
TypeError: Cannot read properties of undefined (reading 'canvas')
    at https://localhost:44310/_content/Blazorise.Charts/blazorise.charts.js:181:32
    at Object.Q [as each] (https://localhost:44310/Chart.js/chart.min.js:13:8100)
    at Object.getChart (https://localhost:44310/_content/Blazorise.Charts/blazorise.charts.js:180:23)
    at Object.clear (https://localhost:44310/_content/Blazorise.Charts/blazorise.charts.js:73:46)
    at https://localhost:44310/_framework/blazor.server.js:8:35886
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:44310/_framework/blazor.server.js:8:35854)
    at https://localhost:44310/_framework/blazor.server.js:1:20247
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:44310/_framework/blazor.server.js:1:20217)'
`

My Component Code

`@page "/sensordata"
@using System.Text.Json
@using System.Text.Json.Serialization;
@using HomeHubApplication.Data;
@using Blazorise.DataGrid
@using Blazorise.Charts 

@inject IEnvironmentDataService DataService

<h3>Sensor Data</h3>

<div style="width:500px;">
    <Tabs SelectedTab="table" >
        <Items>
            <Tab Name="table">Table</Tab>
            <Tab Name="graph">Graph</Tab>
        </Items>
    <Content>
        <TabPanel Name="graph">
            <LineChart @ref="lineChart" TItem="double"></LineChart>
        </TabPanel>
        <TabPanel Name="table">
            <DataGrid TItem="EnvironmentData" Data="@environmentData" Sortable="true" Editable="true" ShowPager="true" PageSize="5">
                <DataGridColumn TItem="EnvironmentData" Field="@nameof(EnvironmentData.Key)" Caption="Key" Editable="true"></DataGridColumn>
                <DataGridColumn TItem="EnvironmentData" Field="@nameof(EnvironmentData.Temperature)" Caption="Temperature" Editable="true"></DataGridColumn>
                <DataGridColumn TItem="EnvironmentData" Field="@nameof(EnvironmentData.Humidity)" Caption="Humidity" Editable="true"></DataGridColumn>
                <DataGridColumn TItem="EnvironmentData" Field="@nameof(EnvironmentData.Location)" Caption="Location" Editable="true"></DataGridColumn>
            </DataGrid>
        </TabPanel>
    </Content>
    </Tabs>
</div>

@code {
    LineChart<double> lineChart;

    LineChartDataset<double> temperatureChartData;
    LineChartDataset<double> humidtyChartData;
    List<EnvironmentData> environmentData;

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (temperatureChartData == null | humidtyChartData == null)
        {
            IEnumerable<EnvironmentData> data = null;
            data = await DataService.GetAll();

            temperatureChartData = new LineChartDataset<double>
            {
                Label = "temperature",
                Data = data.Select(d => d.Temperature).ToList(),
                BackgroundColor = backgroundColors,
                BorderColor = borderColors,
                Fill = true,
                PointRadius = 3,
                CubicInterpolationMode = "monotone"
            };

            humidtyChartData = new LineChartDataset<double>
            {
                Label = "humidity",
                Data = data.Select(d => d.Humidity).ToList(),
                BackgroundColor = backgroundColors[1],
                BorderColor = borderColors,
                Fill = true,
                PointRadius = 3,
                CubicInterpolationMode = "monotone"
            };

            environmentData = data as List<EnvironmentData>;
        }

        if (firstRender)
        {
            await HandleRedraw();
        }
    }

    private async Task HandleRedraw()
    {
        await lineChart.Clear();
        await lineChart.AddLabelsDatasetsAndUpdate(new string[] { "1", "2", "3", "4", "5", "6" }, temperatureChartData);
        await lineChart.AddDatasetsAndUpdate(humidtyChartData);
    }

    List<string> backgroundColors = new List<string> { ChartColor.FromRgba(255, 99, 132, 0.2f), ChartColor.FromRgba(54, 162, 235, 0.2f), ChartColor.FromRgba(255, 206, 86, 0.2f), ChartColor.FromRgba(75, 192, 192, 0.2f), ChartColor.FromRgba(153, 102, 255, 0.2f), ChartColor.FromRgba(255, 159, 64, 0.2f) };
    List<string> borderColors = new List<string> { ChartColor.FromRgba(255, 99, 132, 1f), ChartColor.FromRgba(54, 162, 235, 1f), ChartColor.FromRgba(255, 206, 86, 1f), ChartColor.FromRgba(75, 192, 192, 1f), ChartColor.FromRgba(153, 102, 255, 1f), ChartColor.FromRgba(255, 159, 64, 1f) };
`

**Comment by stsrki** [comment]
What version of Blazorise do you use?

The `blazorise.charts.js` doesn't exist for some time now, and you can safely remove it from the `_Host.cshtml` page.

**Comment by thomaspb88** [comment]
@stsrki I'm currently using 0.9.2.5 as I'm using ASP.NET Core 3.1.
