### ISSUE TITLE
Possible virus on the demo Blazorise Site

### ISSUE THREAD

**Issue by well0549** [Megabit/Blazorise#3764]
When i try to load the site i get a warning from bitdefender !

We hebben deze gevaarlijke pagina voor uw bescherming geblokkeerd:
https://bootstrap5demo.blazorise.com/_framework/System.ComponentModel.Primitives.dll
**Naam bedreiging: Trojan.GenericKDZ.84551**
Gevaarlijke pagina's proberen software te installeren die schadelijk kan zijn voor uw apparaat, persoonlijke gegevens kan verzamelen en zonder uw toestemming handelingen kan stellen.

**Comment by David-Moreira** [comment]
Hello @well0549 
Under _framework, should be the .NET libs, and my guess is that it is a false positive. can you test running a new WebAssembly project locally, won't your anti virus complain all the same?

**Comment by stsrki** [comment]
Maybe there is a rule in your virus app to _ignore_ localhost files?

**Comment by David-Moreira** [comment]
> Maybe there is a rule in your virus app to _ignore_ localhost files?

Why do you say this? He didnt say he tested it on localhost did he? I was asking him to, just to see if it happens, but yes, it's probably that it could ignore localhost files.

**Comment by stsrki** [comment]
> > Maybe there is a rule in your virus app to _ignore_ localhost files?
> 
> Why do you say this? He didnt say he tested it on localhost did he? I was asking him to, just to see if it happens, but yes, it's probably that it could ignore localhost files.

The message for meant for @well0549 :)

**Comment by well0549** [comment]
Sorry i was away on holiday for a couple of days. 

I have published the app to a local iis no warnings from the virus scanner. when i debug in visual studo no wanrnings either.
I have no exceptions listed in BitDefender. (only two folders but my dev or iis folder are not whitelisted.)

But when i try the site now i don't get any warnings anymore.

**Comment by stsrki** [comment]
I found this article and it might help someone on the future https://jinalkumarpatel.hashnode.dev/blazor-webassembly-and-firewall
