### ISSUE TITLE
Opening Modal clears the changes

### ISSUE THREAD

**Issue by De-Bill** [Megabit/Blazorise#3766]
Hello! As shown in the video below, after opening modal comments that were added to "problems" (in component ProblemCard) disappear, however this changes are saved to database

https://user-images.githubusercontent.com/79377488/167027249-2e97f411-d19f-4aed-91b6-48024a2efe43.mp4

Code of this page (without some unimportant things):
```csharp
@page "/pages"

@inject HttpClient HttpClient

<h3>
    Problems
    <Button Size="Size.ExtraSmall" Color="Color.Primary" Clicked="@ShowModal">
        <Icon Name="Blazorise.Icons.FontAwesome.FontAwesomeIcons.Plus"/>
    </Button>
</h3>

@if (_problems != null)
{
    <Div Class="card-columns">
        @foreach (var problem in _problems)
        {
            <ProblemCard Problem="problem"/>
        }
    </Div>
}

<Modal @ref="modalRef">
    <ModalContent>
    </ModalContent>
</Modal>

@code {
    private List<ProblemViewModel>? _problems;
    private List<EmployeeViewModel>? _employees;

    private Modal modalRef;

    private Task ShowModal()
    {
        return modalRef.Show();
    }

    private Task HideModal()
    {
        return modalRef.Hide();
    }

    protected override async Task OnInitializedAsync()
    {
        _problems = await HttpClient.GetFromJsonAsync<List<ProblemViewModel>>("api/problem/");
        _employees = await HttpClient.GetFromJsonAsync<List<EmployeeViewModel>>("api/employee");
        _problems = _problems.OrderBy(problem => problem.CreationTime).ToList();
    }
}
```
Thanks!

**Comment by stsrki** [comment]
It's hard to tell what might be wrong without full code to reproduce. Your pasted code is only partial.

Check what happens with `@if (_problems != null)`, especially `_problems` variable. Do you change it between clicks?

**Comment by De-Bill** [comment]
> Check what happens with `@if (_problems != null)`, especially `_problems` variable. Do you change it between clicks?

Thanks:) That helped me to find the problem.
The trouble was caused by not updating  record in `_problems` that was updated in component `ProblemCard`. That's why after opening the modal, rerendering occurred with `_problems` containing outdated data
