### ISSUE TITLE
Minimum length for filtering in Datagrid

### ISSUE THREAD

**Issue by zawarq** [Megabit/Blazorise#3774]
Hi

I have a datagrid configured to load data from the server. I would like the user to enter a string that is at least length n (where n should be customizable), before the OnFilterChanged event (implemented in Datagrid.razor.cs) triggers a reload.

Alternatively, or in addition, the filter(s) should be configurable so as to be applied only upon pressing the search button.

I am hoping that the latter is already doable but couldn't find an example.

Thanks!
Zawar

**Comment by David-Moreira** [comment]
Hello,
Please take a look at the custom filter examples in our docs.
https://blazorise.com/docs/extensions/datagrid/features

There might be a few ways to go about this, these come to mind:
1. Use the `CustomFilter` function and check for > minLength and apply the filter, you can basically just do whatever logic you want.
2. Make use of `context.TriggerFilterChange` to trigger the filter change whenever you want.

Let us know if this helps.

**Comment by zawarq** [comment]
Hi David.

Thanks for the quick feedback! Both of the approaches you suggest show potential. Let me try these out and get back to you.

Regards
Zawar

**Comment by zawarq** [comment]
Hello again

So I went with the TriggerFilterChange suggestion, and have the following markup and code (chunks removed for simplicity):

`DataGrid TItem="Country"
          Data="@countries"
          ...>
    ...
    <DataGridColumn Field="@nameof(Country.Name)" Caption="Name" Editable>
        <FilterTemplate>
            <Blazorise.TextEdit 
                Text="@((string)context.SearchValue)"
                TextChanged="@OnFilterChange">
            </Blazorise.TextEdit>
        </FilterTemplate>
    </DataGridColumn>
</DataGrid>

@code{
...
private void OnFilterChange(string value)
    {
        if (value.ToString().Length > 2)
        {
            return; //how do I invoke context.TriggerFilterChange here?
        }
    }
}`

Ideally if the if condition is met, I'd like to call `context.TriggerFilterChange(value);` . But I don't have access to the FilterContext object inside OnFilterChange.

Thanks in advance!
Zawar

**Comment by David-Moreira** [comment]
So 
```
<Blazorise.TextEdit
Text="@((string)context.SearchValue)"
TextChanged="@OnFilterChange">
</Blazorise.TextEdit>
```
Should be within a column right? You can make use of C# closures. 
Set up an anonymous method and pass in the additional variable, like so:

```
<Blazorise.TextEdit
Text="@((string)context.SearchValue)"
TextChanged="@((value) => OnFilterChange(value, context))">
</Blazorise.TextEdit>
```

Just update your `OnFilterChange` method to reflect the changes and try it, Let us know how it goes. :)

**Comment by zawarq** [comment]
Hi David!

Thank you for pointing out the use of the anonymous method. The problem here is that if I don't call TriggerFilterChange, the filter text gets reset back to empty string, so I can never type anything. If I try to avoid that by using a custom filter then I lose access to the context.

I solved this doing some state management i.e. get a snapshot of all inputs that determine what to display in the grid such as page, page size, sorting, current filter value etc. This allows me to compare the current state with the previously recorded state inside the OnReadData method, and trigger a server-side call only if my filter meets the length criteria.

I hope it helps someone, and wanted you to know that I solved my problem but not based on your recommendations, but your input certainly helped!

Thanks
Zawar

**Comment by stsrki** [comment]
In `OnFilterChange`, aid you assign the `context.SearchValue = newValue;`? I think that might be the reason for resetting the input.

**Comment by zawarq** [comment]
> In `OnFilterChange`, did you assign the `context.SearchValue = newValue;`? I think that might be the reason for resetting the input.

No I didn't. The field gets reset to empty if you don't call TriggerFilterChange.

**Comment by David-Moreira** [comment]
> > In `OnFilterChange`, did you assign the `context.SearchValue = newValue;`? I think that might be the reason for resetting the input.
> 
> No I didn't. The field gets reset to empty if you don't call TriggerFilterChange.

So you didn't try to do `context.SearchValue = newValue;` before `TriggerFilterChange`? You should not need to do all that state management, but glad you got it working eitherway.

**Comment by zawarq** [comment]
Hi David

No I didn't try it. But I hope this answer helps someone else :).
