### ISSUE TITLE
DataGrid DataGridMultiSelectColumn doesn't update CheckBox (Bootstrap 5)

### ISSUE THREAD

**Issue by massimotomasi** [Megabit/Blazorise#3780]
Using DataGridMultiSelectColumn with Bootstrap 5 i found that if i select the row with the check box it isn't updated accordingly. Otherwise, if i select the row pressing it everything works as expected

**To Reproduce**

Go to https://bootstrap5demo.blazorise.com/tests/datagrid/selection/multiple and try to select the row using the checkbox. The row is selected but the CheckBox is not checked

**Expected behavior**
Once the DataGridMultiSelectColumn is selected the CheckBox should be selected

**Screenshots**
![image](https://user-images.githubusercontent.com/69517475/167593238-e60aac1e-0c00-44ff-b631-86b094ef0a58.png)

**Comment by David-Moreira** [comment]
I thinj we've had this reported and fixed already. @stsrki are we running latest version on bootstrap 5 demo?

**Comment by stsrki** [comment]
I think we might be still on an older demo. I will now go and publish a new version.

**Comment by massimotomasi** [comment]
@David-Moreira , @stsrki thx for the help, now the demo is ok
