### ISSUE TITLE
Tabs displayed when set not to be displayed

### ISSUE THREAD

**Issue by ivancavlek** [Megabit/Blazorise#3781]
When _Tabs_ are set to not be displayed with option:

`<Tabs Display="Display.None.If(true)">`

they are still being displayed (missing CSS class _d-none_).

Blazorise Version: 1.0.4

**Comment by stsrki** [comment]
I have tried it and it works as expected

![image](https://user-images.githubusercontent.com/900302/167607177-c20cd53c-9263-4f9e-bb57-b3663439652e.png)

**Comment by ivancavlek** [comment]
You are right. It is there. Mea culpa 😋.
But, the _Content_ of the _Tabs_ is still displayed (everything under CSS class _tab-content_). How can I hide the tabs and its content?

**Comment by David-Moreira** [comment]
Actually what you end up hiding is the tabs header:
![image](https://user-images.githubusercontent.com/22283161/168452382-5f2f3851-f002-4033-85e6-c384eb9e6319.png)

Not sure if we should apply all styles to both the ul responsible for the header and the div responsible for the tabs content, but that seems that it could also have weirds or unpexcted behaviours with certain styling, what do you think @stsrki ?

**Comment by stsrki** [comment]
You can do it if you use `TabsContent` along with `Tabs` component. In that case you will not need the `Content` template.

Fast example:

```cshtml
<Tabs SelectedTab="@selectedTab" SelectedTabChanged="@OnSelectedTabChanged"
      Display="Display.None.If(true)">
    <Items>
        <Tab Name="home">Home</Tab>
        <Tab Name="profile">Profile</Tab>
        <Tab Name="messages">Messages</Tab>
        <Tab Name="settings">Settings</Tab>
    </Items>
</Tabs>
<TabsContent @bind-SelectedPanel="@selectedTab" Class="some-class">
    <TabPanel Name="home">
        Content for home.
    </TabPanel>
    <TabPanel Name="profile">
        Vidljiv sam.
    </TabPanel>
    <TabPanel Name="messages">
        Content for messages.
    </TabPanel>
    <TabPanel Name="settings">
        Content for settings.
    </TabPanel>
</TabsContent>

@code{
    string selectedTab = "profile";

    private Task OnSelectedTabChanged( string name )
    {
        selectedTab = name;

        return Task.CompletedTask;
    }
}
```

**Comment by ivancavlek** [comment]
@stsrki, works as intended. Thanks 😊!
