### ISSUE TITLE
Match highlighting for Autocomplete component

### ISSUE THREAD

**Issue by oaldrian** [Megabit/Blazorise#3791]
When using an `Autocomplete `component there should be the possibility to enable match highlighting for Autocomplete items.
When a search string is entered, and matches are shown, the matching parts should be highlighted when this Attribute is set.

Obviously this would only work if no `<ItemContent>` is given. To mitigate that the current search string could be entered into the `Context `of the `Autocomplete`, then the match highlighting could be done "manually". Still this would be complicated.

**Describe the solution you'd like**
The matching parts of the `Autocomplete `items could be made bold.

### Additional context
![image](https://user-images.githubusercontent.com/44060248/168128701-cc121fa2-e1e7-4697-9098-6fe965389120.png)

Currently there is no possibility to do match highlighting manually via `ItemContent `and matching the search string again to the data, as the `SearchText` is not available afaik, as only `SearchChanged ` is exposed but not `SearchText`. Also one would essentially have to implement the matching again, and then it is also executed twice, only to get the highliting. Not so nice, if even possible.

**Comment by oaldrian** [comment]
... And I wrote a docs enhancement request again ;-) Please add an example of how to use Autocomplete and Highlighter together.

**Comment by stsrki** [comment]
If you clone the repo from master and run the docs you can see it in action :)

**Comment by stsrki** [comment]
@David-Moreira should we do this in 1.2?

**Comment by David-Moreira** [comment]
Seems doable. I hadn't even tried the `Highlighter` component yet. Seems great.
On the surface doesn't even seem hard, good feature.
