### ISSUE TITLE
Add documentation for Blazorise.Animate

### ISSUE THREAD

**Issue by PatrickBig** [Megabit/Blazorise#3793]
Currently there is no documentation for the `Blazorise.Animate` package.

I can dig around in the source to see how it basically works but it would be nice to have it featured in the main docs.

**Comment by David-Moreira** [comment]
So like @stsrki mentioned on discord, it's already done as part of our next release. I had forgotten about it haha.

This is the PR: https://github.com/Megabit/Blazorise/pull/3578

If you want, you can take a look at the docs and see if you'd like us to improve on something. 
I'll be closing this issue. Thank you!
