### ISSUE TITLE
DataGrid with EmptyTemplate in VirtualizeManualReadMode does not load data

### ISSUE THREAD

**Issue by hillin** [Megabit/Blazorise#3795]
If a DataGrid has an `EmptyTemplate`, with `Virtualization` enabled and a `ReadData` callback provided to it, i.e. in `VirtualizeManualReadMode`, and does not have initial data, it will not load data with the `Reload()` method later.

**Comment by David-Moreira** [comment]
Hello,
Can confirm this does happen. It seems like the Virtualize component never gets to render so it does not trigger the `ReadData`. 
`Reload` however should have worked as a workaround, we'll take a look.
