### ISSUE TITLE
ValidationError (message) within Addons not showing up 

### ISSUE THREAD

**Issue by sturlath** [Megabit/Blazorise#3802]
I´m not getting [this](https://github.com/Megabit/Blazorise/issues/2926#issuecomment-920866852) to work @stsrki. The validation text doesn´t show for this code

How can I get the error message to show below the Addons?

```xml
<Column>
    <Field>
        <FieldLabel>@L["StartingDate"]</FieldLabel>
        <Addons>
            <Addon AddonType="AddonType.Body">
                <Validation Validator="@ValidateEventStartingDate">
                    <DatePicker @ref="@startingDatePicker" TValue="DateTime?" InputMode="DateInputMode.Date" Date="@NewStreamEvent.StartingDate" DateChanged="@OnStartingDateChanged" DisplayFormat="dd-MM-Y" Disabled="@DisabledMode">
                    </DatePicker>
                </Validation>
            </Addon>
            <Addon AddonType="AddonType.End">
                <Button Color="Color.Light" Clicked="@(()=>startingDatePicker.ToggleAsync())">
                    <Icon Name="IconName.CalendarDay" />
                </Button>
            </Addon>
            <ValidationError>@L["PleseSelectValidFutureStartingDateForEventDate"]</ValidationError>
        </Addons>
    </Field>
</Column>
```

![image](https://user-images.githubusercontent.com/2386572/168439454-3251f97a-e9d4-43e5-b0bb-b97a2aff3c95.png)

this was my initial codeI was trying to fix, with the error new-lining the end Addon 

```xml
<Column>
    <Field>
        <FieldLabel>@L["StartingDate"]</FieldLabel>
        <Addons>
            <Addon AddonType="AddonType.Body">
                <Validation Validator="@ValidateEventStartingDate">
                    <DatePicker @ref="@startingDatePicker" TValue="DateTime?" InputMode="DateInputMode.Date" Date="@NewStreamEvent.StartingDate" DateChanged="@OnStartingDateChanged" DisplayFormat="dd-MM-Y" Disabled="@DisabledMode">
                        <Feedback>
                            <ValidationError>@L["PleseSelectValidFutureStartingDateForEventDate"]</ValidationError>
                        </Feedback>
                    </DatePicker>
                </Validation>
            </Addon>
            <Addon AddonType="AddonType.End">
                <Button Color="Color.Light" Clicked="@(()=>startingDatePicker.ToggleAsync())">
                    <Icon Name="IconName.CalendarDay" />
                </Button>
            </Addon>
        </Addons>
    </Field>
</Column>
```
![image](https://user-images.githubusercontent.com/2386572/168437715-c5719885-8bfd-4c4a-95bb-06e09469c7ee.png)

Blazorise version 1.0.4

**Comment by StefanOssendorf** [comment]
Hi @sturlath,

the problem is that the `ValidationError` isn't within the `Validation` component. Therefore it does not know what or when to show.
Can you try spanning the `Validation` around the `Addons` component?

**Comment by sturlath** [comment]
Thank you @StefanOssendorf, I really thought I had tried that and every permutation but dropping the feedback and lifting `<ValidaitonError>` within Addons solved it.

So this worked

```xml 
<Validation Validator="@ValidateEventStartingDate">
    <Addons>
        <Addon AddonType="AddonType.Body">
            <DatePicker @ref="@startingDatePicker" TValue="DateTime?" InputMode="DateInputMode.Date" Date="@NewStreamEvent.StartingDate" DateChanged="@OnStartingDateChanged" DisplayFormat="dd-MM-Y" Disabled="@DisabledMode">
            </DatePicker>
        </Addon>
        <Addon AddonType="AddonType.End">
            <Button Color="Color.Light" Clicked="@(()=>startingDatePicker.ToggleAsync())">
                <Icon Name="IconName.CalendarDay" />
            </Button>
        </Addon>
        <ValidationError>@L["PleseSelectValidFutureStartingDateForEventDate"]</ValidationError>
    </Addons>
</Validation>
```

and looks like this
![image](https://user-images.githubusercontent.com/2386572/168461498-11c1f029-ed1e-482e-8c9d-844decff0c56.png)

Closing this

**Comment by sturlath** [comment]
Should I create another ticket @stsrki @David-Moreira ?

**Comment by David-Moreira** [comment]
Nah just leave this one. No idea what mught have changed. We need to take a look.

**Comment by David-Moreira** [comment]
> Should I create another ticket @stsrki @David-Moreira ?

Do you happen to know which version caused this?

**Comment by sturlath** [comment]
I think this was working in 1.1.6 and now I’m on 1.2.2

**Comment by simonkorosec** [comment]
Hi,
The same issue is with the FileEdit component.
On 1.1.7
 
![image](https://github.com/Megabit/Blazorise/assets/29300732/258cf52a-f47c-416f-8c8b-3befb0088a8c)

On 1.2.0
 
![image](https://github.com/Megabit/Blazorise/assets/29300732/7b83da89-7b3b-4d2e-b975-f14db5488df8)

**Comment by sturlath** [comment]
This is still an issue in 1.3.2. At least it does not work for Addons like pointed out [here](https://github.com/Megabit/Blazorise/issues/4740#issuecomment-1722460009). Or is there some special way to do it for Addons?

**Comment by David-Moreira** [comment]
@stsrki

**Comment by David-Moreira** [comment]
@stsrki originally this was reported as a problem (not with FileEdit) that the user fixed it himself but then it came back from a version update.

Does that problem not exist at all in the latest version?
![image](https://github.com/Megabit/Blazorise/assets/22283161/b5095122-0d29-45ab-a441-bc276292e3a9)

**Comment by stsrki** [comment]
It's a separate issue that we already have an open ticket #5121
