### ISSUE TITLE
[Bug] Modal does not show when awaited?

### ISSUE THREAD

**Issue by yggdrasil-tynor** [Megabit/Blazorise#3810]
**Describe the bug**
The Model.Show is async, but Modal's do not show when awaiting the modal. 
The documentation is not very clear about this?

**To Reproduce**
await Modal.Show() - not working
Modal.Show() - working

Should the Modal.Show() not be awaited?

**Comment by stsrki** [comment]
It should be. What is your version of Blazorise?

Also, can you post some code snippet?

**Comment by yggdrasil-tynor** [comment]
@stsrki Version 1.0.4. It used to to work before 1.0.

Codesnippet working:

```csharp  
public async Task Show(StrategyTestParameters parameters, Func<StrategyTestParameters, Task> onTest = null)
    {
        Model = parameters;
        await Validations.ClearAll();
        if (onTest == null)
        {
            OnTest = Close;
        }
        else
        {
            OnTest = async () =>
            {
                if (await Validations.ValidateAll())
                {
                    using (Loading())
                    {
                        await onTest(Model);
                    };
                    Close();
                }
            };
        }

        Modal.Show();
    }
```

Not working when awaiting the modal.

**Comment by stsrki** [comment]
Do you call this `Show` on a button click?

**Comment by yggdrasil-tynor** [comment]
@stsrki yes sir

**Comment by stsrki** [comment]
Hmm, I believe that somehow with the `ExecuteActionAfterCheckDataChanged`, you're breaking Blazor rendering, so the Modal internals is not triggered. Can you try adding `await InvokeAsync(StateHasChanged)` somewhere after the `modal.Show`?

**Comment by yggdrasil-tynor** [comment]
> Hmm, I believe that somehow with the `ExecuteActionAfterCheckDataChanged`, you're breaking Blazor rendering, so the Modal internals is not triggered. Can you try adding `await InvokeAsync(StateHasChanged)` somewhere after the `modal.Show`?

You're completely right. I was synchronously waiting for a task in that method which broke it. Wait() instead of await. Thanks for the quick support :)
