### ISSUE TITLE
Password show button shows only upon initial input

### ISSUE THREAD

**Issue by janseris** [Megabit/Blazorise#3818]
**Describe the bug**
![image](https://user-images.githubusercontent.com/64279914/169489391-c2571198-8c5a-4c77-9652-be6c1ccddbe9.png)

The button to show password shows only when writing first input.
When leaving the input and entering again, it never shows again.
Also, when Model is loaded from property, the button never shows.

Is it possible to hide the password switch feature completely? I have already implemented the feature myself so now it is sometimes duplicated because of the embedded switch behavior.

![image](https://user-images.githubusercontent.com/64279914/169493239-6961f902-79f1-4682-9bcb-3ae0cb0542e1.png)

**To Reproduce**
```
<TextEdit @bind-Role="passwordTextEditRole" @bind-Text=Model.Password>

//custom switch button to show/hide password - created because I didn't know the switch feature was even there
private TextRole passwordTextEditRole { get; set; } = TextRole.Password;

    private bool _showPassword = false;
    private bool ShowPassword
    {
        get => _showPassword;
        set
        {
            if (value == true)
            {
                passwordTextEditRole = TextRole.Text;
            }
            else
            {
                passwordTextEditRole = TextRole.Password;
            }
            _showPassword = value;
        }
    }



```
**Expected behavior**
The button embedded in TextEdit when mode is password should be shown always

**Screenshots**

**Additional context**

**Comment by stsrki** [comment]
I don't recognize these buttons, and I suspect they are added automatically by the browser. Which means we don't have a way to control them.

**Comment by janseris** [comment]
> I don't recognize these buttons, and I suspect they are added automatically by the browser. Which means we don't have a way to control them.

Oh, thanks!
Seems like it must be some kind of MS Edge feature. I found that it might be `-ms-reveal`.
