### ISSUE TITLE
 Message service Chose option

### ISSUE THREAD

**Issue by Mr-Pearce** [Megabit/Blazorise#3819]
**Is your feature request related to a problem? Please describe.**
Currently you have to use a Modal with an an custom List to chose simple actions.

**Describe the solution you'd like**
A function for the MessageService `Chose` where the parameters are 
`message`, 
`title` 
and `items` an array of strings you can chose in the modal.
maybe even `Multiselect`.

The Modal result is then the string(s) you chose (after clicked ok).

**Comment by WolfgangKluge** [comment]
Although I think the OP want's a select box in the "question part" and the MessageService to return the selected text after confirming, I think I need something similar...

I want the user to select between `Yes, save`, `Cancel`, and `No, continue without saving`.
E.g. on the question "Do you want to save the changes you've made?"


So, a way to customize the dialog in various aspects would be great.

**Comment by Mr-Pearce** [comment]
Something like
`var decision = await MessageService.Chose("Please chose one of the following","Attention", new List(){"a","b","c","d"});`
![grafik](https://user-images.githubusercontent.com/13457314/169507193-e1963526-9ce5-439f-8a1f-1444a500fc51.png)
The Header is messed up but you should get the idea.

**Comment by stsrki** [comment]
@WolfgangKluge That is already possible through options:

```cs
async Task ShowConfirmMessage()
{
    if ( await MessageService.Confirm( "Are you sure you want to delete?", "Confirmation", options =>
    {
        options.CancelButtonText = "Go back";
        options.OkButtonText = "Yes, please delete";
    } ) )
    {
        Console.WriteLine( "OK Clicked" );
    }
    else
    {
        Console.WriteLine( "Cancel Clicked" );
    }
}
```

**Comment by stsrki** [comment]
@Mr-Pearce, I don't think we would add that feature. It is just too specific of a use case. Maybe you would be able to do it with our new ModalProvider feature that is currently in the works https://github.com/Megabit/Blazorise/pull/3614

@David-Moreira do you think it will be possible with the new modal provider?

**Comment by Mr-Pearce** [comment]
To Bad.
In Xamarin Android/Ios they are called Actionsheets i think
![grafik](https://user-images.githubusercontent.com/13457314/169508235-612a553f-8548-4f6c-ad69-e93251a0bde2.png)
And are just an easy way for Questions that are more then two options.

**Comment by WolfgangKluge** [comment]
@stsrki No, I need 3 buttons (and therefore a third state beside `true` and `false`).
Or do I miss something?

**Comment by stsrki** [comment]
You're right three or more buttons are not supported.

**Comment by Mr-Pearce** [comment]
@WolfgangKluge 
I just build a `ActionSheet.razor` its not Perfect but it solves my usecase.

```
<Modal @ref="currentModal" Closing="@OnModalClosing">
    <ModalContent Centered Size="ModalSize.Default">
        <ModalHeader TextAlignment="TextAlignment.Center" TextWeight="TextWeight.Bold">
            @Header
            <CloseButton></CloseButton>
        </ModalHeader>
        <ModalBody Padding="Padding.Is0">
            <ListGroup Flush Mode="ListGroupMode.Selectable" SelectedItem="@modalselection" SelectedItemChanged="@OnModalSelection">
                @if (Options != null)
                {
                    @foreach (var item in Options)
                    {
                        <ListGroupItem Name="@item" TextAlignment="TextAlignment.Center">@item</ListGroupItem>
                    }
                }
            </ListGroup>
        </ModalBody>
        <ModalFooter>
            <Button Color="Color.Primary" Block Clicked="(async ()=> await OnModalSelection(null))">@Cancel</Button>
        </ModalFooter>
    </ModalContent>
</Modal>

@code {

    Modal currentModal;
    string modalselection;
    string Header { get; set; }
    string Cancel { get; set; }
    string[] Options { get; set; }
    bool _initialOpen;
    bool _cancelClose;
    TaskCompletionSource<string> taskCompletionSource = new();

    private Task OnModalClosing(ModalClosingEventArgs e)
    {
        e.Cancel = _cancelClose || e.CloseReason != CloseReason.UserClosing;
        return Task.CompletedTask;
    }

    async Task OnModalSelection(string selection)
    {
        modalselection = selection;
        if (!_initialOpen)
        {
            _cancelClose = false;
            await currentModal.Hide();
            taskCompletionSource.SetResult(selection);
        }
    }

    public async Task<string> ChoseAsync(string header, string[] options, string cancelText = "Cancel")
    {
        taskCompletionSource = new();
        Header = header;
        Cancel = cancelText;
        _initialOpen = true;
        Options = options;
        modalselection = null;
        await currentModal.Show();
        _initialOpen = false;
        return await taskCompletionSource.Task;
    }
}

```

just put it in your Razor ui File like
`<ActionSheet @ref=actionSheetRef/>`
And put this in your mouse or whatever event.
           ` var sheetResult = await actionSheetRef.ChoseAsync("Chose", new[] { "a", "b", "b" });
`
