### ISSUE TITLE
Border doesn't use theme color

### ISSUE THREAD

**Issue by daywee** [Megabit/Blazorise#3820]
**Describe the bug**
Border (primary) color is not the same as theme (primary) color.

**To Reproduce**
1. Go to [Borders demo](https://bootstrapdemo.blazorise.com/tests/utilities/borders)
2. Change the theme
3. You can see that border color did not change when `Border.Primary` is used, but color is changed correctly when only bottom border is set `Border.Is1.Primary.OnBottom`.

![image](https://user-images.githubusercontent.com/13921707/169506101-ccc10e1a-7a63-464d-902f-0af205610087.png)

**Expected behavior**
I expect the color to change when `Border.Primary` is used.

**Additional context**
I've tried to make a workaround by applying color for each side one by one
```csharp
Border.Is1.OnTop.Primary.OnEnd.Primary.OnBottom.Primary.OnStart.Primary
```
but it didn't work for me and border was applied only on last side set, in this case `OnStart.Primary`. I'm not sure if this is by design, but I would expect this to add border on each side.

**Comment by stsrki** [comment]
Yes, you're right, it doesn't work, and I can reproduce. Thanks for letting us know.
