### ISSUE TITLE
Optionally locally disable ValidationSuccess

### ISSUE THREAD

**Issue by janseris** [Megabit/Blazorise#3822]
**Is your feature request related to a problem? Please describe.**
I am trying to hide `ValidationSuccess` on a form field (**locally for only some fields!**) in a clean way.
Currently, it can be partially achieved using css hacks but that turns very complicated/impossible when trying to restore default border color and default border shadow etc to simulate that the `is-valid` CSS class which is applied to create the validation effect is actually _not applied_.

**Describe the solution you'd like**
A way to disable `ValidationSuccess` effect on a form field but at the same time preserve `ValidationError` effect and the validation.
Removing/not adding the `ValidationSuccess` element or adding properties to it does not help.

Applying a css class like this can modify the `ValidationSuccess` look.
 However it is hard to _**unset/hide**_ it cleanly this way.
```
/* for Blazorise form validation input fields */
.form-control.is-valid.no-validation-success {
    background-image: none; 
    border-color: original??
}

```

Setting `border-color` to `inherit`/`initial`/`unset` yields different result than the original look (probably the same problem for border shadow)

![image](https://user-images.githubusercontent.com/64279914/169525550-e3b43bc7-2d50-44d3-9a2f-b4053dc12a9a.png)

**Comment by stsrki** [comment]
Did we talk on Discord about this? 😅

The solution is to do

```css
.form-control.is-valid.no-validation-success {
    background-image: none; 
    border-color: var(--b-theme-success, #28a745);
}
```

**Comment by janseris** [comment]
> Did we talk on Discord about this? 😅
> 
> The solution is to do
> 
> ```css
> .form-control.is-valid.no-validation-success {
>     background-image: none; 
>     border-color: var(--b-theme-success, #28a745);
> }
> ```

What about different CSS provider? Blazorise supports [Bootstrap](https://bootstrapdemo.blazorise.com/), [Bulma](https://bulmademo.blazorise.com/), [Material](https://materialdemo.blazorise.com/), or [AntDesign](https://antdesigndemo.blazorise.com/)

**Comment by stsrki** [comment]
For all providers, the CSS variable name is the same `--b-theme-success`. The only difference is that `#28a745`.

**Comment by stsrki** [comment]
You can inspect it like this

![image](https://user-images.githubusercontent.com/900302/169545887-5d71c2e9-17de-4c0a-af1c-89bc27e56a39.png)

**Comment by stsrki** [comment]
Well, usually, the shadow color is automatically done with the theming system. But since you're modifying some parts there are no ways around it than manual CSS.

**Comment by janseris** [comment]
>  there are no ways around it than manual CSS. 
And also another option is if Blazorise supported it out of the box.

**Comment by stsrki** [comment]
It would make little sense because only Bootstrap and Bulma contain an icon on validation inputs. Other providers don't have it. So that feature would be redundant to have.

**Comment by WolfgangKluge** [comment]
A bit late to the party, but you can create a custom ClassProvider (inherit e.g. from [`Bootstrap5ClassProvider`](https://github.com/Megabit/Blazorise/blob/41cba1ea58abdfc26981144eb2bc2e037e26fa36/Source/Blazorise.Bootstrap5/Bootstrap5ClassProvider.cs)) and overwrite [`ToValidationStatus`](https://github.com/Megabit/Blazorise/blob/41cba1ea58abdfc26981144eb2bc2e037e26fa36/Source/Blazorise/Providers/ClassProvider.cs#L1510-L1518) or (more fine-grained) a `*Validation`-member (e.g. [`TextEditValidation`](https://github.com/Megabit/Blazorise/blob/41cba1ea58abdfc26981144eb2bc2e037e26fa36/Source/Blazorise.Bootstrap5/Bootstrap5ClassProvider.cs#L19)) to return `null` on success.

Don't forget to register your custom class provider `services.AddSingleton<IClassProvider, CustomClassProvider>()`.

It's all-or-nothing - but for my needs it was sufficcient.

**Comment by stsrki** [comment]
Closing the ticket.
