### ISSUE TITLE
Question: Is it possible to change the Pager buttons to either side instead of it being pushed to the middle when ButtonRowTemplate are set?

### ISSUE THREAD

**Issue by joost00719** [Megabit/Blazorise#3823]
Currently I have some tables which contain some buttons at the bottom, which are always aligned to the left.
The thing is, if they are not set, the pager buttons are on the left.
This way it is very inconsistent for the user where the pager buttons are.

Is it possible to change the location of these elements? I haven't found one yet.
If there is no way yet, and it is something which can be added, a good implementation could be to add a location to the templates (e.g. left, middle, right)?

![image](https://user-images.githubusercontent.com/21021559/169545799-a2c745d5-d796-4615-b3e3-95bc55a89fca.png)
ps: I am using Blazorise version 0.9.5.7 because I am stuck on vs 2019 due to company policy :S

**Comment by joost00719** [comment]
This is not a feature request, just a question asking whether it is possible or not

**Comment by David-Moreira** [comment]
Hello.
I think it's possible by playing with the css and the flex utilities, but it might not be easy :)

I guess we can make it more configurable or provide some kind of `PagerTemplate` with enough contextual information for the user to build as he wants it.
