### ISSUE TITLE
DataGrid SortChanged Bug?

### ISSUE THREAD

**Issue by ninjanerdbgm** [Megabit/Blazorise#3825]
**Describe the bug**
There appears to be a bug with how `SortChanged` works.  The method is called and the data on the back-end is sorted correctly, however it displays incorrectly on the actual table.  If `SortDirection` is `Default`, the data displays properly.  Something about `SortDirection` overrides the data, I think.

The reason why I put a question mark in the title is because `SortChanged` isn't even mentioned in the documentation, so I'm not sure what the expected behavior of this override is, but I assume it would be to override the default sorting code.

**To Reproduce**
1. Display a DataGrid with data.
2. Create an `OnSorted` method and set `SortChanged` equal to that method.
3. Within the `OnSorted` method, allow the data to be sorted by two variables (`OrderBy`, followed by a `ThenBy`)
4. See that the data is set properly in the back-end
5. The data displays differently to what is contained within the data variable.

**Expected behavior**
The data should be displayed with the custom sorting set in `SortChanged`

**Screenshots**
DataGrid Parameters: 
![DataGrid Parameters](https://user-images.githubusercontent.com/8430568/169577081-c65937f4-38ec-4e93-a308-8a2b2eaf5459.png)   

`OnSorted` example: 
![OnSorted method example](https://user-images.githubusercontent.com/8430568/169577148-52e2a581-3a20-4152-9f9a-02cad4adef45.png)

`OrderPicklistItems` example (it is supposed to display items with `IsArchived == true` at the bottom of the list):
![OrderPicklistItems method example](https://user-images.githubusercontent.com/8430568/169577189-eb8e3d8c-577e-4488-87c1-4da1ff567675.png)

Expected Output (SortDirection is Default here): 
![Expected Output](https://user-images.githubusercontent.com/8430568/169577304-6075b5d1-be0a-46df-9035-ac42861bb950.png)

Actual Output (SortDirection is Ascending):  
![Actual Output](https://user-images.githubusercontent.com/8430568/169577338-4b946898-2238-4948-9b5a-bf80caf3d9d0.png)

**Additional context**
The users have the option to place archived items at the bottom of the list. This works fine with `SortDirection` equal to `Default`, but does *not* work with any other `SortDirection` value.

In my example code above, `PicklistItems` is properly sorted and pushed back to the `DataGrid` when `StateHasChanged()` is called, however something about `SortDirection` overrides the order they're in and displays them in the order seen in the Actual Output screenshot.

**Comment by David-Moreira** [comment]
Hello @ninjanerdbgm 
actually I don't think `SortChanged` was ever designed to mutate the sort state, at least not directly. It's more of an informational event.
You're probably mutating the data, and the grid is sorting it again itself.

You can still mutate it, but you should be using the appropriate `Sort` API to control the `SortFields` and `SortDirection`.

![image](https://user-images.githubusercontent.com/22283161/175808639-4d6a33ad-de07-4a36-b650-fc9e4317a251.png)

Also don't forget about:
![image](https://user-images.githubusercontent.com/22283161/175808734-4da332fd-8c1f-4025-9cd9-c8dd7bd4ccf4.png)

Can you try it, and let us know if that helps you? If you're still having difficulties can I ask you that you provide the repro so it's easier to setup / help?
