### ISSUE TITLE
Access to Subobjects at Datagrid Filter not possible

### ISSUE THREAD

**Issue by samuelhurni** [Megabit/Blazorise#3829]
When I use a Datagrid with a custom Filter I need an access to my models which have relations to other models. When I want to access to a submodel of my model, the building fails with the rendering error:

_Unhandled exception rendering component: Cannot detect the member of DataAcess.Data.ComponentLibraryDTO (Parameter 'Shortcut')
System.ArgumentException: Cannot detect the member of DataAcess.Data.ComponentLibraryDTO (Parameter 'Shortcut')_

Here is my Code for using the Datagrid:
`<DataGrid  TItem="ComponentLibraryDTO"
                        Data="@Components"
                        Filterable
                        Responsive
                        PageSize="100"
                        FixedHeader
                        FixedHeaderDataGridMaxHeight="800px">
            
            <DataGridSelectColumn CustomFilter="@OnGenderCustomFilter" Field="@nameof( ComponentLibraryDTO.ComponentType.Shortcut)" Caption="Typ" Editable>
            <FilterTemplate>
            <Select TValue="string" SelectedValue="@selectedGenderFilter" SelectedValueChanged="@(value => { selectedGenderFilter = value; context.TriggerFilterChange( selectedGenderFilter ); })">
                <SelectItem Value="@("*")">Alle</SelectItem>
                <SelectItem Value="@("M")">.AFU</SelectItem>
                <SelectItem Value="@("F")">.MSU</SelectItem>
                <SelectItem Value="@("D")">.PRS</SelectItem>
            </Select>
            </FilterTemplate>
            </DataGridSelectColumn>
            <DataGridColumn Field="@nameof( ComponentLibraryDTO.NameDE )" Caption="Name" Editable="false"></DataGridColumn>`

Here are my Datamodels which I use:

` public class ComponentLibraryDTO
    {
        [Key]
        public int ComponentLibraryId { get; set; }         // Primary Key Id
        public string NameDE { get; set; }                  // ComponentName German
        [Required]
        public string NameEN { get; set; }                     // ComponentName English
        public double ThirdPartyPrice { get; set; }         // Price, when this component is not sucessfully declared with products
        public string Supplier { get; set; }                // Supplier of this Thirdpartyprice
        public int SafetyArea { get; set; }                 // Safety Area of Component
        public string PlcName { get; set; }                 // Name for the PLC Instance with the configured functionblock
      
        public ComponentTypeDTO ComponentType { get; set; }    // Foregin Key n-1 to Categorie Type of the Component
      
        public FunctionBlockDTO FunctionBlock { get; set; }    // Foregin Key n-1 to the FunctionBlocks Table 

        public EPlanMacroDTO EPlanMacro { get; set; }          // Foregin Key n-1 to the EplanMacro Table

      
        public DepartmentsEffortDTO DepartmentsEffort { get; set; } // Foregin Key 1-1 to the DepartmentsEffort Table

        public virtual ICollection<SubComponentLibraryDTO> SubComponentsLibrary { get; set; } // Relation 1-n to the SubComponentLibrary Table
                            
        public virtual ICollection<ProductLibraryDTO> ProductsLibrary { get; set; }            // Foregin Key n-n to the ProductLibrary Table

        public virtual ICollection<AuthorDTO> Author { get; set; }

    }`

`public class ComponentTypeDTO
    {
        [Key]
        public int TypeId { get; set; }                                          // Primary Key Id
        [Required]
        public string Shortcut { get; set; }                                     // Shortcut of Designation of this Component, example AFU
        [Required]
        public string DescriptionEN { get; set; }                                // Designation for example Automation Feeding Unit
        [Required]
        public string DescriptionDE { get; set; }                                // Designation for example Automatische Zuführeinheit

        public virtual ICollection<ComponentLibraryDTO> ComponentsLibrary { get; set; }     // Relation 1-n to ComponentsLibrary Table

        public virtual ICollection<ComponentProjectDTO> ComponentsProject { get; set; }     // Relation 1-n to ComponentsProject Table
       

    }`

When I change the acces from Component.ComponentType.Shortcut to a field which is direct located in the Type ComponentDTO, then the access is fine.

So did I make a mistake by using this Datagrid configuration or is this a bug?

**Comment by stsrki** [comment]
For nested fields, you need to not use `nameof`.

```
Field="ComponentType.Shortcut"
```

**Comment by samuelhurni** [comment]
ok this works for me Thank you.
