### ISSUE TITLE
EditContext.OnFieldChanged is not fired for Switch component.

### ISSUE THREAD

**Issue by mrakhra** [Megabit/Blazorise#3843]
**Describe the bug**
EditContext.OnFieldChanged is not fired for switch component using Two-Way binding.

**To Reproduce**
                            <Switch @bind-Checked="@editModel.IsAccepted"
                                    Class="edit-input-class"
                                    TValue="bool">Is Accepting Conditions?</Switch>

**Expected behavior**
EditContext.OnFieldChanged should fired for switch when using Two-Way binding. This is related to https://github.com/Megabit/Blazorise/issues/1839 which was fixed earlier. However, Switch is still not firing EditContext.OnFieldChanged.

**Additional context**
At the moment, I've firing this manually using             
editContext.NotifyFieldChanged(new FieldIdentifier(editModel, nameof(editModel.IsAccepted)));

**Comment by mrakhra** [comment]
Hi guys, I've fixed this issue. There was an issue in my project. Hence, I am closing it.

**Comment by stsrki** [comment]
Hi @mrakhra can you tell us what was the problem? It might help someone in the future,

**Comment by victorprocure** [comment]
We were updating another field based on the value from the switch. However, we'd not overriden `InputBase<T>` correctly. We missed the `ValueExpression`. So internally Blazor wasn't treating it the same as other Form fields. Once this was corrected everything worked and updated correctly.

**Comment by stsrki** [comment]
Thanks!
