### ISSUE TITLE
Charts 0.9.5.7 exception in render step

### ISSUE THREAD

**Issue by franzdeco** [Megabit/Blazorise#3847]
Hello,
I am not able to run a simple chart example: an unhandled exception comes from "_content/Blazorise.Charts/charts.js?v=0.9.5.7" when trying to read property "tooltips".

Error from console says "Unhandled exception rendering component: Cannot read properties of undefined (reading 'tooltips')",
and mentioned source file shows:

if (!Chart.defaults.pie.tooltips.callbacks.title) {
    Chart.defaults.pie.tooltips.callbacks.title = _ChartTitleCallbacks;

Any suggestion to resolve the problem?
Thank you in advance

**Comment by stsrki** [comment]
Do you use Blazorise 1.0.x? Can you check your nugets?
