### ISSUE TITLE
Autocomplete - SelectedValueChanged problem

### ISSUE THREAD

**Issue by HansMeiser234** [Megabit/Blazorise#3868]
Hello,

i use Blazorise Components in current version 1.0.4

I uploaded an image to make the problem visible.
https://ibb.co/sKygT6m

It tells the component Parameter SelectedValueChanged is used two or more times. But i use it only once within this autocomplete.
2nd sentence of message is interesting: The component parameter 'SelectedValueChanged' is generated by the '@bind-SelectedValue' directive attribute.
But then how to use it?
In this case i need the selected value to run immediately a sql-query and show results.

Thanks,
Hans

**Comment by stsrki** [comment]
Closing the ticket since @paulosdfigueiredo is the correct answer.

**Comment by HansMeiser234** [comment]
Thank you, that helped.
