### ISSUE TITLE
DragDrop Reorder not possible to move to first position

### ISSUE THREAD

**Issue by njannink** [Megabit/Blazorise#3872]
I'm trying to get the reorderable dragdrop list to work and I run into an issue which is reproducable with the demo project of Blazorise. It's not possible to drop the selected object in the first position / to the top of the list. The workaround for the user is that he will need to drop the item in second position and then move the item in first position below that, but that is kinda confusing for the user.

**Comment by njannink** [comment]
Nvm I found out its my own problem.

**Comment by ThomasHilbertAtCervis** [comment]
@njannink Would you care to explain how you solved it?

**Comment by njannink** [comment]
no idea anymore is almost a year ago
