### ISSUE TITLE
Add Grid SelectedRowNumber property

### ISSUE THREAD

**Issue by fastlink30** [Megabit/Blazorise#3882]
With DataGrid there aren't property that give the number of row selected, so .ScrollToRow(rownumber) is little tricky to understand how to fill, much more simple have property that give this number

int rowNumber = grid.SelectedRowNumber(item)

**Comment by stsrki** [comment]
We could add something like `SelectedRowIndex`. @David-Moreira what do you think?

**Comment by David-Moreira** [comment]
I guess so... As long as it is a calculated property or. Method. Since the collection may change but the selectedrow index changes.
