### ISSUE TITLE
Get others edited cell value in DataGrid

### ISSUE THREAD

**Issue by benny-adiwijaya** [Megabit/Blazorise#3889]
Hi, I need to update other cell after the current cell is changed based current cell and another different cell.
```
ValueChanged="@( v => {
   context.CellValue = v;
   context.UpdateCell( nameof( MyItem.Subtotal), v * context.Item.ForeignAmount);
})"
```

with context.Item.ForeignAmount we get the original value, I need to get edited value from ForeignAmount. Is it possible to get others edited cell value in DataGrid? Thanks

**Comment by stsrki** [comment]
Yes, it is possible. Along with the `UpdateCell` method, you also have the `ReadCell` method.

**Comment by benny-adiwijaya** [comment]
Great, thank you
