### ISSUE TITLE
Blog: how to use complex types with Select component

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#3890]
Explain why we support primitive types only, and how to workaround to use complex types as a value.

**Comment by David-Moreira** [comment]
If I remember correctly there were some quircks with enums also. We can touch on that also.

**Comment by stsrki** [comment]
Wanna grab this one?

**Comment by David-Moreira** [comment]
Yea, sure.

**Comment by stsrki** [comment]
If you're gonna do it, do it on `rel-1.0.0` branch
