### ISSUE TITLE
DataGrid: Include DisplayTemplate for Row level customizations

### ISSUE THREAD

**Issue by RyanTheShaw** [Megabit/Blazorise#3892]
**Is your feature request related to a problem? Please describe.**
I am trying to track changes to the inline column edits to row items, and mark the entire row with some custom css styling to indicate that the row item has been modified. 

I think a common use case would be to make a number of pending changes to the in-memory collection being used within the Grid, and then fire an event to take those pending changes and perhaps write them to long-term storage.

**Describe the solution you'd like**
Ideally, I would like to be able to apply a class value to the generated `<tr class="table-row-selectable">` tag, much like the component when you click on a row and the class `table-primary` is applied. It seems the way to do this for `DataGridColumn` is to use the `DisplayTemplate` for the child content, but there doesn't seem to be that level of customization for the row (or at least there doesn't seem to be based on what I've seen in the docs / found when looking at examples).

### Additional context
Please see below for a visual as to what behavior I'm attempting to achieve.
#### Step one: Load grid with no edits
![image](https://user-images.githubusercontent.com/7875250/173987146-539b9e0e-174a-4a56-8e35-e3dd5b8b9599.png)
#### Step two: Make an edit in grid (notice IsPublished flag flipped on row 3)
![image](https://user-images.githubusercontent.com/7875250/173987455-b9089040-4012-412a-8588-309420842a02.png)
#### Step three: Make additional edit 
![image](https://user-images.githubusercontent.com/7875250/173987583-95320af5-40fe-4a5b-b41c-559cfe4c9b47.png)

### Last thoughts
Is there a way already that is supported by the tool to account for this use case? I know we have functionality for assigning selected via click events, but it doesn't seem right for me to mix that concept in with dirtiness tracking of the in-memory items. I'm curious to hear other's thoughts on what I've shared though.

**Comment by stsrki** [comment]
Thank you for the detailed example. We actually have a way to defining class and style for the row. It is named `RowStyling` and can be used as:

```diff
<DataGrid TItem="Employee"
    Data="inMemoryData"
    ShowPager
    ShowPageSizes
+    RowStyling="@((item, e) => { e.Class = "my-table-row-selectable"; })">
```

**Comment by RyanTheShaw** [comment]
That was exactly what I needed, thank you for your response :)
