### ISSUE TITLE
DataGridRowStyling with FixedHeader not working

### ISSUE THREAD

**Issue by f4n0** [Megabit/Blazorise#3900]
**Describe the bug**
If the Datagrid has the Fixed Heder, the styles will not be applied
This is due to this CSS rule:
![image](https://user-images.githubusercontent.com/36199751/174602101-2932a8cd-3fdc-49a7-9a98-926150abeec5.png)

blazorise.bootstrap.css:1490

**Comment by David-Moreira** [comment]
Can you clarify? What styles are not applied? 
- Are we overriding our own styles incorrectly? 
- Is it your own styles? Maybe you need more specificity.

**Comment by f4n0** [comment]
![image](https://user-images.githubusercontent.com/36199751/174737878-73c114fa-a188-4e2e-8154-81023a22cb67.png)

I'm doing something like that, where BackgroudColor is currently Background.Dark 
If I remove the FixedHeader property, the background colors will be applied correctly
