### ISSUE TITLE
Custom validator as an async function

### ISSUE THREAD

**Issue by tacoWanneeJama** [Megabit/Blazorise#3907]
I am writing a custom validator for a serial number field. I want to check if that serial number is already in de the database in the backend. For that I want to be able to connect to the backend from this validator.
As far as I see the validator in is a Synchronous function, that is not able to do https request (for they are async).

I like to be able to make the validator function as an async function

**Comment by stsrki** [comment]
Just use the `AsyncValidator` instead of the `Validator` parameter.

**Comment by tacoWanneeJama** [comment]
Thanx, I had not discovered this property
