### ISSUE TITLE
Datagrid with many rows & DataGridMultiSelectColumn activated become slow when check pressed

### ISSUE THREAD

**Issue by fastlink30** [Megabit/Blazorise#3908]
when use @bind-SelectedRows selection of checkbox become much slower

an example in the attached example project

[BlazorTestGrid.zip](https://github.com/Megabit/Blazorise/files/8976504/BlazorTestGrid.zip)

**Comment by David-Moreira** [comment]
@fastlink30 by the way, how many rows are "too many"? :D

**Comment by fastlink30** [comment]
on the example is 1000, if you try with 50 is the same, GUI is not reactive how must be
50, 500, 1000, 10000 performance progressively degrades, that's the point
