### ISSUE TITLE
Autocomplete multiple values using comma for input value

### ISSUE THREAD

**Issue by benny-adiwijaya** [Megabit/Blazorise#3910]
Hi, autocomplete in this project is working great. With multiple values we press enter to input value, can we modify input value key to comma key along with enter key?

**Comment by stsrki** [comment]
@David-Moreira ?

**Comment by David-Moreira** [comment]
Hello @benny-adiwijaya,
We're happy that it is working great for you.

I guess we can take it as a feature. 
A `ConfirmKey` parameter with the list of the key codes, that when set overrides our internal "key checker"
![image](https://user-images.githubusercontent.com/22283161/175773445-69be85d4-3249-4277-842b-72d2acd200d9.png)


As for a workaround, if you can't wait for this feature, maybe you can do something "dirty" like listening to the events and when it is a ',' send an 'Enter' instead?
In theory it can work, not sure if it's easy to do, most likelly you need to do it with your own javascript.
