### ISSUE TITLE
Autocomplete freetyping multiple input with similiar values

### ISSUE THREAD

**Issue by benny-adiwijaya** [Megabit/Blazorise#3915]
Hi @David-Moreira, I found it difficult to type new value with similiar data. An example, I want to submit new value "United" whereas there is already data "United Kingdom", when I press Enter Key its automatically set to "United Kingdom" instead of "United". Is there an easy way to input similiar values as stated above?

**Comment by stsrki** [comment]
Isn't that supposed to happen? You're basically searching for a value, and only if it doesn't exist it should be added to a list. I don't see a way around it. Maybe only if you have an empty list to begin with?

**Comment by benny-adiwijaya** [comment]
With Freetyping feature its allows the value to not be on the data source, thats awesome feature. But when user want to add new value whereas there is already data with similiar value like stated above its not easy. sometimes double click outside text box do the job, but sometimes its not work.

**Comment by David-Moreira** [comment]
I'll have to look it up, but we've had a similar report some time ago.
@stsrki I know we disagree here, but it's yet another request about `FreeTyping` allowing a value even if there's already a similar value listed. I think we had tought of a solution, where it would not pre-select the first value, which should solve this.

**Comment by David-Moreira** [comment]
Found it, please refer to #3813

**Comment by stsrki** [comment]
@David-Moreira this is fixed with #3949

**Comment by David-Moreira** [comment]
Right, closing issue. Appreciate it if you try the release 1.1.0 when it's out for this. :)
