### ISSUE TITLE
Docs: generate blog posts from markdown

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#3919]
Investigate to see if we can generate razor pages from `.md` files. We can add new parsers to the `Blazorise.Docs.Compiler` that uses Markdig. Then use it to generate `BlogPageParagraph` for paragraphs,  `BlogPageSubtitle` for `h2`s, `BlogPageSourceBlock` for code blocks, etc.

**Comment by David-Moreira** [comment]
I think Microsoft automates their documentation pages for example. Don't know if the source is md files though.

**Comment by stsrki** [comment]
I've already made some progress today. You can check `rel-1.0.0-seo-markdown` branch. It is still work in progress but it works :)
