### ISSUE TITLE
Component Margin attribute generates wrong classes !

### ISSUE THREAD

**Issue by ALVSoft** [Megabit/Blazorise#3924]
Hello ! Thanks for this amazing component toolkit.
Sorry I could be wrong.
When set the **Margin** attribute of a component like this **`<BarToggler Margin="Margin.IsAuto.FromTop.Is3.FromEnd.IsAuto.FromBottom.Is0.FromStart" />`**, the generated classes are **`class="navbar-toggler mt-auto mb-auto me-3 ms-0"`** instead of **`class="navbar-toggler mr-3 mt-auto mb-auto mr-3 ml-0"`**.

**Note:** **`me-3`** instead of **`mr-3`** and **`ms-0`** instead of **`ml-0`**.

Thank you for your attention.

**Comment by stsrki** [comment]
Those classes are per design and are now the default for Bootstrap 5. You can see them on their documentation https://getbootstrap.com/docs/5.2/utilities/spacing/
