### ISSUE TITLE
Tooltip Multiline not working

### ISSUE THREAD

**Issue by Mr-Pearce** [Megabit/Blazorise#3927]
**Describe the bug**
Setting Multiline on Tooltip will still ignore linebreaks.

**To Reproduce**

1. Create Tooltip Component
2. Add Text and Multiline Property 
3. \r\n will be ignored

**Expected behavior**
Linebreaks should be working.

Also please provide a sample code or point us to a minimalistic GitHub repo

**Screenshots**

**Additional context**
Blazorise 1.0.5

**Comment by stsrki** [comment]
We don't support `\r\n` as line breaks. Remember that tooltip will be rendered in HTML in an element attribute. Which is handled by the browser in the end.

You can try adding `<br />` instead. Tooltip supports simple HTML as a content.

**Comment by Mr-Pearce** [comment]
Oh... Thanks <br> works fine.

Is there a way change the tooltip bubble with?

I Tried putting it in a <div style="width: 400 px">content</div> but that just cuts the text.
![grafik](https://user-images.githubusercontent.com/13457314/176629586-1e99f33e-300c-4eb4-857c-378252eab50b.png)

**Comment by stsrki** [comment]
Cool. Closing now :)
