### ISSUE TITLE
Toolbar with only a preview button can't toggle back

### ISSUE THREAD

**Issue by marcvannieuwenhuijzen** [Megabit/Blazorise#3942]
I created a Toolbar with only the preview button.
The toolbar gets the class `disabled-for-preview` when the preview button is clicked.

Buttons in Easy Markdown Editor have a noDisable option but there doesn't seem to be a similiar option in Blazorise.

This makes it impossible to return to the markdown view.

**Comment by stsrki** [comment]
Hi, can you please share your code so that we can reproduce it on our side?

**Comment by stsrki** [comment]
This is what I use

```
<Markdown @bind-Value="@markdownValue" CustomButtonClicked="@OnCustomButtonClicked">
    <Toolbar>
        <MarkdownToolbarButton Action="MarkdownAction.Preview" Title="Preview" />
    </Toolbar>
</Markdown>
```

When I inspect it in dev tools

1. Toolbar element is set to `editor-toolbar disabled-for-preview`
2. Toolbar button is set to `preview no-disable active`

And the same behavior can be seen in https://easy-markdown-editor.tk/. So I think it works as expected.

Closing now.
