### ISSUE TITLE
Investigate usage of IJSStreamReference for FileEdit

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#3944]
https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0#stream-from-javascript-to-net

https://twitter.com/claasdev/status/1545104580874223617

**Comment by David-Moreira** [comment]
What?? Already implemented on c49f034800d36abed1911a8e94706eb95a3c7dbb
It works pretty fast with WASM.

Any other idea with this?

**Comment by stsrki** [comment]
I forgot completely. Who can keep track of all of this anymore 😅

Closing now
