### ISSUE TITLE
IJSUtilitiesModule.GetUserAgent returning null in DatagridBaseComponent under UnitTests

### ISSUE THREAD

**Issue by AlexTeixeira** [Megabit/Blazorise#3946]
**Describe the bug**
After migrating to version 1.0.6 all my tests with a DataGrid stop working with this error :

```
System.NullReferenceException: Object reference not set to an instance of an object.

System.NullReferenceException
Object reference not set to an instance of an object.
   at Blazorise.DataGrid.DataGrid`1.IsUserAgentMacintoshOS()
   at Blazorise.DataGrid.DataGrid`1.OnAfterRenderAsync(Boolean firstRender)
   at Bunit.Rendering.TestRenderer.AssertNoUnhandledExceptions() in /_/src/bunit.core/Rendering/TestRenderer.cs:line 376
   at Bunit.Rendering.TestRenderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs, Boolean ignoreUnknownEventHandlers) in /_/src/bunit.core/Rendering/TestRenderer.cs:line 102

```

After some investigation, I notice that the **IJSUtilitiesModule.GetUserAgent** return null in my test environment.

**To Reproduce**

To reproduce the issue, juste create a component with a Datagrid ( it can be empty ).
And try to render the component in a test. In my case, I test with bUnit & xUnit.

The exception throw when the component is render.

**Expected behavior**

I expect a different value for this method. The best thing is to return an empty string instead of null.

**Additional context**

Of course, this is not a blocking thing because you can override the dependency like this.

```
`
public class JSUtilitiesModuleFake : JSUtilitiesModule, IJSUtilitiesModule
{
    public JSUtilitiesModuleFake(IJSRuntime jsRuntime, IVersionProvider versionProvider) : base(jsRuntime, versionProvider)
    {
    }

    public override ValueTask<string> GetUserAgent() => new ValueTask<string>(String.Empty);
}

//In your test dependencies

Services.AddScoped<IJSUtilitiesModule, JSUtilitiesModuleFake>();

`
```

**Comment by stsrki** [comment]
The `IJSUtilitiesModule.GetUserAgent` is a JavaScript code and bUnit doesn't support any JS invocation. That's why you need to mock any JS call for the tests to pass. Your code examples are one of the ways to do it, but you can also set up it with bUnit. Look at our source for an example https://github.com/Megabit/Blazorise/blob/master/Tests/Blazorise.Tests/Helpers/BlazoriseConfig.cs

**Comment by AlexTeixeira** [comment]
Thansk for the code examples.

I know that the `IJSUtilitiesModule.GetUserAgent` comes from JavaScript code, but still wrapper in C# code.
So it should be possible to use `??` operator to return an empty string ?

**Comment by stsrki** [comment]
I'm not sure what you mean by

> ?? operator to return an empty string

When you mock the calls you can decide what you want it to return.

**Comment by AlexTeixeira** [comment]
Let make the change directly in the method :)

We can made this change ? This avoid to create a mock or a fake for one method.
And if you move to C# 9 and above with the Nullable options enable, it will also avoid warning because you are not using `string?`

```
 public virtual async ValueTask<string> GetUserAgent()
        {
            var moduleInstance = await Module;

            return (await moduleInstance.InvokeAsync<string>( "getUserAgent" )) ?? string.Empty;
        }
```

**Comment by David-Moreira** [comment]
Hello,
Our implementation uses `navigator.userAgent` which as far as I know is widely accepted and not expected to return null, otherwise our `DataGrid` would be breaking.

In my opinion implementations should rarely ever change to accomodate tests. 

Imagine that you started to modify every component to accomodate testing code. It is the other way around, the testing code should setup the necessary environment, configuration, mocks, etc... to test the component properly.

I'm sorry but at the moment we have to respectfully decline the request to change this implementation.

However if in the future we change our Repository Coding Conventions && Guidelines to accomodate :
> And if you move to C# 9 and above with the Nullable options enable, it will also avoid warning because you are not using string?

We'll be happy to make the change as that would then make sense to adhere to the Repository Coding Conventions && Guidelines.

**PS:** Can I ask you to reference `the C# 9 and above with the Nullable options enable` feature you're talking about for our knowledge? Thanks.

**Comment by David-Moreira** [comment]
Hello,

I am now closing this issue. Feel free to reopen it if you have any other comments.

**Comment by masteratt** [comment]
> The `IJSUtilitiesModule.GetUserAgent` is a JavaScript code and bUnit doesn't support any JS invocation. That's why you need to mock any JS call for the tests to pass. Your code examples are one of the ways to do it, but you can also set up it with bUnit. Look at our source for an example https://github.com/Megabit/Blazorise/blob/master/Tests/Blazorise.Tests/Helpers/BlazoriseConfig.cs

This is great, thank you. However, I can't use it in my project as a bunit test with a DataGrid gives error:

"Cannot provide a value for property 'ComponentDisposer' on type 'Blazorise.DataGrid [...]"

And your linked helper got rid of the other errors except that one and I can't use the line:

"services.AddSingleton<IComponentDisposer, ComponentDisposer>();"

Due to the ComponentDisposer being an internal class, I don't have access to it.

Any suggestions to get rid of that error?

**Comment by David-Moreira** [comment]
Hello @masteratt 
**Try**
![image](https://github.com/Megabit/Blazorise/assets/22283161/27253a2b-8ac2-4499-85b3-355433b37745)

https://blazorise.com/docs/usage

**Comment by masteratt** [comment]
My bad on that, a RTFM moment for sure :) 

Unfortunately though, I still get a different error. I trimmed my component (stripped attributes from the table) and UT right down and this is the test I'm trying to run:

Component:
```
<div id="table-wrapper" class="h-100">
    <DataGrid TItem="GameReportTableRowDto"
              Data="@GamesList">
        <DataGridColumn Field="@nameof(GameReportTableRowDto.GameName)" Caption="Game"/>
        <DataGridColumn Field="@nameof(GameReportTableRowDto.StoreName)" Caption="Store"/>
        <DataGridColumn Field="@nameof(GameReportTableRowDto.CountryCode)" Caption="Country"/>
        <DataGridColumn Field="@nameof(GameReportTableRowDto.MasterPrice)"
                        Caption="Master Price">
        </DataGridColumn>
        <DataGridColumn Field="@nameof(GameReportTableRowDto.DetectedPrice)"
                        Caption="Detected Price">
        </DataGridColumn>
        <DataGridColumn Field="@nameof(GameReportTableRowDto.Variance)"
                        Caption="Variance">
        </DataGridColumn>
        <DataGridColumn Field="@nameof(GameReportTableRowDto.LastCheckDateTime)"
                        Caption="Last Check"
                        DisplayFormat="{0:dd MMM yyyy}">
        </DataGridColumn>
    </DataGrid>
</div>
```

Unit Test:
```
[TestFixture]
public class GameReportDataGridTests : Bunit.TestContext
{
    [Test]
    public void OnInitialized_InitialLoad_ShouldGetData()
    {
        Services.AddBlazorise().Replace(ServiceDescriptor.Transient<IComponentActivator, ComponentActivator>());

        var cut = RenderComponent<GameReportDataGrid>();

        Assert.That(cut.Instance.AllData, Is.Not.Null);
    }
}
```

The error is:
"Cannot provide a value for property 'ClassProvider' on type {myDto} There is no registered service of type 'Blazorise.IClassProvider'."

So it's back to not being able to find certain related services... And if I then add this just to get rid of that specific error:
`Services.AddSingleton<IClassProvider>( new BootstrapClassProvider() );`

Then I'm back to the cycle of having to add every missing service, as it then complains about:
" Cannot provide a value for property 'StyleProvider' on type 'Blazorise.Form'. There is no registered service of type 'Blazorise.IStyleProvider'." and so on...

I was thinking adding "Services.AddBlazorise().Replace(ServiceDescriptor.Transient<IComponentActivator, ComponentActivator>());" would do all this.

Any ideas welcome

**Comment by David-Moreira** [comment]
Hello,

`Services.AddBlazorise().Replace(ServiceDescriptor.Transient<IComponentActivator, ComponentActivator>());` Is a necessary workaround to inject this dependency with the correct lifetime scope for testing.

You still have to mock any other dependencies.
https://github.com/Megabit/Blazorise/blob/master/Tests/Blazorise.Tests/Helpers/BlazoriseConfig.cs Shows an example of that.
We use `AddBootstrapProviders` on pretty much every test, which should inject all required dependencies. 

And then we mock any required JS Interop as required by the unit we're testing. 

We're looking to def build a Test helper package, so our users can have an easier time setting up testing in the future.

**Comment by masteratt** [comment]
Ah, I had to combine the two solutions. The document read like once you put that line in, you don't need anything else. Thank you so much for your time @David-Moreira , and yeah some helpers included to make this more intuitive would be appreciated but thanks for the great support and that helper class with its static methods once you know how to use it is quite helpful in its own way already.

For Googlers who land here, final SetUp for a page with a Blazorise DataGrid looks like following:

```
[SetUp]
public void Setup()
{
    // I copied this helper class from the one linked above into my project. Replacing in that class, line 
    // "services.AddSingleton<IComponentDisposer, ComponentDisposer>();" with 
    // "services.AddBlazorise().Replace(ServiceDescriptor.Transient<IComponentActivator, ComponentActivator>());"
    BlazoriseConfig.AddBootstrapProviders(Services);

    // Here, make sure you are using the JSInterop from that helper class to call "AddDataGrid()" (or whatever Blazorise component you have in your CUT
    // and then passing in the TestContext's JSInterop.
    // You can rename the one in the helper class to not mix up the two.
    BlazoriseConfig.JSInterop.AddDataGrid(JSInterop);
}
```

I got those satisfying green ticks in my tests now. Much appreciated, have a great rest of your weekend  :)
