### ISSUE TITLE
Select doesn't call SelectedValueChanged when TValue is "MyEnum?" and SelectItem Value is "(MyEnum?)null"

### ISSUE THREAD

**Issue by Jinjinov** [Megabit/Blazorise#3958]
**Describe the bug**
Select doesn't call SelectedValueChanged when TValue is "MyEnum?" and SelectItem Value is "(MyEnum?)null"

**To Reproduce**
1. make a Select with TValue "MyEnum?" where MyEnum is an enum
2. make a SelectItem with Value "(MyEnum?)null"
3. change to another SelectItem - SelectedValueChanged is called
4. change to "(MyEnum?)null" - SelectedValueChanged is not called

**Expected behavior**
Select should call SelectedValueChanged when TValue is "MyEnum?" and SelectItem Value is "(MyEnum?)null"

**Comment by stsrki** [comment]
Do you have any content inside of the `SelectItem`? eg.

```
<SelectItem Value="(MyEnum?)null">Something here<SelectItem>
```

If yes, then `Something here` will actually become the `<option>` value. That's a browser limitation. The solution is to leave it empty.

```
<SelectItem Value="(MyEnum?)null"><SelectItem>
```

**Comment by stsrki** [comment]
https://blazorise.com/blog/how-to-handle-select-with-primitive-and-complex-types
