### ISSUE TITLE
SelectList and SelectedValues

### ISSUE THREAD

**Issue by GeertvanHorrik** [Megabit/Blazorise#3960]
**Describe the bug**

I am using the SelectList with `Multiple=true` and visually it's working great. However, I cannot seem to bind the values correctly. To have a similar API as the `AutoComplete` component, would it make sense to introduce:

* `SelectedValues` (List<TValue>)

Then, if `Multiple=true`, it's possible to bind against a list.

**Comment by stsrki** [comment]
I'm confused how we didn't notice before that `SelectedValues` is missing from `SelectList`. We will try to add it for the next release if there is not any major problem that we aren't aware of.
