### ISSUE TITLE
ListView ValueField missing?

### ISSUE THREAD

**Issue by GeertvanHorrik** [Megabit/Blazorise#3962]
The ListView does not have a ValueField, which is useful when differentiating display values from identifiers. Most other selection components support the ValueField?

**Comment by stsrki** [comment]
I believe there was a reason why we didn't add the value field. @David-Moreira, do you remember?

**Comment by David-Moreira** [comment]
You're right, I think it was just a design decision miss.

There should be a `ValueField` to uniquely identify an item, just like some of our other more complex components. Currently, the only problem with this, is if  `DisplayText` is repeated and you get an incorrect `SelectedItem`. If that is not the case, you can just access the `SelectedItem` for whatever context you need.

This will make it so we have to change `ListView<TItem>` to `ListView<TItem, TValue>` either that or provide a string based `ValueField` to keep the component simple. @stsrki ?

**Comment by stsrki** [comment]
Adding a `TValue` would be a breaking change, not an iterative change. So it would probably have to go into the v2.0. Until then, we can only ValueField as a `string` or an `object` type.

**Comment by GeertvanHorrik** [comment]
You could introduce ListView<TItem, TValue> and mark the other implementation obsolete so it wouldn't be a breaking change? Just not sure how to match the correct razor part, but maybe the engine can pick it up based on the type params?

**Comment by stsrki** [comment]
Unfortunately, the razor engine is not that smart. We cannot have two component versions that have a different generic signature, `ListView<TItem>` vs `ListView<TItem, TValue>`. Only one can exist at the time.

**Comment by David-Moreira** [comment]
2.0 might still take a while. let's provide a `ValueField<string>` in the short term. Opening a seperate issue.
