### ISSUE TITLE
Ant Design upgrade

### ISSUE THREAD

**Issue by GeertvanHorrik** [Megabit/Blazorise#3966]
I am trying to move all external dependencies (such as css, js, etc) to self-hosted so we are always in control and never dependent on external providers.

Most of the times I do this using:

```
npm install antd
```

Then as a prebuild msbuild step, I copy the dist files into `wwwroot/vendor/antd/`.

This gives me a few advantages:

1. Dependabot checks the dependencies and informs me about potential security issues
2. Self-control so I can patch if needed without relying on external parties

I noticed that Blazorise is using [4.0.0](https://www.npmjs.com/package/antd/v/4.0.0), but that seems very old (2 years). I tried upgrading to the latest (at time of writing this ticket, [4.21.6](https://www.npmjs.com/package/antd/v/4.21.6)), but here seem to be a few issues there.

A few ideas / requests / things to discuss:

1. Why not ship antd with Blazorise (or maybe give an option to do so)?
3. Would it be good to upgrade the AntDesign version (npm gives me warnings about outdated stuff and recommends to upgrade)?

One of the reasons I self-host is that I can also have light / dark mode support with Ant Design.

**Comment by stsrki** [comment]
I think the best would be to just update antd version and then to also update all the custom CSS that we have in Blazorise. Regarding the shipping of antd with Blazorise, we always wanted to avoid that because it would make it harder to use some other theme or template base on antd, if any.

**Comment by GeertvanHorrik** [comment]
Closing in favor of #4450
