### ISSUE TITLE
Autocomplete Input Changes without User Input when `SearchChanged` or `ReadData` Execute a "Long" Running Routine

### ISSUE THREAD

**Issue by gkochera** [Megabit/Blazorise#3970]
# The Issue
The Autocomplete component exhibits erratic behavior when debounce is set to `true` and SearchChanged executes a long running function synchronously or asynchronously. The text changes on its own when text is typed at a specific pace. It's almost like the TextEdit field value is being replaced with the value it had when the SearchChanged function was initially fired.

Setting `Debounce` to false eliminates this issue, but introduces a different set of challenges which are outside the scope of this issue.

I think this issue is related to what I was observing in #3865.

In my particular use case, I have the dropdown getting populated by firing off a call to a remote API after the SearchChanged event fires. I've tried setting `DebounceInterval` as low as 100 and as high as 1000. Very high values minimize this behavior but start to diminish the overall user experience because of the delay between typing and when the results populate the dropdown.

# Component Usage
```HTML
                            <Autocomplete
                                TItem="User"
                                TValue="User"
                                Data="@MatchingEmployees"
                                Debounce=true
                                DebounceInterval="100"
                                SearchChanged="@SearchChanged"
                                TextField="@GetTextField"
                                ValueField="@((item) => item)"
                                SelectedValue="@SelectedValue"
                                MaxMenuHeight="600px"
                                SelectedValueChanged="@SelectedValueChanged"
                                Placeholder="Enter an ..."
                                CustomFilter="@Filter"
                                >
                                <ItemContent>
                                   @* Just accessing context to present results with a specific look and feel, nothing special *@
                                </ItemContent>
                            </Autocomplete>
```
# SearchChanged Callback
```C#
        protected async Task SearchChanged(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                MatchingEmployees = new List<User>();
            }
            else
            {
                // I've also tried running this by making the parent function protected void and running the following line as
                // MatchingEmployees = UserService.GetEmployeesAsUsersByQueryString(value);
                // This makes it horrifically worse which I think sort of makes sense because it probably blocks Blazor's UI thread.
                MatchingEmployees = await Task.Run(() => UserService.GetEmployeesAsUsersByQueryString(value));
            }
        }
```

`GetEmployeesAsUsersByQueryString` is just running an EF routine synchronously to fetch data from a database.

# `ReadData` 

So, I know there has been some work on trying to resolve some unpredictable behavior in this particular use case by creating a parameter called `ReadData` for this component.

I pulled that code down, implemented it in my project and ran it. I hate to say, but the same thing happens. Same values yield the same behavior except that now I'm firing my API call on `ReadData` instead of `SearchChanged`.

I dove in as far as I can understand the overall implementation and if I had to throw a Hail Mary, I'd say there is either some sort of race condition happening (maybe something to do with 2 way binding), or there might be an issue with how debounce is implemented in `ValueDebouncer.cs`. But those are honestly pure guesses. I'm not as well versed in C# and Blazor as those who work in this project so I'm not going to pretend like I know deeply what is going on here.

# To Reproduce
1. Implement an AutoComplete in your code. `Debounce` must be true. `DebounceInterval` should be anywhere between 100 and 1000, but I'm sure it will manifest with other values.
2. Write a `SearchChanged` callback that runs some "long" running routine (like an API call to fetch data) and setting the dropdown contents equal to the returned data.
3. Type text in the Autocomplete at varying cadences, observe erratic behavior.

# Expected behavior
The TextField shouldn't change at all for any reason other than what the user types in. To be honest, I'd think that a fire-and-forget approach would be ideal. As the user types, send the request out, and when it comes back, render the dropdown with the updated content.

# Screenshots
![ezgif com-gif-maker](https://user-images.githubusercontent.com/54916850/179263762-ae098f6c-bc4c-4427-8478-61492916a2d9.gif)
This image shows me attempting to type the word 'brown' into my Autocomplete 4 different times at different cadences. Notice how sometimes certain letters disappear as I am typing, and at one point, the letters that disappeared, come back and spell out the correct word. From a UX perspective, this is a show-stopper.

# Use Case Information

.Net 6 project using Blazor Server Side
Running locally generally has less occurrences of this issue, but manifests more often when the project is deployed on an AWS EC2 instance. As I stated, I've experimented with all sorts of `DebounceInterval` values.

**Comment by David-Moreira** [comment]
Hello @gkochera,

Please make use of our `ReadData` for these type of operations on our **v1.1.0**. This is our recommended way to deal with fetching /updating data as user types. We've made it so, there should not be a race condition. (You should check the provided `CancellationToken.IsCancellationRequested` before updating your data after the long running operation)

Closing this issue now. Please don't hesitate to reopen this issue if for some reason it does not work out.
