### ISSUE TITLE
Localization for FileEdit isn´t kicking in

### ISSUE THREAD

**Issue by sturlath** [Megabit/Blazorise#3976]
Hi for some reason I´m not getting the Icelandic localization for File edit (its [here](https://github.com/Megabit/Blazorise/blob/67da3e1fb3256f83f25eb378026eda10768322b5/Source/Blazorise/Resources/Localization/FileEdit/is.json))

Basically this code

```xml
<Validation Validator="@ValidatePosterUpload">
    <FileEdit Filter="image/jpeg, image/jpg, image/gif" Changed="@OnPosterImageChanged" Multiple="false">
        <Feedback>
            <ValidationError />
            <FieldHelp>@L["EventPosterFieldHelp"]</FieldHelp>
        </Feedback>
    </FileEdit>
</Validation>
```

But as you can see its not getting localized but my abp.io `@L["EventPosterFieldHelp"]` is.
![image](https://user-images.githubusercontent.com/2386572/179399360-5065cc35-4a0e-41de-85aa-5fb084918223.png)

Am I missing something?

I´m on Blazorise 1.0.4 and abp.io 5.3.2

**Comment by stsrki** [comment]
Are you using the BS5 provider? In the latest Bootstrap 5, there is no content defined in the DOM that could be replaced by the localization. So the label "No file chosen" is now controlled by the browser. Not sure if we can do anything about it. JavaScript comes to mind, but we will need to investigate that approach.

**Comment by sturlath** [comment]
Yes Im using BS5. Hopefully its possible to localize it sice it some how. It looks out of place like this. Wish I could help 🫣
