### ISSUE TITLE
Chart options only partially working

### ISSUE THREAD

**Issue by jpacreb** [Megabit/Blazorise#3977]
The chart options don't appear to match the documentation [Blazorise Chart component](https://blazorise.com/docs/extensions/chart), an example being that the **Legend** option is not available,

I'm in the process of upgrading from 9.5.7 to 1.0.5  and am experiencing problems getting the charts to work properly.  In 9.5.7 I was using the **OptionsObject** property, but this isn't working in 1.0.5, and the **Options** property is not working either so I cannot get the charts to format properly.

Below is a minimal implementation of a Doughnut chart that demonstrates some of the problems.  Please Note:

- The **AspectRatio** option is available in the option (_and works as expected_) so some options work.
- The **CutoutPercentage** option is available for Doughnut charts but setting it _does not do anything_.
- The **Legend** option is meant to be available according to the documentation but is not i.e. program cannot be compiled

```
@page "/ChartTest"

<Card ColumnSize="ColumnSize.Is3">
    <CardBody>
        <DoughnutChart @ref="doughnutChart" TItem="double" Options="@chartOptions" />
    </CardBody>
</Card>

@code {
    private DoughnutChart<double> doughnutChart;
    private bool isAlreadyInitialised;
    private Random random = new( DateTime.Now.Millisecond );
    private List<string> colors = new () 
    {
        ChartColor.FromRgba( 255, 0, 0, 0.2f ),
        ChartColor.FromRgba( 0, 255, 0, 0.2f ),
        ChartColor.FromRgba( 0, 0, 255, 0.2f ),
        ChartColor.FromRgba( 0, 0, 0, 0.2f ),
    };

    private DoughnutChartOptions chartOptions = new()
    {
        AspectRatio = 1.5,     // This works 
        CutoutPercentage = 90, // This doesn't work 
        //Legend = new ChartLegend  // This wont even compile if uncommented
        //{
        //    Display = false
        //}
    };

    private async Task HandleRedraw<TDataSet, TItem, TOptions, TModel>( BaseChart<TDataSet, TItem, TOptions, TModel> chart, Func<TDataSet> getDataSet )
     where TDataSet : ChartDataset<TItem>
     where TOptions : ChartOptions
     where TModel : ChartModel
    {
        await chart.Clear();

        await chart.AddLabelsDatasetsAndUpdate( new List<string> { "Q1", "Q2", "Q3", "Q4" }, getDataSet() );
    }

    protected override async Task OnAfterRenderAsync( bool firstRender )
    {
        if ( !isAlreadyInitialised )
        {
            isAlreadyInitialised = true;

            await Task.WhenAll(HandleRedraw(doughnutChart, GetDataset));
        }
    }

    private DoughnutChartDataset<double> GetDataset()
    {
        return new DoughnutChartDataset<double>
        {
            Data = new List<double>{random.NextDouble() * 50,random.NextDouble() * 10,random.NextDouble() * 10,random.NextDouble() * 10 },
            BackgroundColor = colors,
            BorderColor = colors,
            BorderWidth = 1,
        };
    }
}
```
 
Is there a way to work around this?  I've tried both **OptionsObject** and **OptionsJsonString** but couldn't find a way to hide the legend or set the cutout percentage.

**Comment by stsrki** [comment]
A lot has changed in the latest chart extension. We have moved to the v3 chart.js library, which had some breaking changes. Since you were using OptionsObject previously, it means a lot of stuff is not strongly typed for you, and you should look at their documentation for guidance https://www.chartjs.org/docs/latest/getting-started/v3-migration.html

By the way, I strongly suggest using the `Options`  parameter in v1.0.x. We tried to map as many options from chart v3, so it is now much better than on 0.9.x. Also, many improvements are made regarding the JSON serialization, so only what is used is sent directly to the JS.

**Comment by jpacreb** [comment]
Hi stsrki,

Thanks for the quick reply.  I'm trying to use the ```Options``` parameter, however:

1.  there is no ```Options.Legend``` property on the class (even though the documentation says there is).  
2. the ```DoughnutChartOptions.CutoutPercentage``` property does not have any effect on the doughnut.

I think some of the implementation of the ```Options``` class is missing, and so I will need to work around it with the ```OptionsObject```.  I will look through the documentation in the link you sent to see if I can work it out from there.

Thanks.

**Comment by stsrki** [comment]
Note for me https://www.chartjs.org/docs/latest/charts/doughnut.html#config-options

**Comment by well0549** [comment]
Maybe this helps, i struggled a lot with this. But now it works ok.

using Blazorise.Charts;
using BlazorisePortal.Models.Settings;

namespace BlazorisePortal.Components
{
    public static class DefaultChartOptions
    {
        public static object GetLineChartOptionsObject(string title)
        {
            object chartOptions = new
            {
                Animation = new
                {
                    Duration = 0,
                },
                Plugins = new
                {
                    Title = new
                    {
                        Text = title,
                        Color = SiteSettings._GraphLegend.TranslatedValue,
                        Display = true
                    },
                    Legend = new
                    {
                        Labels = new
                        {
                            Color = SiteSettings._GraphLegend.TranslatedValue,
                        }
                    },
                    zoom = new
                    {
                        zoom = new
                        {
                            drag = new
                            {
                                enabled = true,

                            },
                            mode = "x",
                            overScaleMode = "x",
                        },
                     },
                },
                Responsive = true,
                MaintainAspectRatio = false,
                Scales = new
                {
                    Y = new
                    {
                        Ticks = new
                        {
                            Color = SiteSettings._GraphLegend.TranslatedValue,
                        },
                        Grid = new
                        {
                            Color = SiteSettings._GraphBackground.TranslatedValue,
                        }
                    },
                    X = new
                    {
                        Type = "time",
                        Distribution= "series",
                        time = new
                        {
                            unit = "hour",
                         },
                        Ticks = new
                        {
                            Color = SiteSettings._GraphLegend.TranslatedValue,
                        },
                        Grid = new
                        {
                            Color = SiteSettings._GraphBackground.TranslatedValue,
                        },
                    },
                },
                Interaction = new
                {
                    intersect = false
                }
            };

            return chartOptions;
        }
    }
}


and use it loke so 👍 
sing Blazorise.Charts
@using BlazorisePortal.Components
@using BlazorisePortal.Models.Settings
@inject NavigationManager NavManager
@inject IJSRuntime JS
<Div Style=@($"height:{ViewHeight}vh; width:{ViewWidth}%;margin:10px 0px 10px 0px;padding:0px 20px 0px 10px;border-style:solid;border-width:1px;border-color:{SiteSettings._GraphBackground.TranslatedValue}")>
    <Div Style=@($"position: relative; height:100%; width:100%;")>
        <LineChart @key="@(System.Guid.NewGuid().ToString())" @ref="lineChart" TItem="DataPoint" Clicked="@OnClicked" OptionsObject="@DefaultChartOptions.GetLineChartOptionsObject(ChartTitle)" />
    </Div>
</Div>

**Comment by stsrki** [comment]
Thank you @well0549

**Comment by alen-resser** [comment]
Cutout is still not working 3 years later, how is this possible?

**Comment by stsrki** [comment]
> Cutout is still not working 3 years later, how is this possible?

People forget. 

Opening a new ticket for 1.8

**Comment by alen-resser** [comment]
> > Cutout is still not working 3 years later, how is this possible?
> 
> People forget.
> 
> Opening a new ticket for 1.8

well that is true, happens to me all the time.

here's the workaround until guys map it in the next version in case someone needs it 

var customOptions = new Dictionary<string, object>
{
    { "cutout", "75%" },
    { "borderWidth", 2 },
    { "plugins", new Dictionary<string, object>
        {
            { "legend", new Dictionary<string, object> { { "display", false } } },
            { "tooltip", new Dictionary<string, object> { { "enabled", true } } }
        }
    }
};
await Chart.SetOptionsObject(customOptions);

**Comment by stsrki** [comment]
> > > Cutout is still not working 3 years later, how is this possible?
> > 
> > 
> > People forget.
> > Opening a new ticket for 1.8
> 
> well that is true, happens to me all the time.
> 
> here's the workaround until guys map it in the next version in case someone needs it
> 
> ```
> var customOptions = new Dictionary<string, object>
> {
>     { "cutout", "75%" },
>     { "borderWidth", 2 },
>     { "plugins", new Dictionary<string, object>
>         {
>             { "legend", new Dictionary<string, object> { { "display", false } } },
>             { "tooltip", new Dictionary<string, object> { { "enabled", true } } }
>         }
>     }
> };
> await Chart.SetOptionsObject(customOptions);
> ```

To be honest, I never thought we could use a dictionary instead of an `object`. The new simplified dictionary syntax in the latest C# versions really helps.
