### ISSUE TITLE
Autocomplete better keyboard support

### ISSUE THREAD

**Issue by glutio** [Megabit/Blazorise#3980]
**Is your feature request related to a problem? Please describe.**
In the Autocomplete demo, it is not possible to remove the selected badges with a backspace and not possible to tab to a specific badge to delete it.
<img width="322" alt="image" src="https://user-images.githubusercontent.com/22550674/179654789-cae72fc6-0922-410e-bc7a-717c7b99b27d.png">

**Describe the solution you'd like**
Add keyboard navigation support

### Additional context
Thanks for your work

**Comment by stsrki** [comment]
It seems like a good feature to have. We can try adding it for the future milstone.
