### ISSUE TITLE
WASM : Reinvestigate startup improvements

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#4005]
WASM : Reinvestigate startup improvements

**Comment by stsrki** [comment]
https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-trimmer?view=aspnetcore-6.0

**Comment by stsrki** [comment]
https://github.com/ILoveDotNet/ilovedotnet has a prerendering enabled.

**Comment by sturlath** [comment]
Is Blazorize slow to startup? I have been having massive [loadtime issues with abp.io](https://github.com/abpframework/abp/issues/13114) and I thought that apb.io was the issue.

 Just to add I cant use [trimming  ecause  of obfuscated dlls](https://github.com/abpframework/abp/issues/13373) at the moment

**Comment by stsrki** [comment]
Blazorise has very little footprint compared to ABP, but we still want to make it better. The end result should be to load instantly, if possible.

**Comment by David-Moreira** [comment]
Right, when we talk about start up improvements, it's stuff/tricks that you can do to make it actually download faster or be perceived to load faster, since WASM as you know has a big payload.

We had tried the trimmer and the prerender in the past with no great success...
But we've recently started to see some wasm sites load pretty fast on first load.... So we'll be taking a look at those and reinvestigate this.

So we'll see what we can do on **our demo** running **WASM**. So basically we'll be trying to optimize the demo wasm app, not exactly Blazorise itself. Altought if there's improvements we can do, we wil if it makes sense of course.

**Comment by stsrki** [comment]
And we can and will write a blog post once we figure the necessary steps to make it load faster.

**Comment by stsrki** [comment]
@David-Moreira  Should we close this? The coming Blazor United in .NET 8 will most probably solve the loading problem.

**Comment by David-Moreira** [comment]
The Blazor United is an effort centralized in reusing all the tools available in kind of a single solution but one thing it does require for some of the features, like loading the Blazor.Server component first while loading the dlls in the background, isis having the solution hosted in a server. Which is kinda different from straight up just having the app served without a "dedicated" server. I.e only reading html and css/js/dll/etc... resouces

However nowadays as long as you are using dotnet publish you should already notice that the apps load pretty fast. So you can close with that in mind.
