### ISSUE TITLE
Select List Extension Multiple Select

### ISSUE THREAD

**Issue by samuelhurni** [Megabit/Blazorise#4012]
**Describe the bug**
I want to use a multiple Select List with the SelectList Extension.  For that I have to change the the TValue item to a list, becauseotherwhise the callback Method will not be accepted. But with a List in TVlaue I have other errors. So how can I use a Multiple Select List with a Callback Method with a list of the selected Items inside?

```
<SelectList   
                        TItem="MySelectModel" 
                        TValue="int"
                        Data="@selectDataCategorie"
                        TextField="@((item)=>item.MyTextField)"
                        ValueField="@((item)=>item.MyValueField)"
                       @* SelectedValue="@selectedValueCategorie" *@
                        SelectedValueChanged="OnSelectedValueCategorieChanged"
                        DefaultItemText="Kategorie auswählen"
                        Multiple/>



private Task OnSelectedValueSubCategorieChanged( IReadOnlyList<int> obj )
    {
        selectedValueSubCategorie = obj;
        foreach (var item in obj)
        {
            Console.WriteLine(item);
        }
        return Task.CompletedTask;
    }
```

**Comment by stsrki** [comment]
In 1.0.x we're still missing a `SelectedValues` and `SelectedValuesChanged` parameters that are supposed to be used for Multiple modes. It is already fixed for the next v1.1 release, but it is still not ready for the public.
