### ISSUE TITLE
DataTable Not renderng all rows

### ISSUE THREAD

**Issue by BrenMcM** [Megabit/Blazorise#4015]
Hi,
I am trying to work with the DataTables. However it seems they have issues rendering All rows.
From the images you will see I have a DataTable with List Source on top, and a regular Table on the bottom using the same source. For the DataTable, no more that 5 rows ever renders. I have no special styling etc and have tried Refresh, and state.hasChanged to no effect.
Please Help.
![UI_Issue](https://user-images.githubusercontent.com/25453203/181351629-ac8c5b5f-279f-43f4-90cc-254a3b918e19.jpg)
![CodeOfIssue](https://user-images.githubusercontent.com/25453203/181351703-691688d3-6c0b-48db-b296-3412288574fe.jpg)

**Comment by stsrki** [comment]
You just need to increase the page size. eg.

`<DataGrid PageSize="20">`

**Comment by mtbayley** [comment]
I found this confusing the first time I used the DataGrid. Maybe the default should be to show the pager if the number of items exceeds the page size.

**Comment by stsrki** [comment]
I think we can increase a default from 5 to 10. It seems like a more natural number that people would expect.
