### ISSUE TITLE
DateEdit component ignores seconds

### ISSUE THREAD

**Issue by andythomasdev** [Megabit/Blazorise#4016]
**Description**
When programmatically setting the `Date` attribute of the `DateEdit` component to a specific value such as `DateTime.Now`, the component ignores seconds, and only sets the date, hour, and minute. 

**To Reproduce**
1. Add a `DateEdit` component to a page.
2. Set `TValue="DateTime?"`
3. Set `InputMode="DateInputMode.DateTime"`
4. Set `Date="@DateTime.Now"`
5. Load and view the page. The field will show the current date, hour, and minute, but seconds will be 0.

**Expected behavior**
The field should be set with the exact value of `DateTime.Now` when the page is rendered, including seconds.

**Code**
![image](https://user-images.githubusercontent.com/95927725/181358887-8a0a6c93-714e-4d29-acea-c9b7f075833e.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/95927725/181358424-e2a9c671-5120-47ec-a55c-d8b1589ca551.png)

**Comment by andythomasdev** [comment]
@stsrki Has this been looked into?

**Comment by stsrki** [comment]
Not jet. Sorry, somehow it went under the radar. Adding on the backlog.

**Comment by stsrki** [comment]
After a little investigation, it seems that seconds are not supported with `input type="datetime-local"` https://stackoverflow.com/questions/58023438/cant-set-seconds-value-of-input-type-datetime-local-to-be-0

**Comment by andythomasdev** [comment]
Why have your DateEdit component include a selection for seconds then? Is there no way to get this to work?

**Comment by andythomasdev** [comment]
In an attempted workaround, I'm trying to use your InputMask component. It seems to have a bug where it is unable to distinguish between `MM` for month and `mm` for minute. When using this input, the minute section is treated as month, and I am unable to type in a value greater than 12. 

![image](https://user-images.githubusercontent.com/95927725/199350362-141218da-20ed-4a64-ab48-57141a063693.png)

**Comment by stsrki** [comment]
Have you tried with DatePicker component?

**Comment by andythomasdev** [comment]
No, I need to be able to enter a specific date and time down to the second. I would be fine with using the `InputMask` component, but as I noted above, it appears to have a bug with the InputFormat not being able to distinguish between `MM` for month and `mm` for minutes.
