### ISSUE TITLE
Question about Autocomplete

### ISSUE THREAD

**Issue by grumpykiwi** [Megabit/Blazorise#4021]
This is not exactly a bug. I just haven't figured out how to do it

I have a class like this:

```
public class Project
{
	public string ClientCode { get; set; }
	public string CommunicationItem { get; set; }
}
```

I want to use an Autocomplete that enables me to search both fields for a match.

Let's say I want to select the following item in the Projects List<Project> collection

ClientCode = '0722.0011'
CommunicationItem = 'Quarterly Refresh'

If I search on 'quar' or '0011' in the text field I want the following to show as a match:

0722.0011 - Quarterly Refresh

When I click on that, I want the selected value to be the value in ClientCode (0722.0011) and the selected text in the textbox to be

0722.0011 - Quarterly Refresh

How do I achieve that?

I have gone around in circles trying to get this to work to no avail.

Thanks

Mark

**Comment by grumpykiwi** [comment]
Well I got it to work I think, I had to fiddle a bit with calling custom methods and getting the calling syntax correct

Here is the relevant code. I hope this helps someone trying to do the same thing, Your mileage may vary of course.

```
public class Project
{
	public string ClientCode { get; set; }
	public string CommunicationItem { get; set; }
}

protected bool OnCustomFilter(Project project, string searchValue)
{
	if (project is null)
		return true;

	return
		project.ClientCode.Contains(searchValue, StringComparison.OrdinalIgnoreCase) == true ||
		project.CommunicationItem.Contains(searchValue, StringComparison.OrdinalIgnoreCase) == true;
}

protected async Task SelectedProjectChanged(string clientCode)
{
	if (string.IsNullOrEmpty(clientCode))
	{
		return;
	}
	EditTimeModel.ProjectCode = clientCode;
	using var ctx = await DbFactory.CreateDbContextAsync();
	var project = await ctx.Projects.Where(c => c.ClientCode == clientCode).FirstOrDefaultAsync();
	SelectedProjectText = $"{project.ClientCode} - {project.CommunicationItem}";
}


<Autocomplete TItem="Project"
		  Style="flex-grow: 1;"
		  MinLength="2"
		  TValue="string"
		  Data="@Projects"
		  TextField=@((i) => $"{i.ClientCode} - {i.CommunicationItem}")
		  ValueField="@(( item ) => item.ClientCode)"
		  SelectedText="@SelectedProjectText"
		  SelectedValue="@EditTimeModel.ProjectCode"
		  SelectedValueChanged="@SelectedProjectChanged"
		  Placeholder="Select a project..."
		  Filter="AutocompleteFilter.Contains"
		  CustomFilter="@(( item, searchValue ) => OnCustomFilter(item, searchValue))">


	<ItemContent Context="project">
		@project.Item.ClientCode - @project.Item.CommunicationItem
	</ItemContent>
</Autocomplete>
```

Sorry to waste your time. Been fiddling with this code off and on for a long time. All of a sudden management actually wants to use the project so I am hurrying to test it and get it to staging for a thrashing by the masses.

**Comment by stsrki** [comment]
Thanks for sharing your solution.
