### ISSUE TITLE
DataGrid fixed header bootstrap5 CSS selector bug

### ISSUE THREAD

**Issue by simonkorosec** [Megabit/Blazorise#4028]
**Describe the bug**
The Bootstrap5 CSS styles contain a typo for the fixed header background color rule. Currently the selector doesn't match the headers and so it has no background color meaning that the rows are visable as you scroll down (for example on virutalized tables).

Current CSS:
```
        > thread:not(.table-thead-theme) > th {
            background: white;
        }
```
Corrected CSS:
```
        > thead:not(.table-thead-theme) th {
            background: white;
        }
```

**Comment by mtbayley** [comment]
Noticing this also with our grids.
