### ISSUE TITLE
Author Bio

### ISSUE THREAD

**Issue by jamattey** [Megabit/Blazorise#4046]
To build a community, an author bio will help communicate the authenticity of an author and how people can reach out to him. 

![image](https://user-images.githubusercontent.com/69109175/184718946-5bb45840-36a0-4574-aa76-d4d0ab244800.png)

**Comment by David-Moreira** [comment]
@stsrki I'm not sure what issue is this. Do we keep this open?

**Comment by stsrki** [comment]
Nop. Closing it.
