### ISSUE TITLE
The Class property of a Card component is ignored

### ISSUE THREAD

**Issue by tacoWanneeJama** [Megabit/Blazorise#4047]
When you do a `<Card Class="my-class">` the resulting html is not decorated with this style-class.

It would be nice if this would function as expected.
I am using the latest version of Blazorise Wasm (1.06)

**Comment by stsrki** [comment]
I cannot reproduce it. it seems to work fine on my side.

```cshtml
<Card Margin="Margin.Is4.OnY" Class="my-class">
```

![image](https://user-images.githubusercontent.com/900302/184849665-1dc19fef-b906-4d80-acfe-9f9eb0e96dc8.png)

---

What provider do you use?

**Comment by tacoWanneeJama** [comment]
Sorry, I can't reproduce it now either.
Must have been a mistake in my code.
