### ISSUE TITLE
Suggestion: Add Blazorise.Charts.ChartColor.ToString()

### ISSUE THREAD

**Issue by blake-fm** [Megabit/Blazorise#4052]
**Is your feature request related to a problem? Please describe.**
`Blazorise.Charts.ChartColor` supports implicit string conversion, but not string interpolation / anything trying to call `object.ToString()`

**Describe the solution you'd like**
Probably just add `public override string ToString() => ToJsRgba();`

**Comment by stsrki** [comment]
It seems like an easy thing to do.
