### ISSUE TITLE
Markdown HideIcons adds icons when trying to hide image icon

### ISSUE THREAD

**Issue by HdVsha** [Megabit/Blazorise#4056]
**Describe the bug**
When trying to hide the image icon in default Markdown toolbar, the image icon disappears(as it should) but also adds "fullscreen" and "side-by-side" icons to toolbar.

**To Reproduce**
1. Create Markdown component;
2. Add HideIcons="@(new []{"image"})" to the component;
3. Open Markdown editor at the website;
4. See added icons.

**Expected behavior**
Only image icon disappearance.

`<Markdown HideIcons="@(new []{"image"})"/>`

**Screenshots**
This is what happens if I try to hide image icon.
<img width="478" alt="image" src="https://user-images.githubusercontent.com/62552291/185627940-93a0d0d9-04d6-4854-ae3f-6d2daf2a3f0e.png">

**Comment by HdVsha** [comment]
Without HideIcons="@(new []{"image"})"
<img width="490" alt="image" src="https://user-images.githubusercontent.com/62552291/185628269-d3d8d0d7-3a7b-4aa9-9d7c-45df905332a6.png">

**Comment by Jimmys20** [comment]
The `HideIcons` property has a default value of `new[] { "side-by-side", "fullscreen" }`:

`[Parameter] public string[] HideIcons { get; set; } = new[] { "side-by-side", "fullscreen" };`

When you set the parameter you have to add those two values yourself.
`<Markdown HideIcons="@(new []{"image", "side-by-side", "fullscreen" })"/>`

**Comment by HdVsha** [comment]
Oh, yes, I see. Thank you for your response!
