### ISSUE TITLE
Datagrid row-level context menu's

### ISSUE THREAD

**Issue by tacoWanneeJama** [Megabit/Blazorise#4076]
I now use [Blazor.Contextmenu](https://github.com/stavroskasidis/BlazorContextMenu) component to add context menu's for Blazor. This can simply be applied for cell fields of a `<Datagrid>` by using the `<DisplayTemplate>`.
But we like to make the contextmenu on row level instead of cell-level. Just adding it to all cells of the row is very messy, and the space between cells and empty cells are not covered in this way.

For this we want to be able to add a component that wraps the full row.

Even nicer would be that the [Blazor.Contextmenu](https://github.com/stavroskasidis/BlazorContextMenu) is fully integrated and supported by Blazorise.

**Comment by stsrki** [comment]
In the upcoming v1.1, we will have a row context menu event https://github.com/Megabit/Blazorise/blob/master/Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs#L1860

**Comment by tacoWanneeJama** [comment]
Nice, is a release date planned?
