### ISSUE TITLE
Can't find Blazorise scripts for initial setup

### ISSUE THREAD

**Issue by DevYaroslavOrlov** [Megabit/Blazorise#4095]
There was created a simple asp.mvc application using .net6.
The application was reworked to use Blazor framework is some time.
Next step is start use **Blazorise** lib.

1. did everything according to official doc to setup.
2. use simple component like **Button** or **RichTextEdit** via additional setup
3. start application
4. the error for init scripts is occurred that called `DirectoryNotFoundException: Could not find a part of the path \wwwroot\_content`

I am new at **Blazor** and **Blazorise** but supposed to be easy setup initial configuration. What's wrong I am doing?

![image](https://user-images.githubusercontent.com/75127246/189521521-12f7f1c7-ca14-412c-b370-8b36dc4ac7ce.png)
![image](https://user-images.githubusercontent.com/75127246/189521535-767ac75a-17db-463f-9242-42cacadb2c94.png)

**Comment by stsrki** [comment]
My suspicion is that you have a custom path in your URL. Try reading

- #3160
- #3378
- #3431

and apply the `UseStaticFiles` where needed. Please let me know how it goes.

**Comment by DevYaroslavOrlov** [comment]
I apply `UseStaticFiles` with empty path, apply base tag on _layout, use all scripts on _layout but still have error

**Comment by DevYaroslavOrlov** [comment]
Actually I didn't get how and why it works but it helps

https://github.com/Megabit/Blazorise/issues/3160#issuecomment-1059579141

`builder.WebHost.UseStaticWebAssets();`

**Comment by stsrki** [comment]
Glad you were able to make it work :)

Closing now.
