### ISSUE TITLE
Modal has a memory leak (Blazor Server only)

### ISSUE THREAD

**Issue by ryanph-javs** [Megabit/Blazorise#4100]
**Describe the bug**
There is a memory leak in the Modal component in Blazor Server (there is no issue with WASM).

**To Reproduce**
1. Create a new Blazor Server project
2. Add Blazorise nuget packages (I've seen the issue with bootstrap4 and bootstrap5 packages) and add to Program.cs
4. Add a Modal to any page (can literally be just `<Modal/>`)
5. Navigate to and from that page several times
6. Take a memory snapshot and there will be a modal for every time you visited the page

**Expected behavior**
No memory leak

**Screenshots**
My `Counter.razor` file (the default for this file adding only `<Modal/>`)
![image](https://user-images.githubusercontent.com/74311566/189755552-4dd2349d-787e-4959-9abf-fae157dc6b62.png)

Memory snapshot taken in Jetbrains dotMemory after forcing GC showing there are 7 Modals in memory after visiting the page 7 times. 
![image](https://user-images.githubusercontent.com/74311566/189754948-d4bc5bca-4bcc-4333-b8c4-24618ffb2baf.png)

**Additional context**
None

**Comment by ryanph-javs** [comment]
It never gets cleared, I gave it a lot of time and forced the GC and they all stick around. I tested from 1.0.6 back to 1.0.4 and the issue exists in each of them.

**Comment by EnsignPayton** [comment]
I tried commenting out the UI implementation of `Modal`, setting all fields to default, switching between `Server` and `ServerPrerendered`, and nothing made a difference. There's still a reference to `Modal` hanging around for every page load, even after forcing a GC collect using either dotMemory's UI or `GC.Collect()`.

This is from a single page view off of `master` with only a `<Modal/>` added to the page.

![image](https://user-images.githubusercontent.com/18620874/189942793-684e263a-34cb-4050-bf41-011241881bce.png)

![image](https://user-images.githubusercontent.com/18620874/189943184-5813e852-919d-4da6-8c4f-5d034be3c88d.png)

The outgoing references and `ClosableAdapter` incoming reference are all fine and expected from what I can tell, but the modal stays in `ServiceProviderEngineScope`'s list of disposables forever.

I think what we're running into is an issue with Microsoft DI's handing of disposable transient services:

https://github.com/dotnet/runtime/issues/36461

Unfortunately, MS has been sitting on this issue for three years now.

**Comment by stsrki** [comment]
I have also done the same, commented on everything, and Modal is still held in my memory. DI might be the problem, but even if I comment it [here](https://github.com/Megabit/Blazorise/blob/rel-1.0.0/Source/Blazorise.Bootstrap/Config.cs#L61) it is still alive.

**Comment by EnsignPayton** [comment]
Ref https://github.com/Megabit/Blazorise/issues/2165
