### ISSUE TITLE
Treeview - Expand all nodes in the TreeView by default 

### ISSUE THREAD

**Issue by saeb-panahifar** [Megabit/Blazorise#4108]
**Is your feature request related to a problem? Please describe.**
It seems that there is no mechanism to expand all nodes in the `TreeView` by default 

A clear and concise description of what the problem is. Example: I am trying to set the below `Treeview` expand but unfortunately, there is no specific property to configure. 
<img width="272" alt="Screen Shot 2022-09-14 at 10 33 17 AM" src="https://user-images.githubusercontent.com/17474030/190211602-ad31921d-9e7b-4635-9bb9-d620bcbe7804.png">

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by David-Moreira** [comment]
Hello,

While a good feature to have.

You might be able to do this currently.
Have you tried adding the Nodes to the `ExpandedNodes` collection? Even if its the full collection? My guess is that it can still figure out the correct structure as long as `GetChildNodes` and `HasChildNodes` are well defined.

**Comment by saeb-panahifar** [comment]
Here is a PR for this: https://github.com/Megabit/Blazorise/pull/4116

**Comment by saeb-panahifar** [comment]
> Hello,
> 
> While a good feature to have.
> 
> You might be able to do this currently. Have you tried adding the Nodes to the `ExpandedNodes` collection? Even if its the full collection? My guess is that it can still figure out the correct structure as long as `GetChildNodes` and `HasChildNodes` are well defined.

Yes, I agree it is a useful feature. I checked that but it didn't work.

**Comment by David-Moreira** [comment]
> > Hello,
> > While a good feature to have.
> > You might be able to do this currently. Have you tried adding the Nodes to the `ExpandedNodes` collection? Even if its the full collection? My guess is that it can still figure out the correct structure as long as `GetChildNodes` and `HasChildNodes` are well defined.
> 
> Yes, I agree it is a useful feature. I checked that but it didn't work.

Hello,
I had some treeview code sitting around from helping a customer. So I went and gave it a try since I was kinda sure it would work.
It does work, here's an example.

![image](https://user-images.githubusercontent.com/22283161/191356094-a90e5332-542d-4096-8e76-0884d33f974a.png)
![image](https://user-images.githubusercontent.com/22283161/191356137-b238a5a8-4f61-4f2b-a110-43dd1db8419d.png)
![image](https://user-images.githubusercontent.com/22283161/191356177-318e77c2-5445-4a49-99ac-cd27eb8fef45.png)

**Comment by saeb-panahifar** [comment]
Let me try this way.

**Comment by David-Moreira** [comment]
Right. Just post your source code if you can  if it isn't working for some reason.

**Comment by saeb-panahifar** [comment]
By doing this way it worked. The reason why before did not work was because I just loaded and set it to `ExpandedNodes`. So I already loaded the items why do we need to loop again for expanding? 

Let me tell you the scenarios we have.  
1. We need to expand all nodes when we load data.
2. We want to store data with `IsExpanded`. (In the current implementation we have to store an extra list for expanded nodes).
3. Sometimes we want to set a specific node depending on the business logic in the backend. 


All in all, If we have expanded information besides the node we can fully control of node. We won't need to store a separate list.  Loaded data will have that information.

**Comment by David-Moreira** [comment]
> So I already loaded the items why do we need to loop again for expanding (child nodes)?

On my version I was iterating tough every node and adding every node's `Children` to the expanded Nodes.
I.E: **ByModule** adds **Developer** / **Test** / **Settings** Which in turn loops again on each node and adds their own children.... **Developer** adds **IDE** / **Tools**, so on...
![image](https://user-images.githubusercontent.com/22283161/191378530-8e51f476-7344-4947-b79a-04217c6633ed.png)


If you have the `IsExpanded` information on your own data. Then it's easy to just add those exact nodes to the `ExpandedNodes` collection.

So with this, do you have enough information to make it work as you'd like on your end?

**Comment by saeb-panahifar** [comment]
I would prefer to have one collection rather than two but that is fine.

Thanks for the explanation.

Since your approach support this scenario. Should I close this PR? https://github.com/Megabit/Blazorise/pull/4116

**Comment by David-Moreira** [comment]
Well we'd still appreciate your contribution to Blazorise. 

The ExpandAll is a good feature to have. But of course, in the end its up to you.
