### ISSUE TITLE
Treeview - Access the state of Treeview

### ISSUE THREAD

**Issue by saeb-panahifar** [Megabit/Blazorise#4109]
**Is your feature request related to a problem? Please describe.**
On our website we like to save the `Treeview` state and when a user back to the page it shows the latest state of `Treeview`.  At the moment this is impossible because this work has been done internally. 

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by David-Moreira** [comment]
Hmm can you elaborate? While a complete "graph" would be ideal. 
Maybe a `treeRef.GetNodesState` or something like that provides you with a Tree Strucutre with your provided data would be interesting to have.

But I believe, you might already have that information? You have both the `ExpandedNodes` collection and the `Nodes` collection (The one you provide)? Would that not be enough?

**Comment by stsrki** [comment]
I agree with @David-Moreira; you already have complete control over the expanded nodes and how to load child nodes. So I don't think adding API to access the internal state is needed.

Closing this now.
