### ISSUE TITLE
badge - different colors and css classes - custom theming? configuration missing?

### ISSUE THREAD

**Issue by drma-dev** [Megabit/Blazorise#4111]
I noticed that, at least in the badge, the colors of my badge are not the same as the documentation site. I don't know if it's some configuration missing or you guys are using some custom theme there. i know different css is being generated. even if I force the same css, the result is not the same.

documentation site:
![image](https://user-images.githubusercontent.com/12803050/190406624-5b64b257-6712-4968-8215-28db6a357956.png)
`<span class="badge bg-secondary rounded-pill">On hold</span>`

my project:
![image](https://user-images.githubusercontent.com/12803050/190406846-6f844088-a124-4712-b2a5-4f66e5f11c05.png)
`<span class="badge badge-secondary badge-pill">Brasil - Estado - Cidade</span>`

forcing same css:
![image](https://user-images.githubusercontent.com/12803050/190407091-597caa47-12b7-4140-b81c-9edec92af4ca.png)
`<span class="badge bg-secondary rounded-pill">Brasil - Estado - Cidade</span>`

**Comment by stsrki** [comment]
Do you have ThemeProvider in your app?

**Comment by drma-dev** [comment]
I do not have. the only thing I do in the components is manipulate padding and marging.

**Comment by drma-dev** [comment]
What do I need to do to make my project look like the documentation site?

**Comment by stsrki** [comment]
We use ThemeProvider so I would say you also need to include it in your app.

**Comment by drma-dev** [comment]
```
private Theme theme = new Theme
        {
            ColorOptions = new ThemeColorOptions
            {
                Primary = "#9317E1",
                Secondary = "#A5A5A5",
                Success = "#4CAF50",
                Danger = "#F44336",
                Warning = "#FFEB3B",
                Info = "#00BCD4",
                Light = "#F5F5F5",
                Dark = "#424242"
            }
        };
```
OK. but what exactly is the configuration that you use? I can't make the components the same. because it's not just the colors that change, but also the classes used.

**Comment by stsrki** [comment]
You can find it here https://github.com/Megabit/Blazorise/blob/master/Documentation/Blazorise.Docs/App.razor#L40

**Comment by stsrki** [comment]
PS. Also, define a `LuminanceThreshold`.

**Comment by drma-dev** [comment]
I can't make it beautiful. I think I'll have to hire a designer to see this. hahaha
