### ISSUE TITLE
fontawesome - update the new icons

### ISSUE THREAD

**Issue by drma-dev** [Megabit/Blazorise#4112]
in the documentation, you already recommend using the new version 5.15.4, but the icons are out of date.

example:
![image](https://user-images.githubusercontent.com/12803050/190530049-3e13a4f3-bf5e-4d26-8ffd-30cfbccdcfe1.png)
![image](https://user-images.githubusercontent.com/12803050/190530136-f5d873e3-d386-4ce7-a4b1-8922e3569b90.png)

**Comment by stsrki** [comment]
They're made with `5.15.x` in mind, so that one should work. We can start thinking of adding additional icons in the future milestone.

**Comment by drma-dev** [comment]
do you mean this?
![image](https://user-images.githubusercontent.com/12803050/190631650-64adcb8f-63a9-46e5-b293-8b21a2614688.png)

I had already tried. but nothing appears. and that ::before does not appear inside the <i> like the other icons. I don't know what this is.
![image](https://user-images.githubusercontent.com/12803050/190631955-6aaa94c8-f625-494d-92e7-d95dce61f63f.png)

**Comment by drma-dev** [comment]
@stsrki whats the correct way to use new icoins?

**Comment by stsrki** [comment]
Since strongly types are not going to work then the only other way is to use it like

```
<Icon Name="@("fa-some-name")" />
```

**Comment by drma-dev** [comment]
> Since strongly types are not going to work then the only other way is to use it like
> 
> ```
> <Icon Name="@("fa-some-name")" />
> ```

that's exactly what i did. It is not working. I commented on the previous post.

**Comment by David-Moreira** [comment]
Hello @drma-dev 
Blazorise provides only a wrapper around how an icon should work for a specific provider with some helpers to make your life easier.

But as long as `FontAwesome` keeps working like it always did, based on an `i` html element, where all you need is to apply the class to the `i` element and have their css file updated for the icon you want to be using, then it's always possible for you to use their icons by providing the class in the `Name` `Parameter` just like @stsrki mentioned.

By looking at the icon you're trying, it seems like it is a "PRO Icon", meaning that you'll have to have access to a different css othen then the free provided version.

![image](https://user-images.githubusercontent.com/22283161/195993056-fc2d7877-f371-40cb-acee-4597d70df1e0.png)
 
![image](https://user-images.githubusercontent.com/22283161/195993016-547a41cc-9301-465d-a957-2c86e33e30e2.png)


I am closing this issue, feel free to reopen if this does not help.
