### ISSUE TITLE
PaginationLink Clicked is called even when PaginationItem is Disabled

### ISSUE THREAD

**Issue by Magehernan** [Megabit/Blazorise#4122]
**Describe the bug**
Is this a bug or is intended?
When Disabled parameter of PaginationItem is set Disabled = true and you click it invoke the PaginationLink Clicked method.

I look at the PaginationLink code 
https://github.com/Megabit/Blazorise/blob/8d6f80033612e5ec7e208a3a5c1807d807ec5858/Source/Blazorise/Components/Pagination/PaginationLink.razor.cs#L41-L44

it has the state of the PaginationItem but it not check if is disabled and call directly.

So the fix maybe is strait foward but i am not sure if it is a bug?

**Comment by stsrki** [comment]
Yeah, it is a bug.

**Comment by Magehernan** [comment]
@stsrki Ok, would you like it fix it and send a pull request?

**Comment by stsrki** [comment]
Wouldn't hurt :)

**Comment by Magehernan** [comment]
done
