### ISSUE TITLE
disabled button - generates a shadow

### ISSUE THREAD

**Issue by drma-dev** [Megabit/Blazorise#4125]
![image](https://user-images.githubusercontent.com/12803050/191983529-9d660258-dc51-41f5-87ed-491a8b5b7a3c.png)
when I disable a boot, it casts a shadow on the button. I think there's something wrong. shadow should only be generated when clicking the button.

**Comment by stsrki** [comment]
I agree it looks wrong. What provider do you use? BS4 or BS5?

**Comment by drma-dev** [comment]
@stsrki 4
