### ISSUE TITLE
Implement Microsoft Fluent UI

### ISSUE THREAD

**Issue by lonix1** [Megabit/Blazorise#4135]
Blazorise supports all the major themes, which is very nice!

But since this is a blazor library - a Microsoft product - it would be nice to also have a Microsoft theme as well. Then we can make apps that look like azure / office365 / windows / etc.

That design system is called "FAST", and the theme is called "FluentUI". There is already a [blazor library](https://github.com/microsoft/fast-blazor) for that, but it is small and lacks all the features in blazorise - importantly, it does not have layouts, grids, validations, breakpoints, css utilities, etc., etc., etc. It only has components.

**Comment by stsrki** [comment]
> blazor library - a Microsoft product

I wish we were Microsoft and that we had their resources.

Creating a new provider is time-consuming and hard to do. That's why we choose wisely which one to support, especially now that we need to be production ready. The Fluent/FAST is on our to-do list, but TBH, it will not be done soon. The following provider will be Tailwind and is planned for v1.2.

**Comment by stsrki** [comment]
> Do you think there is more need/users for tailwind? I'm interested to try it also.

A lot of people have requested it, and I can see from Twitter and other sources that it is on the rise. So I would be pretty confident it will also be quite popular in Blazorise. But I already know it will be hard to do 😅

> By the way, from your experience, do you think it would be possible for me to simply create custom css to make blazorise look more like fluentui, or is it more complex than that? Maybe I can build a custom css solution, until it's supported officially.

It is possible. A quick google showed me this

- https://disjfa.github.io/fluent-bootstrap/
- https://scottkuhl.medium.com/fluent-ui-for-bootstrap-3fd983d0c2e3

**Comment by stsrki** [comment]
Yeap, people keep missing what a robust framework Bootsrap is, and that it can be used to practically look like anything. At least with a little knowledge of CSS 😅
