### ISSUE TITLE
Modal not Closing with X in 1.1

### ISSUE THREAD

**Issue by HansMeiser234** [Megabit/Blazorise#4153]
Hello,

in Version 1.1  Modal is not Closing when Using X in right upper corner. Currently you have to add a close-button.
This happens also on your testpage: https://blazorise.com/docs/components/modal

Hans

**Comment by stsrki** [comment]
The issue is already fixed #4146. We'll release the patch ASAP.

**Comment by HansMeiser234** [comment]
Thanks you, no problem.
