### ISSUE TITLE
Breaking changes 1.1 for Autocomplete

### ISSUE THREAD

**Issue by TacoWannee** [Megabit/Blazorise#4156]
Autocomplete of version 1.1 
- does not know the .Focus() any more
- .Close(reason) is now .Close()

**Comment by andythomasdev** [comment]
Prior to 1.1.0, I was using the extension method `Clear()` on an Autocomplete object to clear out its selected value and text. After updating to 1.1.0, that method is gone. Everything I've tried to clear out the selected text in this field does not work. I've tried resetting the values of the fields bound to `SelectedText `and `SelectedValue`, and calling `Reload()` and `ResetSelected()`. Nothing has worked.

**Comment by stsrki** [comment]
@David-Moreira can you please look at all the missing APIs that we might change? Continue on the same PR as I already started #4157

**Comment by David-Moreira** [comment]
Hello,
It is not our policy to do these kind of breaking changes in minor versions. It was a miss on our side and we'll be re-adding these. 
Thank you for reporting.

As a temporary workaround for the `Clear()`, the following should work:

`@bind-CurrentSearch="search"`
```
    private Task Reset()
    {
        search = string.Empty;

        return autoCompleteRef.ResetSelected();
    }
```

**Comment by TacoWannee** [comment]
I reported about `Focus()` and `Close`, but see reply about `Clear()` are they related?

**Comment by stsrki** [comment]
> I reported about `Focus()` and `Close()`, but see reply about `Clear()` are they related?

Yes, we noticed other API changes.

What happened was that Autocomplete had made a significant rewrite internally, and as a result, we missed some API changes while reviewing PRs. Sorry for any inconvenience. The update will be released today.
