### ISSUE TITLE
ModalProvider / UseModalStructure = false => doesnt work

### ISSUE THREAD

**Issue by drma-dev** [Megabit/Blazorise#4161]
```
<Modal @ref="modal">
    <ModalContent Centered="true" Size="ModalSize.Default">
        <ModalHeader>
            <ModalTitle>@label</ModalTitle>
            <CloseButton />
        </ModalHeader>
        <ModalBody MaxHeight="70">
            asd
        </ModalBody>
        <ModalFooter>
            <Button Color="Color.Secondary" Clicked="@(()=>{modal?.Hide();})">Cancelar</Button>
            <Button Color="Color.Primary" Clicked="@Confirmar">Confirmar</Button>
        </ModalFooter>
    </ModalContent>
</Modal>
```

when I try to use my own structure (because I have some buttons in the footer), the popup does not appear. just a 1px high div.

**Comment by David-Moreira** [comment]
Hello,
you just need the Modal Internal Structure. 
Can you try just 
```
    <ModalContent Centered="true" Size="ModalSize.Default">
        <ModalHeader>
            <ModalTitle>@label</ModalTitle>
            <CloseButton />
        </ModalHeader>
        <ModalBody MaxHeight="70">
            asd
        </ModalBody>
        <ModalFooter>
            <Button Color="Color.Secondary" Clicked="@(()=>{modal?.Hide();})">Cancelar</Button>
            <Button Color="Color.Primary" Clicked="@Confirmar">Confirmar</Button>
        </ModalFooter>
    </ModalContent>
```

**Comment by drma-dev** [comment]
but if I don't use the ref, how am I going to dynamically close?

**Comment by David-Moreira** [comment]
Maybe we need to improve the docs with further examples, but here it is:
https://blazorise.com/docs/services/modal-provider

![image](https://user-images.githubusercontent.com/22283161/193351579-98219a62-1d0f-4104-89e4-bd0421cecc37.png)

`[Inject] public IModalService ModalService { get; set; }`

If I remember correctly you may close through the `ModalService`

**Comment by David-Moreira** [comment]
@drma-dev Also when you do `.Show` you get a `ModalInstance` back which also tracks the `ModalRef`.

I just noticed we'll have to document these behaviours better. We'll make the docs for `ModalProvider` better soon. :)

**Comment by drma-dev** [comment]
Cannot start from ModalContent. it gets all broken (it has to be a level down).
```
<ModalHeader>
    <ModalTitle>@Title</ModalTitle>
    <CloseButton />
</ModalHeader>
<ModalBody MaxHeight="70">
    asd
</ModalBody>
<ModalFooter>
    <Button Color="Color.Secondary" Clicked="@(async()=>{await ModalService.Hide();})">Cancelar</Button>
    <Button Color="Color.Primary" Clicked="@Confirmar">Confirmar</Button>
</ModalFooter>
```

but I managed to close dynamically. this instance that returns from the Show, doesn't work for me because I have to close it from within the modal.

**Comment by drma-dev** [comment]
`[Inject] public IModalService ModalService { get; set; } = default!;`
only one thing worries me. if I use this instance to close the modal, how do I know that I'm closing exactly this modal and not other possible modals that are open?

**Comment by David-Moreira** [comment]
> `[Inject] public IModalService ModalService { get; set; } = default!;` only one thing worries me. if I use this instance to close the modal, how do I know that I'm closing exactly this modal and not other possible modals that are open?

I was actually just thinking about this when you said you couldn't access the `ModalInstance`. One thing of note `ModalProvider` only keeps track of `Modals` opened by itself. So `ModalService.Hide();` closes the last opened `Modal`.

As for keeping the exact track of the `ModalInstance` you've opened, I guess currently one way is to just pass it down to your custom component and then just `ModalService.Hide(modalInstance);`? 

I don't think you'll ever have too many instances to keep track of... 

However it might be worth to make each `ModalInstance` a `CascadingParameter` actually. This way you could easilly access the correct instance with `[CascadingParameter] public ModalInstance modalInstance { get;set; }` in your own component.
Does this seem good to you? @stsrki what do you think, seems a good additional approach for these use cases, right?

**Comment by David-Moreira** [comment]
> I have a project (not working on it at the moment) that opens several modals in sequence. I had suggested this ModalProvider precisely because of it. As soon as I get back to this project, I'll test it and let you know.

Great in the meantime when I grab `ModalProvider` to do some improvements on the docs, I'll take a look at `ModalInstance` working as a `CascadingParameter`, this one we'd have to wait for v1.2 tough.

We'll happily take any feedback/suggestions you have on the component once you test it also!

**Comment by stsrki** [comment]
The `IModalService` is registered as scoped service, so each user has their own instance. When you open modals in a sequence, from UI/UX perspective, you can and will always close the last opened or front-visible modal. You cannot click on the modal behind it. And even if you want that behavior you can still use `ModalInstance`, as David already mentioned.

So, I don't see a reason for cascading `IModalService`.

**Comment by David-Moreira** [comment]
> ModalInstance

Correction it would be a cascading `ModalInstance`, which is what is unique for each `Modal`. But agreed for now, It seems the flexibility is enough.
