### ISSUE TITLE
Focus : Use dotnet inbuilt FocusAsync

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#4162]
Do we still need this implementation?
![image](https://user-images.githubusercontent.com/22283161/193407159-b30bec55-a027-4f82-9481-287f30683f29.png)

Will Microsoft's work all the same?
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-5.0#focus-an-element-1

**Comment by stsrki** [comment]
Probably not. We can use the dotnet version. Just need to reverse `scrollToElement`. In dotnet it is named `preventScroll`.

**Comment by stsrki** [comment]
From PR comment

> I have left our implementation because we already use the same utilities.focus from several places inside of the JS modules. And also, our implementation has the benefit that the element can be retrieved by ElementRef and ElementId, a kinda a fallback in some cases. So all in all it's better to leave it.
