### ISSUE TITLE
FluentValidation.DependencyInjectionExtensions is not installed as part of Blazorise.FluentValidation

### ISSUE THREAD

**Issue by robalexclark** [Megabit/Blazorise#4167]
the line in the docs for Blazourse.FluentValidation says that the following line is needed in Startup.cs

`services.AddValidatorsFromAssembly( typeof( App ).Assembly );`

But this line wont compile until the FluentValidation.DependencyInjectionExtensions nuget package is manually installed. Should this package not be a dependancy of the Blazorise.FluentValidation package?

**Comment by stsrki** [comment]
Blazorise only has core fluent package

```
<ItemGroup>
  <PackageReference Include="FluentValidation" Version="11.2.0" />
</ItemGroup>
```

We should probably add a note mentioning that `FluentValidation.DependencyInjectionExtensions` is also needed.

**Comment by David-Moreira** [comment]
Closing issue. Should have a new line to install the missing dependency on the next docs release.

Thanks for reporting.
