### ISSUE TITLE
Documentation site - Chart Component - lost of http post requests

### ISSUE THREAD

**Issue by syska** [Megabit/Blazorise#4168]
**Describe the bug**
When going to: https://blazorise.com/docs/extensions/chart

I see lots of http post reuqests:
![image](https://user-images.githubusercontent.com/317770/193604396-a55b745a-d24d-4052-84b4-5ef06b25f516.png)

And they just keeps going.

The `Events` part don't render ... just a blank canvas. Not sure what is supposed to be there.
![image](https://user-images.githubusercontent.com/317770/193604659-7cba9edb-6e87-4e91-a463-7958b26ce922.png)

Tested in both Chrome and Edge.

The request payload contains:
![image](https://user-images.githubusercontent.com/317770/193605749-0f3f8e51-9c62-49f5-80cc-b892ed1dd4c3.png)

**To Reproduce**
1. Go to https://blazorise.com/docs/extensions/chart
2. Look in the dev tools network tab.
3. Also scroll down to the 'Events' header.

**Expected behavior**
Not making so many reuqests and print the chart that might be missing.

**Screenshots**
See above screenshots.

**Comment by syska** [comment]
Just saw that this also happens on: https://blazorise.com/docs/components/layout and https://blazorise.com/docs/components/alert - The Component section.

For Services section:
* https://blazorise.com/docs/services/message-provider - No
* https://blazorise.com/docs/services/modal-provider - Yes
* https://blazorise.com/docs/services/notification-provider - No
* https://blazorise.com/docs/services/page-progress-provider - No

I'm fairly new to Blazor ... so maybe I have missed something obviously here.

**Comment by stsrki** [comment]
That's strange. @David-Moreira, can you look into this?

**Comment by David-Moreira** [comment]
Ok so the available protocols on our server for the connection are:
![image](https://user-images.githubusercontent.com/22283161/193696579-6a7e5743-595f-4810-abaa-cc808f375855.png)
So it's using the available Server Side Events, which means it's normal for the client <> server communication to be several http requests.

![image](https://user-images.githubusercontent.com/22283161/193697703-0cfa2085-139e-4881-b50f-b88cbbd5854d.png)

@stsrki if you'd like you can install the web socket protocol in the server, it's a bit better in my opinion. Keeps a single connection open with the client for chatting.

It's in Portuguese, but it should be here:
Under Windows functionalities... Internet Information Services... World Wide Web Services.... Development Tools
![Sem título](https://user-images.githubusercontent.com/22283161/193697201-0536d7c2-c5e2-4fae-823c-1d5737920f97.png)

With that explained, this just means, the http requests are just the blazor SignalR communication back and forth. 
Either some of the chart example has something in a loop or the chart itself does some re-rendering itself, causing the constant requests...

As for the missing chart might be a bug on our example generation in the docs or even the chart itself we'll take a look.

For the other cases it's the same explanation. Now it is indeed weird that there's so many requests, maybe there's some bug that's causing unecessary re-rendering? We'll be taking a look. Thanks for reporting. :)

**Comment by syska** [comment]
@David-Moreira 

I guess it make sense it the SSE ... just so often used to WebSockets being there :-) so you don't see them.

The amount of request was actually the worrying part ... I guess for a big site it add up to cpu cycles if Blazor Server is being used, like I guess it's here.

I will keep reporting if I find issues ... :-) Looking for a Blazor Component library, so the fact with such fast response is a good start.

**Comment by stsrki** [comment]
> @stsrki if you'd like you can install the web socket protocol in the server, it's a bit better in my opinion. Keeps a single connection open with the client for chatting.

Thanks, David. I have added WebSockets and it fixed that "chatty" page.
