### ISSUE TITLE
FluentValidation not working for unbound SelectList

### ISSUE THREAD

**Issue by robalexclark** [Megabit/Blazorise#4169]
I'm not sure whether this is a bug or a feature request.

The FluentValidation only works with a SelectList when using @bind-SelectedValue. When trying to use the SelectedValueChanged option an error is thrown:

`
System.NotImplementedException: Unable to determine the validator type.`

Given that this is not implemented - is it that FluentValidation does not handle this scenario?

**Comment by stsrki** [comment]
It's not a bug. It's actually how Blazor works. When you bind to a value, eg. `@bind-SelectedValue`, Blazor will do for you 

```cshtml
<Select SelectedValue="@model.Field" SelectedValueChanged="@(v => model.Field = v)">
```

But it will also assign a third parameter, `SelectedValueExpression`.

Which will end up as:

```cshtml
<Select SelectedValue="@model.Field" SelectedValueChanged="@(v => model.Field = v)" SelectedValueExpression="@(() => model.Field)">
```

That `*Expression` parameter tells us what field is used and how to validate it. So, if you don't `bind-*` you have to define `*Expression` yourself for validation to work properly.

**Comment by robalexclark** [comment]
That's works great - thanks - I had no idea abotu the SelectedValueExpression parameter
