### ISSUE TITLE
NumericEdit not work with decimal 0.0X

### ISSUE THREAD

**Issue by rgomezia** [Megabit/Blazorise#4172]
hi friends , i found this when try to digit decimals on blazorise material ,  when i try to digit 0.0X , the component delete the number after the dot , but if y digit 0.6 and after ditig 0 on left works  0,06.

the same thing hapend on Demo material on Numeric Fields

i want to work with more decimal , because its very important when yo work on Kg , grs.

ty for your time.

**Comment by stsrki** [comment]
Can you try setting the `Immediate="false"` on NumericEdit?
