### ISSUE TITLE
Snackbar work as a service

### ISSUE THREAD

**Issue by drma-dev** [Megabit/Blazorise#4173]
I recently discovered Snackbar, but it is very limited in use. you are required to physically put it on the page. Why can't you use it as a service (like Message)?

I know I could use Message, since it works as a service, but it's very ugly, big, fussy. haha. currently I use Toast from blazored, because it is more beautiful visually.

**Comment by stsrki** [comment]
Notification service is used as wrapper around the Snackbar

https://blazorise.com/docs/services/notification-provider

**Comment by drma-dev** [comment]
Why is the appearance the same as the message component?  there is no way to display without the title and the close button?

**Comment by stsrki** [comment]
It's not possible to control the close button, But the title can be changes with the second argument of the Info/Success method.
