### ISSUE TITLE
Datagrid Virtualize header text overlaps row

### ISSUE THREAD

**Issue by mtbayley** [Megabit/Blazorise#4175]
Viewable in the demo when scrolling.

![image](https://user-images.githubusercontent.com/34929316/194074028-8d67fabc-8c6c-47e8-869d-3bdc7889e078.png)

**Comment by David-Moreira** [comment]
Hello @mtbayley 
I am unable to reproduce on https://bootstrapdemo.blazorise.com/tests/datagrid/virtualize/in-memory
Can you make sure the cache is cleared? Any additional info you can provide us?
![chrome-capture-2022-9-8 (1)](https://user-images.githubusercontent.com/22283161/194719432-01687f0f-2966-498a-b723-3793874b20e3.gif)

**Comment by mtbayley** [comment]
Hi @David-Moreira 
This demo seems to work ok.
I am having a problem with the bootstrap 5 demo: https://bootstrapdemo.blazorise.com/tests/datagrid/virtualize/in-memory
Sorry for not detailing that
