### ISSUE TITLE
Dynamic tree with drag & drop

### ISSUE THREAD

**Issue by jerpic** [Megabit/Blazorise#4176]
Hello,

I would like to build a tree dynamically with data (items) from another zone. Do you think is possible with the Blazorise Drag & Drop component? Can we have DropZones inside DropZones in order to build a tree?

Best Regards,

**Comment by stsrki** [comment]
Have you tried it? In theory it should be possible because cascaded values of the drop zones should be respected and applied to the nearest descendant. Just make sure that you filter the right items for each zone.

**Comment by jerpic** [comment]
Hi @stsrki,

I have figured out about a potential solution to manage dropzone into dropzone.

Here is the code I produced for that (it's only a test) :


`
<DropContainer TItem="DropItem" Items="@_dropItems" ItemsFilter="@((item, dropZone) => item.Parent == Guid.Parse(dropZone))" ItemDropped="@ItemDropped" Flex="Flex.Wrap.Grow.Is1">
    <ChildContent>
        
        <DropZone @ref="_mainDropZone" TItem="DropItem" Name="bf847d37-2cab-4934-9818-194881334a86" AllowReorder Padding="Padding.Is3" Margin="Margin.Is3" Flex="Flex.Grow.Is1">
            <Heading Size="HeadingSize.Is4" Margin="Margin.Is3.FromBottom">Rule - ID : @_mainDropZone.Name</Heading>
        </DropZone>
        
    </ChildContent>
    <ItemTemplate>
       @{
           if (context is DropZone<DropItem>)
           {
                DropZone<DropItem> _newZone = (DropZone<DropItem>)context;
               
               <DropZone @ref="_newZone" TItem="DropItem" Name="@context.Id.ToString()" AllowReorder Padding="Padding.Is3" Margin="Margin.Is3" Flex="Flex.Grow.Is1">
                  <Heading Size="HeadingSize.Is5" Margin="Margin.Is3.FromBottom">@context.Title - ID :  @context.Id - Parent : @context.Parent</Heading>
               </DropZone>
           }
           else
           {
               <Card Shadow="Shadow.Default" Margin="Margin.Is3.OnY">
                   <CardBody>
                       @context.Title - ID : @context.Id
                   </CardBody>
               </Card>
           }
       }
       
    </ItemTemplate>
</DropContainer>

<Row>
    <Column ColumnSize="ColumnSize.Is6">
        <Alert Color="Color.Primary" Visible>
            OPERATORS
            <Button Color="Color.Success" Clicked='() => OnButtonOperatorClicked("AND")'>AND</Button>
            <Button Color="Color.Success" Clicked='() => OnButtonOperatorClicked("OR")'>OR</Button>
        </Alert>
    </Column>
    <Column ColumnSize="ColumnSize.Is6">
        <Alert Color="Color.Secondary" Visible>
            CRITERIAS
            <Button Color="Color.Success" Clicked='() => OnButtonCriteriaClicked()'>AND</Button>
        </Alert>
    </Column>
</Row>

@code {

    protected DropZone<DropItem> _mainDropZone;
    protected List<DropItem> _dropItems = new();
    
    
    protected interface  DropItem
    {
        public Guid Id { get; set; }
        public Guid Parent { get; set; }
        
        public string Title { get; set; }
   
       
    }

    protected class CriteriaItem : DropItem
    {
        public Guid Id { get; set; }
        public Guid Parent { get; set; }
        
        public string Title { get; set; }
        
    }
    
    protected class OperatorItem : DropZone<DropItem>, DropItem
    {
        public Guid Id { get; set; }
        public Guid Parent { get; set; }
        
        public string Title { get; set; }
    }
    

    protected void ItemDropped( DraggableDroppedEventArgs<DropItem> dropItem )
    {
        try
        {
            dropItem.Item.Parent = Guid.Parse(dropItem.DropZoneName);

            Console.WriteLine("-------------------------------------------------");
            foreach (var item in _dropItems)
            {
                Console.WriteLine($"Id : {item.Id} - Parent : {item.Parent}");
            }
        }
        catch (Exception exp)
        {
            Console.WriteLine(exp.Message);
        }
    }

    protected Task OnButtonOperatorClicked(string type)
    {
        
        OperatorItem item = new OperatorItem();
        item.Parent = Guid.Parse(_mainDropZone.Name);
        item.Title = type;
        item.Id = Guid.NewGuid();
        
        
        _dropItems.Add(item);
        
        Console.WriteLine($"Id : {item.Id} - Parent : {item.Parent}");
        
       return Task.CompletedTask;
    }

    
        
    protected Task OnButtonCriteriaClicked()
    {
        
        CriteriaItem item = new CriteriaItem();
        item.Parent = Guid.Parse(_mainDropZone.Name);
        item.Id = Guid.NewGuid();
        item.Title = "CRITERIA";
        
        
        _dropItems.Add(item);
        
        Console.WriteLine($"Id : {item.Id} - Parent : {item.Parent}");
        
        return Task.CompletedTask;
    }

}`

The objective is to to add (and then drag & drop) two kind of objects : CriteriaItem (simple object) and OperatorItem (it's a dropzone, it can include CriteriaItems).

You can add OperatorItem or CriteriaItem by clicking on the respective buttons.

Here is a screen copy : 

![image](https://user-images.githubusercontent.com/8591455/194248463-f8f1e469-5955-4e7a-bbf8-d8a7c93084a8.png)

That works as expected, but when I try to drag & drop a CriteriaItem or an OperatorItem to the root dropzone (Rule), I got an this exception : 

`warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Blazorise.DropContainer`1.CancelTransaction()
         at Blazorise._Draggable`1.OnDragEndHandler(DragEventArgs e)
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '9RGt5k1nhyH3UCEJZhEsvuh5bcUcis8yoaVomWHrEOI'.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Blazorise.DropContainer`1.CancelTransaction()
         at Blazorise._Draggable`1.OnDragEndHandler(DragEventArgs e)
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
`

Maybe is not the good approach and this is why I got the exception. Any help would be very much appreciated.

Best Regards,

**Comment by stsrki** [comment]
It seems like you missing a null check somewhere. Can you debug it?

Maybe like:

```
if ( dropItem?.Item?.Parent != null )
   dropItem.Item.Parent = something here;
```

**Comment by jerpic** [comment]
@stsrki 

I did it, same issue. It seems that the error occurs in the "OnDragEndHandler" therefore before to intercept it into the ItemDropped method.

**Comment by jerpic** [comment]
Hello @stsrki,

Hope you are well.

Any news on this issue please?

Best Regards,

**Comment by stsrki** [comment]
We still didn't investigate it. I will move it forward.

**Comment by stsrki** [comment]
I have added a couple of internal null checks on DropContainer, and it seems to be working. No errors now. But I have noticed that in some cases, I cannot drag and drop from one dropzone into another. Specifically when going from child to parent zone. Not sure if that is expected behavior for your use cases.

@jerpic, it would be great if you could test the PR before merging to confirm it is OK.

**Comment by jerpic** [comment]
Many thanks for your investigation.

In fact, the objective is to build a treeview with multiple levels (parent nodes/child nodes/etc..), each node can be reattached (with drag and drop) to another node (parent or child node). In addition to that, the treeview specially the nodes has to come from another treeview.

I will test the PR and come back to you.

Thanks again.

**Comment by jerpic** [comment]
Before testing the PR, I have upgraded to the last version of the Blazorise libs, and now I’m not able to reproduce the issue…. It’s a good news but a little bit strange.

**Comment by stsrki** [comment]
So, which version were you using before, and which are you using now?

**Comment by jerpic** [comment]
Hi,

Sorry, I did a mistake, I still have the issue. In fact, I think I got a better understanding about the issue.

You know in my example, you can add multiple « Operators AND / OR » which are « DropZone<DropItem> » and multiple « Criterias » which are « DropItem ». The issue appears when I try to move a « Criteria » from an « Operator » to another one. In this case the DropItem in the method (event) « ItemDropped » is not directly the selected item but the related dropzone (Operator).

Best Regards,
Jérôme

**Comment by stsrki** [comment]
I will continue and merge #4311. In case the error still happens in 1.1.4, you can open a new ticket.
