### ISSUE TITLE
why is only the last MessageService dialog displayed in one thread?

### ISSUE THREAD

**Issue by mshakurov** [Megabit/Blazorise#4181]
I'm not sure if this is a bug. But the documentation does not say anything about this behavior. Also, the obvious meaning of the "dialog box" is to delay the flow and wait for the user's action. Maybe IMessageService is not a "dialog box" or "modal" service?

**To Reproduce**
this code displays only one, the last message:

```
    private async Task ButtonClickedAsync()
    {
        await messageService.Info($"Button Clicked. 1", "Info");

        await messageService.Info($"Button Clicked. 2", "Info");
    }
```

**Expected behavior**
I expected this code to display two messages sequentially.

**Additional context**
If, after all, my suspicions are correct, and the IMessaeService methods (except Confirm) do not issue modal behavior, then what convenient service/component is there in the Blazorise library for modal notification? It is clear that I can write my own service for such tasks. But it seems to me that such a service is available in all known libraries for Blazor.
_(sorry for the confusing language or style of presentation)_

**Comment by stsrki** [comment]
Same as #4178. Are you two connected? 😄

**Comment by stsrki** [comment]
No worries. If the answer in the other thread doesn't work for you, please reopen it.

**Comment by David-Moreira** [comment]
(Crazy coincidences haha)

I am closing this issue again, as the issue seems resolved.

Feel free to re-open if it's not.
