### ISSUE TITLE
ModalService not awaiting 

### ISSUE THREAD

**Issue by f4n0** [Megabit/Blazorise#4184]
**Describe the bug**
Hi, I was expecting that modal service will work quite like the other providers. 
If I use the Await, it will wait till the modal close, am I missing something?

**Comment by David-Moreira** [comment]
Hello @f4n0 
Can you elaborate on what you're trying to do?

**Comment by f4n0** [comment]
Yes!

I would like to open a modal, but I need that the code will wait until the user closes this modal!

This modal is not blocking the code execution even if I add the await keyword!

**Comment by David-Moreira** [comment]
Hello,
It's not a blocking operation. You should rework your logic to listen to events or pass on a Func/Action for example depending on what you're trying to do.

**Comment by f4n0** [comment]
thanks!
I've added specific code to do that.
