### ISSUE TITLE
Carousel behaviour

### ISSUE THREAD

**Issue by ChrisGilson** [Megabit/Blazorise#4199]
I have the carousel working but with one big issue, every time an image slides out of view it is followed by a blank screen before the next image slides in. I am using just 3 images. Also, is there a way of slowing down the slide frequency?

**Comment by David-Moreira** [comment]
Hello @ChrisGilson 
We have a working example of a Carousel here : 
https://bootstrapdemo.blazorise.com/tests/carousel
So it's best you can provide us with a repro with the bug so we can take a look.

For the slide frequency, I believe you are looking for this:
![image](https://user-images.githubusercontent.com/22283161/195941710-7cfefa26-4edb-4a84-a652-cd00a70c070c.png)

It seems like it's missing on the docs, we'll add it.
