### ISSUE TITLE
Spacing issue on TreeView (Material only)

### ISSUE THREAD

**Issue by NJ-Brad** [Megabit/Blazorise#4209]
**Describe the bug**
Spacing of items before the first one with an expand icon are too far left
I added a few items above the expand icon to make the issue more visible
![image](https://user-images.githubusercontent.com/7256486/196276921-eb341f4d-d42c-4255-afa0-d19a2755cb49.png)

**To Reproduce**
Create a new project, following the instructions here: [https://blazorise.com/docs/extensions/treeview](https://blazorise.com/docs/extensions/treeview)
My project is a Web Assembly, with PWA selected

I have also seen the issue in the demo site for Material
![image](https://user-images.githubusercontent.com/7256486/196293366-cbc0b35a-60fc-4fb2-83cd-b50bcf78b7df.png)

**Expected behavior**
Should look like this

![image](https://user-images.githubusercontent.com/7256486/196277428-301144e9-a2d5-42a6-8d05-bc7c2e32245e.png)

**Screenshots**
Actual
![image](https://user-images.githubusercontent.com/7256486/196277601-56c866f4-c39a-4fd4-b7e1-4c6d60bc8a5f.png)

**Additional context**

**This is only an issue when using Material**

**Comment by stsrki** [comment]
Did you try to investigate with DevTools? I suspect another CSS style overrides one of the tree node styles.

**Comment by NJ-Brad** [comment]
The online demo shows the same behavior.  (Shown under To Reproduce)

**Comment by stsrki** [comment]
The problem is in the default `font-size` of material icons. It is too large and then it overflows the space used by the tree node.

Try to apply the CSS

```
.tree-view-icon i.material-icons {
  font-size: 1.3rem !important;
}
```
