### ISSUE TITLE
Only one detail row opened at time

### ISSUE THREAD

**Issue by JCQuirozL** [Megabit/Blazorise#4210]
**Describe the bug**
Is there any chance to have just one detailRow opened at time? I mean, when I click a Row a its DetailRow opens and is fine, but then I try to open another different row its detailRow opens too (good!), BUT, the previous Row remians OPENED too, what I'm trying to achieve is to close the previous DetailRow when I click a new Row.

This is my DetailRowTrigger event
``
DetailRowTrigger="@((e)=>e.Item.Policy == selectedItem?.Policy)"
``

**Comment by David-Moreira** [comment]
Hello @JCQuirozL 
`DetailRow` has been made to be quite flexible in the latest versions. 
There's a bunch of options you can set in the callback arguments:
![image](https://user-images.githubusercontent.com/22283161/196524244-52581e52-25b6-4104-8ad0-af27be6c9fdc.png)

Try setting `Single` to true. Let us know if this helps.

**Comment by JCQuirozL** [comment]
This is just what I was looking for! Thnxs!

We can close the issue
