### ISSUE TITLE
Pointer issue when using Numeric Picker with GroupSeparator

### ISSUE THREAD

**Issue by benny-adiwijaya** [Megabit/Blazorise#4215]
Hi, when edit data using numeric picker with group separator from the middle digit, the pointer always move to the last digit. Is there a way to solve this? Thanks

**Comment by stsrki** [comment]
The problem comes from how the Blazor refreshes the UI after each update. So to workaround around it, you can:

1. Disable update on each key with `Immediate="false"`
2. Postpone an update with `Debounce="true" DebounceInterval="500"`

Hope it helps.

**Comment by David-Moreira** [comment]
@stsrki 
Can you also clarify this one in relation to #3543 ?

**Comment by stsrki** [comment]
Well, not much to clarify. This is primarily a Blazor rendering/state/tracking problem. Unless we don't use EventCallback, Blazor will always trigger re-render and then update the picker's internal Value. And in turn, the picker will think that it needs to update and so it will move the cursor to the end.

**Comment by David-Moreira** [comment]
Gotcha, Just figuring out that number 2 proposed workaround will not be an option in the future.
