### ISSUE TITLE
Issue with Modal and Button

### ISSUE THREAD

**Issue by HansMeiser234** [Megabit/Blazorise#4219]
Hello,

have a small problem with Modal and Buttons discovered.  Blazorise Package Version is 1.1.2
I have an image of problem here:  https://ibb.co/bgDnYsB
Content of Modal is just a Copy of Content of MainPage. There is a table with two Selectlists and Buttons to move items from left to right side and reverse.
I noticed that buttons in modal only have color on MouseOver. You can see it in image, the lower button looks ok because the not captured Mousearrow is above. the upper button looks empty.
Reason is the embedding in table with class tag in table tag.
Following shows wrong buttons if you put it in ModalBody

```
<table class="table">
<tr>
<td>
<button class="btn btn-primary" @onclick="(() => commit_job())"  >&gt;&gt;</button><br /><button class="btn btn-primary" @onclick="(() => commit_job_reverse())"  >&lt;&lt;</button>
</td>
</tr>
</table>
```
If you remove the >>class="table"<< then the buttons will have expected color. I noticed this currently only in Modal. Same Code is used in Mainpage and as image shows there is no Colorbug on buttons.

Is this expected and issue on my side or a kind of bug?

Thanks,
Hans

**Comment by stsrki** [comment]
Seems to me that something is overriding the style of the button. Can you inspect in dev tools and see what might be the problem?

**Comment by HansMeiser234** [comment]
I can see that attribute background is missing and contrast seems to be different, but i dont know where it is coming from.
https://ibb.co/VB6RGnf

Sorry, i cant tell better. I never used the devtools...

**Comment by HansMeiser234** [comment]
The code for buttons looks identical in main and modal.
https://ibb.co/B29KJ74
I noticed if i uncheck the background-color in .table then color of buttons is visible. (red arrow in image)
I dont know why, i just use standard blazor and blazorise packages. it seems the attribut is not overwritten when in modal.
Thanks.

**Comment by stsrki** [comment]
It seems that the color is coming from Bootstrap CSS. Maybe you can try adding it explicitly with `Background="Background.Primary"`.
