### ISSUE TITLE
Autocomplete regression since 1.1.0

### ISSUE THREAD

**Issue by guillaumebaril** [Megabit/Blazorise#4221]
**Describe the bug**
Setting selected text manually in Autocomplete is not working anymore

**To Reproduce**
```
<Autocomplete TItem="string"
              TValue="string"
              Data="@_strings"
              TextField="@(( item ) => item)"
              ValueField="@(( item ) => item)"
              @bind-SelectedText="_selText">
</Autocomplete>

<Button Clicked="@OnClick">Click me</Button>

@code {

    private List<string> _strings = new List<string>()
    {
        "this is line 1",
        "this is line 2",
        "this is line 3"
    };

    private string _selText = null;

    private void OnClick()
    {
        _selText = "hello";
    }
}
```

**Expected behavior**
When you click on "Click me", aucomplete component should have "hello" text.

**Additional context**
It is not working in 1.1.1 neither in 1.1.2

**Comment by David-Moreira** [comment]
Have you tried setting Freetyping to true? The value is outside the bound data values.

**Comment by guillaumebaril** [comment]
I think the issue is that we were messing a lot with the value directly in SelectedValueChanged, because in 1.0.6 the onlostfocus was not being triggered correctly and we had to find a workaround. I guess we are going to have to refactor our code for 1.1.2.

**Comment by David-Moreira** [comment]
Alright keep us posted if something does not seem to be working quite right to you.
