### ISSUE TITLE
DataGridAggregate Average behavior for null values

### ISSUE THREAD

**Issue by TacoWannee** [Megabit/Blazorise#4226]
The average behavior for a columns is now that null-values are taken as 0. 
I would like to have an average over all not-null values. So null-values are ignored.
![image](https://user-images.githubusercontent.com/108428600/197504042-5c4a45eb-bd2f-4377-9e1c-32397a8167d2.png)
As in this example I want an average off 99 instead of 66

**Comment by David-Moreira** [comment]
Hello @TacoWannee 
unfortunately I don't believe that is the way to go.
If there are 3 records then the **AVG** should be calculcated from all the existing universe. 

I understand null can represent an absence of value, but it does not make sense to act as if the record does not exist and therefore not made part of the `AggregationFunction`. If we'd make that change, then other users could argue they'd want the reverse behaviour.

If it makes sense for your use case, then what you can do is that you can provide your own `AggregationFunction` and there you can ignore null values just like you want.

Oh and here's our internal Average Function if you want to base yourself in it:
```
public static object Average( IEnumerable<TItem> Data, DataGridColumn<TItem> column )
{
    if ( Data == null )
        return 0;

    if ( !ValidNumericTypes.Contains( column.GetValueType() ) )
        return 0;

    return ( from item in Data
             let value = column.GetValue( item )
             select Convert.ToDecimal( value ) ).Average();
}
```

Let us know if this helps.

**Comment by TacoWannee** [comment]
Maybe you can add new aggregate function beside the `Average`, that is names like `AverageNotNull` ??

**Comment by David-Moreira** [comment]
> The custom `AggregateFunction` is a way to achieve this, but elaborate if you need it in multiple columns. Maybe you can add new aggregate function beside the `Average`, that is names like `AverageNotNull` ??

Also why would it be elaborate? You write the function once and then pass in the delegate to the various columns that need the custom `AggregateFunction`.

I know that in an ideal world libraries can do everything for us!! But I just don't think this is the way to go here. :)

Please reconsider and see if the provided solution works for you @TacoWannee

**Comment by TacoWannee** [comment]
Ok, I can live with that
