### ISSUE TITLE
Markdown component supports `previewRender`

### ISSUE THREAD

**Issue by realLiangshiwei** [Megabit/Blazorise#4229]
**Is your feature request related to a problem? Please describe.**

I'm trying to do ABP CMS dynamic widget for BlazorUI, but I had a problem when to custom markdown preview.

**Describe the solution you'd like**

It will be helpful if the markdown component supports `previewRender` property.

https://github.com/Ionaru/easy-markdown-editor#configuration

![image](https://user-images.githubusercontent.com/16813853/197805710-fc8c1fe3-38f1-4acb-be8d-278bb1910617.png)

**Comment by stsrki** [comment]
It's not a bad feature to have. We can add it as part of the 1.2, considering it is a new API.
