### ISSUE TITLE
How can I stop live data streaming on a live chart, after 20 seconds for example?

### ISSUE THREAD

**Issue by mut9bu** [Megabit/Blazorise#4242]

**Comment by stsrki** [comment]
Sorry for not answering sooner. The feature will be done in 1.2 as part of #4258

**Comment by mut9bu** [comment]
Thank you for the  feedback :-)  I have few suggestions for this option. Will send as a feature suggestion

**Comment by stsrki** [comment]
I have added Pause and Play functions(in my branch still). Do you think that is enough for this feature, or do you have another idea?

**Comment by mut9bu** [comment]
Hello
For the first step, definitly its OK :-) Thank you so much for your quick response.

**Comment by mut9bu** [comment]
OK one more idea perhaps:
If you have a continous live chart (where data is flowing over a long time) it is OK that the data stream comes from left side of the chart area and flows from left to right continously. 
But if you have atime limited Live Chart (lets say 20 data points) and it is presentable in the X axis range completely (X=0...20) then it is prefered generaly that the data points (line curve) is drawn from left to right and the X axis is not moving. I think this is better to track the line for each new value. On a flowing X axis itis difficult to track the line change because the line is completely moving. Just a suggestion,as I am working a lot of with charts.

**Comment by stsrki** [comment]
> OK one more idea perhaps:
> If you have a continous live chart (where data is flowing over a long time) it is OK that the data stream comes from left side of the chart area and flows from left to right continously.
> But if you have atime limited Live Chart (lets say 20 data points) and it is presentable in the X axis range completely (X=0...20) then it is prefered generaly that the data points (line curve) is drawn from left to right and the X axis is not moving. I think this is better to track the line for each new value. On a flowing X axis itis difficult to track the line change because the line is completely moving. Just a suggestion,as I am working a lot of with charts.

Do you have any working examples that I can look for inspiration for this feature?
