### ISSUE TITLE
Memory leak in ThemeCache

### ISSUE THREAD

**Issue by gjhommersom** [Megabit/Blazorise#4254]
**Describe the bug**
The ThemeCache class is leaking memory because the ammount of cached themes is ever increasing.

**To Reproduce**
1. Wrap the app in a theme.
```
<Blazorise.ThemeProvider Theme="@theme">
  ...
</Blazorise.ThemeProvider>

@code{
    private Theme theme = new Theme();
}
```
2. Start the application
3. Refresh the page continuously and monitor memory usage.

**Expected behavior**
I expect memory usage to remain stable.

**Screenshots**
Before cleanup:
![image](https://user-images.githubusercontent.com/28047460/199435760-161d12db-3cbe-4082-b733-f842e2c19dbe.png)

After cleanup:
![image](https://user-images.githubusercontent.com/28047460/199435902-3f8d76bf-7d71-47c7-a276-a3e963a08859.png)

All these themes are exactly the same.

**Additional context**
This is caused due to a flaw in the equality comparison. Whenever it is attempted to retrieve styles the provided `Theme` has 1 event handler attached to the `Changed` event. The `Theme` objects in the cache however have 2 handlers attached. Therefor no cached `Theme` can be found and a new one is inserted. This is not limited to the `Changed` event. Modifying any property can cause this issue.

```
ThemeCache cache = new ThemeCache(new(null, options => { }));
for (int i = 0; i < 12; i++)
{
    Theme theme = new Theme();
    if (!cache.TryGetStylesFromCache(theme, out _))
    {
        cache.CacheStyles(theme, "abc");
        theme.Changed += (_, _) => { }; // Comment this line and it works as expected.
    }
}
```

Another issue is that the `UncacheTheme()` method doesn't remove anything from the `variableCache` or `styleCache`.  This seems to happen when the `Theme` that was added to a dictionary is modified afterwards. This happens when a second event listener is added (not sure where). Again, this is not limited to the `Changed` event but can happen for any propery.

```
Dictionary<Theme, string> styleCache = new();
var theme = new Theme();
styleCache.Add(theme, "");
theme.Black = "not black"; // Comment this line and it works as expected.
styleCache.Remove(styleCache.FirstOrDefault().Key);
```

**Workaround**
Can be avoided by disabling the cache in the options as such:
```
services.AddBlazorise(options =>
{
     options.ThemeCacheSize = 0;
});
```

**Comment by stsrki** [comment]
@David-Moreira, as we have discussed. Try to add a new ignore attribute, possibly `IgnoreEqualityAttribute`, and then try to use it with source generators to override the record Equality.

Otherwise, override the record Equality and check every field manually.

**Comment by David-Moreira** [comment]
@gjhommersom

Thank you for reporting.
Really appreciated for doing all the digging.
