### ISSUE TITLE
Suggestions for Blazorise Live Chart option (Stop, Pause, Rewind, Forward functions)

### ISSUE THREAD

**Issue by mut9bu** [Megabit/Blazorise#4260]
**Is your feature request related to a problem? Please describe.**
No I have suggestions (see below)

**Describe the solution you'd like**
1) The Live Chart should be stoppable any time if required. (Let say I have just 20 measuring points (each per 1 second) and I want that the X time axis movement can be stopped programatically.

2) There should be also a "Pause" function. That means I should be able to pause the chart if I want to look to the curve in detail, but the chart should collect values in the background,so that when I restart the chart I should be able to see the actual chart streaming.

3) In our language there is a saying " requesting is free of charge" :-) So I have a last request:
It would be even better If I would be able go back to the charts streaming history. (I mean rewind and forwardbuttons after I have stopped the chart.

Sorry for requesting so much :-)

**Comment by stsrki** [comment]
I'm working in Pause and Play API. Well see about the rest.
