### ISSUE TITLE
FilePicker documentation issue

### ISSUE THREAD

**Issue by NJ-Brad** [Megabit/Blazorise#4263]
**Describe the bug**
In the documentation for the FilePicker component the default value for AutoReset is documented as true.  When I use the component without specifying a value, it behaves as if the default is false.  I am not sure which needs to be changed (documentation or code)
[https://blazorise.com/docs/components/file-picker](https://blazorise.com/docs/components/file-picker)

**Comment by David-Moreira** [comment]
Documentation should be wrong. Thanks for reporting.
The idea of `FilePicker` is to have visual cue's of what's happening to your files from start to end.
Where ending the full upload, it will just display the current status of all the files, Uploaded or With Error, but not reset by default.
