### ISSUE TITLE
Forum down?

### ISSUE THREAD

**Issue by MeestorX** [Megabit/Blazorise#4274]
Probably not the right place to post this, but is the support forum down? Doesn't seem to be allowing new issues.
https://support.blazorise.com

**Comment by stsrki** [comment]
I've just checked, and the forum is working. The new issues are only allowed for our commercial users.

**Comment by MeestorX** [comment]
Ah. Might be an idea to disable the button for community or popup an alert? There's no errors or warnings or anything that come up when adding an issue, the page just sits there doing nothing.

**Comment by stsrki** [comment]
We have created a new ticket to solve this issue. Thanks for letting us know.
