### ISSUE TITLE
Unable to customize date separator of DatePicker

### ISSUE THREAD

**Issue by enisn** [Megabit/Blazorise#4278]
**Describe the bug**
While using DatePicker with `SelectionMode="DateInputSelectionMode.Range"`, there is a `to` word between dates and it's not localized. And I couldn't find any way to customize it. I want to make it dash `-`   instead of `to`.

Currently: `1.1.2020 to 1.1.2022`
What I want to see: `1.1.2020 - 1.1.2022`

**To Reproduce**
1. Create a DatePicker with range mode
  ```html
  <DatePicker TValue="DateTime?"
                                    SelectionMode="DateInputSelectionMode.Range" />
  ```
2. Choose 2 dates and see the separator is `to`
![datepicker-separator](https://user-images.githubusercontent.com/23705418/200493376-7fdbe6dc-b314-4284-aa61-d97489064ea6.gif)

**Expected behavior**
It should be localized or it should be customized.

**Screenshots**
![datepicker-separator](https://user-images.githubusercontent.com/23705418/200493376-7fdbe6dc-b314-4284-aa61-d97489064ea6.gif)

**Additional context**

**Comment by stsrki** [comment]
This feature is going to be a part of the 1.2 release; see #4238

PS. I love the look of your app theme.
