### ISSUE TITLE
NotificationService won't show correctly

### ISSUE THREAD

**Issue by Shraned** [Megabit/Blazorise#4279]
HI,

In my Index.razor i've put the code that is in the documentation for this service.
The bar won't show in the page, it adds a bar under the page with a cross and disappear after a while.
I can't reproduce the documentation sample ...
the code i used :

```
_" @page "/"

<PageTitle>Index</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.

<SurveyPrompt Title="How is Blazor working for you?" />

<Alert Color="Color.Success" Visible>
    <AlertMessage>Well done!</AlertMessage>
    <AlertDescription>You successfully read this important alert message.</AlertDescription>
</Alert>
<Button Color="Color.Warning" Clicked="@ShowWarningNotification">Show alert!</Button>
@code {
    [Inject] INotificationService NotificationService { get; set; }

    Task ShowWarningNotification()
    {
        return NotificationService.Warning("This is a simple notification message!", "Hello");
    }
}"
```

![image](https://user-images.githubusercontent.com/109082491/200505913-1cb1e36f-a05c-420f-9041-715485e25125.png)

**Comment by stsrki** [comment]
Notifications are based on the Snackbar component. I assume you don't have CSS included in your project. See here https://blazorise.com/docs/extensions/snackbar

**Comment by Shraned** [comment]
Absolutely,
Just add it in my Layout.cshtml and works like a charm.
Thank you for your answer.

Is it missing in the documentation for NotificationService ? 😉

Best Regards,

Olivier Lefèvre

MB Tech  - https://www.mbtech.fr
Mobile : 07 83 98 48 87
Mail: ***@***.***
________________________________
De : Mladen Macanović ***@***.***>
Envoyé : mardi 8 novembre 2022 08:56
À : Megabit/Blazorise ***@***.***>
Cc : Olivier Lefèvre ***@***.***>; Author ***@***.***>
Objet : Re: [Megabit/Blazorise] NotificationService won't show correctly (Issue #4279)


Notifications are based on the Snackbar component. I assume you don't have CSS included in your project. See here https://blazorise.com/docs/extensions/snackbar

**Comment by stsrki** [comment]
It is. We will add it soon, before 1.1.3 release.
