### ISSUE TITLE
DataGrid causes exception as soon as Nuget package is installed.

### ISSUE THREAD

**Issue by BigWinston** [Megabit/Blazorise#4284]
**Describe the bug**
After installing the DataGrid using the Nuget package manager (v1.1.3.1) and running (without modifuying any code at all, not even adding an import), I get the below exception on the following line, when running in debug mode.  When not debugging, I just get a message saying the server failed to start.  I have tried adding the using statement in my _Imports.razor but this made no difference.

**[Program.cs]**
builder.Services.AddBlazorise(options =>{options.Immediate = true;}).AddBootstrap5Providers().AddFontAwesomeIcons();

**[EXCEPTION]**
System.TypeLoadException: 'Method 'BarDropdownToggleDisabled' in type 'Blazorise.Bootstrap5.Bootstrap5ClassProvider' from assembly 'Blazorise.Bootstrap5, Version=1.1.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'

**To Reproduce**
1. Follow instructions here: https://blazorise.com/docs/extensions/datagrid/getting-started
2. After Installation, and before Imports step, run/debug the application
3. The app is halted and the exception shown

**Expected behavior**
No exception.  I have verified that no exception occurs when using Blazorise.Material and Blazorise.Bulma - things seem to work ok with these variants.

**Additional context**
Blazorise.Bootstrap5 v1.1.2
Blazorise.Icons.FontAwesome v1.1.2
Datagrid v1.1.3.1

**Comment by David-Moreira** [comment]
@BigWinston is it possible that you can keep the version in sync across the Blazorise packages? Can you upgrade bs5/font awesome to **1.1.3**?

**Comment by stsrki** [comment]
You should be on the same version for all Blazorise NuGet packages; in this case, a v1.1.3.1.

**Comment by David-Moreira** [comment]
@BigWinston once again please try the provided resolutions:
![image](https://user-images.githubusercontent.com/22283161/203178008-093295e1-f6df-4510-8a07-3428f32b0123.png)

If these don't work, please provide a Repro. Thanks.
