### ISSUE TITLE
Splitter Extension

### ISSUE THREAD

**Issue by smfields** [Megabit/Blazorise#4286]
Creating this feature to track work on adding an extension that wraps [Split.js](https://split.js.org/).

I've already got a version of this wrapper implemented called [BlazorSplit](https://blazor-split.smfields.net/). This issue is just tracking the work to port that independent library into Blazorise.

Couple questions I've got about this wrapper:

1. What do we want to call the component? We could call it Split like I do in my version, but I'm open to other naming ideas if they're more descriptive.
2. I've considered trying to replicate the same functionality natively in Blazor without wrapping a Javascript library. Do we think there's value in that? Personally, I'd be concerned about the performance of sending the pointer events over the web socket in the case of serverside Blazor, but I also know that some people really like native Blazor components and avoid Javascript when possible.

**Comment by stsrki** [comment]
1, We can call it `Blazorise.Splitter`. I think it is a fairly common name.
2. In the past, I would be all for native Blazor, but nowadays, I see the benefits of JavaScript. When it works out of the box the users should not care how it works behind. It will be a lot faster for the user experience, and the JS library is already fool-proof, so a lot of issues are already handled. So, we can go with JS. As long as it is abstract enough, we can always rewrite it in Blazor in the future.

The general API can be

```html
<Splitter>
  <SplitterSection></SplitterSection>
  <SplitterSection></SplitterSection>
</Splitter>
```

**Comment by stsrki** [comment]
Hey, @smfields. Do you need help with the new component? Or do you want us to move forward? Thanks.

**Comment by smfields** [comment]
Hey @stsrki, sorry I just haven't had the time to work on this lately. I've pushed everything I had to a branch that you're welcome to take over and move forward with on your own.

https://github.com/smfields/Blazorise/tree/master-split-extension

**Comment by stsrki** [comment]
No worries. You did a great job. Can you just create a PR from your branch into our `master`? It would be a lot easier to continue from where you stopped.
