### ISSUE TITLE
DataGrid Pagination Size is not applied properly

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#4290]
https://support.blazorise.com/issues/76

**Comment by David-Moreira** [comment]
So, just so we're in the same page.

Changes are:
- Consider globally defined Theme's `PaginationOptions.Size` if `PagerOptions.ButtonSize` is not defined.
  - If neither are defined, the default is applied, ofc
- The "Page Selector" which only shows below Tablet, should also consider the defined Size.

I was thinking, should we provide a Template for the "PageSelector" in **v1.2**? 
![image](https://user-images.githubusercontent.com/22283161/201520845-59f7a7a7-d30d-4a22-90ab-2a14d86fb748.png)

**Comment by stsrki** [comment]
> Changes are:
> 
> * Consider globally defined Theme's `PaginationOptions.Size` if `PagerOptions.ButtonSize` is not defined.
>   
>   * If neither are defined, the default is applied, ofc
> * The "Page Selector" which only shows below Tablet, should also consider the defined Size.

Sounds good to me.

> I was thinking, should we provide a Template for the "PageSelector" in v1.2?

We already have all other page templates so it is a good idea to have PageSelectorTemplate also.
