### ISSUE TITLE
Markdown : Able to set upload url after processing a file

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#4335]
Example print :
OnImageUploadedEnded is called in the exact moment upload is ended, **but before an URL can be set,** for example, as a result of a remote api call that returns the UploadedUrl
![image](https://user-images.githubusercontent.com/22283161/204109595-061135ad-9dbc-4cc1-a964-7e890333aacb.png)

Investigate:
![image](https://user-images.githubusercontent.com/22283161/204109589-62b22878-a398-4bd5-b4bb-e830c73aa301.png)

Or @stsrki's suggestion with TaskCompletionSource

**Comment by stsrki** [comment]
I would prefer to try to make it work in 1,1, if possible, without introducing a new API. Try with TCS and see how it goes.
