### ISSUE TITLE
Modal: scrolling page closes modal

### ISSUE THREAD

**Issue by ArneCools** [Megabit/Blazorise#4341]
**Describe the bug**
When modal and page both have a scrollbar. Scrolling the modal with scrollbar closes the modal

**To Reproduce**
1. Go to https://blazorise.com/docs/components/modal
2. Open example modal
3. Make screen small enough so modal has to be scrolled
4. Scroll by clicking scrollbar

**Expected behavior**
Modal has to stay open, but it closes

**Comment by David-Moreira** [comment]
@stsrki do you know the reasoning behind this condition?
`ElementId == elementId` isn't that the element itself? Why would that be a condition to close?

![image](https://user-images.githubusercontent.com/22283161/206315016-44f5158b-faea-4d11-906a-5de95c05da38.png)

**Comment by David-Moreira** [comment]
Would a backdrop click provide the same `ElementId`, that seems quite strange. I will test it out. But a possible fix for this, would be to change that condition, since the scroll click does successfully return the same `ElementId`, at least from my first initial test / debug. 

I would argue that it should be `ElementId != elementId` or just remove it all together and leave only the other condition, but maybe there could be a reason for it to be there...

**Comment by stsrki** [comment]
I know the reason. Because the `modal` element itself takes an entire screen space.

![image](https://user-images.githubusercontent.com/900302/206418096-3f9656b0-eda8-45ca-809b-c5ddc63fc8b4.png)

**Comment by David-Moreira** [comment]
I see.. If that's the case it's gonna be hard to differentiate a scroll bar click because it's all the same I guess O.o

**Comment by David-Moreira** [comment]
We can investigate a little more, but I might argue, if a user wants it to not close on scroll click then he should disable the Background Click Closing option?

**Comment by David-Moreira** [comment]
@stsrki what do you think here?

**Comment by stsrki** [comment]
We can see how the BS detects it in JavaScript and then try to recreate it in Blazorise.

**Comment by David-Moreira** [comment]
In their case it seems to work fine with this:
![image](https://user-images.githubusercontent.com/22283161/218180794-5f4bba41-9cb3-456c-b591-a9ca7ca159f6.png)
where currentTarget is the backdrop and target can be anything other then the backdrop like the actual modal itself. Not sure it applies to our use case.
