### ISSUE TITLE
DatePicker bind-Date not updating

### ISSUE THREAD

**Issue by rmills963** [Megabit/Blazorise#4342]
**Describe the bug**
the bind-Date field on the date picker component only updates the UI

**To Reproduce**
1. Add a DateTime variable
2. Add the date picker component, binding the date to the variable
3. Run the app
4. The date changes on the UI but not the variable

**Expected behavior**
The new date that was picked should be printed to the console, but only the original date is ever shown.
The component itself shows the new date but my variable never updates.

Below is the code for the date picker component I used to test.

```
@using Blazorise

<DatePicker @bind-Date="dt" @onchange="@(() => Console.WriteLine(dt))" />

@code {
    DateTime dt = DateTime.Now;
}
```

**Comment by stsrki** [comment]
You shouldn't combine `@bind-Date` and `@onchange`. DatePicker is already using `@onchange` internally so when you try to use it as a parameter you're basically overriding the internal and how it updates the Date. If you really want to have a callback to print to the console then use two-way binding without the `@bind-*` part.

```razor
@using Blazorise

<DatePicker TValue="DateTime" Date="@dt" DateChanged="@OnDateChanged" />

@code {
    DateTime dt = DateTime.Now;

    Task OnDateChanged(DateTime newDate)
    {
        dt = newDate;
        return Task.CompletedTask;
    }
}
```

**Comment by rmills963** [comment]
Okay, I see now. I have to use the bind-date for the fluent validation extension to determine which validator to use, but I wanted another trigger on change. I can move that trigger elsewhere since the FV doesn't seem to play as nice with manual bindings.

**Comment by stsrki** [comment]
For validation to work you need to add a third `*Expression` parameter. This once usually gets assigned by the Blazor when `@bind-*` is used.

```razor
@using Blazorise

<DatePicker TValue="DateTime" Date="@dt" DateChanged="@OnDateChanged" DateExpression="@(()=>dt)" />

@code {
    DateTime dt = DateTime.Now;

    Task OnDateChanged(DateTime newDate)
    {
        dt = newDate;
        Console.WriteLine(dt);
        return Task.CompletedTask;
    }
}
```

or 

`DateExpression="@(()=>yourModel.SomeFieldToValidate)"`
