### ISSUE TITLE
DatePicker doesn't work when has DatesChanged

### ISSUE THREAD

**Issue by PavloParafiloCricut** [Megabit/Blazorise#4356]
**Describe the bug**
DatePicker is not working when DatesChanged="OnTestDatesChanged" is added - visually anything is selected after clicking, DatesChanged is triggered with default values , without DatesChanged it works good. 

"Blazorise" Version="1.1.3.1" 

**To Reproduce**

`    <DatePicker TValue="DateOnly?"
                                        Width="Width.Is100"
                                        Dates="_testDateFilterValue"
                                        Placeholder="Select range..."
                                        DatesChanged="OnTestDatesChanged"
                                        SelectionMode="DateInputSelectionMode.Range" />`

```
        public IReadOnlyList<DateOnly?> _testDateFilterValue = new List<DateOnly?>();

        public Task OnTestDatesChanged(IReadOnlyList<DateOnly?> vals)
        {
            return Task.CompletedTask;
        }
```

**Comment by stsrki** [comment]
Yoo didn't update your variable.

Add this:

```diff
public IReadOnlyList<DateOnly?> _testDateFilterValue = new List<DateOnly?>();

public Task OnTestDatesChanged(IReadOnlyList<DateOnly?> vals)
{
+    _testDateFilterValue  = vals;
    return Task.CompletedTask;
}
```

**Comment by PavloParafiloCricut** [comment]
Yes, it works, thanks
