### ISSUE TITLE
Multicolor AutoComplete badges

### ISSUE THREAD

**Issue by WolfgangKluge** [Megabit/Blazorise#4358]
**Is your feature request related to a problem? Please describe.**
I want to style autocomplete-badges differently (based on the respective badge).

**Describe the solution you'd like**
The property `MultipleBadgeColor` could be a function that is called for every badge that should be rendered (to be backward compatible, maybe `MultipleBadgeColors` - or to be consistent `BadgeColorField`).

**Comment by WolfgangKluge** [comment]
Hmm. I want to be able to add a tooltip for a single badge, too. So I redefine my request.

I want to fully control the rendering of the badges so that I'm able to set different colors or e.g. icons instead of the badge or as stated above, to add a tooltip control around every single badge..

So instead (or in addition to) `MultiBadgeColors`, I want to have a `BadgeContent`-property that controls the rendering.

**Comment by stsrki** [comment]
BadgeTemplate, or BadgeContent seems like a best way to customize it.

**Comment by David-Moreira** [comment]
`BadgeTemplate` seems good. 

I also would take the breaking change for `MultipleBadgeColor` in v2.0, seems worthy. @stsrki ?

As a reminder we should use `Template` as the suffix :
![image](https://user-images.githubusercontent.com/22283161/206059917-1db239a0-ea3b-419c-a9cf-559551e416c5.png)

**Comment by stsrki** [comment]
> `BadgeTemplate` seems good.

I agree.
