### ISSUE TITLE
Docs: mention nameof is not required for DataGrid

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#4359]
@stsrki  Any chance the documentation can be updated to mention that nameof() is not required for Nested Fields. 
https://blazorise.com/docs/extensions/datagrid/getting-started

It was not clear going through the documentation and could have saved me many hours until I decided to check for Issues in Github :)

Thanks

_Originally posted by @ssinghm32 in https://github.com/Megabit/Blazorise/issues/1906#issuecomment-1335914102_

**Comment by bkea** [comment]
@stsrki Complex types are still not showing up in Data Grid after following your suggestion.  There are no errors or cell data.  The column headings are there.  Any ideas?

```
@page "/Loadinglist"
@using TESTBlazor1.Data

<h3>Loading List</h3>
<DataGrid TItem="LoadData"
          Data="@loadList">
    <DataGridColumns>
        <DataGridColumn Field="@nameof(LoadData.loadId)" Caption="#" />
        <DataGridColumn Field="@nameof(LoadData.caliber)" Caption="Caliber" />
        <DataGridColumn TItem="LoadData" Field="powder.powderName" Caption="Powder" />
        <DataGridColumn TItem="LoadData" Field="bullet.bulletName" Caption="Bullet" />
        <DataGridColumn TItem="LoadData" Field="bullet.bulletWT" Caption="Bullet WT" />
        <DataGridColumn Field="@nameof(LoadData.chargeWT)" Caption="Charge" />
    </DataGridColumns>
</DataGrid>

@code {
    [Inject]
    public GetLoadData getLoadData { get; set; }
    private List<LoadData>? loadList;

    protected override async Task OnInitializedAsync()
    {
        loadList = await getLoadData.GetDataAsync();
        await base.OnInitializedAsync();
    }
}
```
```
namespace TESTBlazor1.Data
{
    public class LoadData
    {
        public int loadId { get; set; } = new int();
        public string caliber { get; set; } =  string.Empty;
        public PowderInfo powder { get; set; } = new PowderInfo();
        public BulletInfo bullet { get; set; } = new BulletInfo();
        public decimal chargeWT { get; set; } = new decimal();
        public string comments { get; set; } = string.Empty;
    }
}
```
```
namespace TESTBlazor1.Data
{
    public class BulletInfo
    {
        public int bulletID { get; set; } = new int();
        public string bulletManufacture { get; set; } = string.Empty;
        public string bulletName { get; set; } = string.Empty;
        public decimal bulletWT { get; set; } = decimal.Zero;
        public int bulletProductId { get; set; } = new int();

    }
}
```
```
namespace TESTBlazor1.Data
{
    public class PowderInfo
    {
        public int powderID { get; set; } = new int();
        public string powderManufacture { get; set; } = string.Empty;
        public string powderName { get; set; } = string.Empty;
    }
}
```

**Comment by stsrki** [comment]
If the columns header shows and the data is not, that means there is no full data loaded. I can see that your field and JSON data are not named the same. It's possible that is the reason why it cannot deserialise it properly.

Can you debug the `loadList` and see what you have there?

![image](https://user-images.githubusercontent.com/900302/209624098-5424d96c-17b9-4398-babe-9454c1bc504d.png)

**Comment by bkea** [comment]
Geez oh fricken petes (pardon my language).  I'm concentrating on the code when the test data (and the programmer) was bad.  But now I am wondering if I am breaking the pattern.  Should I be manipulating the code to fit the model or create a specialized model to fit the view (MVVC).  

Thank you for the assist!!!!

**Comment by stsrki** [comment]
Well, it depends. If you don't control the data, then you should adjust the models. If you control everything, then you should start by renaming models and data based on the best conventions.

For example, models and fields always must be written in upper case first letter.

```cs
namespace TESTBlazor1.Data
{
    public class LoadData
    {
        public int LoadId { get; set; } = new int();
        public string Caliber { get; set; } =  string.Empty;
        public PowderInfo Powder { get; set; } = new PowderInfo();
        public BulletInfo Bullet { get; set; } = new BulletInfo();
        public decimal ChargeWT { get; set; } = new decimal(); // prefer full name over WT. Nobody else besides you know what WT stands for.
        public string Comments { get; set; } = string.Empty;
    }
}
```

For JSON, it is best to make it a lowercase the first letter. This is a convention and it can be controlled with serialization options on startup.

```json
[
  {
    "loadId": 1,
    "caliber": "22-250",
    "powderInfo": {
      "powderID": 1,
      "powderManufacture": "Hodgdons",
      "powderName": "H4350"
    },
    ...
  }
]
```

**Comment by stsrki** [comment]
Make it as part of #4438
