### ISSUE TITLE
Validation: add support for IValidatableObject

### ISSUE THREAD

**Issue by bodeg** [Megabit/Blazorise#4360]
Sorry if this is a total newbie question...

Does Blazorise validation support IValidatableObject ?

When I use `DataAnnotationsValidator` the `IValidatableObject.Validate` works fine.
I couldn't make Blazorise Validation component to call `IValidatableObject.Validate`

**Comment by stsrki** [comment]
Not sure if we support it. Our DataAnnotations validators follow the original Blazor validation, but it is not 100% the same. We have a different use case, and API is a little different, so they can never be the same. 

I am looking at the [aspnetcore repo](https://github.com/dotnet/aspnetcore/search?q=IValidatableObject) for IValidatableObject, but all I can see it the mention of it in the Mvc parts.

**Comment by bodeg** [comment]
`IValidatableObject `is using to validate the whole object and not a specific field.

When using `DataAnnotationsValidator`, it first check the property validations, like Required, StringLength etc. 
and if they passed, then it check the `IValidatableObject.Validate`

`IValidatableObject.Validate` may return a list of fields that not pass the check + error message

**Comment by stsrki** [comment]
Just a quick update. I already have a working code in my private branch. But I cannot decide on the right behavior. With my current implementation, it works automatically if validation detects the `IValidatableObject`.

The problem comes when circular validation references other fields and the validation rule changes dynamically.

Like in the following example, if we switch the `Company.UseAlphaCode` `true` and `false`. It will not trigger re-validation unless we go and type into the input field.

```razor
<Validations Model="@Company" Mode="ValidationMode.Auto">
    <Validation>
        <Field>
            <FieldLabel>Name</FieldLabel>
            <FieldBody>
                <TextEdit @bind-Text="@Company.Name" />
            </FieldBody>
        </Field>
    </Validation>
    <Validation>
        <Field>
            <FieldLabel>Description</FieldLabel>
            <FieldBody>
                <TextEdit @bind-Text="@Company.Description" />
            </FieldBody>
        </Field>
    </Validation>
    <Field>
        <Switch @bind-Checked="@Company.UseAlphaCode">Use AlphaCode</Switch>
    </Field>
    <Fields>
        <Validation>
            <Field>
                <FieldLabel>AlphaCode</FieldLabel>
                <FieldBody>
                    <TextEdit @bind-Text="@Company.AlphaCode" />
                </FieldBody>
            </Field>
        </Validation>
        <Validation>
            <Field>
                <FieldLabel>BetaCode</FieldLabel>
                <FieldBody>
                    <TextEdit @bind-Text="@Company.BetaCode" />
                </FieldBody>
            </Field>
        </Validation>
    </Fields>
</Validations>

@code {
  CompanyInfo Company = new CompanyInfo()
  {
      UseAlphaCode = true,
  };
  
  public class CompanyInfo : IValidatableObject
  {
      [Required( ErrorMessage = "Name is required" )]
      public string Name { get; set; }
  
      [Required( ErrorMessage = "Description is required" )]
      public string Description { get; set; }
  
      public bool UseAlphaCode { get; set; }
  
      public string AlphaCode { get; set; }
  
      public string BetaCode { get; set; }
  
      [Range( 0, 999.99 )]
      public decimal Price { get; set; }
  
      public IEnumerable<ValidationResult> Validate( ValidationContext validationContext )
      {
          if ( UseAlphaCode )
          {
              if ( String.IsNullOrWhiteSpace( AlphaCode ) )
              {
                  yield return new ValidationResult( "AlphaCode is required", new[] { "AlphaCode" } );
              }
          }
          else
          {
              if ( String.IsNullOrWhiteSpace( BetaCode ) )
              {
                  yield return new ValidationResult( "BetaCode is required", new[] { "BetaCode" } );
              }
          }
      }
  }
}
```
