### ISSUE TITLE
How to update value in multiple AutoComplete components

### ISSUE THREAD

**Issue by FranKieSator** [Megabit/Blazorise#4362]
I'm trying to have multiple Autocomplete components for adding address.

I have AutoComplete for:
- Street
- City
- Zip
- Country

When I enter any value (FreeTyping) to any of the fields, ReadData handler is called, API is called and it searches (on server) and returns found results (Address model). I select one...

Now, the question - how can I update Text and Value fields in all components?

As a workaround, I found:
- setting each AutoComplete.Search=found address (which gives me warning that I shall not use Search param outside of component)
- calling each AutoComplete.Reload - that causes that each AutoComplete is reloaded, text is set but it also causes to trigger ReadData handler to be called for each AutoComplete = not efficient.

Is there any other way how to set selected item for multiple AutoCompletes without reloading them?
Interesting thing is, that if I set .Search property it doesn't change the text, until I mouse over over the AutoComplete - I tried calling StateHasChanged but that didn't cause AutoComplete field to refresh.

**Comment by David-Moreira** [comment]
The warning is correct you should not try to set the parameter directly. Something like `@bind-Search` should work However I believe what you are looking for is the `AddMultipleTextAndValue`? Can you try it? Let us know if it works properly.
https://blazorise.com/docs/extensions/autocomplete

![image](https://user-images.githubusercontent.com/22283161/206061129-d619d8dd-a133-4c22-8680-5e81599e29c7.png)

**Comment by FranKieSator** [comment]
Thanks for the reply, I've tried but with no success.

Here's my Autocomplete for City and Street (there are also for zip, country...)

```
<Autocomplete @ref="CityAutocomplete"
                      TItem="AddressModel"
                      TValue="int"
                      ReadData="(e) => OnHandleReadData(e, isCity:true)"
                      Data="@AddressList"
                      Debounce="true"
                      DebounceInterval="500"
                      Validator="(e)=>{ValidationService.ValidateName(e);}"
                      TextField="@(( item ) => item.City)"
                      ValueField="@(( item ) => item.Id)"
                      Placeholder="@Localizer.Get("SelectCity")"
                      Multiple="false"
                      FreeTyping                           
                      SelectedValueChanged="async (val)=>{ await UpdateAddressModel(val, isCity:true);}">
        </Autocomplete>
<Autocomplete @ref="StreetAutocomplete"
                      TItem="AddressModel"
                      TValue="int"
                      ReadData="(e) => OnHandleReadData(e, isStreet:true)"
                      Data="@AddressList"
                      Validator="(e)=>{ValidationService.ValidateName(e);}"
                      TextField="@(( item ) => item.Street)"
                      ValueField="@(( item ) => item.Id)"
                      Placeholder="@Localizer.Get("SelectStreet")"
                      Multiple="false"
                      FreeTyping
                      Debounce="true"
                      DebounceInterval="500"
                      @bind-Search="@SelectedStreet"
                      @bind-SelectedText="@SelectedStreet"
                      SelectedValueChanged="async (val)=>{ await UpdateAddressModel(val, isStreet:true);}">
                     >
        </Autocomplete>
```


basically, what I do: I enter city, it offers me list of cities, I select one and it calls UpdateAddressModel where I tried (as suggested):

```
  SelectedStreet = AddressList.FirstOrDefault().Street;   //here I assign Street name from found AddressList based on the selected City
  await StreetAutocomplete.AddMultipleTextAndValue(AddressId);
```

however, when I do this, City is populated but Street autocomplete stays empty. I also tried to debug it and it hits both the lines.

**Comment by David-Moreira** [comment]
Hello @FranKieSator

`AddMultipleTextAndValue` should not be used when `Multiple="false"`. The method is reserved for when `Autocomplete` is on Multiple Selection.

You've failed to provide a complete repro... I had to fill in some code... So it's not going to be exactly like yours, but this worked just fine.
Once I type something on first Autocomplete, the second updates with the "Awesome" Street.

```
<Autocomplete @ref="CityAutocomplete"
              TItem="AddressModel"
              TValue="int"
              Data="@AddressList"
              Debounce="true"
              DebounceInterval="500"
              TextField="@(( item ) => item.City)"
              ValueField="@(( item ) => item.Id)"
              Multiple="false"
              FreeTyping
              SelectedValueChanged="async (val)=>{ await UpdateAddressModel(val, isCity:true);}">
</Autocomplete>
<Autocomplete @ref="StreetAutocomplete"
              TItem="AddressModel"
              TValue="int"
              Data="@AddressList"
              TextField="@(( item ) => item.Street)"
              ValueField="@(( item ) => item.Id)"
              Multiple="false"
              FreeTyping
              Debounce="true"
              DebounceInterval="500"
              @bind-Search="@SelectedStreet"
              @bind-SelectedText="@SelectedStreet"
              SelectedValueChanged="async (val)=>{ await UpdateAddressModel(val, isStreet:true);}">
    >
</Autocomplete>

@code {
    private Autocomplete<AddressModel, int> CityAutocomplete;
    private Autocomplete<AddressModel, int> StreetAutocomplete;

    List<AddressModel> AddressList = new()
    {
        new()
        {
            Id = 1,
            City = "City"
        },
        new()
        {
            Id = 2,
            Street = "Awesome"
        }
    };
    private string SelectedStreet;
    private int selectedStreetValue;
    private class AddressModel
    {
        public int Id { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
    }

    Task UpdateAddressModel( int value, bool isStreet = false, bool isCity = false )
    {
        if ( isCity )
        {
            SelectedStreet = "Awesome";
        }
        return Task.CompletedTask;
    }
}
```
