### ISSUE TITLE
Preselection of ListView-Element is not working

### ISSUE THREAD

**Issue by WolfgangKluge** [Megabit/Blazorise#4364]
**Describe the bug**
I have a ListView and want to preselect an entry. This is not working as expected.

**To Reproduce**
Here's a simple example
```razor

<Blazorise.Components.ListView
    Data="@data"
    @bind-SelectedItem="@selected"
    TextField="@(item => item)"
    ValueField="@(item => item)"
    Mode="ListGroupMode.Selectable" />

@code {
    private string[] data = new[] { "A", "B", "C" };
    private string selected = "B";
}
```

Entry B should have a class name that indicates its selection state (as if I select any of the items).

**Screenshots**
Actual
![image](https://user-images.githubusercontent.com/639482/205978570-a129591a-ab76-4f80-a7fd-138abf65058c.png)

Expected
![image](https://user-images.githubusercontent.com/639482/205978621-8914eca0-e589-4336-9343-4a709ed694c6.png)

**Comment by WolfgangKluge** [comment]
Oh. I see that it's never working.
Not only the initial value is refreshed but also changes are not registered.

```razor
<Blazorise.Components.ListView
    Data="@data"
    @bind-SelectedItem="@selected"
    TextField="@(item => item)"
    ValueField="@(item => item)"
    Mode="ListGroupMode.Selectable" />

<Blazorise.Components.ListView
    Data="@data"
    @bind-SelectedItem="@selected"
    TextField="@(item => item)"
    ValueField="@(item => item)"
    Mode="ListGroupMode.Selectable" />


@code {
    private string[] data = new[] { "A", "B", "C" };
    private string selected = "B";
}
```

The two lists are not in sync if I click any of the elements.

**Comment by WolfgangKluge** [comment]
To get the sync working, one solution could be to add ` SelectedItem="@GetItemValue(SelectedItem)"` to https://github.com/Megabit/Blazorise/blob/master/Source/Extensions/Blazorise.Components/ListView.razor#L2

**Comment by WolfgangKluge** [comment]
That solves only the sync part (=changes after initialization are recognized).
The fix does not solve the problem with the preselection (initial value is still ignored).

**Comment by David-Moreira** [comment]
@WolfgangKluge

**Comment by WolfgangKluge** [comment]
@David-Moreira yeah, it works now. (I tested before, but my that test was wrong, sorry)

**Comment by David-Moreira** [comment]
Ok, great! :)
