### ISSUE TITLE
On the DataGrid component, is there a 'FormFieldColumnSize' parameter?

### ISSUE THREAD

**Issue by ms4sman** [Megabit/Blazorise#4365]
On the DataGrid component, is there a 'FormFieldColumnSize' parameter similar to the 'PopupFieldColumnSize' that would allow fields on the Form Edit Mode to be set to a custom width instead of defaulting to 6 or half?

I saw the PopupFieldColumnSize parameter used in one of the demo samples and assumed there would be something similar for the Form Edit Mode but there doesn't seem to be.

Thanks!

**Comment by David-Moreira** [comment]
It shouldn't be.
Maybe it would be better to introduce a `EditFieldColumnSize` that would work for both? Deprecate `PopupFieldColumnSize` in the future?

**Comment by ms4sman** [comment]
I wondered about something like that. Since you are only using one Edit
Mode at a time for a given DataTable, having the setting apply to both
really won't hurt anything.

**Comment by stsrki** [comment]
`EditFieldColumnSize` seems like a good name.
