### ISSUE TITLE
Possible to customize the Modal for the Popup Edit Mode on the DataGrid Component?

### ISSUE THREAD

**Issue by ms4sman** [Megabit/Blazorise#4366]
Is it possible to customize the properties of the Modal that gets created when using the Popup Edit Mode for the DataGrid?

Specifically, I'm hoping to be able to make the modal wider or even full-screen if possible. But I didn't see anything in the templates for customizing the Modal itself. Just the Title on the Modal.

Thanks!

**Comment by stsrki** [comment]
There is a `PopupSize` parameter on DataGrid. Have you tried it?

**Comment by ms4sman** [comment]
Welp, now I feel silly. I promise, I did look for this before asking, but I must have missed it. Sorry about that!

Thank you for the quick, helpful response! Much appreciated.

**Comment by stsrki** [comment]
No worries :)

Closing now.
