### ISSUE TITLE
Autocomplete with empty SelectedValues

### ISSUE THREAD

**Issue by WolfgangKluge** [Megabit/Blazorise#4372]
**Describe the bug**
I have an Autocomplete-Element with `SelectionMode=Multiple` and want to display several badges.
When I change the `SelectedValues` property, it works as expected - except when I want to clear the values.

Then, the last value is shown.

**To Reproduce**
I've tested several ways

```razor
<Autocomplete
    AutoPreSelect
    CloseOnSelection
    Data="@(new[] {
        ("A", "a"),
        ("B", "b"),
        ("C", "c")
    })"
    SelectionMode="AutocompleteSelectionMode.Multiple"
    MinLength="0"
    TItem="(string Name, string Value)"
    TValue="string"
    TextField="@(item => item.Name)"
    ValueField="@(item => item.Value)"
    SelectedValues="@Values.Split(' ').ToList()"
    SelectedValuesChanged="@(values => Values = string.Join(" ", values))"
/>

<Autocomplete
    AutoPreSelect
    CloseOnSelection
    Data="@(new[] {
        ("A", "a"),
        ("B", "b"),
        ("C", "c")
    })"
    SelectionMode="AutocompleteSelectionMode.Multiple"
    MinLength="0"
    TItem="(string Name, string Value)"
    TValue="string"
    TextField="@(item => item.Name)"
    ValueField="@(item => item.Value)"
    @bind-SelectedValues="@Values2"
/>

<Button Clicked="@(() => { Values = "a b"; Values2.Clear(); Values2.AddRange(Values.Split(' ')); })">A, B</Button>
<Button Clicked="@(() => { Values = "a"; Values2.Clear(); Values2.AddRange(Values.Split(' ')); })">A</Button>
<Button Clicked="@(() => { Values = ""; Values2.Clear(); })">[empty]</Button>
```

(click on buttons 1 and 2 - whenever you click on \[empty\], the autocomplete elements should be empty)

Both ways will work, when I change
https://github.com/Megabit/Blazorise/blob/05b04636335cc8749cd1ce9ba7ed638b7027bcba/Source/Extensions/Blazorise.Components/Autocomplete.razor.cs#L206
to
`if ( selectedValuesParamChanged && selectedValuesParam != null && !Data.IsNullOrEmpty() )`

and
https://github.com/Megabit/Blazorise/blob/05b04636335cc8749cd1ce9ba7ed638b7027bcba/Source/Extensions/Blazorise.Components/Autocomplete.razor.cs#L218
to
`if ( texts != null && !SelectedTexts.AreEqualOrdered( texts ) )`

but I'm unsure if that's sufficient (and not too much).

-----
As a workaround, I call `Clear()` of the Autocomplete instance whenever the value changes, but that's not very convenient.

**Comment by WolfgangKluge** [comment]
Hmm. My workaround does not work if I select the same value two times in a row (so not only inconvenient, but also buggy).

**Comment by David-Moreira** [comment]
But for the meantime, and even tought it's not convenient, checking for empty and calling the `Autocomplete.Clear()` should be the workaround.

**Comment by WolfgangKluge** [comment]
For a workaround I use `AddMultipleTextAndValue("x");` (any improper value) and `Clear();` thereafter.
In that way I get it working even with 2 times the same value (2 times the second button in the example above)

**Comment by WolfgangKluge** [comment]
Ok, here's the `Clear`-only workaround:

```razor
<Autocomplete @ref="ac"
    AutoPreSelect
    CloseOnSelection
    Data="@(new[] {
        ("A", "a"),
        ("B", "b"),
        ("C", "c")
    })"
    SelectionMode="AutocompleteSelectionMode.Multiple"
    MinLength="0"
    TItem="(string Name, string Value)"
    TValue="string"
    TextField="@(item => item.Name)"
    ValueField="@(item => item.Value)"
    @bind-SelectedValues="@Values"
/>

<Button Clicked="@(async () => { await ac!.Clear(); Values ??= new(); Values.Clear(); Values.Add("a"); Values.Add("b"); })">A, B</Button>
<Button Clicked="@(async () => { await ac!.Clear(); Values ??= new(); Values.Clear(); Values.Add("a"); })">A</Button>
<Button Clicked="@(async () => { await ac!.Clear(); Values ??= new(); Values.Clear(); })">[none]</Button>

@code {
    private List<string> Values = new();
    private Autocomplete<(string, string), string>? ac;
}
```

Seems to work whenever the value changes - but if you hit one of the buttons twice, it wont.

So my "new" workaround is to call `AddMultipleTextAndValue` before. Like so

```razor
<Button Clicked="@(async () => { await ac!.AddMultipleTextAndValue("x"); await ac!.Clear(); Values ??= new(); Values.Clear(); Values.Add("a"); Values.Add("b"); })">A, B</Button>
<Button Clicked="@(async () => { await ac!.AddMultipleTextAndValue("x"); await ac!.Clear(); Values ??= new(); Values.Clear(); Values.Add("a"); })">A</Button>
<Button Clicked="@(async () => { await ac!.AddMultipleTextAndValue("x"); await ac!.Clear(); Values ??= new(); Values.Clear(); })">[none]</Button>
```
