### ISSUE TITLE
Set FilterMethod on individual DataGrid columns

### ISSUE THREAD

**Issue by asser-dk** [Megabit/Blazorise#4373]
Would it be possible to add the ability to set the FilterMethod on the individual columns when you use column filtering in a Data Grid? Occasionally I make a grid where I would like different filtering methods for each column (just the same as the ones you set for the entire table) and writing custom filters feels a bit tedious.

**Comment by David-Moreira** [comment]
So `FilterMethod="DataGridFilterMethod.Contains"` on each column right? Seems like a good feature to me.

**Comment by stsrki** [comment]
We have that already. Look for the `CustomFilter` parameter on DataGridColumn.

**Comment by David-Moreira** [comment]
If I can interject on behalf of OP. I believe that he acknowledges the existence of Custom Filter, but would like just a quick way to define simple filters for the columns.
> `and writing custom filters feels a bit tedious.`

Of course OP could just write a few generic method filters himself and then just do `CustomFilter="MyCustomFilter"` `CustomFilter="MyOtherCustomFilter"`  `CustomFilter="MyContainsFilter"` and so on... on each column.

**Comment by stsrki** [comment]
I see. We have `FilterMethod` on `DataGrid`, but making it available on the columns would make it much better, Makes sense.

**Comment by stsrki** [comment]
We can just use existing filters

```
public enum DataGridFilterMethod
{
    Contains,
    StartsWith,
    EndsWith,
    Equals,
    NotEquals,
}
```

**Comment by David-Moreira** [comment]
Right, that's a given, I meant this feature:
![image](https://user-images.githubusercontent.com/22283161/206417987-5d7aa014-0f45-42b3-9db6-92db1b9561d4.png)
[
http://www.guriddo.net/demo/guriddojs/
- Searching and Filtering
  - [Support for in and not in operandsNew](http://www.guriddo.net/demo/guriddojs/searching/searchin/index.html)](http://www.guriddo.net/demo/guriddojs/searching/searchin/index.html)

**Comment by David-Moreira** [comment]
Hello,

The `FilterMethod` should be a simpler task to implemtn if you're not yet used to our code base. We're always open to accept community contributions. :)
https://github.com/Megabit/Blazorise/wiki/Contributing

I believe the other suggested feature is a nice to have too, do you agree @stsrki may we go ahead and open a seperate feature request with it? And @asser-dk could also grab that one if he wants to.

**Comment by stsrki** [comment]
I think we already have an open feature for that dropdown filter method. But it not, please open it.

Regarding the `FilterMethod`, just add it on a column and then make it a higher priority over the one that we already have on a DataGrid. eg `=> Column?.FilterMethod ?? FilterMethod;`

**Comment by David-Moreira** [comment]
@asser-dk allocated to you for the time being. 
If you by any chance you are unable to work on this, it's fine. Just let us know. :)

**Comment by asser-dk** [comment]
Gotcha. Thanks :)

**Comment by crazycatcoder** [comment]
Hi  @David-Moreira , @asser-dk !

Up above, David mentioned a feature: Sometimes Grids have a little icon by the side of each Header Column which let's you choose which column to filter and with which type of Filter.

So, what is the status of this desired feature?  I have a project for it and was wondering if it is finished or in beta or somehow available?

Also, @asser-dk, you mentioned you have made some custom FilterTemplate 's , do you have any code sample you could share.  
I am newer to Blazorise, and am used to a datagrid's per column "column filtering method multi-select button" being much more plug and play ready( like for DevExpress, material, etc ).

Please let me know,
thanks
