### ISSUE TITLE
Modals not closing when clicked on backdrop

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#4379]
This only happens when more than one modal is opened.

To reproduce, go to https://bootstrapdemo.blazorise.com/tests/modals

1. Open any modal
2. Click on the `Show second modal` button
3. Click on the backdrop
4. After the second modal closes, click on the backdrop again

The modal should be closed.

**Comment by Bobbar** [comment]
Looks like it started somewhere between 78de281 and a4764e5d.  I can't nail down what change did it.

The tryClose within the closeable.js module seems to be passing an ID for the wrong component/backdrop, one that should be closed already.  Then the IsSafeToClose condition within Modal.cs fails.

**Comment by David-Moreira** [comment]
THanks for taking the time to help us solve the issue. It's helpful to know the range of commits where it might have been working properly before.
