### ISSUE TITLE
Keyboard input to select from autocomplete

### ISSUE THREAD

**Issue by jerchap** [Megabit/Blazorise#4385]
Is there a way to set up autocomplete so that up/down arrows then enter or tab can select something from the drop down?  So far I have only been able to get the first record to select on enter, using the ConfirmKey attribute.

**Comment by David-Moreira** [comment]
I think this should pretty much work.
And You can configure various confirm keys in the ConfirmKey parameter.

Can you clarify what is not working as you'd expect?

**Comment by stsrki** [comment]
The bootstrap version should have no effect. Can you tell us what Blazorise version you have?
