### ISSUE TITLE
DataGrid : Nested field throws error when creating new item

### ISSUE THREAD

**Issue by Weidmann16** [Megabit/Blazorise#4392]
I am currently creating a datagrid with the DataGridCommandColumn buttons.
![image](https://user-images.githubusercontent.com/74007151/208117368-3d532f15-f08c-45a2-b4f5-08d0cb8ec24b.png)

I use a model as follows:
![image](https://user-images.githubusercontent.com/74007151/208116788-236a4205-09d4-442c-a156-514a4b7da932.png)
![image](https://user-images.githubusercontent.com/74007151/208120559-8fc3f809-60f6-44ae-87e0-27bfd3cf31a7.png)
![image](https://user-images.githubusercontent.com/74007151/208121107-3700684f-78b7-49a1-9e89-fe176917240f.png)

When I go to save the data, the column does not recognize the model, and the datagrid crashes
![image](https://user-images.githubusercontent.com/74007151/208121512-c6d551f5-7ba4-4fcf-814c-804587d0c820.png)

I would like to know how to solve this problem, so that when saving, the model is sent completely to the method
![image](https://user-images.githubusercontent.com/74007151/208120788-3ff41bfe-6a96-4c63-9e5f-289921340080.png)

I will be very attentive to your comments

**Comment by David-Moreira** [comment]
Hello, it would be helpful to post the call stack.
Are you sure it's not throwing on your own code? `e.Item.EstadoCuidad` is null, no? You are trying to acess `idEstado` and assign a value.

**Comment by David-Moreira** [comment]
Hello,
In the future, please provide us with a repro, or at least code that's able to be copied, that makes it easier for us to quickly troubleshoot the exact same scenario as you.

Eitherway, I just took the time to reproduce your issue and It was in fact an error being thrown in `Datagrid`. This is because you're binding a Field/Prop from your Class to a `DataGridColumn` that can be null, the `Ciudad.EstadoCiudad`. So when Datagrid tries to set the new value internally, it throws.

For this, we provide a `NewItemCreator` parameter which you can use to provide the `Datagrid` with the correct instantion of your object.

So it would look something like this: Take a look at `NewItemCreator="NewCiudad"`
As a suggestion, you can also promptly assign default starting values here, like the `SeleccionEstado`.

```
<DataGrid TItem="Ciudad"
          Data="Data"
          RowInserted="@InsertarCiudad"
          UseInternalEditing ShowPager Editable Filterable Responsive Narrow Sortable NewItemCreator="NewCiudad">
    <DataGridCommandColumn NewCommandAllowed></DataGridCommandColumn>
    <DataGridColumn Field="IdCiudad" Editable="false" Caption="Id"></DataGridColumn>
    <DataGridColumn Field="NombreCiudad" Caption="Nombre" Editable></DataGridColumn>
    <DataGridColumn Field="EstadoCiudad.DescripcionEstado" Caption="Descripcion" Editable></DataGridColumn>
</DataGrid>

@code {
    private List<Ciudad> Data = new() { new Ciudad() { IdCiudad = "XPTO0001", NombreCiudad = "Lisbon", EstadoCiudad = new() { DescripcionEstado = "Estado" } } };
    public string SeleccionEstado = "1";
    public class Ciudad
    {
        public string? IdCiudad { get; set; }
        public string? NombreCiudad { get; set; }
        public Estado? EstadoCiudad { get; set; }
    }
    public class Estado
    {
        public string? IdEstado { get; set; }
        public string? DescripcionEstado { get; set; }
    }

    private Ciudad NewCiudad()
    {
        return new()
            {
                EstadoCiudad = new()
                {
                    IdEstado = SeleccionEstado
                }
            };
    }

    protected async Task InsertarCiudad( SavedRowItem<Ciudad, Dictionary<string, object>> e )
    {
        e.Item.IdCiudad = "1";
        var ciudadNueva = e.Item;


        //await CiudadService.SaveCiudad(ciudadNueva);
        SeleccionEstado = "-1";
    }

}
```
Please let us know if this helps you.

**Comment by Weidmann16** [comment]
Hello

Sorry for the delay, I was on vacation.

What you recommended worked for me, thank you very much

what I did was start the model in the same model :

![image](https://user-images.githubusercontent.com/74007151/210805412-c8bbbfaf-8b74-4927-8d0b-4e9589376e5c.png)


Thank you so much for everything

**Comment by stsrki** [comment]
Great. Glad it worked for you.

Closing the ticket now.
