### ISSUE TITLE
NumericPicker needs to support OnInput so it can be tested using BUnit

### ISSUE THREAD

**Issue by robalexclark** [Megabit/Blazorise#4411]
I can't seem to find a way to unit test the NumericPicker control using BUnit. It seems that this control does not support Input or Change so testing components that use NumericPicker seems to be impossible. 

Any ideas on how to test components using NumericPicker?

**Comment by robalexclark** [comment]
For now I have switched to Numeric edit and using css to hide the spinner controls

**Comment by stsrki** [comment]
NumericPicker relies on the JS library, and bUnit doesn't support any JSInterop calls. To be able to test, you will need to mock any call to JSInterop and JS modules.
