### ISSUE TITLE
Docs / Charts: How to create horizontal bar chart

### ISSUE THREAD

**Issue by BravermanMillimanCRS** [Megabit/Blazorise#4417]
**Describe the bug**
The [documentation for Blazorise.Charts](https://blazorise.com/docs/extensions/chart) refers to a `HoriztonalBarChart` class that does not exist in the current code base. No documentation appears to exist for how to create a horizontal bar chart using the `BarChart` component.

**Possible fixes**
1. Remove references to the `HorizontalBarChart` class from the documentation.
2. Provide an example in the documentation for creating a horizontal bar chart.
3. Alternately, restore the `HorizontalBarChart` class.

**Comment by stsrki** [comment]
This is an accidental leftover from before v1.0. We should update the docs and remove its mention. And also add a horizontal example.
