### ISSUE TITLE
Does Blazorise wiil support Vscode?

### ISSUE THREAD

**Issue by Edemilorhea** [Megabit/Blazorise#4421]
**Is your feature request related to a problem? Please describe.**

I just wanna know does a day Blazorise will support Vscode?

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

 I like VSCode more than VS, but Blazorise dosen't have any extension in vscode, there dosn't have any intellisense and snippet.

So I need back to docs to check my code is right or something can use attributes.

**Comment by stsrki** [comment]
Blazorise should work in VSCode. Things like that you mentioned should be able to work with extensions for VSCode. Blazorise, in that way, is similar to any other C# project, as I am aware of.

**Comment by Edemilorhea** [comment]
![image](https://user-images.githubusercontent.com/92776711/210050858-d8fc8440-801b-438b-a62c-c32cffc14cbd.png)

Cause That code all the White, Doesn't have any color to identify

**Comment by stsrki** [comment]
So, it's missing tag names to color them. We will need to investigate this before we proceed.

**Comment by David-Moreira** [comment]
I'm not currently at my desktop to test this. Not do I vs code frequently, but that seems more like a lack of razor support.
Have you tried regular razor? How does it handle the blazor inbuilt components and your own? Is it able to? My guess is that there should be a more general extension for razor that mimcks the work thats done in vs to color stuff.

**Comment by David-Moreira** [comment]
Seems fine to me, can you please re-check your vs code configuration? There shouldn't be anything Blazorise specific we need to do. I believe the razor "color detection" should all be provided by the C# language extension if I'm not wrong.

![image](https://user-images.githubusercontent.com/22283161/210283428-0ac979ee-f6a1-44d3-9059-781dd8c5a779.png)

**Comment by Edemilorhea** [comment]
> Seems fine to me, can you please re-check your vs code configuration? There shouldn't be anything Blazorise specific we need to do. I believe the razor "color detection" should all be provided by the C# language extension if I'm not wrong.
> 
> ![image](https://user-images.githubusercontent.com/22283161/210283428-0ac979ee-f6a1-44d3-9059-781dd8c5a779.png)

hey relly thanks your replay, I think you're right, razor is work, Maybe is my vscode Theme problem, I change back to vs2019 theme, it's look up like your pic.

**Comment by stsrki** [comment]
Nice. Glad it works now.

Closing the ticket now.
