### ISSUE TITLE
Numeric Edit Attribute Min & Max not working when used on Edit Template Datagrid

### ISSUE THREAD

**Issue by benny-adiwijaya** [Megabit/Blazorise#4422]
Hi, when using Numeric Edit inside edit template on datagrid, the attribute min & max not working. Is there a way to solve this? Thanks

**Comment by stsrki** [comment]
Hi @benny-adiwijaya 

The NumericEdit is a simple wrapper around the native `<input type="number">` so the browser mostly controls the input. We could add a min/max check after `onblur` event as the best and probably the only option.

Other than that, I advise using the new `NumericPicker` component. It has much more features.

**Comment by benny-adiwijaya** [comment]
Oke thanks, it works
