### ISSUE TITLE
Add Checkbox into DropdownItem

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#4428]
We need to add support for checkboxes in the Dropdown/DropdownList component.

It should look as 

![image](https://user-images.githubusercontent.com/900302/210333677-76baee66-e1fd-4a6e-8a62-b596948a3538.png)

Behavior wise:

- When we click on Check, the selection will toggle. The dropdown menu should stay open when clicking on a check.
- When we click on an item, the item `Clicked` event will fire, and the dropdown menu should close.

New parameters

Adding a Check means we need to have multiselection support. So the new SelectedValues parameter is also needed.

**Comment by carlblanchard** [comment]
I agree, this is a nice and needed feature.

**Comment by carlblanchard** [comment]
One of the issues I am facing with this is when selecting the checkbox it closes the dropdown. 
It seems like there are no easy workarounds either like using preventDefault as that prevents the check from occurring.
