### ISSUE TITLE
DataGrid: Select the sort direction on first click of sorting

### ISSUE THREAD

**Issue by pDakov** [Megabit/Blazorise#4431]
**Is your feature request related to a problem? Please describe.**
Hi team,

I am curious if it is possible at the moment and I miss seeing how to do it, or if it can be implemented in the future.

I would like to have the opportunity to change the direction on the first click of sorting.

I do not mean this SortDirection="SortDirection.Descending", this is for the default sorting when the screen is loaded.

At the moment when I click for the first time on the header I get ASC sorting, and when clicking it again (the second time) I get DESC sorting.

**Describe the solution you'd like**
My understanding is if we have some attribute like this FirstClickSortDirection="SortDirection.Descending" to select the sort direction, we can achieve this result without any custom logic.

This will be useful for pages that show any financial report and will be more intuitive and user-friendly.

**Comment by stsrki** [comment]
Instead of `FirstClickSortDirection` it seems to me that it would make more sense to have a sort direction logic reversed when clicked. Or, make the sort icon clickable and then show the drop-menu with an extra feature to select the desired sort mode.

**Comment by pDakov** [comment]
> Instead of `FirstClickSortDirection` it seems to me that it would make more sense to have a sort direction logic reversed when clicked. Or, make the sort icon clickable and then show the drop-menu with an extra feature to select the desired sort mode.

I see it to be simple, without any visible changes for the user, only for the developer to set for the first click DESC, for the second to be ASC.

For the moment have no option, always is ASC for the first click and DESC for the second.

**Comment by injDakov** [comment]
@stsrki
please take a look at this https://github.com/Megabit/Blazorise/pull/4432

Here is the implementation of my suggestion.

I will be thankful if you accepted it.
I am open to discussing the naming if you have some concerns.
