### ISSUE TITLE
Add dependabot notificaftions for updated js libs

### ISSUE THREAD

**Issue by GeertvanHorrik** [Megabit/Blazorise#4440]
**Is your feature request related to a problem? Please describe.**

It's about outdated js library versions.

**Describe the solution you'd like**

For internal projects, I've set up dependabot for the js libs. At least there is a signal when a new version is shipped so it doesn't always leave the library with outdated libs.

### Additional context

Happy to provide a PR that:

1. Uses npm to manage the js library
2. Build steps to copy the correct scripts from the npm lib folder into the source folders
3. Automatically checks for updates and create PRs using dependabot

We use this in our own projects and we really like this workflow since it's easy to "forget" about checking new updates for js libraries (in a .NET world).

**Comment by stsrki** [comment]
It would be nice, but I don't believe that it would be possible for all JS libraries. For some libraries, we had to modify them slightly so that they would work properly as JS modules. If in the meantime, those libraries are fixed then it is great. 

Although I would really move away from NPM completely 😅

**Comment by GeertvanHorrik** [comment]
Would you like me to work on a PR?

**Comment by stsrki** [comment]
Try it on a small scale first. On one or two JS libraries to see how it goes. Then submit a WIP PR so we can look and see how to proceed. Is that OK?

**Comment by stsrki** [comment]
I have merged the PR. We'll see how it goes before moving forward with other changes.

Thank you for your help in making it happen!

**Comment by stsrki** [comment]
PS. it worked great once I merged and got reports. I have patched all the reported files to the latest supported, nonbreaking version, and so far, all is working fine.

Thank you once again @GeertvanHorrik

**Comment by GeertvanHorrik** [comment]
Glad you like it :)

Shall I do one for the NuGet ecosystem as well? Shouldn't be this big

**Comment by stsrki** [comment]
> Shall I do one for the NuGet ecosystem as well? Shouldn't be this big

I would appreciate it ☺
