### ISSUE TITLE
Textfield in Autocomplete is swallowing characters when typing extremely fast

### ISSUE THREAD

**Issue by sdog879** [Megabit/Blazorise#4444]
I have an autocomplete component set up and when typing in it fast, it will drop characters from the text field.

![Screenshot_1](https://user-images.githubusercontent.com/48141860/211105381-f54868d1-8df2-4a3a-bd4b-c06308de2ada.png)

After typing in the string "testing123" notice that the N and 1 have been dropped from the string. The behaviour of what characters are being dropped appears to happen at random.  

1. Go to a Autocomplete Textfield (this could happen across all text fields, I never tested it)
2. Type in a string FAST, even just repeating to characters can illustrate this behaviour .
3. Notice that characters will have been dropped from the string.

Not something that is a _major_ concern as most users won't have a fast typing speed, but it is a little bit of wacky behaviour that I noticed.

Thanks.

**Comment by David-Moreira** [comment]
I believe we had fixed this behaviour. Are you using the latest version?

**Comment by sdog879** [comment]
> I believe we had fixed this behaviour. Are you using the latest version?

Ah, we're using 1.1.4.1 so that might be why.

**Comment by David-Moreira** [comment]
Actually that seems pretty recent, the fix was somewhere at the end of last year I believe. Still best If you can please try with latest.

**Comment by David-Moreira** [comment]
@sdog879 please test on latest version and let us know your findings. If it still happens, we'd appreciate a Repro. Thanks!

**Comment by sdog879** [comment]
@David-Moreira, sorry for the late reply. The newest version appears to have fixed it but will continue to monitor it. 

Thanks!
