### ISSUE TITLE
ColumnWidth in Rows with RowColumns defined is not used

### ISSUE THREAD

**Issue by oaldrian** [Megabit/Blazorise#4458]
**Describe the bug**
ColumnWidth in Rows with RowColumns defined is not used

**To Reproduce**
see reproduction in https://github.com/oaldrian/BlazoriseReproductions/tree/ColumnWidthInRowsWithColumnCounts index.razor

**Expected behavior**
column width is used even when RowColumns are defined.

**Additional info**
- running on blazorize bootstrap 1.1.5
- happening with webassembly and serverside blazor, reproduction with webassembly
- generated css suggests that the class is applied (div has class="col-4", or 8 applied) but somehow it gets overwritten by the rowcolumns count

**Comment by stsrki** [comment]
RowColumns are meant to be used as a convenient way to define columns. They should not be mixed with the explicitly defined column sizes on an actual Column component. I don't know how that would work.

Source https://getbootstrap.com/docs/5.1/layout/grid/#row-columns

**Comment by oaldrian** [comment]
hmm...

if I define `RowColumns.Is1.OnMobile.Is2.OnDesktop`
and `ColumnSize.Is4.OnMobile.Is3.OnDesktop`

the system should have all needed information to render correctly.

it is only weird, but not undefined, if I do `ColumnSize.Is3` and nothing else. Then the column would look weird on one device type as it is only "optimized" for the other one.

**Comment by stsrki** [comment]
Sorry for not getting to you sooner.

As I have already mentioned you should only use one or the other, It's not possible to define column sizes on Row and on Column.

I have checked your project and what you were basically missing is the logic of defining the rules. You must start from the min to max. In this case from mobile to desktop, and higher.

Here is the working example:

```
<ModalBody>
  <Row RowColumns="RowColumns.Are1.OnMobile.Are2.OnTablet">
      <Column>

          <Field>
              <FieldLabel><strong>test</strong></FieldLabel>
              <FieldBody>
                  <TextEdit />
              </FieldBody>
          </Field>
      </Column>

      <Column>
          <Field>
              <FieldLabel><strong>test</strong></FieldLabel>
              <FieldBody>
                  <TextEdit />
              </FieldBody>
          </Field>
      </Column>
  </Row>
</ModalBody>
```

Notice we now have only `RowColumns.Are1.OnMobile.Are2.OnTablet`. It means we want to take full size on small devices and half size on larger devices.

![image](https://user-images.githubusercontent.com/900302/215095110-39c4c7b1-b29c-4b3a-9723-ca3a78edfb86.png)
![image](https://user-images.githubusercontent.com/900302/215095135-838056a2-22f0-4a4d-b288-6bff919562bd.png)

**Comment by oaldrian** [comment]
That is a nice insight, thanks for the coding lesson 😅

With this understanding I think you can close this issue
