### ISSUE TITLE
Datagrid Sort behaviour regression

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#4460]
@stsrki Regression for Sorting on master.
I believe there was a non sorted state right? It now only switches between asc/desc, I believe it might have been added here : #4434

@injDakov would you have time to take a look at it?

**Comment by stsrki** [comment]
Yes, there should be a non-sorting state when looping the states.

**Comment by injDakov** [comment]
@David-Moreira 
My changes here only give the opportunity to reverse the first direction of sorting. 

Non-Sorting (on init) -> ASC (first click)-> DESC (second click) and etc
or 
Non-Sorting (on init) -> DESC (first click)-> ASC (second click) and etc

**Comment by David-Moreira** [comment]
But does it go back to the non sorting again?
Ie:
Non-sorting -> asc -> desc -> non-sorting so on...

**Comment by stsrki** [comment]
As David mentione need to go

Non sorting -> asc -> desc -> non sorting

and in reverse

Non sorting -> desc -> asc -> non sorting

**Comment by injDakov** [comment]
I got it.
Will prepare a new PR with a fix for this in one hour.

Need to remove these lines https://github.com/Megabit/Blazorise/pull/4434/files#diff-6d764d902c8a96989eb7ab34c9aa0681559b3a1c059e96fffc62cae2171baf16R29

**Comment by injDakov** [comment]
Here is it: https://github.com/Megabit/Blazorise/pull/4464

**Comment by David-Moreira** [comment]
Closing issue. Thanks alot for taking the time @injDakov
