### ISSUE TITLE
Expose an EventCallback for Autocomplete on blur

### ISSUE THREAD

**Issue by joost00719** [Megabit/Blazorise#4469]
**Is your feature request related to a problem? Please describe.**
I am trying to reset the user's search query to the SelectedValue text when the component has lost focus.
I want to do this because this way it is clear what value is chosen.

**Describe the solution you'd like**
I'd like to have an eventcallback parameter to the Autocomplete component which gets called when the component loses focus (onblur event maybe?)
**Note:** Make sure when a user selects a value, the "SelectedValueChanged" callback is called _before_ the proposed callback is called.

### Additional context
A good name for the proposed event could be "OnClose" or "OnFocusLost". OnBlur might interfere with the standard javascript event names.

Maybe add some more events (e.g. when it is opened) to allow more extensive usage of this component.

**Comment by stsrki** [comment]
@David-Moreira ?

**Comment by David-Moreira** [comment]
I don't see why not.
We could have an `Opened `and `Closed` events called on our corresponding internal `OnTextFocusHandler` and `OnTextBlurHandler` events.

As for the problem itself, I don't think I quite got it. Would that be something we can improve on our `Autocomplete` handling?

**Comment by joost00719** [comment]
I use the Autocomplete component as a form element (instead of a normal html <select>), so that it's possible to search within a bigger dataset. This is probably not intended by design, but works pretty good for me.

The issue with (ab)using the component like this, is that when a user selects a value, then changes their mind, and starts searching again (without clicking/selecting another value after searching), is that when they leave the search area, it is not visible which value is actually selected.

What I want is that the SelectedText is revert back.

In this screenshot you can see I searched for "United kingdom" rather than "United Kingdom" (notice capital K).
If this was in a form, the user would think they have selected a country, but in reality they selected null.
![image](https://user-images.githubusercontent.com/21021559/212760883-3b5c329b-f3ff-4c18-ac3e-e86977dd3777.png)


My fix would be to listen to the `Closed ` event, and manually setting the SelectedText to the SelectedValue's text.
This way the SelectedText will be overruled by what's actually selected, and not what is being searched.

I think adding the `Opened` and `Closed` events is the way to go.

**Comment by joost00719** [comment]
I use the Autocomplete component as a form element (instead of a normal html \<select\>), so that it's possible to search within a bigger dataset. This is probably not intended by design, but works pretty good for me.

The issue with (ab)using the component like this, is that when a user selects a value, then changes their mind, and starts searching again (without clicking/selecting another value after searching), is that when they leave the search area, it is not visible which value is actually selected.


What I want is that the SelectedText is revert back.


In this screenshot you can see I searched for "United kingdom" rather than "United Kingdom" (notice capital K).
If this was in a form, the user would think they have selected a country, but in reality they selected null.
![image](https://user-images.githubusercontent.com/21021559/212760883-3b5c329b-f3ff-4c18-ac3e-e86977dd3777.png)


My fix would be to listen to the `Closed` event, and manually setting the SelectedText to the SelectedValue's text.
This way the SelectedText will be overruled by what's actually selected, and not what is being searched.

Only adding the `Opened` and `Closed` events should be enough and won't introduce breaking changes.

**Comment by David-Moreira** [comment]
@joost00719 
The Autocomplete by default already solves this, does it not? If `FreeTyping` is disabled, then when the user leaves the Autocomplete, the Autocomplete will clear itself, because there isn't a valid value.

**Comment by David-Moreira** [comment]
Ahhh, I re-read that, you want to go back to a value you already got stored previously?

**Comment by David-Moreira** [comment]
Anyway, if you really wanted to make it work, maybe you could try inheriting Autocomplete or reflection to access 
![image](https://user-images.githubusercontent.com/22283161/212784570-2caaa641-5e97-4e4a-8493-0dce6ded77b1.png)
And then play with the `ValueChanged` events? But I'm not sure you would be able to work it out...
![image](https://user-images.githubusercontent.com/22283161/212784191-e24f4ad6-b84c-4500-8acb-c246b656a149.png)

**Comment by joost00719** [comment]
I'll take a look at the freetyping value tomorrow. IIRC I removed that attribute from when I was fiddling around, but maybe I have to explicitly set it to false.

I'll fiddle around a bit more and see if I can use reflection as well, I'll report back to you!

Note that I'll be unavailable after tomorrow morning (utc) for 2 days, and might not reply in that time.

**Comment by joost00719** [comment]
To get back to you, I have confirmed that disabling `FreeTyping` will fix my issue in the newest version.
I have also confirmed that it's broken in version 0.9.5.7. However, we plan to upgrade to .NET 6 soon™, so that should fix the issue.

**Comment by David-Moreira** [comment]
> To get back to you, I have confirmed that disabling `FreeTyping` will fix my issue in the newest version. I have also confirmed that it's broken in version 0.9.5.7. However, we plan to upgrade to .NET 6 soon™, so that should fix the issue.
> 
> Please let me know if you want to add those events or not. If not, I'll close this issue.

That's great! :)

@stsrki despite this issue being fixed, would you also agree in taking the `Opened` and `Closed` events as a feature?

**Comment by joost00719** [comment]
Any info when the `Opened` and `Closed` event callbacks are expected to release?

**Comment by stsrki** [comment]
We didn't assign any milestones for this ticket. @David-Moreira, what do you think? Worth doing for 1.3?

**Comment by David-Moreira** [comment]
I guess, since it should be a pretty quick implementation.
We also accept Pulll Requests of course if you're willing @joost00719  :)
