### ISSUE TITLE
Blazor Validation not working when using Child Component when Child Component is Autocomplete

### ISSUE THREAD

**Issue by nelsonad** [Megabit/Blazorise#4482]
Hello. 

I'm trying to follow the solution outlined here https://github.com/Megabit/Blazorise/issues/1953 

but my nested child control is an Autocomplete and does not have the ValueExpression property.

Please help me so that I can validate a nested Autocomplete control.

Thank you.

**Comment by stsrki** [comment]
Autocomplete has its own built-in validation component. So you cannot define any that will be used outside of it—also, ti only supports the "handler" validator. You can define one with the parameters `Validator`, or `AsyncValidator`.

**Comment by nelsonad** [comment]
Thank you. I will try that.
