### ISSUE TITLE
Autocomplete NotFoundContent not working since the latest version

### ISSUE THREAD

**Issue by ArneCools** [Megabit/Blazorise#4488]
**Describe the bug**
NotFoundContent is not shown anymore in the latest version

**To Reproduce**
1. Go to https://blazorise.com/docs/extensions/autocomplete
2. Search for anything not on the list
3. NotFoundContent not shown

**Expected behavior**
Show NotFoundContent 

**Additional context**
I remember it working correctly in a previous version

**Comment by David-Moreira** [comment]
Hello @ArneCools can you please recheck, it's working properly.

Please note that those are demos and they might not have all the **NotFoundContent** Parameter defined. In this case the **Autocomplete Multiple Selection** example does not have the **NotFoundContent** defined.
![image](https://user-images.githubusercontent.com/22283161/214443193-976b36d4-eee6-465c-9312-f0bda8acdb56.png)


Please let us know whether you had an issue using trying to use the feature.

**Comment by ArneCools** [comment]
It seems that the **NotFoundContent** is not shown when **FreeTyping** is set to true. In the examples where it is true, **NotFoundContent** is still provided in the example which is confusing. 

Maybe we can still show the **NotFoundContent** when **FreeTyping** is enabled? and show another option "Add <yourvalue>" Example in MUI:
![image](https://user-images.githubusercontent.com/1440244/215513634-53f3ee4f-2596-4ede-bd92-95b7ea042d2c.png)

**Comment by David-Moreira** [comment]
I can see the benefit, but I can also see people not wanting it to show when `FreeTyping` is enabled.

What do you think @stsrki ?

**Comment by stsrki** [comment]
In FreeTyping, it should not show. Because anything that users write that is not in the original list would mean that the template would be visible.

**Comment by David-Moreira** [comment]
What if it was `FreeTypingContent`? 
If I am going out of the predefined values of the auto complete then I'm starting to FreeType, and I might want to show a custom template like the suggestion from @ArneCools?
Add "Some Value outside Predefined Values"....
![image](https://user-images.githubusercontent.com/22283161/216783396-d10a46cc-d917-46a9-97fc-f6089027df36.png)

**Comment by stsrki** [comment]
That makes more sense(although named `FreeTypingNotFoundContent`), but I still feel it would be confusing for the user.

**Comment by David-Moreira** [comment]
Actually I'd prefer `FreeTypingContent`, the user should be able to deduce that content will show up when free typing is happening, which is when it is going out of the bound data values/options.

**Comment by stsrki** [comment]
> the user should be able to deduce that content will show up when free typing is happening

I wouldn't rely on that :)

Would `FreeTypingContent` show all the the while the user is typing or only when there are no data?

**Comment by David-Moreira** [comment]
The point of `FreeTyping` is that it allows you to specify a text that's outside the options. So that's when it would show.

**Comment by stsrki** [comment]
In that case, I think `FreeTypingContent` would not make sense. `FreeTypingNotFoundContent` while longer immediately communicates what it means.

**Comment by David-Moreira** [comment]
I still believe `FreeTypingContent` would imply that meaning. Anyway I wouldn't mind going with `FreeTypingNotFoundContent` anyway, so do you think it's a worthy feature?

**Comment by stsrki** [comment]
> Anyway I wouldn't mind going with `FreeTypingNotFoundContent` anyway, so do you think it's a worthy feature?

Yes, it is fine to do it.
