### ISSUE TITLE
New Feature: Icon Picker

### ISSUE THREAD

**Issue by WillianGruber** [Megabit/Blazorise#452]
In my application I need to enable my users to choose an icon to custom documents. So, I developed an Icon Picker, and I'm sharing here so that @stsrki may add to Blazorise if the component proves itself useful. My best bet is that it would be an Extension Component.
I'm sharing it here as I am using it now (with FontAwesome Icons), so probably it would need to be refactored to add other icon providers.
Feel free to modify as you see fit.

### How to use it
```
<h4>Simple Icon Picker</h4>
<IconPicker @bind-Icon="Icon"></IconPicker>
<h6>Chosen icon: @Icon</h6>
@code {
    protected string Icon { get; set; }
}
```

### Results:
![image](https://user-images.githubusercontent.com/56033692/71213969-a317bc00-2293-11ea-8048-7a4610ea8b9d.png)
![image](https://user-images.githubusercontent.com/56033692/71214310-bf1b5d80-2293-11ea-8011-aa367b78fd60.png)
![image](https://user-images.githubusercontent.com/56033692/71214334-d22e2d80-2293-11ea-8393-6293485fd26d.png)
![image](https://user-images.githubusercontent.com/56033692/71214361-e1ad7680-2293-11ea-8e36-851b37fb6579.png)
![image](https://user-images.githubusercontent.com/56033692/71214481-318c3d80-2294-11ea-94e8-0a39a688abed.png)

### Parameters:
**Icon** The selected formatted icon. You can pass an icon here and it will highlight as selected in modal, too, including parsing options.
**AllowFlip** Enables the options for Flipping horizontally, vertically, and both. Default: true
**AllowRotation** Enables the options for rotating 90, 180 and 270 degrees. Default: true
**AllowSize** Enables the size options. Default: true
**AllowSizeMinimum** Sets a minimum in the size options, so that the user cannot select a smaller size. Default: IconSize.ExtraSmall
**AllowSizeMaximum** Sets a macimum in the size options, so that the user cannot select a larger size. Default: IconSize.x10
**ButtonSize** The size of the button used to open the modal. Default: ButtonSize.None
**ButtonColor** The color of the button used to open the modal. Default: Color.None
**ButtonTooltipText** The tooltip of the button used to open the modal. Default: "Select an Icon"
**ButtonTooltipPlacement** The placement of tooltip of the button used to open the modal. Default: Placement.Bottom
**ModalTitle** The header title of the modal component. Default: "Select an Icon"
**ModalButtonSize** The size of the buttons in the modal component. Default: ButtonSize.None
**ModalTooltipPlacement** The placement of the tooltip of icons in the modal component. Default: Placement.Bottom

### Files
https://gist.github.com/WillianGruber/d29b0e422edd17ec3819a90aafb48c9d
https://gist.github.com/WillianGruber/8b829845c171fb9578a380143c0218cd
https://gist.github.com/WillianGruber/843032460e5168163dc1083e9d7ceb6a
https://gist.github.com/WillianGruber/ba084bf332d00ed3462ddd0639c39c78

**Comment by stsrki** [comment]
@WillianGruber 

I must say this look really great. It's clean and fully done with Blazorise components. I appreciated that. Great job!

It will be an extension for Blazorise as you already mentioned. After I create it I will mention you as an author in the nuget and project properties.

**Comment by WillianGruber** [comment]
Thx @stsrki !

Btw, I'll make a small cosmetic update in the razor file now, to make the option buttons look better.
I plan to make a better version latter, with tabs, groups and filters. This v2 version will take some months, as it is past my prototype plans.

Oh, did you see the horizontal scrollbar? I can't find a way to get rid of it. If it is a 1-minute effort from you, I would appreciate if you take a look at it 😃

**Comment by WillianGruber** [comment]
@stsrki as this component loads too many icons it gets laggy when filling an input field, for example. I plan on rewriting it with dynamically rendered tree, so the lag exists only when the modal is opened. Right now the modal is loaded and generated, but is invisible, and impacts negativelly on performance.

**Comment by stsrki** [comment]
@WillianGruber Yeah, that's what I also experienced. It's too slow to render all icons at once. I thinks I will wait for you to finish optimizations before I release it. I have done it on branch `dev088-iconpicker` so if you're going to do anything you can push it there.

**Comment by WillianGruber** [comment]
Updated gist to only render icons if the modal is open

**Comment by stsrki** [comment]
Closing since we don't have plans for this component.
