### ISSUE TITLE
Button group Flex is interfering with Display.None

### ISSUE THREAD

**Issue by ivancavlek** [Megabit/Blazorise#4545]
This is a elaboration on #3954. I found out what was causing it.

Describe the bug
When using `Display="Display.None"` in Buttons (button group), it doesn't hide the entire group **when** `Flex="Flex.JustifyContent.Center"` is present.

```C#
<Buttons Display="Display.None" Flex="Flex.JustifyContent.Center">
        <Button Color="Color.Secondary">LEFT</Button>
        <Button Color="Color.Secondary">CENTER</Button>
        <Button Color="Color.Secondary">RIGHT</Button>
</Buttons>
```
![image](https://user-images.githubusercontent.com/16662190/215807892-19ff1d56-ad84-4f69-8ff2-b99b7c583530.png)
![image](https://user-images.githubusercontent.com/16662190/215808464-b29cb998-e543-41de-b2e1-b38753a2c8ce.png)

Disabling Flex in F12 resolves the issue with Display, but I need centering of the button group.

![image](https://user-images.githubusercontent.com/16662190/215808991-60d73000-d2a8-4201-9701-3bdf6e4beb5b.png)

**Comment by stsrki** [comment]
It works as expected from what I can see. I know it's not too intuitive. But you're trying to define two `display` styles while there can only be one.

You can do the following if you need to have some control over it.

`<Buttons Display="@(show ? null : Display.None)" Flex="@(show ? Flex.JustifyContent.Center : null)">`

**Comment by ivancavlek** [comment]
I understand now. Thank you @stsrki 😊!
