### ISSUE TITLE
Expose JS `function calculateAutoHeight(e)` as a public C# method `UpdateAutoHeight` in `MemoEdit`

### ISSUE THREAD

**Issue by Jinjinov** [Megabit/Blazorise#4555]
**Is your feature request related to a problem? Please describe.**

I would like to call `MemoEdit.UpdateAutoHeight` even if the `MemoEdit` doesn't have focus and the text was updated programmatically in C#

**Describe the solution you'd like**

Expose JS `function calculateAutoHeight(e)` as a public C# method `UpdateAutoHeight` in `MemoEdit`

### Additional context

If we update the `MemoEdit` text by pressing a button outside, then `element.oninput = calculateAutoHeight;` will not trigger in JS and `MemoEdit` will not update its size.

**Comment by stsrki** [comment]
I think it would be better to fix it by calling `calculateAutoHeight` internally if the `Text` has changed from outside.

**Comment by Jinjinov** [comment]
That would be even better! :)
