### ISSUE TITLE
Autocomplete dropdown doesn't close when the first item is auto selected

### ISSUE THREAD

**Issue by ItsTahaRehman** [Megabit/Blazorise#4563]
In the autocomplete component when I auto select the first item in the list then the autocomplete dropdown doesn't close 

![image](https://user-images.githubusercontent.com/95471572/217003111-bae5f786-2972-4103-8fbf-2ad5620c3f28.png)

Below is the code that I am using in the autocomplete 
I'm using the properties close on selection as well but still the autocomplete dropdown is open after the selection

![image](https://user-images.githubusercontent.com/95471572/217003329-430d8018-0c09-4f1a-910e-ea72313253b8.png)

**Comment by David-Moreira** [comment]
Hello,
It's preferable if you can provide a ready to reproduce code sample with the proper steps to reproduce. Otherwise we can't test and help you.
I tested the following on latest version and it worked. Appreciated if you can get a repo with this or more details, thanks!

```
<Autocomplete TItem="Test"
              TValue="string"
              AutoPreSelect
              AutoSelectFirstItem
              CloseOnSelection
              ValueField="(x) => x.Name"
              TextField="(x) => x.Name"
              ReadData="ReadData"
              Data="Data">
</Autocomplete>

@code {
    public class Test
    {
        public string Name { get; set; }
    }
    private List<Test> Data = new() { new() { Name = "XPTO" }, new() { Name = "XPTO2" }, new() { Name = "XPTO3" } };
    private Task ReadData( AutocompleteReadDataEventArgs e )
    {

        return Task.CompletedTask;
    }
}
```

**Comment by David-Moreira** [comment]
Hello @ItsTahaRehman 
Sorry for the detay.

Can you retry 1st problem with the latest version?

About the 2nd one, I didn't understand what's the problem? It seems like your ReadData, takes a while to get back and then it lists the option you've searched for. Is that not ok?
