### ISSUE TITLE
Improve `Highlighter` to highlight inside nested HTML

### ISSUE THREAD

**Issue by Jinjinov** [Megabit/Blazorise#4571]
**Is your feature request related to a problem? Please describe.**

Right now `Highlighter` only works with plain text.

    <Highlighter Text="@sentence" HighlightedText="@searchValue" />

**Describe the solution you'd like**

Improve `Highlighter` to highlight inside nested HTML (`Text`, `Paragraph`, `Heading`, `Link`):

    <Highlighter HighlightedText="Blazor">
        <Heading Size="HeadingSize.Is1">h1. Blazorise heading</Heading>
        <Text TextColor="TextColor.Primary">Lorem ipsum dolor sit amet.</Text>
        <Link To="https://github.com/Megabit/Blazorise" Target="Target.Blank">Blazorise link</Link>
    </Highlighter>

### Additional context

I have a very special use case:

1. open `*.md` file with `FileInput`
2. get `string` from `Stream`
3. get markdown HTML from `string` using https://github.com/xoofx/markdig
4. use `MarkupString` inside a `Div` to render markdown as HTML
5. search markdown and highlight results (replace `Div` with `Highlighter`)

Right now I am using https://github.com/zzzprojects/html-agility-pack

**Comment by stsrki** [comment]
I don't think this will be possible to do. Our Highlighter is working in C# to detect parts of the string to highlight. If we would change that and try to get the `innerHtml`, we would probably have to use JSInterop. Which would slow rendering, even if it is possible to do.

**Comment by Jinjinov** [comment]
I understand, that makes sense.

I created my own read-only `MarkdownView` control that supports highlighting.

It was really easy to create it, so I will leave the instructions here, if someone else needs it:

The control accepts `string MarkdownText` and `string HighlightText`.

This is the razor:

```razor
    <Div>
        @if (string.IsNullOrEmpty(HighlightText))
        {
            @((MarkupString)_markdownHtml)
        }
        else
        {
            @((MarkupString)MarkHighlightText(_markdownHtml))
        }
    </Div>
```

This is the C# for Markdown:

```csharp
    using Markdig;

    static readonly MarkdownPipeline _markdownPipeline = new MarkdownPipelineBuilder()
        .UseAdvancedExtensions()
        .UseSoftlineBreakAsHardlineBreak()
        .Build();

    private string _markdownHtml = string.Empty;

    public string MarkdownText
    {
        set
        {
            _markdownHtml = Markdown.ToHtml(value, _markdownPipeline);
        }
    }
```

This is the C# for highlights:

```csharp
    using HtmlAgilityPack;

    string MarkHighlightText(string text)
    {
        var htmlDoc = new HtmlDocument();
        htmlDoc.LoadHtml(text);

        HtmlNodeCollection coll = htmlDoc.DocumentNode.SelectNodes("//text()");

        foreach (HtmlTextNode node in coll.Cast<HtmlTextNode>())
        {
            node.Text = node.Text.Replace(Filters.SearchFilter, $"<mark>{Filters.SearchFilter}</mark>");
        }

        return htmlDoc.DocumentNode.OuterHtml;
    }
```

**Comment by stsrki** [comment]
Seems like material for a blog post.
