### ISSUE TITLE
DropdownToggle Outline attribute not working

### ISSUE THREAD

**Issue by DirkSuelmann** [Megabit/Blazorise#4578]
**Describe the bug**
The "Outline" attribute doesn't work. When I set it to false or "false", it still keeps showing the outline.

**To Reproduce**
1. Copy paste this code
```
<Dropdown @ref="LanguageDropdown" Width="Width.Auto">
    <DropdownToggle Outline="false">
        @CultureInfo.CurrentCulture.Name
    </DropdownToggle>
    <DropdownMenu>
        <DropdownItem>one</DropdownItem>
    </DropdownMenu>
</Dropdown>

@code{
    Dropdown? LanguageDropdown { get; set; }

}
```
2. Click on the dropdown toggle and notice that there is an outline around it.

**Expected behavior**
No outline should be visible on the `DropdownToggle` when Outline is set to `false`

**Screenshots**
3. This is not expected when outline is set to false
![image](https://user-images.githubusercontent.com/109461119/217761323-429baa93-c04d-4898-960c-a696e02eb192.png)

**Additional notes**
It's also not possible to set the outline to 0 using Style.

**Comment by steal4life** [comment]
I tried to fix this and for now it's working on bootstrap and material
