### ISSUE TITLE
AntDesign Switch not switching

### ISSUE THREAD

**Issue by Magehernan** [Megabit/Blazorise#4583]
**Describe the bug**
When you change the value of the parameter Checked  of the switch from code it not render correctly, if you click it it change only if the value is the opposite.

**To Reproduce**
1. Create a switch
2. Create a button
3. create a bool variable and toggle it value on the button clicked
4. set the bool variable to the Checked of the switch
5. click at the button and the switch and it not switch.

**Expected behavior**
The switch to represent the value of the variable.

**Comment by Magehernan** [comment]
@stsrki hi, i was making the new pull request but, like you say in your last comment maybe it will be fix on the base component instead of the antdesign so... if that the case isn't needed to make the pull request? so let me know what you want.
Thanks

**Comment by stsrki** [comment]
No worries I can make the change :)

**Comment by stsrki** [comment]
#4589
