### ISSUE TITLE
Strange Behaviour of Accordion component

### ISSUE THREAD

**Issue by HansMeiser234** [Megabit/Blazorise#4604]
Version of installed blazorise packages: 1.2.0
Hello,

currently i use the Accordion component to show detailed data after opening the accordion. I create Collapse-Elements by loop and noticed a strange closing of my opened Collapse.  This is what i do:

I create a custom data class:

```
public class MyList{
        public string Guid { get; set; }
        public DateTime MyDate { get; set; }
         .
         .
         .
         public bool AccordionVisible = false;
}
```

This class is filled by SQL and currently only has 3 rows.
Now i create the accordion in HTML Area within a HTML table:

```
<Accordion>
@foreach (var item in MyList){
    <Collapse Visible="@item.AccordionVisible">
        <CollapseHeader>
            <Heading Size="HeadingSize.Is5">
                <AccordionToggle>Guid: @item.Guid</AccordionToggle>
            </Heading>
        </CollapseHeader>
        <CollapseBody>
<button class="btn btn-primary" @onclick="()=>makeit(item.Guid,item.AccordionVisible)">Download PFX</button><br /></CollapseBody>
    </Collapse>
    }
</Accordion>
```

Until now all works as expected. Have an Accordion  with 3 Collapse-Elements and expected data. I can open/close and see all my data.
makeit is currently a Task without real function. It just writes out the Paramenters to Console.

```
private async Task makeit(string guid, bool accvisible){
    Console.WriteLine(guid+", "+accvisible);
}
```

Pressing the button is just the moment my Collapse Element closes, and i have no idea why. In Console i can see the expected guid value and bool accvisible is written as "False". Currently iam running out of ideas. What can i do to have Visibility of accordion unchanged?

Thank you,
Hans

**Comment by David-Moreira** [comment]
Hello @HansMeiser234 have you tried `@bind-Visible`? The model is not being notified back of the **VisibleChanged** and so when it re-renders it's still set to false.

Also it's advised to use the `@key` instruction with an unique value assigned when doing loops so the rendering engine is smarter about it.

**Comment by HansMeiser234** [comment]
Thank you, this is working. 
I think i was confused, because i misses @bin-visible in component description. https://blazorise.com/docs/components/accordion

Thanks,
Hans
