### ISSUE TITLE
blazorise reload

### ISSUE THREAD

**Issue by KSahu997** [Megabit/Blazorise#4615]
Blazorise template when implemented in maui blazor it shows following error on Reload of any kind :
![image](https://user-images.githubusercontent.com/101610082/219857658-25eebf7a-db45-47f2-8b46-9ae39c069e0a.png)

**Comment by David-Moreira** [comment]
@KSahu997 Can you just provide the repo? Appreciated!

**Comment by KSahu997** [comment]
https://github.com/KSahu997/AONLOGBOOK

**Comment by KSahu997** [comment]
Just reload on windows application emulator launch

**Comment by David-Moreira** [comment]
Happens on component disposal, on an attempt of ours to call js disposal.
Different behavior then Blazor, in Blazor we try, if its not possible then all is ok, (as it's possible user has closed the app, etc..)

IN MAUI even if us, Blazorise "swallow" the exception and try to continue execution, MAUI still shows a blank page and a js exception.

Will probably have to repro something and open an issue over at MAUI repo, see what they tell us.

**Comment by David-Moreira** [comment]
Well I just found that we had already troubleshooted a similar issue and opened an issue.
Please track over at :
https://github.com/Megabit/Blazorise/issues/4287

**Comment by KSahu997** [comment]
IN MAUI even if us, Blazorise "swallow" the exception and try to continue execution, MAUI still shows a blank page and a js exception.
how can i swallow the exception

**Comment by David-Moreira** [comment]
Well we'll have to wait the dotnet's team response / resolution.

I'm going to answer your question with how you probably could swallow the exception yourself, but that's not at all recommended of course, and I didn't try it myself.
You could download the blazor web view js and remove / alter the bit about throwing and then load that new js into your app.
![image](https://user-images.githubusercontent.com/22283161/219940384-d41dd17e-a61f-43e5-b3b9-cbe30e36d2e9.png)

Of course modifying some libraries files is not recommended as you have to keep them updated whenever the library is updated, and you might do something unintended. 
Anyway... If you want to, Do it at your own risk. :)
