### ISSUE TITLE
TreeView 1.2.0 Fails to open pre-selected node

### ISSUE THREAD

**Issue by jacobsen9026** [Megabit/Blazorise#4616]
**Problem Description**
So when running 1.1.7 of Blazorise.TreeView my Active Directory Organizational Unit tree view component works as expected, but updating to 1.2.0 for just that package prevents it from opening the root node even though I'm supplying it to ExpandedNodes. The root node renders as if it were open, with the down arrow displayed. Also clicking the arrow, indeed collapses the nonexistent child nodes, with a second click finally drawing the child nodes. No exceptions are thrown.

My code pulls the children OU's in real-time with no precaching (though I do precache the root children), and synchronously. I've tried using the new Async parameters for the TreeView component but got no change in behavior.

**To Reproduce**
[My Implementation](https://github.com/Blazam-App/BLAZAM/blob/BlazoriseTreeViewError/BLAZAM/Shared/UI/OU/OUTreeView.razor)

**Expected behavior**
Setting the exact same RootNode object that is supplied as Data, as a member of a List of ExpandedNodes would render the root node as expanded on initialization.

My TreeView implementation is linked above, but [this](https://github.com/Blazam-App/BLAZAM/blob/BlazoriseTreeViewError/BLAZAMCommon/Data/ActiveDirectory/Models/ADOrganizationalUnit.cs) is the object that Tree is supplied with as data. Also, I am not setting my StartRootExapnded parameter to false, I just double checked, [this ](https://github.com/Blazam-App/BLAZAM/blob/BlazoriseTreeViewError/BLAZAM/Shared/UI/Settings/Permissions/PrivilegeMapper.razor)is the implementation of the screenshotted example.

**Screenshots**
[As Initialized](https://github.com/Blazam-App/BLAZAM/blob/BlazoriseTreeViewError/BLAZAM/Shared/UI/OU/asInitialized.png)
[After First Click of expander](https://github.com/Blazam-App/BLAZAM/blob/BlazoriseTreeViewError/BLAZAM/Shared/UI/OU/firstClick.png)
[After Second Click of expander](https://github.com/Blazam-App/BLAZAM/blob/BlazoriseTreeViewError/BLAZAM/Shared/UI/OU/secondClick.png)

**Additional context**
Seeing as the new example TreeView from the documentation works fine,  I'm suspecting either the way I'm supplying the nodes or preselecting them is wrong.

Also, as this data is linked to a synchronous yet inherently asynchronous exchange with a running Active Directory environment. I can't just pull the snippet of my code and anyone can run it.

I haven't yet had the time to make a generic analog of the OrganizationalUnit class I've made to test. But I should be able to in a couple of days.

I'd also like to thank everyone who's helped make Blazorise, it's makes Blazor development so painless.

**Comment by stsrki** [comment]
I believe this is the same problem as #4572. We have already fixed the issue, and it will be available today in 1.2.1.

**Comment by stsrki** [comment]
Hello @jacobsen9026, have you tried v1.2.1 release?

**Comment by jacobsen9026** [comment]
> Hi @stsrki, I have just tested 1.2.1 and can confirm that it has resolved this issue. Cheers!
