### ISSUE TITLE
Autocomplete keydown issue when dropdown is closed

### ISSUE THREAD

**Issue by WayneHiller** [Megabit/Blazorise#4622]
In the Autocomplete method
```
protected async Task OnTextKeyDownHandler( KeyboardEventArgs eventArgs )
```
Shouldn't the code below only execute if the dropdown is open?

```
if ( IsConfirmKey( eventArgs ) )
        {
            if ( IsMultiple && FreeTyping && !string.IsNullOrEmpty( CurrentSearch ) && ActiveItemIndex < 0 )
            {
                await AddMultipleText( CurrentSearch );
                if ( CloseOnSelection )
                {
                    await ResetCurrentSearch();
                    await Close();
                }
                return;
            }

            if ( ActiveItemIndex >= 0 )
            {
                if ( FilteredData?.Count > 0 )
                {
                    var item = FilteredData[ActiveItemIndex];
                    if ( item != null && ValueField != null )
                    {
                        await OnDropdownItemSelected( ValueField.Invoke( item ) );
                    }
                }
            }

            return;
        }
```

I am having issues with the user pressing the Confirm key when the dropdown is not visible and it auto assigns the "hidden" selected item/text the code has stored (behind the scene so to speak).

**Comment by WayneHiller** [comment]
I copied the component locally and made this change, seems to work correctly now.
```
if ( IsConfirmKey( eventArgs ) )
        {
            if ( IsMultiple && FreeTyping && !string.IsNullOrEmpty( CurrentSearch ) && ActiveItemIndex < 0 )
            {
                await AddMultipleText( CurrentSearch );
                if ( CloseOnSelection )
                {
                    await ResetCurrentSearch();
                    await Close();
                }
                return;
            }

            if ( ActiveItemIndex >= 0 && DropdownVisible)
            {
                if ( FilteredData?.Count > 0 )
                {
                    var item = FilteredData[ActiveItemIndex];
                    if ( item != null && ValueField != null )
                    {
                        await OnDropdownItemSelected( ValueField.Invoke( item ) );
                    }
                }
            }

            return;
        }
```

**Comment by stsrki** [comment]
Seems like an easy fix. If you could create a PR we would really appreciate it. Otherwise, we can look into it.

**Comment by WayneHiller** [comment]
@stsrki I have not cloned the repo locally yet. Pretty simple change maybe a contributor can do it? If everyone is too busy I can do it.

**Comment by WayneHiller** [comment]
Another little thing I noticed is that the CurrentSearch field is depreciated yet it is used all over in the code.

**Comment by David-Moreira** [comment]
> Another little thing I noticed is that the CurrentSearch field is depreciated yet it is used all over in the code.

Thanks for noticing. It will be removed in v2.0.

**Comment by David-Moreira** [comment]
> @stsrki I have not cloned the repo locally yet. Pretty simple change maybe a contributor can do it? If everyone is too busy I can do it.

Yes you may submit a PR with the fix if you have the time. we always appreciate community contributing into the project.
However as you know even the simpler changes can have side effects, Autocomplete really has a lot of features/quirks in there. 
But on first look doesn't seem like it will break anything.


I just noticed that the first if has a weird condition, hmm O.o I don't remember us using negatives for the idx, but surely there's a reason.
![image](https://user-images.githubusercontent.com/22283161/222835982-2163574e-7f85-4226-802e-ed022d1538b6.png)

**Comment by David-Moreira** [comment]
I'll go ahead and assign this task to you. If you don't have time or don't want to bother doing it, just let us know. :)

**Comment by WayneHiller** [comment]
>I just noticed that the first if has a weird condition, hmm O.o I don't remember us using negatives for the idx, but surely there's a reason.

Must be because of the Multiple Selections.

**Comment by 4taghavi** [comment]
This is not still fixed in autoComplete multiple checkbox selection, when first page loads if user instead of searching, press BackSpace button of keyboard if will throw an exception as  follows :

[2023-04-10T05:10:11.992Z] Error: System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetLast[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source)
   at Blazorise.Components.Autocomplete`2.OnTextKeyDownHandler(KeyboardEventArgs eventArgs)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

blazorise version 1.2.2

**Comment by David-Moreira** [comment]
> This is not still fixed in autoComplete multiple checkbox selection, when first page loads if user instead of searching, press BackSpace button of keyboard if will throw an exception as follows :
> 
> [2023-04-10T05:10:11.992Z] Error: System.ArgumentNullException: Value cannot be null. (Parameter 'source') at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument) at System.Linq.Enumerable.TryGetLast[TSource](IEnumerable`1 source, Boolean& found) at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source) at Blazorise.Components.Autocomplete`2.OnTextKeyDownHandler(KeyboardEventArgs eventArgs) at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task) at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task) at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
> 
> blazorise version 1.2.2

I will go ahead and open a seperate issue with this.
