### ISSUE TITLE
New add button is disappearing

### ISSUE THREAD

**Issue by yunusemrecaglar** [Megabit/Blazorise#4627]
I am using ABP frameworks, I added a button to the 'Toolbar' inside the 'PageHeader' tag in the .cs file. The button appears when I directly enter the page, but when I enter the page via the menu, the button is initially visible but then disappears. Can you help me with this? Screenshots are provided below.

![image](https://user-images.githubusercontent.com/84885139/221349400-e99d56e4-a7c0-443f-b6dd-f9379087718c.png)
![image](https://user-images.githubusercontent.com/84885139/221349443-6d4fb9ea-1fe9-4ab6-affa-f92fcea65358.png)

**Comment by stsrki** [comment]
Working in menus is fairly specific for the ABP framework. It would be best to question it on the ABP project pages.

**Comment by David-Moreira** [comment]
Hello @yunusemrecaglar I will be closing this, as this seems an issue more specific to the ABP framework, however if you happen to not be able to get your issue fixed or feel like it's an issue with **Blazorise**, please do feel free to reopen the issue.

We would also appreciate a repro in that case, so we can actually reproduce and help.
