### ISSUE TITLE
Autocomplete's external validation not working

### ISSUE THREAD

**Issue by mony-fx** [Megabit/Blazorise#4628]
I cannot use external validations Data Annotation Validator or FluentValidation

Validator shouldn't be set to None when there is no rule set. 
This will prevent validation coming from external validations.
`    
<Validation Validator="@(Validator ?? ValidationRule.None)" AsyncValidator="@AsyncValidator">
`

**Comment by stsrki** [comment]
The `Validator` and `AsyncValidator` have the highest priority over data-annotation. But only if they are defined. Can you post you code so that we can see how you use it?

**Comment by mony-fx** [comment]
Here is my code:
![image](https://user-images.githubusercontent.com/113479470/222018890-4d0288a8-e897-4688-a17c-710d284fb434.png)
![image](https://user-images.githubusercontent.com/113479470/222019012-7414d8bd-4cbc-4552-884e-2b1c59b5ed3c.png)

No validation showing coming from Data Annoation

![image](https://user-images.githubusercontent.com/113479470/222019086-55c298c2-e0e9-48fe-b931-711a3ad60a59.png)

I used this as an example by replacing Select to the AutoComplete component https://github.com/Megabit/Blazorise-Samples
[ValidationWithDataAnnotations.zip](https://github.com/Megabit/Blazorise/files/10856063/ValidationWithDataAnnotations.zip)

**Comment by David-Moreira** [comment]
I was just taking a brief look at `Autocomplete` validation, correct me if I'm wrong @stsrki 
but from what I can tell, in `Autocomplete` you either have to set the `Validator` or `AsyncValidator` parameters with your validation.
![image](https://user-images.githubusercontent.com/22283161/222297421-f010ec46-69e8-439c-9a7e-6357a950e180.png)
![image](https://user-images.githubusercontent.com/22283161/222297432-d601db67-b051-49f8-b95d-b681fa127348.png)
https://blazorise.com/docs/extensions/autocomplete

I believe Data Annotations aren't currently supported by `Autocomplete` in that case. Again correct me If I'm wrong.

Also I'd argue that we should remove the internal `Validator` and `Validator` / `AsyncValidator` and just have the validation work as regular Blazorise Validation would work, by wrapping with the `Validations` / `Validator` outside the `Autocomplete`.

**Comment by stsrki** [comment]
I must admit I misread the original comment. Autocomplete, at the moment, does not support data annotation. As @David-Moreira mentioned, you must use the `Validator` or `AsyncValidator` parameters with your validation.

**Comment by David-Moreira** [comment]
#4767 opened to track whether a validation refactor would be worth it. Closing issue.
