### ISSUE TITLE
The Accordion <AccordionToggle> not working as advertised

### ISSUE THREAD

**Issue by GilShalit** [Megabit/Blazorise#4629]
The <AccordionToggle> does not work as it does in the documentation:
1) It is only clickable on the heading text and not the entire width of the control
2) it lacks the opened or closed indicator

**To Reproduce**
1. create new Webassembly Blazor application in VisualStudio 2022
2. add the Blazorise bootstrap packages and follow all other instructions in 'Getting Started'
3. replace the code on Index.razor with the accordion Basic code example
4. run 

**Expected behavior**
The same accordion should be rendered as in the demo.
**_What I have noticed is that the accordion related styles are not applied to the Divs and buttons under the Accordion tag._**

**Also please provide a sample code or point us to a minimalistic GitHub repo
A repo is at: https://github.com/GilShalit/AccordionTest

**Screenshots**
The screenshot shows the button does not get the `accordion-button` class.
![image](https://user-images.githubusercontent.com/34002589/221539578-a4bc1caf-5c6f-4aad-b514-92ccf3a95622.png)

**Comment by stsrki** [comment]
In the documentation, we're using the Bootstrap 5 NuGet package. And in your project, you have installed the Bootstrap 4 version. That's why they look and behave differently. To install BS5, you can follow the guide at https://blazorise.com/docs/usage/bootstrap5

**Comment by GilShalit** [comment]
Thanks for the quick response, I have just learnt this from the closed issue at https://github.com/Megabit/Blazorise/issues/3132...

It might be helpful to mention this in the documentation or make it more prominent if it is already there.
