### ISSUE TITLE
Autocomplete - Setting selectedValue does not update selected item in the list (1.2.1)

### ISSUE THREAD

**Issue by guillaumebaril** [Megabit/Blazorise#4634]
**Describe the bug**
I need to set the selected value of the Autocomplete when I press a button. It works if I set the selectedValue, but it keeps the previously selected text. As a workaround, I tried setting the selectedText to the associated text, but as soon as I do that, the value is not updated anymore and "nothing" happens.

**To Reproduce**
First I type "Noah"
![image](https://user-images.githubusercontent.com/906761/221955448-f7ea5e32-589b-461c-9709-e6c5d3b985c1.png)

Then I click on the "Change name to Emma" button
![image](https://user-images.githubusercontent.com/906761/221955681-1eee06a2-ded4-4393-b5b1-46056f5c5639.png)

Then when I click on the autocomplete, it still shows "Noah" as the selected item. That's the bug.
![image](https://user-images.githubusercontent.com/906761/221955803-b7bb4a8f-4cc8-47ea-8f5c-689463bcdfc9.png)

If I try to set the SelectedText (or Search property) at the same time than when I set SelectedValue, it doesn't work (the selected value / selected text stays on Noah). That's the workaround I tried.

**Expected behavior**
When we click on the autocomplete, it should show the selected value in the list, not the previous one.

**Additional context**
Piece of code to reproduce the issue
```razor
@page "/counter"
@using BlazorApp1.Client;
@using Blazorise.Components

<PageTitle>Counter</PageTitle>

<Autocomplete @ref="_autocomplete"
              TItem="MyClass"
              TValue="int"
              Data="firstNames"
              ValueField="@((item) => item.Id)"
              TextField="@((item) => item.Name)"
              @bind-SelectedValue="@_selectedValue"
              @bind-SelectedText="@_selectedText"
              ConfirmKey="_confirmKeys"
              @onfocusout="@OnFocusOut" />

<Button Outline Clicked="OnClickedButton">Change name to Emma</Button>
<Button Outline Clicked="OnClearButton">Clear</Button>

@code {
    private Autocomplete<MyClass, int> _autocomplete;

    private int _previousValue = 0;
    private int _selectedValue;
    private string _selectedText;

    private string[] _confirmKeys = new string[]
    {
        "Enter", "NumpadEnter", "Tab"
    };

    private int currentCount = 0;

    private List<MyClass> firstNames = new List<MyClass>()
    {
        new MyClass(1, "Alice"), new MyClass(2, "Emma"), new MyClass(3, "Liam"), 
        new MyClass(4, "Olivia"), new MyClass(5, "Noah"), new MyClass(6, "Ethan"),
        new MyClass(7, "Mason"), new MyClass(8, "Mia"), new MyClass(9, "Oliver")
    };

    private void OnFocusOut()
    {
        if (_previousValue != _selectedValue)
        {
            Console.WriteLine($"{_selectedValue}");
            _previousValue = _selectedValue;
        }
    }

    private void OnClickedButton()
    {
        var val = "Emma";

        var item = _autocomplete.GetItemByText(val);

        _selectedValue = item.Id;
        _selectedText = item.Name;
    }

    private void OnClearButton()
    {
        _autocomplete.Clear();
    }
}
```

**Comment by abhimanyu891998** [comment]
I am facing a similar issue, I am using multi select autocomplete and when I programatically try to set the autocomplete value, it keeps changing to the previous set value.
