### ISSUE TITLE
Datagrid lines miss-aligned if emty DataGridCommandColum

### ISSUE THREAD

**Issue by f4n0** [Megabit/Blazorise#4636]
**Describe the bug**

![image](https://user-images.githubusercontent.com/36199751/222107388-40eacbdb-e9ee-466a-9fe6-f6f94d73f045.png)
as you see, there is some UI problems with the lines where there needs to be the DataGridCommands. 

(never seen in previous versions) 

The murder is this class "d-flex"
![image](https://user-images.githubusercontent.com/36199751/222108089-6c4ea414-83d8-47c3-bb2e-7d74dfbd6c63.png)

if removed (or adding content) the lines will be aligned as the others in the table

**To Reproduce**
4. See an error

**Expected behavior**

Also please provide a sample code or point us to a minimalistic GitHub repo

**Screenshots**

**Additional context**

**Comment by David-Moreira** [comment]
@f4f0 Have you retested this issue? Is everything working ok now?

**Comment by f4n0** [comment]
yes, now it is working

**Comment by stsrki** [comment]
Excellent; thank you for letting us know. Closing the ticket now.
