### ISSUE TITLE
Autocomplete - Strange behaviour with SelectedValue triggering (1.2.1)

### ISSUE THREAD

**Issue by guillaumebaril** [Megabit/Blazorise#4640]
**Describe the bug**
I've got a strange behaviour and I was wondering if it was intended:

While typing in the field, as soon as there is a match, it triggers the SelectedValue event. It is not the same behaviour as in 1.0.6 and is kind of problematic in my use cases. I want to perform a somewhat long operation after the user has finished selecting a value (_see what I mean in the Expected behaviour section_).

**How to reproduce**
Let say I have this list of values: 
"1"
"10"
"100"
"1000"
And the user types "1000"

Each match will trigger the SelectedValue event, possibly resulting in a very poor UX.

**Expected behavior**
I think the SelectedValue event should only be triggered when the user has _finished_ selecting a value. That could mean : 
- User has clicked on the value in the dropdown list
- User has pressed a confirm keys (_tab, enter, ..._)
- Focus is lost while a valid value has been entered (less sure about that one)

**Suggestion**
I would suggest adding a parameter to allow this behaviour, but I'm open to any workaround! 

Thanks !

**Comment by David-Moreira** [comment]
We have a section where we list the expected change trigger.
![image](https://user-images.githubusercontent.com/22283161/222957088-b9f9bc9e-24da-4270-9ed1-36178bdbef27.png)
https://blazorise.com/docs/specifications/autocomplete

Are you using FreeTyping by any chance? It will trigger everytime in that case.

If this does not help, can you please provide a simple repro? Thank you!

**Comment by David-Moreira** [comment]
Actually that seems to be an error in the docs, the second section header should read SelectedTextChanged. It seems you are right. 

Can you please provide a repro? Appreciate it!

**Comment by guillaumebaril** [comment]
Hi, here is the code to reproduce what I think is an issue (same result if I change the parameter AutoPreSelect)

```razor
@page "/Test"

@using Blazorise.Components

<Autocomplete TItem="MyClass"
              TValue="MyClass"
              Data="_data"
              ValueField="@((item) => item)"
              TextField="@((item) => item.Name)"
              SelectedValue="@_selectedValue"
              SelectedValueChanged="OnSelectedValueChanged"
              @bind-SelectedText="@_selectedText"
              AutoPreSelect="false"
              AutoSelectFirstItem="false" />

@code {

    public class MyClass
    {
        public MyClass(int id, string name)
        {
            Id = id;
            Name = name;
        }
        public int Id { get; set; }
        public string Name { get; set; }
    }

    private readonly List<MyClass> _data = new()
    {
        new MyClass(1, "1"), new MyClass(2, "10"), new MyClass(3, "100"),
        new MyClass(4, "1000"), new MyClass(5, "10000"), new MyClass(6, "100000"),
        new MyClass(7, "1000000"), new MyClass(8, "10000000"), new MyClass(9, "100000000"), new MyClass(10, "1000000000")
    };

    private MyClass _selectedValue { get; set; }
    private string _selectedText { get; set; }

    private void OnSelectedValueChanged(MyClass value)
    {
        Console.WriteLine($"{DateTime.Now}: Selected Value = '{value.Name}'");
    }
}
```

Here is the console output that happens for each match
![image](https://user-images.githubusercontent.com/906761/223120732-a2b979ed-e286-4f70-99a9-fb029b85d627.png)

I have also confirmed in Blazorise source code that there is no workaround possible, the code selected in red is where the auto selection happens : 
![image](https://user-images.githubusercontent.com/906761/223121364-62b2057a-0c0b-4903-902a-720aed551b2c.png)

**Comment by guillaumebaril** [comment]
Any news concerning this issue?

**Comment by David-Moreira** [comment]
Hello, not yet. Thanks for the code.
Will let you know once we go over it.

**Comment by David-Moreira** [comment]
You're right. @stsrki I guess this is one of those behavioural changes that snuck in #3988
I think the old behaviour makes way more sense. It's expected that the **SelectedValue** triggers upon explicit **Confirm**. I would go ahead and revert this unitended behavior, agree?

**Comment by stsrki** [comment]
> I think the old behaviour makes way more sense. It's expected that the **SelectedValue** triggers upon explicit **Confirm**. I would go ahead and revert this unitended behavior, agree?

I definitely agree. Don't know how we didn't notice that big of a change before. Also, write tests so that i doesn't happen again

**Comment by David-Moreira** [comment]
> > I think the old behaviour makes way more sense. It's expected that the **SelectedValue** triggers upon explicit **Confirm**. I would go ahead and revert this unitended behavior, agree?
> 
> I definitely agree. Don't know how we didn't notice that big of a change before. Also, write tests so that i doesn't happen again

I mean, it's not noticeable in regular cases, this only happens when a value is immediately found on the options available.
For example:
If we had **John** and **Johny** and wanted to Select **Jonhy**, **SelectedValue** would trigger twice, one for **John** and another for **Johny**. 

And I guess if someone is not actively doing any logic in SelectedValueChanged, it can easily go unnoticed.

**Comment by guillaumebaril** [comment]
It is not completely fixed. For example, using this code : 

```razor
@page "/Test"

@using Blazorise.Components;
<Autocomplete @ref="autocompleteRef"
              TItem="MyClass"
              TValue="MyClass"
              Data="_data"
              ValueField="@((item) => item)"
              TextField="@((item) => item?.Name)"
              SelectedValue="@_selectedValue"
              SelectedValueChanged="OnSelectedValueChanged"
              AutoPreSelect="true"
              AutoSelectFirstItem="false"
              ConfirmKey="_confirmKeys" />

@code {
    private Autocomplete<MyClass, MyClass> autocompleteRef;
    private readonly string[] _confirmKeys = new string[]
    {
            "Enter", "NumpadEnter", "Tab"
    };

    public class MyClass
    {
        public MyClass(int id, string name)
        {
            Id = id;
            Name = name;
        }
        public int Id { get; set; }
        public string Name { get; set; }
    }

    private readonly List<MyClass> _data = new()
    {
        new MyClass(1, "Hello"), new MyClass(2, "World")
    };

    private MyClass _selectedValue { get; set; }
    private string _selectedText { get; set; }

    private void OnSelectedValueChanged(MyClass value)
    {
        _selectedValue = value;
        Console.WriteLine($"{DateTime.Now}: Selected Value = '{value?.Name}'");
    }
}
```

I type "Hel", then tab out. It correctly invoke SelectedValueChanged handler.
I click in the autocomplete input, then hit "backspace" once (the text is now _Hell_), it **incorrectly** immediately invoke SelectedValueChanged handler.
Then I type "o" (the text is now _Hello_), it doesn't trigger "SelectedValueChanged handler" immediately, but triggers it when I use a confirm key (tab/enter).

I'm open for a dirty work around that I can implement myself, but I don't see how can I correctly detect that case. Got any idea? 

Thanks!

**Comment by David-Moreira** [comment]
You're right,
so when you press backspace it immediately goes, "Hey this value is invalid and triggers `SelectedValueChanged` with the default value", I guess it should only happen on commit, **confirm key** or **blur** as the user as not made the decision yet. @stsrki agree?

**Comment by stsrki** [comment]
I agree; it shouldn't trigger `SelectedValueChanged` on the back key.

**Comment by guillaumebaril** [comment]
Also, not sure if I should log this in a different issue, but if I "shift-tab" (to go to the previous field), it doesn't get registered as a _confirm key_ even if "Tab" is in the confirm keys property. Please let me know if you need a different issue.

**Comment by David-Moreira** [comment]
> Also, not sure if I should log this in a different issue, but if I "shift-tab" (to go to the previous field), it doesn't get registered as a _confirm key_ even if "Tab" is in the confirm keys property. Please let me know if you need a different issue.

Can you open a different issue, please? Also I'm not sure that's an issue, in theory **shift-tab** is indeed a different key press then just **Tab**?
