### ISSUE TITLE
MessageService with no styles

### ISSUE THREAD

**Issue by JCQuirozL** [Megabit/Blazorise#4641]
**Describe the bug**
Is there any way to have the styles of a MessageService without internet connection, I have to deploy a blazor app where I include blazorise, but the server doesn't have internet connection (for reasons beyond me) and I realized it doesn't have the styles.

**Expected behavior**
To have the MessageService styles offline

![blazor](https://user-images.githubusercontent.com/82295997/222609290-e98da934-f987-4ebd-9511-3012b809a267.png)

**Comment by stsrki** [comment]
Message service doesn't have any styles on its own. It uses the styles from Bootstrap. To have it offline, you can download necessary `.css` and `.js` files and place them into the `wwwroot` of your Blazor app and then serve them from there.

**Comment by JCQuirozL** [comment]
Thank you, I was inspecting the page I realized about that.
