### ISSUE TITLE
Localized MessageService dialog

### ISSUE THREAD

**Issue by tacoWanneeJama** [Megabit/Blazorise#4645]
![image](https://user-images.githubusercontent.com/76042577/222691920-1178a545-b7a0-475b-abdf-02c905276e83.png)
I like to localize the text on the buttons of MessageService. The text "Cancel" and "Yes". My customer likes to read it in my local language.

Setting:```LocalizationService.ChangeLanguage("nl");``` on whatever level does not solve this.

**Comment by stsrki** [comment]
You can localize it through the options argument.

![image](https://user-images.githubusercontent.com/900302/222694192-050dab75-92e0-40b2-aaba-fa3c11778a2d.png)

**Comment by tacoWanneeJama** [comment]
Thank for a working solution.
Localization would be a much nicer solution I think....

**Comment by stsrki** [comment]
I agree. It's going on the backlog for the v1.3.
