### ISSUE TITLE
DatePicker Calendar Pop-up is shown in bottom of page

### ISSUE THREAD

**Issue by faarbaek** [Megabit/Blazorise#4647]
**Describe the bug**
When clicking the DatePicker field, the calendar pop-up is shown in bottom of screen and only visible when scrolling down.

**To Reproduce**
A simple DatePicker tag will produce the issue, when the user clicks the DatePicker.

```html
<DatePicker TValue="DateTime" />
```

**Expected behavior**
The Calendar should be shown just below the DatePicker field

**Comment by stsrki** [comment]
I cannot reproduce it. Does your project have any CSS styles that can interfere with it?

**Comment by faarbaek** [comment]
We do not have any special CSS. I can reproduce it with the following repo: https://github.com/faarbaek/BlazoriseDatePickerTest

**Comment by stsrki** [comment]
> We do not have any special CSS. I can reproduce it with the following repo: https://github.com/faarbaek/BlazoriseDatePickerTest

It seems it's a private repository. I cannot access it.

**Comment by faarbaek** [comment]
Sorry about that. Should be public now

**Comment by stsrki** [comment]
I was able to run it. It happens because we apply the `static` position to the calendar menu. I will try to see if it can be fixed in 1.2. Otherwise, we will have to make it optional in 1.3.

**Comment by blenke** [comment]
Is there a work around for this? Seems like datepicker and timepicker cannot be used in 1.2 like this. However on the documentation page it seems to work.

**Comment by faarbaek** [comment]
> Is there a work around for this? Seems like datepicker and timepicker cannot be used in 1.2 like this. However on the documentation page it seems to work.

I am using the following temporary CSS to fix it
```css
.flatpickr-calendar.static {
    top: unset;
}
```

**Comment by blenke** [comment]
Thanks , that works.

**Comment by stsrki** [comment]
> > Is there a work around for this? Seems like datepicker and timepicker cannot be used in 1.2 like this. However on the documentation page it seems to work.
> 
> I am using the following temporary CSS to fix it
> 
> ```css
> .flatpickr-calendar.static {
>     top: unset;
> }
> ```

That's a good workaround. Thanks for sharing.
