### ISSUE TITLE
Generated QR code not scannable by 3rd party library

### ISSUE THREAD

**Issue by oaldrian** [Megabit/Blazorise#4658]
**Describe the bug**
I tried to generate a QR code with Blazorise, and scan it back with https://github.com/sabitertan/BlazorBarcodeScanner and the scanner is not able to pick up a valid QR code. Tried it with the qr from blazorise docs, and it also didn't work. the same qr code content wise "https://blazorise.com/" but generated by another code generator https://goqr.me/ (with the same error correction level) looks different (see screenshot), and this other one scans without issues. 

Even setting error correction level to highest possible in Blazorise does not make the qr scannable.

I am not 100% that this is a bug, but I don't know enough about QR codes to definitely say that.

What confuses me the most, is that the QRs look different, see screenshot below.

Camera quality / print quality differences were ruled out by presenting the QR codes via virtual camera (OBS)

**To Reproduce**
see description

**Expected behavior**
QR Code is scannable with 3rd party library

**Screenshots**
![image](https://user-images.githubusercontent.com/44060248/223495574-086b75f4-b970-484b-a70d-ff6462791d1d.png)

**Comment by stsrki** [comment]
My first guess is that the problem might be in [BlazorBarcodeScanner](https://github.com/sabitertan/BlazorBarcodeScanner). I have tried several different QR Scanners, and they all work the same without any issues.

**Comment by oaldrian** [comment]
can definitely be, just weird that it works fine with other QR generators.
What does Blazorise use as QR generator, or is it natively coded? Just want to investigate a bit further.

**Comment by stsrki** [comment]
> What does Blazorise use as QR generator, or is it natively coded?

We use the library https://qr-code-styling.com/
