### ISSUE TITLE
Unable to create tests for Modals due to dependency on injected internal ModalSharedContext

### ISSUE THREAD

**Issue by Judas1337** [Megabit/Blazorise#4660]
**Describe the bug**
Writing tests for own components using Modal is not possible due to the dependency on the injected class ModalSharedContext since it is marked as internal.

Ran into this when trying suggestion from @David-Moreira in issue: https://github.com/Megabit/Blazorise/issues/3327

**To Reproduce**
1. Create a component using Modal
2. In a test project using bUnit (like in Blazorise.Tests) create a test for the component in 1
3. Notice 3 different outcomes when rendering
a. If ModalSharedContext has not been added to services:
"System.InvalidOperationException : Cannot provide a value for property 'ModalContext' on type 'Blazorise.Modal'. There is no registered service of type 'Blazorise.ModalSharedContext'." 
b. If ModalShareContext is added to services:
"'ModalSharedContext' is inaccessible due to its protection level"
c. If Services.AddBlazorise() is used:
"System.InvalidOperationException : Cannot consume scoped service 'Microsoft.AspNetCore.Components.IComponentActivator' from singleton 'Bunit.Rendering.WebTestRenderer'."

**Expected behavior**
Be able in a test scenario to render a component that uses the Modal component.

**Screenshots**
Component:
![image](https://user-images.githubusercontent.com/6430943/223682791-0c2bff04-521e-472b-af0e-fddd3fad2f41.png)

Tests for cases A, B and C:
![image](https://user-images.githubusercontent.com/6430943/223684768-912eaf19-0948-476a-a236-ce57b14b79e9.png)

**Additional context**
Notice that all dependencies presented in Blazorise.Tests' BlazoriseConfig is either based on public interfaces or public classes. ModalSharedContext is the seemingly only dependency marked as internal and not behind an interface.

ModalSharedContext marked as internal: https://github.com/Megabit/Blazorise/blob/master/Source/Blazorise/Components/Modal/ModalSharedContext.cs#L6
Modal dependency on ModalSharedContext: https://github.com/Megabit/Blazorise/blob/master/Source/Blazorise/Components/Modal/Modal.razor.cs#L485
Blazorise allowing internals visible to Blazorise.Tests: https://github.com/Megabit/Blazorise/blob/master/Source/Blazorise/Properties/AssemblyInfo.cs#L10
Blazorise.Tests' setup of Blazorise Configuration: https://github.com/Megabit/Blazorise/blob/master/Tests/Blazorise.Tests/Helpers/BlazoriseConfig.cs#L40

**Comment by stsrki** [comment]
That's a valid point. I think it should be safe to mark it as public, even for 1.2 patches.

**Comment by Judas1337** [comment]
Thank you!
