### ISSUE TITLE
MessageProvider has exception / error when loading app / page

### ISSUE THREAD

**Issue by GeertvanHorrik** [Megabit/Blazorise#4682]
**Describe the bug**

When using the `MessageProvider` provider (in combination with AntDesign), an error is logged to the console when Serilog logging is enabled:

```
[ Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer ]  Unhandled exception rendering component:  Value cannot be null. (Parameter 'jsObjectReference') 
 System.ArgumentNullException: Value cannot be null. (Parameter 'jsObjectReference')
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at Blazorise.Modules.BaseJSModule.InvokeSafeVoidAsync(String identifier, Object[] args)
   at Blazorise.Button.<OnInitialized>b__12_0()
   at Blazorise.BaseAfterRenderComponent.OnAfterRenderAsync(Boolean firstRender)
   at Blazorise.BaseComponent.OnAfterRenderAsync(Boolean firstRender)
```

Usage:

```
<MyApp.Shared.ThemeProvider>
    <Router AppAssembly="@typeof(Program).Assembly" PreferExactMatches="@true">
        <Found Context="routeData">
            <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
        </Found>
        <NotFound>
            <LayoutView Layout="@typeof(MainLayout)">
                <p>Sorry, there's nothing at this address.</p>
            </LayoutView>
        </NotFound>
    </Router>

    <MessageProvider />
    <NotificationProvider />
</MyApp.Shared.ThemeProvider>
```

The error goes away when I remove the `<MessageProvider />` line.

**To Reproduce**

See code above

**Expected behavior**

The button / message provider should never cause exceptions.

**Comment by GeertvanHorrik** [comment]
Trying to create a repro with the demo app.

**Comment by GeertvanHorrik** [comment]
When checking the BaseJSModule.InvokeSafeVoid, and the Button component, it looks like the app has issues loading the module for Button, but it's included:

```
<script src="_content/Blazorise/button.js?v=1.2.1.0" type="module"></script>
```

Continuing investigation...

**Comment by David-Moreira** [comment]
Please make sure that you've included every necessary dependency that's in the docs.
Yes, please provide a repro, so we can right into it and help you, thanks.

**Comment by GeertvanHorrik** [comment]
Will try. Did a double check on all modules, they seem to be loaded, but trying to pinpoint what causes this (authentication, the message provider, etc). Need to strip down the solution until I reach a point where I can reliably repro. Also using .NET 6 instead of 7, will investigate if that also makes a difference.

**Comment by stsrki** [comment]
Closing the issue since it is quite old now. If you still have the problem please reopen.
