### ISSUE TITLE
Two buttons on FileEdit

### ISSUE THREAD

**Issue by sturlath** [Megabit/Blazorise#4694]
We are getting two buttons on the FileEdit. Is this a bug or something I´m doing incorrectly?

Here is how it looks
![image](https://user-images.githubusercontent.com/2386572/227514334-08240c2a-2d40-47bb-902f-fdeb3057299b.png)

The code 
```xml
 <Tooltip Text="@L["UploadEventPoster"]">
    <Validation Validator="@ValidatePosterUpload">
        <FileEdit Filter="image/jpeg, image/jpg, image/gif" Changed="@OnPosterImageChanged" Multiple="false">
            <Feedback>
                <FieldHelp>@L["EventPosterFieldHelp"]</FieldHelp>
                <ValidationError />
            </Feedback>
        </FileEdit>
    </Validation>
</Tooltip>
```

Its like this also when I use English localization.
![image](https://user-images.githubusercontent.com/2386572/227515254-3621447c-a308-44c1-953b-53e525ce6ce8.png)

And here is how the html looks like
![image](https://user-images.githubusercontent.com/2386572/227514737-9870ad4c-353f-4bd0-81f1-70e621f72c3b.png)

Version: **1.2.2**
Bootstrap5
Abp.io Commercial

**Comment by stsrki** [comment]
What browser you have?

**Comment by sturlath** [comment]
Microsoft Edge
Version 111.0.1661.44 (Official build) (64-bit)

**Comment by stsrki** [comment]
Try clearing the cache. Or rebuild the ABP bundle CSS file. We have recently made some changed to file input CSS, so maybe they don't get applied.

**Comment by sturlath** [comment]
Yes running `abp bundle` in the Blazor project solved this. Thank you. Will close
