### ISSUE TITLE
Trendline does not work in Blazorise 1.2.1

### ISSUE THREAD

**Issue by ledpup** [Megabit/Blazorise#4697]
When using the trendline plugin on charts, there is an error with the color property. This was found when updating Blazorise to a new version of previously working trendlines.

**System.InvalidOperationException: The ignore condition 'JsonIgnoreCondition.WhenWritingNull' is not valid on value-type member 'Color' on type 'Blazorise.Charts.Trendline.ChartTrendlineData'. Consider using 'JsonIgnoreCondition.WhenWritingDefault'.**

**Comment by stsrki** [comment]
Can you share some code so that we can reproduce the error?

**Comment by ledpup** [comment]
> Can you share some code so that we can reproduce the error?

The sample code on the docs doesn't work any more, with the same error. https://blazorise.com/docs/extensions/chart-trendline

**Comment by stsrki** [comment]
It is fixed for 1.2.3 release.
