### ISSUE TITLE
Is it possible to define "help text" below the fields when editing with a datagrid?

### ISSUE THREAD

**Issue by ms4sman** [Megabit/Blazorise#4700]
EDIT: Sorry, bumped the enter key before I was ready to submit

This isn't really related to any problem. And I know I can use a custom editTemplate to do this, but I'd like to (ideally) not have to do that to define help text.

**Describe the solution you'd like**
Ideally I'd like to see a parameter for the DataGridColumn that defines that help text. I couldn't find anything so far in searching the docs but it can sometimes be a bit confusing to find things. I also didn't find anything like this in the DataGrid demo website

**Comment by stsrki** [comment]
Just to make sure. Do you want this part?

![image](https://user-images.githubusercontent.com/900302/227848771-1c44cef2-050b-4003-9a5c-5b9fa8b64977.png)

**Comment by ms4sman** [comment]
Yes, that's what I'm hoping for! Thanks!

**Comment by ms4sman** [comment]
Any update on this?

**Comment by stsrki** [comment]
We only had a little time to make it in 1.3, but we will make it for 1.4. Until then, you can workaround it with the use of Edittemplate and then manually write `Field` with `FieldHelp` inside of it.

**Comment by ms4sman** [comment]
Ok thank you for the follow-up!

**Comment by stsrki** [comment]
Hopefully the Inline edit mode will not be too hard. From what I can think of, the new help-line could alter the height of the cell and row. Making it "jumpy".
