### ISSUE TITLE
BarDropdownToggle Clicked event does not fire

### ISSUE THREAD

**Issue by ivancavlek** [Megabit/Blazorise#4707]
**Describe the bug**
BarDropdownToggle Clicked event does not fire. After clicking the toggle for BarDropdownToggle, nothing happens. This is not the case with other toggles.

**To Reproduce**
```C#
@inherits LayoutComponentBase

<Layout>
    <LayoutHeader>
        <Bar Background="Background.Primary"
                Breakpoint="Breakpoint.Desktop"
                ThemeContrast="ThemeContrast.Light">
            <BarToggler />
            <BarMenu>
                <BarStart>
                    <BarItem>
                        <BarDropdown>
                            <BarDropdownToggle Clicked="OnLoadAppLinks">
                            </BarDropdownToggle>
                            <BarDropdownMenu>
                            </BarDropdownMenu>
                        </BarDropdown>
                    </BarItem>
                </BarStart>
            </BarMenu>
        </Bar>
    </LayoutHeader>
    <LayoutContent Margin="Margin.Is5.FromTop.Is5.FromBottom">
        <CascadingValue IsFixed="true"
                        Value="this">
            <LoadingIndicator FullScreen="true">
                @Body
            </LoadingIndicator>
        </CascadingValue>
    </LayoutContent>
</Layout>

@code
{
    private void OnLoadAppLinks() =>
        Console.WriteLine("Entered");
}
```

**Comment by stsrki** [comment]
This might be because if the changes we have made in the last release. @David-Moreira can you look into this?

**Comment by David-Moreira** [comment]
Hey @stsrki 
For a moment I thought the same, but apparently is due to this:
![image](https://user-images.githubusercontent.com/22283161/229098988-84db4883-25f4-45ae-be97-d6ba0452b7e2.png)

If a `ParentDropdown` exists the `Clicked` isn't triggered. What do you think? I believe we should still trigger it.

**Comment by David-Moreira** [comment]
Also the recent changes were #4655 which is **BarToggler**, not **BarDropdownToggler**.

**Comment by stsrki** [comment]
> I believe we should still trigger it.

Yes, the click should still be triggered.

**Comment by devantler** [comment]
Any chance that you can make a prerelease for this fix? 🙏🏻

**Comment by stsrki** [comment]
> Any chance that you can make a prerelease for this fix? 🙏🏻

Can't promise but I will try to make it.

**Comment by devantler** [comment]
> > Any chance that you can make a prerelease for this fix? 🙏🏻
> 
> 
> 
> Can't promise but I will try to make it.

Fair enough! And thanks

**Comment by devantler** [comment]
I understand if it is not a priority to do a pre-release just for this issue, but do you know when we can expect a new release that includes this fix?

**Comment by stsrki** [comment]
We plan to release it next week.

**Comment by devantler** [comment]
Thanks, that is awesome news!
