### ISSUE TITLE
TreeView in 1.2.x does not update when adding items

### ISSUE THREAD

**Issue by AlbertoPa** [Megabit/Blazorise#4713]
**Describe the bug**
The addition of items to the TreeView does not produce any change to the list of visible items even triggering StateHasChanged().

This breaks compatibility with previous versions, since the TreeView was properly updated in 1.1.x.

**To Reproduce**
1. Run the test case here https://github.com/AlbertoPa/TreeViewBug

**Expected behavior**
Adding items should trigger a tree update, at least after invoking StateHasChanged.

**Comment by stsrki** [comment]
We're already trying to fix this behavior with #4702

Apart from listening for list changes with INotifyCollectionChanged, the only way to know that the list has changed is to check for the list hashcode. For example, every time a `Nodes` parameter is received, we calculate an entire list hashcode and cache it. The next time a `Nodes` parameter is received, we repeat it and compare. The downside could be a performance. @David-Moreira what do you think?

**Comment by AlbertoPa** [comment]
Thank you @stsrki. 

For my use case, a way to manually trigger a rerender of the tree would suffice.

In the current implementation I have not been successful when I tried to force the tree to update based on the new content.

**Comment by David-Moreira** [comment]
> We're already trying to fix this behavior with #4702
> 
> Apart from listening for list changes with INotifyCollectionChanged, the only way to know that the list has changed is to check for the list hashcode. For example, every time a `Nodes` parameter is received, we calculate an entire list hashcode and cache it. The next time a `Nodes` parameter is received, we repeat it and compare. The downside could be a performance. @David-Moreira what do you think?

Well the observable should be enough for people that need to listen for changes when it's mutation of a collection add / remove etc...

I don't like the idea of incurring the cost of calculating the hash and it'd be challenging to have it be unique without any special user defined keys..

We could instead have a method like in Datagrid? Reload?

**Comment by stsrki** [comment]
We can only add `Reload` in 1.3, as we can't change the API in 1.2.
