### ISSUE TITLE
Docs: investigate why sorting page is crashing

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#4721]
On our docs page https://blazorise.com/docs/extensions/datagrid/features/sorting every couple of days the error happens and we have to restart the app on IIS to be able to fix it. We need to find the issue.

**Comment by David-Moreira** [comment]
Well what's the error? How do you know its this page? It's the last error you got registered on some. Log?

**Comment by stsrki** [comment]
Because it happens only on this page.

**Comment by David-Moreira** [comment]
Did you fix this yet like we talked?

**Comment by stsrki** [comment]
Yes, it seems from the logs that this error is gone. Closing it.
