### ISSUE TITLE
Add RowSpan and ColumnSpan on the DataGridColumn

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#4727]
I don't think it would be possible to do it at the moment. There is no way to control the `td` outside of DataGrid. We would have to add new APIs on DataGridColumn

- `RowSpan`, and
- `ColumnSpan`

It is not such a bad idea to have.

Also, it seems we lack an `Attributes` parameter to catch all custom HTML attributes missing from our API. I will open a new ticket to add it to the next milestone.

_Originally posted by @stsrki in https://github.com/Megabit/Blazorise/discussions/4726#discussioncomment-5564421_

**Comment by steal4life** [comment]
After conducting thorough testing, we have concluded that adding parameters such as row span and column span to the Blazorise Datagrid does not make sense. In fact, it can even break the functionality of the Datagrid.

The Datagrid is designed to display tabular data in a structured and organized manner. Each cell in the Datagrid represents a unique piece of data, and modifying the row span or column span would disrupt this structure.

Furthermore, the Datagrid provides several powerful features for sorting, filtering, and manipulating data, all of which rely on the consistent and predictable structure of the Datagrid. Adding row span and column span would make it much more difficult to implement these features and could lead to unexpected behavior.

Therefore, based on our testing and analysis, we recommend against adding row span and column span to the Blazorise Datagrid. Instead, we suggest exploring other alternatives that are better suited to the task at hand.

![image](https://user-images.githubusercontent.com/79018897/232738887-a2976319-7422-4deb-851e-d417b3e9e0ec.png)
