### ISSUE TITLE
Question DataGrid `SelectedRowChanged` and `SelectedRowsChanged`

### ISSUE THREAD

**Issue by fdq09eca** [Megabit/Blazorise#4739]
Hi, I have an object like the following:
```cs
  public ResultRecord(string identifier, int recordId, string title, string @abstract, double score, bool isSelected, bool hasGeoServices) {
      this.Identifier = identifier;
      this.Id = recordId;
      this.Title = title;
      this.Abstract = @abstract;
      this.Score = score;
      this.IsSelected = isSelected;
      this.HasGeoServices = hasGeoServices;
    }
```

I want to toggle the `IsSelected` property by the `SelectedRowChanged` EventCallBack. How may I do so?
I could not find any related documentation, it would be great if anyone could show some pointers.

**Comment by David-Moreira** [comment]
Hello,
You should be able to implement a field or property that targets the currently SelectedRow. Each time the SelectedRowChanhed is triggered you can set the previous selected row selected property to false and the new one to true. This should be enough.

Does this help?
