### ISSUE TITLE
Documentation for `Addon` to contain `Validation` info

### ISSUE THREAD

**Issue by oaldrian** [Megabit/Blazorise#4740]
**Is your feature request related to a problem? Please describe.**
When working with `Addon` and `Validation`, there are a few extra steps to take to make it visually "correct".
These are described in https://github.com/Megabit/Blazorise/issues/4106

**Describe the solution you'd like**
The solution (or a different one, that has a similar result) of https://github.com/Megabit/Blazorise/issues/4106 should be added to the `Addon` docs, as apart from this issue the info is not easily available.

**Comment by sturlath** [comment]
I guess this “solves” this one https://github.com/Megabit/Blazorise/issues/3802 right?

**Comment by stsrki** [comment]
@sturlath Yes, it should work with #3802. But you will have to adjust the Addons structure according to the documentation example.

**Comment by sturlath** [comment]
@stsrki Just tried this with 1.3.1 and this code here does not work. [And I can´t see better than your validation example doesn´t either](https://blazorise.com/docs/components/addon).. 

```xml
<Column>
    <Field>
        <FieldLabel>@L["StartingDate"]</FieldLabel>
        <Validation Validator="@ValidateEventStartingDate">
            <Addons>
                <Addon AddonType="AddonType.Body">
                    <DatePicker @ref="@startingDatePicker" TValue="DateTime?" InputMode="DateInputMode.Date" Date="@NewStreamEvent.StartingDate" DateChanged="@OnStartingDateChanged" DisplayFormat="dd-MM-Y" Disabled="@DisabledMode">
                    </DatePicker>
                </Addon>
                <Addon AddonType="AddonType.End">
                    <Button Color="Color.Light" Clicked="@(()=>startingDatePicker.ToggleAsync())">
                        <Icon Name="IconName.CalendarDay" />
                    </Button>
                </Addon>
            </Addons>
            <ValidationNone></ValidationNone>
            <ValidationSuccess></ValidationSuccess>
            <ValidationError>@L["PleaseSelectValidFutureStartingDateForEventDate"]</ValidationError>
        </Validation>
    </Field>
</Column>
```


```csharp
  private void ValidateEventStartingDate(ValidatorEventArgs e)
  {
      if (StartingDateInPastNotAllowed)
      {
          if (!NewStreamEvent.StartingDate.HasValue || NewStreamEvent.StartingDate.Value.DayOfYear < Clock.Now.DayOfYear)
          {
              e.Status = ValidationStatus.Error;
          }
          else
          {
              e.Status = ValidationStatus.Success;
          }
      }
  }
```

<img width="284" alt="image" src="https://github.com/Megabit/Blazorise/assets/2386572/3067c05f-5947-4aa0-9ce9-145432a0f88b">
