### ISSUE TITLE
Datagrid Inline edit, not using Edit Template

### ISSUE THREAD

**Issue by f4n0** [Megabit/Blazorise#4746]
**Describe the bug**
Hi, 
I've just find out that if I use the Edit Mode "Inline" the Edit template will not be used. 
Am I missing something? 

To add some context: 
I'm adding to a datagrid a custom column like the command one (to display other buttons). I need this to be hidden when the row is being edited. I've added to the display template an If in order to show only if the field is not a button. this will work if the edit mode is Form (or popup) but not inline

**Comment by David-Moreira** [comment]
@f4n0 It should indeed use the Edit Template, as such can you please provide a repro? It might be something very specific you're trying.

Now about you're original use case, maybe you just need to set your new column `IsEditable` to false? And it should be ommited from the editting columns?
