### ISSUE TITLE
FileEdit resets in WriteToStreamAsync example

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#4748]
On our page, for example WriteToStreamAsync 

https://blazorise.com/docs/components/file

If we select the file, the filename will show briefly, and then it will be cleared.

**Comment by David-Moreira** [comment]
Isn't that the `AutoReset` feature?

**Comment by David-Moreira** [comment]
![image](https://user-images.githubusercontent.com/22283161/233616977-c2e5416b-ddc0-4cb0-9bc5-296017bdf751.png)

**Comment by stsrki** [comment]
Haha yeah, that works. Thanks
