### ISSUE TITLE
Localization of "'No file chosen" missing

### ISSUE THREAD

**Issue by oaldrian** [Megabit/Blazorise#4756]
**Describe the bug**
![image](https://user-images.githubusercontent.com/44060248/235251425-0ab4838c-155e-4356-bcfe-016de5c2ac23.png)

**To Reproduce**
it is visible in the docs for localization 

**Expected behavior**
localized string

**Comment by stsrki** [comment]
That part of the input element is controlled by the browser shadow DOM so we don't have much freedom to change it. In any case, we will do our best.

**Comment by stsrki** [comment]
They are closing until Bootstrap fixes it natively.
