### ISSUE TITLE
SelectList SelectedValueChanged command not working in DataGrid

### ISSUE THREAD

**Issue by JCQuirozL** [Megabit/Blazorise#4763]
**Describe the bug**
Hello everyone, I have this compile error when I try to make the EventCallBack to the SelectedValueChanged command in a DataGrid, and I know that is the SelectedValueChanged command because when a remove it, it runs perfectly, but it doesn't refresh the DataGrid, so can you guys please tell me what am I doing wrong please? Thanks in advance

**Expected behavior**
To run succesfully the blazor app

```
<SelectList` Data="@AllGroups"
                            Class="background"
                            TextField="@((item)=>item.Name)"
                            ValueField="@((item)=>item.Id)"
                            SelectedValue="@((int)((CellEditContext)context).CellValue)"
                            SelectedValueChanged="@(e => {context.CellValue = Convert.ToInt32(e);})" />

IList<CSCGroups> AllGroups;
AllGroups = new List<CSCGroups>
            {
                new CSCGroups{Id=1,Name="MCR_CAE"},
                new CSCGroups{Id=2,Name="MCR_CCUsuario"},
                new CSCGroups{Id=3,Name="MCR_Desembolso"},
                new CSCGroups{Id=4,Name="MCR_Ejecutivos"},
                new CSCGroups{Id=5,Name="MCR_Tesoreria"},
                new CSCGroups{Id=6,Name="MCR_MC"}

            };
```

**Screenshots**

![selectedchanged](https://user-images.githubusercontent.com/82295997/236585485-fe434566-2624-495a-ac69-cc32440aa1d4.png)

**Comment by David-Moreira** [comment]
Hello,
The compiler seems to be having a hard time infering the generic value, try specifying instead:
```
TValue="int"
TItem="CSCGroups"
```

**Comment by JCQuirozL** [comment]
This works just perfect, thanks for the time, it was such a dumb thing sorry.
