### ISSUE TITLE
Using Material Icons with Bootstrap5

### ISSUE THREAD

**Issue by grumpykiwi** [Megabit/Blazorise#4764]
Hi 

I am trying to use Material icons in a Blazorise Bootstrap5 project but cannot get them to display.

I have:

- Added the css link to _Layout.cshtml
- Added the blasorise material icons nuget package
- Added the service registration for AddMaterialIcons to program.cs

if I specify a an icon such as:

`<Icon Name="Blazorise.Icons.Material.MaterialIcons.Search" />`

The icon does not display. I dont see anything missing in Network view in Dev Tools. 

What am I missing ?

Thanks

Mark

**Comment by stsrki** [comment]
I have tried it in the BS5 demo, and it works as expected. 

Ensure you include all the CSS links as in the following screenshot.

![image](https://user-images.githubusercontent.com/900302/236677850-21bc3d48-7e43-4672-974e-e22e8a358d09.png)

**Comment by stsrki** [comment]
You're probably missing those styles when importing material CSS links. Check this https://stackoverflow.com/questions/50303454/how-to-use-the-new-material-design-icon-themes-outlined-rounded-two-tone-and

**Comment by stsrki** [comment]
Glad I could help.

Closing the ticket now.
