### ISSUE TITLE
Theme options seem to be ignored in Tailwind

### ISSUE THREAD

**Issue by mijgame** [Megabit/Blazorise#4780]
**Describe the bug**
I have the following setup, using the latest version of Blazorise and the Tailwind CSS provider:
```csharp
 private Theme _theme = new Theme
    {
        ColorOptions = new ThemeColorOptions
        {
            Primary = "#206A57",
            Secondary = "#F1F5F8",
            Light = "#F1F5F8",
            Dark = "#7F9EB9",
            Danger = "#D32929",
            Warning = "#FBC500",
            Info = "#7BB1A7",
            Link = "#365A74",
            Success = "#91C714"
        }
    };
```

```csharp
<ThemeProvider Theme="@_theme">
    <CascadingAuthenticationState>
        <Router AppAssembly="@typeof(App).Assembly">
             // other bits...
        </Router>
    </CascadingAuthenticationState>
</ThemeProvider>
```

I would expect default elements like `Card` to take over these colors (mostly light/green colors). But instead I still have the default styling:
![image](https://github.com/Megabit/Blazorise/assets/8114544/8725f9cc-2236-40de-ab0d-1548145dde1e)

I see the same colors (and very low background-to-text) contrast on the example website too. Adjusting the theme options doesn´t seem to change much:
![image](https://github.com/Megabit/Blazorise/assets/8114544/5a6ef818-99b1-4373-9722-590dcb7d1ef0)

How could I change the colors of the cards and such?

Thanks!

**Comment by stsrki** [comment]
The Tailwind theming is disabled for now, on purpose. The reason is that, unlike other CSS providers, tailwind works a little differently when compiling into CSS. So it is challenging to override those CSS styles through the theming.

My advice is to copy the config from 

- https://github.com/Megabit/Blazorise/blob/master/Demos/Blazorise.Demo.Tailwind/wwwroot/index.html#L19
- found in https://github.com/Megabit/Blazorise/blob/master/Source/Blazorise.Tailwind/wwwroot/blazorise.tailwind.config.js

And then override anything that you want.

---

The proper Blazorise theming will eventually come on future releases.

**Comment by mijgame** [comment]
Hmm, I see. Thanks for the input. But to override it myself  I'll adopt your configuration as my own tailwind.config.js I take it? Otherwise I don´t see how I could override settings in it.

**Comment by stsrki** [comment]
That's right. You need to create your own ailwind.config.js file.

**Comment by mijgame** [comment]
I've playing with it and got it mostly working as expected, thanks for the help! I have only one more question: DataGrid styling doesn´t seem to work and I'm trying to figure out why. I see styles being applied to rows like this: `group-[.b-table-sm]:py-2 group-[:not(.b-table-sm)]:py-4 px-4`. But I don't see any classes generated for things like `group-[.b-table-sm]:py-2`, most likely because tailwind can't look into the dependencies (like Blazorise); I noticed these classes are provided by the tailwind provider however.

Is there any standard way to deal with that or do I need to develop a workaround?

**Comment by stsrki** [comment]
The `b-table-sm` is used as the TW group name, https://tailwindcss.com/docs/hover-focus-and-other-states#arbitrary-groups. I believe that as long as you override padding that is used along it, then it should work.
