### ISSUE TITLE
Blazorise with .Net 6

### ISSUE THREAD

**Issue by alizalevinger** [Megabit/Blazorise#4792]
Trying to use blazorise datagrid. My project targets .net6. I installed the nuget packages and added builder.Services.UseBlazorise() in the location where I'm registering the rest of my services. I can run the project locally just fine, but when I publish to IIS I get the following error. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=7.0.0.0.

**Comment by David-Moreira** [comment]
Hello @alizalevinger 
we recommend you to try one of our templates : https://blazorise.com/docs/templates
If you feel like you've found a bug, please provide a repro as that's not enough information to troubleshoot.

**Comment by stsrki** [comment]
Make sure that you target the same .NET 6 when publishing. And also, check that you have all the required runtimes installed on your server.

![image](https://github.com/Megabit/Blazorise/assets/900302/9915d110-0ad3-4b9a-8a0b-b6f478ab4e66)
