### ISSUE TITLE
FlexWrap.NoWrap on button

### ISSUE THREAD

**Issue by 1zerro1** [Megabit/Blazorise#4816]
As of today we do : 
`    <Button style="white-space: nowrap;" [...]`
It would be nice to have a native blazorise way.

We often have buttons that include an icon and the wrapping effect on small screens is ugly.

Thanks

**Comment by stsrki** [comment]
There is :)

```razor
<Button Flex="Flex.NoWrap">
    Hello flex
</Button>
```

**Comment by 1zerro1** [comment]
Thank you, 
on my end, when I use this, mostly everywhere.  I am not able to center the text horizontaly which push me to css.

Any idea what I am doing wrong?
try this simple one, good luck 

<Container >
    <Row>
        <Column Flex="Flex.NoWrap" ColumnSize="ColumnSize.Is12">
            <Label >@DisplayText</Label> 
            <Button Color="Color.Primary" ***@***.***">    <Icon Name="IconName.Pen" /></Button>
        </Column>
    </Row>
</Container>

On 2023-06-13 12:46:25, Mladen Macanović ***@***.***> wrote:
There is :)
<Button Flex="Flex.NoWrap"> Hello flex </Button>

**Comment by stsrki** [comment]
You can combine Flex utilities however you want.

`Flex="Flex.JustifyContent.Center.AlignItems.Center"`

**Comment by 1zerro1** [comment]
That's great!
Works like a charm
On 2023-06-20 04:47:46, Mladen Macanović ***@***.***> wrote:
You can combine Flex utilities however you want.
Flex="Flex.JustifyContent.Center.AlignItems.Center"
