### ISSUE TITLE
SignaturePad:  repeating images

### ISSUE THREAD

**Issue by sks-ttaylor** [Megabit/Blazorise#4841]
**Describe the bug**
When drawing, the image is repeated smaller and to the top / left of the canvas.

**To Reproduce**
1.  Download solution from repo
2.  Set "Blazorise.Demo.Bootstrap5" as the startup project.
3.  Run the solution.
4.  navigate to http://localhost:???/tests/signaturepad
5.  Draw a line.

I expect a single line to be drawn.

Also please provide a sample code or point us to a minimalistic GitHub repo
Blazorise.Demo.Bootstrap5 master branch.

**Screenshots**
![image](https://github.com/Megabit/Blazorise/assets/5667162/5a4b0fd7-7507-4fc5-a7a7-d70318f96798)

**Additional context**

I was able to subdue the issue by adding a parameter to signaturepad.js calls ::  

sigpad.fromDataURL(options.dataUrl, { ratio: 1 } )

**Comment by David-Moreira** [comment]
Hello @sks-ttaylor 
I just tried this, and was not able to reproduce. Is there something else you have to do that's not listed in the **Steps To Reproduce**?

![image](https://github.com/Megabit/Blazorise/assets/22283161/64e15075-b64c-4d86-9dc9-4d20d2484f67)

**Comment by sks-ttaylor** [comment]
unable to reproduce after getting latest master branch... closing ticket
