### ISSUE TITLE
DataGrid : Visually group columns

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#4854]
@stsrki like we've talked let's go ahead and work on implementing a solution on DataGrid so that columns can be visually grouped.

For Visual Grouping:
**We've though about doing**
- HeaderGroupCaption parameter that would group the columns

An additional Table Row Header will then show up that will present the caption for these groups.

The grid should know how to reorder columns if needed.

For the reordering:
**We've though of:**
- **the first column in the column order** taking priority for the starting point for the group where the rest will have to follow and should still obey to whatever order they have set within their own group.

**Comment by stsrki** [comment]
Sounds about right to me.
