### ISSUE TITLE
Add compatibility with Bunit.

### ISSUE THREAD

**Issue by rubenblazor** [Megabit/Blazorise#4857]
I have tried to do an unit test with Bunit and it is not posible because I receive the error:

Cannot consume scoped service 'Microsoft.AspNetCore.Components.IComponentActivator' from singleton 'Bunit.Rendering.WebTestRenderer

I woud like request that Blazorise will be compatible with Bunit because is the library recommended by microsoft in the official documentation of Blazor.

Steps to reproduce:

https://stackoverflow.com/questions/76597158/bunit-blazorise-cannot-consume-scoped-service-microsoft-aspnetcore-components

**Comment by David-Moreira** [comment]
@rubenblazor You've already gotten a response from the bUnit maintainer over at stackoverflow that referred our docs for bUnit usage. Let us know if you were able to get it working!

We use bunit ourselves you can find some of our bunit tests here:
https://github.com/Megabit/Blazorise/tree/master/Tests/Blazorise.Tests/Components

**Comment by rubenblazor** [comment]
@David-Moreira  Hi David, I have been able to create the tests in BUnit. thanks for your help
