### ISSUE TITLE
Allow Blazorise.Icon to take a string for IconSize and IconStyle

### ISSUE THREAD

**Issue by InzeNL** [Megabit/Blazorise#4858]
Currently, the `IconSize` and `IconStyle` properties for [Blazorise.Icon](https://github.com/Megabit/Blazorise/tree/master/Source/Blazorise/Components/Icon) only take Enums [IconSize](https://github.com/Megabit/Blazorise/blob/master/Source/Blazorise/Enums/IconSize.cs) and [IconStyle](https://github.com/Megabit/Blazorise/blob/master/Source/Blazorise/Enums/IconStyle.cs) respectively)

Note: This issue describes more about `IconStyle` than about `IconSize`, but for consistency, it might be good to allow both to take strings

I am trying to implement a custom IconProvider to use FontAwesome's Pro Icons.
For the icon names, this is no problem, because they allow me to put in strings.
However, pro offers more styles (solid, regular, light, duotone, and thin for "Classic", and solid, regular, and light for "Sharp", and another separate brands style for "Brands", making for a total of 9 styles) than the enumerator covers. My current solution would be making my own implementation for the `Blazorise.Icon`, too.

However, it'd be nice if I could *just* change the `IIconProvider` implementation, allowing me to pass in strings (similar to how [FontAwesomeIcons](https://github.com/Megabit/Blazorise/blob/master/Source/Extensions/Blazorise.Icons.FontAwesome/FontAwesomeIcons.cs) does it), allowing me to simply add a static class containing all styles I need

I added `IconSize` to the feature request since it both touches this component in a very similar way, and I can foresee someone wanting to make their own handling of different icon sizes.

**Describe the solution you'd like**
Changing the `IconSize` and `IconStyle` parameters to be objects (similar to `IconName`), then allowing the current enumerators *or* a string. (again, similar to `IconName`)

On the `IIconProvider` side, all `IconSize` and `IconStyle` parameter would also change to objects.

### Additional context
Reference to FontAwesome's styles here: [https://fontawesome.com/docs/web/dig-deeper/styles](https://fontawesome.com/docs/web/dig-deeper/styles)

**Comment by stsrki** [comment]
The icon is already accepting the string as `Name`. It's just that the `.razor` editor is not smart enough to figure out the type so you need to explicitly tell it it is a string,

eg.

```razor
<Icon Name="@("fas fa-home")" />
```

The icon provider should also take care of parsing the icon styles automatically from strings.

**Comment by InzeNL** [comment]
I get an error when I try to use a string for IconSize or IconStyle

```csharp
Icon Name="@("fas fa-home")" IconStyle="@("fa-thin")" IconSize="@("fa-xs")" />
```

Errors:
```
error CS1503: Argument 1: cannot convert from 'string' to 'Blazorise.IconStyle?'
error CS1503: Argument 1: cannot convert from 'string' to 'Blazorise.IconSize?'
```

**Comment by InzeNL** [comment]
I do realise I misread your comment, and adding `fa-thin` and `fa-xs` to the `Name` should indeed work

**Comment by InzeNL** [comment]
Using the following code for my icon
```csharp
<Icon Name="@("fa-thin fa-xs fa-home")" />
```

I generate this
```html
<i class="fas fa-thin fa-xs fa-home"></i>
```

Here `fas` conflicts with `fa-thin`

**Comment by InzeNL** [comment]
Fixed the issue I mentioned by overriding `GetStyleName` like this

```csharp
public override string GetStyleName(IconStyle iconStyle)
{
    return null;
}
```
