### ISSUE TITLE
Link to code in demos

### ISSUE THREAD

**Issue by oaldrian** [Megabit/Blazorise#4874]
**Is your feature request related to a problem? Please describe.**
Most of the time you look at a demo page (eg. https://bootstrapdemo.blazorise.com/tests/cards) and you want to see the code for it.
Would be nice to have a Button / Link to the respective file in GitHub.

**Describe the solution you'd like**
A Link to the source file of a demo page to github, somewhere in the TopBar

**Comment by stsrki** [comment]
It's an excellent approach for a demo since we prefer to make it as clean as possible.

@steal4life We can discuss this to be done after the next release.
