### ISSUE TITLE
Show dynamic data from dataset in DataGrid

### ISSUE THREAD

**Issue by raavikr12c** [Megabit/Blazorise#4878]
I am new to blazorise. I have a requirement where I need to get data from database and show it in DataGrid format. I have a select list from which I will choose a table name for which i want to see data and then load that data from database via api. All the tables have different data with different number of columns. In my api I am getting data in a dataset and returning after JsonConvert.SerializeObject(dataset) and receiving it in a string variable. Then I am deserializing it to a variable of type System.Data.DataSet. But I am facing issue with showing this data in DataGrid. I need to show it in data grid because I want to have the option to insert, edit or delete the data record in database directly from from ui.
Any help on how to approach this or what to do for this will be greatly appreciated. Please give some example too.

**Comment by David-Moreira** [comment]
Hello,

Is converting the Dataset/table to a support Datagrid collection out of the question? 

Take a look at this user example at rendering columns dynamically (for each of your tables)
https://github.com/Megabit/Blazorise/issues/3278

**Comment by raavikr12c** [comment]
Hi @David-Moreira , thanks for the reply. 
I tried this approach and converted data table to Dictionary List and now I am able to display the data in data grid.  
Now I just need to figure out how to edit SelectedRow of in data grid to make changes in the data.

Thanks for the help.

PS: Apologies for my late reply I was busy in some other thing.

**Comment by David-Moreira** [comment]
> Hi @David-Moreira , thanks for the reply. I tried this approach and converted data table to Dictionary List and now I am able to display the data in data grid. Now I just need to figure out how to edit SelectedRow of in data grid to make changes in the data.
> 
> Thanks for the help.
> 
> PS: Apologies for my late reply I was busy in some other thing.

Hello,

I think you'll have to customize by providing appropriate EditTemplates, and you might have to provide a way to keep the state, let us know what you've tried and if you're unable to, if you can post the code that you have currently, that will help. 

Thanks!
