### ISSUE TITLE
Migrate PopperJS to new library

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#4885]
It seems that popperJS have become obsolete https://github.com/floating-ui/floating-ui/issues/2386#issuecomment-1596447265

We need to think of moving to the new version 

The migration to the new library on https://floating-ui.com/docs/migration

**Comment by David-Moreira** [comment]
Oh Jesus Christ haha.
Well comes in handy, there's an issue we still haven't figured out when buttons inside it seem to mess it up. In fact I was going to investigate that for #4870, so might as well do this first if it isn't too hard to migrate. Maybe this migration will help with that.

**Comment by stsrki** [comment]
> Well comes in handy, there's an issue we still haven't figured out when buttons inside it seem to mess it up.

Didn't we fix it by not using DropdownItem?

**Comment by David-Moreira** [comment]
> > Well comes in handy, there's an issue we still haven't figured out when buttons inside it seem to mess it up.
> 
> Didn't we fix it by not using DropdownItem?

That was a different issue, not being able to interact with the input components inside. 

The one I'm talking about is this one : 
https://github.com/Megabit/BlazoriseSupport/issues/65
![image](https://github.com/Megabit/Blazorise/assets/22283161/ff8d705e-6c0c-4903-b79b-4edbfe7667cb)


I can't find whatever issue I must've opened over at Blazorise's side.
