### ISSUE TITLE
myget.org is dead

### ISSUE THREAD

**Issue by sks-ttaylor** [Megabit/Blazorise#4895]
myget has been nonresponsive for over 24 hours...

See thread below... 

https://www.reddit.com/r/dotnet/comments/159yigd/is_myget_gone_for_good/

**Comment by stsrki** [comment]
I noticed it myself yesterday after trying to build a project in VS and failing every time. After removing MyGet from Nuget feeds, it started working. We will remove all mention of MyGet from the documentation. Thank you for letting us know.

**Comment by sks-ttaylor** [comment]
It still would be nice to have somewhere to get a nightly of the master branch..

________________________________

**Comment by David-Moreira** [comment]
> Done with removing MyGet from the documentation.
> 
> Ragarding the nigtly build. We had that in the past, and we, for some reason, disabled them. I don't remember the exact reason. @David-Moreira do you remember?

Honestly I don't remember us ever having that. As far as I know we never had the package deployment automated.
I do think it's a very nice to have, to quickly get our users testing latest master without us having to manually deploy a preview.
Or to just get feedback faster from the current dev release, from users who are willing to use nightly builds instead (altough not recommended ofc, specially for prod :D).

**Comment by stsrki** [comment]
It's here https://github.com/Megabit/Blazorise/blob/master/.github/disabled-workflows/build-nuget.yml

**Comment by David-Moreira** [comment]
Well, no idea why it was stopped then. :) I'm up for re-enabling it.
