### ISSUE TITLE
Allow Component Parameters  to override BlazoriseOptions :: Example Icon 

### ISSUE THREAD

**Issue by sks-ttaylor** [Megabit/Blazorise#4897]
**Describe the bug**
I am unable to override BlazoriseOptions.IconSize at the Icon component level.

**To Reproduce**

In Program.cs :: 
services.AddBlazorise(options => {
           options.IconStyle = IconStyle.Solid;
           options.IconSize = IconSize.Small;
});

In Razor::
<Icon IconSize=IconSize.x3 Name=IconName.FileUpload />

**Expected behavior**
I expect to be able to override any BlazoriseOptions at the Component level.

**Screenshots**

**Additional context**
Icon.razor.cs

CURRENT
   protected IconSize GetIconSize() => **Options.IconSize ?? IconSize** ?? Blazorise.IconSize.Default;
   protected IconStyle GetIconStyle() => **Options.IconStyle ?? IconStyle** ?? Blazorise.IconStyle.Solid;

RECOMMEDED
   protected IconSize GetIconSize() => **IconSize ?? Options.IconSize** ??  Blazorise.IconSize.Default;
   protected IconStyle GetIconStyle() => **IconStyle ?? Options.IconStyle** ??  Blazorise.IconStyle.Solid;

This change should be made for any component that implements a BlazoriseOptions setting.

**Comment by David-Moreira** [comment]
Seems like an oversight indeed. Other places seem to be correct.
@stsrki any specific reason why options could take precedence over the more specific definition in the component?

As a side note, this does not seem to be used anywhere:
![image](https://github.com/Megabit/Blazorise/assets/22283161/50bde4f7-aa78-4c2f-9b49-7eef02d3bddc)

**Comment by stsrki** [comment]
It seems like an oversight, indeed. We will fix it.

> As a side note, this does not seem to be used anywhere:
> ![image](https://user-images.githubusercontent.com/22283161/256679494-50bde4f7-aa78-4c2f-9b49-7eef02d3bddc.png)

TBH, I don't remember about that feature. Probably a long-time API that was used at some point.
