### ISSUE TITLE
FilePicker / FileEdit :: Status being rest when Remove is called 

### ISSUE THREAD

**Issue by sks-ttaylor** [Megabit/Blazorise#4901]
**Describe the bug**

Using the FilePicker Multiple=true,
I have a custom UploadAll handler that calls the FilePicker.UploadAll then remove a files where Status==Uploaded.

I select several files to upload,
I click my UploadAll
It calls FilePicker.UploadAll 
Then a foreach FilePicker.FileEdit.Files.Where(Status=Uploaded) => FilePicker.FileEdit.RemoveFile(file.Id)

When the FilePicker.FileEdit.RemoveFile(file.Id) returns and Re-Renders, the Status of the other files change from Uploaded to Ready.

**Expected behavior**
Calling RemoveFile does not change the Status of the other Files.

**Additional context**

I think the issue is in the FileEdit.NotifyChange handler

**Comment by David-Moreira** [comment]
Hello @sks-ttaylor 
You're right. As soon as you remove a File, the `FilePicker` re-renders the state for each file's status is lost and the internal ids are also lost, so subsequent files fail to be removed.

This isn't a good experience and we'll work on it such that it keeps the correct state even after you remove a file or multiple.

For the meantime a hacky workaround is to materialize the files that were uploaded and then before issuing the remove command, requery them from the internal `FileEdit` by name.

Or just use `FilePicker.Clear` if all you intend to do is clear the picker after upload.
An additional idea is that if you want to have the user confirm if the files have errors, you can compromise and take the approach where you only **Clear** if all the existing files have been uploaded successfully. 
If not, then the user needs to see which files are errored.

```
<Field>
    <FilePicker @ref=filePicker Multiple Upload="OnFileUpload" ShowMode="FilePickerShowMode.List" />
</Field>

<Button Clicked="UploadAll">Upload All</Button>
@code {
    private FilePicker filePicker;

    async Task UploadAll()
    {
        await filePicker.UploadAll();

        var allFiles = filePicker.FileEdit.Files.Where(x => x.Status == FileEntryStatus.Uploaded).ToList();

        foreach ( var file in allFiles )
        {
            var actualFile = filePicker.FileEdit.Files.FirstOrDefault(x => x.Name == file.Name);
            await filePicker.RemoveFile( actualFile );
        }
    }

    async Task OnFileUpload( FileUploadEventArgs e )
    {
        try
        {
            using ( MemoryStream result = new MemoryStream() )
            {
                await e.File.OpenReadStream( long.MaxValue ).CopyToAsync( result );
            }
        }
        catch ( Exception exc )
        {
            Console.WriteLine( exc.Message );
        }
        finally
        {
            this.StateHasChanged();
        }
    }
}
```
