### ISSUE TITLE
DataGrid Validation throw NullReferenceException when TItem is not POCO

### ISSUE THREAD

**Issue by rbillott** [Megabit/Blazorise#4906]
**Describe the bug**
Look like DataGrid Validation work only with **plain object** type as row item type (parameter-less constructor, only properties). 
When row data is not a POCO, the Validation might work with invalid copies of the model and will most likely throw an NullReferenceException when trying to edit element. 

This is not documented so my guess is that, under the hood, the Validation create clone objects using reflection to create instance and map all editable properties.  In my case that doesn't work as I need to instantiate in a very specific way.    

**To Reproduce**
- Use below code to create a Grid 
- Click Edit on the Grid row  => that should throw the exception

```
<DataGrid TItem="RowViewModel" Data="Rows"
          
          Editable="true" 
          EditMode="DataGridEditMode.Popup" 
          UseValidation="true"
          SelectionMode="DataGridSelectionMode.Single"
          Striped Bordered Narrow Hoverable>
    <DataGridColumns>
        
        <DataGridCommandColumn NewCommandAllowed="false">
            <EditCommandTemplate>
                <Button ElementId="btnEdit" Color="Color.Primary" Size="Size.ExtraSmall" Clicked="@context.Clicked">
                    <Icon Name="IconName.Edit" />
                </Button>
            </EditCommandTemplate>
            <DeleteCommandTemplate>
                <Button ElementId="btnDelete" Color="Color.Danger" Size="Size.ExtraSmall" Clicked="@context.Clicked">
                    <Icon Name="IconName.Delete" />
                </Button>
            </DeleteCommandTemplate>
            <SaveCommandTemplate>
                <Button Type="ButtonType.Submit" PreventDefaultOnSubmit Color="Color.Primary" Size="Size.Default" Clicked="@context.Clicked">Save</Button>
            </SaveCommandTemplate>
            <CancelCommandTemplate>
                <Button Color="Color.Secondary" Size="Size.Default" Clicked="@context.Clicked">Cancel</Button>
            </CancelCommandTemplate>
        </DataGridCommandColumn>

        <DataGridColumn Field="@nameof(RowViewModel.Id)" Caption="Id" />
        <DataGridColumn Field="@nameof(RowViewModel.Name)" Caption="Name" Editable />
        <DataGridColumn Field="@nameof(RowViewModel.Description)" Caption="Description" Editable />

    </DataGridColumns>
</DataGrid>
@code {
    public List<RowViewModel> Rows = new();

    protected override void OnInitialized()
    {
        Rows.Add(new RowViewModel( new RowData { Id = 1, Name = "Batman", Description = "Batman is a superhero from gotham city" }));
    }
}


    public class RowViewModel
    {
        private readonly RowData _data;

        public RowViewModel(RowData data)
        {
            _data = data;
        }

        public int Id { get => _data.Id; set => _data.Id = value; }
        [Required] public string Name { get => _data.Name; set => _data.Name = value; }
        [Required] public string Description { get => _data.Description; set => _data.Description = value; }
    }

    public class RowData
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }

```

**Expected behavior**
Expecting Validation not to throw Exception

**Additional context**
RowViewModel and RowData  are dummy class to reproduce the issue, they are not my real Data type.

**Comment by stsrki** [comment]
DataGrid will fallback to data-annotation validation if there is no another validation handler defined. And data-annotation requires a model to validate.

If you want to override it, you can use the parameters on `DataGridColumn`:

- `Validator`
- `AsyncValidator`
- `ValidationPattern`

You can read more about validators on https://blazorise.com/docs/components/validation

**Comment by David-Moreira** [comment]
@stsrki should we at least try to throw a better error? If possible?

**Comment by rbillott** [comment]
> DataGrid will fallback to data-annotation validation if there is no another validation handler defined. And data-annotation requires a model to validate.
> 
> If you want to override it, you can use the parameters on `DataGridColumn`:
> 
> * `Validator`
> * `AsyncValidator`
> * `ValidationPattern`
> 
> You can read more about validators on https://blazorise.com/docs/components/validation

The issue is also happening with a `Validator`  which is the one I was trying when I faced the issue.
(I used annotation in the sample code to reduce the code, but I believe it's independent of how the handler is defined.)

My point is thatt he Validation is creating a copy of the model assuming it's a `plain object`  (again it's a guess as I didn't really check the code, but I know Validation is interacting with objects different that the one bound to the DataGrid, and which I didn't create), and it just doesn't work when it's not the case..  If the validation is restricted to work only with plain object..  then fine but that limit a lot what we can do; plus it needs to be properly documented.

**Comment by stsrki** [comment]
@rbillott If you need to do custom initialization, you can try `NewItemCreator`, or `NewItemDefaultSetter`. It allows you to create an object without DataGrid doing it internally with reflection. There is also `EditItemCreator` for updating objects.

One example can be found on https://blazorise.com/docs/extensions/datagrid/features/editing

**Comment by rbillott** [comment]
Hi , first, I appreciate very much that you are taking the time to check and  answering very quickly. 
But I think there is a bit of misunderstanding. I do not need a custom initialisation for **New** item  (b/c I don't need to add new items) 
The problem is when I edit the existing ones ; Apparently the DataGrid  Validation need to create a  **copy** of the existing model objects bound to the DataGrid, and in my case the **copy** is invalid.   

Just to be clear, the problem happen only when  **UseValidation="true"**;  Without that, the DataGrid  work and can edit just fine.  

Why those copies are happening ?

**Comment by David-Moreira** [comment]
Actually there's a **ValidationItemCreator** in case you do not want to use our internal implementation for the "**copy**".
```
    /// <summary>
    /// Function that, if set, is called to create a validation instance of an item that it's used as a separate instance for Datagrid's internal processing of validation. If left null, Datagrid will try to use it's own implementation to instantiate.
    /// </summary>
    [Parameter] public Func<TItem> ValidationItemCreator { get; set; }
```

**Comment by rbillott** [comment]
> Actually there's a **ValidationItemCreator** in case you do not want to use our internal implementation for the "**copy**".
> 
> ```
>     /// <summary>
>     /// Function that, if set, is called to create a validation instance of an item that it's used as a separate instance for Datagrid's internal processing of validation. If left null, Datagrid will try to use it's own implementation to instantiate.
>     /// </summary>
>     [Parameter] public Func<TItem> ValidationItemCreator { get; set; }
> ```
> 
> ![image](https://user-images.githubusercontent.com/22283161/257810823-6af7e3ef-4dd7-4911-ba90-bc114ee08979.png) https://blazorise.com/docs/extensions/datagrid/getting-started

OK, yes that make more sense and it works for me..   
Added that prop :  `ValidationItemCreator="@(() => new RowViewModel(new RowData()))"`
