### ISSUE TITLE
Update Video player to new library

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#4914]
The Plyr.js is going to be obsolete by the new library at some point https://github.com/sampotts/plyr/issues/2408

We must plan for the upgrade once it is stabilized and exits beta.

New Library: https://www.vidstack.io/

**Comment by sturlath** [comment]
Its **almost** there https://github.com/vidstack/player/discussions/categories/releases ... so many things there I would love/need to see in Blazorise.

**Comment by stsrki** [comment]
Hopefully, there will not be a lot of breaking changes.

**Comment by David-Moreira** [comment]
@stsrki would it be possible to abstract it in a way that you can have multiple video providers? 
Like we did for Captcha?
There can be people that already depend on the old player funcionality and almost always these kind of migrations lead to stuff breaking or just working differently. 
Would you think that'd be worth it?

**Comment by stsrki** [comment]
It might be possible as long as they share similar features so that the API can be abstracted. I will know as soon as I start working on it. But the general idea for the future is to create most of the extensions that way by abstracting and then implementing different libraries.

**Comment by stsrki** [comment]
Working on this. So far, we can

- play all videos
- set DRM protection
- load dash or hls on demand

We are still missing some APIs from plyr. Hopefully, I will be able to find an alternative.
