### ISSUE TITLE
PositionStrategy doesn't work on Autocomplete in docs search field

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#4922]
Also tried with the Fixed parameter, and it doesn't work.

![image](https://github.com/Megabit/Blazorise/assets/900302/4c3f21da-8d3f-4e1d-b913-56831ce37921)

---

Should work as on https://blazorise.com/docs

![image](https://github.com/Megabit/Blazorise/assets/900302/cb765279-7344-4dbd-bb7f-c5a530d0485a)

**Comment by David-Moreira** [comment]
Well that's unfortunate, autocomplete is pretty much broken. I'm not sure why it's anchoring on top instead of below... :(
