### ISSUE TITLE
ColumnSize

### ISSUE THREAD

**Issue by grumpykiwi** [Megabit/Blazorise#4930]
Is it possible to set the width on a column in code behind, based on the value of a bool like so:

```	
protected async Task ToggleFilterView()
{
	MainColumn.ColumnSize = !FiltersVisible ? ColumnSize.Is12 : ColumnSize.Is10;
	await JSRuntime.InvokeVoidAsync("ShowHideSearchFilter", "filterPanel", "btnToggleFilterMenu");
	FiltersVisible= !FiltersVisible;
}

declaration
protected Blazorise.Column MainColumn { get; set; }

razor
<Column @ref="@MainColumn">
```

The filter column is 2 grid units wide, so the main column defaults to 10. The method above does not change the width of the column so I end up with a bunch of free space to the right when the filter column is hidden.

Using the latest version of Blazorise with VS2022 Pro and latest updates (as of Thursday)

Thanks

Mark

**Comment by stsrki** [comment]
It's usually not recommended to set the component property directly,  eg. `MainColumn.ColumnSize`. I believe the compiler would also give you a warning if you try it.

To dynamically change column size, you need to define it through parameters. eg.

```razor
<Column ColumnSize="@myColumnSize">
</Column>
@code{
    IFluentColumn myColumnSize;
  
    protected async Task ToggleFilterView()
    {
        myColumnSize = !FiltersVisible ? ColumnSize.Is12 : ColumnSize.Is10;
        await JSRuntime.InvokeVoidAsync("ShowHideSearchFilter", "filterPanel", "btnToggleFilterMenu");
        FiltersVisible= !FiltersVisible;
    }
}
```
