### ISSUE TITLE
Datepicker is in the middle of input

### ISSUE THREAD

**Issue by danik121** [Megabit/Blazorise#4939]
Datepicker is in the middle of input

![image](https://github.com/Megabit/Blazorise/assets/8233518/9a64c10b-68a9-4515-a3ea-5c855d903f8f)

**Comment by steal4life** [comment]
@David-Moreira  sorry for bothering, I noticed when comparing our datepicker and the datepicker in the flatpickr library that our calendar doesn't open down, which is actually the expected behavior in case the user scrolls enough to see only the input with no space below

**Comment by Lasoty** [comment]
You can reproduce this bug on https://bootstrap5demo.blazorise.com/tests/pickers. Bug still occurs.

**Comment by sturlath** [comment]
> You can reproduce this bug on https://bootstrap5demo.blazorise.com/tests/pickers. Bug still occurs.

FYI there is no popup for DatePicker when on IPhone.

**Comment by stsrki** [comment]
Fixed in the coming 1.5.3
