### ISSUE TITLE
Add GreaterThan and LessThan Filter method to Blazorise DataGrid component?

### ISSUE THREAD

**Issue by JLfarhan** [Megabit/Blazorise#4941]
**Is your feature request related to a problem? Please describe.**
I'm using Blazorise DataGrid component. The currently supported filtering methods include the following:

- Contains
- StartsWith
- EndsWith
- Equals
- NotEquals

However, I have a need to filter a column with numeric values using **Greater Than** and **Less Than** operators (filter methods). Is there a way to add new Filter methods to Blazorise DataGrid component? For example, add GreaterThan and LessThan filter methods for DataGridNumericColumn?

**Describe the solution you'd like**
I would like DataGrid Filter methods to include GreaterThan and LessThan methods. At a minimum, I'm expecting that there is an example or documentation of extending the filter component to add the additional filter methods. 

### Additional context
I am using Blazorise.DataGrid version 1.3.0.
**Edit:** I am loading data from External source, so my filtering will be on the server side: https://blazorise.com/docs/extensions/datagrid/binding-data/large-data

**Comment by JLfarhan** [comment]
Thank you for your response. I am using Menu Mode filtering. Some of my columns in the grid are numeric and some are just text. For the numeric columns, I want to give them Equal, Not Equal, Less Than and Greater Than filter options. For the text columns, I want to give them the default filters available in Data Grid. However, using custom filters, is there a way to customize the Menu (Menu Mode Filters) based on the type of column, so that columns will get filters based on the type of data (numeric vs. text).

**Comment by David-Moreira** [comment]
@stsrki is on the right path with the current DataGrid capabilities.

I will get back to you with a more concrete example once I get the time. But it should be possible to customize it to your liking, it just takes a bit more work.

A combination of the feature
**Menu Mode Filtering : Template** & the feature **Custom Filtering**

You modify the template with your own filtering capabilities, it can be your own defined enum, and then on the custom filter you filter based on your own filtering capabilities. However I'm not sure how easy it will be to implement it such that it can be generic enough for your use case. I.E having numeric filters applied to every numeric column, etc...

https://blazorise.com/docs/extensions/datagrid/features/filtering

@stsrki I do think it's interesting if we explore in providing better & expected contextual filtering mechanism for the numeric, date, etc columns...
Although I'm also not yet sure how we would extend it internally. :D

**Comment by JLfarhan** [comment]
@David-Moreira Thanks for your detailed response and direction. I will explore it further on my end too and share what I find. Due to lack of time (with other responsibilities), I might not be able to explore a generic solution. I might just build a custom template for a couple of numeric columns using `<FilterTemplate>`  and `CustomFilter `, and use `DataGridFilterMode.Default` instead of `DataGridFilterMode.Menu` in the interest of time. However, this use case is expected to come up in the future and a long-term solution would still help.

**Comment by mtbayley** [comment]
The new filter menu is great. Adding ability to filter by numeric or DateTime values would make this even better.

**Comment by David-Moreira** [comment]
Hello,

Here's a very quick dirty example, I just focused on making it work, you'll have to adapt the code, to make it more reusable, more elegant, etc... But I think this might be an acceptable starting point:
```
<DataGrid @ref="dataGrid"
          TItem="Employee"
          Data="@employeeList"
          Responsive
          Filterable
           FilterMode="DataGridFilterMode.Menu" CustomFilter="MyCustomFilter">
     <DataGridColumns>
         <DataGridColumn Field="@nameof( Employee.FirstName )" Caption="First Name" Editable="false" FilterMethod="DataGridFilterMethod.StartsWith"></DataGridColumn>
         <DataGridColumn Field="@nameof( Employee.LastName )" Caption="Last Name" Editable="false"></DataGridColumn>
         <DataGridSelectColumn TItem="Employee" Field="@nameof( Employee.Gender )" Caption="Gender" Editable Data="EmployeeData.Genders" ValueField="(x) => ((Gender)x).Code" TextField="(x) => ((Gender)x).Description" />
     </DataGridColumns>
     <FilterMenuTemplate>
         <Row>
             <Column ColumnSize="ColumnSize.Is4">
                 <Select TValue="MyFilter" SelectedValue="@_filterTracker.GetColumnFilterValue(context.Column.Field)" SelectedValueChanged="e => { _filterTracker.SetColumnFilter(context.Column, e); }">
                     <SelectItem TValue="MyFilter" Value="@MyFilter.Contains">Contains</SelectItem>
                     <SelectItem TValue="MyFilter" Value="@MyFilter.StartsWith">Starts With</SelectItem>
                     <SelectItem TValue="MyFilter" Value="@MyFilter.EndsWith">Ends With</SelectItem>
                     <SelectItem TValue="MyFilter" Value="@MyFilter.Equals">Equals</SelectItem>
                     <SelectItem TValue="MyFilter" Value="@MyFilter.NotEquals">Not Equals</SelectItem>
                     <SelectItem TValue="MyFilter" Value="@MyFilter.GreaterThan">GreaterThan</SelectItem>
                     <SelectItem TValue="MyFilter" Value="@MyFilter.LessThan">LessThan</SelectItem>
                 </Select>
             </Column>

             <Column ColumnSize="ColumnSize.Is4">
                 <TextEdit Text="@context.GetSearchValue()?.ToString()" TextChanged="@((newValue) => _filterTracker.SetColumnSearchValue(context.Column, newValue))" />
             </Column>

             <Column ColumnSize="ColumnSize.Is4">
                 <Button Clicked="context.Filter" Color="Color.Primary"><Icon Name="IconName.Filter"></Icon> Filter</Button>
                 <Button Clicked="context.ClearFilter" Color="Color.Light"><Icon Name="IconName.Clear"></Icon> Clear</Button>
             </Column>
         </Row>
     </FilterMenuTemplate>
 </DataGrid>
 @code {
    private DataGrid<Employee> dataGrid;
    private List<Employee> employeeList = new() {
        new(){ FirstName = "David", LastName = "Moreira", Gender = "M" } ,
        new (){ FirstName = "MLaden", LastName = "Macanovic", Gender = "M" }   };

    private FilterTracker<Employee> _filterTracker = new();

    public class FilterTracker<T>
    {
        public List<ColumnFilter<T>> columnFilters { get; set; }
        public void SetColumnFilter( DataGridColumn<T> column, MyFilter myFilter )
        {
            columnFilters ??= new();

            var columnFilter = columnFilters.FirstOrDefault( x => x.Column.Field == column.Field );
            if ( columnFilter is null )
            {
                columnFilters.Add( new()
                    {
                        Column = column,
                        SelectedFilter = myFilter
                    } );
            }
            else
            {
                columnFilter.SelectedFilter = myFilter;
            }
        }

        public void SetColumnSearchValue( DataGridColumn<T> column, string searchValue )
        {
            columnFilters ??= new();

            var columnFilter = columnFilters.FirstOrDefault( x => x.Column.Field == column.Field );
            if ( columnFilter is null )
            {
                columnFilters.Add( new()
                    {
                        Column = column,
                        SearchValue = searchValue
                    } );
            }
            else
            {
                columnFilter.SearchValue = searchValue;
            }
        }

        public ColumnFilter<T> GetColumnFilter( string fieldName )
            => columnFilters?.FirstOrDefault( x => x.Column.Field == fieldName );

        public MyFilter GetColumnFilterValue( string fieldName )
            => GetColumnFilter( fieldName )?.SelectedFilter ?? MyFilter.Contains;



    }
    public class ColumnFilter<T>
    {
        public DataGridColumn<T> Column;
        public string SearchValue;
        public MyFilter SelectedFilter { get; set; } = MyFilter.Contains;
    }

    public enum MyFilter
    {
        Equals, NotEquals, Contains, StartsWith, EndsWith, GreaterThan, LessThan
    }

    private bool MyCustomFilter( Employee row )
    {
        return _filterTracker.columnFilters is null
            ? true
            : _filterTracker.columnFilters.All( EvaluateColumnFilter );
    }

    private bool EvaluateColumnFilter( ColumnFilter<Employee> columnFilter )
    {
        Console.WriteLine( $"Evaluating... {columnFilter.Column.Field}" );
        Console.WriteLine( $"Filter to apply... {columnFilter.SelectedFilter}" );
        //You might need some reflection based or expression based getter to get the value of the corresponding field dynamically
        //Do whatever boolean logic you need to do here
        return true;
    }
}
```

![image](https://github.com/Megabit/Blazorise/assets/22283161/45de49a6-30d2-4c35-a613-2087284176fd)

**Comment by David-Moreira** [comment]
> @David-Moreira wanna write the blog post describing this solution?

Well sure, it should only be a temporary fix but I guess it will help people looking for this. I'll improve the example and write the post later.

**Comment by stsrki** [comment]
Thanks

**Comment by JLfarhan** [comment]
> Hello,
> 
> Here's a very quick dirty example, I just focused on making it work, I didn't bother too much with details, data types, etc... just an example, you'll have to adapt the code, to make it more reusable, more elegant, etc... But I think this might be an acceptable starting point:
> 
> ```
> <DataGrid @ref="dataGrid"
>           TItem="Employee"
>           Data="@employeeList"
>           Responsive
>           Filterable
>            FilterMode="DataGridFilterMode.Menu" CustomFilter="MyCustomFilter">
>      <DataGridColumns>
>          <DataGridColumn Field="@nameof( Employee.FirstName )" Caption="First Name" Editable="false" FilterMethod="DataGridFilterMethod.StartsWith"></DataGridColumn>
>          <DataGridColumn Field="@nameof( Employee.LastName )" Caption="Last Name" Editable="false"></DataGridColumn>
>          <DataGridSelectColumn TItem="Employee" Field="@nameof( Employee.Gender )" Caption="Gender" Editable Data="EmployeeData.Genders" ValueField="(x) => ((Gender)x).Code" TextField="(x) => ((Gender)x).Description" />
>      </DataGridColumns>
>      <FilterMenuTemplate>
>          <Row>
>              <Column ColumnSize="ColumnSize.Is4">
>                  <Select TValue="MyFilter" SelectedValue="@_filterTracker.GetColumnFilterValue(context.Column.Field)" SelectedValueChanged="e => { _filterTracker.SetColumnFilter(context.Column, e); }">
>                      <SelectItem TValue="MyFilter" Value="@MyFilter.Contains">Contains</SelectItem>
>                      <SelectItem TValue="MyFilter" Value="@MyFilter.StartsWith">Starts With</SelectItem>
>                      <SelectItem TValue="MyFilter" Value="@MyFilter.EndsWith">Ends With</SelectItem>
>                      <SelectItem TValue="MyFilter" Value="@MyFilter.Equals">Equals</SelectItem>
>                      <SelectItem TValue="MyFilter" Value="@MyFilter.NotEquals">Not Equals</SelectItem>
>                      <SelectItem TValue="MyFilter" Value="@MyFilter.GreaterThan">GreaterThan</SelectItem>
>                      <SelectItem TValue="MyFilter" Value="@MyFilter.LessThan">LessThan</SelectItem>
>                  </Select>
>              </Column>
> 
>              <Column ColumnSize="ColumnSize.Is4">
>                  <TextEdit Text="@_filterTracker.GetColumnSearchValue(context.Column.Field)" TextChanged="@((newValue) => _filterTracker.SetColumnSearchValue(context.Column, newValue))" />
>              </Column>
> 
>              <Column ColumnSize="ColumnSize.Is4">
>                  <Button Clicked="context.Filter" Color="Color.Primary"><Icon Name="IconName.Filter"></Icon> Filter</Button>
>                  <Button Clicked="context.ClearFilter" Color="Color.Light"><Icon Name="IconName.Clear"></Icon> Clear</Button>
>              </Column>
>          </Row>
>      </FilterMenuTemplate>
>  </DataGrid>
>  @code {
>     private DataGrid<Employee> dataGrid;
>     private List<Employee> employeeList = new() {
>         new(){ FirstName = "David", LastName = "Moreira", Gender = "M" } ,
>         new (){ FirstName = "MLaden", LastName = "Macanovic", Gender = "M" }   };
> 
>     private FilterTracker<Employee> _filterTracker = new();
> 
>     public class FilterTracker<T>
>     {
>         public List<ColumnFilter<T>> columnFilters { get; set; }
>         public void SetColumnFilter( DataGridColumn<T> column, MyFilter myFilter )
>         {
>             columnFilters ??= new();
> 
>             var columnFilter = columnFilters.FirstOrDefault( x => x.Column.Field == column.Field );
>             if ( columnFilter is null )
>             {
>                 columnFilters.Add( new()
>                     {
>                         Column = column,
>                         SelectedFilter = myFilter
>                     } );
>             }
>             else
>             {
>                 columnFilter.SelectedFilter = myFilter;
>             }
>         }
> 
>         public void SetColumnSearchValue( DataGridColumn<T> column, string searchValue )
>         {
>             columnFilters ??= new();
> 
>             var columnFilter = columnFilters.FirstOrDefault( x => x.Column.Field == column.Field );
>             if ( columnFilter is null )
>             {
>                 columnFilters.Add( new()
>                     {
>                         Column = column,
>                         SearchValue = searchValue
>                     } );
>             }
>             else
>             {
>                 columnFilter.SearchValue = searchValue;
>             }
>         }
> 
>         public ColumnFilter<T> GetColumnFilter( string fieldName )
>             => columnFilters?.FirstOrDefault( x => x.Column.Field == fieldName );
> 
>         public MyFilter GetColumnFilterValue( string fieldName )
>             => GetColumnFilter( fieldName )?.SelectedFilter ?? MyFilter.Contains;
> 
>         public string GetColumnSearchValue( string fieldName )
>             => GetColumnFilter( fieldName )?.SearchValue;
> 
> 
> 
>     }
>     public class ColumnFilter<T>
>     {
>         public DataGridColumn<T> Column;
>         public string SearchValue;
>         public MyFilter SelectedFilter { get; set; } = MyFilter.Contains;
>     }
> 
>     public enum MyFilter
>     {
>         Equals, NotEquals, Contains, StartsWith, EndsWith, GreaterThan, LessThan
>     }
> 
>     private bool MyCustomFilter( Employee row )
>     {
>         return _filterTracker.columnFilters is null
>             ? true
>             : _filterTracker.columnFilters.All( EvaluateColumnFilter );
>     }
> 
>     private bool EvaluateColumnFilter( ColumnFilter<Employee> columnFilter )
>     {
>         Console.WriteLine( $"Evaluating... {columnFilter.Column.Field}" );
>         Console.WriteLine( $"Filter to apply... {columnFilter.SelectedFilter}" );
>         //You might need some reflection based or expression based getter to get the value of the corresponding field dynamically
>         //Do whatever boolean logic you need to do here
>         return true;
>     }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/22283161/262168637-45de49a6-30d2-4c35-a613-2087284176fd.png)

Thank you, I appreciate your help. I couldn't get this to work as I am using server-side filtering/sorting and `OnReadData(DataGridReadDataEventArgs<T> e)` gives me null "SearchValue" for the columns I am trying to filter using the above code. I do see the new filter menu with Greater Than and Less Than options. But as expected, the code requires more work for my use case. Perhaps another feature request, but it would be nice to send the filter method in DataGridReadDataEventArgs so that the right method can be applied when using server-side filtering.

**Comment by David-Moreira** [comment]
The code I gave is a generalized example as a temporary fix. You will have to adapt it and probably fix any bugs if any. 

The example given is for static data, not readdata, althought it should work similarly, prioritized getting the search value from a new `ColumnFilter<T>`. So might have forgotten to set the internal column `SearchValue`, since we are overriding it ourselves anyway, no wonder it might not show up in the arguments.
