### ISSUE TITLE
ObjectExtensions.IsEqual is an anti-pattern 

### ISSUE THREAD

**Issue by rbillott** [Megabit/Blazorise#4945]
**Describe the bug**
Getting **using Blazorise.Extensions** import automatically added everywhere in my code by resharper or IntelliSense 
it's not really a bug but that's annoying and that is direct consequences of the anti-pattern of defining extension on Object type

**To Reproduce**
No sure about the exact step, so sorry about that, I'm pretty sure it's coming from resharper or IntelliSense which have those automatic feature 
- https://learn.microsoft.com/en-us/visualstudio/ide/reference/intellisense-completion-unimported-types-extension-methods?view=vs-2022
- https://www.jetbrains.com/help/resharper/Automatically_import_namespaces.html

**Expected behavior**
The point is that having extension on object type is generally consider as anti-patter, and can have some unexpected side effect. 
And because of IntelliSense  listing it as possible function for all possible types it has strong tendency of spreading all over the place in your users's code.   
I believe that as a **UI component library provider** you **should not** expose extensions on **object** or common types like **string**, **IEnumerable<T>**  ...    if you need them internally, better do define as traditional static function..

**Comment by David-Moreira** [comment]
> The point is that having extension on object type is generally consider as anti-patter, and can have some unexpected side effect.

First time I hear about this. What's the reasoning people use for it being an anti pattern? 
Being an "anti pattern" because of how intellisense works is different from being an "anti pattern" from a best practices coding perspective.

If there's a reason for an extension to be available on the base object on your code base, which you extensibly use it as such, I don't see why not.

**Comment by David-Moreira** [comment]
![image](https://github.com/Megabit/Blazorise/assets/22283161/ed390d1b-f5c1-4429-abc5-c1f8e8853582)

**Comment by rbillott** [comment]
To answer to the disagreement on the pattern. 

I did the test in my solution having few dependencies (Blazorise, Nlog, FluentEmail, AutoMApper, CvsHelper, Newtonsoft, and bunch of MS ones) checking extension on primitive type (like int) and I just have 2 extensions showing up .  
- `IsEquals<T>(this T..)` // from you Blazorise.Extensions
- `ToExpando(this object..) `// from RazorLight.Extension  (btw do not get any auto import for this namespace )

So I guess it is not exactly a **common pattern**.

And indeed I personally like when my IntelliSense is not getting polluted by bunch of utility extensions. I understand you have your own good reason to use it. But I believe that's part of a **good developer experience** to have clean dev environment, without the need of changing the IDE settings  even when using 3rd party libraries. Plus, I see it as a risk of side effect as it looks like a framework function and can be miss used; even if your "IsEquals" seems perfectly safe, generally speaking, as library provider you cannot guaranty the behaviour on unknown types (also true for interface, you might say, but there is way less risk of miss-usage)..  

To be honest it is probably more a language issue, it would be better if we could declare a public extension and limit the scope to internal usage only.. but that's another discussion topic.  

PS : It is still a bit mysterious why I am get those auto import for that namespace only as usually need to confirm them.. so I will try to monitor to see how that happen

**Comment by stsrki** [comment]
It is only a "problem" if the `Blazorise.Extensions` is imported. The problem in your case is that somehow the namespace is implicitly imported.

**Comment by rbillott** [comment]
Some additional info as I now know how to reproduce. 

- It's happening in the **Unit Tests only**.  
- and the import appear as soon as I type  ` Assert.Equal(`  which is the reason why it's happening so often.
