### ISSUE TITLE
What are the advanced features?

### ISSUE THREAD

**Issue by Tony20221** [Megabit/Blazorise#4949]
The docs says if you have a commercial license the advanced features are unlocked.
No where I can find any info about these features! I searched the docs, the support forum and here. Nothing!

**Comment by stsrki** [comment]
Hello @Tony20221 

The advanced features are extra themes, access to private projects that we have and use ourselves, and block products that are coming soon to the public. Nothing advanced is for the Blazorise core components. All our components are the same for everyone, and there is nothing that is locked for commercial or community use.

**Comment by David-Moreira** [comment]
> Thanks but once you mention there are advanced features, you need to mention what they are. Don't leave users wondering what that phrase means.

Hello @Tony20221 
We are always open to suggestions or ways we can improve. Could it be the page you've visited didn't go into details, for brevity sake? Can I ask you where in **Blazorise** you've seen this and how do you feel we can better improve? 

I believe that on our **Pricing** page currently does a good job at explaining our offerings by comparing every plan we have available and what they each offer.

https://blazorise.com/pricing
![image](https://github.com/Megabit/Blazorise/assets/22283161/92bd8d52-5989-46da-a7ad-3938b10feacd)
