### ISSUE TITLE
🔧 1.3 Support Docs

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#4962]
## 1.3.5

- #5221
- #5233
- #5256

## 1.3.4

- #5145
- #5173
- #5181
- #5185
- #5184

## 1.3.3

- #4578
- #5103
- #4994
- #5120
- #5114
- #5105
- #3802
- #5121
- #5132
- #5116
- #5137

## 1.3.2

- #4951
- #4973
- #4886
- #4981
- #4995
- #4955
- #4975
- #4940
- #4874
- #5015
- #5038
- #5020
- #5051
- #5041
- #5058
- #4992
- #5070
- #5063
- #5073

**Comment by David-Moreira** [comment]
I'm going ahead and pinning this as it might be useful for users to know what's coming next.
Please go ahead and unpin, if you find it's not worth having this pinned.
