### ISSUE TITLE
DataGrid in the docs is shared and can be edited by everyone

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#4964]
Basically, everyone can edit data in DataGrid on our main docs pages. And when saving it it is visible by everyone. We need to make it so that it is not shared and only accessible by one user.

![image](https://github.com/Megabit/Blazorise/assets/900302/f23e5c2d-9145-406b-b38a-2f76ad26ebf6)

**Comment by David-Moreira** [comment]
Closed by #4965
