### ISSUE TITLE
Blazorise TextEdit RegEx issue

### ISSUE THREAD

**Issue by lachlanlhhq** [Megabit/Blazorise#4972]
RegEx that used to work is no longer working the same way as it previously did.

Steps to reproduce the behaviour:
1. Create a Text Edit field
2. Add MaskType="MaskType.RegEx" and EditMask="^(\d+(\.\d{0,2})?|\.?\d{1,2})$"
3. Try to type decimals in the field
4. The field does not allow decimals

The behaviour expected of the field is to allow decimals to 2 places. This code used to work but it was only noticed recently that it no longer functions anymore. We are using the numeric edit in the mean time with a decimal t value, but this does not allow us to put negative values in easily (you must type a number then add the negative after). We were using the text edit as a way around this and to be able to control the mask type and regex manually, but something has changed.

Example field:
![image](https://github.com/Megabit/Blazorise/assets/144070285/ac4e35e9-5c72-4c18-b4f7-ae03e65084c9)

Please find below the link to the original bug raised on the abp support forum 
https://support.abp.io/QA/Questions/5616/Blazorize-Text-Edit-Control-with-Regex-not-working

Any info on what has caused the issue and how to rectify would be greatly appreciated.

Thanks

**Comment by stsrki** [comment]
We will look into it. In the mean time, can you try to use NumericPicker instead of NumericEdit? It should have more control over value editing.

**Comment by stsrki** [comment]
I have tested and I cannot reproduce it on my machine. Can you provide us with more information?

- Blazorise version?
- Browser?
- Locale setting?

**Comment by latchyy94** [comment]
Blazorise Version: 1.2.4
Browser: Google Chrome
Locale setting: English

In our instance if you type the decimal into the empty field it looks as though it is trying to add it as the text cursor flashes, but no decimal shows up. I tested in edge as well and the same behaviour persists there.

And this is our on text changed method for the field which has been the same since August 2022 when it was implemented and working:

        private void AmountValueChanged(int index, string value)
        {
            if (string.IsNullOrWhiteSpace(value.ToString()))
            {
                Amount = null;
            }
            else
            {
                Amount = Convert.ToDecimal(value);
            }
            StateHasChanged();
        }

**Comment by David-Moreira** [comment]
@stsrki

**Comment by stsrki** [comment]
My suspect is that the locale might be what is causing it. I will need to recheck.

**Comment by stsrki** [comment]
I'm still unable to reproduce it. I have tried with several different cultures and locales.

**Comment by lachlanlhhq** [comment]
It seems like the main culprit might be the TextChanged property. I created a new simple solution and added our code to the Index.razor and the issue is occurring. Below is each page and the code that was added there to test. My guess would be the TextChanged has been updated since we first implemented it and that caused the previously working code to no longer work.

**Index.razor:**

<Field ColumnSize="ColumnSize.Is1">
    <FieldLabel>Amount</FieldLabel>
    <TextEdit aria-label="Amount" MaskType="MaskType.RegEx" EditMask="^(\d+(.\d{0,2})?|.?\d{1,2})$" TextChanged="(string value) => AmountValueChanged(value)" Text="@Amount.ToString()"></TextEdit>
</Field>

**Index.razor.cs:**

  public partial class Index
  {
      private decimal? Amount { get; set; }


      private void AmountValueChanged(string value)
      {
          if (string.IsNullOrWhiteSpace(value.ToString()))
          {
              Amount = null;
          }
          else
          {
              Amount = Convert.ToDecimal(value);
          }
      }

  }

**Comment by stsrki** [comment]
There is your problem. You're converting the raw Text string value to a number, and it will lose all the details of a string once it is converted. Like the position of a decimal place, padding, and trailing zeros, etc. You must always work with a value that you're binding. In this case, you should bind to a string directly. And then, if needed, you can convert it to a decimal without affecting the original.

```razor
<TextEdit @bind-Text="YourFieldName" />

@code {

  string YourFieldName { get; set; }
 
  // add error handling
  decimal? YourAmount => Convert.ToDecimal(YourFieldName);
}
```
