### ISSUE TITLE
In the Autocomplete you can see what you are typing

### ISSUE THREAD

**Issue by tacoWanneeJama** [Megabit/Blazorise#4973]
The standard Autocomplete shows this while typing:
![image](https://github.com/Megabit/Blazorise/assets/76042577/3cd9a3be-17d4-4711-ae99-1f52e47352c7)

I think it very uncomfortable, that you can't see what you are typing.

I used https://blazorise.com/docs/extensions/autocomplete for the example.

**Comment by stsrki** [comment]
This seems like a bug. It might be because we have introduced a new library for dropdown menus.  @David-Moreira?

**Comment by David-Moreira** [comment]
Strange I remember we had the bug also on the side menu of the docs and we had fixed it... #4924 And it's there again...
![image](https://github.com/Megabit/Blazorise/assets/22283161/cfa70611-85c0-4d94-941e-c42b2bd70ac0)

Well I'll have to take a look.
