### ISSUE TITLE
Helper Packages : Unit Tests

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#4977]
Provide helper packages.

Unit tests has been a recurring topic where users could benefit of a few helper methods to help them get started faster.

@stsrki ideas for the helper packages naming convention?
Blazorise.**Helpers**.BunitTests
Blazorise.**Utilities**.BunitTests
Blazorise.BunitTests

**Comment by stsrki** [comment]
I would go with Tests in the middle in case we in the future add more support for other testing libraries. We could also add an E2E tests.

- Blazorise.Tests.bUnit
- Blazorise.Tests.Playright

**Comment by David-Moreira** [comment]
Ok, It was just if we had other type of helper packages we would have an easy to go to name, and everything would be under the same bucket. I'm fine with this also.

**Comment by rbillott** [comment]
That's great initiative to have a package that contains the helper code for Bunit (and other frameworks)  

I just want to share some helpers I coded in my project on top the ones I found here. 
I have an extension I call wherever I need it from a Razor Test class, and also a custom attribute that list the needed components. 

```
    public static class BlazoriseTestExtension
    {
        public static void SetupBlazorise(this TestContext context)
        {
            // don't recall well why this is needed
            context.Services.AddBlazorise().Replace(ServiceDescriptor.Transient<IComponentActivator, ComponentActivator>());
            BlazoriseConfig.AddBootstrapProviders(context.Services);

            if (Attribute.GetCustomAttribute(context.GetType(), typeof (BlazoriseJSInteropAttribute)) is BlazoriseJSInteropAttribute attribute)
            {
                foreach (var name in attribute.Names)
                {
                    var methodInfo = typeof(BlazoriseConfig.JSInterop).GetMethod($"Add{name}");
                    if (methodInfo == null) throw new ArgumentException($"<{name}> is not a valid Blazorise component name or there is no interop support");
                    methodInfo.Invoke(null, new object?[]{context.JSInterop});
                }
            }
        }
    }


    [AttributeUsage(AttributeTargets.Class)]
    public class BlazoriseJSInteropAttribute : Attribute
    {
        internal string[] Names { get; }
        public BlazoriseJSInteropAttribute(params string[] names)  {  Names = names;   }
    }
```

And below is a test class to demonstrate the usage

```
    [BlazoriseJSInterop("Button","DataGrid","Breakpoint")]
    public class MyPageTest : TestContext
    {
        public MyPageTest ()
        {
            this.SetupBlazorise();
        }

        [Fact]
        public void MyPageTest_ShouldRenderCorrectly()
        {

            // Act
            var cut = RenderComponent<MyPage>();

            // Assert
            Assert.NotNull(cut.Find("div#Xxxx"));
 

```
