### ISSUE TITLE
DataGrid - Consistent height regardless of amount of data

### ISSUE THREAD

**Issue by masteratt** [Megabit/Blazorise#4978]
**Is your feature request related to a problem? Please describe.**
I am trying to make it so that the DataGrid always covers the height it is given, regardless of how much data is in it. I set height to 100% to no avail. The container of it might be filling that 100% space but the rows only show the ones with data.

For example, this:
<img width="438" alt="image" src="https://github.com/Megabit/Blazorise/assets/36424101/f56a8a6c-079a-4bc1-aaba-93de0b900c9a">

Should look something like this (rough mockup):
<img width="437" alt="image" src="https://github.com/Megabit/Blazorise/assets/36424101/1ccd4cab-9557-403d-8f10-6cc816808f29">

**Describe the solution you'd like**
Maybe an option like "ShowEmptyRowsToFillHeight" or something so the table always is the given height.

### Additional context
This is a paged example but Virtualised table does the same even with `VirtualizeOptions="@(new VirtualizeOptions { DataGridHeight = "500px" })` for example, if there's only one row of data, it doesn't fill that 500px.

If there's a way to handle this already, please let me know!
_PS: I did spend a long time googling and checking docs and couldn't find anything._

**Comment by David-Moreira** [comment]
Hello @masteratt 
Is this what you're looking for?

https://blazorise.com/docs/extensions/datagrid/features/fixed-header
https://bootstrapdemo.blazorise.com/tests/datagrid/fixed-header

**Comment by masteratt** [comment]
Hi @David-Moreira - Not exactly. I want the table to fill that empty space out even if there is only one row of data.

<img width="1120" alt="Screenshot 2023-09-05 203001" src="https://github.com/Megabit/Blazorise/assets/36424101/51620b8d-f6a2-4d48-9fba-2c846b9ca393">


Here is a super simple demo project using the options in your example:
https://drive.google.com/u/0/uc?id=1FsSr7JBsBGEG3kvk1UybMZOaSVO09Hmo&export=download
_If you don't want to download that just have a col within a row and a table with one row of data._

I want the table to fill that bg-dark column height fully with the DataGrid. I can achieve this by adding "h-100" to the `<DataGrid>` class but that adjust the size of the single row to be massive:
<img width="807" alt="image" src="https://github.com/Megabit/Blazorise/assets/36424101/0695d656-954a-4e70-a38b-0628e10867da">

So where I'm trying to get to:
DataGrid to fill the height of that dark column but without messing with the row height.

**Comment by David-Moreira** [comment]
Hello, it should work with 
```
FixedHeader
FixedHeaderDataGridHeight="250px"
```

`FixedHeaderDataGridHeight` tells the DataGrid the height to be at.

![image](https://github.com/Megabit/Blazorise/assets/22283161/4d3c410f-b994-4b61-94ae-0de6ca9a93ef)

**Comment by masteratt** [comment]
Thanks you and yes that works great if it's white on white but when put in front of a dark background, which is our case, it looks very off. By which I mean the one row to the page controls gap is not our desired look.

<img width="632" alt="image" src="https://github.com/Megabit/Blazorise/assets/36424101/b15462dd-597c-4114-88ee-c43021c7a37f">

Desired outcome:
The red highlighted bit in that screenshot, it'll be nice if it was empty rows instead of the table cutting off after that one row. I hope this makes sense? See my rough mock-up in original post for our desired look.

**Comment by David-Moreira** [comment]
I guess you will have to manually style it. If you are using the suggested **Fixed Header** feature. The Grid will have a `table-fixed-header` class which you can use to style.

try adding the background that you want:

```
.table-fixed-header{
  background:white;
}
```

**Comment by masteratt** [comment]
Yep, that did it thanks. We have to do more custom styling for that to look good for striped rows for example but at least we got the look we want now. 

Optimally some attribute like "ShowEmptyRowsToFillHeight" or something would be good but I'm not sure how realistic that is or the demand for it.

Happy for request to be closed as this is an acceptable compromise. Thanks for ping-ponging ideas.

**Comment by David-Moreira** [comment]
I understand that ideally a component library can do almost everything for us!! 
But this seems too niche of a feature, which is easily fixed by some custom styling.
@stsrki Would you agree on going ahead and closing this?
