### ISSUE TITLE
Add FilterMethod to DataGridColumnInfo

### ISSUE THREAD

**Issue by PatrickBig** [Megabit/Blazorise#4981]
**Is your feature request related to a problem? Please describe.**
I'm attempting to utilize the `ReadData` event in a Blazorise.DataGrid component in the menu filtering mode.

With the current state I am unable to send the `DataGridFilterMethod` *eg: Contains vs Equal to, etc* since this is missing from the DataGridColumn info.

**Describe the solution you'd like**
Modify `DataGridColumnInfo.cs` to contain a `public DataGridFilterMethod FilterMethod` property containing the value from the column definition.
When building the `DataGridReadDataEventArgs<T>` ensure the filter method from the column is passed to the event arguments on the `ReadData` event.

**Comment by David-Moreira** [comment]
This should have been in the **v1.3** release so users are able to selectively filter by column on readdata.
It was a miss on our part.
