### ISSUE TITLE
[Bug]: Numeric Edit resets on Lost Focus

### ISSUE THREAD

**Issue by cholden-dev** [Megabit/Blazorise#5004]
### Blazorise Version

1.3

### What Blazorise provider are you running on?

None

### Link to minimal reproduction, or a simple code snippet

<Field Class="mb-2">
                <FieldLabel>@Label</FieldLabel>
            <FieldBody>
                <NumericEdit TValue=@TValue
                    Style=@Style
                    Value=@Value 
                    ValueChanged=@ValueChanged 
                    Placeholder=@Placeholder
                    Disabled=@ReadOnly
                    Min=@MinValue
                    Max=@MaxValue>
                    <Feedback>
                        <ValidationError />
                    </Feedback>
                </NumericEdit>
            </FieldBody>
        </Field>

### Steps to reproduce

Enter a value into the input.
Change focus from the component.

### What is expected?

The bound value remains in the input after focus changes.

### What is actually happening?

The value resets to original default value. 0 in the case of TValue being Int

### What browsers are you seeing the problem on?

Chrome

**Comment by stsrki** [comment]
This is the expected behavior. The `int` type cannot have an empty value. Hence, the default is set to 0. If you want to have an empty or null value then the `TValue` must be an `int?` type.

**Comment by cholden-dev** [comment]
> This is the expected behavior. The `int` type cannot have an empty value. Hence, the default is set to 0. If you want to have an empty or null value then the `TValue` must be an `int?` type.

Hi, the value isn't empty during this behaviour, say for example I enter 2 , then click on the next element in the form, the value resets to 0

**Comment by stsrki** [comment]
Does it have Min or Max defined? Can you provide a code to reproduce it?

**Comment by cholden-dev** [comment]
My apologies, this is a bug with a wrapper component we are using that passes all the properties down into the NumericEdit, which was misleading.
