### ISSUE TITLE
[Bug]: Still Two Buttons on FileEdit

### ISSUE THREAD

**Issue by TorreyGarland** [Megabit/Blazorise#5008]
### Blazorise Version

1.3.1

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction, or a simple code snippet

```
 <Div Class="form-group mb-3">
     <Label For="exampleFormControlFile1">File input</Label>
     <FileEdit ElementId="exampleFormControlFile1"  />
 </Div>
```

![file-edit-3](https://github.com/Megabit/Blazorise/assets/1054548/3e9ad5be-0cda-4955-a5bb-9d1cd61a566a)

![file-edit-2](https://github.com/Megabit/Blazorise/assets/1054548/71fa7acc-0884-4414-a153-aff4449f88f5)

![file-edit-1](https://github.com/Megabit/Blazorise/assets/1054548/3db6535d-7c62-41a5-97de-0fb0e357d41d)

### Steps to reproduce

Open blazor page in Microsoft Edge.  See FileEdit Display two(2) "Choose File" elements.

### What is expected?

Only one "Choose File" element displayed.

### What is actually happening?

Two (2) "Choose File" elements displayed.

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by stsrki** [comment]
The problem is that you're mixing some of the class names that are not supported in Bootstrap 5 anymore, eg. `form-group`. Also, mixing regular HTML and components is not recommended, as Blazorise cannot properly detect how to render.

It is recommended to **always** use our `Field` component when wrapping input components.

Try this:

```razor
<Field>
    <FieldLabel>Default file input</FieldLabel>
    <FieldBody>
        <FileEdit Placeholder="Please select the file..." />
    </FieldBody>
</Field>
```

**Comment by David-Moreira** [comment]
@TorreyGarland can you please let us know if this has helped you? Thanks!

**Comment by TorreyGarland** [comment]
Is this documented on your documentation page.  I didn't see it.

**Comment by David-Moreira** [comment]
Hello @TorreyGarland 

![image](https://github.com/Megabit/Blazorise/assets/22283161/13ba3a3e-1afc-4761-83bc-ec0ec9d2dbba)
https://blazorise.com/docs/components/field

![image](https://github.com/Megabit/Blazorise/assets/22283161/8edc961c-4bd5-49b9-b074-1b3841e6f37b)
https://blazorise.com/docs/components/file

Going ahead and closing the issue, just feel free to reopen if you encounter any difficulties.

**Comment by TorreyGarland** [comment]
I have a custom layout in which I don't want to surround the FileEdit with a Field.  What now???
