### ISSUE TITLE
Add ImageViewer component

### ISSUE THREAD

**Issue by He-Wu** [Megabit/Blazorise#5023]
This is a component I saw in other component libraries
![image](https://github.com/Megabit/Blazorise/assets/56440130/18e352c6-35c4-4106-bbbd-2fa051767302)
Click on the image to preview the larger image
![image](https://github.com/Megabit/Blazorise/assets/56440130/ce74585c-94da-47ea-ba14-78125814246a)
I can't wait to have a component like this used in datagrid
Can you add an ImageViewer component, this is very important to me, thank you

**Comment by stsrki** [comment]
This is something that you can already build yourself with Blazorise components. It's just a simple use of `Image` and `Modal` components.

eg.

```razor
<Image Source="your/image/path.jpg" Fluid @onclick="@(()=>modalRef.Show())" />

<Modal @ref="modalRef">
    <ModalContent Centered>
        <ModalHeader>
            <ModalTitle>Image Viewer</ModalTitle>
            <CloseButton />
        </ModalHeader>
        <ModalBody>
            <Image Source="your/image/path.jpg" Fluid />
        </ModalBody>
        <ModalFooter>
            <Button Color="Color.Secondary" Clicked="@HideModal">Close</Button>
        </ModalFooter>
    </ModalContent>
</Modal>
```

**Comment by He-Wu** [comment]
Thank you very much, your answer is very helpful to me
