### ISSUE TITLE
I saw that there is no information related to <form></form> in the document.

### ISSUE THREAD

**Issue by He-Wu** [Megabit/Blazorise#5024]
Can you add the corresponding documentation to https://blazorise.com/?

**Comment by stsrki** [comment]
Hello @He-Wu. What kind of information do you wish to see in the docs regarding the form?

**Comment by David-Moreira** [comment]
Hello @He-Wu 
Tipically we do not make use of `Form` component in our forms.
We have dedicated apis and structure for validation and feedback, that mimick some of the behaviour that's provided by the Blazor `Form` component.

Maybe this is what you're looking for? There should be a few blazorise form examples in this page:
https://blazorise.com/docs/components/validation
https://blazorise.com/docs/extensions/fluent-validation

Please let us know if this helps.

**Comment by He-Wu** [comment]
Thank you very much, this successfully solved my problem
