### ISSUE TITLE
[Bug]: RTE QuillJS uses deprecated js

### ISSUE THREAD

**Issue by njannink** [Megabit/Blazorise#5032]
### Blazorise Version

1.3.1

### What Blazorise provider are you running on?

Material

### Link to minimal reproduction, or a simple code snippet

When using Blazorise RTE you see the following warnings: 

quill.js:4237  [Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.

### Steps to reproduce

Open https://blazorise.com/docs/extensions/richtextedit

### What is expected?

no errors or warnings

### What browsers are you seeing the problem on?

Microsoft Edge

### Any additional comments?

Probably in the near future we will have to deprecate the current RTE since QuillJS isnt beind maintained anymore. Our penetration test also generated remarks about the usage of QuillJS so we will have to migrate away from Blazorise.RichTextEdit to RoosterJS. I will donate some of this work to the PR I already started a while ago.

**Comment by benny-adiwijaya** [comment]
Any update on this?

**Comment by njannink** [comment]
Good work @stsrki. Might be good to have a more indepth look to migrate the solution to how other Blazorise modules work so its no longer loading the scripts and stylesheets from external sources
