### ISSUE TITLE
Blazorise Datagrid - select (and highlight) first element of Datagrid after refresh

### ISSUE THREAD

**Issue by mgosx** [Megabit/Blazorise#5036]
Hi,
after doing a refresh of my datagrid I would like to select the first Item in the list.
My page displays the list on the left and on the right I get some Details of the selected Item.

Here is the Datagrid definition:
            <DataGrid
                 Data="@orders"
                  TItem="Order"
                  SelectedRowChanged="@selectedOrder">

After refreshing the datagrid I could call **selectedOrder = orders[0]**. 
Like that the details (on the right) would be shown.
But the first Item in the grid is not highlighted, the user doesn't see which row is selected.

How could I highlight the first (or any other) row by code instead of clicking on the row?

I hope everybody could follow my thoughts,

Mark

**Comment by David-Moreira** [comment]
Hello @mgosx 

Sometimes the documentation may assume some basic understanding of **Blazor** features.

In this case, to call component methods in **Blazor** you need to set up a reference to the component, that is the `DataGrid`.

Refer to : 
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-7.0#capture-references-to-components

That would look something like the following "pseudo code"
`<DataGrid @ref=_dataGridRef.... >`
```
@code{
private DataGrid<MyTItem> _dataGridRef;
}

private void CallSelectMethodOnDatagrid(){
//Might need to null check _dataGridRef depending on where the method is called. (i.e DataGrid is not yet initialized)
    await _dataGridRef.Select(...);
}
}
```

Let us know if this has helped you programatically calling a method on the `DataGrid`.

**Comment by mgosx** [comment]
Thank you very much, you've made my day.

Everything works fine now.
