### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by He-Wu** [Megabit/Blazorise#5044]
### Blazorise Version

1.2.3

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction, or a simple code snippet

<Select TValue="object" @bind-SelectedValue="Value" SelectedValueChanged="ValueChanged">
 
    @foreach (var item in SelectItems)
    {
        <SelectItem Value="@item.Value">@item.Key</SelectItem>
    }
</Select>

### Steps to reproduce

Same as the picture

### What is expected?

Two-way binding and can listen to drop-down option change events

### What is actually happening?

@bind-SelectedValue cannot be used together with the SelectedValueChanged event. The exception prompt is as follows RZ10010: The component parameter 'SelectedValueChanged' is used two or more times for this componentParameters must be unique (case-insensitive). The component parameter 'SelectedValueChanged' is generated by the ' @bind-SelectedValue' directive attribute.
So when I need two-way binding, how can I listen to the SelectedValueChanged event?
![image](https://github.com/Megabit/Blazorise/assets/56440130/5a7dfecc-fdfa-42e9-ae22-edfed3c0e6e2)

**Comment by stsrki** [comment]
This behavior is coming from Blazor. When you use `@bind-SelectedValue="Value"`, Blazor will automatically bind it as `SelectedValue="Value"`, and SelectedValueChanged="@(v=>Value = v)". The only alternative is for you to write it yourself without the `@bind-` part.

**Comment by He-Wu** [comment]
Please tell me how to monitor the value change event after I bind it during weekends.

**Comment by stsrki** [comment]
```razor
<Select SelectedValue="Value" SelectedValueChanged="@OnValueChanged">
  ...
</Select>

@code{
  Task OnValueChanged(object value)
  {
    Value = value;

    // do any additional logic here if necesary

    return Task.CompletedTask;
  }
}
```
