### ISSUE TITLE
[Bug]: Select Bug

### ISSUE THREAD

**Issue by He-Wu** [Megabit/Blazorise#5047]
### Blazorise Version

1.3.1

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction, or a simple code snippet

```
this is my demo componet

<Select TValue="enumTest" @bind-SelectedValue="Value">
    <SelectItem Value="enumTest.Test0">0</SelectItem>
    <SelectItem Value="enumTest.Test1">1</SelectItem>
    <SelectItem Value="enumTest.Test2">2</SelectItem>
</Select>

@code {
    [Parameter]
    public enumTest Value { get; set; }
}
```

this is my test page
```
@page "/"

<BlazorApp1.Components.Test Value="Value"></BlazorApp1.Components.Test>
<Button Clicked="IncrementCount">test</Button>
@code {
    private int currentCount = 0;
    public enumTest Value { get; set; }
    private void IncrementCount()
    {
        Console.WriteLine(Value);
    }
}
```

### Steps to reproduce

I encapsulated the Select component in a new Test component. After changing the option, click any button and the Select value will be reset.
But I don’t put it in the component. Clicking the button can get the normal value. I don’t know if this is a bug. I need to re-encapsulate this component for subsequent use.

### What is expected?

Clicking the button should not reset the component

### What is actually happening?

Clicking the button should not reset the component

### What browsers are you seeing the problem on?

Chrome

**Comment by stsrki** [comment]
It happens because you're made it work only on one-bind mode. So every time it rerenders, it will always reset. You need to make it into a two-way binding.

First made it like this:

```
<Select TValue="enumTest" @bind-SelectedValue="Value">
    <SelectItem Value="enumTest.Test0">0</SelectItem>
    <SelectItem Value="enumTest.Test1">1</SelectItem>
    <SelectItem Value="enumTest.Test2">2</SelectItem>
</Select>

@code {
    Task OnSelectedValueChanged(enumTest value)
    {
        Value = value;
        return ValueChanged.InvokeAsync(Value);
    }

    [Parameter]
    public enumTest Value { get; set; }

    [Parameter]
    public EventCallback<enumTest> ValueChanged { get; set; }
}
```

Next on your page use it as:

`<BlazorApp1.Components.Test @bind-Value="Value" />`

---

PS. You should really look into some fundamentals of how Blazor works. An excellent source of knowledge is https://blazor-university.com/components/two-way-binding/

**Comment by He-Wu** [comment]
Thank you very much, but using your example, clicking any button after using bind-Value will still reset the Select value.
OnSelectedValueChanged in your code doesn't seem to come in handy

**Comment by stsrki** [comment]
Yeah, I was quick to type and didn't test.

Do this

```razor
<Select TValue="enumTest" SelectedValue="@Value" SelectedValueChanged="@OnSelectedValueChanged">
    <SelectItem Value="enumTest.Test0">0</SelectItem>
    <SelectItem Value="enumTest.Test1">1</SelectItem>
    <SelectItem Value="enumTest.Test2">2</SelectItem>
</Select>

@code {
    Task OnSelectedValueChanged(enumTest value)
    {
        Value = value;
        return ValueChanged.InvokeAsync(Value);
    }

    [Parameter]
    public enumTest Value { get; set; }

    [Parameter]
    public EventCallback<enumTest> ValueChanged { get; set; }
}
```

**Comment by He-Wu** [comment]
Thank you very much, this successfully solved my problem
