### ISSUE TITLE
serial number automatically generated by datagrid

### ISSUE THREAD

**Issue by He-Wu** [Megabit/Blazorise#5055]
![image](https://github.com/Megabit/Blazorise/assets/56440130/0224e59c-1726-4aa1-9772-0f1ea3a35a45)
I need such a self-increasing serial number. Can this column be displayed through configuration?

**Comment by David-Moreira** [comment]
Currently not. I'm not sure this should be a concern/feature of the `DataGrid`.
Why is it not viable for you to iterate over your data and assign a sequential `Id`?

**Comment by stsrki** [comment]
You can also just use DisplayTemplate on the fly.

```razor
<DisplayTemplate>
  <Span>@yourDataList.IndexOf(context)</Span>
</DisplayTemplate>
```

**Comment by He-Wu** [comment]
> You can also just use DisplayTemplate on the fly.
> 
> ```
> <DisplayTemplate>
>   <Span>@yourDataList.IndexOf(context)</Span>
> </DisplayTemplate>
> ```

wow,good idea,thank you very much
