### ISSUE TITLE
TextEdit Placeholder

### ISSUE THREAD

**Issue by He-Wu** [Megabit/Blazorise#5060]
![image](https://github.com/Megabit/Blazorise/assets/56440130/f5c43866-1c46-4fb2-aeee-2abf6ff9ee3a)
Hello, I want the placeholder to be centered, is it possible?

**Comment by stsrki** [comment]
It's not possible to do it natively with Blazorise. But you can override it with some custom CSS. See https://stackoverflow.com/questions/7381446/center-html-input-text-field-placeholder

Although I would advise against centering it as it can be considered an antipattern from a UX perspective.

**Comment by He-Wu** [comment]
thank you very much
