### ISSUE TITLE
[Bug]: datagrid not showing updated content

### ISSUE THREAD

**Issue by HansMeiser234** [Megabit/Blazorise#5075]
### Blazorise Version

1.3.1

### What Blazorise provider are you running on?

None

### Link to minimal reproduction, or a simple code snippet

no link

### Steps to reproduce

Hello,

I noticed a change of datagrid behaviour. I updated to 1.3.1 a few days ago, but i think i realised this problem right now.

I have a datagrid which is filled by sql. By input on my page it is possible that sql-data and so content of my datagrid changes. i have tasks to save data and refill lists.
However i still see old and not updated content in my datagrid, but every testoutput on console or html shows the new data. I reduced datagrid to absolute minimum to avoid sideeffects, but still dont want to work:

```
<tr>
        <td style="width:5%">&nbsp;</td>
        <td colspan="5">
        <DataGrid TItem="AktuelleAusnahmen"
          Data="@aktuelleausnahmen"
          Responsive>
          <DataGridCommandColumn />
    <DataGridColumn Field="@nameof( AktuelleAusnahmen.VMName )" Caption="VM" Editable></DataGridColumn>
</DataGrid>
        </td>
	</tr>
    @foreach(var testdata in aktuelleausnahmen){
        <tr>
            <td colspan="6">@testdata.VMName - </td>
        </tr>
    }
```
The datagrid is unchanged, but the foreach shows new content. It seems that datagrid ist not automatically updating the view.
I have to reload the page to view updates in datagrid.
Was there something changed in this behavior?

### What is expected?

Autoupdating the datagridview.

### What is actually happening?

nothing visible

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Any additional comments?

no further comments

**Comment by HansMeiser234** [comment]
Hello David,

i have a lot of datagrids, almost multiple in every page. Hummpfff....

Sometimes my datagrids are not visible, it depends on securitylevel of user. In this case i have to make same decision to gridRef.Reload(); because reloading a not visible object leads to a crash.

**Comment by HansMeiser234** [comment]
Hello David,

this seems to work. I just changed 

`List<AktuelleAusnahmen> aktuelleausnahmen = new List<AktuelleAusnahmen>();`
into
`ObservableCollection<AktuelleAusnahmen> aktuelleausnahmen = new ObservableCollection<AktuelleAusnahmen>();`
and removed all refs and reloads.

I had an immediatley visible update of my datgrids and it seems to work properly.

But as a casual programmer i do not know if i should expect sideeffects or basic behaviour/methods of List and ObservableCollection are identical. I will investigate further.

Hans

**Comment by David-Moreira** [comment]
> Hello David,
> 
> this seems to work. I just changed
> 
> `List<AktuelleAusnahmen> aktuelleausnahmen = new List<AktuelleAusnahmen>();` into `ObservableCollection<AktuelleAusnahmen> aktuelleausnahmen = new ObservableCollection<AktuelleAusnahmen>();` and removed all refs and reloads.
> 
> I had an immediatley visible update of my datgrids and it seems to work properly.
> 
> But as a casual programmer i do not know if i should expect sideeffects or basic behaviour/methods of List and ObservableCollection are identical. I will investigate further.
> 
> Hans

It should work pretty much as a List. The observable collection adds observability over the operations that mutate the list, like `Add`, `Remove`, `Clear`, etc... that are exposed via an interface (`INotifyChanged` or something like that) where other apis (like the DataGrid) can listen to these changes and proceed accordingly.
