### ISSUE TITLE
Filtering - Value DisplayTemplate

### ISSUE THREAD

**Issue by KatarinaPr3** [Megabit/Blazorise#5081]
Is there a way to create filtering for a DataGridColumn based on the value displayed in the DisplayTemplate?
Example:

`<DataGridColumn Field="@nameof(User.CreatedDate)" Caption="Created" Filterable="true" Sortable="true">`
    `<DisplayTemplate>`
       ` @context.CreatedDate.ToString("dd MMMM yy")`
    `</DisplayTemplate>`
`</DataGridColumn>`

When I want to filter the data, what I search for applies to User.CreatedDate, but I want it to apply to the displayed value - @context.CreatedUtc.ToString("dd MMMM yy").
Is there a way to achieve this type of filtering?

**Comment by David-Moreira** [comment]
Hello @KatarinaPr3 
I'm not sure what the difference would be to filter a date on the displayed value? 
Anyway, you should be able to implement custom filtering & make it apply whatever rule you want. 
https://blazorise.com/docs/extensions/datagrid/features/filtering

**Comment by KatarinaPr3** [comment]
@David-Moreira Thank you for your response. 
For example, if the value is User.Created (type DateTime), for instance, "01/01/2023 07:00:00" and I want to display the value as "01 January 2023", I use a Display Template. When I enter the value "01 January" in the filter field for that column, I don't see any items. But, if I enter "01/01/2023"  then all items containing that actual property value, rather than the displayed value, are displayed.
I wanted to know if there is a possibility to adjust the field values without using a custom filter. 
Specifically, I want the filter should apply to the displayed value, not the property value.

I'll provide another example that might clarify the issue further:
If I want to do the same thing for an integer, for example, having a list of several items with the property "Count" set to 20, and I use a display template to show the value as @context.Value + 1. In this case, we are displaying the value 21 (while the property value is 20). I want to be able to filter by the displayed value every time I enter that value in the filter field, not the property value.
But here are some screenshots to show you what happens when I enter 20. How can I filter by the displayed values rather than the property values?
![Screenshot 2023-10-18 002040](https://github.com/Megabit/Blazorise/assets/79110651/e1864325-35d4-49f7-8531-b0f12abc713e) - Displayed values
![Screenshot 2023-10-18 002049](https://github.com/Megabit/Blazorise/assets/79110651/56a3e5fa-8b1b-48ca-b33d-785a4babad5a) - This is what happens when I enter the value I see.

![Screenshot 2023-10-18 002056](https://github.com/Megabit/Blazorise/assets/79110651/717e2835-1bce-45df-961c-91ac1cbd5655) - This is what happens when I enter the actual value of the property.

**Comment by David-Moreira** [comment]
> @David-Moreira Thank you for your response. For example, if the value is User.Created (type DateTime), for instance, "01/01/2023 07:00:00" and I want to display the value as "01 January 2023", I use a Display Template. When I enter the value "01 January" in the filter field for that column, I don't see any items. But, if I enter "01/01/2023" then all items containing that actual property value, rather than the displayed value, are displayed. I wanted to know if there is a possibility to adjust the field values without using a custom filter. Specifically, I want the filter should apply to the displayed value, not the property value.
> 
> I'll provide another example that might clarify the issue further: If I want to do the same thing for an integer, for example, having a list of several items with the property "Count" set to 20, and I use a display template to show the value as @context.Value + 1. In this case, we are displaying the value 21 (while the property value is 20). I want to be able to filter by the displayed value every time I enter that value in the filter field, not the property value. But here are some screenshots to show you what happens when I enter 20. How can I filter by the displayed values rather than the property values? ![Screenshot 2023-10-18 002040](https://user-images.githubusercontent.com/79110651/276019132-e1864325-35d4-49f7-8531-b0f12abc713e.png) - Displayed values ![Screenshot 2023-10-18 002049](https://user-images.githubusercontent.com/79110651/276019134-56a3e5fa-8b1b-48ca-b33d-785a4babad5a.png) - This is what happens when I enter the value I see.
> 
> ![Screenshot 2023-10-18 002056](https://user-images.githubusercontent.com/79110651/276019127-717e2835-1bce-45df-961c-91ac1cbd5655.png) - This is what happens when I enter the actual value of the property.

The `DisplayTemplate` is pretty much dynamic; it's a `RenderFragment` you can have anything pretty much anything in there, so filtering based on whatever's in there is not supported.

The filtering happens on that column's property value by default, that is why if you have custom requirements you need to implement a custom filtering.

In the latter example of context value+1, that's pretty much custom filtering, the system can't guess that, that row should be filtered by context value+1 instead of just the context value

Now there might be tricks you can do. You can try adding a **calculated property to your model**, for example, instead of doing 
`<DisplayTemplate>context+1</DisplayTemplate>`
You do 
`public int PropertyPlusOne => Property + 1;`
and assign that to the `DataGridColumn`, now `Filtering` should be able to properly filter on the values when it looks at the value on the property.

**Comment by KatarinaPr3** [comment]
Ok, I understand. Using custom filtering is one option for sure. I was just thinking if there is a built-in option to set what we want to filter without adding complexity to the model.

**Comment by David-Moreira** [comment]
I believe these are viable options. But feel free to provide any suggestion if you feel like there's a gap in our functionality.
I believe, the system can't really be guessing your "custom intentions", these are the options I see currently:

**Summarizing again**
1- Use your model to provide a proper property value with how you want to display and filter values
2- Use our CustomFilter to provide your customer handler for how you want to handle filtering
![image](https://github.com/Megabit/Blazorise/assets/22283161/af73c2f6-4681-4c76-9e8e-b96d3d236844)

https://blazorise.com/docs/extensions/datagrid/features/filtering
3- Use FilterTemplate

Closing issue. Feel free to reopen if you have any objections or feel like your issue hasn't really been solved.
