### ISSUE TITLE
How use Validation component on my custom componet?

### ISSUE THREAD

**Issue by He-Wu** [Megabit/Blazorise#5082]
**Is your feature request related to a problem? Please describe.**
I have a custom componet, How use Validation on my custom componet?

**Describe the solution you'd like**
I hope to use it like this, but it will prompt an error. It can only be used if it is defined internally in the component.
![image](https://github.com/Megabit/Blazorise/assets/56440130/cfd9bc77-9875-4108-86bb-5cd2e5cadc7b)

**Comment by He-Wu** [comment]
> 你好@He-Wu 它应该像这样使用：
> 
> ```
> <RadioGroup>
>     <ChildContent>
>         <Radio>
>         </Radio>
>         ...
>     </ChildContent>
>     <Feedback></Feedback>
> </RadioGroup>
> ```
> 
> https://blazorise.com/docs/components/validation

@David-Moreira Thank you very much, I know this is the reply, I mean when I cannot use <Feedback> in a custom component, I mean if my component name is FieldBody

**Comment by David-Moreira** [comment]
Only regular input components are supported for the `Feedback`. You cannot use it on `FieldBody`.

@stsrki Isn't that correct? Any other way?

**Comment by stsrki** [comment]
Correct. The Feedback is not a component. It is a render fragment that is only available inside of input components.

**Comment by He-Wu** [comment]
Hi, if I write a form component, I need to make it verifiable like other form components. How do I do that?

**Comment by He-Wu** [comment]
@stsrki Do you have any good suggestions or methods?

**Comment by stsrki** [comment]
Can you explain how custom your component is? In case it is a completely new component then you need to inherit it from `IValidationInput` and then wire all the methods that call the Validation. You can look into our source and see how it works https://github.com/Megabit/Blazorise/blob/master/Source/Blazorise/Base/BaseInputComponent.razor.cs#L131

**Comment by He-Wu** [comment]
> Can you explain how custom your component is? In case it is a completely new component then you need to inherit it from `IValidationInput` and then wire all the methods that call the Validation. You can look into our source and see how it works https://github.com/Megabit/Blazorise/blob/master/Source/Blazorise/Base/BaseInputComponent.razor.cs#L131

@stsrki thank you very much
