### ISSUE TITLE
Provide an easy way for a user to clear a field

### ISSUE THREAD

**Issue by mtbayley** [Megabit/Blazorise#5092]
It would be nice to have the ability to clear a field with the 'X' within a field. Autocomplete already has this.

Could this be extended to TextEdit, NumericEdit, DateEdit, etc?

![image](https://github.com/Megabit/Blazorise/assets/34929316/8d252b14-1a5c-4fa5-9297-22500b7707cd)

**Comment by stsrki** [comment]
The Autocomplete text field is based on an input with `type="search"`, as shown in the image below.

![image](https://github.com/Megabit/Blazorise/assets/900302/8eed86c9-6451-4ebe-9a84-5b79dd268874)

That means the clear button is handled natively by the browser. You can do the same on our regular TextEdit by defining the `Role` parameter, but for the Numeric and Date fields, I don't see it happening.

If you really want that feature, you can make it by placing them inside of an Addon and then having a clear button to reset the value.

**Comment by mtbayley** [comment]
```Role="TextRole.Search"``` was what I needed. Thanks!
