### ISSUE TITLE
[Bug]: NumericEdit not working with Debounce

### ISSUE THREAD

**Issue by realLiangshiwei** [Megabit/Blazorise#5100]
### Blazorise Version

1.3.2

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction, or a simple code snippet

From the ABP support: https://support.abp.io/QA/Questions/6034/NumericEdit-component-is-used-incorrectly-in-LeptonX-Theme-theme

### Steps to reproduce

https://blazorise.com/docs/components/numeric

Config the `Debounce` to true.

```csharp
context.Services.AddBlazorise(options =>
{
    options.Debounce = true;
});
```

### What is expected?

We expect the component to prevent decimal input, but no

### What is actually happening?

Decimals can be entered

**Comment by stsrki** [comment]
I don't see that you use Min or Max to prevent values. Have you tried to define them?

**Comment by realLiangshiwei** [comment]
Just:

```csharp
<NumericEdit Value="123" />
```

You can see two different behaviors with:

```csharp
context.Services.AddBlazorise(options =>
{
    options.Debounce = true;
});

//context.Services.AddBlazorise(options =>
//{
//    options. Immediate = true;
//});
```

**Comment by stsrki** [comment]
> ### What is expected?
> We expect the component to prevent decimal input, but no

The Debounce and Immediate are not to prevent from entering decimals. They are used as a means to delay the entered value or to postpone the entered value from submission until the user leaves the input field.

**Comment by realLiangshiwei** [comment]
If you try it, you will definitely notice the difference :)

**Comment by stsrki** [comment]
I'm trying it on https://blazorise.com/docs/components/numeric, and also locally. In both cases, the NumericEdit is working as expected.

**Comment by realLiangshiwei** [comment]
https://github.com/realLiangshiwei/QA5100

This is a reproducible example

<img width="1097" alt="image" src="https://github.com/Megabit/Blazorise/assets/16813853/ddf3fd07-f230-4d35-b155-f70061169380">

**Comment by stsrki** [comment]
Can you please explain what exactly needs to happen? I'm trying your repro and it is working as expected.

**Comment by realLiangshiwei** [comment]
OK.

https://blazorise.com/docs/components/numeric

In the example, You can see that the component is preventing decimal value:

<img width="1053" alt="image" src="https://github.com/Megabit/Blazorise/assets/16813853/c424ad18-0461-4df0-bbd2-b127ca35a5da">

<img width="1244" alt="image" src="https://github.com/Megabit/Blazorise/assets/16813853/c9716fcf-3956-49a7-876f-6d19b923503e">

**Comment by stsrki** [comment]
Ah, so the problem is decimals. That's an entirely different issue. OK, we need to explain i a bit more. The NumericEdit uses `input type="number"`. That means the input behavior is completely controlled by the browser. We have very little control over it. Some browsers may allow it by setting the `Step="1"` but that is not guaranteed to work.

My advice is if you want to allow only integers, then user our NumericPicker component. It was created just because of these limitations, and it has many more features.

**Comment by realLiangshiwei** [comment]
ok
