### ISSUE TITLE
Jsinterop exception sporadic ..dynamic loading error

### ISSUE THREAD

**Issue by annapras** [Megabit/Blazorise#5102]
Hello,

We are seeing sporadic errors with jsinterop 
Error is : unhandlled exception in circuit. Failed to fetch dynamically imported module .._content/blazorise/button.js?v=1.2.2.0 type error..

This also happens with utilities.js,memoedit and few others.

This doesn't happen all the time but sporadic

Blazorise version 1.2.2
Bootstrap5 provider

Are there any other known issues 

Thanks

**Comment by Flatscha** [comment]
Hi,

also stepped in an similar problem with _tooltip.js_ 
Do you use a Hybrid-Variant of Blazor (WinForms, Maui, ...)?
Does the modulepath start with __server_/_subpage_/_content/bla....

If so as a workaround until the devs fix the problem you could override the implementation of _IJSButtonModule_
Add this class-code to your wrapper-project (WinForms, Maui, ...)

```
public class HybridJSButtonModule : JSButtonModule 
{
    public override string ModuleFileName => "../_content/blazorise/button.js?v=" + base.VersionProvider.Version;

    public WinFormsJSTooltipModule(IJSRuntime jsRuntime, IVersionProvider versionProvider) : base(jsRuntime, versionProvider)
    {
    }
}
```
and override the service using:
```
services.RemoveAll<IJSButtonModule>();
services.AddScoped<IJSButtonModule, HybridJSButtonModule>();
```

Hope this helps

**Comment by stsrki** [comment]
From the error, it seems that your app is not configured correctly, `.._content/blazorise/button.js?v=1.2.2.0`. The` .._ `is not a valid path. 

Check what you have in your Startup

```cs
app.UsePathBase( "what is here" );
app.UseStaticFiles("or here");
```

**Comment by David-Moreira** [comment]
There seems to be 2 issues here, I'm not sure they are the exact same.

**1.** A sporadic error reported by @annapras where the js module sometimes throws an error?

We need more information about this. 
Does the page still works? Always on the same page with the same components? Or are you just seeing this on server error logs? Meaning it could be from users navigating away from pages before they fully load or something like that? If **it's sporadic** then it does not seem to be the same problem reported by @Flatscha as it should not work at all in that case, as it would never find the files.

**2.** Other issue, is what it seems to be static files configured in another path reported by @Flatscha , I guess Flastcha just found an alternative way to override the path where they get loaded from, but generally it's recommended to configure where the static files get loaded from in the startup just like @strski mentioned.

**Comment by annapras** [comment]
Hello,

The page doesn't work and we have to refresh the page for it to work.

There is only one page in the applications with 3 dropdowns,one of them being a multi select list.

This happens onload itself when the user gets the first and only page.

Are there any known issues with thia load of these components that could trigger in some conditions and error is not handled?

Thanks

**Comment by David-Moreira** [comment]
There are no known issues for transient unhandled errors on first page load. We'd probably have a few issues open if that happened.

Can we ask that you provide us with a repro that reproduces this? My guess is that it is something specific to your environment, so setting up the repo that reproduces the issue, might already lead you to find it, otherwise, we can take a look at it ourselves.

**Comment by annapras** [comment]
Hello
We are using blazorise.dropdownmenu in one of our components and encountering this issue of dynamic load failure sporadically.
Additional info..

Microsoft.jsinterop.jsexception failed to fetch dynamically imported module : https//appurl/_content/Blazorise/closable.js?v=1.2.2.0 at Microsoft.JSInterop.JSRuntime.InvokeAsync at Blazorise.modules.BaseJSModule.invokesafevoidasync(..)  at Blazorise.DropdownToggle.<HandleVisibilityStyles>b__13_0 at 
Blazorise.BaseAfterRENDErComponent.onafterrenderasync..

If there are any known issues or workaround that will be helpful..
Thanks

**Comment by David-Moreira** [comment]
Hello,
We've just told you that there are not known issues for a transient error like that.

We ask that you follow the request, and provide us with the reproducible, which will also help you make sure that by isolating the problem, there's nothing else on your environment that's affecting it,

Unfortunately for transient errors, this is the best course of action so we can troubleshoot & help you.

**Comment by annapras** [comment]
Ok, will tey to see what I can send..would you need code snippets?
I should clarify that the failure or error message occurs in 2 out of 10 requests and quite consistently..

**Comment by David-Moreira** [comment]
Reminder : 

> Hello @annapras, thank you for your submission. The issue was labeled "Status: Repro Missing", as you have not provided a way to reproduce the issue quickly. Most problems already solve themselves when isolated, but we would like you to provide us with a reproducible code to make it easier to investigate a possible bug.
