### ISSUE TITLE
Customizing Filter Modes for Individual columns in a DataGrid

### ISSUE THREAD

**Issue by KatarinaPr3** [Megabit/Blazorise#5104]
How can I create a data grid that will generally have the default FilterMode, but for specific columns, use FilterMode.Menu? Each of my columns in the grid needs to have specific filtering, so I can't use just one mode.

**Comment by David-Moreira** [comment]
Good news is that we are improving the `FilterMode.Menu` next version to have contextual filters for numeric and date columns, greater than, greater than or equal, less than, less than or equal.

As for your question, currently you may use the `FilterMenuTemplate` to customize how the menu gets displayed.

![image](https://github.com/Megabit/Blazorise/assets/22283161/3aeba3ff-6770-4f65-acda-62442e59f325)
https://blazorise.com/docs/extensions/datagrid/getting-started

---

For a more custom approach, where you even get to define your specific filtering for each column please read this blog post:
https://blazorise.com/blog/how-to-enhance-the-new-datagrid-menu-filter

**Comment by KatarinaPr3** [comment]
I think none of the options provided are helpful. This is because I have realized that if the DataGrid uses the FilterMode=Default, then it is not possible to set a filter above a specific column that is Mode=Menu. If I am mistaken, please correct me, and it would be great if there is an example of applying such filters. Thank you in advance.

**Comment by David-Moreira** [comment]
Ah so you only want to use **menu** in some columns? Is that it? That's indeed not supported.
But it does seem like it makes sense, to provide the `FilterMode` not only on the `DataGrid` but also per column.
@stsrki agree?

**Comment by KatarinaPr3** [comment]
@David-Moreira Yes, that's right.

**Comment by stsrki** [comment]
Yeah, it makes sense to have it on the column level. If if have any time after we finish remaining 1.4 issue we can look into it.
