### ISSUE TITLE
How to select all by default in DataGrid multi-selection mode

### ISSUE THREAD

**Issue by He-Wu** [Megabit/Blazorise#5107]

**Comment by David-Moreira** [comment]
You can try binding `SelectedRows` to the DataGrid with all the data that you want to start selected. Have you tried that?

**Comment by He-Wu** [comment]
@David-Moreira yes,But it doesn't select all
@bind-SelectedRows="SelectedRows"  and SelectedRows = Data

**Comment by He-Wu** [comment]
![image](https://github.com/Megabit/Blazorise/assets/56440130/05164b3c-2532-4e41-8109-8cddae14e9f9)
![image](https://github.com/Megabit/Blazorise/assets/56440130/c2b4422f-434c-480a-887d-c5ac39873c1b)

**Comment by David-Moreira** [comment]
You are mapping the objects and creating two collections with the same items but **different in memory references**. The object references need to be the same so the Grid can match the selected items.

**Comment by David-Moreira** [comment]
Ok, I'll take a look and let you know then.

**Comment by He-Wu** [comment]
ok thank you

> Ok, I'll take a look and let you know then.

**Comment by He-Wu** [comment]
I executed the datagrid's refresh event after that, sorry
