### ISSUE TITLE
DataGridAggregate Questions

### ISSUE THREAD

**Issue by He-Wu** [Megabit/Blazorise#5112]
**Is your feature request related to a problem? Please describe.**
I need to display total under the selection box, but setting it is useless. abc is not a field where TItem exists. I only need to display the string total.According to the following code, it will not display the total string at the bottom of the checkbox
![image](https://github.com/Megabit/Blazorise/assets/56440130/74142070-4b26-455f-af59-17dc1f3ea81f)
![image](https://github.com/Megabit/Blazorise/assets/56440130/ce543e95-f4b9-4d8d-ab5a-487c3e282424)
![image](https://github.com/Megabit/Blazorise/assets/56440130/fa5ef639-33f2-41af-87f6-495fc1c65251)

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by David-Moreira** [comment]
The `DataGridAggregate` requires `Field` to be the same Field as the `Column` you want to put it under currently. There is currently no way to customize the `DataGridAggregate` under the command and multi select columns.

I believe providing a `CommandColumnTemplate` and `MultiSelectColumnTemplate` under the DataGridAggregate might be appropriate. Would you also agree @stsrki ?

But for now, your best would be to allocate the `Total` string under the `Id` column for example.

**Comment by stsrki** [comment]
At the moment, when we define `DataGridAggregate` with the `Field` name, it automatically know to which Field/Column needs to be placed. Without the `Field` defined, it would be quite problematic to determine where we need to place the `DataGridAggregate` cell. So to overcome that limitation we would most probably have to have multiple `DataGridAggregate`s to be able to place the aggregate cell under the desired column. To me that sounds a bit strange.

**Comment by David-Moreira** [comment]
In this case I'm proposing two new templates for the command and multi select columns. Which is where the user is apparently trying to place the aggregate.

Nothing to do with `DataGridAggregate` and the `Field`. I think that should stay like that for now.

**Comment by stsrki** [comment]
> I believe providing a `CommandColumnTemplate` and `MultiSelectColumnTemplate` under the DataGridAggregate might be appropriate. Would you also agree @stsrki ?

Yeah, but adding it under the DataGridAggregate would not make sense for the reasons I mentioned previously. 

If we go the new template route, then I think adding it under the DataGridColumn(and other types) makes most sense. I would name it something along `AggregateTemplate` which would indicate by the naming where it would be placed. The `AggregateTemplate` would have the highest priority over the current `DataGridAggregate` rendering.

**Comment by David-Moreira** [comment]
OH yes, that's what I meant haha. I didn't explain the api correctly I guess.

Yes, To have the AgreggateTemplate in the CommandColumn and MultiSelectColumn. 

I guess the template is also a nice addition to the column either way, although it can be redudant since the aggregate already has the display template.

**Comment by stsrki** [comment]
@David-Moreira, easy win for the 1.5?

**Comment by David-Moreira** [comment]
kk
