### ISSUE TITLE
Enable Nightly Builds for Current Dev Branch

### ISSUE THREAD

**Issue by paulsterling** [Megabit/Blazorise#5143]
I know that MyGet was removed as a reference location for nightly (preview) builds in June 2023 #4895 since the myget.org site was down. It appears to be back now and is in use by other OSS projects currently. I use Umbraco and they have any active MyGet feed (https://www.myget.org/F/umbracoprereleases/api/v3/index.json).

It'd be great to have a place to grab dev branch builds rather than having to build Blazorise locally and set up the local configuration to support local nuget packages. I think that could help with testing the work in progress since it'd make getting the latest much easier. 

I am currently waiting on some fixes in 1.3.3 #4962 that would be great to test in the same environment where I encountered the issues originally.

Could this be as straightforward as re-enabling the workflow https://github.com/Megabit/Blazorise/blob/master/.github/disabled-workflows/build-nuget.yml ?

Thanks for considering!

**Comment by stsrki** [comment]
It seems the MyGet free plan is now quite limited with only 500MB of available storage. And we already use half of it. In case we would to have nightly builds I think we would need to proceed with higher MyGet plans.

I like the idea of having nightly builds. Will need to see how much work we need to have. And how to version them properly.

@David-Moreira

**Comment by stsrki** [comment]
> I am currently waiting on some fixes in 1.3.3 #4962 that would be great to test in the same environment where I encountered the issues originally.

We're releasing it today as soon as .NET 8 is made public.

**Comment by David-Moreira** [comment]
> It seems the MyGet free plan is now quite limited with only 500MB of available storage. And we already use half of it. In case we would to have nightly builds I think we would need to proceed with higher MyGet plans.
> 
> I like the idea of having nightly builds. Will need to see how much work we need to have. And how to version them properly.
> 
> @David-Moreira

Yea I had already voiced my thoughts on this. I think it's very very useful to have them.
