### ISSUE TITLE
VirtualizeOption not working with fixed height

### ISSUE THREAD

**Issue by VivienMAN** [Megabit/Blazorise#5145]
![image](https://github.com/Megabit/Blazorise/assets/103559756/592da297-05af-49db-b752-9c064b4d7c2b)

https://blazorise.com/docs/extensions/datagrid/binding-data/virtualize

The height is not the same and the scroll is broken.

In my project, i try DataGridHeight  and DataGridMaxHeight but not working.

**Comment by David-Moreira** [comment]
Hello,

As mentioned in the notes,
> Note that this mode requires that all rows have the same height.

If this isn't complied with, the Virtualize feature might not work correctly, as it calculates the number of rows to load ahead based on row height.
In our example, you managed to decrease the width of the Grid such that the rows aren't the same height, you can tackle this issue specifically by applying a definitive row height, using fixed column width, truncanting column text, etc...
**e.g** `RowStyling='(x,y ) => y.Style = "height: 80px;"'`
We can go ahead and update our example, so we showcase the row height definition.

As for `DataGridHeight` and `DataGridMaxHeight`, we'll have to ask for a reproducable. In the example the Grid height is defined as 250px and seems to be working correctly.
