### ISSUE TITLE
[Bug]: Blazorise.Templates : Flag -f=net8.0 not working

### ISSUE THREAD

**Issue by Jenubis78** [Megabit/Blazorise#5147]
### Blazorise Version

1.3.3

### What Blazorise provider are you running on?

None

### Link to minimal reproduction, or a simple code snippet

dotnet new blazorise -n Mikontroller -p Material -ut false -f net8.0

### Steps to reproduce

Type this command with Blazorise.Templates installed

### What is expected?

Create new project with .net8

### What is actually happening?

Error: Invalid option(s):
-f net8.0
   'net8.0' is not a valid value for -f. The possible values are:
      net6.0   - Target net6.0
      net7.0   - Target net7.0

**Comment by David-Moreira** [comment]
This should already be fixed & live for quite some time. Closing issue.
