### ISSUE TITLE
Add more configurability to ColorPicker

### ISSUE THREAD

**Issue by mkontula** [Megabit/Blazorise#5156]
I'm trying to use ColorPicker to choose colors with Hue and Alpha. Pickr has ability to do that, but current implementation falls short in configurability.

Add an option to address this line: https://github.com/Megabit/Blazorise/blob/master/Source/Blazorise/wwwroot/colorPicker.js#L30C24-L30C24 
Aka, add booleans to enable alpha, hue, etc. options.

Thanks for the absolutely brilliant work you've done in this repo.

**Comment by stsrki** [comment]
To clarify. Do you wish to have control over the `hue` option? And also over the `rgba` option?

**Comment by mkontula** [comment]
![image](https://github.com/Megabit/Blazorise/assets/1148526/c79a7a15-8744-43f5-ac46-adff8a5df496)

The thing circled in red. Without it, changing the color is somewhat cumbersome. ColorEdit has it, but then again lacks other features in Picker. Adding control over this via a simple Boolean should be enough? It can be defaulted to false to maintain backwards compatibility.

**Comment by stsrki** [comment]
But, we already show that by default

![image](https://github.com/Megabit/Blazorise/assets/900302/3e2eca77-c38f-4980-b429-f9f01e0ebe0f)

**Comment by stsrki** [comment]
Sorry, I was looking at the wrong input.

**Comment by stsrki** [comment]
#5160

**Comment by mkontula** [comment]
Merci beaucoup! 🥇
