### ISSUE TITLE
[Bug]: Ant Design Bar background does not work on sider bar

### ISSUE THREAD

**Issue by KyleTraynor** [Megabit/Blazorise#5188]
### Blazorise Version

1.4

### What Blazorise provider are you running on?

AntDesign

### Link to minimal reproduction, or a simple code snippet

https://github.com/KyleTraynor/BlazoriseAntBug

### Steps to reproduce

Create a new project in visual studio using Blazorise App (MegaBit). choose Ant Design for the provider.

Add this code to the theme:

```
BarOptions = new ThemeBarOptions
{
    HorizontalHeight = "64px",
    DarkColors = new ThemeBarColorOptions
    {
        BackgroundColor = "#ff0000",
        Color = "#ff0000",
        ItemColorOptions = new ThemeBarItemColorOptions
        {
            ActiveBackgroundColor = "#ff0000",
            ActiveColor = "#ff0000",
            HoverBackgroundColor = "#ff0000",
            HoverColor = "#ff0000",
        }
    },
},
```

### What is expected?

Bar background should be red.

### What is actually happening?

Bar background does not change.

### Any additional comments?

It works with the bootstrap provider, but not with the ant design provider.

**Comment by steal4life** [comment]
Hi @KyleTraynor, now everything should work for you, thanks for your report and feel free to ask if anything is unclear.
