### ISSUE TITLE
[Bug]: content/Blazorise/inputmask.js?v=1.4.0.0 404 Not Found

### ISSUE THREAD

**Issue by realLiangshiwei** [Megabit/Blazorise#5189]
### Blazorise Version

1.4.0

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction, or a simple code snippet
```csharp
<DatePicker TValue="DateTime?" @bind-Date="@value" />
@code {
    DateTime? value;
}
```

### Steps to reproduce

* Create a new Blazor web app(NET 8)
* Install Blazorise according to document: https://blazorise.com/docs/start
* Add a datapicker component https://blazorise.com/docs/components/date-picker

<img width="1278" alt="image" src="https://github.com/Megabit/Blazorise/assets/16813853/bbde721a-a428-48c1-8649-fb5093d439a2">

### What is expected?

Should not be error

### What is actually happening?

GET https://localhost:7231/_content/Blazorise/inputmask.js?v=1.4.0.0 net::ERR_ABORTED 404 (Not Found)

**Comment by David-Moreira** [comment]
Hello @realLiangshiwei did you make sure to enable interactivity?

**Comment by DenisChimbor** [comment]
I also have a similar issue with the DatePicker on v1.4.0 and net7.0 project. And it happens only on deployed app. If I run the app from Visual Studio everything works.

```
Microsoft.AspNetCore.Components.Web.ErrorBoundary[0]
      Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://mysite.com/_content/Blazorise/datePicker.js?v=1.4.0.0
      TypeError: Failed to fetch dynamically imported module: https://mysite.com/_content/Blazorise/datePicker.js?v=1.4.0.0
         at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
         at Blazorise.Modules.BaseJSModule.InvokeSafeVoidAsync(String identifier, Object[] args)
         at Blazorise.Extensions.ModuleExtensions.SafeDestroy(IJSDestroyableModule module, ElementReference elementRef, String elementId)
         at Blazorise.DatePicker`1.<DisposeAsync>d__4[[System.DateTime, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
         at Blazorise.BaseAfterRenderComponent.DisposeAsync()
Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://mysite.com/_content/Blazorise/datePicker.js?v=1.4.0.0
TypeError: Failed to fetch dynamically imported module: https://mysite.com/_content/Blazorise/datePicker.js?v=1.4.0.0
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Blazorise.Modules.BaseJSModule.InvokeSafeVoidAsync(String identifier, Object[] args)
   at Blazorise.Extensions.ModuleExtensions.SafeDestroy(IJSDestroyableModule module, ElementReference elementRef, String elementId)
   at Blazorise.DatePicker`1.<DisposeAsync>d__4[[System.DateTime, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Blazorise.BaseAfterRenderComponent.DisposeAsync()
```

**Comment by David-Moreira** [comment]
@DenisChimbor Please see if this helps you
https://blazorise.com/support/issues/115/blazorise-doesnt-dynamically-resolve-scripts-if-aspnetcore-environment-isnt-set-to-development

**Comment by realLiangshiwei** [comment]
> did you make sure to enable interactivity?

Of course, other components work fine except DatePicker

**Comment by realLiangshiwei** [comment]
I think it's a simple problem, wrong filename

https://github.com/Megabit/Blazorise/blob/7aaede66bec33a248573e09efe5cc324d0a5cd07/Source/Blazorise/wwwroot/datePicker.js#L3

https://github.com/Megabit/Blazorise/blob/master/Source/Blazorise/wwwroot/inputMask.js

* inputmask.js
* inputMask.js

**Comment by David-Moreira** [comment]
I kinda doubt that is the problem. I think the file still gets resolved. WE have apps in 1.4.
Have you tried visiting the url directly with the original path and also with the path that you think is wrong? Is the resource returned?
https://localhost:7231/_content/Blazorise/inputmask.js?v=1.4.0.0
https://localhost:7231/_content/Blazorise/inputMask.js?v=1.4.0.0

**Comment by realLiangshiwei** [comment]
When you use a non-windows system, file name is case-sensitive

> The URLs for content exposed with UseDirectoryBrowser and UseStaticFiles are subject to the case sensitivity and character restrictions of the underlying file system. For example, Windows is case insensitive, but macOS and Linux aren't.

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-8.0#security-considerations-for-static-files

<img width="984" alt="image" src="https://github.com/Megabit/Blazorise/assets/16813853/0d295e5f-24cb-40b5-b555-30ea2b580140">

**Comment by David-Moreira** [comment]
Ah, makes sense, the linux fs is case sensitive indepedent of the browser. Takes for the help troubleshooting it does seem you're right. We'll fix it for next patch. You can try loading the resource manually but I'm not sure it will help.
<script src="_content/Blazorise/inputMask.js?v=1.4.0.0" type="module"></script>

**Comment by stsrki** [comment]
Yeah, thanks for looking into this. It's such a dumb mistake from us. I would never guess it. 😅

**Comment by realLiangshiwei** [comment]
I'd like to ask when will release the patch version?

**Comment by stsrki** [comment]
Possibly by the end of next week.
