### ISSUE TITLE
🔧 1.4 Support Docs

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#5192]
## 1.4.3

- #5280
- #5310
- #5311
- #5288
- #5335
- #5332
- #5339
- #5338

## 1.4.2

- #5221
- #5233
- #5253
- #5251
- #5256
- #5261
- #5268
- #5186
- #5250
- #5208
- #5169

## 1.4.1

- #5173
- #5189
- #5188
- #5217
- #5199
- #5222
- #5202
- #5226

**Comment by JosephFicara** [comment]
Has the 1.4.2 version been released, if not do you have an ETA on when it will be?  I am not seeing it in the nuget feed for upgrading yet.

**Comment by stsrki** [comment]
> Has the 1.4.2 version been released, if not do you have an ETA on when it will be? I am not seeing it in the nuget feed for upgrading yet.

Hello, no, it's not released yet. This ticker is mostly used to keep track of the change logs. We usually release patches every two-or three weeks. Depending on the urgency of the fixed bugs. So I think the next release will be next week.
