### ISSUE TITLE
[Bug]: LineChart Only shows first 10 points on v1.4

### ISSUE THREAD

**Issue by simonvanes** [Megabit/Blazorise#5195]
### Blazorise Version

1.4.0

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction, or a simple code snippet

Example code 

```
await ChartingComponent.Clear();
 
await ChartingComponent.AddLabelsDatasetsAndUpdate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], new LineChartDataset<int>
 {
     Label = StringLocaliser["BookingPerDayChartLabel"],
     Data =  [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
     BackgroundColor = new List<string> { ChartColor.FromRgba(0, 255, 0, 0.2f) },
     BorderColor = new List<string> { ChartColor.FromRgba(0, 255, 0, 0.2f) },
     Fill = true,
     PointRadius = 3,
     SpanGaps=true, 
     CubicInterpolationMode = "monotone",
 });

 await ChartingComponent.Update();
```

### Steps to reproduce

Create a line chart,    add say 15 labels  and 15 data points then display it.  It will only shown 10 points on Blazorise Charts 1.4,  but on 1.3.4 it works fine and shows all points.   (You must clean and rebuild your solution to see it not work in 1.3.4, then not work 1.4)

v1.4 (not showing all points)

<img width="576" alt="image" src="https://github.com/Megabit/Blazorise/assets/51195863/c550d07c-882b-40a9-bdd6-045c64d8cb3f">

v1.3.4  (shows all points)

<img width="569" alt="image" src="https://github.com/Megabit/Blazorise/assets/51195863/6f260e32-ed35-49e4-8360-7d1acab6ba2e">

_It would also be nice if we could add support for v4.0+ Chart JS,  currently Blazorise only works with up to 3.9.1i think_
 

### What is expected?

All the points are shown on the graph

### What is actually happening?

Only the first 10 points are shown on the graph

### What browsers are you seeing the problem on?

Chrome

**Comment by stsrki** [comment]
Hello. Yes, this is by design. We have changed licensing terms in latest 1.4 version. You can read about the changes on https://blazorise.com/news/release-notes/140

Also the limit details can be seen on https://blazorise.com/pricing
