### ISSUE TITLE
[Bug]: Ant Design Datagrid page size selection doesn't show list

### ISSUE THREAD

**Issue by Lasoty** [Megabit/Blazorise#5199]
### Blazorise Version

1.4

### What Blazorise provider are you running on?

AntDesign

### Link to minimal reproduction, or a simple code snippet

Can be reporduced on https://antdesigndemo.blazorise.com/tests/datagrid/aggregates. 

![image](https://github.com/Megabit/Blazorise/assets/23433922/6e82b201-e1df-457a-ae54-2593bd83b355)

### Steps to reproduce

1. Open browser
2. Navigate to https://antdesigndemo.blazorise.com/tests/datagrid/aggregates
3. Try change datagrid page size. 

### What is expected?

List of page sizes is visible.

### What is actually happening?

The page size list is not visible. I can only see the scroll bar.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

**Comment by stsrki** [comment]
I assume the problem might be with the wrong `position: absolute` calculation. 

@steal4life Can you look into it?
