### ISSUE TITLE
[Bug]: Carousel : Back/Next buttons are a bit unresponsive

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#5202]
ok, I'll create a project from scratch and test this. but the problem with the button not responding happens in your demo too.

_Originally posted by @drma-dev in https://github.com/Megabit/Blazorise/issues/5200#issuecomment-1869626843_

**Comment by stsrki** [comment]
@David-Moreira can you look into this? I would like it to be ready for 1.4.1 if possible.

**Comment by David-Moreira** [comment]
I'll try.
