### ISSUE TITLE
[Bug]: Have error "A 'using namespace' directive can only be applied to namespaces; 'Blazorise' is a type not a namespace. " in _Imports.razor

### ISSUE THREAD

**Issue by vsirghii** [Megabit/Blazorise#5209]
### Blazorise Version

1.4.0

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction, or a simple code snippet

I'm using VS 2022 .net core 7 and its Blazor sereverside app template. Following your docs, https://blazorise.com/docs/usage/bootstrap5 , I'm trying to start with Blazorise in the new Blazor app. 
Running the app throws the error:  "A 'using namespace' directive can only be applied to namespaces; 'Blazorise' is a type not a namespace. " in Imports.razor .
VS 2022 doesn't highlight the statement in Import.razor file as an error. The error throws in compile mode only.

In my Blazor app template I have the following **Host.razor** code:
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="~/" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" rel="stylesheet">

    <link href="_content/Blazorise/blazorise.css" rel="stylesheet" />
    <link href="_content/Blazorise.Bootstrap5/blazorise.bootstrap5.css" rel="stylesheet" />
    <component type="typeof(HeadOutlet)" render-mode="ServerPrerendered" />
</head>
<body>
    <div id="app"></div>

    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

    <script src="_framework/blazor.server.js"></script>
</body>
</html>

And the following **MaynLayout**:
@inherits LayoutComponentBase

<PageTitle>Pluralsight blazor server app</PageTitle>

<div class="page">
    <div class="sidebar">
        <NavMenu />
    </div>

    <main>
        <div class="top-row px-4">
            <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
        </div>

        <article class="content px-4">
            @Body
        </article>
    </main>
</div>

And the following in the **Import.razor** file:
@using System.Net.Http
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Components.Authorization
@using Microsoft.AspNetCore.Components.Forms
@using Microsoft.AspNetCore.Components.Routing
@using Microsoft.AspNetCore.Components.Web
@using Microsoft.AspNetCore.Components.Web.Virtualization
@using Microsoft.JSInterop
@using Pluralsight_blazor_server_app
@using Pluralsight_blazor_server_app.Shared

@using Blazorise   !!!! Here is the error place!!!!!

Any ideas what might be wrong here??

Thank you.

### Steps to reproduce

Create a new Blazor app in VS 2022. Then, follow the instructions from https://blazorise.com/docs/usage/bootstrap5 link

### What is expected?

A running app with probably broken layout as no Blazorise layout is used yet

### What is actually happening?

Exception when start compiling the app:  "A 'using namespace' directive can only be applied to namespaces; 'Blazorise' is a type not a namespace. " in _Imports.razor

### What browsers are you seeing the problem on?

Chrome

**Comment by David-Moreira** [comment]
Hello @vsirghii 
Do you have something on your project namespace defined as `Blazorise` that could conflict with our namespace?
i.e
`public class Blazorise {}`

Otherwise I advise you to use our templates which provide a ready to start project and should not have that problem at all.
https://blazorise.com/docs/templates

If you're still having difficulties, we'll need a reproducable of the issue.

**Comment by vsirghii** [comment]
Hi David. Thanks a lot for your response! Yeah, creating a new project from blazorise templates worked perfectly fine, loved the Grid and To-do sample pages.
The only question remains for us. We're heavily using in our current  .net core projects jquery Select2 and Datatable plugins. I can clearly see that Blazorise  DataGrid is a good replacement for datatable. But couldn't find anything in your docs that could serve as Select2 (I mean a Select element with filtering/search capabilities). 
Would you please point us to a direction we should search for the Select2 solution in Blazorise UI? Or would you recommend to use javascript interop and go with the real Select2? Any ideas would be greatly appreciated.
Thank you,

**Comment by David-Moreira** [comment]
Hello,
Great to hear that.

The closest option to the `Select2` is our `Autocomplete`. 
In order for it to open right away, like how a select would work, you can set the `MinLength` to 0.

**Comment by vsirghii** [comment]
Thank you David!
