### ISSUE TITLE
[Bug]: DataGrid Refresh doesnt work

### ISSUE THREAD

**Issue by JanVargovsky** [Megabit/Blazorise#5213]
### Blazorise Version

1.3.3, 1.4.0, dev

### What Blazorise provider are you running on?

None

### Link to minimal reproduction, or a simple code snippet

https://github.com/JanVargovsky/Blazorise/commit/6f1d0b283f74610bc78d602256031706578f28de

### Steps to reproduce

- Remove item from a bound collection that holds data of a DataGrid
  - e.g. via button click like in the repro
- call `DataGrid.Refresh()`

### What is expected?

DataGrid should be re-rendered and removed items should not be visible

### What is actually happening?

Nothing happens, removed items are still visible

### Any additional comments?

it used to work even without the Reload, I see there was a change in the 1.3.0 release and we are expected to call [Refresh](https://blazorise.com/news/release-notes/130#:~:text=Invoke-,gridRef.Reload()%3B,-when%20you%27re%20done) ourselves but it doesn't work.

**Comment by David-Moreira** [comment]
Hello @JanVargovsky 
Could I ask why you keep stating `Refresh`? The method is `Reload` not `Refresh`.

`Refresh` calls `StateHasChanged()` internally to make sure internal components are updated.
`Reload` makes sure to reload the data.

If you are mutating the collection in place using `.Add` `.Remove`, etc we also recommend the Observable collection.

**Comment by JanVargovsky** [comment]
Hi @David-Moreira,

Oh, what a silly mistake. I don't want to reload the data (query the DB in our case), just remove the item from the current page. Is it possible without the observable collection?

**Comment by David-Moreira** [comment]
**Without using the observable collection,**

If you are using an in memory collection it should be ok to call `Reload` as you've already loaded the data from your **DB**? It will just make sure to re-bind `Data`, reapply fitlers, sorts, etc...

If you are using `ReadData`, and do not want to trigger `Reload` which will trigger the `ReadData` then you can:
- Make sure that the `Data` collection has a new bound collection so the `DataGrid` detects a different reference and updates automatically. You can do so by using `.ToList()` for instance or just straight up creating a new collection reference.
- Try our `Delete` method, this should also make sure to remove the item and keep the collection updated. 
  - This requires that a derived type of `ICollection` is bound (like a List).. 
  - This requires that `UseInternalEditing` is set to true
![image](https://github.com/Megabit/Blazorise/assets/22283161/65622620-4fcf-4325-8a52-dd7c39dedfeb)

**Comment by JanVargovsky** [comment]
I'm using the `ReadData`. I tried binding it to new Data but it didn't work for some reason - I had a combination of all things that should work but they didn't
```csharp
    private async Task OnWorkflowsDismissed(ICollection<WorkflowItemDto> dismissedItems)
    {
        dismissedItems.ForEach(e => _workflowItems.Remove(e));
        if (_workflowItems.Count == 0)
            await ReloadItems();
        else
        {
            _workflowItems = _workflowItems.ToList();
            await _datagrid.Refresh();
            await InvokeAsync(StateHasChanged);
        }
    }
```

It didn't work on Friday but works today (as is and also just the re-assign the `_workflowItems`).

the `Delete` works too but as I'm looking at what is being done under the hood it might not be ideal for deleting multiple items but since we have another solution I'm it, thanks for the help, not sure what was happening on my PC during Friday 🤷‍♀️
