### ISSUE TITLE
Built-in Bootstrap 5 XXL breakpoint support

### ISSUE THREAD

**Issue by XanderStoffels** [Megabit/Blazorise#5215]
**Is your feature request related to a problem? Please describe.**
I'm trying to use Bootstrap's 5 `xxl` breakpoint using Blazorise, but it's not available.
Blazorise breakpoints go up to `FullHD`, which corresponds to Bootstrap's `xl` breakpoint.

**Describe the solution you'd like**
A Blazorise breakpoint that goes up to `≥1400px`.

**Comment by stsrki** [comment]
I'm already thinking about this feature as I'm working on new Fluent UI provider ATM, which also have higher breakpoint. In theory, it shouldn't be too problematic. But some providers like Bootstrap 4 doesn't have `xxl` size so we would have to either:

1. implement all the missing `xxl` for every utility, for all CSS providers
2. implement only on CSS providers that support it

**Comment by stsrki** [comment]
I'm open to suggestions to name the new Breakpoint.

Proposals:

- Full2K
- 2K
