### ISSUE TITLE
[Bug]: I want to drag the column width, but when the dragged column becomes wider, other columns will become narrower, and no scroll bar will appear in the horizontal direction.

### ISSUE THREAD

**Issue by He-Wu** [Megabit/Blazorise#5216]
### Blazorise Version

1.2.0

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction, or a simple code snippet

https://v12x.blazorise.com/docs/extensions/datagrid/features/resizing

### Steps to reproduce

![image](https://github.com/Megabit/Blazorise/assets/56440130/d67a97d3-f294-4b40-b3af-0061f1c3f091)
I want to drag the column width, but when the dragged column becomes wider, other columns will become narrower, and no scroll bar will appear in the horizontal direction.

### What is expected?

Scroll bars appear horizontally and other column widths remain unchanged

### What is actually happening?

I want to drag the column width, but when the dragged column becomes wider, other columns will become narrower, and no scroll bar will appear in the horizontal direction.

### What browsers are you seeing the problem on?

Chrome

**Comment by David-Moreira** [comment]
Hello @He-Wu Have you tried setting the `DataGrid` to `Response`?

**Comment by He-Wu** [comment]
> Hello @He-Wu Have you tried setting the `DataGrid` to `Response`?

Hi,yes I've tried setting Response to true and false with the same result

**Comment by David-Moreira** [comment]
Correction, I meant `Responsive` 
Ok, we need to take a look whether we can make it so you are more freely able to resize the `DataGrid` columns when it's set to `Responsive`, since the `DataGrid` overflows horizontally.

**Comment by He-Wu** [comment]
> Correction, I meant `Responsive` Ok, we need to take a look whether we can make it so you are more freely able to resize the `DataGrid` columns when it's set to `Responsive`, since the `DataGrid` overflows horizontally.

Ok,thanks

**Comment by David-Moreira** [comment]
> Did you ever have a look at this? We're running into the same problem right now. Are there maybe any possible workarounds that we could take?

Unfortunately not.
The resizing feature is handled by js. You'd probably need to rewrite with your own version and override our own to make it work like you want, But I don't think it's an easy feat.

**Comment by stsrki** [comment]
This might be fixes with [#5908](https://github.com/Megabit/Blazorise/pull/5908)
