### ISSUE TITLE
[Bug]: Blazorise TreeView control shows duplicate entries

### ISSUE THREAD

**Issue by JosephFicara** [Megabit/Blazorise#5221]
### Blazorise Version

1.3.3, 1.3.4 and 1.4

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction, or a simple code snippet

![BlazorizeControlWithProgressAndRightClickMenu-Rendered](https://github.com/Megabit/Blazorise/assets/5749053/5ad55d3a-e03f-4463-b536-d65fb96ab06d)

### Steps to reproduce

1. To enable dynamic loading HasChildNodes="@(item => true)"
2. Utilize the GetChildNodesAsync="@(async item => await GetChildNodes(item))" to populate the child nodes
3. Add a child node to a tree node that currently has no child nodes
4. Observe that the UI shows duplicate child nodes
5. Collapse and reopen the child node
6. Observe that the single child node is properly reflected

### What is expected?

Only  the single node that was added should be shown. 

### What is actually happening?

Duplicate child nodes are shown

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Any additional comments?

This only happens when a parent node has no children.  If the parent node initially has children, then duplicate nodes are not shown
The backing data store does not get duplicate nodes, its only something that is happening in the tree.  When you collapse and expand the parent node the proper children are represented.

**Comment by David-Moreira** [comment]
@JosephFicara I am sorry but please provide a repository with the reproduceable, there might be very specific things that you are doing in the code that we can't tell... or have to be guessing in order to try and reproduce ourselves.

**Comment by JosephFicara** [comment]
Hi @David-Moreira,

I added a simplified example in this repo: https://github.com/JosephFicara/blazorisebugs.git

You will find it in the TreeControlTestAppBlazoirizeSolution 

Let me know if you have any questions.  

Thank you for your help and support.

**Comment by David-Moreira** [comment]
Hello,
It's indeed a bug where our internals are causing the duplication with the usage of `ObservableCollection`.

We'll be fixing the issue as soon as possible.

**PS:** Really appreciated for the good repro, it really helps us alot.
