### ISSUE TITLE
[Bug]: Bulma Carousel Slide Transition Animation is broken

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#5223]
### Blazorise Version

1.4.0

### What Blazorise provider are you running on?

None

### Link to minimal reproduction, or a simple code snippet

https://bulmademo.blazorise.com/tests/carousel

### Steps to reproduce

Visit the carousel page. 
Select Previous or Next Slide

### What is expected?

.

### What is actually happening?

 No animation when slides transition.

**Comment by David-Moreira** [comment]
@stsrki Can you confirm whether this is indeed a bug? I'm guessing we've had animation in bulma in the past? Or was it always like this?

**Comment by stsrki** [comment]
I can see the transition animation in Bulma CSS, so I would assume it worked in the past.

**Comment by David-Moreira** [comment]
You said something about next bulma version. So let's leave it for now?

**Comment by stsrki** [comment]
Closing now as we plan to update to Bulma 1.0.
