### ISSUE TITLE
[Bug]: AutoComplete excepts when SelectedTexts is null or not bound and Backspace is pressed in an empty AutoComplete

### ISSUE THREAD

**Issue by oaldrian** [Megabit/Blazorise#5233]
### Blazorise Version

1.3.4, 1.4.0 (and others maybe)

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction, or a simple code snippet

- reproduction in 1.3.4: https://github.com/oaldrian/BlazoriseReproductions/tree/Autocomplete-SelectedTexts-Exception-1.3.4
- reproduction in 1.4.0: https://github.com/oaldrian/BlazoriseReproductions/tree/Autocomplete-SelectedTexts-Exception-1.4.0

### Steps to reproduce

1. Start reproduction site
2. Focus one of the AutoCompletes
3. Hit the "Backspace" key
4. Exception happens

### What is expected?

Exception does not happen.

### What is actually happening?

Exception happens.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Firefox

### Any additional comments?

it excepts in this line if SelectedTexts is not bound or bound but not initialized.
https://github.com/Megabit/Blazorise/blob/e608cac341508e3825b143c408e8fe84eb502ab9/Source/Extensions/Blazorise.Components/Autocomplete.razor.cs#L348C11-L348C11

likely due SelectedTexts only being set to something if it is null in `AddMultipleText`
https://github.com/Megabit/Blazorise/blob/e608cac341508e3825b143c408e8fe84eb502ab9/Source/Extensions/Blazorise.Components/Autocomplete.razor.cs#L699C9-L699C27

The same null check / initializer should solve the problem. Maybe check other occurences of SelectedTexts, if they need the same check as well.

As a workaround the user can bind SelectedTexts and initialize it.

**Comment by David-Moreira** [comment]
Hello,
Indeed a bug, we'll fix it.
