### ISSUE TITLE
[Bug]: Manual Event handler in Select control not working

### ISSUE THREAD

**Issue by zawarq** [Megabit/Blazorise#5237]
### Blazorise Version

1.4.1

### What Blazorise provider are you running on?

None

### Link to minimal reproduction, or a simple code snippet

[Select - Blazorise Docs](https://blazorise.com/docs/components/select) if you try changing the selection under the "Manual Event binding" example, there is no output on console. Also, my own select components aren't firing the specified event handler.

If you need more information then I can provide my code. But I think the above link is a good reproduction of the issue.

### Steps to reproduce

Change the Select option in the Select docs for the Manual event binding example

### What is expected?

Output on console

### What is actually happening?

No output on console

### What browsers are you seeing the problem on?

Chrome

### Any additional comments?

Chrome version 120.0.6099.217

**Comment by David-Moreira** [comment]
Hello @zawarq please provide a repro as our Blazorise Docs web application is in **Blazor.Server** which means you cannot see what's written into the Console . From quickly running the app locally, it is working as expected:
![image](https://github.com/Megabit/Blazorise/assets/22283161/8e8180de-c361-40e3-b5d7-80a2ffca4806)
