### ISSUE TITLE
Edit/delete in RowOverlayTemplate

### ISSUE THREAD

**Issue by leetheman** [Megabit/Blazorise#5242]
Hi there,
I love the RowOverlayTemplate, looks really slick.

I can get it working with a delete button, but wondering if there's a way I can fire off the Edit Command from a button.  I can only access the context.Item from the template, however.

Any ideas?

**Comment by David-Moreira** [comment]
Hello @leetheman 
You can check the public api for DataGrid in this page.
https://blazorise.com/docs/extensions/datagrid/getting-started

At the bottom there's a section for methods. You will find an `Edit` method. So basically you should be able to bind your button to a method that eventually calls the following `await _dataGridRef.Edit(myItem);`

**Comment by leetheman** [comment]
Perfect, this works flawlessly
