### ISSUE TITLE
[2.0] Strip all logic that uses Collapse within the Accordion

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#5248]
## Reason

Using the Collapse within accordion is leaking too much of logic between components that are not that directly connected. Since we have added dedicated AccordionItem, AccordionHeader, and AccordionBody there is no need for using Collapse in the Accordion anymore.

**Comment by tesar-tech** [comment]
So this means removing the `Collapse` component from the codebase entirely, right?

It seems there is no other usage for it apart from being part of the `Accordion`, which will no longer be the case in 2.0.

Or what's the reason for keeping `Collapse` component?

**Comment by stsrki** [comment]
We want to leave Collapse component.It still has it's use cases. 

But any usage WITHIN the accordion needs to be removed.
