### ISSUE TITLE
[Bug]: DataGrid Conflicting behaviour between RowSelectable & DetailRowTrigger

### ISSUE THREAD

**Issue by rbillott** [Megabit/Blazorise#5251]
### Blazorise Version

1.3

### What Blazorise provider are you running on?

Bootstrap4

### Link to minimal reproduction, or a simple code snippet

n/a 

### Steps to reproduce

I would like to have grid with both of below features 
- Multi Row selections  
- Row detail to display a break done of information 

I have used below code which is more or less coming from Blazorise doc samples.  
```
    <DataGrid 
              SelectionMode="DataGridSelectionMode.Multiple" SelectedRows="@SelectedRows"
              RowSelectable="RowSelectableHandler"
              DetailRowTrigger="@(GroupDetailRowTrigger)"
              SelectedRowsChanged="@(async (_)=>await OnSelectedRowChanged())"
              ...
         <DataGridColumns>
            <DataGridMultiSelectColumn TItem="PositionAllocationViewModel" Width="30px"></DataGridMultiSelectColumn>
            ...


private bool RowSelectableHandler(RowSelectableEventArgs<MyViewModel> rowSelectableEventArgs)
{
    return rowSelectableEventArgs.SelectReason is not DataGridSelectReason.RowClick;
}

private bool GroupDetailRowTrigger(DetailRowTriggerEventArgs<MyViewModel> e)
{
    // Not being called 
    return SelectedPositions.Contains(e.Item);
}
```

### What is expected?

I would like 
- to change the selection only with click on  DataGridMultiSelectColumn  
- to enable/disable DetailRow grid when clicking on any other columns 
And I need those 2 features to run independently from each other as I may want to see detail of an un-selected Row  and vice&versa 

### What is actually happening?

The Selection is actually working as expected, but it somehow prevent the DetailRow to work; The DetailRowTrigger callback is actually not getting called. 
If I remove `RowSelectable` callback, then DetailRow  works fine, but it get coupled with the selection which is kinda weird and cumbersome behaviour.  
 

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by David-Moreira** [comment]
Hello @rbillott 
A fix will be deployed that fixes the following behaviour:

- If `RowSelectable` evalautes to false, then `DetailRowTrigger` will still be evaluated upon row click.

You can't really tell in the `DetailRowTrigger` delegate whether the click was from a regular row click or multiselectclick.
For now, if you need this information you could do something like this:

```
    private bool RowSelectableHandler( RowSelectableEventArgs<PositionAllocationViewModel> rowSelectableEventArgs )
    {
        Console.WriteLine( "RowSelectableHandler" );
        Console.WriteLine( rowSelectableEventArgs.SelectReason );

        wasMultiSelectClick = rowSelectableEventArgs.SelectReason is DataGridSelectReason.MultiSelectClick;

        return rowSelectableEventArgs.SelectReason is not DataGridSelectReason.RowClick;
    }
    private bool wasMultiSelectClick = false;

    private bool GroupDetailRowTrigger( DetailRowTriggerEventArgs<PositionAllocationViewModel> e )
    {
        Console.WriteLine( "GroupDetailRowTrigger" );

        if ( wasMultiSelectClick )
        {
            Console.WriteLine( "GroupDetailRowTrigger : MultiSelect!" );

        }
        wasMultiSelectClick = false;
        return SelectedPositions.Contains( e.Item );
    }
```
