### ISSUE TITLE
DataGrid save on Enter in pop-up mode

### ISSUE THREAD

**Issue by leetheman** [Megabit/Blazorise#5258]
Hi there, is there a way to get the DataGrid to save and close the pop-up when the user presses enter?

escape works perfectly fine as a cancel command.

**Comment by stsrki** [comment]
I think you should be able to do it with the Button inside of the Form component.

Check the **Submit button** on https://blazorise.com/docs/components/button

**Comment by leetheman** [comment]
It does but then it bypasses validation and nothing is inserted into the database.   

I can knock up a repro later if needed?
