### ISSUE TITLE
Checkboxes for SelectList multiple mode

### ISSUE THREAD

**Issue by leetheman** [Megabit/Blazorise#5259]
Hi , there there a way to get checkboxes for the mutilpe mode of SelectList

Reason is:

If multiple items are selected, often a user will click on another one to "add" it to the list, but instead it will reset the entire selection and only select that single one.

Would be great if we could preserve it without having to hold down CTRL all the time?

Cheers

Lee

**Comment by David-Moreira** [comment]
Hello @leetheman 
The `DropdownList` has Checkbox support. That might be a decent alternative for now.
https://blazorise.com/docs/extensions/dropdownlist

I don't think we'll implement checkbox support in `SelectList` as we make use of the standard html select input which has no support for it. 
@stsrki Just to confirm, Is checkbox support viable in `SelectList`?
