### ISSUE TITLE
Improved filtering for DataGridCheckColumn

### ISSUE THREAD

**Issue by mtbayley** [Megabit/Blazorise#5262]
When the DataGrid column is a DataGridCheckColumn, only DataGridColumnFilterMethod.Equals makes sense

Additionally, I think it would be nice to select from true/false instead of typing "true" or "false" (many of our users won't know to do this).

I realize you could likely achieve this with FilterMenuTemplate, but I'm hoping this can be a default.

![image](https://github.com/Megabit/Blazorise/assets/34929316/cdb333da-41dd-4c71-a95d-0015642f1734)

**Comment by David-Moreira** [comment]
I'm closing this issue. And aggregating the changes in #5263 as they will be implemented as part of the same PR.
