### ISSUE TITLE
DataGrid : Improve filtering for Column specialized inputs, numeric, dates, boolean, etc... 

### ISSUE THREAD

**Issue by mtbayley** [Megabit/Blazorise#5263]
I think it would be nice to select from a date picker instead of typing the date as a filter.

Additionally, I think a additional mode DataGridColumnFilterMethod.Between would be nice to specify the start and end date. This could also apply to DataGridNumericColumn

I realize you could likely achieve this with FilterMenuTemplate, but I'm hoping this can be a default.

![image](https://github.com/Megabit/Blazorise/assets/34929316/e84e1da6-18dd-4384-b3fd-44fa3a6668bd)

---

**From #5262**

When the DataGrid column is a DataGridCheckColumn, only DataGridColumnFilterMethod.Equals makes sense

Additionally, I think it would be nice to select from true/false instead of typing "true" or "false" (many of our users won't know to do this).

I realize you could likely achieve this with FilterMenuTemplate, but I'm hoping this can be a default.

![image](https://github.com/Megabit/Blazorise/assets/34929316/cdb333da-41dd-4c71-a95d-0015642f1734)

**Comment by David-Moreira** [comment]
We're working on introducing the missing contextual components, date and check.
However your other suggestion for : 
`"Additionally, I think a additional mode DataGridColumnFilterMethod.Between would be nice to specify the start and end date. This could also apply to DataGridNumericColumn"`
requires planning as it involves: 
- Ranges having two filters values (that need to be propagated across the DataGrid and ReadData mode)
- introducing a new `DataGridFilterMethod` that again involves handling more then 1 value at a time.

**Comment by David-Moreira** [comment]
> I realize you could likely achieve this with FilterMenuTemplate, but I'm hoping this can be a default.

**PS:** Regarding this, you could probably set the UI up, but I don't think the DataGrid would support this filtering as it needs two values. You would need to do a `CustomFilter` or something.
