### ISSUE TITLE
[Bug]: video component source change hls media can not play

### ISSUE THREAD

**Issue by mrsleepman** [Megabit/Blazorise#5264]
### Blazorise Version

1.4.1

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction, or a simple code snippet

    
    @using Blazorise.Video

    @if (IsValidUrl(Url))
    {
        <Video @ref="@videoRef"
            Source="@Url"
            CurrentTime="@currentTime"
            DefaultQuality="1080"
            Ended="Ended"
            StreamingLibrary="StreamingLibrary.Hls"
            Ratio="16:9"
            AutomaticallyHideControls="true" />
    }
    else
    {
    }

    @code {

        [Parameter]
        public string Url { get; set; }

        [Parameter]
        public Func<Task> Ended { get; set; }

        Video videoRef;
        double currentTime = 0;

        private VideoSource videoSource;

        private bool IsValidUrl(string url)
        {
            return Uri.TryCreate(url, UriKind.Absolute, out var uriResult)
                && (uriResult.Scheme == Uri.UriSchemeHttp || uriResult.Scheme ==     Uri.UriSchemeHttps);
        }

        protected override async Task OnInitializedAsync()
        {
            Console.WriteLine(Environment.NewLine + $"OnInitializedAsync SystemPlayer");

        }
        protected override async Task OnParametersSetAsync()
        {
            Console.WriteLine(Environment.NewLine + $"OnParametersSetAsync SystemPlayer");
        }

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            Console.WriteLine(Environment.NewLine + $"OnAfterRenderAsync SystemPlayer");
            if (videoRef != null)
            {
                await videoRef.Play();
            }
        }
    }

### Steps to reproduce

Use a page to reference this component, and set the URL parameters of the component. After successfully playing the current URL, use a button to change the URL of the component. The video URL does seem to be switched successfully in the HTML Source, but it cannot be played, and the video is not even displayed duration.

It works normally when the video source is mp4. However, HLS does not work properly and cannot be switched and played.

[https://stackoverflow.com/questions/77874493](https://stackoverflow.com/questions/77874493)

### What is expected?

Switch the HLS video source normally and play it

### What is actually happening?

Unable to switch HLS video source and play

### What browsers are you seeing the problem on?

Chrome

**Comment by mrsleepman** [comment]
I tried this code, changed the playback source, and it works fine.

    document.addEventListener('DOMContentLoaded', () => {
    const sources = [
        'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8',
        'https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/hls/BigBuckBunny.m3u8'
    ];
    let currentSourceIndex = 0;
    const video = document.querySelector('video');

    const player = new Plyr(video, {captions: {active: true, update: true, language: 'en'}});

    function loadSource() {
        if (!Hls.isSupported()) {
            video.src = sources[currentSourceIndex];
        } else {
            const hls = new Hls();
            hls.loadSource(sources[currentSourceIndex]);
            hls.attachMedia(video);
            window.hls = hls;
        }
    }

    loadSource();

    document.querySelector('#switch-source').addEventListener('click', () => {
        currentSourceIndex = (currentSourceIndex + 1) % sources.length;
        loadSource();
    });

    window.player = player;
    });

So I tried the same code  `instance.hls = createHls(element, sourceUrl, null);`

![image_2024-02-06_15-59-50](https://github.com/Megabit/Blazorise/assets/146803274/e05af1b3-e1d0-4130-83a9-530d8a2a1d7f)

However, the expected effect was not achieved, and the playback source could not be changed for playback. In fact, html rendering did not work properly.

![image_2024-02-06_16-02-19](https://github.com/Megabit/Blazorise/assets/146803274/28717513-3649-4874-835f-f642cbaf1af7)


So ultimately my temporary solution was to always re-render the component for an HLS type of playback source. That worked fine.

![image_2024-02-06_16-00-53](https://github.com/Megabit/Blazorise/assets/146803274/0d1dbbcd-f3d0-41b1-b82b-957a025e58cc)

Due to my own technical limitations, I did not conduct more in-depth debugging. I hope this preliminary debugging information is helpful.

**Comment by stsrki** [comment]
Thank you for the extra information. We will hopefully start working on it soon.
