### ISSUE TITLE
[Bug]: Error when using Blazorise.Tests.bUnit and FluentValidationHandler

### ISSUE THREAD

**Issue by stiankroknes** [Megabit/Blazorise#5284]
### Blazorise Version

1.4.2

### What Blazorise provider are you running on?

Bootstrap4, NA.

### Link to minimal reproduction, or a simple code snippet

-

### Steps to reproduce

Using the FluentValidationHandler for validating form.

### What is expected?

Tests should continue to work.

### What is actually happening?

When migrating working test project to use Blazorise.Tests.bUnit instead of manual setup i get error:

```
Message: 
System.InvalidOperationException : Cannot resolve scoped service 'Blazorise.FluentValidation.FluentValidationHandler' from root provider.

  Stack Trace: 
CallSiteValidator.ValidateResolution(ServiceCallSite callSite, IServiceScope scope, IServiceScope rootScope)
ServiceProvider.OnResolve(ServiceCallSite callSite, IServiceScope scope)
ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
ServiceProviderEngineScope.GetService(Type serviceType)
ValidationHandlerFactory.CreateImpl(Type handlerType)
ValidationHandlerFactory.<Create>b__3_0(Type key)
ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
ValidationHandlerFactory.Create(Type handlerType)
Validation.GetValidationHandler()
Validation.ValidateAsync(Object newValidationValue)
Validation.InitializeInput(IValidationInput inputComponent)
BaseInputComponent`1.InitializeValidation()
DatePicker`1.SetParametersAsync(ParameterView parameters)
```

### Any additional comments?

Could be because the new AddBlazoriseTests() extension register some key services as singleton instead of scoped as the main library does. Did look in the solution to add a testcase but did not find a obvious place for Blazorise.FluentValidation-tests, would be happy to contribute.

```
services.AddSingleton<IEditContextValidator>( sp => new EditContextValidator( new ValidationMessageLocalizerAttributeFinder(), sp ) );
services.AddSingleton<IValidationHandlerFactory, ValidationHandlerFactory>();
services.AddSingleton<ValidatorValidationHandler>();
services.AddSingleton<PatternValidationHandler>();
services.AddSingleton<DataAnnotationValidationHandler>();
```

The extension Blazorise.FluentValidation register the handler as scoped and the ValidationHandlerFactory (singleton) can not resolve scoped. I could omit the extension for registration in tests but..
```
public static IServiceCollection AddBlazoriseFluentValidation( this IServiceCollection services )
{
    services.AddScoped<FluentValidationHandler>();

    return services;
}
```

**Comment by David-Moreira** [comment]
Hello @stiankroknes 
The `Blazorise.FluentValidation` is an extension and as such it's not supported by the helper package as it has no knowledge of the concrete type we use for fluent validation. 
It's fine that you register with the additional `AddBlazoriseFluentValidation` as we do not need to mock out anything for you.

I.E `.AddBlazoriseTests().AddBlazoriseFluentValidation();`

**Comment by stiankroknes** [comment]
The issue is that the helper `AddBlazoriseTests()` adds:
```
services.AddSingleton<IValidationHandlerFactory, ValidationHandlerFactory>();
```
and some other services as `singleton`. But the `Config.cs` in Blazorise register these with `scoped` lifetime:
```
 //https://github.com/Megabit/Blazorise/blob/master/Source/Blazorise/Config.cs
    foreach ( var mapping in LocalizationMap
                     .Concat( ValidationMap )
                     .Concat( ServiceMap )
                     .Concat( JSModuleMap ) )
        {
            serviceCollection.AddScoped( mapping.Key, mapping.Value );
        }

    public static IDictionary<Type, Type> ValidationMap => new Dictionary<Type, Type>
    {
        { typeof( IEditContextValidator ), typeof( EditContextValidator ) },
        { typeof( IValidationHandlerFactory ), typeof( ValidationHandlerFactory ) },
        { typeof( ValidatorValidationHandler ), typeof( ValidatorValidationHandler ) },
        { typeof( PatternValidationHandler ), typeof( PatternValidationHandler ) },
        { typeof( DataAnnotationValidationHandler ), typeof( DataAnnotationValidationHandler ) },
    };
```
In my production code I register:
```
services.AddBlazorise(..)
    .AddBootstrap..
   .AddBlazoriseFluentValidation()
```
The `AddBlazoriseFluentValidation` registers:
```
services.AddScoped<FluentValidationHandler>();
```
This works fine in my application. But when I try to utilize the `AddBlazoriseTests()` in my tests this will not work since the `IValidationHandlerFactory` is registered as `singleton`. In a view with validation using FluentValidation, the `singleton` factory will then try to resolve the `scoped` `FluentValidationHandler` resulting in the exception can not resolve scoped from root scope. 

If the `AddBlazoriseTests()` registered the mentioned services as `scoped` it would work just fine. Because of this I can not utilize the test helper. Hope this help describe the issue.
