### ISSUE TITLE
Use latest C# language version

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#5307]
Need to update all. 

`<LangVersion>10.0</LangVersion>
`
into

`<LangVersion>12.0</LangVersion>`

**Comment by David-Moreira** [comment]
Why not remove the tag? Which should use latest always?

**Comment by stsrki** [comment]
Hmm, it might be harder than I thought

![image](https://github.com/Megabit/Blazorise/assets/900302/80792961-a5f0-4623-b5ae-ca6e4179bfd6)

**Comment by David-Moreira** [comment]
You can still remove the tag, and it'll use the latest for any given version will it not? If you try to compile with an unsupported c# feature it will throw?

**Comment by stsrki** [comment]
Moving to 2.0. 

A quick test resulted in this error

![image](https://github.com/Megabit/Blazorise/assets/900302/ced115e5-b054-4c0c-9bc3-9c138eebaa60)

**Comment by stsrki** [comment]
We have already used C# 11.0 as the newest version without breaking anything. Since in 2.0 we plan to remove some older .NET frameworks at that time we will also move to newer C# version.

Closing now.
