### ISSUE TITLE
[Bug]: DataGrid When using ReadData, click the header to sort or click the button of the paging component, the checkbox of DataGridMultiSelectColumn cannot remain selected.

### ISSUE THREAD

**Issue by mrsleepman** [Megabit/Blazorise#5320]
### Blazorise Version

1.4.1

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction, or a simple code snippet

I tested it in demo.

Blazorise.Demo.Pages.Tests.DataGrid.SelectionMultiplePage.razor

```
  <DataGrid TItem="Employee"
            Data="inMemoryData"
            ReadData="OnDataGridReadAsync"
            SelectionMode="DataGridSelectionMode.Multiple"
            @bind-SelectedRows="selectedEmployees"
            Responsive
            ShowPager
            ShowPageSizes>
                          
                          
    private async Task OnDataGridReadAsync()
    {
        Console.WriteLine("OnDataGridReadAsync");
        inMemoryData = (await EmployeeData.GetDataAsync().ConfigureAwait(false)).Take(10);
        await base.OnInitializedAsync();
    }
```

### Steps to reproduce

When using ReadData, click the header to sort or click the button of the paging component, the checkbox of DataGridMultiSelectColumn cannot remain selected.

### What is expected?

Checkbox remains selected when changing sorting or changing paging

### What is actually happening?

The checkbox loses its selected status when changing the sorting or changing the paging.

### What browsers are you seeing the problem on?

Chrome

**Comment by mrsleepman** [comment]
Yes, I get your point. When the data changes, the object reference should also change accordingly. However, I tried the following code and it didn’t work as expected. The checkbox just flashes and disappears.

I think it would be beneficial to add a setting that allows us to bind the checkbox to a specific field (like the primary key ID), instead of relying on the object reference.

    <DataGrid TItem="NodeInfoDto"
              Data="Entities"
              ReadData="OnDataGridReadAsync"
              TotalItems="TotalCount"
              PageSize="10000"
              SelectionMode="DataGridSelectionMode.Multiple"
              SelectedRowsChanged="OnSelectedRowsChanged"
              SelectedRows="NodeInfos"
              SortChanged="OnSortChanged"
              Responsive>

    private async Task OnSortChanged()
    {
        NodeInfos = new List<NodeInfoDto>();
        foreach (var item in Entities)
        {
            if (NodeInfoIds.Contains(item.Id))
            {
                NodeInfos.Add(item);
                Console.WriteLine("item.Id " + item.Id);
                // await Task.Delay(200);
            }
        }
    }


https://github.com/Megabit/Blazorise/assets/146803274/3e180677-cf22-47ad-8098-d63d9a0bbe7a

**Comment by David-Moreira** [comment]
Hello @mrsleepman 
Please try the following : 
```
    private async Task OnDataGridReadAsync()
    {
        Console.WriteLine( "OnDataGridReadAsync" );

        inMemoryData = ( await EmployeeData.GetDataAsync().ConfigureAwait( false ) ).Take( 10 );
        if ( !selectedEmployees.IsNullOrEmpty() )
            selectedEmployees = inMemoryData.Where( x => selectedEmployees.Any( selected => selected.Id == x.Id ) ).ToList();
    }
```

This should work by rebinding the `SelectedEmployees` to the new references.

The suggested feature seems a nice to have, where you provide a key of some sorts to the DataGrid and it is able to keep selection based on that same key instead of by reference. Please open a feature request if you're interested in the feature.

**Comment by mrsleepman** [comment]
@David-Moreira 
I tried your code and it works normally. But there is still a problem in the case of paging. I have tried many methods, and this is my current code, which basically works normally in the case of pagination.
But it's quite confusing. If there are no other proposals for this issue, I think can try to bind the selection based on the key. I will open a feature and provide as much help as I can.

    
    <DataGrid TItem="NodeInfoDto"
              Data="NodeInfoList"
              ReadData="OnDataGridReadAsync"
              TotalItems="TotalCount"
              PageSize="PageSize"
              CurrentPage="CurrentPage"
              SelectionMode="DataGridSelectionMode.Multiple"
              SelectedRowsChanged="OnSelectedRowsChanged"
              SelectedRows="NodeInfos"
              ShowPager
              Responsive>
        <DataGridMultiSelectColumn Width="30px"></DataGridMultiSelectColumn>
        <DataGridColumn TItem="NodeInfoDto"
                        VerticalAlignment="VerticalAlignment.Middle"
                        Field="@nameof(NodeInfoDto.NodeName)"
                        Caption="@L["NodeName"]"></DataGridColumn>
    </DataGrid>
    
    @code {
    
        [Parameter]
        public EventCallback<List<long>> OnSelectedRowsChangedEvent { get; set; }
    
        [Parameter]
        public List<long> NodeInfoIds { get; set; } = new List<long>();
    
        private List<NodeInfoDto> NodeInfos { get; set; } = new List<NodeInfoDto>();
    
        protected override async Task OnParametersSetAsync()
        {
            SetSelectItem();
        }
    
        private void SetSelectItem()
        {
            foreach (var item in NodeInfoList)
            {
                if (NodeInfoIds.Contains(item.Id))
                {
                    if (!NodeInfos.Any(m => m.Id == item.Id))
                    {
                        NodeInfos.Add(item);
                    }
                }
                else
                {
                    if (NodeInfos.Any(m => m.Id == item.Id))
                    {
                        NodeInfos.Remove(item);
                    }
                }
            }
    
            NodeInfos = NodeInfoList.Where(x => NodeInfos.Any(selected => selected.Id == x.Id)).ToList();
        }
    
        private async Task OnDataGridReadAsync(DataGridReadDataEventArgs<NodeInfoDto> e)
        {
            CurrentSorting = e.Columns
                .Where(c => c.SortDirection != SortDirection.Default)
                .Select(c => c.Field + (c.SortDirection == SortDirection.Descending ? " DESC" : ""))
                .JoinAsString(",");
            CurrentPage = e.Page;
            await GetNodeInfosAsync();
    
            SetSelectItem();
    
            await InvokeAsync(StateHasChanged);
    
        }
    
        private async Task OnSelectedRowsChanged(List<NodeInfoDto> nodeInfos)
        {
            foreach (var item in NodeInfoList)
            {
                if (nodeInfos.Any(m => m.Id == item.Id))
                {
                    if (!NodeInfoIds.Any(m => m == item.Id))
                    {
                        NodeInfoIds.Add(item.Id);
                    }
                }
                else
                {
                    if (NodeInfoIds.Any(m => m == item.Id))
                    {
                        NodeInfoIds.Remove(item.Id);
                    }
                }
            }
    
            // callback only Id
            await OnSelectedRowsChangedEvent.InvokeAsync(NodeInfoIds);
        }
    }

**Comment by David-Moreira** [comment]
Yep. If you want to track across multiple pages, you'll need to have one centralized collection to keep track of it.
Which seems to be what you are doing. That doesn't seem that confusing to me. :) You can always use more descriptive method names if you want it to be more understandable for other devs.

i.e
`SelectedNodeInfoIdsTracking` or `SelectedNodeInfoIdsState`
`TrackSelectedNodeInfoIds()`

etc...

---

Additionally if that's something that's generalized in your project you can always make your own DataGrid component that handles this. 
Either by inheriting or composing.

---

It's great if our favorite libraries can handle all use cases we have, but it's not always the case.
You say the code is confusing, if that the code isn't in your project to handle that use case, it will be in the library anyway, it's just a matter of trying to make it more understandable or encapsulating it.

If you're willing to contribute, I'm fine with having a **Key** feature. I'm thinking it would be something defined as `<Func<TItem,Tkey>` where `TKey` would have to be something like an `object` or `string`? Since we can't really be introducing a generic because of the `TKey`. Better look at doing it similar to how the `Field` works internally.

Please find our guide on how to contribute here: https://github.com/Megabit/Blazorise/wiki/Contributing
@stsrki any objections or notes to the **Key** Feature?

**Comment by stsrki** [comment]
Having a `Func<TItem,Tkey>` that would be used as a key is not a bad idea. It would also potentially solve other problems where we compare TItem by reference. It could also be used internally for the Blazor `@key` parameter, where needed.

@David-Moreira you can freely explore more and see if it possible to do.
