### ISSUE TITLE
[Bug]: DataGrid DetailsRowTemplate doesn't show if event calls Mediator.Send (MediatR)

### ISSUE THREAD

**Issue by joergkrause** [Megabit/Blazorise#5323]
### Blazorise Version

1.4.2

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction, or a simple code snippet

https://github.com/joergkrause/BlazorizeMediatRIssue.git

### Steps to reproduce

Using the repo, on start page is a simple DataGrid. Click a row --> template details appear. Set checkbox (this let the SelectedRowChanged event forward a call to Mediator.Send. This executes fine, but it somehow "eats" the event to open the details template. The code definitely returns. 

This is basic grid definition:

~~~
<DataGrid TItem="WeatherForecast" SelectedRow="@State.Selected" SelectedRowChanged="@SetSelected" Data="@State.AllItems"
~~~

This is the event handler:

~~~
async Task SetSelected(WeatherForecast archive)
{
  if (c)
  {
    await Mediator.Send(new WeatherState.SetSelected.SetAction { Item = archive });
  }
}
~~~

if c==true it's in error, if c==false it works. Mediator.Send itself works and does what's supposed to do (call the handler code and executes it).

### What is expected?

Detailsrowtemplate becomes visible on click, regardless the actions in the handler function (as along as without errors)

### What is actually happening?

Detailsrowtemplate becomes not visible on click, if the handler contains a call to Mediator.Send from MediatR library. 
There is no error or warning or exception.

### Any additional comments?

The effect is only on "open" / "show". If the detailstemplate is already visible and you turn the error on, it closes as expected. After this, it doesn't open again. From that I assume that's not really an "eaten" event.

**Comment by David-Moreira** [comment]
Hello @joergkrause 
It's verified that the object reference for the Selected Item is not contained in the AllItems.
I have to say, I don't fully understand how that library works, but if new object references are being generated, I guess this can happen.

I solved your issue by just loading the data outside of the MediaR usage. This makes sure the object references don't change.
![image](https://github.com/Megabit/Blazorise/assets/22283161/fe2ea173-e509-4b1c-a344-719c15b21c26)
![image](https://github.com/Megabit/Blazorise/assets/22283161/5efc9259-7ccb-4469-a6ae-9042340957ce)

So it seems like to me that the `DataGrid` is working as expected with what's bound reference wise.

Let us know if this helps.
