### ISSUE TITLE
DataGrid grouping example confusing

### ISSUE THREAD

**Issue by tacoWanneeJama** [Megabit/Blazorise#5339]
I was playing with the first example of page: https://blazorise.com/docs/extensions/datagrid/features/grouping
When you sort on the gender only one gender-group is displayed. When you remove the sorting on the gender you can see all gender-groups.
![image](https://github.com/Megabit/Blazorise/assets/76042577/dbeaa532-1b7a-40b9-bf36-a15a1d3e4ee8)

At first glace this looked lik a bug. But looking further I see, that the visible rows are a subset of the rows of the datasource. So you don't see the same rows when you change the sorting. This is very confusing to me.
I would suggest to adjust the example so that every time the same rows are shown.

**Comment by David-Moreira** [comment]
> When you sort on the gender only one gender-group is displayed.

I was just testing this. Yea I was confused at first also. The thing is, only 10 records are displayed at a time from a total of like 500.

If you order by Gender, well you get only the first gender records, so other buckets do not show as there's no records for the other buckets in this page. This seems correct, but maybe a little confusing indeed.

We can indeed change the example to just handle like a few records which should be more clear. But I'm thinking if we should do anything else here to be more clear when there's alot of records?

@stsrki any thoughts?

**Comment by stsrki** [comment]
If you use ReadData mode, then this is how it behaves, as we don't see all the records. With ReadData, the developer is responsible for the proper fetching and grouping of data.

On the other hand, if this is in memory, then it is definitely wrong.

**Comment by stsrki** [comment]
I see now. Didn't understand that problem is on our demo.

It seems like a bug, indeed. Would it help if we enabled pagination? That way users would see that there is more data available.

**Comment by David-Moreira** [comment]
> I see now. Didn't understand that problem is on our demo.
> 
> It seems like a bug, indeed. Would it help if we enabled pagination? That way users would see that there is more data available.

Right It seems like a bug, but I am thinking that's it. It just seems like it. 
Either we reduce the amount of data so it's clearer. Or allow pagination like you just suggested, that might be indeed a bit clearer.
