### ISSUE TITLE
[Bug]: The IntervalBeforeClose of NotificationService works incorrectly

### ISSUE THREAD

**Issue by tuanhoan** [Megabit/Blazorise#5358]
### Blazorise Version

1.5.0-preview2

### What Blazorise provider are you running on?

None

### Link to minimal reproduction, or a simple code snippet

https://github.com/Megabit/Blazorise/blob/75cda39ad954478ccb5b6db1b871a35a765b5283/Demos/Blazorise.Demo/Pages/Tests/ServicesPage.razor#L81

### Steps to reproduce

1. Go to https://rcbootstrapdemo.blazorise.com/tests/utilities/services
2. Click `Show arter!` in `Notification Service` section
3. 
![image](https://github.com/Megabit/Blazorise/assets/45305726/7c0ccd37-b5ab-49ef-9f2a-7ffeff6d6166)

### What is expected?

the snackbar must shows 10000ms 

### What is actually happening?

The value is set to 10000ms but the snackbar only shows 5000ms as default

**Comment by David-Moreira** [comment]
@stsrki not sure if related : https://github.com/Megabit/Blazorise/pull/5313

**Comment by stsrki** [comment]
I have tested it, and it works in the 1.5 version. The demo on https://rcbootstrapdemo.blazorise.com/tests/utilities/services is still running on an older 1.4.0 version. I think simply uploading a new demo would also fix it there.

**Comment by stsrki** [comment]
Do you mean rc in here? **rc**bootstrapdemo.blazorise.com/tests/utilities/services

That is not for preview. The **rc** part comes from Razor Components. It is from long ago when Microsoft first introduced Blazor server, and they named it Razor Components. So I released the bootstrap server demo with that prefix. I know, I know, terrible naming. :)

**Comment by David-Moreira** [comment]
> Do you mean rc in here? **rc**bootstrapdemo.blazorise.com/tests/utilities/services
> 
> That is not for preview. The **rc** part comes from Razor Components. It is from long ago when Microsoft first introduced Blazor server, and they named it Razor Components. So I released the bootstrap server demo with that prefix. I know, I know, terrible naming. :)

AH right... In my personal opinion, I would rename it or just remove the demo as to not cause confusion...

**Comment by stsrki** [comment]
We need to find better naming for our demos that would indicate server vs wasm mode.
