### ISSUE TITLE
[Bug]: mouse pointer on disabled button in bar is wrong

### ISSUE THREAD

**Issue by blenke** [Megabit/Blazorise#5361]
### Blazorise Version

1.3.4 , 1.4.2

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction, or a simple code snippet

```tsx
<Bar>
  <BarStart>
    <BarItem>              
      <Button Color="Color.Primary" Disabled>test 1, not ok</Button>
      <Button Color="Color.Primary">test 2, ok</Button>               
    </BarItem>
  </BarStart>
  <BarItem>
    <Button Color="Color.Primary" Disabled>test 3 , ok</Button>     
  </BarItem>
</Bar>
```

### Steps to reproduce

Create a Bar with a BarStart then add a button that is disabled. When you place the mouse over the disabled button it will keep showing the 'hand' pointer instead of the arrow as would be expected on a disabled button.
When the button is used outside the Bar, BarStart it works as expected

### What is expected?

the mouse button should be the default pointer on the disabled button 

### What is actually happening?

the hand pointer is showing as if the button is active

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

**Comment by Herdo** [comment]
`BarItem` also has a `Disabled` property. Neither seem to work.

**Comment by ddjerqq** [comment]
I'm assuming I will need to add the disabled attribute to the underlying component?
I will take a closer look soon

**Comment by ddjerqq** [comment]
I will start working on this

**Comment by tesar-tech** [comment]
The way how the cursor pointer is done is like that (reboot.scss from bootstrap)

```css
button,
[type="button"], // 1
[type="reset"],
[type="submit"] {
  -webkit-appearance: button; // 2

  @if $enable-button-pointers {
    &:not(:disabled) {
      cursor: pointer; // 3
    }
  }
}
```

Which means -> in the case of button **not** being disabled, make the cursor pointer..
In the other words -> it doesn't care about the state when it is disable. Disabled button behaves like "normal" text -> inherits cursor from the parent element. 

We can simplify the issue into:

```html
<BarStart>
    <BarItem>
        text
    </BarItem>
</BarStart>
```
Where the text gets the pointer cursor..

BarStart and BarItem is a wrapper for this html:

```html
<div class="navbar-nav me-auto" _bl_3="">
    <div class="nav-item" _bl_9="">
            text
    </div>
</div>
```

The cursor is being set by the:

https://github.com/Megabit/Blazorise/blob/d5466989d186b6e5a847e97fde657e99b30520c4/Source/Blazorise.Bootstrap5/wwwroot/blazorise.bootstrap5.css#L19

the solution in pr

**Comment by stsrki** [comment]
I cannot reproduce the original problem. Whenever I try 

```
<Bar>
  <BarStart>
    <BarItem>              
      <Button Color="Color.Primary" Disabled>test 1, not ok</Button>
      <Button Color="Color.Primary">test 2, ok</Button>               
    </BarItem>
  </BarStart>
  <BarItem>
    <Button Color="Color.Primary" Disabled>test 3 , ok</Button>     
  </BarItem>
</Bar>
```

The cursor shows as expected for disabled-buttons.

**Comment by tesar-tech** [comment]
With that exact code I definitely can:

https://github.com/user-attachments/assets/56480690-f1bb-4186-9c51-43d39138f1bb

brave and ff.

**Comment by blenke** [comment]
I'm also still seeing this problem in blazorise 1.6.2 . I use bootstrap 5 as provider, perhaps this has something to do with it.
