### ISSUE TITLE
Howto make a Button / Dropdown / Colorpicker combination

### ISSUE THREAD

**Issue by njannink** [Megabit/Blazorise#5365]
Im building a toolbar and would like to add a colorpicker to my toolbar. Something that you have in Word etc to be able to have a button to assign a text color.

![image](https://github.com/Megabit/Blazorise/assets/3843546/0abda4ee-155c-4dbf-a15e-a6d4db06d49e)

Is this somehow already possible with Blazorise toolkit by combining various elements?

**Comment by stsrki** [comment]
Did you tried ColorPicker?

Other than that, you might use a regular `Div` element in a Dropdown/DropdownMenu and structure it with a Grid component. Then colorize each Div with either a Background parameter, or explicitly with `Style=""background-color: #fff`.
