### ISSUE TITLE
[Bug]: Uncaught TypeError: Cannot read properties of null (reading 'getData') textEdit

### ISSUE THREAD

**Issue by sturlath** [Megabit/Blazorise#5369]
### Blazorise Version

1.4.2

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction, or a simple code snippet

I'm getting this error from time to time in abp.io version 8.0.2

```
textEdit.js?v=1.4.2.0:51  Uncaught TypeError: Cannot read properties of null (reading 'getData')
    at paste (textEdit.js?v=1.4.2.0:51:46)
    at HTMLInputElement.<anonymous> (textEdit.js?v=1.4.2.0:35:9)
```

I can´t figure out how to reproduce it but maybe this is something you can add error handling around?

### Steps to reproduce

Can´t figure that out

### What is expected?

no error

### What is actually happening?

Error

**Comment by stsrki** [comment]
This might be similar to #5175

**Comment by David-Moreira** [comment]
@sturlath 
Just to be sure, this does not affect your application right? It keeps working regularly?

**Comment by sturlath** [comment]
@David-Moreira I have to say that I don´t remember... 🙈 I have updated my code and I can´t seem to replicate it now. Sorry.. I´ll watch for it and report if I see it again.

**Comment by David-Moreira** [comment]
I'll be closing in favor of #5175 .
If it happens again, and if it crashes your application then that'd be worrying and a different issue.
Feel free to reopen if you obesrve that.
