### ISSUE TITLE
[Bug]: Add Fluent UI to Blazorise provider in bug template

### ISSUE THREAD

**Issue by GeertvanHorrik** [Megabit/Blazorise#5373]
### Blazorise Version

1.5.0

### What Blazorise provider are you running on?

None

### Link to minimal reproduction, or a simple code snippet

see title

### Steps to reproduce

see title

### What is expected?

see title

### What is actually happening?

see title

**Comment by stsrki** [comment]
Done. Thanks for reminding us.
