### ISSUE TITLE
[Bug]: AntDesign paging style issue when using datagrid

### ISSUE THREAD

**Issue by GeertvanHorrik** [Megabit/Blazorise#5375]
### Blazorise Version

1.5.0

### What Blazorise provider are you running on?

AntDesign

### Link to minimal reproduction or a simple code snippet

See example:

https://antdesigndemo.blazorise.com/tests/datagrid/aggregates

The numbers in the pager are not centered (where they are in the paging control demo).

Paginations control demo:

![image](https://github.com/Megabit/Blazorise/assets/1246444/df831c57-2ace-479f-8e93-5e1241872bd7)

Control used by datagrid:

![image](https://github.com/Megabit/Blazorise/assets/1246444/841a0dc6-a633-4d66-b942-c62a7e945e70)

### Steps to reproduce

See demo

### What is expected?

Same style as separate pager control

### What is actually happening?

Different style

**Comment by GeertvanHorrik** [comment]
I think there are more issues with the datagrid. Buttons floating above the datagrid are overlapped by the `ant-table-content` style. Whenever I disable `position: relative`, the buttons show up again.

Below shows the issue where the DataGrid adds the white header at the top (not sure why):

![image](https://github.com/Megabit/Blazorise/assets/1246444/cea3e2b5-4d03-47a9-81fd-c41c04350dd7)

Whenever I remove the `position: relative` from `ant-table-content`, the buttons show up, but before 1.5 it was not adding this white header.

![image](https://github.com/Megabit/Blazorise/assets/1246444/b047c6f8-a611-4b2a-920e-94cca459ff4a)

The datagrid is completely separated from the buttons, yet still it overlaps them somehow. Wrapping the DataGrid inside a div with `clear: both` "solves" the issue:

```
<div>
    <Button>
        Edit
    </Button>

    ....
</div>


<div style="clear: both;">
    <DataGrid>
        ...
    </DataGrid>
</div>
```

![image](https://github.com/Megabit/Blazorise/assets/1246444/4ebf5826-ce85-4998-beb2-c75370225aa5)

**Comment by stsrki** [comment]
Can you clarify what buttons? Are we still talking about pagination button? If you have some custom code it would be great if you could provide an example.

**Comment by GeertvanHorrik** [comment]
No, just custom buttons I put above the datagrid. I will try to create a repro, but it's a lot of work every time I find something so must find resources to do so.

Here is the pseudo code I use:

```
<div>
    <Button>
        Edit
    </Button>

    ....
</div>

<div style="clear: both;">
    <DataGrid>
        ...
    </DataGrid>
</div>
```

Without the `clear: both`, the datagrid expands to the top, hiding the buttons.

**Comment by stsrki** [comment]
Ant Design may also have some new default styles in v4.24.x.

**Comment by GeertvanHorrik** [comment]
Created [Blazorise_Playground](https://github.com/GeertvanHorrik/Blazorise_Playground) repro so I can easily add more repros in the future.

Please see the DataGrid page. Once I update to the latest, the buttons are invisible. If you add the `clear: both`, it starts behaving as it used to do.

**Comment by tesar-tech** [comment]
The first issue is being solved.

The second point you raised is actually expected CSS behavior rather than a bug. The key detail here is that the buttons have `float: right`, which causes them to float over the datagrid and get obscured by the grid’s default white background. To fix this, you can adjust the `z-index` on the buttons to bring them above the datagrid and make them visible.

For positioning buttons on the right, I recommend placing them within a `div` and using `display: flex` with `justify-content: flex-end` for alignment. This approach avoids the issues that come with floats and keeps the layout more stable.

**Comment by stsrki** [comment]
> For positioning buttons on the right, I recommend placing them within a `div` and using `display: flex` with `justify-content: flex-end` for alignment. This approach avoids the issues that come with floats and keeps the layout more stable.

You can also use Blazorise utilities as:

```razor
<Div Flex="Flex.JustifyContent.End">
</Div>
```
