### ISSUE TITLE
DataGrid: Choosing columns in ColumnChooser raises an event

### ISSUE THREAD

**Issue by oaldrian** [Megabit/Blazorise#5400]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to detect if a user has changed their columns in a DataGrid

**Describe the solution you'd like**
Either
- there are two events, one for adding, one for removing a column, or
- there is one event which contains the info in the event data

### Additional context
This could be used to "AutoSave" a GridState for the user.
Filters can already be detected.

**Comment by David-Moreira** [comment]
@stsrki I would do this for 1.6, but by your earliest considerations about adding public apis mid release... this could be added... I personally don't like public apis popping in patches unless absolutely necessary, but if you want to take that route I'm fine with it.

**Comment by stsrki** [comment]
Agree. And I think we should also move #5401 to 1.6. I thought it would be a smaller change but it is too much for a minor release.

**Comment by David-Moreira** [comment]
> Currently there is no way to detect if a user has changed their columns in a DataGrid

It is of note that there's a way. Not very elegant. But by overriding the `ColumnChooserTemplate` you'll be able to know when it changes with `ColumnDisplayChanged`
![image](https://github.com/Megabit/Blazorise/assets/22283161/5e0cde8f-14d2-4740-9bf8-89d1fae5ee74)

I think it's fine to make the same event available at `DataGrid` level. Same arguments with the info you need.
![image](https://github.com/Megabit/Blazorise/assets/22283161/3bc392ee-8169-4b33-aacc-863efafa217c)

Also if you were worried about knowing the state for the `DataGridState`, there's a `GetState` that gets the current `DataGridState`, in v1.6, you'll have access to `ColumnDisplayingStates`.
![image](https://github.com/Megabit/Blazorise/assets/22283161/3042987a-3f8a-4c7c-8349-8d78eaae40ae)

**Comment by oaldrian** [comment]
Thanks for the info! 
I missed the event on the "inner" level. 

KR
