### ISSUE TITLE
Allow DataGrid Columns to be Hidden/Shown in code behind

### ISSUE THREAD

**Issue by gordoncoulter** [Megabit/Blazorise#5407]
**Problem**
The Displayable property is currently read-only. Is that by design? Changing it in VS debug mode is reflected in the grid and column chooser.

For example, based on the code below - in the search criteria, if someone picks to filter to a specific department, then I don't want to show that column in the grid. If they leave it blank, then that column is more relevant.

I'd like to be able to configure that when generating my query.

As a workaround, I think I can use the just committed "Add Column Visibility to Grid State" code to build a grid state and then apply it, but it's not a clean solution.

**Solution**
```
DataGrid<employee> EmployeeGrid;

var col = EmployeeGrid.GetColumns().Where(x=>x.Field == "Department").FirstOrDefault();
col.Displayable = false;

```

**Comment by David-Moreira** [comment]
The `Displayable` property is not readonly, but it is a Parameter and is not recommended to be set imperatively.
Also it's only used to represent the initial state of the column.
![image](https://github.com/Megabit/Blazorise/assets/22283161/799f84f9-3b5c-4529-a54a-c3f07b9ce2fc)

To represent the current display state of the column we now have `Displaying` that was introduced with the Column Chooser feature.

![image](https://github.com/Megabit/Blazorise/assets/22283161/8961fb7d-e73c-44bf-84c3-74b38b1f438c)

This one is indeed `readonly`, and we can consider making it settable.
For now I guess it would be fine to use reflection to set it as we very rarely get rid of public apis or change them. If we do change them, we usually have them obsolete for at least a few versions.

**Comment by David-Moreira** [comment]
@stsrki I think it's fine to make this property settable. I guess this might be one of those changes we could indeed potentially do mid release? What do you think

**Comment by gordoncoulter** [comment]
That's great and yes, I mentioned the wrong property. It is **Displaying** I was referring to.

**Comment by gordoncoulter** [comment]
Works perfectly! Thank you.
