### ISSUE TITLE
[Bug]: Bulma Accordion toggle is just a normal button

### ISSUE THREAD

**Issue by eric-patton-bam** [Megabit/Blazorise#5412]
### Blazorise Version

1.5.0

### What Blazorise provider are you running on?

Bulma

### Link to minimal reproduction or a simple code snippet

https://bulmademo.blazorise.com/tests/accordion

### Steps to reproduce

Just visit the Blazorise demo for the accordion for Bulma: https://bulmademo.blazorise.com/tests/accordion

### What is expected?

Expectation is for it to look like a normal accordion header like the rest of the demos:

https://blazorise.com/docs/components/accordion
https://tailwinddemo.blazorise.com/tests/accordion
https://bootstrapdemo.blazorise.com/tests/accordion
https://materialdemo.blazorise.com/tests/accordion
https://bootstrap5demo.blazorise.com/tests/accordion

### What is actually happening?

The toggle is just rendering a normal button that is just the width of the text in it with a line underneath it separating it from the content. It doesn't look like an accordion should look, like in the other demos.

### What browsers do you see the problem on?

Chrome

**Comment by stsrki** [comment]
The button was used because Bulma natively doesn't have any accordion component. So we had to improvise a little.

In any case. We should at least make it look better.
