### ISSUE TITLE
ToastService - Option to change the AutoHide and the AutoHideDelay via the service

### ISSUE THREAD

**Issue by gadjio** [Megabit/Blazorise#5432]
It could be nice to be able to change the AutoHide / AutohideDelay property via the ToastService, not all toast messages have the same impact.

Something like :
await ToastService.Success(confirmationMessage, localizer["Success"], options => options.Autohide=false);

Thanks

**Comment by stsrki** [comment]
Good idea. I will schedule it for the next release.

Thank you for suggestion.
