### ISSUE TITLE
[Bug]: toast visible throug api does not work

### ISSUE THREAD

**Issue by blenke** [Megabit/Blazorise#5441]
### Blazorise Version

1.5.1

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction or a simple code snippet

When using a reference on a toast component then the Visible=true does not seem to work

### Steps to reproduce

```
<Toaster>
    <Toast @ref=tref>
        <ToastHeader>
            <Strong Margin="Margin.IsAuto.FromEnd">Blazorise</Strong>
            <Small>11 mins ago</Small>
            <CloseButton />
        </ToastHeader>
        <ToastBody>
            Hello, world! This is a toast message.
        </ToastBody>
    </Toast>
</Toaster>

<Button @onclick="t">toast does not work</Button>


@code {    
    Toast tref;    
    void t()
    {    
        tref.Visible = true;        
    }
}

```

### What is expected?

The toast to show. It works when using a bind-Visible .

### What is actually happening?

nothing is showing

### What browsers do you see the problem on?

Chrome, Microsoft Edge

**Comment by stsrki** [comment]
This is by design. Controlling the component with `bind-Visible` is a declarative approach and is a recommended way for Blazor components. Controlling it with `tref.Visible = true;` is imperative and is not recommended as it bypasses the Blazor rendering cycle.

From Blazor docs

![image](https://github.com/Megabit/Blazorise/assets/900302/df484194-6ef2-42cc-aeb9-fdea4654244b)

**Comment by blenke** [comment]
ok, i can make it work with the bind-Visible as well.

**Comment by blenke** [comment]
That's a good tip, i missed that, that was what i was looking for and works indeed. I wanted to show a message after a form closes when saving so it needed to show the toast on the datagrid overview on another form.

**Comment by stsrki** [comment]
At the moment, the toast provider has limited options for styling. We plan to add more in the coming version.
