### ISSUE TITLE
[Bug]: Autocomplete Error sign not possible to remove/ cant add error text  

### ISSUE THREAD

**Issue by danik121** [Megabit/Blazorise#5451]
### Blazorise Version

1.5.1

### What Blazorise provider are you running on?

Fluient ui

### Link to minimal reproduction or a simple code snippet

![image](https://github.com/Megabit/Blazorise/assets/8233518/6a021d1e-014a-4509-991b-e2ae7115bd08)

### Steps to reproduce

```
<Autocomplete Filter="AutocompleteFilter.Contains" Virtualize
                                Validator="@ValidationRule.IsNotEmpty"
                                TItem="NamedSelectionListDto<long>" MinLength="0" Data="@Users"
                                TValue="long?" TextField="@(( item ) => item.Name)"
                                SelectedValue="@User.Id" SelectedValueChanged="@UserValueChanged"
                                ValueField="@(( item ) => item.Id)">
                  <Feedback>
                    <ValidationError>
                      susususu
                    </ValidationError>
                  </Feedback>
                  </Autocomplete>
```

### What is expected?

how  can i add a message or remove error sign?

### What is actually happening?

on error it shown always error sign on next row, i cant hide that sign or add some text after that sign

**Comment by stsrki** [comment]
You need to use your own validator to add the message

```
void ValidateName( ValidatorEventArgs e )
{
    e.Status = string.IsNullOrEmpty( Convert.ToString( e.Value ) )
        ? ValidationStatus.Error
        : ValidationStatus.Success;

    if (e.Status == ValidationStatus.Error)
        e.ErrorText = "your error message";  
}
```

and use it as

```diff
<Autocomplete Filter="AutocompleteFilter.Contains" Virtualize
+                                Validator="@ValidateName"
                                TItem="NamedSelectionListDto<long>" MinLength="0" Data="@Users"
                                TValue="long?" TextField="@(( item ) => item.Name)"
                                SelectedValue="@User.Id" SelectedValueChanged="@UserValueChanged"
                                ValueField="@(( item ) => item.Id)">
                  <Feedback>
                    <ValidationError>
                      susususu
                    </ValidationError>
                  </Feedback>
                  </Autocomplete>
```

**Comment by danik121** [comment]
> You need to use your own validator to add the message
> 
> ```
> void ValidateName( ValidatorEventArgs e )
> {
>     e.Status = string.IsNullOrEmpty( Convert.ToString( e.Value ) )
>         ? ValidationStatus.Error
>         : ValidationStatus.Success;
> 
>     if (e.Status == ValidationStatus.Error)
>         e.ErrorText = "your error message";  
> }
> ```
> 
> and use it as
> 
> ```diff
> <Autocomplete Filter="AutocompleteFilter.Contains" Virtualize
> +                                Validator="@ValidateName"
>                                 TItem="NamedSelectionListDto<long>" MinLength="0" Data="@Users"
>                                 TValue="long?" TextField="@(( item ) => item.Name)"
>                                 SelectedValue="@User.Id" SelectedValueChanged="@UserValueChanged"
>                                 ValueField="@(( item ) => item.Id)">
>                   <Feedback>
>                     <ValidationError>
>                       susususu
>                     </ValidationError>
>                   </Feedback>
>                   </Autocomplete>
> ```

It is possible to remove error sing?

**Comment by stsrki** [comment]
It is not possible at the moment. The fluent design should show the error icon according to the specifications. We could consider adding it in the future. Or add an opt-in parameter.
