### ISSUE TITLE
Using FluentUI2: Unable to change Modal size

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#5454]
### Discussed in https://github.com/Megabit/Blazorise/discussions/5450

<div type='discussions-op-text'>

<sup>Originally posted by **DomenicoFormoso** April 10, 2024</sup>
In version 1.5.1 of FluentUI I found the same problem found on material and then solved here:
https://github.com/Megabit/Blazorise/issues/5063

</div>

**Comment by stsrki** [comment]
@David-Moreira, I need your help with this one. For some reason, when the ModalProvider passes the Size parameter to the ModalContent, which is used by the Fluent provider, it seems to never change after that. I cannot figure out what is wrong.

**Comment by David-Moreira** [comment]
> @David-Moreira, I need your help with this one. For some reason, when the ModalProvider passes the Size parameter to the ModalContent, which is used by the Fluent provider, it seems to never change after that. I cannot figure out what is wrong.

hmm do you have a branch open with the attempt?

**Comment by stsrki** [comment]
I just did this in the demo

```diff
public async Task ShowStateful()
{
    if ( statefulModalInstance is null )
    {
        statefulModalInstance = await ModalService.Show<Counter>( "My Stateful content", new ModalInstanceOptions()
        {
            Stateful = true,
            RenderMode = ModalRenderMode.LazyLoad,
+            Size = ModalSize.ExtraLarge,
        } );

        return;
    }

    await ModalService.Show( statefulModalInstance );
}
```

**Comment by David-Moreira** [comment]
Strange I believe I've seen that work. Is it happening provider specifically?

**Comment by stsrki** [comment]
Yes. For the Fluent provider, I had to propagate the Size from `ModalContent` to the `Modal` parent component.

**Comment by David-Moreira** [comment]
It seems like the custom handlers in `FluentUI` to propagate the Size from `ModalContent` to the `Modal` parent component only propagate on an actual change.
Since the `ModalProvider` renders on demand, the `Size` parameter will already start defined as Extra Large and will not be detected as a change.

I added the `OnInitialized` with similar code and it seems to work properly. Can you verify?
```
protected override void OnInitialized()
    {
        if ( ParentModal is FluentUI2.Components.Modal fluentModal )
        {
            fluentModal.NotifyModalSizeChanged( Size );
            fluentModal.NotifyModalCenteredChanged( Centered );
        }

        base.OnInitialized();
    }
```
![image](https://github.com/Megabit/Blazorise/assets/22283161/d6280ced-6eeb-4e3a-a62b-90b356296456)

**Comment by stsrki** [comment]
It still doesn't work as expected. It remembers the last size and shows XL for all opened modal instances If you go to the demo `tests/modal-provider`, and update

```
public async Task ShowStateful()
{
    if ( statefulModalInstance is null )
    {
        statefulModalInstance = await ModalService.Show<Counter>( "My Stateful content", new ModalInstanceOptions()
        {
            Stateful = true,
            RenderMode = ModalRenderMode.LazyLoad,
            Size = ModalSize.ExtraLarge,
        } );

        return;
    }

    await ModalService.Show( statefulModalInstance );
}
```

launch and click on 

![image](https://github.com/Megabit/Blazorise/assets/900302/75dd41bc-a247-46c6-ba8e-a7b6c6a33a49)

Now click on any other demo and it will still show as XL modal.

**Comment by David-Moreira** [comment]
Are you perhaps forgetting about the global setting? 
`<ModalProvider UseModalStructure Animated Size="ModalSize.ExtraLarge" />`

Ok, so again... I copied your example and ran it, could verify the problem.
Then I went back to my comment and applied the fix, seems to be working correctly. 
Can you please recheck?

Don't forget to set the global setting to `Size="ModalSize.Default" ` or to explicitly pass in the `Size` parameter in the options.

**Comment by stsrki** [comment]
> Are you perhaps forgetting about the global setting? `<ModalProvider UseModalStructure Animated Size="ModalSize.ExtraLarge" />`
> 
> Ok, so again... I copied your example and ran it, could verify the problem. Then I went back to my comment and applied the fix, seems to be working correctly. Can you please recheck?
> 
> Don't forget to set the global setting to `Size="ModalSize.Default" ` or to explicitly pass in the `Size` parameter in the options.

Yeah, that was it. Thanks.
