### ISSUE TITLE
Video: add events for rewind and fast forward

### ISSUE THREAD

**Issue by thumaman** [Megabit/Blazorise#5458]
Is there a feature to skip/rewind 5 or 10 seconds of the video, like in youtube for example?

I saw that there is a rewind and fast-forward option, but is there any event that triggers when the buttons are triggered?

I think it would be a valuable feature to have :)

**Comment by David-Moreira** [comment]
I'm not super familiar with the video extension but I can chime in with some observations, @stsrki might complement later,

There's this example with jump to 20s
https://bootstrapdemo.blazorise.com/tests/video
https://github.com/Megabit/Blazorise/blob/master/Demos/Blazorise.Demo/Pages/Tests/VideoPage.razor

On our docs you can tell there's a controls list
https://blazorise.com/docs/extensions/video
![image](https://github.com/Megabit/Blazorise/assets/22283161/eb9c3769-d93a-4bf7-bab4-2cf85301b1b5)
![image](https://github.com/Megabit/Blazorise/assets/22283161/60df749e-f0af-4b4c-ac24-5fc110d2fff8)

Have you tried these yet?

**Comment by thumaman** [comment]
Yes those worked, thank you, but now I want to catch the event when user presses fast-forward or rewind.

**Comment by David-Moreira** [comment]
I don't think there's an event for that.
We could consider improving on contextual events. @stsrki 

Only workaround I can think off for now, is that you could probably implement your own buttons that do these operations. Downside is that these would live outside the video player I guess.

**Comment by stsrki** [comment]
I don't think we have the events specific for fast-forwarding and rewinding. You might experiment with

- Progress
- TimeUpdate
- Seeking

**Comment by stsrki** [comment]
PS. in the long run, we plan to migrate to the newest video component library. #4914

**Comment by stsrki** [comment]
We plan to add missing events in 1.7.
