### ISSUE TITLE
[Bug]: AntDesign - badges colors do not work

### ISSUE THREAD

**Issue by KyleTraynor** [Megabit/Blazorise#5462]
### Blazorise Version

1.5

### What Blazorise provider are you running on?

AntDesign

### Link to minimal reproduction or a simple code snippet

  <Badge Color="Color.Primary">
          Text
  </Badge>

### Steps to reproduce

See the official blazorise ant demo page, it is also broken there - https://antdesigndemo.blazorise.com/tests/badges

### What is expected?

Badge should respect primary, secondary, danger, info light and dark colors

### What is actually happening?

They are all grey

**Comment by stsrki** [comment]
It's strange how we missed that. It's definitely a bug. Thanks for letting us know.
