### ISSUE TITLE
Change video captions

### ISSUE THREAD

**Issue by thumaman** [Megabit/Blazorise#5479]
Is there a way of changing captions of the video with custom buttons. What I mean by that is, I want to make my own button that displays available captions and by selecting them, they get updated in the video player.

I want this so that i can position and style my own buttons and menus with captions and make my application more customizable.

**Comment by stsrki** [comment]
This should be possible with the `ControlsList` parameter, which accepts an array of strings. The strings are, by default, the predefined names of the controls, but you should be able to define a custom name.

Here are some resources online that might help you to grasp it. Note they are for JS version but they should still apply

- https://codepen.io/kkupgrader/pen/RwGrzMQ
- https://codepen.io/jwjcmw/pen/pedQRL

**Comment by thumaman** [comment]
So if I understand correctly I can define a custom control that can then be used to change the captions of the current video?

**Comment by thumaman** [comment]
Is it possible to do it all with C# and not use any JS?

**Comment by stsrki** [comment]
At the moment, it is not possible.

**Comment by thumaman** [comment]
Then I think it would be a useful feature to have since it is more independent and faster than JS, I would suggest the current player to have a currentTrack field which can then be used to change the video track of the player.

**Comment by stsrki** [comment]
Can you explain the proposed API and how it could be used?

**Comment by thumaman** [comment]
I would have the Video have an attribute called currentTrack which would be initially set to null or the Default value of Tracks array.
Then a user could make a custom menu or use the one currently generated from Tracks which when clicking on a certain subtitle would change the visibility of the desired track from hidden/disabled to showing, thus displaying the track along with the video. 

It could be used so the user could create a custom menu outside the video player with which he/she could manipulate the player and create a more customizable environment.

I hope I explained it well, if not let me know :)

**Comment by thumaman** [comment]
Will that functionality ever be supportedin the upcoming weeks? :)

**Comment by stsrki** [comment]
Possibly yes. But it depends on the complexity. We also plan to migrate to the newer version of the video library so we need to be careful with adding too many features. In case they are not supported by this new library.

**Comment by stsrki** [comment]
Ps. #4914

**Comment by thumaman** [comment]
I understand. If possible I would also suggest that the Video has a Volume attribute, enabling a programmer to make a custom button/slider to manipulate with the volume of the player.

**Comment by thumaman** [comment]
Is there any more information on updating the video player/having customizable controls such as subtitles?

**Comment by stsrki** [comment]
Sorry, not yet planned. I could move it to the next milestone but there are still other work to do first. 

In case you wish to help we're always open to contributions.

**Comment by thumaman** [comment]
That would be much appreciated.

Unfortunately I am very busy at the moment and probably will not be able to contibute to your project.

**Comment by stsrki** [comment]
https://github.com/Megabit/Blazorise/issues/4914#issuecomment-2208779460

**Comment by thumaman** [comment]
Hi, are there any updates on the video player and changing the subtitles? Also are there any plans to change the plyr anytime soon to a more modern player?
Thanks for the answes!

**Comment by stsrki** [comment]
We're updating the video to a new version, and we will try to make it by 1.6 release. Regarding this particular feature it all depends on how complex it might be with the new library.

**Comment by thumaman** [comment]
That is great to hear!
Do you have any idea approximately when the 1.6 version will be released?

**Comment by stsrki** [comment]
It's planned for July 23rd.

**Comment by thumaman** [comment]
Great, thanks for the replies :)
