### ISSUE TITLE
Datagrid Aggregates for Columns without field

### ISSUE THREAD

**Issue by oaldrian** [Megabit/Blazorise#5484]
**Is your feature request related to a problem? Please describe.**
If I have columns that do not directly link to a field as sources for the data, but instead use Display and EditTemplates (#548), there is currently no way to attach an aggregate to this column, as the column identifier for the aggregate is the field name.

**Describe the solution you'd like**
Introduce a ColumnID parameter to the Column and the Aggregate that is set to Field, if it is not overridden. Use this ColumnID paramter to match the aggregate to the column.

### Additional context
introducing an extra standard row to the grid, with the aggregates inside, works only if there is no sorting / filtering / grouping, so it is not really a viable workaround.

A current workaround is to create many (many) placeholder properties in the class to bind the dynamic columns to.

**Comment by David-Moreira** [comment]
hello @oaldrian 
There now exists an `AggregateTemplate` that you can define per column, this should give you the flexibility you are looking for, where the `Field` parameter is no longer required.

https://github.com/Megabit/Blazorise/pull/5350

Please try it out, and feel free to reopen the issue if this does not fix your issue.

**Comment by oaldrian** [comment]
Many thanks, will try out next week!
