### ISSUE TITLE
[Bug]: Crash when checking license if chart is inside a slow carrousel.

### ISSUE THREAD

**Issue by claunia** [Megabit/Blazorise#5491]
### Blazorise Version

1.5.2

### What Blazorise provider are you running on?

None

### Link to minimal reproduction or a simple code snippet

```razor
    <Carousel Interval="5000">
        <CarouselSlide Name="1">
            <PieChart @ref="_chart1" style="padding: 40px" TItem="long"/>
        </CarouselSlide>
        <CarouselSlide Name="2">
            <PieChart @ref=_chart2" style="padding: 40px" TItem="long"/>
        </CarouselSlide>
    </Carousel>

@code
{
    PieChart<long>?       _chart1;
    PieChart<long>?       _chart1;

    protected override async Task OnInitializedAsync()
    {
        await
            Task.WhenAll(HandleRedraw(_chart1, GetChartDataset),
                         HandleRedraw(_chart2, GetChartDataset));
    }
}
```

### Steps to reproduce

Using SSR put charts inside a carousel and put a long interval.

### What is expected?

Charts drawing correctly.

### What is actually happening?

`NullReferenceException` in https://github.com/Megabit/Blazorise/blob/cc900df827da49c7b26823e1ceac1ee91b8b7087/Source/Extensions/Blazorise.Charts/BaseChart.cs#L82

### What browsers do you see the problem on?

Chrome, Microsoft Edge, Safari, Firefox

**Comment by David-Moreira** [comment]
Please provide a complete reproducible, as the snippet alone is not enough to reproduce the issue.

**Comment by claunia** [comment]
It looks like a race condition, as it does not happen with an interval of 2000.

Will take some time to prepare a more complete snippet.

**Comment by stsrki** [comment]
Hello @claunia, were you able to reproduce the error in a separate project?

**Comment by claunia** [comment]
Didn't have the time yet but I have not forgotten.

Need to finish project first sorry, will take some days.
