### ISSUE TITLE
[Bug]: DataGridSelectColumn shows filter value instead of empty filter cell 

### ISSUE THREAD

**Issue by McFSR** [Megabit/Blazorise#5497]
### Blazorise Version

1.5.2

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction or a simple code snippet

```razor
<DataGrid @ref="_dataGrid"
          TItem="BankDTO"
          Data="_bankList"
          Filterable="true">
    <DataGridColumns>
        <DataGridSelectColumn TItem="BankDTO" 
                              Field="@nameof(BankDTO.Rule)" Caption="BankRule" 
                              Data="_allRules" 
                              ValueField="(s) => Convert.ToString(s) " 
                              TextField="(s) => Convert.ToString(s)">
        </DataGridSelectColumn>
    </DataGridColumns>
</DataGrid>
```

### Steps to reproduce

I use the datagrid in the sample above.
Data for the select-column ("_allRules") is a list of strings.

### What is expected?

1. When the grid initially renders, the filter in the column "BankRule" is empty and the grid is not filtered.

### What is actually happening?

1. When the grid initially renders, the first value from the _allRules list is displayed in the column filter. 
2. The grid is NOT filtered. 
3. Clicking the clear filter button does NOT clear the filter. 

### What browsers do you see the problem on?

Chrome

**Comment by David-Moreira** [comment]
@McFSR Does the `_allRules` list contain an empty value so it can bind to?

If I remember correctly the select component will show the first item if it can't find something to bind to.

**Comment by McFSR** [comment]
@David-Moreira 
No `_allRules` does not have an empty entry. I could do that in this case, but what if I bind an enum to the column? 
Feels strange I have to provide an empty entry to allow a "not filtered" state.

**Comment by David-Moreira** [comment]
@McFSR The DataGridSelectColumn is based on our Select component which utilizes html semantics and rules. 
That's how it works by default the provided `<option>` is what you get.
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select
![image](https://github.com/Megabit/Blazorise/assets/22283161/1ba09576-9ea9-4004-93e2-5baaea8a9c82)

However, I was just checking,
We have an option for a default value in Select (which will generate an extra `<option>` to accomodate that value)

Can you try using the `DefaultItemText` and the `DefaultItemHidden` and see if these fit your needs?

![image](https://github.com/Megabit/Blazorise/assets/22283161/32272ac8-6e47-44c6-8a0e-8a5fd7b6b449)

**Comment by McFSR** [comment]
OK, I was able to make it work as desired by simpy adding
`DefaultItemText=""`
Thanks!
