### ISSUE TITLE
Chart: Implement zoom plug-in

### ISSUE THREAD

**Issue by technyon** [Megabit/Blazorise#5502]
**Is your feature request related to a problem? Please describe.**
The current implementation for charts lacks zoom (and panning).

**Describe the solution you'd like**
Allow the user to zoom. This functionality could be enabled by implement wrapper code for chartjs-plugin-zoom

### Additional context
I need a line chart that displays realtime data, and at the same time allows the user to zoom in on parts of the data. Optimally scrolling of realtime data would stop while the user has zoomed in on data, and continue when returning to "normal" zoom.

P.S.: I'm using server-side rendering.

**Comment by stsrki** [comment]
Hello @technyon Thank you for the submission.

As mentioned in our previous discussion, we will look into it and implement it if possible.

---

Not for self: https://www.chartjs.org/chartjs-plugin-zoom/latest/

**Comment by technyon** [comment]
For reference, this library already implements the plugin:

https://github.com/erossini/BlazorChartjs
