### ISSUE TITLE
[Bug]: The DropDown size cannot be changed with version 1.52 and FluentUI

### ISSUE THREAD

**Issue by DomenicoFormoso** [Megabit/Blazorise#5509]
### Blazorise Version

1.52

### What Blazorise provider are you running on?

FluentUI2

### Link to minimal reproduction or a simple code snippet

.

### Steps to reproduce

set Size.ExtraSmall in the DropdownToggle component

### What is expected?

The size are changed

### What is actually happening?

The size remain the same

**Comment by DomenicoFormoso** [comment]
Thank you very much

**Comment by stsrki** [comment]
You're welcome :)

Expect the 1.5.3 release this week.
