### ISSUE TITLE
[Bug]: missing css class for botstrap5

### ISSUE THREAD

**Issue by drma-tech** [Megabit/Blazorise#5511]
### Blazorise Version

1.5.2

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction or a simple code snippet

`<Paragraph TextAlignment="TextAlignment.Justified">`

### Steps to reproduce

`<p class="mb-1 text-justify" _bl_491=""></p>`

A reference to this CSS class is generated, but it does not exist.

### What is expected?

css class present to be processed by the browser

### What is actually happening?

At the time (a year ago) I did this it was with bootstrap4 (it worked at the time). I recently migrated to 5 and now I noticed that this class is missing. There may be other absences, I only noticed this one. Maybe it's even missing in 4 (I don't know, because I don't use it anymore)

### What browsers do you see the problem on?

Chrome

**Comment by drma-tech** [comment]
@David-Moreira  @stsrki

**Comment by stsrki** [comment]
It seems the justify was removed from BS5 according to this note

![Image](https://github.com/user-attachments/assets/4f4fc153-a7e7-4ee3-998b-68d06ec36339)

So, I have added it to Blazorise.
