### ISSUE TITLE
ReuseTab 

### ISSUE THREAD

**Issue by dongfo** [Megabit/Blazorise#5512]
A clear and concise description of what the problem is. Example: I am trying to do [...] but [...]
Implement the reusable tab, when switching the menu, the tab also does not close. You can right-click the pop-up menu and close a single tab or close all left /right/ all.

### Additional context
AntBlazor Components
https://github.com/ant-design-blazor/ant-design-blazor/tree/23c6160bf584d0fc700af99e6151fe5f0ad93d5f/components/tabs/Reuse

**Comment by stsrki** [comment]
I think this can be done as an extension. My idea is to use our Tabs/Tab components and build extra logic to handle dynamic opening and closing, similar to the proposed component.

We can add it to the `Blazorise.Components` package.

**Comment by stsrki** [comment]
@David-Moreira If I remember you got some Blazor tabs component in the past. Maybe this is good feature for you to create since you have some experience already.

**Comment by David-Moreira** [comment]
Yes, seems similar it's this one https://github.com/David-Moreira/BlazorXTabs one of the main features is exactly to be able to open **a tab per url** similar to how browsers behave.

I guess we can bring something similar to Blazorise, but I remember they were a lot of intricacies revolving around making it work correctly with authentication, at least with the approach I took at the time, which was based on providing a customized **RouteView** component, that just by setting it  would handle everything automatically.
![image](https://github.com/user-attachments/assets/a972750e-7f4e-4fc7-8ca3-8b61c82b4442)
I'm not sure whether we would want this specifically or if there's a better way to handle it.

**Comment by stsrki** [comment]
You can investigate how it was done in AntD. And we must give credit if we took any inspiration from it.

**Comment by David-Moreira** [comment]
@stsrki Any idea for the naming? 
PageTabs? RouteTabs? RouterTabs? PagedTabs?

I think I'm going to borrow ideas from AntD. It seems less complex and less bug prone then making a specialized **RouteView**, altough the specialized **RouteView** is a bit more elegant for the end user in my opinion.

**Comment by stsrki** [comment]
RouterTabs seems like the most obvious, considering it listens to the routes.
