### ISSUE TITLE
[Bug]: ModalProvider updates parameters mutliple times on show and again on hide.

### ISSUE THREAD

**Issue by GaryWayneSmith** [Megabit/Blazorise#5525]
### Blazorise Version

1.5.2

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction or a simple code snippet

Sample.Razor page:
```
   int Model=0;

   [Inject] public IModalService ModalService { get; set; }
   private async Task OnEditClick()
   {
       await ModalService.Show<ModalCustom>("Edit Page",
           parameters =>
           {
               parameters.Add("Request", new ModalCustom.RequestModel { PageId=42 , });
               parameters.Add("OnDialogCompleted", EventCallback.Factory.Create<ModalCustom.ModalResult<int>>(this, OnEditDialogCompleted));
           },
           new ModalInstanceOptions()
               {
                   UseModalStructure = false,
                   Animated = false,
               }
       );
       Debug.WriteLine("OnEditClick complete");
   }

   private async void OnEditDialogCompleted(ModalCustom.ModalResult<int> r)
   {
       await ModalService.Hide();
       if (r.ResultType == ModalCustom.ModalResult<int>.ModalResultType.OK)
       {
           if (r.Data == 0)
           {
               Debug.Write("Invalid page returned");
               return;
           }
           Model = r.Data;
           StateHasChanged();
       }
   }
```

ModalCustom.Razor:
```
@using System.Diagnostics

<h3>Full page edit dialog</h3>

<Button class="mt-3" Color="Color.Success" Type="ButtonType.Button" Size="Size.Small" @onclick="Save">Save</Button>
<Button class="mt-3" Color="Color.Success" Type="ButtonType.Button" Size="Size.Small" @onclick="Cancel">Cancel</Button>


@code {

    public class ModalResult<TResult>
    {
        public ModalResultType ResultType { get; private set; } = ModalResultType.NoSet;
        public TResult Data { get; set; } = default;

        public static ModalResult<TResult> OK() => new ModalResult<TResult>() { ResultType = ModalResultType.OK };
        public static ModalResult<TResult> Exit() => new ModalResult<TResult>() { ResultType = ModalResultType.Exit };
        public static ModalResult<TResult> Cancel() => new ModalResult<TResult>() { ResultType = ModalResultType.Cancel };
        public static ModalResult<TResult> OK(TResult data) => new ModalResult<TResult>() { Data = data, ResultType = ModalResultType.OK };
        public static ModalResult<TResult> Exit(TResult data) => new ModalResult<TResult>() { Data = data, ResultType = ModalResultType.Exit };
        public static ModalResult<TResult> Cancel(TResult data) => new ModalResult<TResult>() { Data = data, ResultType = ModalResultType.Cancel };

        public enum ModalResultType { NoSet, OK, Cancel, Exit }
    }

    public class RequestModel
    {
        public int PageId { get; set; }
    }

    [Parameter] public RequestModel Request { get; set; } = default;
    [Parameter] public EventCallback<ModalResult<int>> OnDialogCompleted { get; set; }
    int interation = 0;

    protected override async Task OnParametersSetAsync()
    {
        interation++;
        Debug.WriteLine($"OnParametersSetAsync, iteration: {interation}");

        await base.OnParametersSetAsync();
    }

    protected async Task Save()
    {
        Debug.WriteLine($"Save, iteration: {interation}");
        await OnDialogCompleted.InvokeAsync(ModalResult<int>.OK(22));
    }
    protected async Task Cancel()
    {
        Debug.WriteLine($"Cancel, iteration: {interation}");
        await OnDialogCompleted.InvokeAsync(ModalResult<int>.Cancel());
    }
}
```

### Steps to reproduce

Create the ModalCustom.razor page with the fragment above, then on any page add the additional code with a button to trigger the modal.

### What is expected?

I would expect the parameters to be set once, triggering a single call to the base OnParamtersSet(async) calls.  I would also expect no calls at all on hide as not parameters should be set on exit.

OnEditClick complete
OnParametersSetAsync, iteration: 1
Cancel, iteration: 1

### What is actually happening?

Parameters are being set multiple times, firing multiple events.

OnEditClick complete
OnParametersSetAsync, iteration: 1
OnParametersSetAsync, iteration: 2
OnParametersSetAsync, iteration: 3
OnParametersSetAsync, iteration: 4
OnParametersSetAsync, iteration: 5
OnParametersSetAsync, iteration: 6
OnParametersSetAsync, iteration: 7
Cancel, iteration: 7

### What browsers do you see the problem on?

Firefox

### Any additional comments?

If you have heavy data calls there is a potential to load it multiple times.

Most of the other tested frameworks only trigger it once.  If you are migrating code over this is something to consider.

**Comment by GaryWayneSmith** [comment]
I have a short workaround, which worked at first, then failed, but then worked again, is checking a variable on entry and then immediately setting it.  I originally did this after my data call and saw that it still managed to execute the call to the OnParametersSet call multiple times.  When I moved the _isLoaded to the top of the method it worked better.  It seems like this is being called multiple times in parallel without waiting for the prior event to complete.

```
bool _isLoaded = false;

  protected override async Task OnParametersSetAsync()
  {
      if (_isLoaded)
          return;
      _isLoaded = true;
      interation++;
      Debug.WriteLine($"OnParametersSetAsync, iteration: {interation}");

      await base.OnParametersSetAsync();
  }
```

**Comment by David-Moreira** [comment]
Hello @GaryWayneSmith Unfortunately the `OnParametersSetAsync` is apparently used on your own razor component and for some reason it keeps re-rendering I would say.
I'm not entirely sure the issue is with the `ModalProvider`. I have tried adding the following code to one of our test pages, and the `OnParametersSetAsync` only gets called once. When the page loads.
```

@page "/"
@inject IVersionProvider VersionProvider
@using System.Diagnostics

<h3>Full page edit dialog</h3>

<Button class="mt-3" Color="Color.Success" Type="ButtonType.Button" Size="Size.Small" @onclick="OnEditClick">Edit</Button>
<Button class="mt-3" Color="Color.Success" Type="ButtonType.Button" Size="Size.Small" @onclick="Save">Save</Button>
<Button class="mt-3" Color="Color.Success" Type="ButtonType.Button" Size="Size.Small" @onclick="Cancel">Cancel</Button>


@code {

    public class ModalResult<TResult>
    {
        public ModalResultType ResultType { get; private set; } = ModalResultType.NoSet;
        public TResult Data { get; set; } = default;

        public static ModalResult<TResult> OK() => new ModalResult<TResult>() { ResultType = ModalResultType.OK };
        public static ModalResult<TResult> Exit() => new ModalResult<TResult>() { ResultType = ModalResultType.Exit };
        public static ModalResult<TResult> Cancel() => new ModalResult<TResult>() { ResultType = ModalResultType.Cancel };
        public static ModalResult<TResult> OK( TResult data ) => new ModalResult<TResult>() { Data = data, ResultType = ModalResultType.OK };
        public static ModalResult<TResult> Exit( TResult data ) => new ModalResult<TResult>() { Data = data, ResultType = ModalResultType.Exit };
        public static ModalResult<TResult> Cancel( TResult data ) => new ModalResult<TResult>() { Data = data, ResultType = ModalResultType.Cancel };

        public enum ModalResultType { NoSet, OK, Cancel, Exit }
    }

    public class RequestModel
    {
        public int PageId { get; set; }
    }

    [Parameter] public RequestModel Request { get; set; } = default;
    [Parameter] public EventCallback<ModalResult<int>> OnDialogCompleted { get; set; }
    int interation = 0;

    protected override async Task OnParametersSetAsync()
    {
        interation++;
        Debug.WriteLine( $"OnParametersSetAsync, iteration: {interation}" );

        await base.OnParametersSetAsync();
    }

    protected async Task Save()
    {
        Debug.WriteLine( $"Save, iteration: {interation}" );
        await OnDialogCompleted.InvokeAsync( ModalResult<int>.OK( 22 ) );
    }
    protected async Task Cancel()
    {
        Debug.WriteLine( $"Cancel, iteration: {interation}" );
        await OnDialogCompleted.InvokeAsync( ModalResult<int>.Cancel() );
    }


    int Model = 0;

    [Inject] public IModalService ModalService { get; set; }
    private async Task OnEditClick()
    {
        await ModalService.Show<Counter>( "Edit Page",
            parameters =>
            {
                parameters.Add(x=> x.Value, 2 );
            },
            new ModalInstanceOptions()
                {
                    UseModalStructure = false,
                    Animated = false,
                }
        );
        Debug.WriteLine( "OnEditClick complete" );
    }

    // private async void OnEditDialogCompleted( ModalCustom.ModalResult<int> r )
    // {
    //     await ModalService.Hide();
    //     if ( r.ResultType == ModalCustom.ModalResult<int>.ModalResultType.OK )
    //     {
    //         if ( r.Data == 0 )
    //         {
    //             Debug.Write( "Invalid page returned" );
    //             return;
    //         }
    //         Model = r.Data;
    //         StateHasChanged();
    //     }
    // }
}

```
Can I ask that you provide a clear contained reproduceable of the issue?

**Comment by GaryWayneSmith** [comment]
[https://github.com/GaryWayneSmith/BlazoriseModalServiceTest](https://github.com/GaryWayneSmith/BlazoriseModalServiceTest)

I created a .Net 8 Razor application and included 3 files, the main page, a class for passing some data, and the modal dialog page I want to render. If I pass no parameters it only executes once (even though no parameters were set), otherwise it seems to hit 7 times usually.

```
OnEditClick complete
OnParametersSetAsync, iteration: 1
OnParametersSetAsync, iteration: 2
OnParametersSetAsync, iteration: 3
OnParametersSetAsync, iteration: 4
OnParametersSetAsync, iteration: 5
OnParametersSetAsync, iteration: 6
OnParametersSetAsync, iteration: 7
OnParametersSetAsync, iteration: 8
Save, iteration: 8
```

**Comment by stsrki** [comment]
I think this happens because you're using a reference type, and Blazor is not well suited for it. For Blazor to work best it must check for changes on parameters between renderings and with reference types it always default to true unless you implement proper equality overloads.

![image](https://github.com/Megabit/Blazorise/assets/900302/5a5e9ef3-f975-442d-a4f6-d2e75a8f8283)

---

You might try converting your `RequestModel` to a `record` type. That way, it will have equality overloads already implemented and should work. Let us know it it helps.

**Comment by GaryWayneSmith** [comment]
@stsrki,

You hit the nail on the head.  My problem OnParametersSetAsync isn't being called multiple times, it's SetParametersAsync being called multiple times.  Checking the documentation [MS Learn](https://learn.microsoft.com/en-us/aspnet/core/blazor/performance?view=aspnetcore-8.0) that the snipped was taken from mentions equality and ShouldRender.  I tried both of those and saw no improvement.  Though, that has other improvements that I will utilize for other thanks (thanks for the pointer to that).

This particular dialog razor element is recreated on each client.  Taking that into account I can override SetParametersAsync to check to see if the parameter has been set yet, and if not, set it and then call the base with ParameterView.Empty as the parameter.  Any additional calls to SetParametersAsync will return.

Taking this logic one step further, if I need to use this as an in-process dialog, I can put a more creative check to determine if that parameter has changed, update it, and then make the call to the base parameter.

Example of setting first call for an out-of-process dialog
```
    public override async Task SetParametersAsync(ParameterView parameters)
    {
        if (ModalParameters == null)
        {
            ModalParameters = parameters.GetValueOrDefault<ModalParameterModel<int>>(nameof(ModalParameters));
            await base.SetParametersAsync(ParameterView.Empty);
        }
    }
```

Example of setting if on change for an in-process dialog.  In this case, the ModalParameterModel<T> has to have it's own Equals override to determine if it's changed.  

```
    public override async Task SetParametersAsync(ParameterView parameters)
    {
        bool hasChange = false;
        foreach (var parameter in parameters)
        {
            switch (parameter.Name)
            {
                case nameof(ModalParameters):
                    ModalParameterModel<int> newVal = (ModalParameterModel<int>)parameter.Value;
                    if (newVal.Equals(ModalParameters))
                    {
                        continue;
                    }
                    ModalParameters = newVal;
                    hasChange = true;
                    break;
                default:
                    throw new ArgumentException($"Unknown parameter: {parameter.Name}");
            }
        }

        if (hasChange)
        {
            await base.SetParametersAsync(ParameterView.Empty);
        }
    }
```

Sorry, my parameter names changed from the source I provided.  We have been playing around with the use cases today and decided on a different name since it's doing something a little different.

The key to the first one is to use whatever was passed the first time.  The key to the second one is to check equality when you need it.
