### ISSUE TITLE
Disabled Days

### ISSUE THREAD

**Issue by chris-parker-bliss** [Megabit/Blazorise#5543]
I'm looking for a Blazor date-time picker to use for selecting delivery date on an eCommerce site. The problem is that as well as disabling particular _**dates**_ we also need to the ability to disable _**days**_ of the week (no post on Sundays).

Ideally I'd imagine this would work almost exactly the same as the existing `DisabledDates` attribute, but instead of an array of `DateTime` values it could take an array of `DayOfWeek` values.

**Comment by stsrki** [comment]
The problem with this function is that it is a JavaScript function. There is no easy way to translate C# function into JS. Or to invoke asyncrounous function from synchronous function in JS.

Back to your problem. We could add `DisabledDays` which would handle it internally by making use of flatpickr function. That could work easily.

**Comment by chris-parker-bliss** [comment]
That makes sense @stsrki, thanks for your response, sounds promising!

**Comment by stsrki** [comment]
https://github.com/Megabit/Blazorise/pull/5578
