### ISSUE TITLE
Ability to add vertical scrollbar to DataGrid table body

### ISSUE THREAD

**Issue by HeathU** [Megabit/Blazorise#555]
**Is your feature request related to a problem? Please describe.**
I would like to use the DataGrid but with a vertical scrollbar for the table body instead of paging. I have tried without success to adjust the height of the DataGrid tbody and add a vertical scroller. I was previously using Table, but hit the same issue.

**Describe the solution you'd like**
Extend the DataGrid to optionally add a vertical scrollbar.

**Comment by stsrki** [comment]
Not sure if I understood correctly. Do you mean like infinity scroll?

**Comment by HeathU** [comment]
GridData component has a fixed height, the header is fixed in position and the data rows are wrapped with a vertical scrollbar. Not specifically infinity scroll, but the same look.

**Comment by JamesWinstanley270** [comment]
I would also like to vote for this.
The table head stays fixed whilst the table body scrolls vertically. The DataGrid would require a fixed or maximum height. Similar to this:
https://demos.componentone.com/blazor/blazorexplorer/FlexGrid/Index

**Comment by HeathU** [comment]
@JamesWinstanley270 Yes, that's what I poorly explained. Having this feature on the DataGrid and standard Table would be wonderful. The DataGrid can be an overkill at times.

**Comment by stsrki** [comment]
I understand now. Since v0.9 is already packed I will schedule this for later.

**Comment by HeathU** [comment]
@stsrki Can you please include the change for both DataGrid and Table?

**Comment by stsrki** [comment]
@HeathU Of course. DataGrid is based on the Table so both of them will have this feature.

**Comment by Jinjinov** [comment]
I also need this feature.

I tried to modify the source of `Table` and `TableBody` to include css for `height` and `overflow: scroll` but I was not successful.

I am not very good with css - can anyone give me some advice or a link to an example?

**Comment by stsrki** [comment]
Already done with #2293

**Comment by JamesWinstanley270** [comment]
body {
			margin: 0;
			padding: 0;
		}

		table,
		td,
		tr {
			vertical-align: top;
			border-collapse: collapse;
		}

		* {
			line-height: inherit;
		}

		a[x-apple-data-detectors=true] {
			color: inherit !important;
			text-decoration: none !important;
		}
	

		@media (max-width: 620px) {

			.block-grid,
			.col {
				min-width: 320px !important;
				max-width: 100% !important;
				display: block !important;
			}

			.block-grid {
				width: 100% !important;
			}

			.col {
				width: 100% !important;
			}

			.col>div {
				margin: 0 auto;
			}

			img.fullwidth,
			img.fullwidthOnMobile {
				max-width: 100% !important;
			}

			.no-stack .col {
				min-width: 0 !important;
				display: table-cell !important;
			}

			.no-stack.two-up .col {
				width: 50% !important;
			}

			.no-stack .col.num4 {
				width: 33% !important;
			}

			.no-stack .col.num8 {
				width: 66% !important;
			}

			.no-stack .col.num4 {
				width: 33% !important;
			}

			.no-stack .col.num3 {
				width: 25% !important;
			}

			.no-stack .col.num6 {
				width: 50% !important;
			}

			.no-stack .col.num9 {
				width: 75% !important;
			}

			.video-block {
				max-width: none !important;
			}

			.mobile_hide {
				min-height: 0px;
				max-height: 0px;
				max-width: 0px;
				display: none;
				overflow: hidden;
				font-size: 0px;
			}

			.desktop_hide {
				display: block !important;
				max-height: none !important;
			}
		}
	




















 

























	
		
		
		
		
		
		
	
	
		
		
	


















	

		
			Sorry, I'm Out of Office
		

	











	
		
			Friday 18th June, returning Monday 5th July
		
	






	
		
			
				Thank you for your email.
			
		
		
			
		

		
			
				I am afraid I'm on annual leave and will not have access to my emails.
				Please forward any urgent queries to:
				Lucas Carlton - ***@***.*** and
				Lisa Masters - ***@***.***
			
		
		
			
		

		
			
				Regards,
				James Winstanley
			
		
	


















































	
		
			This was an automated email.
