### ISSUE TITLE
DataGrid: add ToODataString API to the ReadData

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#5550]
Add a new API that converts the `ReadData` state to OData URL query.

Use case:

```
private async Task OnReadData( DataGridReadDataEventArgs<Employee> e )
{
  var query = e.ToODataString();

  var result = await someApi.GetAll( query );
}
```

---

- https://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc371341779

Few examples:

- `https://services.odata.org/V4/Northwind/Northwind.svc/Employees/?$count=true&$select=FirstName`
- `https://services.odata.org/V4/Northwind/Northwind.svc/Employees/?$filter=contains(tolower(FirstName),%27C%27)&$count=true&$select=FirstName`

**Comment by David-Moreira** [comment]
@stsrki I've honestly never used OData, do you have a quick way to test this? At least if the syntax is correct according to the standard?
Also how widely is this really used? Blazorise exists for some time and I don't remember we ever get a question or feature request regarding this.

**Comment by stsrki** [comment]
A few links from our chat

- https://github.com/ZEXSM/OData.QueryBuilder
- https://learn.microsoft.com/en-us/odata/resources/tools
- https://services.odata.org/

The OData.QueryBuilder seems to have some tests.
