### ISSUE TITLE
Blazorise licence in ABPFramework

### ISSUE THREAD

**Issue by freebsensetips** [Megabit/Blazorise#5553]
if you gives some guide on this please ?

https://github.com/abpframework/abp/issues/19957

In documentation you wrote

Beginning from June, 2021, the Blazorise library has dual licenses; open source & commercial. Based on your yearly revenue, you may need to buy a commercial license

Is this correct ?

I followed link in docs, but there is no yearly revenue limit.
Basically there is only one limit - if projects are commercial or not.

If i noticed right then using ABPFramework is not free anymore for blazor commercial projects. Even if developer is freelancer.

**Comment by stsrki** [comment]
Hello @freebsensetips

The license quote that you mentioned is an older iteration of the SLA. We have changed the requirements last year, https://blazorise.com/news/2023-changes-to-blazorise-plans-and-licensing

While we did have 1M threshold in the past, it was too confusing. We got questions almost on a daily basis to clarify it. So we simplified it and removed some parts. The license is now required for all organizations, and for individuals it is still free.
