### ISSUE TITLE
[Bug]: InputMask and placeholder

### ISSUE THREAD

**Issue by imclint21** [Megabit/Blazorise#5560]
### Blazorise Version

latest

### What Blazorise provider are you running on?

None

### Link to minimal reproduction or a simple code snippet

N/a

### Steps to reproduce

`<InputMask ShowMaskOnFocus="false" ShowMaskOnHover="false" Mask="****-****-****" Background="Background.White" Placeholder="Enter HUID (e.g. hdc1-tst1-hcu1)" />`

### What is expected?

Shouldn't use placeholder as mask

### What is actually happening?

The placeholder become a mask it's totally wtf

**Comment by imclint21** [comment]
<img width="225" alt="image" src="https://github.com/Megabit/Blazorise/assets/5221349/50f080c0-c340-4083-9d7d-0db703a5ed56">

**Comment by stsrki** [comment]
Hello, I have reporter an issue on the inputmask repo to clarify if this is the right behavior.

**Comment by stsrki** [comment]
Ps. In case the inputmask placeholder correct as it should I think the best option forward is to introduce new `MaskPlaceholder` parameter that will be used for the inputmask, while an existing `Placeholder` will be used for an input element. But, this would be done in 1.6 as it is a new API.

**Comment by stsrki** [comment]
According to the maintainer from inputmask it seems that the behavior is as expected. Placeholder is working fine.

That means we will need to do some extra steps from our side to separate inputmask placeholder from input element placeholder.
