### ISSUE TITLE
CellStyling of datagrid is not exists

### ISSUE THREAD

**Issue by zandiarash** [Megabit/Blazorise#5571]
### Blazorise Version

1.5.3

### What Blazorise provider are you running on?

Bootstrap5

![image](https://github.com/Megabit/Blazorise/assets/10775073/b8398dfd-12e2-45fd-8e50-02b3cc7b4bfb)

There is a problem with CellStyling.  
Actually It seems there is no CellStyling attribute.

**Comment by stsrki** [comment]
The CellStyling is located on a DataGrid. That's why you don't see it.

The use case would be 

```razor
<DataGrid TItem="Employee"
  Data="@inMemoryData"
  CellStyling="@((item, Column, styling)=>styling.Style = "something" )">
```

**Comment by zandiarash** [comment]
> The CellStyling is located on a DataGrid. That's why you don't see it.
> 
> The use case would be
> 
> ```
> <DataGrid TItem="Employee"
>   Data="@inMemoryData"
>   CellStyling="@((item, Column, styling)=>styling.Style = "something" )">
> ```

Thank you dear @stsrki 
May you help me how to add a class instead of changing style ?
I mean something like this

```
<DataGrid TItem="Employee"
  Data="@inMemoryData"
  CellStyling="@((item, Column, styling)=>Column.Class = "something" )">
```

**Comment by David-Moreira** [comment]
The third argument is a styling dedicated class that can be used to customize:

![image](https://github.com/Megabit/Blazorise/assets/22283161/6f23d0a1-7978-4116-8718-2d8c5d4c5a99)

So in your example you would do 
```diff
- Column.Class = "something"
+ styling.Class = "something"
```

**Comment by zandiarash** [comment]
> The third argument is a styling dedicated class that can be used to customize:
> 
> ![image](https://private-user-images.githubusercontent.com/22283161/341962224-6f23d0a1-7978-4116-8718-2d8c5d4c5a99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNTI0NzQsIm5iZiI6MTcxOTA1MjE3NCwicGF0aCI6Ii8yMjI4MzE2MS8zNDE5NjIyMjQtNmYyM2QwYTEtNzk3OC00MTE2LTg3MTgtMmQ4YzVkNGM1YTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDEwMjkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NTU1ZWIzNGI2N2RiYWQ5YWNlNTAyZmI3NmY4NTBkMjk2NmI0ZGMxODQ2ZGYzNDkwNjQ3ZGUyMWVkNWMwYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UD7oML6-0RkOkGKvZeQ8hJOOnxITOnXln_4GWR9Yi4I)
> 
> So in your example you would do
> 
> ```diff
> - Column.Class = "something"
> + styling.Class = "something"
> ```

Thank you for the fast reply. :)
