### ISSUE TITLE
[Bug]: ColumnChooser is not aligned with pager

### ISSUE THREAD

**Issue by danik121** [Megabit/Blazorise#5587]
### Blazorise Version

1.5.3

### What Blazorise provider are you running on?

FluentUI2

### Link to minimal reproduction or a simple code snippet

Example from doc's

### Steps to reproduce

<DataGrid TItem="Employee"
          Data="inMemoryData"
          Responsive
          ShowColumnChooser
          ShowPager
          ShowPageSizes>
</DataGrid>

### What is expected?

ColumnChooser is not aligned with pager

### What is actually happening?
![image](https://github.com/Megabit/Blazorise/assets/8233518/e03cdd53-5d0c-42e4-8b7a-6c7fdb099eda)

example from demo:
![image](https://github.com/Megabit/Blazorise/assets/8233518/6deab508-870b-4184-8383-95c1a22d428a)

**Comment by David-Moreira** [comment]
@stsrki I know that I've worked on this feature, but weren't you the one that made that layout changes to the pager, and would probably be best suited to fix those correctly? I don't remember well what the changes were, but I think you'll probably be best acquainted, let me know if you still prefer that I take a look myself.

**Comment by stsrki** [comment]
@tesar-tech There is already an open PR for this so please try testing it first.
