### ISSUE TITLE
.srt subtitle files for video player

### ISSUE THREAD

**Issue by thumaman** [Megabit/Blazorise#5598]
Hi,

I noticed that .srt caption files are not working in your video player. The only captions that work are .vtt files. Does the player not have support for .srt files?

**Comment by stsrki** [comment]
I checked the plyr.js library, and it seems they are not supported. And based on their comments it will not be worked on.

The good thing is, their successor will support it, once it is released https://github.com/search?q=repo%3Avidstack%2Fplayer%20srt&type=code

**Comment by thumaman** [comment]
Great, thank you for the update.
