### ISSUE TITLE
Add more Styling options for ListView Itemtemplates

### ISSUE THREAD

**Issue by Mr-Pearce** [Megabit/Blazorise#5606]
In the docs it states that `Listview` uses `GoupList` under the Hood.

On `ListGroupItem`'s you can add Color, Padding Disabled and so on.

In the ListView ItemTemplate you cant use theese.

**Comment by stsrki** [comment]
I think this might be a good feature to have. Since ListView is a wrapper, we need to make these accessor as callbacks

**Proposal of use:**

`Disabled="@((item)=>item.Id > 100)"`

**Comment by stsrki** [comment]
@ddjerqq Would you do this? It seems easy enough.

**Comment by ddjerqq** [comment]
I could take this issue as well!

**Comment by ddjerqq** [comment]
I will assign myself to this issue, and work on the master branch, then make a PR
