### ISSUE TITLE
[Docs] Automate API documentation

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#5607]
Not a priority. However, we could investigate how to generate API documentation for each component. We could use XML comments for all needed information

- https://github.com/loxsmoke/DocXml

One problem I see with automation is that we don't know which public methods must be mentioned and which not. Not all public methods should be used by the user. We might add an additional comment to them, like "Should be used only internally", and then skip those.

**Comment by ddjerqq** [comment]
Could we use the [`[EditorBrowsable]`](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.editorbrowsableattribute?view=net-8.0) Attribute, and when generating docs, use reflection to filter out those members?

If we don't want the user to use those public methods anyway, we could hide them, so someone who does not know about their existence, will not use them.

**Comment by ddjerqq** [comment]
I see, what do we have more of? public methods that are internal Blazorise use only? or public methods that are for users only? 

we could use a custom xml element for marking our methods `BlazoriseInternal` maybe?
```cs
/// <summary>
/// Some method description
/// </summary>
/// <blazorise-internal/>
public void SomeMethod();
```

**Comment by ddjerqq** [comment]
how about [<critical>](https://learn.microsoft.com/en-us/archive/msdn-magazine/2019/october/csharp-accessing-xml-documentation-via-reflection#:~:text=critical%3A%20mark%20members%20that%20are%20critical%20for%20external%20projects%20and%20shouldn%E2%80%99t%20be%20edited)?

**Comment by stsrki** [comment]
My idea is to have a comment convention to indicate that the method is only for internal use. And then ae just filter out those.

```
/// <summary>
/// Some method description. Should not be used externaly. 
/// </summary>
public void SomeMethod();
```

This way we know what to filte. And the user knows that if they use it it could not work as expected. Because the same comment can show in intelisense.
