### ISSUE TITLE
DataGridSelectColumn not recording change

### ISSUE THREAD

**Issue by CD1010** [Megabit/Blazorise#561]
I have  grid as follows.  AccountTransactionView has a property called TargetAccount of type AccountView.  It is referenced in a DataGridSelectColumn.  See below.  When i change the value of the Target Account, it does not register the change.  The display template reverts to the original setting.  
Note that the Transactions collection is a List<AccountTransactionView>

Also, i tried using OnRowUpdated callback, but that is giving me the value of the column BEFORE it was changed.  
```
       public void OnRowUpdated(SavedRowItem<AccountTransactionView, Dictionary<string, object>> e )
        {
// This handler is fired after i hit the save button provided by internal edit functionality.
            AccountTransactionView view = e.Item;
            view.TargetAccount = e.Values["TargetAccount"] as AccountView; // This gives me old value. 
            StateHasChanged();

        } 
```

It seems the only way to get this to work is to change the column to reference a plain string with the display value in the combo box. I would rather not do that.

```
 <Blazorise.DataGrid.DataGrid @ref="RegisterGrid" TItem="AccountTransactionView" Data="@Transactions" PageSize="100" ShowCaptions="true" ShowPager="true" IsBordered="true" IsStriped="true" 
                                                         
                                                         @bind-SelectedRow="@SelectedRow" Editable="true" UseInternalEditing="true" EditMode="DataGridEditMode.Inline" RowUpdated="@OnRowUpdated">
                                <DataGridCommandColumn TItem="AccountTransactionView" />
                                <Blazorise.DataGrid.DataGridColumn TItem="AccountTransactionView" Field="@nameof(AccountTransactionView.TransactionDate)" Caption="Date" Editable="true"></Blazorise.DataGrid.DataGridColumn>
                                <Blazorise.DataGrid.DataGridColumn TItem="AccountTransactionView" Field="@nameof(AccountTransactionView.Description)" Caption="Description" Editable="true"></Blazorise.DataGrid.DataGridColumn>

                               <DataGridSelectColumn TItem="AccountTransactionView" CellsEditableOnEditCommand="true" Field="@nameof(AccountTransactionView.TargetAccount)"  Caption="Category" Editable="true" >
                                    <DisplayTemplate>
                                        @{
                                            var targetname = (context as AccountTransactionView)?.TargetAccount.Name;

                                            @targetname
                                        }
                                    </DisplayTemplate>
                                    <EditTemplate>
                                        @{ 
                                           
                                           <SelectEdit TValue="AccountView"  SelectedValue="@((AccountView)(((CellEditContext)context).CellValue))" SelectedValueChanged="@(v => OnSelectedValueChanged(v))" >
                                                                                     
                                            @foreach (var acct in Accounts)
                                            {

                                                <SelectItem TValue="AccountView" Value="@(acct)">@acct.Name</SelectItem>

                                            }
                                        </SelectEdit>
                                            }
                                    </EditTemplate>
                                </DataGridSelectColumn>

                                <Blazorise.DataGrid.DataGridColumn TItem="AccountTransactionView" Field="@nameof(AccountTransactionView.DebitTotal)" Caption="Debit">
                                    <DisplayTemplate>
                                        @($"{(context as AccountTransactionView)?.DebitTotal.ToString("C")} ")
                                    </DisplayTemplate>
                                    <EditTemplate>
                                        <NumericEdit TValue="decimal" Value="@((decimal)(((CellEditContext)context).CellValue))" ValueChanged="@(v=>((CellEditContext)context).CellValue=v)" />
                                    </EditTemplate>
                                </Blazorise.DataGrid.DataGridColumn>
                                <Blazorise.DataGrid.DataGridColumn TItem="AccountTransactionView" Field="@nameof(AccountTransactionView.CreditTotal)" Caption="Credit">
                                    <DisplayTemplate>
                                        @($"{(context as AccountTransactionView)?.CreditTotal.ToString("C")} ")
                                    </DisplayTemplate>
                                    <EditTemplate>
                                        <NumericEdit TValue="decimal" Value="@((decimal)(((CellEditContext)context).CellValue))" ValueChanged="@(v=>((CellEditContext)context).CellValue=v)" />
                                    </EditTemplate>
                                </Blazorise.DataGrid.DataGridColumn>
                                <Blazorise.DataGrid.DataGridColumn TItem="AccountTransactionView" Field="@nameof(AccountTransactionView.Balance)" Caption="Balance">
                                    <DisplayTemplate>
                                        @($"{(context as AccountTransactionView)?.Balance.ToString("C")} ")
                                    </DisplayTemplate>
                                    <EditTemplate>
                                        <NumericEdit TValue="decimal" Value="@((decimal)(((CellEditContext)context).CellValue))" ValueChanged="@(v=>((CellEditContext)context).CellValue=v)" />
                                    </EditTemplate>
                                </Blazorise.DataGrid.DataGridColumn>

                            </Blazorise.DataGrid.DataGrid>
```

**To Reproduce**
1) Click edit to edit a row.  
2) Change the value in the combo box.
3) Hit save.
4) Value shown is previous value, not what was selected.  OnRowUpdated returns the old value also.

**Expected behavior**

New value should be saved to combo box.

**Comment by stsrki** [comment]
Hi @CD1010, can you create a test repository where I can test the behavior?

**Comment by CD1010** [comment]
CD1010/BlazoriseGridSample


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
CD1010/BlazoriseGridSample

Weather Forecast using Blazorise. Contribute to CD1010/BlazoriseGridSample development by creating an account on...
 |

 |

 |


I made a sample. Click edit, change city and hit save.  It loses setting.  Other fields retain change.
Thanks. Hope this helps.
Nice work with this library by the way.

    On Monday, February 3, 2020, 09:53:49 AM EST, Mladen Macanović <notifications@github.com> wrote:  
 
 
Hi @CD1010, can you create a test repository where I can test the behavior?

**Comment by Riedi2070** [comment]
I've been exacting the same problem with the editable `SelectColumn`. When edit the select field in a `DataGrid` and save the row, the changed value in c# is null. Other simple `TextEdit` values are passing with value correctly.

**Comment by vamsitp** [comment]
FWIW - I see an issue with _Save_ when Columns with **nested** fields (e.g. `ClassA.ClassB.PropB`) are marked `Editable="true"`. If I mark these fields as Editable="false", other normal fields that are Editable (e.g. `ClassA.PropA`) reflect the changes correctly... Not sure if this behavior was there since before, but I see it in v0.9.3.

**Comment by David-Moreira** [comment]
@stsrki can I take a look at this one? Assign if so.

**Comment by stsrki** [comment]
@David-Moreira assigned!

**Comment by David-Moreira** [comment]
Version of the Blazorise on the repo provided is 0.8.8.2.
Component used: `SelectEdit`
The problem is not with the Datagrid itself, but with Select component not supporting complex objects binding. 
This would be the temporary fix for you, while keeping the complex object bound to the Column. I know it isn't pretty, but what matters is that it works! Let me know if this helps...
```
        <EditTemplate>
                <Blazorise.SelectEdit TValue="int" SelectedValue="@((int)((City)(((CellEditContext)context).CellValue)).Id)" SelectedValueChanged="@( v => ((CellEditContext)context).CellValue = Cities.First(x=> x.Id == v))">
                    @foreach (var item in Cities)
                    {

                        <SelectItem TValue="int" Value="@(item.Id)">@item.Name</SelectItem>
                    }
                </Blazorise.SelectEdit>
        </EditTemplate>
```

@stsrki we've had this issue with our users a few times, can we consider opening an issue to solve this by handling complex types internally.
What I think we need:
- Data Source
- We build the Select Options ourselves internally
- We would basically be computing a hash of each of the items to track the currently selected item, by providing the hash value as the value of the Select Options.
- It's pretty much the example above, but the developer wouldn't need to code this "jargon", only bind DataSource of TValue + Desired TValue which could now be a complex type.

You can also assign this one to me if you agree with the proposed solution. Or just let me know if you have a different idea.

**Comment by stsrki** [comment]
I don't want to handle hash tables internally for select options. What if people would want to use JavaScript to read the real value of the select option? That would be impossible if some internal key is used.

Usually, I've seen that people recommend using [TypeConverterAttribute ](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.typeconverterattribute?view=netstandard-2.1) for complex values. Other than that I already have a plan to include _conversion API_  for input components. The guys at MudBlazor have a similar concept.

**Comment by David-Moreira** [comment]
> I don't want to handle hash tables internally for select options. What if people would want to use JavaScript to read the real value of the select option? That would be impossible if some internal key is used. 
- Could also make it so, reference types are restricted to a certain interface, where they would have to provide their unique hash mechanism. So they would be aware of it.

> Usually, I've seen that people recommend using TypeConverterAttribute for complex values. Other than that I already have a plan to include conversion API for input components. The guys at MudBlazor have a similar concept.
- I see, I've never used this TypeConverter before, but the idea here, is about the same above, right? Make the user provide the hashing mechanism?

I could also potentially take a look at this. But it seems you already have something in the works, so just let me know if you need any help.
