### ISSUE TITLE
Change type of ChartStreamingOptions.Delay from int? to long?

### ISSUE THREAD

**Issue by technyon** [Megabit/Blazorise#5615]
**Is your feature request related to a problem? Please describe.**
I use the chart streaming plugin to display historical data. The streaming plugin assumes that data is live data with timestamps from now. For my use case this isn't a valid assumption, and I'm using the ChartStreamingOptions.Delay property to work around this. I know this property isn't exactly meant for this, but it works. For example, for my test data, I'm shifting the currently displayed data back by 41 days to May 30th. The problem is that the Delay property expects milliseconds, and being an int32 value it can only represent up to 28 days. I've worked around this limitation by inheriting from ChartStreamingOptions and redefining the Delay property using the new keyword as "long?".

**Describe the solution you'd like**
My workaround described above isn't exactly clean. A better solution would be to change the type of the Delay property from int? to long? chartjs at this point seems to have no problems processing 64 bit values.

### Additional context
-

**Comment by stsrki** [comment]
It seems like a simple change, so we might do it in 1.5.

**Comment by ddjerqq** [comment]
I will take care of this! 

ps. sorry source generation is taking long

**Comment by ddjerqq** [comment]
should I work on the 1.5 branch for this issue?
