### ISSUE TITLE
Add MultiSelection to Datagrid SelectColumn

### ISSUE THREAD

**Issue by Mr-Pearce** [Megabit/Blazorise#5619]
**Is your feature request related to a problem? Please describe.**
Currently you cannot select multiple entries in the `DatagridGridSelectColumn`

**Describe the solution you'd like**
A Solution would be to add a `Multiple` mode from like https://blazorise.com/docs/extensions/selectlist
so we could select multiple entries.

**Comment by blenke** [comment]
I proposed something like this earlier, would be a great addition. 
See https://github.com/Megabit/Blazorise/issues/5455
Also because the custom filter requires additional code if you want to save and read the state of the datagrid.

**Comment by stsrki** [comment]
We have multiple selection mode. Check the docs https://blazorise.com/docs/extensions/datagrid/selection/multiple

**Comment by blenke** [comment]
I think that is different, that is for selecting multiple rows. The multi select we propose is for the select filter, now you can only select one value from the dropdown menu. What we looking for is that we can select 2 or more values so that a column gets filtered on that (its a bit like in Excel) .

**Comment by Mr-Pearce** [comment]
Yes I meant the filter.
Currently you can only select one from the select.
But multiple like in my example link would be nice.
So we could filter for e.g. multiple states and so on

**Comment by stsrki** [comment]
@David-Moreira can you help?

**Comment by David-Moreira** [comment]
I think it makes sense, the problem is that we currently do not support multiple values filtering. Our internals are just not yet made for it.

Similar request was made where user wanted a range of values : 
https://github.com/Megabit/Blazorise/issues/5586

**Comment by blenke** [comment]
Ok, that part wasn't clear to me. Hopefully you can put this on the wish list for a future version. I can use my custom implementation but it got more complicated with the datagrid state management.

**Comment by stsrki** [comment]
> I think it makes sense, the problem is that we currently do not support multiple values filtering. Our internals are just not yet made for it.
> 
> Similar request was made where user wanted ~a range of values~ to be able to define 2 filter values that would represent the start and end for a **date between** filter: #5586

How hard would it be to do it for 1.6? We still have some time left.

**Comment by David-Moreira** [comment]
I have to investigate. I'll let you know.

**Comment by David-Moreira** [comment]
> > I think it makes sense, the problem is that we currently do not support multiple values filtering. Our internals are just not yet made for it.
> > Similar request was made where user wanted ~a range of values~ to be able to define 2 filter values that would represent the start and end for a **date between** filter: #5586
> 
> How hard would it be to do it for 1.6? We still have some time left.

hmm I think we need to introduce a list of search values, that if exist will be taken into consideration when searching.

Since we don't really want to be touching on the existing API I'd probably add 
```
    /// <summary>
    /// Gets or sets the filter values.
    /// </summary>
    public List<object> SearchValues { get; set; }

    public void TriggerFilterChange( params object values )
    {
    SearchValues ....
    SearchValuesChanged...

    }
```
![image](https://github.com/user-attachments/assets/3419b7dc-dd60-4623-933c-a1561d47ce92)
It's a bit duplicated, but retro compatibility is a must so... Might not be too hard, basically just propagate it everywhere SearchValue currently exists, and change the Filtering to handle multiple values?

**Comment by stsrki** [comment]
Seems good. Create the PR, and I'll see how it behaves.

**Comment by stsrki** [comment]
Can existing `SearchValue` be used to store a `List<>` object type? So that we don't need to introduce new SearchValues just for this usecase.

**Comment by David-Moreira** [comment]
> Can existing `SearchValue` be used to store a `List<>` object type? So that we don't need to introduce new SearchValues just for this usecase.

I think that might break too much stuff for users. I would do that in a 2.0.

**Comment by stsrki** [comment]
@David-Moreira, what do you think? How much would it take you for this?
