### ISSUE TITLE
DataGrid.SelectedRow doesn't work - what am I doing wrong?

### ISSUE THREAD

**Issue by Zapan2006** [Megabit/Blazorise#5621]
Running even the default example of a DataGrid won't trigger the SelectedRow. No visual selected row, no events triggered.
Obviously I'm doing something wrong, since nobody else is complaining.
I've tried with Bootstrap 5 and Material.
I've tried with Safari and Chrome.
Data is visual as expected

example:
```
<DataGrid TItem="Employee"
          Data="@employeeList"
          RowSelectable=@((x)=> x.Item.FirstName != "John")
          Responsive>
    <DataGridColumn Field="@nameof( Employee.FirstName )" Caption="Name" Editable="false"></DataGridColumn>
</DataGrid>
@code{
     class Employee{public string FirstName { get; set; }}
    private List<Employee> employeeList = new() { new() { FirstName = "David" }, new() { FirstName = "MLaden" }, new() { FirstName = "John" }, new() { FirstName = "Ana" }, new() { FirstName = "Jessica" } };
}
```

**Comment by David-Moreira** [comment]
Hello @Zapan2006 
what exactly are you trying to do? This particular example has a `RowSelectable` condition.
`RowSelectable=@((x)=> x.Item.FirstName != "John")`

Have you tried removing it completely?

**Comment by Zapan2006** [comment]
Found the problem.
`@rendermode InteractiveServer` has to be found in Routes.razor for a .Net 8 project.
It turned out that no events where triggered.

**Comment by David-Moreira** [comment]
Right, we have a dotnet 8 enabled template if you need.
https://blazorise.com/docs/templates
