### ISSUE TITLE
LicenseChecker is null problem

### ISSUE THREAD

**Issue by omerozulku** [Megabit/Blazorise#5624]
I’m developing my component library based on blazorise such as library project. 

I add reference this library to my blazor server app project. I’m developing chart componet on class library.

When I use this component on server app project I take an exception like blazoriselicensechecker is null. 

But I give my blazorise token to blazorise service config in server app program.cs. 

How can I send my license info to class library?

**Comment by stsrki** [comment]
Hello @omerozulku 

How do you use Blazorise in your project? Usually, all you need to do is register all internal Blazorise services by calling:

```cs
builder.Services
    .AddBlazorise()
    .AddBootstrap5Providers();
```

Also, can you tell us more about your project, and how you plan to create your own component library?

**Comment by omerozulku** [comment]
I register all service blazorise like this:

`builder.Services
    .AddBlazorise(options =>
    {
        options.ProductToken = "******"
        options.Immediate = true;
    })
    .AddBootstrap5Providers()
    .AddFontAwesomeIcons()
    .AddLoadingIndicator();`

I have 2 project such as one project blazor server app, one project class library. I am developing my own blazor component by using blazorise. 

I add class library to blazor server app project like project reference. 

I register all blazorise service in blazor server app project. If ı use blazorise chart object in my blazor server app project there is no problem but when I use blazor chart object in component (class library) project and reference my own component based on blazorise chart I take error (blazorise license checker is null).

1-) Blazor Server App
![image](https://github.com/user-attachments/assets/a08578b6-c944-4516-90fb-0b95ab3a7858)

2-) Class Library (I add razor component to this project for use other server app project)
![image](https://github.com/user-attachments/assets/9eebfb69-a455-4c85-9e49-6e84bd163ea7)

3-) Blazor server app service registering
![image](https://github.com/user-attachments/assets/3189d044-b92e-418b-a27e-67f52de027d9)

**Comment by David-Moreira** [comment]
Hello @omerozulku we've patched this particular check where it makes the best effort to not throw any exception related to this particular service missing, it will be live on v1.6.1

https://github.com/Megabit/Blazorise/pull/5648

I am closing this for now, feel free to reopen if the problem persists.
