### ISSUE TITLE
[Bug]: Theme Generator registered as Singleton is not thread safe

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#5628]
### Blazorise Version

1.2.3

### What Blazorise provider are you running on?

Bulma

### Link to minimal reproduction or a simple code snippet

https://blazorise.com/support/issues/205#comment_2057

User reported this issue in v.1.2.3 but I believe this issue might still be on latest Blazorise.

Also the registration is not consistent most of the theme generators are scoped, but there are two registered as a singleton, is there a reason for this?
![image](https://github.com/user-attachments/assets/fc154869-7a03-4c46-b2d5-f0c9d887c931)

### Steps to reproduce

See Minimal repro

### What is expected?

Thread safety

### What is actually happening?

![image](https://github.com/user-attachments/assets/706480b3-223c-4742-b6c2-303fbdea0f5d)

**Comment by David-Moreira** [comment]
@stsrki 
Please let me know if you have any comments about this.

**Comment by stsrki** [comment]
I can only assume that we have accidentally left them as Singleton for Bulma. And when I copied some files from Bulma over to Fluent provider it also got incorrectly registered.

It should be defined as Scoped in all cases.

**Comment by David-Moreira** [comment]
> I can only assume that we have accidentally left them as Singleton for Bulma. And when I copied some files from Bulma over to Fluent provider it also got incorrectly registered.
> 
> It should be defined as Scoped in all cases.

Ok then the fix is probably very easy in that case. 

**Singleton + Concurrent Dictionary** could probably be a decent option and more performant (not sure, we'd have to test), since indeed a ThemeGenerator is "global" is it not?

**Comment by stsrki** [comment]
It should be global per user session. So Scoped.

PS. I remember we did a ThemeCache while back. One of the community members created it to have cached themes to not slow down their server. Maybe that is causing the issue?

**Comment by David-Moreira** [comment]
> It should be global per user session. So Scoped.

Ok so it's just wrong, let's just fix it.
Whatever it is in the code, should be fixing by just using scoped anyway, since otherwise we'd have way more complaints about this.

**Comment by danik121** [comment]
@stsrki @David-Moreira It is fixed for 1.6 version? because I have the problem on version 1.6.0
![e50b1223-6e52-4975-948c-462a82aa8773](https://github.com/user-attachments/assets/8f2d563e-77f3-46e2-8612-e87267b66ad3)

**Comment by stsrki** [comment]
Hello @danik121 

Yes, this is already in 1.6 release, https://github.com/Megabit/Blazorise/pull/5652/commits/62498c3b814aa540920caa8468c89fce13a2c00f
