### ISSUE TITLE
[Bug]: Bootstrap 5: ColumnSize uses wrong css class

### ISSUE THREAD

**Issue by XanderStoffels** [Megabit/Blazorise#5630]
### Blazorise Version

1.5.3

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction or a simple code snippet

```html
<Grid>
      @foreach (var i in Enumerable.Range(0, 10))
      {
          <Column ColumnSize="ColumnSize.Is12.Is6.OnDesktop">
              <Card>
                  <CardBody>
                      <CardTitle Size="3">Hello</CardTitle>
                      <CardText>Lorem...</CardText>
                  </CardBody>
              </Card>
          </Column>
      }
</Grid>
```

### Steps to reproduce

Please run the above code.

### What is expected?

The classes `col-12` and `col-md-6` should be applied to each div under the `<Grid>`.

### What is actually happening?

Classes `g-col-12 g-col-md-6` are being applied. I cannot seem to find these classes in the Bootstrap 5 docs. When inspecting in chrome, there is no CSS behind these classes. No CSS is being applied; the elements take the full width regardless of screen size.

Will produce HTML that looks like this:
```html
<div class="grid">
    <div class="g-col-12 g-col-md-6">
        <div class="card">
        ...
        </div>
    </div>
    <div class="g-col-12 g-col-md-6">
        <div class="card">
        ...
        </div>
    </div>
...
</div>
```

### What browsers do you see the problem on?

Chrome, Microsoft Edge

**Comment by stsrki** [comment]
This is the expected behavior. When you place `<Column>` in a Grid, it uses the CSS grid system. If you want to have regular columns, replace the `<Grid>` with the `<Row>` component.

**Comment by stsrki** [comment]
No, you're perfectly fine with using both when and where needed. They both serve different purposes. You can learn about them in the official BS5 documentation and see the differences.

- https://getbootstrap.com/docs/5.3/layout/grid/
- https://getbootstrap.com/docs/5.3/layout/css-grid/

**Comment by stsrki** [comment]
> > CSS Grid is opt-in. Disable the default grid system by setting $enable-grid-classes: false and enable the CSS Grid by setting $enable-cssgrid: true. Then, recompile your Sass.
> 
> Is this something I have to do or is supposed to be set automatically when using Blazorise with Bootstrap 5?

By default, we bring the CSS grid classes to Blazorise. So you don't need to build new Bootstrap 5 CSS manually.

**Comment by XanderStoffels** [comment]
Thanks for your reply. So, it should work out of the box then, right? I fail to see what I did wrong in my code example. I used a `Grid` with `Columns` like in the code examples, but it does not seem to work.

**Comment by stsrki** [comment]
The generated classes should be applied. Do you have the following in your project defined?

`<link href="_content/Blazorise.Bootstrap5/blazorise.bootstrap5.css" rel="stylesheet" />`

**Comment by David-Moreira** [comment]
Hello,
An easy way to troubleshoot where you are doing something wrong is to get quickly started with one of our templates to try your code. https://blazorise.com/docs/templates

If it works on the template, it's most likely a missing resource/configuration and you can just compare your project with the template to see what's missing. Also you can just go over the https://blazorise.com/docs/start and https://blazorise.com/docs/usage/bootstrap5/ to make absolutely sure you got everything right.
If it doesn't then, in that case, there could be a possibility something is indeed wrong.

**Comment by XanderStoffels** [comment]
Thanks all of you for the helpful links. I'll close this issue and investigate a bit more. If the problem persists, I will reopen.
