### ISSUE TITLE
TransferList binding to Items

### ISSUE THREAD

**Issue by blenke** [Megabit/Blazorise#5631]
### Blazorise Version

1.5.3

### What Blazorise provider are you running on?

Bootstrap 5

### Link to minimal reproduction or a simple code snippet

Not sure if this a bug or a feature, but if I fill the Items and only want to know the items that appear in the listEnd (or listStart) and thus do not include a bind to one of these then the Items list will be changed by the TransferList component. Following the web site example you can see the behaviour:
```
<TransferList TItem="string"
              Items="@list"
              SelectionMode="ListGroupSelectionMode.Single"
              Mode="ListGroupMode.Selectable"
              Scrollable=false
              ShowMoveAll=false
             
              @bind-ItemsEnd=@listEnd
              ValueField="item => item"
              TextField="item => item">
</TransferList>

<br />
<b>list:</b>
@foreach (string s in list)
{
    @(s + ",")
}


@code {
    private List<string> list = new List<string> { "Apple", "Banana", "Cherry", "Grapes", "Orange", "Pear", "Strawberry" };
    
    private List<string> listEnd;
}
```

### Steps to reproduce

Move items from start to end and observe that the input Items list is changed

### What is expected?

The Items list should not be changed, the result should be in ItemsStart and ItemsEnd only

### What is actually happening?

Items moved to ItemsEnd are removed from Items. It is problematic because I used this in a modal and want the user to be able to OK/Cancel the selection. If they Cancel then the Items have changed. Its odd that the Items are changed especially when no @bind-Items is defined.

**Comment by David-Moreira** [comment]
Hello @blenke If I understand correctly your complaint is that `Items="@list"` gets mutated, correct?

For a quick workaround I recommend just copying a new list and allocating it to `Items="@copyList"`.

We'll take a look at why the collection is being mutated in that way and if it's intended or not. On first look it seems like it is not an intended behavior.

**Comment by blenke** [comment]
Indeed it gets mutated. I just added the ItemsStart but not use it and the problem was resolved but it took me some time to figure out what was wrong. If it is intended behavior then i would suggest to update the documentation.

**Comment by David-Moreira** [comment]
Thanks for your help. We'll let you know.
