### ISSUE TITLE
[Bug]: Validation is still not working for NumericPicker

### ISSUE THREAD

**Issue by danik121** [Megabit/Blazorise#5637]
### Blazorise Version

1.6

### What Blazorise provider are you running on?

FluentUI2

### Link to minimal reproduction or a simple code snippet

fixed in : https://blazorise.com/support/issues/204/validation-is-not-working-for-numericpicker
but not for version 1.6

### Steps to reproduce

Validation with numeric picker

### What is expected?

Input is red

### What is actually happening?

Input stay black

**Comment by stsrki** [comment]
Can you try clearing the browser cache?

Also, how do you define your `blazorise.fluentui2.css` file? it usually helps to have a query strings between versions. Change:

```html
<link href="_content/Blazorise.FluentUI2/blazorise.fluentui2.css" rel="stylesheet" />
```

Into

```html
<link href="_content/Blazorise.FluentUI2/blazorise.fluentui2.css?v=1.6.0.0" rel="stylesheet" />
```
