### ISSUE TITLE
Add TextOverflow Properties to Datagrid Columns

### ISSUE THREAD

**Issue by Mr-Pearce** [Megabit/Blazorise#5656]
Currently you cannot Truncate the Text fields inside DataGridColumns.

It would be nice if you could set it on table level like the Text Component has.

On Tables with much data you could set a "easy scroll" function so that every row is equal in size and rows with much data won't expand.

**Comment by stsrki** [comment]
It should be an easy thing to do. Going on the 1.7 milestones.
