### ISSUE TITLE
[Bug]: Autocomplete issues when Cropper is used

### ISSUE THREAD

**Issue by DaveAPerry** [Megabit/Blazorise#5677]
### Blazorise Version

1.5.4 (Also verified on 1.6.0)

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction or a simple code snippet

https://github.com/DaveAPerry/WASMHyphenTest

### Steps to reproduce

1. Navigate to the Counter Page
2. Type in the autocomplete component - unable to use +/- characters

### What is expected?

Autocomplete component should function normally and accept valid inputs

### What is actually happening?

Autocomplete does not accept + or - characters from the keyboard

### What browsers do you see the problem on?

Microsoft Edge

### Any additional comments?

We recently used the Cropper component on one of our internal applications - a couple weeks after deployment we were notified that the user could not use - in the autocomplete when looking for a specific value containing a "-" character.

**Comment by mtbayley** [comment]
Further to this, you can recreate the issue by browsing to https://blazorise.com/docs/extensions/cropper
Then select the autocomplete from the sidebar menu.

**Comment by DaveAPerry** [comment]
Though we encountered this issue with an autocomplete - it seems that it's present on any text input component.

**Comment by David-Moreira** [comment]
Hello,

The **main issue** stems from `Cropper` stealing the control of **+ and -** buttons for the zoom feature.
If you're not making use of this feature, or any keyboard controls for that matter, you can disable both the `Zoomable` and `Keyboard` with:
`SelectionOptions="@(new CropperSelectionOptions { AspectRatio = new(ratio), Zoomable = false, Keyboard = false })"`

Unfortunately just disabling `Zoomable` does not seems to solve the issue, as it seems it still steals +/- control.

Then a **second issue** that @mtbayley identified, if the Cropper is disposed, then we'd expect that any events, etc would be disposed also, so even if the library took control of the **+ and -** buttons when it was active, once it was disposed, it should give these back.

Hopefully the workaround will be ok for now.

- For the main issue, we'll need to figure out whether the maintainer of the underlying js library we use for `Cropper` (`cropper.js`) is aware of this 'bug' or limitation and figure out how we can tackle this issue.
- For the second issue, we'll be checking if we are disposing correctly of `Cropper` in Blazorise, if we are, then we also need to ask the maintainer if there's some extra clean up that should be done on `cropper.js`

**Comment by David-Moreira** [comment]
Reopening issue as merged PR does not fully solve this.

**Comment by stsrki** [comment]
So, are we waiting for the fix on the cropper.js side? Should we raise the fixed PR on their side as well?

**Comment by David-Moreira** [comment]
> So, are we waiting for the fix on the cropper.js side? Should we raise the fixed PR on their side as well?

Can you explain what do you mean by this? --> Should we raise the fixed PR on their side as well?

I have already opened an issue other their side (which is linked on the comment above) which explains the possible need to cleanup on their side as again, even though we call .destroy, the + and - are still unusable from my tests.

**Comment by stsrki** [comment]
I meant to fork their repo, fix the issue in their code, and then submit the official PR.

**Comment by David-Moreira** [comment]
> I meant to fork their repo, fix the issue in their code, and then submit the official PR.

Well, if you want to put hours into that. I'm fine, the problem as usual with external dependencies is that I don't whether they are active or not it seems they haven't been in the past 2 months. What if we work on it and no answer... :) Or do you mean to just use the forked version for the meantime?

**Comment by stsrki** [comment]
My long-term plan is to support third-party dependencies that we use, start submitting fixes, and add features. 

If we take Bulma as an example. We often have to implement missing features in our CSS providers that have to bring it up to the same level as other CSS providers like Bootstrap. Making it on Bulma's side will allow us to remove that code from our side, and in turn, they will officially support it. It's a win.

Same with this. If we fix it in cropper.js it is officially supported. If not, we still have to fix it and use it from the forked version.

**Comment by David-Moreira** [comment]
> support third-party dependencies that we use
> If not, we still have to fix it and use it from the forked version.

This answers my question. Let's try and work on a fix ourselves.
I don't remember if I have permissions at org level. Please fork it over under our org, if you have time.

**Comment by stsrki** [comment]
Here it is https://github.com/Megabit/cropperjs

I think the code is on their `v2` branch.

**Comment by DaveAPerry** [comment]
> Hello,
> 
> The **main issue** stems from `Cropper` stealing the control of **+ and -** buttons for the zoom feature. If you're not making use of this feature, or any keyboard controls for that matter, you can disable both the `Zoomable` and `Keyboard` with: `SelectionOptions="@(new CropperSelectionOptions { AspectRatio = new(ratio), Zoomable = false, Keyboard = false })"`
> 
> Unfortunately just disabling `Zoomable` does not seems to solve the issue, as it seems it still steals +/- control, so you'll also have to disable `Keyboard`
> 
> Then a **second issue** that @mtbayley identified, if the Cropper is disposed, then we'd expect that any events, etc would be disposed also, so even if the library took control of the **+ and -** buttons when it was active, once it was disposed, it should give these back.
> 
> Hopefully the workaround will be ok for now.
> 
> * For the main issue, we'll need to figure out whether the maintainer of the underlying js library we use for `Cropper` (`cropper.js`) is aware of this 'bug' or limitation and figure out how we can tackle this issue.
>   
>   * [Plus ('+') and Minus ('-') keyboard keys are bound to cropper and can't be used elsewhere fengyuanchen/cropperjs#1192](https://github.com/fengyuanchen/cropperjs/issues/1192)
> * For the second issue, we'll be checking if we are disposing correctly of `Cropper` in Blazorise, if we are, then we also need to ask the maintainer if there's some extra clean up that should be done on `cropper.js`
>   
>   * [Cropper: Properly destroy and unregister events #5681](https://github.com/Megabit/Blazorise/pull/5681)

Thanks David - this will solve our problem in the meantime. Setting Keyboard to false in the Selection options was enough to enable the +/- keys for text entry.

**Comment by stsrki** [comment]
We can make `Zoomable = false, Keyboard = false ` as defaults. So that are an opt-in feature.

**Comment by DaveAPerry** [comment]
I think you can leave Zoomable enabled - setting `Keyboard = false` was enough to resolve the issue for me. Zooming in/out with the scroll wheel still works as expected.

**Comment by David-Moreira** [comment]
> Here is a quick solution: **Call [`event.stopPropagation()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation) when key down on the input element.**
> 
> For example:
> 
> ```
> <input type="text" onkeydown="onKeydown" >
> ```
> 
> ```js
> function onKeydown(event) {
>   event.stopPropagation();
> }
> ```

Workaround provided by maintainer

**Comment by stsrki** [comment]
I can see the commit on cropperjs, https://github.com/fengyuanchen/cropperjs/commit/af97972366a5a7f5d47343a6e23198ffffc728c6, which means we can just update our version.

**Comment by David-Moreira** [comment]
Yes, unfortunately, he seems like the maintaner didn't take a look at the event disposal, but we've implemented disposal on our side. So by just updating it should fix the main issue.
