### ISSUE TITLE
Make a serialization object for JS interops

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#5701]
> > > Make a serialization object with the first letter in lowercase. This ensures that we get appropriately named JSON objects in case users have different JSON serialization settings. Unlikely but you never know.
> > 
> > 
> > You touch on an important point here. We should not rely on anything external or conventions. We should precisely define how our own stuff gets serialized so it can't fail due to external conditions. Is this not possible?
> 
> Well, we could introduce internal serialization class objects that make use of `JsonPropertyNameAttribute` to strongly type the name of the field. That way, it would be 100% right.

Yes. If we care about it. That's a way to go I guess, not doing guess work and hoping nothing external happens in my opinion.

_Originally posted by @David-Moreira in https://github.com/Megabit/Blazorise/issues/5691#issuecomment-2294976305_

**Comment by David-Moreira** [comment]
> There is no magic setting in System.Text.Json that can change that globally and this convention will hardly change...

@tesar-tech if I remember correctly the  point is that the serializer could be configured in a global way that could affect any convention we might rely on. So we shouldn't rely on conventions that are susceptible to be changed, if they can be that is.
Is it not possible to configure the serializer in a global way? i.e change from camelcase convention to pascal case? I was under the impression it was possible.

**Comment by stsrki** [comment]
So far, when we serialized the object to JS, we relied mostly on the built-in JSON serializer, assuming everyone would have camelCase settings.  But assuming it is not ideal and we need to handle it ourselves.

@tesar-tech The Tooltip you mentioned was just the first iteration of trying to solve the problem.

So, the plan is to have a dedicated serialization object with all the field names properly named using the JSON name attribute. We have already made it on the Video component. See:

- https://github.com/Megabit/Blazorise/blob/master/Source/Extensions/Blazorise.Video/Video.razor.cs#L73, and
- https://github.com/Megabit/Blazorise/blob/master/Source/Extensions/Blazorise.Video/VideoJSOptions.cs

---

We basically need to look everywhere where we have a `new object` for serializing to JSON and implement a new serialization class.

- https://github.com/Megabit/Blazorise/blob/master/Source/Extensions/Blazorise.PdfViewer/PdfViewer.razor.cs#L112
- https://github.com/Megabit/Blazorise/blob/master/Source/Extensions/Blazorise.PdfViewer/PdfViewer.razor.cs#L112
- etc.

**Comment by tesar-tech** [comment]
Oh, yeah. You mean making the object that goes to js a strong type... I agree with that.

But I don't see a reason why to include the `JsonPropertyName` attribute - as discussed above. I would do it only for those properties that require something else than the default camelCase...

Also maybe records instead of class to make it more condensed? Or at least use require keyword to force all the important stuff to be declared..? But that's probably for a different discussion or pr...

So what is left here? The JsOptions for tooltip?

**Comment by stsrki** [comment]
We want this make sure everything is handled properly. So all file must have JsonPropertyName.

Tooltip also need to have a new object.

As for what kind of. Stick with the class. As we have it for Video options.

**Comment by stsrki** [comment]
I think Blazor is always serializing to Camelcase. 

- https://github.com/dotnet/aspnetcore/blob/b7c8cf7506338b9cd5c4960bd99b03d190c3c805/src/Components/Shared/src/JsonSerializerOptionsProvider.cs#L12
- https://github.com/search?q=repo%3Adotnet%2Faspnetcore%20JsonSerializerOptionsProvider&type=code

Also, I found this comment from a Blazor team member saying that they don't have plans to change it as it could affect Blazor itself. https://github.com/dotnet/aspnetcore/issues/38144

So we might not need to do this at all.

**Comment by David-Moreira** [comment]
@stsrki But that's precisely what @tesar-tech was saying. There's currently no way to configure the options globally. I personally was under the impression it was, since it was implied so before.

I'd still take **concrete objects** over **anonymous objects** as an improvement to the code base.

**Comment by stsrki** [comment]
> [@stsrki](https://github.com/stsrki) But that's precisely what [@tesar-tech](https://github.com/tesar-tech) was saying. There's currently no way to configure the options globally. I personally was under the impression it was, since it was implied so before.

I was also under such an impression. But I never tried it in the past.

> I'd still take **concrete objects** over **anonymous objects** as an improvement to the code base.

Agree. At least make concrete objects even though we might not need to have `JsonPropertyName` attribute.
