### ISSUE TITLE
disable a validation

### ISSUE THREAD

**Issue by blenke** [Megabit/Blazorise#5705]
I am looking for a way to disable a validation. I have some forms where the validation is dependent on another field or on the general status of a record. I have some workarounds where i made multiple validations on a form and validate one or more depending on the status of the record. However it would be much simpler if i could disable a specific validation depending on a value as show in the example below. Is there another way to achieve this or could the validation be changed in the below proposed way ? 
I'm aware that i can make custom validations but since the form is quite big i don't want to make lots of custom validations. 

```
<Validations @ref=valref Mode="ValidationMode.Manual" >
    <Validation Validator="ValidationRule.IsNotEmpty" Disabled="@(Status!=0)">
        <TextEdit @bind-Text=mytest></TextEdit>
    </Validation>
</Validations>


<Button Background="Background.Primary" @onclick=Submit>Submit</Button>
@code {
    string mytest = "";
    Validations valref;
    int Status = 0;

    async Task Submit()
    {
        if (await valref.ValidateAll())
        {
            //save the form content
        }
    }
}
````

**Comment by stsrki** [comment]
Can you give us more detailed code examples? I'm not sure if I understand the requirements entirely.

**Comment by blenke** [comment]
I would like to have an optional validation that is dependent on some variable. This is how i solve it now by having multiple validations blocks. If the Status=="New" then it will only validate the first TextEdit, if its "Completed" then it will do both.
For a few inputs this is fine, but on large forms its a bit messy. It would be nice to be able to disable or skip a validation within a validations block by adding a 'Disabled' property or something else. 


```
<Select @bind-SelectedValue=Status>
    <SelectItem>New</SelectItem>
    <SelectItem>Completed</SelectItem>
</Select>

<Validations @ref=valref1 Mode="ValidationMode.Manual">
    <Validation Validator="ValidationRule.IsNotEmpty">
        <TextEdit @bind-Text=text1></TextEdit>
    </Validation>
</Validations>

<Validations @ref=valref2 Mode="ValidationMode.Manual">
    <Validation Validator="ValidationRule.IsNotEmpty">
        <TextEdit @bind-Text=text2></TextEdit>
    </Validation>
</Validations>

<Button Background="Background.Primary" @onclick=Submit>Submit</Button>

@code {
    string text1 = "";
    string text2 = "";
    Validations valref1;
    Validations valref2;
    string Status = "New";

    async Task Submit()
    {
        valref1.ClearAll();
        valref2.ClearAll();
        if (Status=="New")
        {
            await valref1.ValidateAll();
            //save data
        }
        else
        {
            await valref1.ValidateAll();
            await valref2.ValidateAll();
            //save data
        }
    }
}
```

**Comment by stsrki** [comment]
Can you make it custom validators?

```cs
ValidateName( ValidatorEventArgs e )
{
    // check for custom variables here if needed

    e.Status = string.IsNullOrEmpty( Convert.ToString( e.Value ) )
        ? ValidationStatus.Error
        : ValidationStatus.Success;
}
```

and

```
<Validation Validator="@ValidateName">
    <TextEdit @bind-Text=text1></TextEdit>
</Validation>
```

**Comment by stsrki** [comment]
You might also be able to do it with `IValidatableObject`

[ValidateName](https://github.com/Megabit/Blazorise/blob/master/Demos/Blazorise.Demo/Pages/Tests/ValidationsPage.razor#L561)

**Comment by blenke** [comment]
The IValidateObject is indeed a good option. I did not realize that the validations could be implemented in a flexible way. Below an example , Text1 is now fixed and Text2 is dependent on the Status.
I already realized that custom validators is possible as well, but then I have to rewrite the validators which I find not a great solution. 
Thanks for the solution.

```
@using System.ComponentModel.DataAnnotations;

<Select @bind-SelectedValue=mydata.Status>
    <SelectItem>New</SelectItem>
    <SelectItem>Completed</SelectItem>
</Select>


<Validations @ref=valref1 Model=mydata Mode="ValidationMode.Manual">
    <Validation>
        <TextEdit @bind-Text=mydata.Text1></TextEdit>
    </Validation>

    <Validation>
        <TextEdit @bind-Text=mydata.Text2></TextEdit>
    </Validation>
</Validations>


<Button Background="Background.Primary" @onclick=Submit>Submit</Button>

@code {
    someData mydata=new();
    Validations valref1;

    async Task Submit()
    {
        valref1.ClearAll();
        await valref1.ValidateAll();
    }

    class someData : IValidatableObject
    {
        [Required]
        public string Text1 { get; set; }

        public string Text2 { get; set; }
        public string Status { get; set; } = "New";

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (Status == "Completed")
            {
                if (string.IsNullOrEmpty(Text2))
                {
                    yield return new ValidationResult("Text2 is required", new[] { nameof(Text2) });
                }
            }
        }
    }
}
```

**Comment by stsrki** [comment]
Glad I could help. And thanks for sharing the final code that works.

PS. Going to update our docs and mention the `IValidatableObject`.
