### ISSUE TITLE
DataGrid | DataGridEditColumn | Prefer DatePicker | Add DateInputMode & public api

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#5717]
User asked to add `DateInputMode`.

Figure out if there are no technical limitations and add it.

![image](https://github.com/user-attachments/assets/25d046af-c96d-40bc-bae2-036037cf957c)

**Comment by blenke** [comment]
I think you should DatePicker instead of DateEdit in this filter. DateEdit will automatically take the browsers date/time format based on your regional settings. If DatePicker is used then the date format could be taken from the DisplayFormat or it will pick up the default culture setting from the application. 
I've used DatePicker in all my date controls and changed the culture so that all users get the same date format. Always a headache when mixing dd-MM-yy and MM-dd-yy. The column filter now shows a different date format.

I also have a use case for text input instead of date selection. If for instance you want to have all dates of 2024 then this was possible in the old text input by just entering 2024.

**Comment by David-Moreira** [comment]
I understand your point, but we stick to the standards on most of the components. And the DateEdit is based on the standard input type=date. However we understand that tipically this input has the limitations that you mention, and the DatePicker is more flexible. I'd stick to the standards, but I'd introduce a `DatePickerDateColumn` or a new parameter `UseDatePicker`, something along those lines. So best of both worlds. @stsrki ?

**Comment by stsrki** [comment]
> I understand your point, but we stick to the standards on most of the components.

Not necessarily. If you inspect the code in `_DataGridCellEditValidation.razor`, you will see that we use NumericPicker for numeric values. We can do the same with dates.

We can:

- introduce a new column type just for the date picker, or
- replace DateEdit with DatePicker

I think the second option is better as then we can have more features that are present DatePicker, like display format, editor format, etc.

PS. same with TimeEdit/TimePicker

**Comment by David-Moreira** [comment]
Take this example:
Someone uses `DateEdit` all over the app, and then wants to use the `DataGrid`, and is suddenly presented with a different default component for **Date** making their **app inconsistent** input wise.

I would go with first option. User chooses whatever he wants, we don't make his life harder by limiting his options, just because we "think it's better". 

The whole idea of following standards, is to do the already accepted supported  "official" route first and I'd expect that we focus on that first and foremost, but of course can always allow flexibility to allow the user to stray out of the "typical/officicial" html structure.

It's the reason why we have regular `<select>` even though it typically is very limited once you need more features.

**Comment by stsrki** [comment]
I would argue that we limit users by using DateEdit, which is controlled by the browser, and there is absolutely no room to control its behavior. Not to mention that it looks different in every browser and every culture.

With DatePicker, the user gets the same look everywhere. And they can control almost every aspect of the component behavior.

**Comment by David-Moreira** [comment]
> I would argue that we limit users by using DateEdit, which is controlled by the browser, and there is absolutely no room to control its behavior. Not to mention that it looks different in every browser and every culture.

How are you limiting?? I just told you **we introduce both options**. User uses whatever he wants. Plus we already have `DateEdit` in production we shouldn't change stuff just because now we think it's better. And we don't even know if it's better or not. For example personally I like to stick to native stuff as much as possible before introducing customized components.

- If user wants everything with `DateEdit` it's his choice, and he'll be using the html standard.
- If he wants "more power" and what we recommend, the `DatePicker`, then he can also use.

Otherwise following your lines of **DateEdit** "sucks", why even have it then? If `DatePicker` is so much better, just remove `DateEdit` and make users use `DatePicker` because it's so much better. Understand where I am going with this? We might think it's better, and it might indeed be better, but since we have both components just let the user choose.

**Comment by blenke** [comment]
I understand the dilemma, its frustrating that DateEdit format is browser controlled.
I would then suggest to add an option on which control to use, leave default to  what it is now. In that case also please add a none option (text box), so it would go back to the old text input, then users can select a part of the date. Date range would be even better but i understand from earlier discussions that this is not yet possible.

**Comment by stsrki** [comment]
I'm thinking of a hybrid option.

Introduce new APIs, like `DisplayFormat,` `InputFormat,` and `TimeAs24hr`, etc. 

And if any of the new parameters is provided, we switch internally from DateEdit to DatePicker.

**Comment by David-Moreira** [comment]
> I'm thinking of a hybrid option.
> 
> Introduce new APIs, like `DisplayFormat,` `InputFormat,` and `TimeAs24hr`, etc.
> 
> And if any of the new parameters is provided, we switch internally from DateEdit to DatePicker.

I understand where you're going, reduce the quantity of public api surface, but I personally don't like magic... hehe. You "grew" with dotnet as I did, see where the magic has taken them, most of the stuff nowadays is very much way more clearer and configurable. Instead of rigid + "magic".

**Example 1:** 
So if I want to use `DatePicker` instead of `DateEdit` I have to arbitrarily define one of those parameters? And what if everything's working fine, I get a business requirement to add a different `DisplayFormat` and then suddently I get a different date input all together, if QA has strict compliances, they will complain about it.

**Example 2:**
But If I don't define one of those specific parameters, I'll fallback to `DateEdit` even though I might not want to?

And then there's the argument for consistency again, if all my app uses `DateEdit`, but suddently I present a different date component to the end user that displays a different date UI, that might not be a very consistent UI/UX experience.

**Comment by stsrki** [comment]
Using non-native data input would not be problematic, even for QA. The only situation where native input is better is on mobile devices because there is a better UI for picking dates. In all other cases, our DatePicker wins in localization, customization, and overall UX.

I'm aware that it is a breaking-change in terms of usability. And it's not that users could not go back to the previous DateEdit by overriding EditTemplate. Yes, it's a bit more work.

**Comment by David-Moreira** [comment]
To me, you're assuming you know better what the user wants... And I'm not sure why you're also assuming it's not a problem for QA of companies you might not know, It's not like the QA of all companies will tackle QA the same way. 
Just the fact that you might have mixed types of UX for dates might be a good reason for some companies I would guess, and then you have to change every single `DateEdit` to `DatePicker` and re-trigger all the testing, etc... 

You've just said a use case where **even you** think it's better over `DatePicker`.

There might be a myriad of reasons why the user prefers or have to use the native date input.

> I'm aware that it is a breaking-change in terms of usability. And it's not that users could not go back to the previous DateEdit by overriding EditTemplate. Yes, it's a bit more work.
Same otherwise, people can just go to DatePicker by overriding... Anyway the suggestion was never to only have one or the other but to be able to choose. As to me that trumps rigidity / opinated components.

All in all I was just assuming that we'd always prefer html standards first, I see I might have misunderstand the philosophy from previous interactions. This is turning out to be a long thread and you're the decision maker at the end of the day. :) Let's just go with the breaking change then.

- `DateColumn` will now render a `DatePicker` instead and provide the corresponding public api.
