### ISSUE TITLE
FontAwesomeIcons constants

### ISSUE THREAD

**Issue by mtbayley** [Megabit/Blazorise#5737]
I'm looking to use the FontAwesomeIcons static class to define the menu icon for a custom attribute I created.

Would it be possible to make the strings `public const string` instead of `public static readonly string` to support usage in attributes?

Not a big deal, but it's nice working with the class instead of looking them up on the FontAwesome site.

![image](https://github.com/user-attachments/assets/bce447a3-b53b-4f1e-ae38-b66a1a53381c)

**Comment by stsrki** [comment]
I don't see a reason why not. I will add it to a 1.7 list. 

PS. If you have time to contribute, that would be great. Thanks.
