### ISSUE TITLE
[Bug]: Radio buttons  onclick/hover wrong selection

### ISSUE THREAD

**Issue by danik121** [Megabit/Blazorise#5760]
### Blazorise Version

1.6.1

### What Blazorise provider are you running on?

FluentUI2

### Link to minimal reproduction or a simple code snippet

![image](https://github.com/user-attachments/assets/3b2e4907-8298-44e9-86c5-a1693e1ab3e4)
![video](https://github.com/user-attachments/assets/8cfd4d17-d1b6-4180-bdc1-ad10d4fc7e11)

### Steps to reproduce

Demo example

### What is expected?

Select correct button/value

### What is actually happening?

Example from demo:
1. Select Green => selected. Ok
2. Hover on Red => Hover on Blue. Not ok
3. Click on Red(Not everywhere, on letter R) => Blue is Selected Not Ok

**Comment by stsrki** [comment]
The examples in the demo app cannot be selected simultaneously because they are different groups with different names.

![Image](https://github.com/user-attachments/assets/5c844ca7-6bba-4bfd-b25b-eacd645da364)

**Comment by danik121** [comment]
@stsrki it has nothing to do with selecting at the same time

example from fluient ui demo
https://github.com/user-attachments/assets/bf4f22fa-f9fb-4033-a5f0-653b9826a768

**Comment by stsrki** [comment]
Ah, I see it now. It shows the wrong button as selected. Thanks for the video.
