### ISSUE TITLE
Button customization for video player

### ISSUE THREAD

**Issue by thumaman** [Megabit/Blazorise#5767]
Hi, 

are there any was of customizing video player controls such as making them bigger, different color, different icon etc.

Thanks!

**Comment by stsrki** [comment]
Unfortunately, there is no easy way. We load the default video CSS from `https://github.com/Megabit/Blazorise/blob/master/Source/Extensions/Blazorise.Video/wwwroot/vendors/plyr.css`. 

You could copy it and modify it according to your specs to override default styles.

**Comment by stsrki** [comment]
PS. this might also help you https://www.vidstack.io/docs/player/components/layouts/plyr-layout?styling=default-theme

**Comment by thumaman** [comment]
I will check it out, thank you for your suggestions.
