### ISSUE TITLE
Markdown Custom Toolbar not replacing default Toolbar

### ISSUE THREAD

**Issue by linkdotnet** [Megabit/Blazorise#5783]
**Is your feature request related to a problem? Please describe.**
In the current version (`1.6.2`) adding a custom toolbar will replace the original one.
```html
<Markdown>
	<Toolbar>
		<MarkdownToolbarButton></MarkdownToolbarButton>
	</Toolbar>
</Markdown>
```

This will basically render one button.

**Describe the solution you'd like**
Oftentimes, I just want to add functionality and, therefore, would like to keep the original toolbar. Basically I want to have an "append" Toolbar option rather than replacing it.

**Comment by stsrki** [comment]
This is the expected behavior. When you define the Toolbar, you need to define all the buttons that you use. We don't have a way of knowing if you need to replace, remove, or add any particular button. So, by making it from scratch, you have full control over what goes in.

**Comment by linkdotnet** [comment]
That is very unfortunate that there is no easy way of just appending stuff without basically reimplementing all the buttons and aligning them on every update.

Looking at the `markdown.js` it seems that **MDE** just doesn't support such case ootb.

**Comment by stsrki** [comment]
I agree that it is unfortunate. But you just make it one time. It is only about ten buttons, so it shouldn't be much of a problem.

In theory, we could make up some API to add/replace buttons by combining it with the built-in MDE buttons. But overall, I think that would be harder for users to figure out than just straight up replacing them all.

**Comment by linkdotnet** [comment]
> I agree that it is unfortunate. But you just make it one time. It is only about ten buttons, so it shouldn't be much of a problem.

Yes, and to some extent none. For every minor/major version, you would have to check if there are new buttons / different order / ...
By just appending, you come around that maintenance cost.

But I totally understand the reasoning.

**Comment by stsrki** [comment]
Thanks for the understanding. I will close the ticket now.
