### ISSUE TITLE
Attributes of Video player not working

### ISSUE THREAD

**Issue by thumaman** [Megabit/Blazorise#5786]
Hi, 

I have this code to define my video player inside my application:

        <div class="video-player">
            <Video @ref="mainVideo" id="mainVideo" Source="@videoSource" DefaultQuality="1080" AutoPlay="true"
                   ClickToPlay="false" CurrentTime="@currentTime" TimeUpdate="OnTimeUpdate" Ended="@OnVideoEnded" 
                   AutomaticallyHideControls="false" ResetOnEnd="true" />
        </div>

Recently I noticed that not all the atributes are working correctly. Specifically ClickToPlay, ResetOnEnd, AutomaticallyHideControls.

ClickToPlay: my video always stops if I click on it, no matter the ClickToPlay value,
ResetOnEnd: my video always pause when it ends and i have to manually call mainVideo.Play() to play it again.
AutomaticallyHideControls: my controls always hide after 2 seconds of no focus, no matter the AutomaticallyHideControls value.
AutoPlay: works fine.

Can someone check if the attributes work on his/her end please.

Thanks.

**Comment by stsrki** [comment]
I think those commands are still waiting to be implemented appropriately by the Plyr provider of the Vidstack player. https://github.com/vidstack/player/blob/c9e31a851427db838327cebfb15fc16bf242e356/packages/vidstack/src/global/plyr.ts#L72

But I will need to check for confirmation.

**Comment by thumaman** [comment]
So is there no way of having the controls bar always visible?

**Comment by thumaman** [comment]
Hi, are there any updates on the new 1.7 release date?

**Comment by stsrki** [comment]
Hi. We moved it to align with the release of .NET 9. Which is scheduled for November 12 to 14, 2024. So, as soon as we update Blazorise to the latest versions, we will release it.

This change was needed to give us more time to finish extra work.

**Comment by stsrki** [comment]
#5799

**Comment by thumaman** [comment]
Okay, thanks for the info.
