### ISSUE TITLE
[Bug]: ListView Virtualize not working properly

### ISSUE THREAD

**Issue by cpiber** [Megabit/Blazorise#5793]
### Blazorise Version

master

### What Blazorise provider are you running on?

None

### Link to minimal reproduction or a simple code snippet

```blazor
            <ListView TItem="int"
                      Data="Enumerable.Range(0, 1000).ToList()"
                      Virtualize/>
```

### Steps to reproduce

 -

### What is expected?

Virtualization

### What is actually happening?

Only the first few items are shown

### What browsers do you see the problem on?

Firefox, Chromium

### Any additional comments?

The problem happens because `Virtualize` inserts a `div` with the `height` set. In a `<ul>` however, that does nothing and the spacer has height 0. In new versions of Blazor, there is a `SpacerElement` property (https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.web.virtualization.virtualize-1.spacerelement?view=aspnetcore-8.0#microsoft-aspnetcore-components-web-virtualization-virtualize-1-spacerelement). Until then, the option should be removed, since it makes no sense (or change the component to render without `<ul>`)

**Comment by cpiber** [comment]
Correction: I previously said that the `<div>` is ignored inside `<ul>`. This is incorrect. The actual problem is that the list group applies `display: flex`. I'm not sure why it does that, but changing to `display: block` fixes the issue and the height of the spacer is now respected.

**Comment by tesar-tech** [comment]
@cpiber, could you describe the issue in more detail, ideally with screenshots or a video, or by providing a test repository? The following code:

```razor
<ListView TItem="int"
          Data="list"
          TextField="item => item.ToString()"
          ValueField="item => item.ToString()"
          Virtualize />

@code {
    List<int> list = Enumerable.Range(0, 1000).ToList();
}
```

generates the expected output shown here:

https://github.com/user-attachments/assets/d54bf4fc-ad30-4be1-b922-949a43425a80

where everything appears to be working correctly.

**Comment by cpiber** [comment]
@tesar-tech You're not trying to scroll. You're supposed to be able to scroll for 1000 items. The given implementation can only scroll 13 elements, because the virtualization does not work at all. Open the inspector and notice the last child element `<div style="height: 48389.848px;" _bl_5=""></div>`, which is *supposed* to have to have a height of 48k, but has height 0 due to flex display

**Comment by cpiber** [comment]
I've just now also noticed something interesting: With .NET 8.0, the `Virtualize` component adds the `flex-shrink: 0` property to the spacing element, so this bug is effectively fixed upstream for newer versions of Blazorise, but it still persists on .NET 6 (haven't checked 7)

**Comment by tesar-tech** [comment]
Yeah, I just happily scrolled to item 999, running on .net8. 

The 6 and 7 will be out of support in Blazorise 2.0. Are we fixing this for older versions @stsrki ?

**Comment by tesar-tech** [comment]
I don’t see the issue even on .NET 6 (Blazorise 1.6.2).

https://github.com/user-attachments/assets/76c1e2ce-2d74-4413-b043-65ae57da53a7

Please, @cpiber, could you provide a repository with the issue? The provided code appears to be working properly.

**Comment by tesar-tech** [comment]
Yes, I can reproduce the issue, but it’s challenging to address due to different behavior across .NET versions. You can “unstack” the virtualized component by triggering any interactive action, like pressing a button, as described in the referenced bug report.

Given that .NET 6 support will end soon and an easy fix is available by updating to a supported .NET version, we’ve decided not to pursue a solution for this specific case on .NET 6.

**Comment by cpiber** [comment]
We fixed it locally by removing the flex display so this doesn't affect us anyways :) I agree, since it works in .NET 8 it's likely not worth it
