### ISSUE TITLE
Docs: Components which require a Blazorise license

### ISSUE THREAD

**Issue by XanderStoffels** [Megabit/Blazorise#5797]
**Is your feature request related to a problem? Please describe.**
I was wondering why my `LineChart` was not showing all the data I provided.  I tried debugging, checking what goes over the wire, reading the documentation, but nothing seemed to work. After looking at the Blazorise source code, it seems that the amount of data you provide to charts (and some other components) get limited based on your license. Our license is in the process of being renewed, so our data got cut off.

```
   internal const int DEFAULT_UNLICENSED_LIMIT_DATAGRID_MAX_ROWS = 1000;
   internal const int DEFAULT_UNLICENSED_LIMIT_AUTOCOMPLETE_MAX_ROWS = 1000;
   internal const int DEFAULT_UNLICENSED_LIMIT_CHARTS_MAX_ROWS = 10;
   internal const int DEFAULT_UNLICENSED_LIMIT_LISTVIEW_MAX_ROWS = 1000;
   internal const int DEFAULT_UNLICENSED_LIMIT_TREEVIEW_MAX_ROWS = 100;
```

**Describe the solution you'd like**
Write clearly at the top of the component's documentation what its limitations are if you do not have a license. This would have saved us some time figuring out the issue.

### Additional context
![Image](https://github.com/user-attachments/assets/e3661b57-fe92-4caf-82f9-2b190a92cab3)

**Comment by David-Moreira** [comment]
Hello @XanderStoffels 

Please find the information you're looking for on the pricing page:

![Image](https://github.com/user-attachments/assets/4db5b021-12ea-46ea-8773-073600b2700d)
https://blazorise.com/pricing

**Comment by XanderStoffels** [comment]
Thanks. However, I think in order not to confuse developers, the component documentation page should mention the limitations as well. I would have never guessed to check the pricing page. Also, the data in the screenshot you shared does not seem to be correct. It seems the listed limitations are 10x the actual limitation.

**Comment by stsrki** [comment]
It makes sense to add the mentions to the dedicated pages where needed. It never occurred to me before, but it is a valid point.

**Comment by XanderStoffels** [comment]
I think the second option requires the least amount of effort from the people reading the documentation, so my vote is on option 2.
