### ISSUE TITLE
[Bug]: Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by sks-ttaylor** [Megabit/Blazorise#5802]
### Blazorise Version

1.5.3

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction or a simple code snippet

randomly occurring...

### Steps to reproduce

unknown..

### What is expected?

script loaded

### What is actually happening?

failed to load script

### What browsers do you see the problem on?

Chrome

### Any additional comments?

we randomly get error
Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module:
 https://XXX/_content/Blazorise/breakpoint.js?v=1.5.3.0 

is there any way to attempt a retry in 
Source/Blazorise/Modules/BaseJSModule.cs  InitializeModule?

**Comment by stsrki** [comment]
Can you try updating to the latest 1.6.x version? I believe we have made some improvements in this regard.
