### ISSUE TITLE
GitHub template for bug report

### ISSUE THREAD

**Issue by tesar-tech** [Megabit/Blazorise#5822]
This would simplify the process of creating bug report repositories for users significantly.

I’m suggesting a repository under `Blazorise/BugReportProject`, which would host a basic Blazor project pre-configured with Blazorise. This repository would function as a [GitHub template](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository). A GitHub template adds a green "Use template" button at the top, allowing users to create a copy similar to a fork, but without linking to the base repository and with the ability to choose a custom name. It’s quite convenient.

Instructions could be included in the repository's README, and we could reference it in the GitHub issue template (https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository).

Additionally, we could set up a GitHub Action to keep the `BugReportProject` updated with the latest version, minimizing maintenance effort.

**Comment by stsrki** [comment]
I like the idea. Placing it under `Blazorise/` seems fine, as we don't use that account that much.

@David-Moreira what do you think?

**Comment by David-Moreira** [comment]
I'm not sure it will be used as much as we might think, but I mean, if it helps us getting more reproducibles since we simplify the user's life a bit, then the better.
