### ISSUE TITLE
[Bug]: DataGrid,  The fixed column's position is wrong if more than one fixed columns.

### ISSUE THREAD

**Issue by juchunwei** [Megabit/Blazorise#5823]
### Blazorise Version

1.6.2

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction or a simple code snippet

Don't have.

### Steps to reproduce

1. setup 2 fixed columns
![Image](https://github.com/user-attachments/assets/887a8c41-88ab-4fa3-b995-db94a377dbd0)
2. the page like this when I run the project.
![Image](https://github.com/user-attachments/assets/b7d70b89-fa83-413b-a58c-60c6b4eb5d38)

### What is expected?

the style of the first column, should be {"left":0"}

### What is actually happening?

the position of the first column is wrong.

### What browsers do you see the problem on?

Microsoft Edge

**Comment by David-Moreira** [comment]
@juchunwei would you be so kind to test the newest changes in v1.7?
We've introduced a `FixedColumnsPositionSync` parameter that when set to true should make it so it recalculates and produces a more faithful result, can you try it and let us know if it works for you?
![Image](https://github.com/user-attachments/assets/f8bfed10-88dd-42de-aa34-6ac37458e008)

**Comment by juchunwei** [comment]
The fixed columns seem working, but it caused another issue, the select function not working if set the DataGridMultiSelectColumn as fixed column.  and the fixed header not working for the fixed columns.

**Comment by juchunwei** [comment]
@David-Moreira 

The fixed columns seem working, but it caused another issue, the select function not working if set the DataGridMultiSelectColumn as fixed column. and the fixed header not working for the fixed columns.

**Comment by David-Moreira** [comment]
I'm sorry if we somehow introduced some kind of bug. Would you be so kind to open a new issue with the respective reproducible and mention @stsrki as I'm no longer handling datagrid issues.

**Comment by juchunwei** [comment]
@David-Moreira okay, thanks!
