### ISSUE TITLE
Cropper - use alternative image sources other than a directory

### ISSUE THREAD

**Issue by drma-tech** [Megabit/Blazorise#5829]
In the Image and FigureImage components I can use an image source like this:

`www.site.com/image.png`
or
`$"data:{file.Type};base64,{Convert.ToBase64String(buffer)}"`

but in the cropper, if I try to use an image that is not a directory (at least that's what I think is happening), the following error occurs:

```
invoke-js.ts:176 fail: Microsoft.AspNetCore.Components.Web.ErrorBoundary[0]
      System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
       ---> System.NullReferenceException: Object reference not set to an instance of an object.
         at Blazorise.Cropper.Cropper.<>c__DisplayClass1_0.<<SetParametersAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Blazorise.BaseAfterRenderComponent.OnAfterRenderAsync(Boolean firstRender)
         at Blazorise.BaseComponent.OnAfterRenderAsync(Boolean firstRender)
         at Blazorise.Cropper.Cropper.OnAfterRenderAsync(Boolean firstRender)
         --- End of inner exception stack trace ---
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazorise.Cropper.Cropper.<>c__DisplayClass1_0.<<SetParametersAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Blazorise.BaseAfterRenderComponent.OnAfterRenderAsync(Boolean firstRender)
   at Blazorise.BaseComponent.OnAfterRenderAsync(Boolean firstRender)
   at Blazorise.Cropper.Cropper.OnAfterRenderAsync(Boolean firstRender)
   --- End of inner exception stack trace ---
```

**Comment by tesar-tech** [comment]
Do you find this related https://github.com/Megabit/Blazorise/issues/5809? It has been fixed for 1.7 that will be out soon.

I can confirm you can work with base64 images.

**Comment by drma-tech** [comment]
is it possible. as soon as possible i will test.

**Comment by drma-tech** [comment]
It seems that the version that is in the nuget is from 3 weeks ago, before this correction.

**Comment by tesar-tech** [comment]
> It seems that the version that is in the nuget is from 3 weeks ago, before this correction.

That's correct. 1.7 is not released yet.

**Comment by drma-tech** [comment]
i was talking about preview version (1.7.0-preview1)

**Comment by stsrki** [comment]
There is also a night build on MyGet https://www.myget.org/feed/blazorise/package/nuget/Blazorise to try.

https://www.myget.org/feed/blazorise/package/nuget/Blazorise

**Comment by drma-tech** [comment]
ok, its working.
