### ISSUE TITLE
Expose internal order of DropZone items when AllowReorder is enabled

### ISSUE THREAD

**Issue by mkontula** [Megabit/Blazorise#5830]
** Problem **
Droppable supports reordering of items within a zone. However, the internal order is kept only in internal indicies Dictionary.

** Solution **
Please make the internal order accessible from outside the component. With this change, reordering of the items in zone makes sense for application s using the reordering.

**Comment by stsrki** [comment]
I think this is worth pursuing as we have already had similar requests in the past. We only need to figure out the right API that should be exposed. I think having it as 

```cs
/// <summary>
/// The callback that is raised when the order of items changed. Only if <see cref="AllowReorder"/> is enabled.
/// </summary>
[Parameter] public Func<Dictionary<TItem, int>, Task> Reordered { get; set; }
```

@tesar-tech could you do it?

I think we just need to pass internal `indices` on each change.
