### ISSUE TITLE
[Bug]: DataGrid : DatePicker Column isn't compatible with DisplayFormat

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#5837]
@stsrki 

I Remember now why we had a separate DateDisplayFormat.
The DisplayFormat isn't really compatible with the DatePicker format style. It seems to use a **string.format**

DisplayFormat="{0:dd.MM.yyyy}"
**UI**
![Image](https://github.com/user-attachments/assets/aac702d6-26d7-4e3f-9952-6b76853daa7d)
**DatePicker**
![Image](https://github.com/user-attachments/assets/085abe2e-1ccd-4de1-bfdc-b89a336aa06b)

DisplayFormat="dd.MM.yyyy"

**UI**
![Image](https://github.com/user-attachments/assets/34b7cf1e-f2f7-4038-b44d-7f9bf6c19aab)

**DatePicker**
![Image](https://github.com/user-attachments/assets/e4bdde4e-817a-42a5-b38a-2cf41b3c4ad4)

What do you think, should we revert back?

**Comment by stsrki** [comment]
Not sure. `DisplayFormat` is used for display in a non-edit mode. Only when the row is edited that the DatePicker is shown. Right? So then it shouldn't affect it?

**Comment by David-Moreira** [comment]
I don-t understand your question. I just showed you the differences with the screenshot. Cell Display vs DatePicker input.

**Comment by stsrki** [comment]
> I don-t understand your question. I just showed you the differences with the screenshots. Cell Display vs DatePicker input.

Sorry, I was looking at the wrong date input in the image. Yeah, I see the problem now.

Whichever path we take will be a breaking change/behavior for our users. If we tell them to now write "dd.MM.yyyy" instead of "{0:dd.MM.yyyy}" as previously, or if they replace `DisplayFormat` with `DateDisplayFormat` it is essentially the same. They need to change their code.

I'm more open to telling them to do "dd.MM.yyyy" instead of "{0:dd.MM.yyyy}" as that will not introduce any new API.

**Comment by stsrki** [comment]
Dumb idea.. What if we parse and convert "{0:dd.MM.yyyy}" to "dd.MM.yyyy"?

**Comment by stsrki** [comment]
ChatGPT 😅

```cs
public static string ConvertToSimpleDateFormat(string inputFormat)
{
     var match = Regex.Match(inputFormat, @"\{0:(.+?)\}");
    if (match.Success)
    {
         return match.Groups[1].Value;
    }  
 
    return inputFormat;
}
```

**Comment by David-Moreira** [comment]
Well first of all why are we even using this type of format "**{0:}**" ? Was there a special reason for it? Seems weird to define it like this honestly. I'd expect it to work just like : "**dd.MM.yyyy**". 
So if there's no special reason, we could consider the change in order to make it more clear. As a user I would expect "**dd.MM.yyyy**" instead of "{0:dd.MM.yyyy}".

Now, we could wait for 2.0 to make that breaking change, and just try to infer the proper format for DatePicker as you mention.

**Comment by stsrki** [comment]
> Well first of all why are we even using this type of format "**{0:}**" ? Was there a special reason for it? Seems weird to define it like this honestly. I'd expect it to work just like : "**dd.MM.yyyy**". 

I have no idea TBH. It was so long ago that I really don't know the reason by now.

**Comment by David-Moreira** [comment]
> @"\{0:(.+?)\}");

Lol, don't let your "brain rot" by depending on it too much. StartsWith and EndsWith works equally well in this case. Probably more readable even. 
But yea for some stuff it's easy to just not waste time thinking and jump in chatgpt.

**Comment by stsrki** [comment]
My brain is already rot from a lack of sleep from looking at my 1 year old 😅
