### ISSUE TITLE
[Bug]: Change options for Cropper

### ISSUE THREAD

**Issue by drma-tech** [Megabit/Blazorise#5847]
### Blazorise Version

all

### What Blazorise provider are you running on?

None

### Link to minimal reproduction or a simple code snippet

I can't set any configuration. If I try just one, the page gives an error when running. If I try more than one, I get this error.

![Image](https://github.com/user-attachments/assets/a98397a4-7cc7-48d8-a09c-4f82ef48de36)

### Steps to reproduce & bug description

any attempt to define options.

### What is expected?

can set one or more options.

### What is actually happening?

![Image](https://github.com/user-attachments/assets/9d3bc7b5-e7d0-4f28-ba52-5d05aa172cbc)
I don't know if this is the reason (as I don't know the behavior of the record), but the options structure is a record and the properties are set to init.

### Any additional comments?

ImageOptions, SelectionOptions, GridOptions

all have the same problem

**Comment by stsrki** [comment]
It looks like there is something wrong with Visual Studio IntelliSense. Can you try restarting it?

**Comment by drma-tech** [comment]
It's not Visual Studio. I can't even compile. And if I use just one attribute, I get this error:

![Image](https://github.com/user-attachments/assets/705be07f-07a1-4ed8-9640-1c69f138e6cd)

**Comment by stsrki** [comment]
Replace this 
![Image](https://github.com/user-attachments/assets/41cb6b02-6f19-4118-b76c-d38501d8e6a4)

with `,`

**Comment by drma-tech** [comment]
Taking advantage of the cropper subject, when I'm starting and still don't have an image, it looks like this:

![Image](https://github.com/user-attachments/assets/92be7922-767f-4131-bda6-4bcc20acf202)

**Comment by drma-tech** [comment]
@stsrki SetParametersAsync  was resolved also?

**Comment by stsrki** [comment]
The same fix is handled for load and update of image so it should work for SetParametersAsync also.

**Comment by drma-tech** [comment]
They are two different things, even though I put both of them here. But I will test them as soon as they come out.

**Comment by drma-tech** [comment]
![Image](https://github.com/user-attachments/assets/69cfdfba-824b-4a81-bc6f-8eed39069ec5)

![Image](https://github.com/user-attachments/assets/3590bda8-c051-4ab2-8122-cdc3bebd24f1)

I tested it today (better late than never). It still doesn't work.

**Comment by drma-tech** [comment]
also (and yet), when i use the option, i got errrors

```
 <Cropper @ref="cropper" Source="@OriginalPicture" SelectionChanged="@OnSelectionChanged" Style="width: 256px; height: 256px;"
          SelectionOptions="@(new CropperSelectionOptions{Zoomable=false, AspectRatio=CropperAspectRatio.Is2x3})" />
```

![Image](https://github.com/user-attachments/assets/f9928575-c6fc-499a-9d8f-07dbb008941d)

**Comment by stsrki** [comment]
@tesar-tech

**Comment by tesar-tech** [comment]
The first issue is an error indicating that the source is either unreachable or does not exist. This originates from Cropper.js.  
It is the developer's responsibility to ensure that the source is valid. If it is not, Blazorise will not fail; instead, it will trigger the `ImageLoadingFailed` event, as described here: https://github.com/Megabit/Blazorise/pull/5937 (this should be available in the next version).  

We could potentially hide the error, but I don’t think that would be a good idea and from your perspective nothing will change.

For the second one - yes, that seems like another issue. Can you create new ticket for it? so we don't mix the conversations
