### ISSUE TITLE
[Bug]: Using extensions separately does not work (in this case, the Qr Code)

### ISSUE THREAD

**Issue by drma-tech** [Megabit/Blazorise#5851]
### Blazorise Version

all

### What Blazorise provider are you running on?

None

### Link to minimal reproduction or a simple code snippet

according to documentation, installing only the blazorise.qrcode, without configuring anything else. without installing blazorize.

### Steps to reproduce & bug description

 `<QRCode Value="@SerialNumber3" Alt="@SerialNumber3" EccLevel="EccLevel.H" Style="width: 100%" />`

![Image](https://github.com/user-attachments/assets/9f6041a0-ccc4-46e4-bc6b-d3cc6875988d)

### What is expected?

I believe that the components that are part of the extensions section should work in isolation, without having to install Blazorise.

### What is actually happening?

for the component works you need to install Blazorise and a CSS provider.

### What browsers do you see the problem on?

Chrome

**Comment by stsrki** [comment]
Check the **Empty provider** section on

https://blazorise.com/docs/usage
