### ISSUE TITLE
[Bug]: Sample /tests/datagrid/group/single does not show any grouping

### ISSUE THREAD

**Issue by brauerj-gc** [Megabit/Blazorise#5861]
### Blazorise Version

1.7

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction or a simple code snippet

/tests/datagrid/group/single

### Steps to reproduce & bug description

run demos and open /tests/datagrid/group/single 

### What is expected?

To see some grouping.  By Gender it seems.  

### What is actually happening?

No grouping is seen in the UI.

**Comment by David-Moreira** [comment]
@stsrki It can indeed be verified on the live demo.
https://bootstrapdemo.blazorise.com/tests/datagrid/group/single

However the local rel1.7 does not seem to display this behaviour, can I ask that you redeploy latest 1.7 demo?

![Image](https://github.com/user-attachments/assets/7fa7d976-5adf-4402-95b5-c668fe85d00a)

**Comment by David-Moreira** [comment]
Hello @brauerj-gc Please re-read my comment.

> It can indeed be verified on the live demo.

@stsrki Could you please redeploy and re-verify?

**Comment by stsrki** [comment]
> Hello [@brauerj-gc](https://github.com/brauerj-gc) Please re-read my comment.
> 
> > It can indeed be verified on the live demo.
> 
> [@stsrki](https://github.com/stsrki) Could you please redeploy and re-verify?

I will do it tomorrow when I get back in the office. I don't have all the necessary workloads installed on my home PC.

**Comment by stsrki** [comment]
All is redeployed now.

Closing the ticket.

**Comment by David-Moreira** [comment]
I can confirm that is now working. Strange "bug" though. Thanks.
