### ISSUE TITLE
[Bug]: "Toggle Detail Row" does nothing on sample /tests/datagrid/selection/row-detail

### ISSUE THREAD

**Issue by brauerj-gc** [Megabit/Blazorise#5862]
### Blazorise Version

1.7

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction or a simple code snippet

/tests/datagrid/selection/row-detail 

### Steps to reproduce & bug description

Select a Name and click "Toggle Detail Row"

### What is expected?

Something to expand or contract

### What is actually happening?

Nothing noticeable

**Comment by David-Moreira** [comment]
Hello @brauerj-gc 
Actually it's working as expected. I'm sorry if the demo isn't clear, but some rows do not have detail rows to expand as per the rules on it:
![Image](https://github.com/user-attachments/assets/d1a02e2b-417b-4762-9ef7-5ca61f4dd4f8)
![Image](https://github.com/user-attachments/assets/ea65741d-e1b5-4fdb-af87-f49ed40d0124)
