### ISSUE TITLE
Virtualize: Analyzing Limitations with Large Datasets

### ISSUE THREAD

**Issue by tesar-tech** [Megabit/Blazorise#5901]
While investigating support for larger datasets ( [see](https://github.com/Megabit/Blazorise/issues/5170)) and transitioning from `int` to `long`, I identified several issues with the `Virtualize` component. Below are the findings and potential approaches to address them.

## 1M large datasets

Even before nearing the `int.MaxValue` threshold, the `Virtualize` component begins to exhibit issues with datasets around 1M items.

```razor
@page "/"
@using Blazorise.DataGrid
@rendermode  InteractiveServer
<h3>Virtualize in DataGrid</h3>

<DataGrid TItem="LargeModelItem"
          Data="items"
          ReadData="OnDataRead"
          Virtualize="true"
          TotalItems="totalItems"
          
     
>
    <DataGridColumn Field="@nameof( LargeModelItem.Id )" Caption="id" />
    <DataGridColumn Field="@nameof( LargeModelItem.Name )" Caption="Name" Editable/>
</DataGrid>



@code {
    class LargeModelItem
    {
        public long Id { get; set; }
        public string Name { get; set; } = "";
    }

    IEnumerable<LargeModelItem> items = [];
    int totalItems = 10_000_000;
    
    private void OnDataRead(DataGridReadDataEventArgs<LargeModelItem> e)
    {
        items = Enumerable.Range(e.VirtualizeOffset, e.VirtualizeCount).Select(i => new LargeModelItem
        {
            Id = i,
            Name = $"Item id { i} "
        });
    }
}
```

First you will notice the slider being in half, but it's only on 300k-th item (from 10M):
![Image](https://github.com/user-attachments/assets/276d24b5-a4ee-49fd-bfbc-b506c3bc8aff)

Second - when you scroll down (by dragging the scrollbar) it lose its marbles and show some "random"... It can get close to 1M, but not in a consistent way.

https://github.com/user-attachments/assets/71a6b046-af9c-4789-9218-a5e97cd66075

This is not an issue with the Blazorise library but rather with browsers themselves. The `Virtualize` component works by using top and bottom "placeholder" elements, which have their height set to: 

```
numberOfItemsToSkip * heightOfSingleItem
```

In this case, it results in:

```
height: 2.73663e+08px;
```

This value is far too large for browsers to handle, and as a result, they simply cut the content.

It's actually reported in aspnetcore repo: https://github.com/dotnet/aspnetcore/issues/26354   
But explained in this answer on SO: https://stackoverflow.com/a/10884837/1154773   
With nice too jsfiddle tool to verify the max pixels your browser can handle: https://jsfiddle.net/josh3736/BhHfN/   
It is also mentioned in syncfusion's DataGrid docs: https://blazor.syncfusion.com/documentation/datagrid/virtual#limitations-for-virtualization (they don't support such large datasets in virtualized datagrid)

The maximum height for Chromium browsers is 16 million pixels, and for Firefox, it's 4 million pixels. This is why my example fails at around 1 million items, given that each item is approximately 20px in height.

While the issue on the `aspnetcore` repository was dismissed, I don't believe it's impossible to solve. The scrollbar looks identical whether your list contains 100k items or 10k items—just a small, draggable thumb. 

For this reason, I think it is feasible to adapt the `Virtualize` component to handle much larger datasets. This could be achieved either at the component level or within the Blazorise library itself. 

 ## int.MaxValue + datasets

Here it hits another problem. 

https://github.com/dotnet/aspnetcore/blob/1f0c1a87709a9b20a46df5c36f616950f0427ad1/src/Components/Web/src/Virtualization/ItemsProviderResult.cs#L20

`ItemsProviderResult` which is used in:

https://github.com/Megabit/Blazorise/blob/f53c76fa5f9bf47edc206c0883557790247d5aeb/Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs#L2160

`TotalItems` is type of int, thus we cannot simply tell it to have more than that. 

## Solutions?:

- Just simply mention that in docs "we cannot support large datasets with `Virtualize`, but it's not our fault"
- Try to trick the `Virtualize` to think it's working on something smaller - I think doable, but rabbit holes ahead for sure. "The worst" scenario would be forking the `Virtualize` component... But from there it would be just a step to make support for int.MaxValue+ datasets - and that would be awesome...
- Something else ??

**Comment by stsrki** [comment]
> * Just simply mention that in docs "we cannot support large datasets with `Virtualize`, but it's not our fault"

I would do just this. Mention that virtualize will break for >1M of data. It's a technical limitation that is not in our control, so people should understand it.

With `long.MaxData`, we want to be able to handle non-virtualize mode, which is still possible with regular pagination.
