### ISSUE TITLE
[Bug]: ColorPicker does not accept empty color

### ISSUE THREAD

**Issue by cpiber** [Megabit/Blazorise#5905]
### Blazorise Version

1.7

### What Blazorise provider are you running on?

None

### Link to minimal reproduction or a simple code snippet

```blazor
<ColorPicker Color="null" />
```

### Steps to reproduce & bug description

Set `Color` property to `null`

### What is expected?

The item should be set to no color, same as when the "Clear" button is used

### What is actually happening?

Black is selected

### Any additional comments?

I have a strong suspicion it is because of this line:
https://github.com/Megabit/Blazorise/blob/314d97e68968efbe270b8a047c9da6fcbb569936/Source/Blazorise/wwwroot/colorPicker.js#L19

The JS part has a fallback again; the blazor part already sets this default, so this should not be there

**Comment by stsrki** [comment]
There seem to be two problems here.

1. As you have assumed the `default: options.default || "#000000"` is more corrected to be defined as `default: options.default || "#00000000"`. Which will set the color as transparent, same as it is in preview.
2. The `<ColorPicker Color="null" />` is not correct to define it as null. Remember, the `Color` parameter is a string type, so in this case, you have defined it as string `"null"` value. The expected value format should be a HEX. That means to really to define it as a `null`, it needs to be defined as `<ColorPicker Color="@((string)null)" />.`

---

We will fix the first issue.

**Comment by cpiber** [comment]
>  is more corrected to be defined as default: options.default || "#00000000"

That still is not correct, is it? Clicking "Clear" sets Color to `null`, so giving `null` should also work without changing the value

> The <ColorPicker Color="null" /> is not correct to define it as null. Remember, the Color parameter is a string type, so in this case, you have defined it as string "null" value. The expected value format should be a HEX. That means to really to define it as a null, it needs to be defined as <ColorPicker Color="@((string)null)" />.

`null` is equivalent to `@((string)null)` because `string` is nullable

**Comment by stsrki** [comment]
> `null` is equivalent to `@((string)null)` because `string` is nullable

No. The `.razor` engine is kinda to blame here. When it tries to solve what you define for the string parameter it takes it as it is written. In your case, the actual value for `Color="null"` when inspected in the debugger would be the `"null",` not the `null`.

**Comment by stsrki** [comment]
> That still is not correct, is it? Clicking "Clear" sets Color to `null`, so giving `null` should also work without changing the value
> 
> >

This problem is from the original library. The real color cannot be undefined. So we try to have default color that makes some sense.

See https://github.com/simonwep/pickr/issues/178

**Comment by cpiber** [comment]
Interesting, good to know. In my actual test I have a variable that is null and it behaves the same, so I did not notice, thanks for the info.
Still, the input should not change the color to anything without the user selecting something, and both "#000000" and "#00000000" are different from `null`

**Comment by stsrki** [comment]
That might work. Working on it.

**Comment by cpiber** [comment]
Thank you for the fast work!
