### ISSUE TITLE
PdfViewer component

### ISSUE THREAD

**Issue by WillianGruber** [Megabit/Blazorise#598]
A PDF Viewer container :)

**Comment by stsrki** [comment]
I guess this would be an extension component for Blazorise. In that case, what JS library for PDFs is going to be implemented. There is many to choose from.

**Comment by WillianGruber** [comment]
No idea, I'm new to all these outside of SAP. Got any options?

**Comment by stsrki** [comment]
https://github.com/mozilla/pdf.js/

This one looks good.

**Comment by WillianGruber** [comment]
Perfect

**Comment by InzeNL** [comment]
Any updates on when this might be implemented?

I'll be needing something similar, and I'm debating between waiting for this component and implementing something myself

**Comment by Mr-Pearce** [comment]
Hello there,
Is there an ETA or something for that?
We would kinda also need a PDF Viewer in short future.

**Comment by stsrki** [comment]
> It's put on hold for now. I don't remember the exact problem, but there was something technical that gave me problems while implementing it. I will need to revisit it again to see what was the issue.

Basically, it's the same answer as before. I can try scheduling it for 1.7 and see if it would be possible now.
