### ISSUE TITLE
Sidebar sync to open page selected by a navlink

### ISSUE THREAD

**Issue by intech-paul** [Megabit/Blazorise#607]
Can the side bar auto select (and open if needed) an item that has been navigated to via a navlink ?
I.e I have a hot list of page names displayed as navlinks on a main menu page, once one is clicked the page is changed, and the sidebar opens the "Page" tree and selects page x that the user has just chosen.

**Comment by WillianGruber** [comment]
I believe you can change the sidebaritem isopen manually

**Comment by stsrki** [comment]
Hi @intech-paul, I think you can do it as @WillianGruber told you. Please try it before, and if it doesn't work for you please post in here the sample code so we can help you.

**Comment by intech-paul** [comment]
I am using a code generated sidebar, I don't see where I could put the isopen setting:

            new SidebarItemInfo
            {
                Text = "Pages ", 
                SubItems = new List<SidebarItemInfo>
                {
                new SidebarItemInfo { To = "ShowPageN/1", Text = "Page 1" },
                new SidebarItemInfo { To = "ShowPageN/2", Text = "Page 2" },
                new SidebarItemInfo { To = "ShowPageN/3", Text = "Page 3" },
                new SidebarItemInfo { To = "ShowPageN/4", Text = "Page 4" },
                }

**Comment by stsrki** [comment]
@intech-paul There is a field `IsShow` on `SidebarItemInfo`. Maybe you can control it with that.

If not, I can try to think of something else. Maybe add a visibility handler to the `SidebarItemInfo`. 🤔

**Comment by intech-paul** [comment]
Hello

I have not been able to try this, as I seem to get a lot of compile errors when updating the blazorise nuget packages to the latest version and have to rewind to 0.8.6.2.

Do I need to upgrade the core to 3.2.0 ?

[cid:image001.png@01D5EC9A.E7DFCBE0]

Thanks & Regards
Paul

**Comment by intech-paul** [comment]
![image](https://user-images.githubusercontent.com/56703036/75294837-44238400-588e-11ea-8b20-6a7e7b054376.png)

**Comment by stsrki** [comment]
@intech-paul Blazorise 0.8.8.3 is on .Net Core 3.1.0. I see you have a really old version. I advise to upgrade to the latest version but you will probably have to also upgrade Visual Studio and .Net Core.

Here are some release notes that can help you:
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-1-preview-3/
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-1/

PS. For now you can stay on Blazorise 0.8.8.3, and .Net Core 3.1 but if you have time you can try the latest Blazorise 0.9-p1 with .Net Core 3.2. Just keep in mind there are going to be some breaking changes.

**Comment by stsrki** [comment]
Closing in favor of #2888
