### ISSUE TITLE
[Feature Request] Tokenfield Control (Based on Autocomplete)

### ISSUE THREAD

**Issue by MichaelPeter** [Megabit/Blazorise#614]
**Is your feature request related to a problem? Please describe.**
When you need to be able to select multiple values from a select you need a tokenfield, this could look like the jQuery Tokenfield.

Can be used for inputting multiple values.
Or to filter for multiple values

**Describe the solution you'd like**
A blazor component based on the Autocomplete control to select multiple values. The section is over the Autocomplete control, but just that multiple values can be selected.

Simular to Bootstrap Autocomplete:
https://sliptree.github.io/bootstrap-tokenfield/

### Additional context
![grafik](https://user-images.githubusercontent.com/4217002/75174095-41128180-5730-11ea-9918-39a8f84c3d6f.png)

**Comment by stsrki** [comment]
@MichaelPeter The token field is already planned, #340. I'm currently working on v0.9 so I will see what can be done after it's finished.

**Comment by stsrki** [comment]
Done in 0.9.5
