### ISSUE TITLE
LineChart not picking up columnsize properly 0.8.8.3

### ISSUE THREAD

**Issue by intech-paul** [Megabit/Blazorise#629]
Sample Code:

`<Fields>
   <Field ColumnSize="ColumnSize.Is6">
	<LineChart @ref="lineChart" TItem="double" OptionsJsonString="@("{\"animation\": {\"duration\": 0}}")"/>
	</Field>
</Fields>`

Drew ok on 0.8.6.2/.net 3.1 preview

Now drawn  as:

![image](https://user-images.githubusercontent.com/56703036/75931528-14056200-5eda-11ea-8d93-50beb6129f4d.png)

Chart Draws ok if the Fields are removed.

Also updated environment today to preview 3.2 & .net standard 2.1

![image](https://user-images.githubusercontent.com/56703036/75931778-a3127a00-5eda-11ea-9bf6-29368ff525c7.png)

**Comment by stsrki** [comment]
Field is only used to hold input components and labels. It's an abstraction over `form-group` in Bootstrap: https://getbootstrap.com/docs/4.3/components/forms/#form-groups

Maybe you can try use `Col` instead to hold the chart?!

**Comment by intech-paul** [comment]
Hi, I have put the line chart into a table and that draws it correctly when the browser window is first displayed. When I resize the browser to a larger size, the chart & items resize correctly, but when I make the browse window smaller, no redraw is fired, what could be happening here ?

**Comment by stsrki** [comment]
Can you show me a sample of your code?

**Comment by intech-paul** [comment]
Here's a bare bones sample:

`@page "/GraphSizeTest"

<h3>GraphSizeTest</h3>

<Table>
<colgroup>
    <col span="1" style="width:20%"/>
</colgroup>
    <tr>
    <td><LineChart @ref="lineChart" TItem="double" OptionsJsonString="@("{\"animation\": {\"duration\": 0}}")"/></td>
    </tr>
</Table>

@code {
        LineChart<double> lineChart;

      protected override async Task OnAfterRenderAsync(bool firstRender)
        {
        if (firstRender)
        {
            LineChartDataset<double> dsEmpty = new LineChartDataset<double>();
            lineChart.AddDataSet(dsEmpty);
            await lineChart.Update();
        }
    }
}
`
It works ok when browser page is made bigger, but when smaller the graph size is not changed.
I have also got a sidebar on the page,. I wonder if that is gobbling up some messages ?

**Comment by intech-paul** [comment]
Line chart definition
<Table>
<colgroup>
    <col span="1" style="width:20%"/>
</colgroup>
    <tr>
    <td><LineChart @ref="lineChart" TItem="double" OptionsJsonString="@("{\"animation\": {\"duration\": 0}}")"/></td>
    </tr>
</Table>

**Comment by intech-paul** [comment]
[GraphSizeTest.razor.txt](https://github.com/stsrki/Blazorise/files/4315232/GraphSizeTest.razor.txt)

**Comment by stsrki** [comment]
After a quick googling it seems this is a known problem:

https://www.chartjs.org/docs/latest/general/responsive.html
https://github.com/jtblin/angular-chart.js/issues/614

Maybe you could do the trick with some custom css styles. Please try that first. 

If you don't succeed I will see what can be done in next version. I think the best option is to handle window resize by the Blazorise.
