### ISSUE TITLE
The documentation is difficult to read on certain browser window widths.

### ISSUE THREAD

**Issue by TPIvan** [Megabit/Blazorise#659]
**Describe the bug**
Font size in documentation web increases with screen width. This makes font to large on full screen browser window on standard full HD desktop screen. Parts of code get scrollbars and text in table columns is partially not readable. 

**To Reproduce**
1. Go to 'https://blazorise.com/docs/extensions/datagrid/#command-templates' (I have tested Chrome and Firefox)
2. Try to change the window width

**Expected behavior**
If font size change is necessary (for small screens?) it should prevent scrollbars in code and text hidding in tables.

**Screenshots**
 **Narrow (OK):**
![Narow](https://user-images.githubusercontent.com/39948593/77555330-6cb39380-6eb7-11ea-960c-e2b605487116.png)
**Wide (problematic):**
![Wide](https://user-images.githubusercontent.com/39948593/77555253-560d3c80-6eb7-11ea-9ff3-5308f56ab478.png)

**Comment by stsrki** [comment]
Resizing the window on desktop indeed shows the scrollbars for code blocks, but on mobile they are only party visible when you tap on code and move around. Regarding the table I don't think much can be done there. Tables are not very responsive.

I'm using template from [minimal-mistakes](https://github.com/mmistakes/minimal-mistakes) for documentation so hopefully I can find some part of code where I can control the font size.

**Comment by TPIvan** [comment]
The main problem is hidden text in tables, which is caused by (irrelevant properties deleted )
    
      table {
        	display: block;
	        width: 100%;
	        overflow-x: auto;
             }

I think that the table should be in a container with those properties.

**Comment by stsrki** [comment]
Help links, for later!
https://github.com/mmistakes/minimal-mistakes/issues/1043
https://github.com/mmistakes/minimal-mistakes/issues/1184

**Comment by stsrki** [comment]
Closing since we're already in process of creating new documentation pages. https://preview.blazorise.com/
