### ISSUE TITLE
Adding support to Open Iconic

### ISSUE THREAD

**Issue by cabralRodrigo** [Megabit/Blazorise#667]
First of all, thank you for the awesome library.
I'm starting with Blazor now and your library helped me so much!

I'm interesting in using Blazorise with Open Iconic.
I've already forked the repository and started working on a pull request.

My question is: there're any intention from you're part in including support for Open Iconic?
If yes, then we have to chose how to integrate the icons on Blazorise.

Open Iconic have several diferent ways to use it's icons (SVG, SVG Sprite, Font, Bootstrap, Foundation). [Documentation](https://useiconic.com/open#reference)

My original ideia was to use the Font options (like FontAwesome), but than occured me: Blazorise has support for Bootstrap, so, maybe we could use the Bootstrap Font?

Anyway, I'm very interested in helping bring this feature to life :)

Let known if you have any options on this.

Thanks :)

**Comment by stsrki** [comment]
Hi @cabralRodrigo 

I'm still trying to find time to finish current icon implementation for FontAwesome and Material that @WillianGruber has done in #36. He merged all icons names under one excel file so all I need to do now is to include them in source. So if you are planning to create new icon provider please keep in mind that list and try to synchronize with it if possible.

Now back to your question. Yes, I always plan to add more packages but Blazorise being an open-source project that I do in my spare time it's hard to find time for everything. So I need to prioritize. Currently I'm finishing new provider for AntDesign so I can release it in new v0.9. After that we'll see, maybe I'm finally going to do the proper merging of icon names.

**Comment by WillianGruber** [comment]
I was able to use material icons in the blazorise components as they are made, and fa icons in my own components. Works well for me. I installed both packages but only referenced one in the static files, so it worked.

**Comment by stsrki** [comment]
Closing as we don't have plans to expand icons atm.
