### ISSUE TITLE
[Feature] Full featured work with DataTable in DataGrid 

### ISSUE THREAD

**Issue by TPIvan** [Megabit/Blazorise#701]
**Is your feature request related to a problem? Please describe.**
`DataGrid `is very useful and simple to use when working with strongly typed collection of objects. Sometimes (e.g. user configurable reports) is useful to use a simple (old?) [DataTable ](https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable?view=netcore-3.1) or [DataView](https://docs.microsoft.com/en-us/dotnet/api/system.data.dataview?view=netcore-3.1). 
Both can be used in `Data` property of `DataGrid`. But through Field is possible to access `DataRow` properties not the `DataTable` columns. When I use a column name I get: 

     System.ArgumentException: 'col1' is not a member of type 'System.Data.DataRowView' (Parameter 'propertyOrFieldName')
        at System.Linq.Expressions.Expression.PropertyOrField(Expression expression, String propertyOrFieldName)
        at Blazorise.DataGrid.Utils.FunctionCompiler.GetSafeField(Expression item, String fieldName)
        at Blazorise.DataGrid.Utils.FunctionCompiler.CreateValueGetter[TItem](String fieldName)

**Describe the solution you'd like**
The solution would be that for `DataRowView` or `DataRow` objects the component would use `Item[Field]` instead of `Item.Field`. My estimation from quick look to [FunctionCompiler.cs](https://github.com/stsrki/Blazorise/blob/master/Source/Extensions/Blazorise.DataGrid/Utils/FunctionCompiler.cs) is that simple decision by type in `CreateValueGetter` could do the job. WPF or WebForms `GridView` probably do similar decision because they are both able to use collection as well as `DataTable`. 

### Additional context
DataTable has a collection of `DataRow`s which can be accessed strongly typed through extension method `.AsEnumerable()`. `DataView` is a collection of DataRowView but is necessary to use `.Cast<DataRowView>`
Code Sample (a dummy property is used so no sorting or filtering is available):  

      <DataGrid Data="dataView.Cast<DataRowView>()" TItem="DataRowView" IsBordered="true"
                  IsHoverable="true" ShowPager="true">
            <DataGridColumn TItem="DataRowView" Caption="col1" Field="@nameof(DataRowView.RowVersion)" Context="item">
                <DisplayTemplate>
                    @($"{item["col1"]}")
                </DisplayTemplate>
            </DataGridColumn>
            <DataGridColumn TItem="DataRowView" Caption="col2" Context="item" Field="@nameof(DataRowView.RowVersion)">
                <DisplayTemplate>
                    @($"{item["col2"]}")
                </DisplayTemplate>
            </DataGridColumn>
        </DataGrid>
        
            @code {
                DataTable myTable;
                DataView dataView;
                protected override void OnInitialized()
                {
                    base.OnInitialized();
                    myTable = new DataTable();
                    myTable.Columns.Add("col1", typeof(string));
                    myTable.Columns.Add("col2", typeof(string));
                    myTable.Rows.Add("a1", "bb");
                    myTable.Rows.Add("a2", "cc");
                    dataView = myTable.DefaultView;
                }
            }
And I Imagine that the Grid markup will be

        <DataGrid Data="dataView.Cast<DataRowView>()" TItem="DataRowView" IsBordered="true"
                  IsHoverable="true" ShowPager="true">
            <DataGridColumn TItem="DataRowView" Caption="col1" Field="col1"/>      
            <DataGridColumn TItem="DataRowView" Caption="col2" Context="item" Field="col2" />
        </DataGrid>

**Comment by vstribrny** [comment]
Please do not make such hacks like adding condition on DataTable/DataView into this awesome project.

The support in WPF/WinForms for `DataTable/DataView` is achieved by general mechanism present in `System.ComponentModel` namespace - the beasts like `MarshalByValueComponent`, `IListSource` or `PropertyDescriptor` base classes actually do the job. I would really not include this super-legacy stuff in Blazorise, it would make the "binding" system very complicated.

But we have a solution here I think - actually the same that is used in WPF, UWP or Xamarin - and it is ability to **bind to string indexer** (string-indexed properties). It is general mechanism that is great for any kind of dynamic data sources. And, as `DataRowView` also contains string indexer, it will do the job also for DataTable/DataView

Proposed binding syntax is `[FirstName]`, which is commonly used (in WPF, UWP or Xamarin at least), so it would be like Field="[FirstName]".

What do you think?

**Comment by stsrki** [comment]
To answer both of you. Currently I don't have any plans to add support for DataTable or DataView. I have personaly worked with DataTables many times and while I understand it's for legacy support I think it's better to focus on going with models as classes.

Technically I believe it could be done by abstracting field getters and setters. But I need to investigate more about this. Don't want to promise anything. So to summarize, I will put this on backlog but don't expect to be it any time soon.

**Comment by 199621616** [comment]
本不想现在提出昨天刚刚形成的一个想法，肯定在1.0以前stsrki不可能考虑的问题。可是今天看到这个问题，就顺便写在这里，供stsrki以后参考。
将来可绑定到List<dynamic>，各字段使用Field = “FirstName”或者  Field = xm.FirstName   (dynamic xm),将会极大的简化开发过程。
感谢stsrki带来这么好的工具，祝健康快乐！
