### ISSUE TITLE
Bar component is missing Color property

### ISSUE THREAD

**Issue by MattFromGer** [Megabit/Blazorise#772]
The Bar component is missing the Color property even though the documentation says so. Should be a quick fix :)

**Comment by stsrki** [comment]
It's typo. Thank you for notice.

**Comment by MattFromGer** [comment]
By the way, why are there no Color/Background properties on more/all elements? Wouldn't it be useful to add this to the BaseComponent, so it's easier to go hand in hand with theming?

**Comment by stsrki** [comment]
Not all components need variant colors like primary, secondary, danger, etc. Also I try to be as close to original colors for Bootstrap, Bulma and other frameworks.

**Comment by MattFromGer** [comment]
Understand, thanks for the quick answer.
