### ISSUE TITLE
Show DataGrid Master/Detail Status of expansion/collapsion

### ISSUE THREAD

**Issue by tarafdarmansour** [Megabit/Blazorise#843]
Hi
Actually there are 3 master record type in Blazorise DataGrid with master/detail data:
1) master record without any child
2) master record with child that clicked and its detail is in view state
3) master record with child that is not clicked now and its detail row is not in view state 
Is It possible to add plus(+) and minus (-) to DataGrid in which shows status of master/detail records?
In such design there is no sign for Type 1, plus(+) sign for Type 3 and minus (-) sign for Type 2 
![Drawing1](https://user-images.githubusercontent.com/36349773/80579834-e8a57c00-8a1f-11ea-8159-3d14bc1fbb65.png)

**Comment by tarafdarmansour** [comment]
My question is vague or there is no answer ?!

**Comment by stsrki** [comment]
I am really sorry. There was so many emails lately that I completelly missed this one. Currently I'm out so I will look at it in detail when I return home.

**Comment by stsrki** [comment]
We now have a new DataGrid APIs that can be used to support this custom behavior. Closing now.
