### ISSUE TITLE
DataGrid : Support rapid editing | "Bulk Edit" & Batch Insert/Save

### ISSUE THREAD

**Issue by cowsen** [Megabit/Blazorise#855]
There are applications such as selecting checkboxs or entering quantities across multiple rows, where having to click save after every entry is inefficient.   There are several alternatives:  Some libraries support batch editing.  I have written code at a low level catching change events at a row or even cell level and responding to them.  Any help would open up new applications for your Datagrid component.

**Comment by WillianGruber** [comment]
Mass editing the datagrid is an old need, #266 .

**Comment by cowsen** [comment]
I am not suggesting a spreadsheet like datagrid, which might introduce control issues.  I am suggesting a batch edit datagrid.  A quick Google search suggest it is supported in on Syncfusion, Telerik, EJ2 etc.

**Comment by stsrki** [comment]
I would say it's doable. From what I can see, DataGrid will need to have some refactoring to make it work. For now I will leave at backlog planning stage as I'm currently focused on other things.

**Comment by cowsen** [comment]
Thank you.

**Comment by mtbayley** [comment]
I was going to create a new enhancement, but I'll bump this one :

It would be really nice if I could batch inline edit in a data grid.
I.e.

- If I'm editing a cell and hit **Tab** it will start editing the cell to the **Right**.
- If I'm editing a cell and hit **Shift+Tab** it will start editing the cell to the **Left**.
- If I'm editing a cell and hit **Enter** it will start editing the cell **Below**.
- If I'm editing a cell and hit **Shift+Enter** it will start editing the cell **Above**.

Also would be nice to either save all changes as batch, or save when exiting row.

**Comment by oaldrian** [comment]
also bumping this issue 👍

**Comment by David-Moreira** [comment]
Hello,
Moving this up.
We'll attempt bulk edit and evaluate @mtbayley shortcut suggestions for the next **v1.4**.
