### ISSUE TITLE
Tab bottom border should not appear in vertical modes

### ISSUE THREAD

**Issue by WillianGruber** [Megabit/Blazorise#887]
Tab bottom border should not appear in vertical modes.
It is nice for horizontal tabs, but strange for vertical ones:
![image](https://user-images.githubusercontent.com/56033692/81880308-9ad25d00-9563-11ea-814e-dd32d01169e6.png)
https://materialdemo.blazorise.com/tests/tabs

**Comment by WillianGruber** [comment]
Actually, in vertical tabs the line is separating the tabs from the contents. In vertical tabs it should be vertical too, separating them, shouldn't it?

![image](https://user-images.githubusercontent.com/56033692/81880643-5bf0d700-9564-11ea-95a9-c4ee1669a8f0.png)
Forgive my mspaint skills...

**Comment by stsrki** [comment]
You're right, the best option is to have the side border for vertical tabs. Your MSPaint skills are good enough :)

**Comment by stsrki** [comment]
Fixed already.
