### ISSUE TITLE
blazor-error-ui

### ISSUE THREAD

**Issue by imtrobin** [Megabit/Blazorise#911]
Hi, one of things that is good that there is a default blazor-error-ui that trap unhandled exception (until there's a better way from blazor)

Since the recommendation is remove default .css, is there something similar in blazorise? This is used in blazor.webassembly.js

**Comment by stsrki** [comment]
I must admit I wasn't aware of "blazor-error-ui". Obviously this one should be left in `site.css` if it's needed. But I might also consider creating a Blazorise component around it. Thanks for letting me know!

**Comment by stsrki** [comment]
Blazor will have better error handling in .Net 6 so this feature will not be needed. Closing now.
