### ISSUE TITLE
LineChart streaming freeze

### ISSUE THREAD

**Issue by stevemonaco** [Megabit/Blazorise#925]
When mousing over data points to show labels, the LineChart will freeze its rendering despite receiving new data points. The LineChart will refresh when a different point is hovered. The issue is intermittent and may take a couple reloads to reproduce. I could not produce the same freezing behavior in the streaming bar charts.

**To Reproduce**
1. Go to any Blazorise online demo (tested with all available Blazorise CSS framework targets)
2. Click on Extensions -> Live Charts
3. Begin hovering data points on the streaming LineCharts. Move mouse off of chart.
4. You will see the LineChart cease to render, however new points are being calculated in the background.

**Additional context**
I am experimenting with LineChart streaming in a Blazor WASM app and the same behavior is present using Blazorise 0.9.0.3. Explicitly adding the Type to YAxes (not present in the Blazorise demo) seemed to make the issue less frequent, yet it still persists.

```cs
Scales = new
{
	YAxes = new object[]
	{
		new {
			Type = "linear",
			ScaleLabel = new {
			Display = true, LabelString = "value" }
		}
	}
},
```

**Comment by stsrki** [comment]
Fixed with new v3 charts support.
