### ISSUE TITLE
Background image in theme

### ISSUE THREAD

**Issue by imtrobin** [Megabit/Blazorise#931]
Hi, I want to use background image in theme instead of default white color. I tried setting the css in App or b_body_layout but it seems to be overwritten. How should I be doing it? It will be good if I can use it in Background themes too.

**Comment by stsrki** [comment]
Currently Blazorise doesn't set background images for a page or a document. I plan to add that feature in the future, but for now you need to do that part by yourself. Example: https://www.w3schools.com/html/html_images_background.asp

**Comment by imtrobin** [comment]
Thanks, I know what's the bug. It seems the browser is caching old copies, I need to clear the browser cache and full rebuild to see the changes.

Looking forward to the feature

**Comment by stsrki** [comment]
We added support for body colors through theming but for images, we don't have plans. So the only way is to use custom CSS.

Closing now.
