### ISSUE TITLE
No vertical scroll bar when navigating from modal window

### ISSUE THREAD

**Issue by intiharj** [Megabit/Blazorise#986]
The browser's vertical scrollbar does not appear when navigating to a page from a modal window.
Instructions are in the attached example project.  If you use the link to the weather page from the modal window, the weather page will not have a vertical scroll bar.  If you then refresh the weather page, you will see the scrollbar.  Was able to repro this using edge, firefox, and chrome.

[BlazorApp14.zip](https://github.com/stsrki/Blazorise/files/4784364/BlazorApp14.zip)

**Comment by stsrki** [comment]
I think this is fixed with #483 and is going to be released probably this week.

**Comment by intiharj** [comment]
That's great.  One thing: I read #483 (sorry I didn't find it before), and noticed that NavigationManager was used.  In the scenario I posted, I just used an anchor tag <a>.  I see your Modal.Dispose override in branch dev091.  Will I need to explicitly call Dispose, or does the framework handle that?  Thank you.

**Comment by stsrki** [comment]
The framework will make sure it is disposed properly.
